// Author: Andrew Fisher. Read-only navigation audit of the public page.
const fs=require('fs'),path=require('path'),Module=require('module'),assert=require('assert/strict');
const output=process.env.EVIDENCE_DIR||'/tmp/gc500-timeline968';fs.mkdirSync(output,{recursive:true});
const tool=path.resolve(__dirname,'../toolchain/harness'),hp=tool+'/open_page.js',fetcher=require(tool+'/curlfetch'),native=fetcher.curlFetch;let version;
fetcher.curlFetch=async(url,headers,method,body)=>{assert.equal(method,'GET');const r=await native(url,headers,method,body);if(new URL(url).pathname==='/api/state')version=JSON.parse(r.body).version;return r;};
const m=new Module(hp,module);m.filename=hp;m.paths=Module._nodeModulePaths(path.dirname(hp));m._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;'),hp);
(async()=>{const h=await m.exports.open({pageFile:process.env.PAGE||null,hash:'#day/2026-10-13',W:390,H:844,mobile:true});const p=h.page,result={};try{
await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:120000});await p.locator('#pane-timeline [data-day-step="1"]').waitFor({state:'visible',timeout:90000});await p.waitForTimeout(300);
const read=()=>p.evaluate(()=>{const main=document.querySelector('main'),pane=document.getElementById('pane-timeline');return {hash:location.hash,day:state.day,scroll:main.scrollTop,height:main.scrollHeight,width:document.documentElement.scrollWidth,inner:innerWidth,rows:[...pane.querySelectorAll('[data-tl846-load]')].map(n=>({id:n.dataset.tl846Load,top:n.getBoundingClientRect().top,height:n.getBoundingClientRect().height})),facts:[...pane.querySelectorAll('[data-r931-load]')].map(n=>({id:n.getAttribute('data-r931-load'),facts:[...n.querySelectorAll('.r931-fact')].filter(f=>/\b(?:mm|kg)\b/.test(f.querySelector('strong')?.textContent||'')).map(f=>({label:f.querySelector('span').textContent,value:f.querySelector('strong').textContent}))})),steps:[...pane.querySelectorAll('[data-day-step],.timeline968-days [data-day]')].map(n=>({label:n.innerText,top:n.getBoundingClientRect().top,left:n.getBoundingClientRect().left})),summaryText:[...pane.querySelectorAll('[data-r931-load]')].map(n=>n.innerText)};});
const initial=await p.evaluate(()=>JSON.stringify(S));const models=await p.evaluate(()=>{const d=programmeDays().find(x=>x.iso==='2026-10-13'),g=dpLoads(d);return JSON.stringify({products:g.map(x=>Loading931.loadProducts931(x)),prints:g.map((x,i)=>Loading931.printPages(d,x,i+1)),charges:allAssets().map(a=>chargeLines(a)),programmes:programmeDays()});});
result.before=await read();await p.screenshot({path:output+'/phone-before-top.png'});await p.locator('#pane-timeline [data-tl846-load]').first().scrollIntoViewIfNeeded();await p.screenshot({path:output+'/phone-before-load.png'});
assert.equal(await p.evaluate(()=>typeof TimelineFlow968),'undefined','Run against the predecessor; this test injects the candidate presentation once.');await p.addStyleTag({path:path.join(__dirname,'timeline968.css')});await p.addScriptTag({path:path.join(__dirname,'timeline968.js')});await p.evaluate(()=>document.querySelector('main').scrollTop=0);result.after=await read();
assert.deepEqual(result.after.rows.map(r=>r.id),result.before.rows.map(r=>r.id));assert.deepEqual(result.after.facts,result.before.facts);assert(result.after.height<result.before.height);assert.equal(result.after.width,390);assert.equal(new Set(result.after.steps.map(x=>x.top)).size,1);
assert.equal(await p.locator('#pane-timeline details[data-timeline968-more][open]').count(),0);assert.equal(await p.locator('#pane-timeline .timeline908-plans:not([data-timeline968-controls]) > details.loading872').count(),0);assert.equal(await p.locator('#pane-timeline > .rochip details[open]').count(),0);assert((await p.locator('#pane-timeline > .rochip summary').innerText()).includes('View only'));await p.evaluate(()=>applyCapability());assert.equal(await p.locator('#pane-timeline > .rochip details[open]').count(),0);assert.equal(await p.locator('#pane-timeline details[data-timeline968-more]').count(),result.before.facts.length);assert(result.after.summaryText.every(t=>!t.includes('Waste tanks empty.')&&!t.includes('Guide model figures are reference values;')));
await p.screenshot({path:output+'/phone-after-top.png'});await p.locator('#pane-timeline [data-tl846-load]').first().scrollIntoViewIfNeeded();await p.screenshot({path:output+'/phone-after-load.png'});await p.locator('#pane-timeline .timeline968-loading').first().screenshot({path:output+'/phone-data-panel.png'});
const first=p.locator('#pane-timeline details[data-timeline968-more]').first();const key=await first.getAttribute('data-timeline968-more');await first.locator(':scope > summary').click();await p.waitForFunction(k=>[...document.querySelectorAll('[data-timeline968-more]')].find(x=>x.getAttribute('data-timeline968-more')===k)?.open,key);const moreScroll=await p.evaluate(()=>document.querySelector('main').scrollTop);await p.evaluate(()=>renderTimeline());assert.equal(await first.evaluate(n=>n.open),true);assert(Math.abs(await p.evaluate(()=>document.querySelector('main').scrollTop)-moreScroll)<=2);assert(await first.locator('[data-timeline968-controls]').count());await p.screenshot({path:output+'/phone-more-info.png'});await p.evaluate(()=>render());assert.equal(await first.evaluate(n=>n.open),true);
await p.locator('#pane-timeline [data-day-step="1"]').click();await p.locator('#pane-timeline [data-day-step="-1"]').click();assert.equal(await first.evaluate(n=>n.open),true);
await p.evaluate(()=>{location.hash='#plant';});await p.locator('#pane-plant').waitFor({state:'visible'});await p.evaluate(()=>{location.hash='#day/2026-10-13';});await p.locator('#pane-timeline').waitFor({state:'visible'});assert.equal(await first.evaluate(n=>n.open),true);
await first.locator(':scope > summary').click();await p.waitForFunction(k=>![...document.querySelectorAll('[data-timeline968-more]')].find(x=>x.getAttribute('data-timeline968-more')===k)?.open,key);await p.evaluate(()=>renderTimeline());assert.equal(await first.evaluate(n=>n.open),false);
const progress=p.locator('#pane-timeline [data-tl841-open]').first();await progress.scrollIntoViewIfNeeded();const returnScroll=await p.evaluate(()=>document.querySelector('main').scrollTop);await progress.click();result.dialog=await p.locator('dialog').innerText();assert(result.dialog.includes('Back'));await p.locator('[data-tl841-close]').click();assert.equal(await p.evaluate(()=>document.querySelector('main').scrollTop),returnScroll);
result.modelsUnchanged=await p.evaluate(x=>{const d=programmeDays().find(x=>x.iso==='2026-10-13'),g=dpLoads(d);return JSON.stringify({products:g.map(x=>Loading931.loadProducts931(x)),prints:g.map((x,i)=>Loading931.printPages(d,x,i+1)),charges:allAssets().map(a=>chargeLines(a)),programmes:programmeDays()})===x;},models);assert(result.modelsUnchanged);
result.renderTimes=await p.evaluate(()=>{const times=[];for(let i=0;i<3;i++){let s=performance.now();renderTimeline();times.push(performance.now()-s);}return times;});
await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>{render();document.querySelector('main').scrollTop=0;});result.desktop=await read();assert.equal(result.desktop.width,1440);await p.screenshot({path:output+'/desktop-after.png'});
result.recordUnchanged=await p.evaluate(x=>JSON.stringify(S)===x,initial);assert(result.recordUnchanged);result.nativeVersion=version;result.pageErrors=h.errors;assert.deepEqual(h.errors,[]);fs.writeFileSync(output+'/native-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({nativeVersion:version,unchanged:result.recordUnchanged,modelsUnchanged:result.modelsUnchanged,loads:result.before.rows.length,heights:[result.before.height,result.after.height],firstLoadHeights:[result.before.rows[0].height,result.after.rows[0].height],renderTimes:result.renderTimes,errors:h.errors}));
}finally{await h.browser.close();}})().catch(e=>{console.error(e.stack);process.exitCode=1});
