// Author: Andrew Fisher. Focused read-only Option A checks against native load data.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {installWriteGuard,ready840,nativeSnapshot}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const {open}=require(path.join(process.env.GC500_TOOLCHAIN||path.join(__dirname,'../toolchain'),'harness/open_page.js'));
const {PAGE,OUT,CANDIDATE_SHA}=process.env;if(!PAGE||!OUT||!CANDIDATE_SHA)throw Error('PAGE, OUT and frozen CANDIDATE_SHA are required');
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');if(sha(fs.readFileSync(PAGE))!==CANDIDATE_SHA)throw Error('Candidate changed');
fs.mkdirSync(OUT,{recursive:true});const guard=installWriteGuard(),report={author:'Andrew Fisher',sha:CANDIDATE_SHA,checks:[],views:[]};let session;
const check=(name,ok,evidence)=>{report.checks.push({name,ok:!!ok,evidence});if(!ok)console.log('FAIL '+name);};
const save=()=>fs.writeFileSync(path.join(OUT,'timeline846.json'),JSON.stringify(report,null,2));
(async()=>{try{
for(const view of [{name:'laptop',W:1366,H:900},{name:'phone',W:390,H:844,dpr:2,mobile:true},{name:'4k',W:3840,H:2160}].filter(v=>!process.env.VIEWS||process.env.VIEWS.split(',').includes(v.name))){
  session=await open({...view,pageFile:PAGE,hash:'#timeline'});const p=session.page;await ready840(p,false);
  const before=await nativeSnapshot(p);
  const expected=await p.evaluate(()=>{const d=programmeDays().filter(d=>d.deliveries.length).sort((a,b)=>b.deliveries.length-a.deliveries.length)[0];state.q='';state.disc=null;state.light=null;state.day=d.iso;state.tlView='day';go('timeline');setHash('day/'+d.iso);render();return {day:d.iso,loads:['deliveries','removals'].flatMap(kind=>ldGroups(d,d[kind],kind).map(({g,n})=>({id:ldId(d,g),kind,n,keys:g.rows.map(r=>r.a.key),stages:g.rows.map(r=>timeline841State(r.a).stage),time:g.time,carrier:g.carrier,url:(()=>{const x=ldGoTarget751(g);return x?navUrl(x.t.ll):null;})()})))};});
  await p.waitForSelector('#pane-timeline .tl846');await p.waitForTimeout(350);
  const actual=await p.evaluate(()=>{const pane=document.querySelector('#pane-timeline'),main=document.querySelector('main');return {page:document.documentElement.scrollWidth,width:innerWidth,main:[main.scrollWidth,main.clientWidth],pane:[pane.scrollWidth,pane.clientWidth],nested:pane.querySelectorAll('button button,button a').length,loads:[...pane.querySelectorAll('[data-tl846-load]')].map(n=>({id:n.dataset.tl846Load,keys:[...n.querySelectorAll('[data-tl846-ref]')].map(r=>r.dataset.tl846Ref),stages:[...n.querySelectorAll('.tl841-gantry')].map(r=>+r.dataset.tl841Stage),five:[...n.querySelectorAll('.tl841-gantry')].map(r=>r.querySelectorAll('.tl841-unit').length),qr:n.querySelector('.ld-qr')?.getAttribute('href')||null,nav:n.querySelector('.ld-nav')?.getAttribute('href')||null,prints:[...n.querySelectorAll('[data-tl841-print]')].map(b=>({day:b.dataset.tl841Print,only:+b.dataset.tl841Only})),progress:[...n.querySelectorAll('[data-tl841-open]')].map(b=>b.dataset.tl841Open),text:n.textContent,scroll:n.scrollWidth,client:n.clientWidth,headings:[...n.querySelectorAll('.tl846-name,.ld-c>b')].map(h=>{const s=getComputedStyle(h);return {size:parseFloat(s.fontSize),style:s.fontStyle,filter:s.filter,shadow:s.textShadow};}),controls:[...n.querySelectorAll('button,a')].map(b=>({w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height})),labels:[...n.querySelectorAll('.tl841-unit small')].map(e=>({text:e.textContent,w:e.scrollWidth,c:e.clientWidth}))})),supplier:!!pane.querySelector('#ep819')};});
  report.views.push({view,expected,actual});
  check(view.name+' exact native load and reference coverage',actual.loads.length===expected.loads.length&&expected.loads.every(e=>{const a=actual.loads.find(a=>a.id===e.id);return a&&JSON.stringify(a.keys)===JSON.stringify(e.keys)&&JSON.stringify(a.stages)===JSON.stringify(e.stages);}),{expected:expected.loads,actual:actual.loads});
  check(view.name+' five original lamps for every reference',actual.loads.every(l=>l.five.every(n=>n===5)));
  check(view.name+' native QR destination and navigation match',expected.loads.every(e=>{const a=actual.loads.find(a=>a.id===e.id);return a&&a.qr===e.url&&a.nav===e.url;}));
  check(view.name+' exact native Progress and print scopes retained',expected.loads.every(e=>{const a=actual.loads.find(a=>a.id===e.id);return a&&(e.kind==='deliveries'?JSON.stringify(a.progress)===JSON.stringify(e.keys)&&a.prints.length===1&&a.prints[0].day===expected.day&&a.prints[0].only===e.n-1:a.prints.length===0);}));
  check(view.name+' timed and carrier values remain visible',expected.loads.every(e=>{const a=actual.loads.find(a=>a.id===e.id);return a&&(!e.time||a.text.includes(e.time))&&(!e.carrier||a.text.includes(e.carrier));}));
  check(view.name+' natural fit and no nested actions',actual.page<=actual.width+1&&actual.main[0]<=actual.main[1]+1&&actual.pane[0]<=actual.pane[1]+1&&actual.loads.every(l=>l.scroll<=l.client+1)&&actual.nested===0,actual);
  check(view.name+' readable upright names and full stage labels',actual.loads.every(l=>l.headings.every(h=>h.size>=22&&h.style==='normal'&&h.filter==='none'&&h.shadow==='none')&&l.labels.every(x=>x.w<=x.c+1)),actual.loads.map(l=>({id:l.id,headings:l.headings,labels:l.labels})));
  check(view.name+' controls retain 44px touch height',actual.loads.every(l=>l.controls.every(b=>b.h>=44&&b.w>=44)),actual.loads.map(l=>({id:l.id,controls:l.controls})));
  check(view.name+' native supplier section remains available',actual.supplier);
  const first=p.locator('#pane-timeline .tl846').first();await first.scrollIntoViewIfNeeded();await p.screenshot({path:path.join(OUT,'timeline846-'+view.name+'.png')});
  const toggle=first.locator('.ldl'),id=await toggle.getAttribute('data-ld');await toggle.click();await p.waitForFunction(id=>{const b=[...document.querySelectorAll('.ldl')].find(n=>n.dataset.ld===id);return b?.getAttribute('aria-expanded')==='true'&&document.getElementById(b.getAttribute('aria-controls'));},id);check(view.name+' native load expansion still owns its delivery cards',true);await p.locator('[data-ld='+JSON.stringify(id)+']').click();
  const progress=p.locator('#pane-timeline .tl846 [data-tl841-open]').first(),key=await progress.getAttribute('data-tl841-open');await progress.click();await p.locator('#timeline841-dialog').waitFor({state:'visible'});check(view.name+' native Progress opens the correct reference',await p.locator('#timeline841-heading').textContent()===key);check(view.name+' readonly Progress offers no write controls',await p.locator('#timeline841-dialog [data-tl841-set]').count()===0);await p.keyboard.press('Escape');await p.waitForFunction(key=>document.activeElement?.dataset.tl841Open===key,key);check(view.name+' native close restores Progress focus',true);
  const after=await nativeSnapshot(p);check(view.name+' records and media unchanged',JSON.stringify(before.collections)===JSON.stringify(after.collections)&&JSON.stringify(before.media)===JSON.stringify(after.media));check(view.name+' no runtime errors',session.errors.length===0,session.errors);await session.browser.close();session=null;save();
}
}catch(e){check('Timeline browser execution',false,e.stack);}finally{if(session)await session.browser.close();await guard.closeAll();check('Candidate bytes unchanged',sha(fs.readFileSync(PAGE))===CANDIDATE_SHA);check('No operational write attempts',!guard.nonGetSeen.some(r=>r.operational),guard.nonGetSeen);report.guard=guard;report.passed=report.checks.filter(c=>c.ok).length;report.total=report.checks.length;save();console.log(JSON.stringify({passed:report.passed,total:report.total,sha:CANDIDATE_SHA}));if(report.passed!==report.total)process.exitCode=1;}})();
