/* Author: Andrew Fisher. Portable synthetic fixtures; no private source values. */
const fs=require('fs'), path=require('path'), vm=require('vm'), assert=require('assert/strict');
const context={}; vm.createContext(context); vm.runInContext(fs.readFileSync(path.join(__dirname,'../building_transport831.js'),'utf8'),context);
const model=x=>JSON.parse(JSON.stringify(context.buildingTransport831(x)));
const b=(patch={})=>Object.assign({id:'B-A',ref:'A',item:'Building 6m',quantity:1,numbers:[],branch:'TEST',contracts:['C-A'],lineKeys:['C-A|1'],rate:120,rateSource:'synthetic current card',holdReasons:[]},patch);
const c=(patch={})=>Object.assign({id:'C-A|90',contract:'C-A',lineKeys:['C-A|1'],leg:'delivery',quantity:1,quantityBasis:'units',amount:60,scope:'exact'},patch);
let count=0;
const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
test('two explicit legs, missing asset number allowed',()=>assert.equal(model({buildings:[b()]}).uncoveredAdditional,240));
test('does not mutate inputs',()=>{const x={buildings:[b()],coverage:[c()]},s=JSON.stringify(x);model(x);assert.equal(JSON.stringify(x),s);});
test('own use, cancelled, rest-of and zero excluded',()=>{const x=model({buildings:[b({id:'a',exclusion:'Own use'}),b({id:'b',exclusion:'Cancelled'}),b({id:'c',exclusion:'Rest-of'}),b({id:'d',quantity:0})]});assert.equal(x.uncoveredAdditional,0);assert.equal(x.excluded,4);});
test('missing quantity held, never default one',()=>{for(const quantity of [null,undefined,-1,1.5])assert.equal(model({buildings:[b({quantity})]}).uncoveredAdditional,0);});
test('missing rate held',()=>{const x=model({buildings:[b({rate:null})]});assert.equal(x.held,1);assert.equal(x.uncoveredAdditional,0);});
test('explicit zero rate is readable',()=>assert.equal(model({buildings:[b({rate:0})]}).held,0));
test('exact lower priced leg replaces estimate with no top-up',()=>assert.equal(model({buildings:[b()],coverage:[c()]}).uncoveredAdditional,120));
test('higher priced leg still replaces estimate',()=>assert.equal(model({buildings:[b()],coverage:[c({amount:900})]}).uncoveredAdditional,120));
test('explicit included zero leg replaces estimate',()=>assert.equal(model({buildings:[b()],coverage:[c({amount:0})]}).uncoveredAdditional,120));
test('both covered legs never added again',()=>{const x=model({buildings:[b()],coverage:[c(),c({id:'C-A|91',leg:'pickup'})]});assert.equal(x.uncoveredAdditional,0);assert.equal(x.coveredEstimate,240);});
test('quantity two delivery is two units not two directions',()=>assert.equal(model({buildings:[b({quantity:2})],coverage:[c({quantity:2})]}).uncoveredAdditional,240));
test('one unit partly covered from two',()=>assert.equal(model({buildings:[b({quantity:2})],coverage:[c()]}).uncoveredAdditional,360));
test('two-way one-unit contract quantity two consumed once',()=>assert.equal(model({buildings:[b()],coverage:[c({leg:'both',quantity:2,quantityBasis:'total-legs'})]}).uncoveredAdditional,0));
test('ambiguous both-way quantity held',()=>assert.equal(model({buildings:[b()],coverage:[c({leg:'both',quantityBasis:'unknown'})]}).uncoveredAdditional,0));
test('null contract amount holds direction, does not become zero',()=>{const x=model({buildings:[b()],coverage:[c({amount:null})]});assert.equal(x.uncoveredAdditional,120);assert.equal(x.rows[0].state,'held');});
test('same demand identity does not duplicate',()=>assert.equal(model({buildings:[b(),b()]}).uncoveredAdditional,240));
test('conflicting demand identity held',()=>assert.equal(model({buildings:[b(),b({quantity:2})]}).uncoveredAdditional,0));
test('same contract row consumed once',()=>assert.equal(model({buildings:[b({quantity:2})],coverage:[c(),c()]}).uncoveredAdditional,360));
test('shared active number held, unrelated reference retained',()=>{const x=model({buildings:[b({numbers:['UNIT-A']}),b({id:'B-B',ref:'B',numbers:['UNIT-A']}),b({id:'B-C',ref:'C'})]});assert.equal(x.held,2);assert.equal(x.uncoveredAdditional,240);});
test('cancelled number does not block active reference',()=>assert.equal(model({buildings:[b({numbers:['UNIT-A']}),b({id:'B-B',ref:'B',numbers:['UNIT-A'],exclusion:'Cancelled'})]}).uncoveredAdditional,240));
test('excess numbers hold without increasing asked quantity',()=>{const x=model({buildings:[b({numbers:['UNIT-A','UNIT-B']})]});assert.equal(x.rows[0].quantity,1);assert.equal(x.held,1);assert.equal(x.uncoveredAdditional,0);});
test('unallocated contract charge holds affected subset only',()=>{const x=model({buildings:[b(),b({id:'B-B',ref:'B',contracts:['C-B'],lineKeys:['C-B|1']})],coverage:[c({scope:'unallocated',lineKeys:[],leg:null})]});assert.equal(x.uncoveredAdditional,240);assert.equal(x.held,1);});
test('unknown contract branch charge holds branch only',()=>{const x=model({buildings:[b(),b({id:'B-B',ref:'B',branch:'OTHER'})],coverage:[c({contract:'',branch:'TEST',scope:'unallocated',lineKeys:[],leg:null})]});assert.equal(x.uncoveredAdditional,240);});
test('known nonbuilding transport never subtracted',()=>assert.equal(model({buildings:[b()],coverage:[c({scope:'other'})]}).uncoveredAdditional,240));
test('explicit reference and conflicting contract hold that leg',()=>{const x=model({buildings:[b()],coverage:[c({contract:'C-B',ref:'A',lineKeys:[]})]});assert.equal(x.uncoveredAdditional,120);assert.equal(x.held,1);});
test('shared exact whole quantity covers once across units',()=>{const x=model({buildings:[b(),b({id:'B-B',ref:'B',lineKeys:['C-A|2']})],coverage:[c({quantity:2,lineKeys:['C-A|1','C-A|2']})]});assert.equal(x.uncoveredAdditional,240);assert.equal(x.coveredEstimate,240);});
test('partial shared charge holds exact candidates, no arbitrary allocation',()=>{const x=model({buildings:[b(),b({id:'B-B',ref:'B',lineKeys:['C-A|2']})],coverage:[c({lineKeys:['C-A|1','C-A|2']})]});assert.equal(x.uncoveredAdditional,240);assert.equal(x.held,2);});
test('rate change recalculates same demand count',()=>{const x={buildings:[b()]};assert.equal(model(x).uncoveredAdditional,240);x.buildings[0].rate=150;assert.equal(model(x).uncoveredAdditional,300);});
test('later contract entry replaces estimate',()=>{const x={buildings:[b()]};assert.equal(model(x).uncoveredAdditional,240);x.coverage=[c()];assert.equal(model(x).uncoveredAdditional,120);x.coverage.push(c({id:'C-A|91',leg:'pickup'}));assert.equal(model(x).uncoveredAdditional,0);});
test('all sums reconcile in cents',()=>{const x=model({buildings:[b({rate:100.005}),b({id:'B-B',ref:'B',branch:'OTHER',rate:0.335,quantity:3})]});assert.equal(x.uncoveredAdditional,202.04);assert.equal(Math.round(x.uncoveredAdditional*100),x.rows.reduce((s,r)=>s+Math.round(r.additional*100),0));assert.equal(Math.round(x.uncoveredAdditional*100),x.byBranch.reduce((s,r)=>s+Math.round(r.uncoveredAdditional*100),0));});
test('historical comparison amounts do not enter model',()=>{const x={buildings:[b()],historical:{invoice:999999,rate:1}};assert.equal(model(x).uncoveredAdditional,240);delete x.historical;assert.equal(model(x).uncoveredAdditional,240);});
test('HA list parsing stops before date and binds contract',()=>{const p=context.buildingTransportSource831({rental_contract:'TEST-C',description:'Delivery for HA Line Item(s) 4,7 15 Sep 2030'});assert.deepEqual(Array.from(p.lineKeys),['TEST-C|4','TEST-C|7']);assert.equal(p.leg,'delivery');});
test('explicit pickup each-way remains one named leg',()=>{const p=context.buildingTransportSource831({description:'Pickup each way per Building'});assert.equal(p.leg,'pickup');assert.equal(p.quantityBasis,'units');});
test('generic each-way total quantity is leg basis',()=>{const p=context.buildingTransportSource831({description:'Transport each way per building'});assert.equal(p.leg,'both');assert.equal(p.quantityBasis,'total-legs');});
test('package and malformed HA ranges stay qualified',()=>{assert.equal(context.buildingTransportSource831({description:'Delivery and installation package'}).package,true);assert.equal(context.buildingTransportSource831({description:'Delivery for HA Line Items 4-7'}).malformedHA,true);});
test('delivery remainder hold preserves exact covered units and pickup forecast',()=>{const x=model({buildings:[b({quantity:2,holdReasonsByLeg:{delivery:['Remaining delivery scope needs allocation']}})],coverage:[c()]});assert.equal(x.rows[0].coveredQuantity,1);assert.equal(x.rows[0].state,'held');assert.equal(x.rows[0].heldEstimate,120);assert.equal(x.rows[1].additional,240);assert.equal(x.uncoveredAdditional,240);});
test('included transport stays explicit without fabricated quantity or standalone price',()=>{const x=model({buildings:[b({included:'Transport included in hire',quantity:null,rate:null,branch:''})]});assert.equal(x.uncoveredAdditional,0);assert.equal(x.grossEstimate,0);assert.equal(x.included,1);assert.equal(x.excluded,0);assert.equal(x.held,0);assert.equal(x.rows[0].state,'included');});
console.log(JSON.stringify({author:'Andrew Fisher',passed:count}));
