/* Author: Andrew Fisher. Synthetic current projection and contract adapter checks. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../building_transport831.js'),'utf8');
const asset=(patch={})=>Object.assign({key:'X01',discipline:'Portable buildings',locations:[],asset_numbers:[],charge_lines:[{item:'Building 6m',quantity:1,priceable:true}]},patch);
const charge=(patch={})=>Object.assign({rental_contract:'TEST-C',branch_code:'TEST',line:90,kind:'transport',item:'Delivery',description:'Delivery X01',charge_line:true,quantity:1,price:70},patch);
const hire=(patch={})=>Object.assign({rental_contract:'TEST-C',branch_code:'TEST',line:1,kind:'building',asset_no:'UNIT-A',asset_no_is_plant_number:true,description:'X01 Portable Building',match:{to:'asset',key:'X01'}},patch);
function project(assets=[asset()],sources=[],options={}){
 const ctx={allAssets:()=>assets,ONHIRE_ROWS:sources,chargeLines:a=>a.charge_lines,contractOf:()=>({id:'TEST-C',ids:['TEST-C'],where:'rental'}),branchOf:()=>({code:'TEST',contracts:['TEST-C']}),qtyOf:l=>l.quantity,cardRate:()=>options.nullRate?null:{line:'Synthetic building',transport:{charge:120}},CARD_WORD:'street',contractTreatment747:r=>r.own?{kind:'own_use'}:null,contractCharge:r=>({amount:r.price==null?null:r.price*r.quantity}),tombedHere:id=>(options.tombs||[]).includes(id)};
 vm.createContext(ctx);vm.runInContext(source,ctx);const input=ctx.buildingTransportInput831();return {context:ctx,input,model:ctx.buildingTransport831(input)};
}
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
test('missing card object becomes hold without throwing',()=>{const x=project(undefined,[],{nullRate:true});assert.equal(x.model.held,1);assert.equal(x.model.uncoveredAdditional,0);});
test('nontransport charge line does not suppress transport',()=>{const x=project(undefined,[charge({kind:'labour',item:'Labour',description:'Labour X01'})]);assert.equal(x.input.coverage.length,0);assert.equal(x.model.uncoveredAdditional,240);});
test('unknown transport item is not misclassified as labour',()=>assert.equal(project(undefined,[charge({kind:null,item:'Delivery'})]).model.uncoveredAdditional,120));
test('own-use primary building excluded',()=>assert.equal(project(undefined,[hire({own:true})]).model.excluded,1));
test('own-use accessory cannot exclude customer building',()=>assert.equal(project(undefined,[hire({kind:'accessory',own:true})]).model.uncoveredAdditional,240));
test('explicit current location alias resolves one charge',()=>{const x=project([asset({locations:['X01 (Y09) - Test room']})],[charge({description:'Delivery Y09'})]);assert.equal(x.input.coverage[0].ref,'X01');assert.equal(x.model.uncoveredAdditional,120);});
test('number-bearing relocation never creates a new trip',()=>assert.equal(project([asset({relocation:true,asset_numbers:['UNIT-A']})]).model.uncoveredAdditional,0));
test('nonpriceable numeric source row held',()=>{const x=project([asset({charge_lines:[{item:'Building 6m',quantity:1,priceable:false}]})]);assert.equal(x.model.held,1);assert.equal(x.model.uncoveredAdditional,0);});
test('container and furniture are outside building scope',()=>assert.equal(project([asset({charge_lines:[{item:'Container 6m',quantity:1},{item:'Fridge',quantity:1}]})]).model.rows.length,0));
test('asked item stays basis despite larger supplied descriptor',()=>{const x=project([asset({item_types:['Building 6m'],supplied:'Building 12m'})]);assert.equal(x.model.rows[0].item,'Building 6m');assert.equal(x.model.rows[0].quantity,1);});
const swapped=[asset({asset_numbers:['UNIT-B']}),asset({key:'X02',asset_numbers:['UNIT-A']})];
const swapSources=[hire(),hire({line:2,asset_no:'UNIT-B',description:'X02 Portable Building',match:{to:'asset',key:'X02'}})];
const settled={tombs:['num/X01/UNIT-A','num/X02/UNIT-B']};
test('settled native reassignment defeats stale rental match holds',()=>{const x=project(swapped,swapSources,settled);assert.equal(x.model.uncoveredAdditional,480);assert.equal(x.model.held,0);});
test('unresolved swap held without native removal evidence',()=>assert.equal(project(swapped,swapSources).model.uncoveredAdditional,0));
test('future disputed old hire-line coverage holds affected leg',()=>{const x=project(swapped,swapSources.concat(charge({description:'Delivery for HA Line Item(s) 1'})),settled);assert.equal(x.model.uncoveredAdditional,240);assert.equal(x.model.held,2);});
test('mixed exact HA package scope stays held',()=>{const x=project([asset({asset_numbers:['UNIT-A']})],[hire(),hire({line:2,kind:'toilet',asset_no:'UNIT-T',description:'Test toilet',match:null}),charge({description:'Delivery for HA Line Item(s) 1,2'})]);assert.equal(x.model.uncoveredAdditional,120);assert.equal(x.model.rows[0].state,'held');});
test('explicit whole building HA quantity matches two asked units',()=>{const x=project([asset({charge_lines:[{item:'Building 6m',quantity:2,priceable:true}]})],[hire({quantity:2}),charge({description:'Delivery for HA Line Item(s) 1',quantity:2})]);assert.equal(x.model.uncoveredAdditional,240);assert.equal(x.model.rows[0].coveredQuantity,2);});
test('known building HA without current owner holds delivery, not assumed other scope',()=>{const x=project(undefined,[hire({match:null,asset_no:'UNMATCHED'}),charge({description:'Delivery for HA Line Item(s) 1'})]);assert.equal(x.input.coverage[0].scope,'unallocated');assert.equal(x.model.uncoveredAdditional,120);assert.equal(x.model.rows[0].state,'held');});
const demand=(family,item,ref,quantity=1)=>({id:ref+'|'+item,ref,item,family,quantity,rate:120,numbers:[],contracts:['TEST-C'],lineKeys:[],branch:'TEST',holdReasons:[]});
function combined(ds,ss){const ctx=project().context;const coverage=ctx.transportCoverage831(ds,ss,{});return ctx.buildingTransport831({buildings:ds,coverage});}
for(const [family,item,description] of [['Toilets & amenities','FWF','Portable toilet delivery'],['Access & plant','Forklift','Forklift delivery'],['Containers','Container 6m','Container pickup']]){
 test('generic '+family+' charge holds only named family and leg',()=>{const x=combined([demand(family,item,'E01',3),demand('Buildings','Building 6m','B01')],[charge({description,item:description.includes('pickup')?'Pickup':'Delivery'})]);assert.equal(x.uncoveredAdditional,600);assert.equal(x.rows.filter(r=>r.ref==='B01').every(r=>r.state==='estimate'),true);assert.equal(x.rows.filter(r=>r.ref==='E01'&&r.state==='held').length,1);});
}
test('positively other family charge leaves eligible families unchanged',()=>{const x=combined([demand('Buildings','Building 6m','B01'),demand('Toilets & amenities','FWF','W01')],[charge({description:'Scissor lift delivery'})]);assert.equal(x.uncoveredAdditional,480);assert.equal(x.held,0);});
test('HA charge quantity one cannot imply one of three units without basis',()=>{const d=demand('Toilets & amenities','FWF','W01',3);d.lineKeys=['TEST-C|1'];const x=combined([d],[hire({kind:'toilet',register_type:'FWF',description:'FWF',quantity:3}),charge({description:'Delivery for HA Line Item(s) 1'})]);assert.equal(x.uncoveredAdditional,360);assert.equal(x.rows[0].state,'held');});
test('explicit per-unit HA partial coverage remains permissible',()=>{const d=demand('Toilets & amenities','FWF','W01',3);d.lineKeys=['TEST-C|1'];const x=combined([d],[hire({kind:'toilet',register_type:'FWF',description:'FWF',quantity:3}),charge({description:'Delivery per unit for HA Line Item(s) 1'})]);assert.equal(x.uncoveredAdditional,600);assert.equal(x.rows[0].coveredQuantity,1);});
test('explicit truckload does not become repeated unit transport',()=>{const x=combined([demand('Toilets & amenities','FWF','W01',17)],[charge({description:'Delivery W01 - all 17 FWF units, one truck load'})]);assert.equal(x.uncoveredAdditional,2040);assert.equal(x.rows[0].state,'held');});
test('direct reference partial quantity without unit authority stays held',()=>{const x=combined([demand('Toilets & amenities','FWF','W01',3)],[charge({description:'Delivery W01'})]);assert.equal(x.uncoveredAdditional,360);});
test('new contract on known branch holds named family without inferring exact coverage',()=>{const x=combined([demand('Toilets & amenities','FWF','W01',3),demand('Buildings','Building 6m','B01')],[charge({rental_contract:'NEW-CONTRACT',description:'Portable toilet delivery'})]);assert.equal(x.uncoveredAdditional,600);assert.equal(x.rows.filter(r=>r.ref==='B01').every(r=>r.state==='estimate'),true);assert.equal(x.rows.find(r=>r.ref==='W01'&&r.leg==='delivery').coveredQuantity,0);});
test('new contract with wholly unallocated transport holds its branch leg',()=>{const x=combined([demand('Toilets & amenities','FWF','W01'),demand('Buildings','Building 6m','B01')],[charge({rental_contract:'NEW-CONTRACT',description:'Delivery'})]);assert.equal(x.uncoveredAdditional,240);assert.equal(x.held,2);});
console.log(JSON.stringify({author:'Andrew Fisher',passed:count}));
