/* Author: Andrew Fisher. Month-end review: evidence, forecasts and decisions stay separate. */
function acc762FmtMoney(n){ return typeof n === 'number' && Number.isFinite(n) ? n.toLocaleString('en-AU', {style:'currency',currency:'AUD',minimumFractionDigits:2,maximumFractionDigits:2}) : 'Not confirmed'; }
function acc762RowStatus(r){ return r.extra && r.extra.status || 'review'; }
function acc762RowAmount(r){ return r.candidate != null ? r.candidate : r.amount; }
function acc762People(L, month){ return (L.people || []).filter(p => p.month === month); }
function acc761Text(X){
 const L = acc761Labour(), lines = [`${DATA.event.name} · Month-end Finance review · ${X.label} · as at ${fmtDate(X.asAt)} · AUD ex GST`, 'Author: Andrew Fisher', 'Review schedule only. Source amounts are not proof of earned Revenue, unpaid invoices or a journal to post. Future work is forecast.'];
 if (X.baseplan) lines.push(`Billing snapshot: ${X.baseplan.supplied_on ? fmtDate(X.baseplan.supplied_on) : 'date not supplied'}; ${X.baseplan.billed} of ${X.baseplan.n} lines show a billed amount. Reconcile current billing before calculating unbilled Revenue.`);
 lines.push('', `REVENUE ALLOCATED TO THIS MONTH — ${acc762FmtMoney(X.revenueTotal)}`);
 X.revenue.forEach(r => lines.push(`• ${r.stream} · ${r.branch} · ${acc762FmtMoney(r.amount)} · ${acc762RowStatus(r)}. ${r.basis}. ${r.words || ''}`));
 lines.push('', `COST ESTIMATES FOR REVIEW — ${acc762FmtMoney(X.costCandidateTotal)}`);
 X.costs.forEach(r => lines.push(`• ${r.stream} · ${r.branch} · source value ${acc762FmtMoney(r.candidate)}${r.extra.unpricedCount?' — partial; unpriced sources remain':''} · invoices recorded ${acc762FmtMoney(r.invoiced)} · ${acc762RowStatus(r)}. ${r.evidence}. ${r.words || ''}`));
 lines.push('Accrual to post: not confirmed. Check work performed, invoices, payments and existing allocations first.');
 for (const [label, rows] of [['WORK NEEDING MONTH ALLOCATION', X.unallocatedRevenue || []], ['COSTS NEEDING MONTH ALLOCATION', X.unallocatedCosts || []]]) {
  if (rows.length) { lines.push('', label); rows.forEach(r => lines.push(`• ${r.stream || r.what} · ${acc762FmtMoney(acc762RowAmount(r))} · ${r.basis || r.evidence || ''}`)); }
 }
 lines.push('', 'FENCING PAYMENT AND CUSTOMER BILLING');
 (X.wip || []).forEach(w => lines.push(`${w.what}. ${w.words}.`));
 lines.push('', 'CUSTOMER CHARGE FORECAST — WHOLE JOB');
 for (const [label, g] of [['Labour Install',L.groups.install],['Cleaning',L.groups.cleaning],['Fire extinguishers',L.groups.fire_ext],['Other recorded charges',L.groups.other]]) if (g && (g.n || g.total || g.unpriced)) lines.push(`${label}: recorded ${acc762FmtMoney(g.charged)}; expected ${acc762FmtMoney(g.expected)}; to come ${acc762FmtMoney(g.tocome)}; later ${acc762FmtMoney(g.later)}; known total ${acc762FmtMoney(g.total)}${g.unpriced ? `; ${g.unpriced} unpriced lines` : ''}.`);
 lines.push(`Event people: ${acc762FmtMoney(L.scopePeople)} for ${fin745Hours(L.scopeHours || 0)}. Accommodation/travel: ${acc762FmtMoney(L.scopeSupport)}.`, `Labour-only forecast: ${acc762FmtMoney(L.labourOnlyTotal)}${!L.labourOnlyComplete?' — partial; unpriced amounts remain':''}. All listed charges: ${acc762FmtMoney(L.packageTotal)}${!L.packageComplete ? ' — partial; unpriced amounts remain' : ''}.`);
 lines.push('', `PEOPLE, DAYS AND HOURS — ${X.label}`);
 acc762People(L,X.month).forEach(p => lines.push(`${p.person} · ${p.type} · ${p.dayCount} days entered · dates ${p.dates.join(', ')} · ${fin745Hours(p.grossHours)} before breaks / ${fin745Hours(p.hours)} paid or allocation · confirmed ${fin745Hours(p.confirmedPaidHours)} / awaiting confirmation ${fin745Hours(p.pendingPaidHours)} / forecast ${fin745Hours(p.forecastPaidHours)}. Cost outlook ${p.unpricedCount===p.shifts&&p.shifts>0?'Unpriced':acc762FmtMoney(p.cost)}${p.unpriced ? `; ${fin745Hours(p.unpriced)} unpriced` : ''}.`));
 lines.push('', 'Confirm worked hours and payroll/supplier costs before allocating labour into installs. Finance journal proposals are recorded above; this screen does not post to the ledger. Paid supplier costs must not be accrued a second time.');
 return lines.join('\n');
}
function acc761Csv(X){
 const L=acc761Labour(), rows=[['Author: Andrew Fisher'],['Month-end Finance review — source values and forecasts, no automatic accrual'],['Work month',X.month],['As at',X.asAt],[],['Section','Stream','Branch','Source value AUD ex GST','Invoice amount recorded AUD','Status','Evidence','Review action']];
 X.revenue.forEach(r=>rows.push(['Revenue allocation — not verified unbilled',r.stream,r.branch,r.amount,'',acc762RowStatus(r),r.basis,r.words]));
 X.costs.forEach(r=>rows.push(['Cost review — accrual not confirmed',r.stream,r.branch,r.candidate,r.invoiced,acc762RowStatus(r),r.evidence,r.words]));
 (X.unallocatedRevenue||[]).forEach(r=>rows.push(['Recorded work — month unconfirmed',r.stream,r.branch,acc762RowAmount(r),'','unallocated',r.basis||r.evidence,r.words]));
 (X.unallocatedCosts||[]).forEach(r=>rows.push(['Cost — month unconfirmed',r.stream,r.branch,acc762RowAmount(r),'','unallocated',r.evidence||r.basis,r.words]));
 (X.wip||[]).forEach(w=>rows.push(['Payment / billing review',w.what,'','','','review','',w.words]));
 rows.push([],['Customer forecast — whole job','Kind','Recorded','Expected','To come','Later','Known total','Unpriced lines','Completeness']);
 [['Labour Install',L.groups.install],['Cleaning',L.groups.cleaning],['Fire extinguishers',L.groups.fire_ext],['Other',L.groups.other]].forEach(([name,g])=>rows.push(['Customer forecast',name,g.charged,g.expected,g.tocome,g.later,g.total,g.unpriced]));
 rows.push(['Customer forecast','Event people','','','','',L.scopePeople],['Customer forecast','Accommodation / travel','','','','',L.scopeSupport],['Customer forecast','Labour only','','','','',L.labourOnlyTotal,'',L.labourOnlyComplete?'Complete known scope':'Partial — unpriced amounts remain'],['Customer forecast','All listed charges','','','','',L.packageTotal,L.per.unpriced,L.packageComplete?'Complete known scope':'Partial — unpriced amounts remain']);
 rows.push([],['Work month','Person','Type','Dates entered','Days entered','Hours before breaks','Paid / allocation hours','Confirmed paid hours','Awaiting confirmation paid hours','Forecast paid hours','Cost outlook AUD','Unpriced paid hours']);
 (L.people||[]).forEach(p=>rows.push([p.month,p.person,p.type,p.dates.join('; '),p.dayCount,p.grossHours,p.hours,p.confirmedPaidHours,p.pendingPaidHours,p.forecastPaidHours,p.unpricedCount===p.shifts&&p.shifts>0?null:p.cost,p.unpriced]));
 rows.push([],['Accrual to post','Not confirmed — reconcile work, invoices, payments and existing allocations'],['Billing snapshot date',X.baseplan&&X.baseplan.supplied_on||'Unknown'],['Billing snapshot lines with amount',X.baseplan&&X.baseplan.billed,'of',X.baseplan&&X.baseplan.n]);
 return rows.map(r=>r.map(v=>fin745CsvCell(v==null?'':v)).join(',')).join('\r\n');
}
function acc761Html(){
 let X,L;try{X=acc761Model(acc761Month());L=acc761Labour();}catch(e){return `<section id="accruals761" class="fin745 acc761"><h2>Month-end Finance review</h2><p>The source record could not be read: ${esc(String(e.message||e))}</p></section>`;}
 const m=n=>esc(acc762FmtMoney(n)), h=n=>esc(fin745Hours(n||0)), status=r=>`<span class="acc761-b acc761-b-check">${esc(acc762RowStatus(r))}</span>`, people=acc762People(L,X.month);
 const unallocated=(X.unallocatedRevenue||[]).concat(X.unallocatedCosts||[]);
 const forecastRow=(label,g)=>`<tr><td><b>${label}</b>${g.unpriced?`<br><span class="acc761-w">${esc(g.unpriced)} unpriced lines · partial</span>`:''}</td><td class="num">${m(g.charged)}</td><td class="num">${m(g.expected)}</td><td class="num">${m(g.tocome)}</td><td class="num">${m(g.later)}</td><td class="num"><b>${m(g.total)}</b></td></tr>`;
 return `<section id="accruals761" class="fin745 acc761 nosfold" aria-labelledby="acc761Title">
 <div class="fin745-heading"><div><p class="fin745-eyebrow">MONTH-END FINANCE REVIEW · ${esc(X.label.toUpperCase())} · AUD EX GST</p><h2 id="acc761Title">Sources, forecasts and allocation checks</h2><p>Review ${esc(X.label)} against the work performed, current billing, supplier invoices and payroll. These source values do not establish an accrual or a journal to post.</p></div><div class="fin745-tools"><label for="acc761Month">Work month</label><select id="acc761Month" data-ro>${acc761Months().map(v=>`<option value="${esc(v)}"${v===X.month?' selected':''}>${esc(fin745MonthLabel(v))}</option>`).join('')}</select><div><button type="button" class="btn ghost sm" data-a761="copy">Copy for Finance</button><button type="button" class="btn ghost sm" data-a761="csv">Export review CSV</button></div></div></div>
 <div class="fin745-metrics acc761-metrics">${fin745Card('Revenue allocated to month',acc762FmtMoney(X.revenueTotal),'Contract schedule and dated source work; billing reconciliation required')}${fin745Card('Cost estimates for review',acc762FmtMoney(X.costCandidateTotal),'Includes forecast and unverified estimates; not an accrual to post')}${fin745Card('Supplier invoices recorded',acc762FmtMoney(X.invoiced),'Invoice evidence is not proof of payment or complete coverage')}${fin745Card('Month allocation needed',String(unallocated.length),'Recorded work or costs without a confirmed work month')}</div>
 <p class="fin745-basis">As at ${esc(fmtDate(X.asAt))}. Future work is forecast; running-sheet entries remain unconfirmed until reviewed. ${X.baseplan?`Billing snapshot ${X.baseplan.supplied_on?esc(fmtDate(X.baseplan.supplied_on)):'date not supplied'}: ${esc(X.baseplan.billed)} of ${esc(X.baseplan.n)} lines show a billed amount. This does not establish current unbilled Revenue.`:''}</p>
 <div class="fin745-block"><h3>Revenue schedule · reconciliation required</h3><p>Amounts allocated from contracts and dated source records. Confirm delivery, work performed and customer billing before recognising Revenue or proposing an accrual.</p><div class="fin745-table"><table><thead><tr><th>Stream</th><th>Branch</th><th class="num">Allocated value</th><th>Basis</th><th>Review</th></tr></thead><tbody>${X.revenue.map(r=>`<tr><td>${esc(r.stream)}</td><td>${esc(r.branch)}</td><td class="num">${m(r.amount)}</td><td class="acc761-why">${esc(r.basis)}</td><td>${status(r)}${esc(r.words||'')}</td></tr>`).join('')||'<tr><td colspan="5">No allocated source values in this month.</td></tr>'}</tbody></table></div></div>
 <div class="fin745-block"><h3>Direct cost review · no automatic accrual</h3><p>Use actual cost evidence where recorded; otherwise values remain estimates. An invoice missing from this page does not mean it is unpaid or unposted in Finance.</p><div class="fin745-table"><table><thead><tr><th>Cost</th><th>Branch</th><th class="num">Source value</th><th class="num">Invoices recorded</th><th>Evidence</th><th>Review action</th></tr></thead><tbody>${X.costs.map(r=>`<tr><td>${esc(r.stream)}</td><td>${esc(r.branch)}</td><td class="num">${m(r.candidate)}${r.extra.unpricedCount?'<br><span class="acc761-w">Partial · unpriced sources</span>':''}</td><td class="num">${m(r.invoiced)}</td><td class="acc761-why">${esc(r.evidence)}</td><td>${status(r)}${esc(r.words||'')}</td></tr>`).join('')||'<tr><td colspan="6">No dated cost sources in this month.</td></tr>'}</tbody></table></div></div>
 ${unallocated.length?`<details class="acc761-gloss"><summary>Recorded work and costs needing month allocation (${unallocated.length})</summary><p>These amounts remain visible separately. The delivery date or the time a tick was entered is not a confirmed work date.</p><div class="fin745-table"><table><thead><tr><th>Source</th><th>Branch</th><th class="num">Value</th><th>Evidence needed</th></tr></thead><tbody>${unallocated.map(r=>`<tr><td>${esc(r.stream||r.what||'Source')}</td><td>${esc(r.branch||'the job')}</td><td class="num">${m(acc762RowAmount(r))}</td><td class="acc761-why">${esc(r.basis||r.evidence||r.words||'Confirm work month')}</td></tr>`).join('')}</tbody></table></div></details>`:''}
 <div class="fin745-block acc761-wip"><h3>Fencing paid · customer billing outstanding</h3>${(X.wip||[]).map(w=>`<p><b>${esc(w.what)}.</b> ${esc(w.words)}.</p>`).join('')}<p>Finance should confirm the paid amount, the period of the work and the existing postings before deciding any allocation, Revenue recognition or permitted WIP treatment. Do not accrue the same paid cost again.</p></div>
 <div class="fin745-block"><h3>Customer charge forecast · whole job</h3><p>Labour, cleaning, equipment and event support are separate. Card values remain estimates until agreed rates and scope are confirmed.</p><div class="fin745-table"><table><thead><tr><th>Charge</th><th class="num">Recorded</th><th class="num">Expected on site</th><th class="num">To come</th><th class="num">Later</th><th class="num">Known forecast</th></tr></thead><tbody>${forecastRow('Labour Install · install, steps, levelling and demob',L.groups.install)}${forecastRow('Cleaning',L.groups.cleaning)}${forecastRow('Fire extinguishers',L.groups.fire_ext)}${L.groups.other.n||L.groups.other.total?forecastRow('Other recorded charges',L.groups.other):''}<tr><td colspan="5">Event people · ${h(L.scopeHours)} in the scope</td><td class="num">${m(L.scopePeople)}</td></tr><tr><td colspan="5">Event accommodation and travel</td><td class="num">${m(L.scopeSupport)}</td></tr><tr class="acc761-tot"><td colspan="5"><b>Labour-only forecast · Labour Install + event people</b></td><td class="num"><b>${m(L.labourOnlyTotal)}${!L.labourOnlyComplete?' · partial':''}</b></td></tr><tr><td colspan="5">All listed charges · including cleaning, fire extinguishers and event support${!L.packageComplete?' · PARTIAL: unpriced amounts remain':''}</td><td class="num">${m(L.packageTotal)}</td></tr></tbody></table></div></div>
 <div class="fin745-block"><h3>People, days and hours · ${esc(X.label)}</h3><p>Days entered are person-days. Paid/allocation hours apply the recorded break rules; they are not confirmed actuals until the timesheet review is complete.</p><div class="fin745-table"><table><thead><tr><th>Person / dates</th><th class="num">Days entered</th><th class="num">Before breaks</th><th class="num">Paid / allocation</th><th class="num">Confirmed</th><th class="num">Awaiting confirmation</th><th class="num">Forecast</th><th class="num">Cost outlook</th></tr></thead><tbody>${people.map(p=>`<tr><td><b>${esc(p.person)}</b><br><span class="acc761-w">${esc(p.type)} · ${p.dates.map(d=>esc(d.slice(8))).join(', ')} ${esc(X.label)}</span></td><td class="num">${esc(p.dayCount)}</td><td class="num">${h(p.grossHours)}</td><td class="num">${h(p.hours)}</td><td class="num">${h(p.confirmedPaidHours)}</td><td class="num">${h(p.pendingPaidHours)}</td><td class="num">${h(p.forecastPaidHours)}</td><td class="num">${p.unpricedCount===p.shifts&&p.shifts>0? 'Unpriced':m(p.cost)}${p.unpriced?`<br><span class="acc761-w">${h(p.unpriced)} unpriced</span>`:''}</td></tr>`).join('')||'<tr><td colspan="8">No running-sheet entries in this month.</td></tr>'}</tbody></table></div><p>Internal labour needs its payroll cost and allocation checked, including salary hours. Labour-hire costs need supplier invoice and existing allocation checks. The cost outlook uses verified actual cost where supplied, otherwise the recorded cost rate.</p></div>
 <div class="fin745-block"><h3>Workforce outlook · all months</h3><div class="fin745-table"><table><thead><tr><th>Month</th><th class="num">Paid / allocation hours</th><th class="num">Confirmed</th><th class="num">Awaiting confirmation</th><th class="num">Forecast</th><th class="num">Known cost</th><th class="num">Unpriced hours</th></tr></thead><tbody>${Object.keys(L.months).sort().map(k=>{const r=L.months[k];return `<tr><td>${esc(fin745MonthLabel(k))}</td><td class="num">${h(r.hours)}</td><td class="num">${h(r.confirmedPaidHours)}</td><td class="num">${h(r.pendingPaidHours)}</td><td class="num">${h(r.forecastPaidHours)}</td><td class="num">${m(r.cost)}</td><td class="num">${h(r.unpriced)}</td></tr>`;}).join('')}<tr class="acc761-tot"><td>Whole job</td><td class="num">${h(L.all.hours)}</td><td class="num">${h(L.all.confirmedPaidHours)}</td><td class="num">${h(L.all.pendingPaidHours)}</td><td class="num">${h(L.all.forecastPaidHours)}</td><td class="num">${m(L.all.cost)}</td><td class="num">${h(L.all.unpriced)}</td></tr></tbody></table></div><p class="fin745-basis">Known costs include each type of person only where an actual cost or cost rate is recorded. Unpriced hours are excluded, so the outlook is partial whenever those hours remain.</p></div>
 <details class="acc761-gloss"><summary>Finance terms</summary><dl><dt>Accrual</dt><dd>A period adjustment based on work performed and the invoices or postings still outstanding. The estimates here need reconciliation first.</dd><dt>Unbilled Revenue</dt><dd>Revenue supported by completed performance and the accounting policy, with customer billing still outstanding.</dd><dt>WIP / deferral</dt><dd>A treatment Finance assesses from the work, contract and accounting policy. Paying before customer billing does not automatically qualify a cost for deferral.</dd><dt>Allocation / reclass</dt><dd>Move an existing cost to the correct job, branch or account without creating the cost twice.</dd><dt>Forecast</dt><dd>Expected future work or cost. It is not confirmed actual work or an accrual to post today.</dd></dl></details><p class="fin745-basis acc761-foot">Author: Andrew Fisher · Finance review v7.62 · decisions belong in the existing Finance journal proposals above. No ledger entries are posted by this view.</p></section>`;
}
