function renderFenceComponents849(day, suppliedScope) {
  const esc = fenceComponentsEscape849, scope = String(suppliedScope || 'today').replace(/[^a-zA-Z0-9_-]/g, '-');
  const sourceCache = {books:new Map(), links:new Map()};
  const ledger = typeof fenceComponents849 === 'function' ? fenceComponents849(day) : {state:'unavailable', recorded:[], collections:[], rows:[], collectionRows:[], issues:['Component records are unavailable.']};
  const opened = key => FENCE_COMPONENTS_VIEW849.folds.get(scope + ':' + key) ? ' open' : '';
  const fold = (key, title, body, className) => '<details class="fc849-fold ' + (className || '') + '" data-fc849-fold="' + esc(key) + '"' + opened(key) + '><summary>' + title + '</summary><div class="fc849-fold-body">' + body + '</div></details>';
  const quantity = value => value == null ? 'Not recorded' : value.toLocaleString('en-AU');
  const sourceRows = (item, rows) => rows.filter(row => row.components?.[item.id] != null || row.missing?.includes(item.id) || row.invalid?.includes(item.id)).map(row => {
    const value = row.components?.[item.id], state = value != null ? quantity(value) + ' each' : row.invalid?.includes(item.id) ? 'Count needs review' : 'Not recorded';
    return '<li class="fc849-source"><div class="fc849-source-title"><strong>' + esc((row.book === 'blue' ? 'Collection ' : 'Docket ') + row.number) + '</strong><span>' + esc(state) + '</span></div><p class="fc849-note">' + esc([row.date, row.location].filter(Boolean).join(' · ')) + '</p>' + fenceComponentLinks849(row, sourceCache) + '</li>';
  }).join('');
  const readings = (items, rows, prefix) => '<div class="fc849-readings">' + items.map(item => {
    const coverage = [item.sourceRecordCount + ' record' + (item.sourceRecordCount === 1 ? '' : 's'), item.missingRecordCount ? item.missingRecordCount + ' unstated' : '', item.invalidRecordCount ? item.invalidRecordCount + ' to review' : ''].filter(Boolean).join(' · ');
    return fold(prefix + '-' + item.id, '<span class="fc849-reading-label">' + esc(item.label) + '</span><strong class="fc849-count" data-fc849-count="' + esc(prefix + '-' + item.id) + '">' + esc(quantity(item.quantity)) + (item.quantity == null ? '' : '<small> each</small>') + '</strong><span class="fc849-coverage">' + esc(coverage) + '</span><span class="fc849-reading-action">Sources <span aria-hidden="true">⌄</span></span>', '<ul class="fc849-sources">' + (sourceRows(item, rows) || '<li class="fc849-note">No applicable dated component record is available.</li>') + '</ul>', 'fc849-reading');
  }).join('') + '</div>';
  let audit = {issues:[], pending:[]};
  try { if (typeof fenceComponentEvidence849 === 'function') audit = fenceComponentEvidence849(day); } catch (_) { audit = {issues:[], pending:['Source reconciliation is unavailable.']}; }
  const issues = (audit.issues || []).map(issue => '<li class="fc849-source"><strong>' + esc(issue.title) + '</strong><p class="fc849-note">' + esc(issue.detail) + '</p>' + fenceComponentLinks849(issue, sourceCache) + '</li>');
  const notes = [...(ledger.issues || []), ...(audit.pending || []).map(item => typeof item === 'string' ? item : item.reason || item.detail || item.title || 'A source check is pending.')];
  const issueFold = issues.length || notes.length ? fold('reconcile', 'What needs reconciling' + (issues.length ? ' · ' + issues.length : ''), '<p class="fc849-note">Source differences are listed for review. They have not changed the recorded quantities, work totals or charges.</p>' + (issues.length ? '<ul class="fc849-sources">' + issues.join('') + '</ul>' : '') + (notes.length ? '<ul class="fc849-assumptions">' + notes.map(note => '<li>' + esc(note) + '</li>').join('') + '</ul>' : '')) : '';
  const defaults = {length:'', panels:'', panelWidth:'2.4', gatePanels:'0', gateOpenings:'0', layout:'straight', fixedRuns:'', endGateOpenings:'0', openLineEnds:'', corners:'0', braced:false, ownHingeFeet:false};
  const values = {...defaults, ...(FENCE_COMPONENTS_VIEW849.forms.get(scope) || {})};
  const numberInput = (key, label, step, placeholder) => '<label for="fc849-' + scope + '-' + key + '"><span>' + esc(label) + '</span><input id="fc849-' + scope + '-' + key + '" name="' + key + '" type="number" min="0" step="' + (step || '1') + '" inputmode="' + (step === 'any' ? 'decimal' : 'numeric') + '" value="' + esc(values[key]) + '"' + (placeholder ? ' placeholder="' + esc(placeholder) + '"' : '') + ' data-tw840-focus="fc849-' + scope + '-' + key + '"></label>';
  const planner = '<p class="fc849-note">Use the 2.4 m panel guide to fill planning gaps. These are hypothetical allowances; existing totals, Revenue and Direct costs remain unchanged.</p><form class="fc849-guide" data-fc849-guide data-ro autocomplete="off"><div class="fc849-inputs">' + numberInput('length','Fence line length · m','any','Enter length or panels') + numberInput('panels','Panels · overrides length','1','Optional') + numberInput('panelWidth','Panel width · m','any') + numberInput('gatePanels','Gate panels · leaves') + numberInput('gateOpenings','Gate openings') + '<label for="fc849-' + scope + '-layout"><span>Layout</span><select id="fc849-' + scope + '-layout" name="layout" data-tw840-focus="fc849-' + scope + '-layout">' + [['straight','Straight line'],['closed','Closed perimeter'],['unknown','Runs / layout uncertain']].map(([value,label]) => '<option value="' + value + '"' + (values.layout === value ? ' selected' : '') + '>' + label + '</option>').join('') + '</select></label>' + numberInput('fixedRuns','Fixed runs','1','Derived from layout') + numberInput('endGateOpenings','Gate openings at line ends') + numberInput('openLineEnds','Open line ends','1','Derived from layout') + numberInput('corners','Extra corner stays') + '</div><label class="fc849-check"><input type="checkbox" name="braced"' + (values.braced ? ' checked' : '') + '> Apply scrim bracing every second joint</label><label class="fc849-check"><input type="checkbox" name="ownHingeFeet"' + (values.ownHingeFeet ? ' checked' : '') + '> Each gate hinge has its own extra foot</label><div class="fc849-guide-output" data-fc849-guide-output aria-live="polite" aria-atomic="true">' + fenceComponentGuideOutput849(values) + '</div></form><p class="fc849-note">A gate’s free end has no foot. The usual hinge shares the adjoining fixed-panel foot. Stay feet / ballast are additional to line feet. Gate wheels do not establish the number of gate openings.</p><p class="fc849-note">Each open line end adds two stays under the supplied rule. For the 100 m example with two single gates, that is four end stays: 27 in the written guide, with up to 28 when each fixed run is rounded separately. Slopes and engineered bracing need their own allowance.</p>';
  return '<section class="fc849-components" data-fc849-scope="' + esc(scope) + '" data-fc849-state="' + esc(ledger.state) + '" aria-labelledby="fc849-' + scope + '-heading"><h4 id="fc849-' + scope + '-heading">Recorded components</h4>' + readings(ledger.recorded || [], ledger.rows || [], 'recorded') + fencePresentationFold851(scope, 'count-notes', 'Count notes', '<p class="fc849-note">Gross component counts on dated Build + Event hire agreements' + (ledger.asOf ? ' through ' + esc(ledger.asOf) : '') + '. These count recorded activity, not current stock or confirmed installation. Missing counts stay unrecorded.</p><p class="fc849-note">Braces / stays do not prove scrim is fitted. Component feet / blocks are separate from the charged fence-block work column.</p>') + fold('collections', 'Collections — separate activity', '<p class="fc849-note">Collection forms are shown separately. These counts are not subtracted from hire agreements to infer stock on site.</p>' + readings(ledger.collections || [], ledger.collectionRows || [], 'collected'))+ issueFold + renderFencePoEvidence850(day, scope) + fold('guide', 'Planning guide — separate estimates', planner) + '</section>';
}
