/* Author: Andrew Fisher. Permanent reference handling instructions; source crane wording is not a crane model. */
function handling875Merge(a,b){const valid=x=>x&&['crane-truck','franna','onsite-crane','not-required',''].includes(x.method)&&typeof x.by==='string'&&x.by.trim()&&Number.isFinite(Date.parse(x.at));return !valid(a)?valid(b)?b:null:!valid(b)?a:a.at!==b.at?(a.at>b.at?a:b):JSON.stringify(a)>JSON.stringify(b)?a:b;}
function handling875Record(a){const x=handling875Merge(((CROW.get(a.key)||{}).delivery||{}).handling875,((S.delivery||{})[a.key]||{}).handling875);if(x)return x;const full=assetOf(a.key)||a,e=(full.events||[]).find(e=>e.handling_source875);return e?Object.assign({source:true},e.handling_source875):null;}
function handling875Words(m){return {'crane-truck':'Crane truck required',franna:'Franna required','onsite-crane':'On-site crane required · type to confirm','not-required':'Crane / Franna not required'}[m]||'Lifting requirement not set';}
function handling875Set(ref,method){const a=assetOf(ref);if(!a||a._cancelled||!['crane-truck','franna','onsite-crane','not-required',''].includes(method)||!mayWrite('the lifting requirement'))return false;const who=whoAmI();if(!who)return false;const old=handling875Record(a),d=(S.delivery||(S.delivery={}))[ref]||((S.delivery)[ref]={});d.handling875={method,by:who,at:new Date(Math.max(Date.now(),old&&old.at?Date.parse(old.at)+1:0)).toISOString()};bump();flash(ref+' · '+handling875Words(method)+' saved.');return true;}
let handling875Seq=0;
function handling875Editor(a){if(!a||a._cancelled)return '';const r=handling875Record(a),can=capability()==='edit'&&!SYNC.readonly;if(!r&&!can)return '';const name='handling875-'+a.key+'-'+(++handling875Seq);return '<details class="loading872 handling875"><summary>Lifting · '+esc(handling875Words(r&&r.method))+'</summary><fieldset><legend>Crane / Franna requirement</legend>'+['crane-truck','franna','onsite-crane','not-required'].map(m=>'<label><input type="radio" name="'+esc(name)+'" data-handling875-ref="'+esc(a.key)+'" value="'+m+'"'+(r&&r.method===m?' checked':'')+(can?'':' disabled')+'> '+esc(handling875Words(m))+'</label>').join('')+(r&&r.source?'<p>'+esc(r.source===true?'Schedule source':r.source)+' · '+esc(r.sheet)+' row '+esc(r.row)+'. Confirm the equipment type for the next movement.</p>':'')+(can?'<button type="button" class="btn" data-handling875-clear="'+esc(a.key)+'">Clear</button>':'')+'</fieldset></details>';}
function handling875Sheet(a){const r=a&&handling875Record(a);return r?'<div class="loading872-sheet handling875-sheet"><b>Lifting · '+esc(a.key)+'</b><div>'+esc(handling875Words(r.method))+'</div><div>Confirm the lifting arrangement, operator and site setup before loading or unloading.</div></div>':'';}
const handling875DoorEditor=loading872Editor;loading872Editor=function(a){return handling875DoorEditor(a)+handling875Editor(a);};
function handling875Checks(m,assets){const unique=[...new Map(assets.map(a=>[a.key,a])).values()],rows=unique.map(a=>({a,r:handling875Record(a)})).filter(x=>x.r);if(!rows.length)return m;m.checks.push({id:'lifting-requirement',text:'The reference lifting requirements and lifting arrangement are confirmed with the driver and site team.'});rows.forEach(({a,r})=>{const text=a.key+': '+handling875Words(r.method);if(!r.method||r.method==='onsite-crane')m.warnings.push({key:a.key,text:text+' — confirm equipment for this movement.'});else m.report.push(text);});return m;}
const handling875Driver=driverModel826;driverModel826=function(iso,only){const m=handling875Driver(iso,only),sel=selectedDriver826(iso,only);return m&&sel?handling875Checks(m,sel.loads.flatMap(x=>x.g.rows.map(r=>r.a))):m;};
const handling875Demob=demobModel826;demobModel826=function(iso,br,what,n){const m=handling875Demob(iso,br,what,n);return m?handling875Checks(m,selectedDemob826(iso,br,what,n).flatMap(L=>L.stops.map(s=>assetOf(s.r.key))).filter(Boolean)):m;};
const handling875Truck=dpTruck;dpTruck=function(g,doc){return handling875Truck(g,doc)+[...new Map(g.rows.map(r=>[r.a.key,r.a])).values()].map(handling875Sheet).join('');};
const handling875Drop=dropPage;dropPage=function(a,...args){return handling875Drop(a,...args).replace('<div class="rs-go">',handling875Sheet(a)+'<div class="rs-go">');};
const handling875Sheet816=sheet816;sheet816=function(iso,L){return handling875Sheet816(iso,L).replace('<h2>Sign-off</h2>',[...new Set(L.stops.map(s=>s.r.key))].map(k=>handling875Sheet(assetOf(k))).join('')+'<h2>Sign-off</h2>');};
const handling875EP=epRunSheet819;epRunSheet819=function(L){return handling875EP(L).replace('<div class="rs-so">',[...new Set((L.stops||[]).flatMap(s=>(s.drops||[]).map(d=>d.ref)).filter(Boolean))].map(k=>handling875Sheet(assetOf(k))).join('')+'<div class="rs-so">');};
document.addEventListener('change',e=>{const n=e.target;if(!n.matches('[data-handling875-ref]'))return;const main=document.querySelector('main'),y=main&&main.scrollTop;handling875Set(n.dataset.handling875Ref,n.value);if(main)main.scrollTop=y;});
document.addEventListener('click',e=>{const n=e.target.closest('[data-handling875-clear]');if(!n)return;e.preventDefault();handling875Set(n.dataset.handling875Clear,'');n.closest('fieldset').querySelectorAll('input').forEach(x=>x.checked=false);});
const handling875Groups=todayGroupDetails841;todayGroupDetails841=function(...args){const r=handling875Groups(...args),review=DATA.schedule_review875;if(review&&r.vms&&r.vms.health.ready){const total=r.vms.groups.reduce((n,g)=>n+(g.summary.total||0),0);if(total!==review.vms_boq)r.vms.notes.push(review.source+' programme: '+total+' VMS boards; BOQ: '+review.vms_boq+'. Difference '+Math.abs(total-review.vms_boq)+' — quantity basis to confirm. These source readings remain separate.');}return r;};

const handling875BookingLoads=bookingLoads801;bookingLoads801=function(d){return handling875BookingLoads(d).map(l=>String(l.n||'').startsWith('schedule875-')?Object.assign({},l,{source:'Schedule (5)',supplied_by:'Schedule source'}):l);};
