// Author: Andrew Fisher. Current allocation, historical evidence and later-record precedence.
'use strict';
const assert=require('assert/strict'),I=require('../identities973.js');let checks=0;
const check=(name,fn)=>{fn();checks++;},copy=x=>JSON.parse(JSON.stringify(x));
function fixture(){
 const a={key:'P36',_buildingNumbers:['1327222','1282487'],_numberSources:{'1327222':['the schedule'],'1282487':['recorded on site','the rental system']},events:[{task_id:'T0232',sheet:'Week 5',source_range:"'Week 5'!A35:N35",date:'2026-09-17',movement:'place',item:'Building 6m',quantity_raw:1}]};
 const rows=['1327222','1282487','1283004'].map((assetNo,i)=>({id:assetNo,ref:'P36',owner:'coates',assetNo,item:i===2?'Aircon':'Building 6m',physical:true,source:'native',raw:{asset_no:assetNo}}));
 const model={ref:'P36',rows,groups:[{item:'Building 6m',quantity:1,pending:0,units:rows.slice(0,2)},{item:'Description to confirm',quantity:null,pending:null,units:rows.slice(2)}]};
 const c={ready:true,scheduleSha:I.scheduleSha,lines:[{item:'Building 6m',quantity:1}],photos:I.photos.map(([id,at])=>({id,at,by:'Andrew Fisher',unit:'1282487'})),units:[{asset_no:'1283004',label:'Aircon'}],identifications:[],delivered:true,override:false};
 return {a,model,c};
}
check('one current building and explicit retained history',()=>{const {a,model,c}=fixture(),before=JSON.stringify({a,model,c}),r=I.project(a,model,c);assert.equal(r.rows.length,3);assert.equal(r.rows.filter(x=>x.physical&&x.item==='Building 6m').length,1);assert.equal(r.rows.find(x=>x.assetNo==='1327222').source,'history');assert.equal(r.groups[0].units[0].assetNo,'1282487');assert.equal(r.groups[0].quantity,1);assert.equal(r.groups[0].pending,0);assert.equal(r.rows[2],model.rows[2]);assert.equal(JSON.stringify({a,model,c}),before);assert.equal(I.project(a,r,c),r);});
const cases=[
 ['unrelated reference',x=>x.a.key='P35'],['not synced',x=>x.c.ready=false],['changed schedule',x=>x.c.scheduleSha='changed'],['cancelled',x=>x.a._cancelled=true],['moved',x=>x.c.moved=true],['location changed',x=>x.a._locationMoved={}],['order quantity changed',x=>x.c.lines[0].quantity=2],['extra charge item',x=>x.c.lines.push({item:'Building 4.8m',quantity:1})],['changed source date',x=>x.a.events[0].date='2026-09-18'],['changed source task',x=>x.a.events[0].task_id='T0000'],['changed source row',x=>x.a.events[0].source_range='other'],['changed source quantity',x=>x.a.events[0].quantity_raw=2],['extra placement',x=>x.a.events.push({...x.a.events[0]})],['third building number',x=>x.a._buildingNumbers.push('999')],['old number recorded on site',x=>x.a._numberSources['1327222'].push('recorded on site')],['current no onsite basis',x=>x.a._numberSources['1282487']=['the rental system']],['later allocation',x=>x.c.override=true],['arrival removed',x=>x.c.delivered=false],['new explicit old unit',x=>x.c.units.push({asset_no:'1327222'})],['new explicit current unit',x=>x.c.units.push({asset_no:'1282487'})],['new named building unit',x=>x.c.units.push({item:'Building 6m'})],['new identity decision',x=>x.c.identifications.push({ref:'P36'})],['photo of old unit',x=>x.c.photos.push({id:'new',unit:'1327222'})],['missing photo',x=>x.c.photos.pop()],['changed photo unit',x=>x.c.photos[0].unit='999'],['changed photo author',x=>x.c.photos[0].by='Other'],['changed photo date',x=>x.c.photos[0].at='2026-10-09'],['removed photo',x=>x.c.photos[0].removed=true],['duplicate photo',x=>x.c.photos.push({...x.c.photos[0]})],['current unit not physical',x=>x.model.rows[1].physical=false],['wrong current item',x=>x.model.rows[1].item='Container'],['old ownership decision',x=>x.model.rows[0].owner='event-portables'],['old explicit metadata',x=>x.model.rows[0].metadata={}],['current explicit metadata',x=>x.model.rows[1].metadata={}],['old archived by native record',x=>x.model.rows[0].physical=false],['duplicate model identity',x=>x.model.rows.push({...x.model.rows[1]})]
];
for(const [name,mutate]of cases)check(name+' retains original model',()=>{const x=fixture();mutate(x);assert.equal(I.project(x.a,x.model,x.c),x.model);});
check('additional photograph of current unit does not discard evidence',()=>{const x=fixture();x.c.photos.push({id:'later-current',unit:'1282487'});assert(I.project(x.a,x.model,x.c).allocation973);});
console.log(JSON.stringify({author:'Andrew Fisher',checks,passed:checks}));
