// Author: Andrew Fisher. Execute actual toolchain output against unchanged native author identities.
'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),vm=require('vm'),cp=require('child_process'),assert=require('assert/strict');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gc500-scrub973-')),scrub=path.resolve(__dirname,'../../toolchain/scrub_attributions.py');let checks=0;
function compiled(file,context={}){const html=path.join(dir,file+'.html');fs.writeFileSync(html,'<script>\n'+fs.readFileSync(path.resolve(__dirname,'..',file),'utf8')+'\n</script>');const run=cp.spawnSync('python3',[scrub,html],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const code=fs.readFileSync(html,'utf8').match(/<script>([\s\S]*)<\/script>/)[1],ctx={...context,module:{exports:{}}};vm.runInNewContext(code,ctx);return ctx.module.exports;}
try{
 const I=compiled('identities973.js'),a={key:'P36',_buildingNumbers:['1327222','1282487'],_numberSources:{'1327222':['the schedule'],'1282487':['recorded on site']},events:[{movement:'place',task_id:'T0232',sheet:'Week 5',source_range:"'Week 5'!A35:N35",date:'2026-09-17',item:'Building 6m',quantity_raw:1}]},c={ready:true,scheduleSha:I.scheduleSha,lines:[{item:'Building 6m',quantity:1}],delivered:true,photos:I.photos.map(([id,at])=>({id,at,by:'Andrew Fisher',unit:'1282487'}))};assert(I.supported(a,c));checks++;c.photos[0].by='the project manager';assert.equal(I.supported(a,c),false);checks++;
 const assets={P20:{key:'P20',item:'Building 4.8m',no:'1097339'},P21:{key:'P21',item:'Building 4.8m',no:'1327220'}},loads={},contracts=[{rental_contract:'9968862',line:38,asset_no:'1097339',register_type:'Building 4.8m',quantity:1,delivery_number:'26076698'},{rental_contract:'9968862',line:92,asset_no:'1327220',register_type:'Building 6m',quantity:1,delivery_number:'26076820'}];for(const [ref,ids]of [['P20',[10,14]],['P21',[12,16]]])for(const id of ids)loads['2026-09-16#'+id]={keys:[ref],by:'Andrew Fisher'};
 const Q=compiled('questions973.js',{DATA:{schedule_review950:{sha256:I.scheduleSha}},S:{loads},ONHIRE_ROWS:contracts,assetOf:r=>assets[r],chargeLines:a=>[{item:a.item,quantity:1}],qtyOf:l=>l.quantity,assetNumbersOf:a=>[a.no]});assert.equal(Q.context().loads,true);checks++;loads['2026-09-16#10'].by='the project manager';assert.equal(Q.context().loads,false);checks++;
 loads['2026-09-16#10'].by='Andrew Fisher';contracts[1].delivery_number='new';assert.equal(Q.context().loads,false);checks++;
 console.log(JSON.stringify({author:'Andrew Fisher',checks,passed:checks,actualToolchainScrub:true}));
}finally{fs.rmSync(dir,{recursive:true,force:true});}
