/* Author: Andrew Fisher. Presentation arithmetic never mutates financial models. */
const assert=require('node:assert/strict'),P=require('../financial_presentation976.js');let n=0;const eq=(a,b)=>{assert.deepEqual(a,b);n++;};
eq(P.remaining(100,140),40);eq(P.remaining(0,100),100);eq(P.remaining(null,100),null);eq(P.remaining(100,90),-10);
const rows=[{code:'1025',line:'Cleaning',now:0,job:156.15,what:'Cleaning',basis:'Card',missing:''}],before=JSON.stringify(rows);eq(P.moneyRows(rows)[0],{code:'1025',label:'Cleaning',recorded:0,remaining:156.15,job:156.15,details:'Cleaning · Card'});eq(JSON.stringify(rows),before);
const SP={paid:100,green:20},fd={charged:200},F={revenue:300,cost:80};const snapshot=JSON.stringify({SP,fd,F}),f=P.fenceSummary(SP,fd,F);eq(f[0].recorded,200);eq(f[0].remaining,300);eq(f[0].job,500);eq(f[1].recorded,120);eq(f[1].remaining,80);eq(f[1].job,200);eq(JSON.stringify({SP,fd,F}),snapshot);assert.match(f[1].details,/not payment confirmations/);n++;

const vm=require('node:vm'),fs=require('node:fs');const model={asAt:'2026-10-09',rev:rows,cost:[{code:'2126',line:'Rehire',now:120,job:200,basis:'Supplier'}],revNow:0,revJob:156.15,direct:120,directJob:200,over:10,overJob:20,wages:{toDate:30,job:50,unpricedHours:0}};
const copy=JSON.stringify(model),context={window:{},module:{exports:{}},esc:v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;'),money:v=>'$'+v.toFixed(2),fmtDate:v=>v,renderCosts:()=>{},fencePrivateApply:()=>{},fencePlCard:()=>'<div id="fencePl">Paid to Advanced</div>',fencePaidSplit:()=>SP,fenceDerived:()=>fd,cj764Fencing:()=>F,pl770Card:()=>'<section id="pl770" aria-labelledby="pl770Title"><h2 id="pl770Title">Details</h2></section>',pl770Model:()=>model};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../financial_presentation976.js'),'utf8'),context);let html=context.pl770Card();assert.match(html,/Forecast remaining/);n++;assert.match(html,/Customer revenue/);n++;assert.match(html,/Overheads and wages/);n++;assert.equal((html.match(/id="pl770"/g)||[]).length,1);n++;assert.equal((html.match(/id="pl770Title"/g)||[]).length,1);n++;eq(JSON.stringify(model),copy);html=context.fencePlCard();assert.match(html,/not payment confirmations/);n++;assert.doesNotMatch(html,/Paid to Advanced/);n++;eq(JSON.stringify({SP,fd,F}),snapshot);



model.gm={now:100,job:200,pcNow:.25,pcJob:.35};model.diff={now:50,job:80,pcNow:.125};model.costNow=130;model.costJob=220;model.checks={revenue:false};html=context.pl770Card();assert.match(html,/Financial reconciliation needs review/);n++;assert.match(html,/Ledger gross margin before overheads and wages/);n++;assert.match(html,/Recorded 25% · job forecast 35%/);n++;assert.match(html,/Recorded 13%/);n++;assert.match(html,/Costs including travel/);n++;
console.log(JSON.stringify({author:'Andrew Fisher',checks:n,passed:true}));