// Author: Andrew Fisher. Focused source binding, readable phone-width information and native A4 output.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const {open}=require(path.resolve(__dirname,'../../toolchain/harness/open_page'));
const out=process.env.OUT931||'/workspace/private-loading931-final';fs.mkdirSync(out,{recursive:true});
(async()=>{const file=process.env.PAGE,hash=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),s=await open({pageFile:file,hash:'#timeline',W:1000,H:1200});try{const p=s.page;
await p.waitForFunction(()=>window.Loading931&&SYNC.status==='live'&&Object.keys(SYNC_COLLS).every(k=>SYNC.first.has(k)),null,{timeout:180000});
const result=await p.evaluate(()=>{window.__r931Before=JSON.stringify(S);const R=Loading931,gn=R.referenceProducts931(assetOf('GN19')),wc=R.referenceProducts931(assetOf('WC09'));return {generator:gn.map(x=>({item:x.item,owner:x.owner,facts:x.facts})),wc09:wc.map(x=>({item:x.item,owner:x.owner,facts:x.facts})),guideGuards:['VMS Colour Senior','VMS A1 Roadlines','JLG Light Tower','Light Tower LED'].every(x=>R.guideRows931(x).length===0)};});
assert(result.generator.some(x=>x.facts.some(f=>f.label==='Delivered rating'&&f.values.includes('80 kVA'))),'GN19 supplied rating from actual contract');assert(result.guideGuards);assert(result.wc09.filter(x=>/fwf|pee.panel/i.test(x.item)).every(x=>x.owner==='event-portables'),'exact supplier items explicit');assert(result.wc09.filter(x=>/toilet.block/i.test(x.item)).every(x=>x.owner==='coates'||x.owner==='unknown'),'Coates block not attributed to supplier');
await p.setViewportSize({width:390,height:844});
for(const ref of ['GN19','WC09','WC20']){await p.evaluate(ref=>openAsset(ref),ref);const box=p.locator('#drawer .r931').first();await box.waitFor({state:'attached'});await box.evaluate(el=>{for(let n=el;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;});assert.equal(await box.locator('input,select,textarea,button').count(),0);assert(await box.evaluate(el=>el.scrollWidth<=el.clientWidth+2));await box.scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,ref+'-390.png')});}
await p.evaluate(()=>{document.getElementById('dclose')?.click();const R=Loading931,pick=programmeDays().flatMap(d=>dpLoads(d).filter(g=>g.kind==='deliveries'&&R.loadProducts931(g).some(x=>x.ref==='WC09'&&R.family931(x.item)==='toilet-block')).map(g=>({d,g})))[0];state.day=pick.d.iso;state.tlView='day';go('timeline');render();});
const timeline=p.locator('#pane-timeline .r931').filter({hasText:'WC09'}).first();await timeline.scrollIntoViewIfNeeded();result.contrast=await timeline.locator('.r931-fact span').first().evaluate(el=>({label:getComputedStyle(el).color,parent:getComputedStyle(el.parentElement).color,opacity:getComputedStyle(el).opacity}));assert.equal(result.contrast.label,result.contrast.parent);await p.screenshot({path:path.join(out,'timeline-390.png')});
await p.setViewportSize({width:1000,height:1200});await p.evaluate(()=>{const R=Loading931,pairs=programmeDays().flatMap(d=>dpLoads(d).map((g,i)=>({d,g,i,n:R.loadProducts931(g).length})).filter(x=>x.g.kind==='deliveries')).sort((a,b)=>b.n-a.n),pick=pairs[0];window.__r931Pick={day:pick.d.iso,loadIndex:pick.i,products:pick.n};dpPrint(pick.d.iso,'drv',{only:pick.i,pdf:(result,wrap,done)=>{window.__r931Print={result};window.__r931Done=done;document.body.classList.remove('pdf7-make');document.body.classList.add('printing-day');}});});
await p.waitForFunction(()=>window.__r931Print,null,{timeout:60000});await p.emulateMedia({media:'print'});result.print=await p.evaluate(()=>({selection:__r931Pick,native:__r931Print.result,pages:[...document.querySelectorAll('#dayprint .r931-paper')].map(el=>({height:el.clientHeight,content:el.scrollHeight,overflow:el.scrollHeight>el.clientHeight+2,footerInside:el.querySelector('.dp-ft').getBoundingClientRect().bottom<=el.getBoundingClientRect().bottom+2,controls:el.querySelectorAll('input,select,textarea,button').length}))}));assert(!result.print.native.timeout&&!result.print.native.over.length);assert(result.print.pages.length&&result.print.pages.every(x=>!x.overflow&&x.footerInside&&!x.controls));await p.pdf({path:path.join(out,'native-driver.pdf'),printBackground:true,preferCSSPageSize:true});
result.unchanged=await p.evaluate(()=>JSON.stringify(S)===__r931Before);assert(result.unchanged,'read-only information changed operational state');result.errors=s.errors;result.requests=s.counts;result.candidateSha256=hash;assert.equal(s.errors.length,0);assert.equal(s.counts.blocked,0);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await s.browser.close();}})().catch(e=>{console.error(e.stack);process.exitCode=1});
