// Author: Andrew Fisher. Read-only product binding, movement scope and source semantics.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const dir=path.join(__dirname,'..'),guide=JSON.parse(fs.readFileSync(path.join(dir,'../v9.24_restraint_integration_LIVE/guide924.json'))),src=['core924.js','information931.js','runtime931.js'].map(n=>fs.readFileSync(path.join(dir,n),'utf8')).join('\n').replace('/* GUIDE924_DATA */[]',JSON.stringify(guide));
const c={console,module:{exports:{}},S:{loads:{}},ONHIRE_ROWS:[],gcUnits925:()=>[],dpItems:r=>r.events||[],assetOf:k=>({key:k,item_types:['Toilet Block 6m','Waste Tank 6m']}),CROW:new Map()};c.globalThis=c;vm.createContext(c);vm.runInContext(src,c);const R=c.Loading931;let checks=0;const ok=(v,m)=>{assert(v,m);checks++};
const a={key:'WC09',item_types:['Toilet Block 6m','Waste Tank 6m']};
const units=['1268858','1311146'].map(n=>({id:R.unitId(a.key,'coates','',n),ref:a.key,owner:'coates',assetNo:n,item:'Toilet Block 6m',label:'Toilet Block 6m',physical:true}));c.gcUnits925=a=>Array.isArray(a._bookingNumbers801)?units.filter(u=>a._bookingNumbers801.includes(u.assetNo)):units;
const rows=[{rental_contract:'9968955',description:'WC09 TOILET BLOCK 6M X 3M',register_type:'Toilet Block 6m',asset_no:'',match:{}}];
let p=R.products931(a,[{item:'Toilet Block 6m',qty:'1'}],rows,{load:true});ok(p.length===1&&p[0].units.length===0&&p[0].qty==='1','unknown partial allocation retains demand without all reference units');
p=R.products931({...a,_bookingNumbers801:['1268858']},[{item:'Toilet Block 6m',qty:'1'}],rows,{load:true});ok(p[0].units.length===1&&p[0].units[0].assetNo==='1268858','explicit booking allocation respected');
p=R.products931({...a,_bookingNumbers801:['1268858']},[{item:'Toilet Block 6m',qty:'2'}],rows,{load:true});ok(p[0].qty==='2'&&p[0].units.length===0,'larger demand is not silently reduced to known unit count');
p=R.products931(a,[{item:'Toilet Block 6m',qty:'2'}],rows,{load:true});ok(p.length===1&&p[0].qty==='2'&&p[0].units.length===2,'complete same-product set groups once');ok(p[0].facts[0].label==='Contract-listed footprint'&&p[0].facts[0].values[0]==='6000 × 3000 mm','source footprint auto-populated');ok(!JSON.stringify(p[0].facts).includes('massKg')&&!p[0].facts.some(f=>f.values.some(v=>/kg|Height/.test(v))),'footprint does not fabricate mass or height');
const other={...rows[0],asset_no:'OTHER',asset_no_is_plant_number:true,match:{key:'WC09'},description:'TOILET BLOCK 12M X 3M'};ok(R.contractRows931(a,units[0],'Toilet Block 6m',[other]).length===0,'exact-number miss cannot borrow another numbered unit');
for(const n of [0,2]){const demob=R.loadProducts931({_restraintDemob924:{stops:[{r:{key:'WC09'},parts:[{type:'Toilet Block 6m',n,unknown:true}]}]}});ok(demob[0].qty===''&&demob[0].units.length===0,'unknown Demob quantity is neither zero nor an allocated full set: '+n);}
ok(R.contractRows931(a,{...units[0],owner:'event-portables'},'Toilet Block 6m',rows).length===0,'rehire unit cannot inherit Coates contract dimensions');
const gen={key:'GN19'},u={id:'GEN',ref:'GN19',assetNo:'1234',owner:'coates',item:'Generator 60kVA',label:'Generator 60kVA'},gr=[{asset_no:'1234',asset_no_is_plant_number:true,rental_contract:'SOURCE',register_type:'Generator 60kVA',description:'GENERATOR 80KVA DIESEL DEL AS 60KVA',match:{key:'GN19'}}];
let i=R.info931(gen,u.item,u,gr);ok(i.source.capacityKva===80,'delivered physical rating precedes DEL AS billing rating');ok(i.facts.some(f=>f.label==='Delivered rating'&&f.values[0]==='80 kVA'),'actual delivered rating visible');ok(i.facts.some(f=>/Guide reference/.test(f.label)&&/skid-mounted/.test(f.label)&&f.values.includes('1662 kg')),'source model weight automatically visible as skid guide reference');ok(!i.actualVerified&&!i.facts.some(f=>f.label==='Recorded actual'),'guide reference is never actual verification');
i=R.info931(gen,'60kva',{...u,item:'60kva'},gr);ok(i.source.capacityKva===80&&i.guidance.title==='Skid equipment loading','native bare 60kva product resolves supplied80 rating and generator guidance');
c.epLine909=(ref,item)=>item==='FWF'||item==='Pee Panel';i=R.info931(a,'FWF',null,[]);ok(i.owner==='event-portables'&&R.productHtml931({...i,units:[],qty:'4'}).includes('SUB-HIRED — Event Portables'),'unnumbered exact supplier product is explicitly Rehire');ok(R.info931(a,'Toilet Block 6m',units[0],rows).owner==='coates','mixed reference Coates blocks do not inherit supplier ownership');delete c.epLine909;
ok(R.guideRows931('100kVA trailer-mounted generator').length===0,'trailer not given skid dimensions');ok(R.guideRows931('Light Tower LED').length===0&&R.guideRows931('Hybrid Light Tower').length===0,'LED/hybrid not assigned hydraulic tower dimensions');ok(R.guideRows931('VMS').length===0&&R.guideRows931('VMS Junior').length===0,'generic/Junior VMS not assigned Senior mass');ok(R.guideRows931('VMS Senior').length===1,'explicit Senior model has labelled guide reference');
for(const item of ['VMS Colour Senior','VMS Color Senior','VMS A1 Roadlines','JLG Light Tower','JLG LED Light Tower','Lighting Tower 6000W LED'])ok(R.guideRows931(item).length===0,'brand or incompatible configuration cannot supply numeric reference: '+item);
ok(R.guideRows931('JLG Lighting Tower 6000W Hydraulic').length===1,'named hydraulic source configuration remains available');
for(const words of ['Toilet Block 6m','Waste Tank 6m','Porta Lisa','Building 6m'])ok(R.guideRows931(words).length===0,'no unrelated numeric guide model for '+words);
ok(R.guideRows931('Porta Lisa portable toilet FWF').length===0,'accessible toilet cannot inherit small Merlin FWF weight');ok(R.guidance931('Porta Lisa portable toilet').title==='Accessible toilet loading','accessible toilet does not receive generic small FWF base method');
ok(R.guidance931('Toilet Block 6m').title==='Portable building loading','block receives building handling');ok(R.guidance931('FWF').pages.includes(53),'small FWF receives base guidance');ok(!R.guidance931('Light Tower POD').text.includes('drawbar'),'POD not represented as trailer');ok(!R.guidance931('Building 6m').text.includes('wagon'),'building not represented as wagon');ok(!R.guidance931('Toilet Block 6m').text.includes('Melbourne'),'generic block not assigned named Melbourne method');
for(const item of ['Toilet Block 6m','Light Tower LED','Generator 60kVA','VMS','Waste Tank 6m']){const inf=R.info931(a,item,null,[]),html=R.productHtml931({...inf,units:[],qty:'1'});ok(!/<input|<select|<textarea|<button|to confirm|not stated|checks to complete|identify individual/i.test(html),'populated read-only information for '+item);ok(inf.guidance.text.length>20,'automatic guidance exists for '+item);}
const doc={kind:'restraint924-unit',unitId:units[0].id,identity:R.fingerprintUnit(units[0]),by:'Synthetic retained evidence',at:'2026-10-08T12:00:00Z',actual:{model:'Recorded test unit',lengthMm:6000,widthMm:3000,heightMm:2500,massKg:2000,source:'Synthetic prior record',verified:true,by:'Synthetic',at:'2026-10-08T12:00:00Z'},methodId:'building',methodEvidence:'Retained source'};c.S.loads[R.unitDocKey(units[0].id)]=doc;const before=JSON.stringify(c.S);
p=R.products931(a,[{item:'Toilet Block 6m',qty:'2'}],rows,{load:true});ok(p.length===2&&p.every(x=>x.qty==='1'),'different retained unit facts do not repeat whole demand');ok(p.some(x=>x.facts.some(f=>f.label==='Recorded actual')),'existing actual evidence remains visible');ok(R.productHtml931(p.find(x=>x.record)).includes('Saved transport evidence'),'saved evidence retained read-only');
const stale=R.info931(a,'Waste Tank 6m',{...units[0],item:'Waste Tank 6m'},[]);ok(!stale.actualVerified&&!stale.facts.some(f=>f.label==='Recorded actual'),'changed source identity cannot reuse prior actual facts');ok(R.productHtml931({...stale,units:[],qty:''}).includes('previous unit details'),'stale record retained as prior evidence');
c.gcUnits925=()=>[{...units[0],owner:'event-portables'}];p=R.products931(a,[{item:'Toilet Block 6m'}],[],{});ok(R.productHtml931(p[0]).includes('SUB-HIRED — Event Portables'),'per-unit supplier explicit');ok(JSON.stringify(c.S)===before,'rendering and binding do not mutate records');ok(R.share({}, {id:'a'}, {id:'b'}).fits===null,'no load-sharing approval');ok(R.assess([],null).fits===false,'no numerical safety approval');
ok(!/data-r924-(?:field|save|copy|slot|plan-save)|addEventListener\('click'/.test(src),'old edit controls and write handlers absent');
ok(R.links931([9,35,36,37,38,39,40]).includes('pp35–40')&&!R.links931([9,35,36,37,38,39,40]).includes('pp9–40'),'disjoint source citations do not imply a continuous page range');ok(R.links931([4,40]).includes('#page=40'),'each disjoint source section has its own working page link');
ok(src.includes('products931(a,dpItems({a,events:events||[]}),sources931(),{load:true})'),'drop-sheet information uses its movement events rather than the entire reference');
const result={checks,passed:checks,catalogueRows:R.guide.length,note:'Synthetic saved-evidence fixtures only. Source dimensions and catalogue figures are provenance-labelled; no operational writes.'};fs.writeFileSync(path.join(dir,'evidence/model931.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
