/* Author: Andrew Fisher. Focused native navigation probes. Every service mutation is blocked. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const assert=require('node:assert/strict'),Module=require('module');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));
const original=fs.readFileSync(hp,'utf8');assert.match(original,/const okPost = [^;]+;/);assert(original.includes('counts.blocked++;'));
hm._compile(original.replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++; (counts.blockedPaths ||= []).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const {open}=hm.exports;
async function guard(p){await p.evaluate(()=>{if(Array.isArray(SYNC.unsub)){SYNC.unsub.forEach(fn=>fn());SYNC.unsub=[];}window.__focus939Writes=[];window.bump=()=>{__focus939Writes.push('bump');throw Error('Keyboard navigation must not save');};if(SYNC.db&&typeof SYNC.db.doc==='function'){const native=SYNC.db.doc.bind(SYNC.db);SYNC.db.doc=(...args)=>{const doc=native(...args);for(const m of ['set','update','delete'])if(typeof doc[m]==='function')doc[m]=()=>{__focus939Writes.push(m);throw Error('Keyboard navigation must not write');};return doc;};}});}
async function assertNoWrites(p,s){assert.deepEqual(await p.evaluate(()=>__focus939Writes),[]);assert((s.counts.blockedPaths||[]).every(x=>x.method==='POST'&&x.origin==='https://tile.googleapis.com'&&x.path==='/v1/createSession'));}

const file=process.env.PAGE||'/workspace/private-focus939/candidate.html',out=process.env.FOCUS_OUT||'/workspace/private-focus939/evidence';fs.mkdirSync(out,{recursive:true});
const result={sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),checks:[],sessions:[]};
function note(name,pass,data){result.checks.push({name,pass,...(data?{data}:{})});console.log((pass?'PASS ':'FAIL ')+name);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));}
async function boundaries(p,selector,label){const ids=await p.locator(selector).evaluate(n=>{const f=[...n.querySelectorAll('a[href],button,input,select,textarea,summary,iframe,object,embed,audio[controls],video[controls],[contenteditable],[tabindex]')].filter(b=>b.tabIndex>=0&&!b.matches(':disabled')&&!b.closest('[hidden],[inert]')&&b.getClientRects().length&&getComputedStyle(b).visibility!=='hidden'&&(()=>{for(let d=b.parentElement?.closest('details:not([open])');d;d=d.parentElement?.closest('details:not([open])'))if(![...d.children].find(x=>x.tagName==='SUMMARY')?.contains(b))return false;return true;})());f[0].dataset.test939='first';f.at(-1).dataset.test939='last';return{count:f.length,first:{tag:f[0].tagName,text:f[0].textContent.slice(0,60)},last:{tag:f.at(-1).tagName,text:f.at(-1).textContent.slice(0,60),id:f.at(-1).id,type:f.at(-1).type}};});if(!ids.count)throw Error(label+' has no controls');await p.locator(selector+' [data-test939=first]').focus();await p.keyboard.press('Shift+Tab');await p.waitForTimeout(30);note(label+' reverse boundary stays inside',await p.locator(selector+' [data-test939=last]').evaluate(b=>document.activeElement===b),await p.evaluate(ids=>({expected:ids,active:document.activeElement.tagName,id:document.activeElement.id,text:document.activeElement.innerText?.slice(0,70)}),ids));await p.keyboard.press('Tab');await p.waitForTimeout(30);note(label+' forward boundary stays inside',await p.locator(selector+' [data-test939=first]').evaluate(b=>document.activeElement===b),await p.evaluate(ids=>({expected:ids,active:document.activeElement.tagName,id:document.activeElement.id,text:document.activeElement.innerText?.slice(0,70)}),ids));}
(async()=>{for(const width of [390,1440]){let s;try{s=await open({pageFile:file,hash:'#plant',W:width,H:900,mobile:width===390});const p=s.page;await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live',null,{timeout:120000});await guard(p);const before=await p.evaluate(()=>JSON.stringify(S));
 await p.evaluate(()=>holdAssets(()=>openAsset('WC20')));await p.waitForTimeout(500);const summaries=p.locator('#drawer .units925-unit summary');
 const unitButtons=p.locator('#drawer .units925-unit button').filter({hasText:'View photos'});note(width+' two native units available',await summaries.count()===2&&await unitButtons.count()===2);
 await summaries.first().focus();await p.keyboard.press('Tab');note(width+' Tab passes first summary to second unit',await unitButtons.nth(1).evaluate(b=>document.activeElement===b));await p.keyboard.press('Shift+Tab');note(width+' Shift+Tab returns to first summary',await summaries.first().evaluate(b=>document.activeElement===b));
 await p.keyboard.press('Enter');await p.waitForTimeout(100);note(width+' keyboard opens item details',await summaries.first().evaluate(b=>b.parentElement.open));await p.keyboard.press('Tab');note(width+' open summary permits onward navigation',await p.evaluate(()=>document.querySelector('#drawer .units925').contains(document.activeElement)&&document.activeElement.tagName!=='SUMMARY'),await p.evaluate(()=>({tag:document.activeElement.tagName,text:document.activeElement.textContent.slice(0,100)})));
 await boundaries(p,'#drawer',width+' equipment drawer');
 await p.locator('#drawer [data-test939=first]').focus();let later=false;for(let i=0;i<140;i++){await p.keyboard.press('Tab');const pos=await p.evaluate(()=>({last:document.activeElement.dataset.test939==='last',first:document.activeElement.dataset.test939==='first'}));if(pos.last)later=true;if(pos.first)break;}note(width+' forward keyboard reaches last drawer control',later);
 await p.evaluate(()=>smsDropBox(assetOf('WC20')));await p.waitForTimeout(120);await boundaries(p,'.drawer.on:not(#drawer)',width+' nested Text dialog');await p.keyboard.press('Escape');note(width+' Escape closes only upper layer',await p.evaluate(()=>!document.querySelector('.drawer.on:not(#drawer)')&&document.querySelector('#drawer').classList.contains('on')));await p.locator('#drawer [data-nav934-back]').click();note(width+' equipment Back exits',await p.evaluate(()=>!document.querySelector('#drawer').classList.contains('on')));
 await p.evaluate(()=>{go('timeline');timeline841Dialog('WC20');});await p.waitForTimeout(100);await boundaries(p,'#timeline841-dialog',width+' progress dialog');await p.locator('#timeline841-dialog [data-tl841-close]').click();note(width+' progress Close exits',await p.locator('#timeline841-dialog').count()===0);
 await p.evaluate(()=>{go('today');const b=document.querySelector('[data-tw840-detail="toilets"]');for(let n=b.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;b.click();});await p.waitForTimeout(100);await boundaries(p,'#gc500-work-dialog840',width+' Today breakdown');await p.keyboard.press('Escape');note(width+' Today Escape exits',await p.evaluate(()=>!document.querySelector('#gc500-work-dialog840').open));
 await p.evaluate(()=>{go('plant');holdAssets(()=>openAsset('FL01'));});await p.waitForTimeout(120);await p.locator('#drawer .r931').evaluate(el=>{for(let n=el;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;});const label=await p.locator('#drawer .r931').innerText();note(width+' unnamed supplier is readable in loading information',label.includes('SUB-HIRED — Supplier Not Named')&&!label.includes('supplier-not-named'));
 if(width===390){await p.locator('#drawer .r931').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'supplier-390.png')});}
 const print=await p.evaluate(()=>holdAssets(()=>{const actual=Loading931.referenceProducts931(assetOf('FL01')),productHtml=actual.map(p=>Loading931.productHtml931(p,true)).join('');const d=calendarDays().find(d=>d.deliveries.some(r=>r.a.key==='FL01')),r=d.deliveries.find(r=>r.a.key==='FL01'),html=dropPage(r.a,r.events,1,1,d,'deliveries');return{readable:productHtml.includes('SUB-HIRED — Supplier Not Named'),raw:/>SUB-HIRED — supplier-not-named</.test(html),labels:html.match(/SUB-HIRED[^<]{0,80}/g),itemInfo:html.includes('r931-paper'),owners:Loading931.referenceProducts931(assetOf('FL01')).map(p=>p.owner)};}));note(width+' native printed loading information is readable',print.readable&&!print.raw,print);note(width+' stored supplier identity unchanged',print.owners.includes('other:supplier-not-named'));
 await p.locator('#dclose').click();note(width+' native record unchanged',await p.evaluate(v=>JSON.stringify(S)===v,before));await assertNoWrites(p,s);note(width+' no runtime errors',s.errors.length===0);result.sessions.push({width,errors:s.errors,requests:s.counts});
 }catch(e){result.error=e.stack;console.error(e.stack);}finally{if(s)await s.browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));}if(result.error)break;}
 console.log(result.checks.filter(c=>c.pass).length+'/'+result.checks.length+' checks passed');if(result.error||result.checks.some(c=>!c.pass))process.exitCode=1;})();
