// Author: Andrew Fisher. Isolated handling records, source projection and native sheet checks; no live writes.
const fs=require('fs'),{open}=require('../../toolchain/harness/open_page');
(async()=>{const mob=!!process.env.MOB,s=await open({pageFile:process.env.PAGE,W:mob?390:1440,H:mob?844:900,mobile:mob,dpr:mob?2:1}),p=s.page,R=[];const ok=(name,pass)=>R.push({name,pass:!!pass});await p.waitForFunction(()=>typeof handling875Set==='function'&&SYNC.status==='live'&&todayWorkHealth840().ready);
 const X=await p.evaluate(()=>{
  const a=allAssets().find(x=>!x._cancelled&&(x.events||[]).some(e=>e.handling_source875)&&handling875Record(x)?.source),original=JSON.stringify(S),money=JSON.stringify([moneySummary(),fh866Model()]);const before={save,bump,whoAmI,mayWrite,capability,readonly:SYNC.readonly};window.save=()=>{};window.bump=()=>{};window.whoAmI=()=> 'Isolated check';window.mayWrite=()=>true;window.capability=()=> 'edit';SYNC.readonly=false;
  const out={source:!!a&&handling875Record(a).method==='onsite-crane',sourceNotModel:!['franna','crane-truck'].includes(handling875Record(a).method)};
  out.forklift=handling875Set(a.key,'forklift')&&handling875Sheet(a).includes('Forklift unloading');out.tilt=handling875Set(a.key,'tilt-tray')&&handling875Sheet(a).includes('Tilt tray unloading');out.tbc=handling875Set(a.key,'to-confirm')&&handling875Checks({checks:[],report:[],warnings:[]},[a]).warnings.length===1;out.notDoor=!loading872Editor(a).includes('value="tilt-tray" data-loading872');out.crane=handling875Set(a.key,'crane-truck')&&handling875Record(a).method==='crane-truck';out.franna=handling875Set(a.key,'franna')&&handling875Record(a).method==='franna';const ed=handling875Editor(a);out.editor=ed.includes('value="franna" checked')&&!ed.includes('value="crane-truck" checked');out.identity=loading872Editor(a).includes('Unloading method');out.nativeSheet=dpTruck({kind:'deliveries',rows:[{a,events:a.events||[]}]},'drv').includes('Franna crane unloading');out.drop=dropPage(a,a.events||[],1,1,{iso:todayIso()},'deliveries').includes('Franna crane unloading');out.checklist=handling875Checks({checks:[],report:[],warnings:[]},[a]).report.some(x=>x.includes('Franna crane unloading'));
  const seven=handling875Editor(a);out.seven=(seven.match(/type="radio"/g)||[]).length===7;const r=handling875Record(a),merged=mergeRecords({delivery:{[a.key]:{handling875:r}}},{delivery:{[a.key]:{state:'on site',by:'Other',set_at:new Date().toISOString()}}}).merged;out.merge=JSON.stringify(merged.delivery[a.key].handling875)===JSON.stringify(r);out.persist=toDocs('delivery')[a.key].handling875.method==='franna';out.retained=!deliveryEmpty({handling875:r});out.invalid=!handling875Set(a.key,'guess')&&!handling875Set('INVENTED','franna');out.legacy=handling875Set(a.key,'not-required')&&!handling875Sheet(a).includes('No unloading required')&&handling875Checks({checks:[],report:[],warnings:[]},[a]).warnings.length===1;out.none=handling875Set(a.key,'none')&&handling875Sheet(a).includes('No unloading required');handling875Set(a.key,'');out.clear=handling875Record(a).method==='';out.clearWarning=handling875Checks({checks:[],report:[],warnings:[]},[a]).warnings.length===1;
  out.money=JSON.stringify([moneySummary(),fh866Model()])===money;S=JSON.parse(original);Object.assign(window,{save:before.save,bump:before.bump,whoAmI:before.whoAmI,mayWrite:before.mayWrite,capability:before.capability});SYNC.readonly=before.readonly;out.restore=JSON.stringify(S)===original;
  const areas=todayWorkMetrics840(),groups=todayGroupDetails841(todayIso(),areas),types=todayTypeMetrics843(todayIso(),groups,todayWorkSummary842(todayIso(),areas,groups,todayFencingSummary841()));out.coverage=groups.__coverage.allRepresented&&types.coverage.allRepresented;out.sourceReview=!!DATA.schedule_review875.sha256&&DATA.schedule_review875.changed_cells>0;out.boqReview=groups.vms.notes.some(x=>x.includes('BOQ:'));const split=programmeDays().flatMap(d=>dpLoads(d)).filter(g=>String(g.truck_id||'').startsWith('schedule875-'));out.split=split.length>1&&split.every(g=>g.rows.length===1&&g.rows[0].a.charge_lines.every(l=>qtyOf(l)===1));out.splitIdentity=new Set(split.map(g=>g.truck_id)).size===split.length;out.splitEvidence=split.every(g=>g.dds.length===1&&g.time);
  return out;
 });for(const[n,v]of Object.entries(X))ok(n,v);await p.evaluate(()=>{go('timeline');state.day=todayIso();state.tlView='day';render();});await p.waitForTimeout(500);ok('reference handling visible',await p.locator('.handling875').count()>0);ok('no horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));if(process.env.OUT){fs.mkdirSync(process.env.OUT,{recursive:true});await p.locator('.handling875').first().scrollIntoViewIfNeeded();await p.screenshot({path:process.env.OUT+'/handling-'+(mob?'phone':'desktop')+'.png'});}ok('no runtime errors',s.errors.length===0);ok('no attempted live writes',s.counts.blocked===0);await s.browser.close();R.forEach(r=>console.log((r.pass?'PASS ':'FAIL ')+r.name));console.log((mob?'phone':'desktop')+': '+R.filter(r=>r.pass).length+'/'+R.length);if(R.some(r=>!r.pass))process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
