/* Author: Andrew Fisher. Captured native upload and fresh association guards; no network. */
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),units=require('../../v9.25_units_subhire_LIVE/units925.js');
const page=fs.readFileSync(process.env.PAGE||'/workspace/private-items933/candidate.html','utf8'),start=page.indexOf('const DROP_UPLOADS = new Set();'),end=page.indexOf('async function dropPhotoRemove(',start),native=page.slice(start,end),moduleSrc=fs.readFileSync(require.resolve('../items933.js'),'utf8');let count=0;
function fixture(){const a={key:'WC09'},u={id:'canonical',ref:'WC09',assetNo:'1268858',owner:'coates',item:'Block',physical:true},v={id:'other',ref:'WC09',assetNo:'1311146',owner:'coates',item:'Block',physical:true};const photos=[{id:'p1',unit:'1268858',slot:0},{id:'p2',unit:'1268858',slot:1}],c={window:{},Units925:units,holdAssets:f=>f(),assetOf:()=>a,gcModel925:()=>({rows:[u,v]}),dropPhotosOf:()=>photos,movedAway:()=>false,PHOTO_OUTBOX:new Map(),DROP_MAX:5,DROP_SLOTS:[],SYNC:{readonly:false,backend:{upload:true}},S:{operator:'Actor'},mayWrite:()=>true,whoAmI:()=> 'Actor',flash:()=>{},unitKey:x=>String(x||''),dropShrink:async f=>({blob:f,shrunk:false}),dropPhotoName:()=> 'test-photo.png',File,Blob,dropPhotoSlots:(ref,unit)=>Array.from({length:5},(_,i)=>photos.find(p=>p.unit===unit&&p.slot===i)||null),photoOutboxPut:async e=>{c.captures.push(e);return true;},photoDrawerRedraw:()=>{},photoSend:async()=>true,captures:[],messages:[]};vm.createContext(c);vm.runInContext(moduleSrc,c);c.Items933=c.window.Items933;vm.runInContext(native,c);c.u=u;c.v=v;c.photos=photos;c.add=async({slot=2,replace=null,home='canonical'}={})=>c.dropPhotoAdd('WC09',slot,new Blob(['x'],{type:'image/png'}),m=>c.messages.push(m),home,{unitId:'canonical',expected:c.Items933.signature(u),replace,actor:'Actor'});return c;}
async function test(name,fn){await fn();count++;console.log('PASS '+name);}
(async()=>{
 await test('native add queues exactly one canonical unit document without replacement',async()=>{const c=fixture();await c.add();assert.equal(c.captures.length,1);assert.equal(c.captures[0].unit,'canonical');assert.equal(c.captures[0].slot,2);assert.equal(c.captures[0].previousId,null);});
 await test('new external photo during shrink aborts Add without replacing it',async()=>{const c=fixture();c.dropShrink=async f=>{c.photos.push({id:'external',unit:'1268858',slot:2});return{blob:f,shrunk:false};};await c.add();assert.equal(c.captures.length,0);assert.match(c.messages.at(-1),/in use/);});
 await test('unit owner changed during shrink aborts Add',async()=>{const c=fixture();c.dropShrink=async f=>{c.u.owner='event-portables';return{blob:f,shrunk:false};};await c.add();assert.equal(c.captures.length,0);assert.match(c.messages.at(-1),/item changed/);});
 await test('replacement moved to another unit after rendering is refused',async()=>{const c=fixture(),expected=c.Items933.signature(c.u),replace={id:'p1',unit:'1268858',slot:0};c.photos[0].unit='1311146';assert.match(c.Items933.guard('WC09','canonical',0,expected,replace),/photo changed/);await c.add({slot:0,replace,home:'1268858'});assert.equal(c.captures.length,0);});
 await test('replacement moved to another slot after rendering is refused',async()=>{const c=fixture(),replace={id:'p1',unit:'1268858',slot:0};c.photos[0].slot=3;await c.add({slot:0,replace,home:'1268858'});assert.equal(c.captures.length,0);});
 await test('replacement cannot adopt a different physical unit even with current destination',async()=>{const c=fixture();c.photos[0].unit='1311146';await c.add({slot:0,replace:{id:'p1',unit:'1311146',slot:0},home:'1311146'});assert.equal(c.captures.length,0);});
 await test('explicit replacement keeps its native legacy home and exact previous photo id',async()=>{const c=fixture();await c.add({slot:0,replace:{id:'p1',unit:'1268858',slot:0},home:'1268858'});assert.equal(c.captures.length,1);assert.equal(c.captures[0].unit,'1268858');assert.equal(c.captures[0].previousId,'p1');});
 await test('permission lost during shrink aborts before outbox',async()=>{const c=fixture();c.dropShrink=async f=>{c.SYNC.readonly=true;return{blob:f,shrunk:false};};await c.add();assert.equal(c.captures.length,0);});
 await test('actor changed during shrink aborts before outbox',async()=>{const c=fixture();c.dropShrink=async f=>{c.whoAmI=()=> 'Other';return{blob:f,shrunk:false};};await c.add();assert.equal(c.captures.length,0);});
 await test('readonly refuses native upload without decoding',async()=>{const c=fixture();c.SYNC.readonly=true;c.dropShrink=()=>{throw Error('must not decode');};await c.add();assert.equal(c.captures.length,0);});
 await test('pending legacy upload reserves the same numbered slot',async()=>{const c=fixture();c.PHOTO_OUTBOX.set('old',{key:'WC09',unit:'1268858',slot:2});await c.add();assert.equal(c.captures.length,0);});
 console.log(count+' native guard checks passed');
})().catch(e=>{console.error(e);process.exitCode=1});
