const {chromium} = require('playwright');
(async () => { const b = await chromium.launch({executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox']});
  const p = await (await b.newContext({viewport: {width: 1400, height: 1000}})).newPage(); const errs = [];
  p.on('pageerror', e => errs.push(String(e).slice(0, 200))); p.on('dialog', d => d.dismiss());
  await p.goto('http://127.0.0.1:8814/e/edittokenedittoken1/#today', {waitUntil: 'load'}); await p.waitForTimeout(4000);
  const r = await p.evaluate(() => { S.operator = 'Test Runner'; const A = k => allAssets().find(x => x.key === k);
    const PN = pinsNow(); const o = {};
    o.userFixes = Object.keys(S.fixes || {}).length; o.pinsNow = Object.keys(PN).length; o.masterPins = Object.values(PN).filter(f => f.master).length; o.userKept = Object.keys(PN).filter(k => !PN[k].master);
    o.P38 = fixOf('P38'); o.P13u = fixOf('P13/u1097346'); o.P13 = fixOf('P13') && fixOf('P13').by;
    o.dayP38 = dayPinCell(A('P38')); o.dayT0022 = dayPinCell(A('T0022')).slice(0, 120);
    const pbP38 = pinBlock(A('P38')), pbWB04 = pinBlock(A('WB04')), pbT = pinBlock(A('T0022'));
    o.pbP38pin = /data-pin=/.test(pbP38); o.pbP38txt = pbP38.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').slice(0, 400);
    o.pbWB04pin = /data-pin=/.test(pbWB04); o.pbWB04area = /Area only/.test(pbWB04); o.pbTpin = /data-pin=/.test(pbT);
    o.where = whereText(A('P38')).also; o.whereWB = whereText(A('WB04')).also;
    let fl = null; const f0 = window.flash; window.flash = m => fl = m; pinMyLocation('P38'); window.flash = f0; o.guard = fl;
    o.board = satBoardPins().length; o.wc07 = fixOf('WC07');
    return o; });
  console.log(JSON.stringify(r, null, 1));
  await p.evaluate(() => go('map')); await p.waitForTimeout(3000); await p.screenshot({path: 'locfind/v685_map.png'});
  await p.evaluate(() => { location.hash = '#ref/P38'; }); await p.waitForTimeout(2500); await p.screenshot({path: 'locfind/v685_p38.png'});
  console.log('errors', JSON.stringify(errs)); await b.close(); })();
