/* Author: Andrew Fisher. Guide references, individual transport specifications and recorded load arrangements. */
(function(root){
'use strict';
const GUIDE=/* GUIDE924_DATA */[];
const GUIDE_URL='/f/Coates-GC500-2026/Coates_Load_Restraint_Guide_2023.pdf';
const METHODS=[
 {id:'mobile',name:'Mobile plant and access equipment',pages:[9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,40],words:'Match the actual machine, transport configuration and matrix row. Check rated manufacturer restraint points, lashing geometry, attachments and loose equipment. Lifting capacity is not transport mass.'},
 {id:'trailer',name:'Trailer-mounted equipment',pages:[9,35,36,37,38,39,40],words:'Match along-deck (up to 1850 kg) or across-deck (up to 1200 kg) method, actual trailer mass and anchor geometry. Secure drawbar and onboard equipment; do not mix chain and webbing on the same restrained item under these methods.'},
 {id:'skid-small',name:'Skid equipment up to 3.3 t',pages:[41,42,43,44,45,46],words:'Match the complete skid method and source row. Central longitudinal placement, looped corner-chain arrangement, stated anchor offsets and stability ratio apply. Two abreast is limited to the same unit, up to 1.65 t each, with aligned pockets.'},
 {id:'skid-medium',name:'Skid equipment 3.3–5.4 t',pages:[41,42,43,47,48],words:'Match the complete skid method: corner restraint plus the specified additional through-pocket chain, exact anchor geometry and stability. Two-abreast limits differ from a single unit.'},
 {id:'skid-large',name:'Large skid equipment',pages:[41,42,43,49,50],words:'The general and model-table requirements differ in places, including the 5475 kg row under the 5.5 t heading and through-pocket chain counts. Resolve the applicable model requirement with Coates/carrier before recording a restraint assessment; do not select chain count from mass alone.'},
 {id:'container',name:'Containerised generator',pages:[41,42,52],words:'For containerised sets below 22 t, match the configuration and all four engaged twistlocks. Fuel tanks must be completely empty or full. Check loading exclusion and actual complete transport mass; skid-only dimensions do not describe a trailer.'},
 {id:'toilet-base',name:'Portable toilet — base restraint',pages:[41,42,53],words:'For small portable toilets up to 700 kg, straps pass over the base inside lifting-point positions, with the specified anti-slip interface and no timber dunnage. Check actual tank state. The Merlin table row is a reference for that unit, not every FWF toilet.'},
 {id:'toilet-blocked',name:'Portable toilets — blocked two abreast',pages:[41,42,54],words:'For small toilets up to 700 kg: requires depicted base restraint and an engineered headboard at least 1 m high providing 30% payload blocking, with at most 200 mm cumulative gap. Merely touching toilets together does not establish the method.'},
 {id:'toilet-frame',name:'Portable toilets — internal-frame top restraint',pages:[41,42,55],words:'For small toilets up to 700 kg: top restraint applies only to toilets with the specified internal frames. Confirm frame, strap path, friction and tank state; do not apply to a frameless unit or an ablution building.'},
 {id:'cage',name:'Transport cages and stillages',pages:[41,42,56,57],words:'Up to 5 t; cages carrying more than 500 kg require a rated WLL/SWL. Check condition, contents containment, wheel/castor condition, blocking, interface and the angle-specific table. These pages do not establish stacking permission.'},
 {id:'barrier',name:'Water-filled barriers',pages:[58,59,67,68],words:'Barriers must be empty for transport. Match model, vehicle, unitised layers, blocking and anti-spearing restraint. The guide limits layers to three on semitrailers and two on tilt trays; new/filmed barriers need extra lashings. This is not a fence-panel or fencing-foot method.'},
 {id:'building',name:'Portable building',pages:[79,80,81,82,83,84,85],words:'Complete pre-transit checks; secure windows, doors, air conditioners and contents. Scope is at most 12 m × 3 m and 5000 kg; select the correct 2000 kg or 5000 kg diagram and check frame and engineered anchors. The p83 dimension conflict requires clarification. Roof straps are not load restraint; overhead lifting points are not tie-down points.'},
 {id:'wagon',name:'Building wagon',pages:[86,87,88],words:'Only dual-axle wagons up to 3500 kg, with axles 300–500 mm above the deck. Match the axle-loop method and geometry; protect brake lines. Body lifting points are not the specified axle-loop restraint anchors.'},
 {id:'ablution',name:'Named Melbourne ablution blocks',pages:[118,119,120,121,122],words:'Only the named BAU sewer, 16 User Number 14 and Event Tank Mount Number 13 configurations. Maximum 5000 kg. Check actual identity, shackle/anchor geometry and the correct four- or six-chain drawing. Resolve the p121 diagram/body dimension conflict with the source owner.'},
 {id:'cube',name:'SMC SL80 pallet light cube',pages:[123,124],words:'Only the named SMC SL80 configuration. Use specified anti-slip mat at every contact, minimum 8 mm and friction 0.6; secure mast/stabilisers and match the single-file or touching-pair arrangement. The 1100 kg scope maximum is not an actual weight.'},
 {id:'other',name:'Other equipment / engineering assessment',pages:[4,40],words:'Use the equipment-specific guide section or a documented alternative supported by testing/engineering advice. Record the actual source and arrangement; do not borrow an unrelated equipment method.'}
];
const txt=v=>String(v==null?'':v).trim();
const positive=v=>typeof v==='number'&&Number.isFinite(v)&&v>0;
const nonnegative=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
const has=v=>typeof v==='string'&&v.trim().length>0;
const fmtSpec=g=>[g.lengthMm,g.widthMm,g.heightMm].map(v=>positive(v)?v:'?').join(' × ')+' mm · '+(positive(g.massKg)?g.massKg+' kg':'mass not stated');
const esc924=v=>txt(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ownerKey(v){const n=txt(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(!n||n==='unknown'||n==='to-confirm')return 'unknown';if(n==='coates'||n==='coates-hire')return 'coates';if(n==='event-portables'||n==='event-portable')return 'event-portables';if(n==='premair'||n==='prem-air'||n==='prem-air-hire'||n==='premair-hire')return 'prem-air-hire';return n.startsWith('other-')?'other:'+n.slice(6):'other:'+n;}
function unitId(ref,owner,nativeId,assetNo){const n=txt(nativeId),a=txt(assetNo);return n||a?JSON.stringify([txt(ref),ownerKey(owner),n?'native':'asset',n||a]):'';}
// Bounded per-document key; the full identity is retained and checked on every read/write.
function keyHash(s){let a=1779033703,b=3144134277,c=1013904242,d=2773480762;for(let i=0;i<s.length;i++){const k=s.charCodeAt(i);a=b^Math.imul(a^k,597399067);b=c^Math.imul(b^k,2869860233);c=d^Math.imul(c^k,951274213);d=a^Math.imul(d^k,2716044179);}a=Math.imul(c^(a>>>18),597399067);b=Math.imul(d^(b>>>22),2869860233);c=Math.imul(a^(c>>>17),951274213);d=Math.imul(b^(d>>>19),2716044179);return [a^b^c^d,b^a,c^a,d^a].map(n=>(n>>>0).toString(16).padStart(8,'0')).join('');}
function unitDocKey(id){return 'restraint924-unit-'+keyHash(id);}
function stateLoads(){return typeof S==='undefined'?{}:S.loads||{};}
function getDoc(id){const d=stateLoads()[unitDocKey(id)];return d&&d.kind==='restraint924-unit'&&d.unitId===id?d:null;}
function guideCandidates(words){
 const w=txt(words).toLowerCase(),kva=w.match(/\b(\d+(?:\.\d+)?)\s*kva\b/),fork=w.match(/(\d+(?:\.\d+)?)\s*t\b/);
 let out=[];
 if(kva)out=GUIDE.filter(g=>/generator/i.test(g.description)&&new RegExp('\\b'+kva[1]+'\\s*kva\\b','i').test(g.description)&&(!/trailer/.test(w)||g.page>=35&&g.page<=38));
 else if(/trailer.*toilet|toilet.*trailer|fwf.*trailer/.test(w))out=GUIDE.filter(g=>/toilet.*trailer/i.test(g.description));
 else if(/\bfwf\b|fresh.?water.*flush/.test(w))out=GUIDE.filter(g=>/fresh water flush/i.test(g.description));
 else if(/\bvms\b|variable message/.test(w))out=GUIDE.filter(g=>/variable message/i.test(g.description));
 else if(/forklift|forktruck|fortruck/.test(w)&&fork)out=GUIDE.filter(g=>/forklift|forktruck|fortruck/i.test(g.description)&&new RegExp('\\b'+fork[1]+'\\s*t\\b','i').test(g.description));
 else if(/light.*tower/.test(w))out=GUIDE.filter(g=>/lighting tower/i.test(g.description));
 else if(/trailer.*toilet|toilet.*trailer/.test(w))out=GUIDE.filter(g=>/toilet.*trailer/i.test(g.description));
 else if(/scissor|boom|excavator|roller|pump|compressor|welder/.test(w)){const term=(w.match(/scissor|boom|excavator|roller|pump|compressor|welder/)||[])[0];out=GUIDE.filter(g=>g.description.toLowerCase().includes(term));}
 const knownMake=[...new Set(GUIDE.map(g=>txt(g.make).toLowerCase()).filter(Boolean))].find(m=>w.includes(m));if(knownMake)out=out.filter(g=>txt(g.make).toLowerCase()===knownMake);
 return out;
}
function methodCandidates(words){const w=txt(words).toLowerCase();let ids=/trailer[ -]?mounted|mounted.*trailer|with trailer/.test(w)?['trailer']:/trailer.*toilet|toilet.*trailer|fwf.*trailer/.test(w)?['trailer']:/building|ticket.?box|\b(?:office|crib|lunch|change).?room/.test(w)?['building','wagon']:/toilet.?block|pan.?block|ablution/.test(w)?['building','ablution']:/\bfwf\b|portable.?toilet|fresh.?water.*flush/.test(w)?['toilet-base','toilet-blocked','toilet-frame']:/water.*barrier|triton|armorzone/.test(w)?['barrier']:/generator|\bkva\b|\bskid\b|pump|compressor|welder/.test(w)?['skid-small','skid-medium','skid-large','container']:/light.*tower|light.*cube/.test(w)?['trailer','cube']:/\bvms\b|variable.?message|trailer/.test(w)?['trailer']:/forklift|forktruck|fortruck|excavator|roller|scissor|boom/.test(w)?['mobile']:/cage|stillage/.test(w)?['cage']:['other'];return METHODS.filter(m=>ids.includes(m.id));}
function nativeUnits(a){
 if(!a||!a.key)return [];
 if(typeof root.gcUnits925==='function'){const r=root.gcUnits925(a);if(Array.isArray(r))return r.filter(u=>u&&u.physical===true&&has(u.id)).map(u=>Object.assign({},u,{ref:a.key,owner:ownerKey(u.owner)}));}
 const out=[],seen=new Set(),lines=typeof chargeLines==='function'?chargeLines(a):[],subs=typeof subOf==='function'?subOf(a.key):[],native=typeof unitsOf==='function'?unitsOf(a.key):[];
 const add=(owner,assetNo,item,label,nativeId)=>{const id=unitId(a.key,owner,nativeId,assetNo);if(!id||seen.has(id))return;seen.add(id);out.push({id,ref:a.key,owner:ownerKey(owner),assetNo:txt(assetNo),item:txt(item),label:txt(label)||txt(item),physical:true});};
 if(typeof vms913BoardsOn==='function'&&typeof vms913Of==='function')for(const b of vms913BoardsOn(a)||[]){const v=vms913Of(b);add(v.co||'unknown',v.fleet||'','VMS',b.vms||b.name,'vms:'+b.key);}
 const allowed=Array.isArray(a._bookingNumbers801)&&typeof asset873Numbers==='function'?new Set(asset873Numbers(a).map(String)):null;
 for(const l of lines){if(!l.item)continue;const nums=typeof asset873Allocated==='function'?asset873Allocated(a,l.item):[];const fallback=nums.length?nums:typeof invItemNums==='function'?invItemNums(a,l.item):[];
  for(const no0 of fallback){const no=txt(no0);if(!no||/^MISCITEM$/i.test(no)||allowed&&!allowed.has(no)||out.some(u=>u.item==='VMS'&&u.assetNo===no))continue;const matches=subs.filter(s=>txt(s.no)===no);const n=native.find(u=>txt(u.asset_no)===no);add(matches.length===1?matches[0].co:matches.length>1?'unknown':'coates',no,l.item,n&&n.label,null);}
 }
 for(const s of subs){if(!s.no||allowed&&!allowed.has(txt(s.no))||out.some(u=>u.item==='VMS'&&u.assetNo===txt(s.no)))continue;const item=s.item||(lines.length===1?lines[0].item:'');const n=native.find(u=>txt(u.asset_no)===txt(s.no));add(s.co||'unknown',s.no,item,n&&n.label,null);}
 for(const n of native){if(!n.asset_no&&!n.id&&!n._id)continue;if(allowed&&!allowed.has(txt(n.asset_no)))continue;if(out.some(u=>u.assetNo&&u.assetNo===txt(n.asset_no)))continue;add(n.owner||'unknown',n.asset_no,n.item||n.label,n.label,n.id||n._id);}
 return out;
}
function unitsFor(a){const out=nativeUnits(a);if(Array.isArray(a._bookingNumbers801))return out;const ids=new Set(out.map(u=>u.id));for(const d of Object.values(stateLoads()))if(d&&d.kind==='restraint924-unit'&&d.slot===true&&d.ref===a.key&&has(d.unitId)&&!ids.has(d.unitId)){out.push({id:d.unitId,ref:a.key,owner:d.owner,assetNo:d.assetNo||'',item:d.item,label:d.label,physical:true,slot:true});ids.add(d.unitId);}return out;}
function methodIssues(u,v,m){const out=[];if(!m)return out;const max={trailer:1850,'toilet-base':700,'toilet-blocked':700,'toilet-frame':700,cage:5000,wagon:3500,'skid-small':3300,'skid-medium':5400,'skid-large':15300,building:5000,ablution:5000,cube:1100}[m.id];if(max&&positive(v.massKg)&&v.massKg>max)out.push('actual mass exceeds the selected method’s '+max+' kg scope');if(m.id==='container'&&positive(v.massKg)&&v.massKg>=22000)out.push('containerised generator method is for sets below 22000 kg');if(m.id==='building'&&(v.lengthMm>12000||v.widthMm>3000))out.push('building exceeds the method’s 12 m × 3 m scope');if(m.id!=='other'&&!methodCandidates(u.item+' '+u.label+' '+v.model+(/trailer[ -]?mounted|mounted.*trailer/i.test(txt(v.configuration))?' trailer-mounted':'')).some(x=>x.id===m.id))out.push('selected method does not match the equipment family');if(m.id.startsWith('skid-')&&(!positive(v.baseWidthMm)||v.baseWidthMm>v.widthMm||v.heightMm>2*v.baseWidthMm))out.push('record the skid support-base width and meet the guide’s 2:1 stability limit, or document an alternative engineering assessment');if(m.id==='cube'&&!/\bsmc\b.*\bsl[ -]?80\b|\bsl[ -]?80\b.*\bsmc\b/i.test(txt(v.model)))out.push('confirm the named SMC SL80 model');if(m.id==='ablution'&&!/BAU.*sewer|16.*user.*(?:number|no\.?|#)?\s*14|event.*tank.*mount.*(?:number|no\.?|#)?\s*13/i.test(txt(v.model)))out.push('confirm a named Melbourne appendix model');return out;}
function fingerprintUnit(u){return JSON.stringify([u.id,u.ref,ownerKey(u.owner),txt(u.assetNo),txt(u.item)]);}
function editableUnit(u,doc){const d=JSON.parse(JSON.stringify(doc||{}));if(d.kind!=='restraint924-unit'||d.unitId!==u.id||d.identity!==fingerprintUnit(u)){d.actual=Object.assign({},d.actual,{verified:false});d.methodConfirmed=false;}return d;}
function actualState(u,doc){const d=doc||getDoc(u.id),v=d&&d.actual||{},issues=[];
 if(!d||d.kind!=='restraint924-unit'||d.unitId!==u.id||d.identity!==fingerprintUnit(u))issues.push('unit identity or equipment type needs confirmation');
 if(!positive(v.lengthMm)||!positive(v.widthMm)||!positive(v.heightMm))issues.push('actual transport dimensions');
 if(!positive(v.massKg))issues.push('actual transport mass including contents');
 if(!has(v.model)||!has(v.configuration)||!has(v.source))issues.push('model, transport condition and evidence');
 if(v.verified!==true||!has(v.by)||!Number.isFinite(Date.parse(v.at)))issues.push('named specification verification');
 const m=d&&METHODS.find(x=>x.id===d.methodId);if(!m)issues.push('applicable restraint method');
 if(!d||d.methodConfirmed!==true||!has(d.methodEvidence))issues.push('method applicability and evidence');
 issues.push(...methodIssues(u,v,m));return {unit:u,doc:d,actual:v,method:m||null,verified:issues.length===0,issues};}
function planKey(day,id){return 'restraint924-load-'+keyHash(JSON.stringify([day,id]));}
function planFor(day,id){const x=stateLoads()[planKey(day,id)];return x&&x.kind==='restraint924-load'&&x.day===day&&x.loadId===id?x:null;}
function scopeFingerprint(states){return JSON.stringify(states.map(s=>{const d=s.doc||{},v=s.actual||{};return [fingerprintUnit(s.unit),d.kind||'',d.unitId||'',d.identity||'',d.at||'',d.by||'',...['model','lengthMm','widthMm','heightMm','massKg','baseWidthMm','configuration','source','verified','by','at'].map(k=>v[k]??null),d.guideId||'',d.methodId||'',d.methodConfirmed===true,d.methodEvidence||'',s.verified===true];}).sort((a,b)=>a[0].localeCompare(b[0])));}
function editablePlan(states,plan){const p=JSON.parse(JSON.stringify(plan||{}));if(p.scope!==scopeFingerprint(states)){p.vehicle=Object.assign({},p.vehicle,{axleChecked:false,anchorChecked:false,restraintChecked:false});p.completeCargo=false;p.placements=(p.placements||[]).map(x=>Object.assign({},x,{rotationConfirmed:false}));}return p;}
function assess(states,plan){
 const reasons=[],v=plan&&plan.vehicle||{},rows=plan&&Array.isArray(plan.placements)?plan.placements:[],known=states.filter(s=>s.verified);let mass=known.reduce((n,s)=>n+s.actual.massKg,0),maxHeight=0;
 if(!states.length)reasons.push('No individual units identified');if(new Set(states.map(s=>s.unit.id)).size!==states.length)reasons.push('A physical unit is listed more than once');if(known.length!==states.length)reasons.push('Verify every unit’s actual transport dimensions, mass and method');
 if(!plan||plan.scope!==scopeFingerprint(states))reasons.push('Load contents or specifications changed — review this arrangement');
 if(!has(v.id)||!has(v.source)||!positive(v.deckLengthMm)||!positive(v.deckWidthMm)||!positive(v.payloadKg)||!positive(v.deckHeightMm)||!positive(v.heightLimitMm)||!nonnegative(v.extraMassKg))reasons.push('Record the actual truck, usable deck, available payload, heights and support/restraint mass');
 for(const k of ['axle','anchor','restraint'])if(v[k+'Checked']!==true||!has(v[k+'Evidence']))reasons.push('Record the '+k+' assessment for this arrangement');
 if(!has(plan&&plan.by)||!Number.isFinite(Date.parse(plan&&plan.at)))reasons.push('Name and date the load assessment');
 const boxes=[];for(const s of states){if(!s.verified)continue;const matches=rows.filter(p=>p.unitId===s.unit.id);if(matches.length!==1){reasons.push('One position required for '+s.unit.label);continue;}const p=matches[0];if(!nonnegative(p.xMm)||!nonnegative(p.yMm)||!nonnegative(p.supportMm)||![0,90].includes(p.rotation)){reasons.push('Complete position and support height for '+s.unit.label);continue;}if(p.rotation===90&&p.rotationConfirmed!==true)reasons.push('Confirm rotated transport configuration for '+s.unit.label);const l=p.rotation===90?s.actual.widthMm:s.actual.lengthMm,w=p.rotation===90?s.actual.lengthMm:s.actual.widthMm;if(p.xMm+l>v.deckLengthMm||p.yMm+w>v.deckWidthMm)reasons.push(s.unit.label+' extends outside the usable deck');if(s.method.id==='trailer'&&p.rotation===90&&(s.actual.massKg>1200||l>v.deckLengthMm||w>2500))reasons.push('Across-deck small trailers require at most 1200 kg and a retracted transport width within 2500 mm');if(s.method.id.startsWith('skid-')&&p.rotation!==0)reasons.push('Skid guide methods require longitudinal placement; use a documented alternative for other orientations');const box={id:s.unit.id,x:p.xMm,y:p.yMm,l,w,state:s};if(boxes.some(b=>box.x<b.x+b.l&&box.x+box.l>b.x&&box.y<b.y+b.w&&box.y+box.w>b.y))reasons.push('Unit envelopes overlap');boxes.push(box);maxHeight=Math.max(maxHeight,v.deckHeightMm+p.supportMm+s.actual.heightMm);}
 for(const b of boxes.filter(b=>b.state.method.id.startsWith('skid-'))){const peers=boxes.filter(o=>o!==b&&b.x<o.x+o.l&&b.x+b.l>o.x);if(!peers.length){if(b.state.method.id==='skid-medium'&&b.state.actual.massKg<3300)reasons.push('Select the single-file method for the actual skid mass range');if(Math.abs(b.y+b.w/2-v.deckWidthMm/2)>1)reasons.push('Single skid units must be central on the deck');}else{const o=peers[0],limit={'skid-small':1650,'skid-medium':2700}[b.state.method.id],v1=b.state.actual,v2=o.state.actual;if(peers.length!==1||!limit||o.state.method.id!==b.state.method.id||v1.model!==v2.model||v1.configuration!==v2.configuration||b.l!==o.l||b.w!==o.w||b.x!==o.x||v1.massKg>limit||v2.massKg>limit||Math.abs((Math.min(b.y,o.y)+Math.max(b.y+b.w,o.y+o.w))/2-v.deckWidthMm/2)>1)reasons.push('Two-abreast skids require the same unit, aligned arrangement, central loading and the guide’s per-unit mass limits');}}
 if(rows.length!==states.length||new Set(rows.map(p=>p.unitId)).size!==rows.length)reasons.push('Load position list does not match the identified units');
 if(nonnegative(v.extraMassKg))mass+=v.extraMassKg;if(positive(v.payloadKg)&&mass>v.payloadKg)reasons.push('Recorded load mass exceeds the entered available payload');if(positive(v.heightLimitMm)&&maxHeight>v.heightLimitMm)reasons.push('Recorded loaded height exceeds the entered limit');
 const geometryFits=reasons.length===0;const review='Restraint approval required: the complete guide method, rated connections, lashing geometry, friction and blocking are not automatically validated. Recorded checks and envelope/payload calculations are planning evidence, not load approval.';return {fits:false,geometryFits,restraintValidated:false,why:[...new Set(reasons),review].join(' · '),massKg:known.length===states.length&&nonnegative(v.extraMassKg)?mass:null,knownMassKg:mass,maxHeightMm:known.length===states.length&&positive(v.deckHeightMm)&&boxes.length===states.length?maxHeight:null,reasons:[...new Set(reasons)]};
}
const API={guide:GUIDE,methods:METHODS,ownerKey,unitId,keyHash,unitDocKey,getDoc,guideCandidates,methodCandidates,unitsFor,actualState,fingerprintUnit,planKey,planFor,scopeFingerprint,editablePlan,editableUnit,methodIssues,assess};
root.Restraint924=API;root.getTransportUnits924=unitsFor;root.transportUnitId924=unitId;
if(typeof module!=='undefined'&&module.exports)module.exports=API;
if(typeof document==='undefined')return;
const E=esc924;
const link=(p,label)=>'<a href="'+GUIDE_URL+'#page='+p+'" target="_blank" rel="noopener">'+E(label||'Guide p'+p)+'</a>';
const methodLinks=m=>m.pages.map(p=>link(p,String(p))).join(', ');
const canEdit=()=>typeof capability==='function'&&capability()==='edit'&&!SYNC.readonly;
const field=(key,label,value,type='text')=>'<label class="f"><span>'+E(label)+'</span><input data-r924-field="'+key+'" type="'+type+'"'+(type==='number'?' min="0" step="any" inputmode="decimal"':'')+' value="'+E(value==null?'':value)+'"'+(canEdit()?'':' disabled')+'></label>';
const check=(key,label,value)=>'<label class="r924-check"><input type="checkbox" data-r924-field="'+key+'"'+(value===true?' checked':'')+(canEdit()?'':' disabled')+'><span>'+E(label)+'</span></label>';
function stamp(old){return new Date(Math.max(Date.now(),old&&Number.isFinite(Date.parse(old.at))?Date.parse(old.at)+1:0)).toISOString();}
function safeKey(key){return typeof docIdOf!=='function'||docIdOf(key).length<180;}
function writeDoc(key,data,identity){if(!safeKey(key)){flash('This identity is too long to store safely. Use a shorter unit label/owner identifier.');return false;}if(!mayWrite('transport specifications and load checks'))return false;const by=whoAmI();if(!by)return false;const old=stateLoads()[key];if(old&&(old.kind!==data.kind||(data.unitId&&old.unitId!==data.unitId)||(data.loadId&&(old.loadId!==data.loadId||old.day!==data.day)))){flash('Record identity conflict — nothing saved.');return false;}S.loads=S.loads||{};const at=stamp(old);if(data.actual){data.actual=Object.assign({},data.actual,{by,at});}S.loads[key]=Object.assign({},data,{by,at});try{bump();if(bump.kept===false)throw new Error('not kept');}catch(e){if(old===undefined)delete S.loads[key];else S.loads[key]=old;render();flash('Transport record was not saved. Review the unsaved notice and retry.');return false;}return true;}
function values(form){const o={};form.querySelectorAll('[data-r924-field]').forEach(n=>{o[n.dataset.r924Field]=n.type==='checkbox'?n.checked:n.type==='number'?(n.value.trim()===''?null:Number(n.value)):n.value.trim();});return o;}
function refWords(a){return (a.item_types||[]).join(' · ')||a.product||a.name||a.key;}
function sourceBlock(words,selected,limit=4){const cs=guideCandidates(words),sel=GUIDE.find(g=>g.id===selected);const shown=sel?[sel]:cs.slice(0,limit);return '<div class="r924-source"><b>Guide reference'+(shown.length===1?'':'s')+' · confirm actual unit</b>'+(shown.length?shown.map(g=>'<p>'+E((g.make?g.make+' · ':'')+g.description)+'<br><strong>'+E(fmtSpec(g))+'</strong> · '+link(g.page)+'</p>').join(''):'<p>No matching model specification in the guide. Record the actual unit from its plate, manufacturer or measured transport evidence.</p>')+(cs.length>limit&&!sel?'<p>'+cs.length+' possible reference rows; select the actual make/model in the equipment record.</p>':'')+'</div>';}
function unitEditor(u){const z=actualState(u),d=editableUnit(u,z.doc),v=d.actual||{},cs=guideCandidates(u.item+' '+u.label),g=GUIDE.find(g=>g.id===d.guideId),opts=g&&!cs.some(x=>x.id===g.id)?[g,...cs]:cs,ms=methodCandidates(u.item+' '+u.label);
 return '<details class="r924-unit" data-r924-unit="'+E(u.id)+'" data-r924-unit-scope="'+E(scopeFingerprint([z]))+'" data-r924-ref="'+E(u.ref)+'"><summary>'+E(u.label||u.item||'Unit')+(u.assetNo?' · '+E(u.assetNo):'')+' <span class="chip '+(z.verified?'act':'cand')+'">'+(z.verified?'Specifications recorded':'Transport specs to confirm')+'</span></summary><div class="r924-body"><p>'+E(u.owner)+' · '+E(u.ref)+'</p>'+sourceBlock(u.item+' '+u.label,d.guideId)+'<div class="form r924-form"><label class="f"><span>Guide model reference</span><select data-r924-field="guideId"'+(canEdit()?'':' disabled')+'><option value="">No exact guide model selected</option>'+opts.map(g=>'<option value="'+E(g.id)+'"'+(d.guideId===g.id?' selected':'')+'>'+E((g.make?g.make+' · ':'')+g.description+' · p'+g.page+' · '+g.massKg+' kg')+'</option>').join('')+'</select></label>'+(canEdit()&&opts.length?'<button type="button" class="btn" data-r924-copy>Use selected reference values in the draft</button>':'')+'<p class="hint">Length × width × height are the travelling envelope. Record the actual mass with fuel, water, attachments and contents included.</p><div class="row2">'+field('model','Actual make / model',v.model)+field('source','Evidence / document / measured source',v.source)+field('lengthMm','Transport length (mm)',v.lengthMm,'number')+field('widthMm','Transport width (mm)',v.widthMm,'number')+field('heightMm','Transport height (mm)',v.heightMm,'number')+field('massKg','Actual transport mass (kg)',v.massKg,'number')+field('baseWidthMm','Skid support-base width (mm, for skid methods)',v.baseWidthMm,'number')+'</div>'+field('configuration','Transport condition / tank state / included equipment',v.configuration)+'<label class="f"><span>Applicable restraint method</span><select data-r924-field="methodId"'+(canEdit()?'':' disabled')+'><option value="">Select the actual method</option>'+METHODS.map(m=>'<option value="'+m.id+'"'+(d.methodId===m.id?' selected':'')+'>'+E(m.name)+' · pp'+m.pages[0]+'–'+m.pages[m.pages.length-1]+'</option>').join('')+'</select></label>'+field('methodEvidence','Method applicability evidence / carrier or engineering reference',d.methodEvidence)+check('methodConfirmed','The selected method applies to this actual unit and transport configuration',d.methodConfirmed)+check('verified','I checked these actual dimensions and mass against the stated evidence',v.verified)+(canEdit()?'<button type="button" class="btn primary" data-r924-save>Save transport specifications</button>':'')+'</div>'+(d.by?'<p class="hint">Recorded by '+E(d.by)+' · '+E(d.at)+'</p>':'')+'<details><summary>Relevant loading and restraint sections</summary>'+ms.map(m=>'<p><b>'+E(m.name)+'</b><br>'+E(m.words)+'<br>Guide pages '+methodLinks(m)+'</p>').join('')+'</details></div></details>';}
function editorFull(a){if(!a||!a.key)return '';const us=unitsFor(a),ready=us.filter(u=>actualState(u).verified).length;return '<details class="loading872 r924" data-r924-ref="'+E(a.key)+'"><summary>Transport &amp; restraint · '+(us.length?ready+' of '+us.length+' units have specifications':'identify individual units')+'</summary><div class="r924-body">'+(!us.length?sourceBlock(refWords(a),''):'')+us.map(unitEditor).join('')+(!us.length?'<p>Guide sizes and weights are references until matched to the actual equipment. '+link(4,'Open the full guide')+'</p>':'')+(canEdit()&&typeof root.gcUnits925!=='function'?'<details class="r924-slot"><summary>Identify an unnumbered transport unit</summary><p class="hint">One physical unit per entry. Existing numbered units are listed above.</p><div class="form"><div class="row2">'+field('label','Unit label / distinguishing mark','')+field('item','Equipment type','')+'<label class="f"><span>Owner</span><select data-r924-field="owner"><option value="unknown">To confirm</option><option value="coates">Coates</option><option value="event-portables">Event Portables</option><option value="prem-air-hire">PremAir Hire</option></select></label></div><button type="button" class="btn" data-r924-slot>Create individual unit</button></div></details>':canEdit()?'<p class="hint">Use the individual Units section to identify another physical unit, then record its transport specifications here.</p>':'')+'</div></details>';}
function demobId(L){return 'demob924/'+JSON.stringify([L.kind,L.group||'',L.co||'',(L.stops||[]).map(s=>[s.r.key,s.part||'',!!s.tankOnly,(s.parts||[]).map(p=>[p.type,p.n,!!p.unknown,!!p.tank]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))]);}
function demobGroup(L){const refs=[...new Set((L.stops||[]).map(s=>s.r.key))];return {kind:'removals',_restraintId924:demobId(L),_restraintDemob924:L,rows:refs.map(key=>({a:assetOf(key)})).filter(r=>r.a)};}
function loadStates(g){const out=[],seen=new Set(),gaps=[];for(const r of g.rows||[]){let us=unitsFor(r.a);if(g._restraintDemob924){const L=g._restraintDemob924,parts=L.stops.filter(s=>s.r.key===r.a.key).flatMap(s=>s.parts||[]);if(L.kind==='toilets')us=us.filter(u=>u.owner==='coates');if(L.kind==='supplier')us=us.filter(u=>u.owner!=='coates'&&u.owner!=='unknown');const count=parts.reduce((n,p)=>n+(Number.isInteger(p.n)?p.n:0),0);if(parts.some(p=>p.unknown||!Number.isInteger(p.n)||p.n<0)||count!==us.length)gaps.push(r.a.key+': this pick-up portion needs the exact individual units allocated before a fit can be recorded');}if(Array.isArray(r.a._bookingNumbers801)){const set=new Set(asset873Numbers(r.a).map(String));us=us.filter(u=>u.assetNo&&set.has(u.assetNo));}if(!us.length)gaps.push(r.a.key+': identify individual units');for(const u of us){if(seen.has(u.id)){gaps.push('Repeated unit '+u.label);continue;}seen.add(u.id);out.push(actualState(u));}}return {states:out,gaps};}
function loadAssessment(day,id,g){const x=loadStates(g),p=planFor(day,id),a=assess(x.states,p);const gaps=x.gaps.slice();if(!p||p.completeCargo!==true)gaps.push('Confirm that every item, attachment and loose load is included');return Object.assign(a,{fits:false,geometryFits:a.geometryFits&&!gaps.length,why:[a.why,...gaps].filter(Boolean).join(' · '),states:x.states,plan:p,gaps});}
function calculationSummary(x){const v=x.plan&&x.plan.vehicle||{},n=x.states.filter(s=>s.verified).length;return '<p><b>Recorded calculations</b> · '+n+' of '+x.states.length+' identified units have checked specifications.</p><p>Identified load and supports: '+(x.massKg!==null?E(x.massKg)+' kg':'total unknown')+' · entered payload allowance: '+(positive(v.payloadKg)?E(v.payloadKg)+' kg':'to confirm')+'<br>Loaded height: '+(x.maxHeightMm!==null?E(x.maxHeightMm)+' mm':'to confirm')+' · entered limit: '+(positive(v.heightLimitMm)?E(v.heightLimitMm)+' mm':'to confirm')+'</p>'; }
function loadEditorFull(d,g){if(!g||!g.rows)return '';const id=g._restraintId924||ldId(d,g),x=loadAssessment(d.iso,id,g),p=editablePlan(x.states,x.plan),v=p.vehicle||{};
 return '<details class="loading872 r924" data-r924-day="'+E(d.iso)+'" data-r924-load="'+E(id)+'"><summary>Load dimensions &amp; restraint · '+(x.geometryFits?'envelope and payload checked · restraint review required':'checks to complete')+'</summary><div class="r924-body"><p class="hint">'+E(x.why)+'</p>'+calculationSummary(x)+g.rows.map(r=>editor(r.a)).join('')+'<details class="r924-truck" data-r924-scope="'+E(scopeFingerprint(x.states))+'"><summary>Actual truck and load arrangement</summary><div class="form"><div class="row2">'+field('id','Truck / trailer registration',v.id)+field('source','Vehicle specification source',v.source)+field('deckLengthMm','Usable deck length (mm)',v.deckLengthMm,'number')+field('deckWidthMm','Usable deck width (mm)',v.deckWidthMm,'number')+field('payloadKg','Available added-load allowance (kg)',v.payloadKg,'number')+field('extraMassKg','Additional dunnage / restraint mass (kg)',v.extraMassKg,'number')+field('deckHeightMm','Travelling deck height (mm)',v.deckHeightMm,'number')+field('heightLimitMm','Applicable overall height limit (mm)',v.heightLimitMm,'number')+'</div><p class="hint">Position is measured from the front-left of the usable deck. No stacking or overhang is assessed. Enter zero explicitly where appropriate.</p>'+x.states.map(s=>{const q=(p.placements||[]).find(r=>r.unitId===s.unit.id)||{};return '<fieldset data-r924-position="'+E(s.unit.id)+'"><legend>'+E(s.unit.label+(s.unit.assetNo?' · '+s.unit.assetNo:''))+'</legend><div class="row2">'+field('xMm','Along deck (mm)',q.xMm,'number')+field('yMm','Across deck (mm)',q.yMm,'number')+field('supportMm','Support height (mm)',q.supportMm,'number')+'<label class="f"><span>Rotation</span><select data-r924-field="rotation"'+(canEdit()?'':' disabled')+'><option value="0"'+(q.rotation!==90?' selected':'')+'>Longitudinal</option><option value="90"'+(q.rotation===90?' selected':'')+'>90° across deck</option></select></label></div>'+check('rotationConfirmed','Rotated transport configuration is permitted by the applicable method',q.rotationConfirmed)+'</fieldset>';}).join('')+['axle','anchor','restraint'].map(k=>field(k+'Evidence',k==='axle'?'Axle distribution / point-load assessment':k==='anchor'?'Anchor ratings and geometry assessment':'Whole restraint arrangement assessment',v[k+'Evidence'])+check(k+'Checked','I checked the '+k+' assessment for this truck and entered arrangement',v[k+'Checked'])).join('')+check('completeCargo','Every physical unit, attachment and loose item on this load is accounted for',p.completeCargo)+(canEdit()?'<button type="button" class="btn primary" data-r924-plan-save>Save load arrangement</button>':'')+'<p class="hint">The calculation checks recorded envelopes, payload and loaded height only. It does not approve axles, anchors or restraint; the carrier’s complete assessment and driver pre-departure checks remain required. Automatic load-sharing approval is disabled.</p></div></details></div></details>';}
function editor(a){if(!a||!a.key)return '';const us=unitsFor(a),n=us.filter(u=>actualState(u).verified).length;return '<details class="loading872 r924" data-r924-lazy="unit" data-r924-ref="'+E(a.key)+'"><summary>Transport &amp; restraint · '+(us.length?n+' of '+us.length+' units have specifications':'identify individual units')+'</summary><div class="r924-body"></div></details>';}
function loadEditor(d,g){if(!g||!g.rows)return '';const id=g._restraintId924||ldId(d,g),x=loadAssessment(d.iso,id,g);return '<details class="loading872 r924" data-r924-lazy="load" data-r924-day="'+E(d.iso)+'" data-r924-load="'+E(id)+'"><summary>Load dimensions &amp; restraint · '+(x.geometryFits?'envelope and payload checked · restraint review required':'checks to complete')+'</summary><div class="r924-body"></div></details>';}
document.addEventListener('toggle',e=>{const el=e.target;if(!el.matches||!el.matches('details[data-r924-lazy]')||!el.open||el.dataset.r924Ready)return;let html='';if(el.dataset.r924Lazy==='unit'){const a=assetOf(el.dataset.r924Ref);if(a)html=editorFull(a);}else{const g=findLoad(el.dataset.r924Day,el.dataset.r924Load);if(g)html=loadEditorFull({iso:el.dataset.r924Day},g);}const tmp=document.createElement('div');tmp.innerHTML=html;const body=tmp.querySelector('.r924-body');if(body){el.querySelector('.r924-body').innerHTML=body.innerHTML;el.dataset.r924Ready='1';}},true);
function summary(a){const us=unitsFor(a);if(!us.length){const cs=guideCandidates(refWords(a));return a.key+': individual transport specs to confirm'+(cs.length?' · '+cs.length+' guide model reference'+(cs.length===1?'':'s')+' available':'');}return us.map(u=>{const s=actualState(u),v=s.actual;return a.key+' · '+(u.assetNo||u.label)+': '+(s.verified?v.lengthMm+' × '+v.widthMm+' × '+v.heightMm+' mm; '+v.massKg+' kg; '+s.method.name:'actual transport specs / method to confirm');}).join(' | ');}
function printDetails(a){const us=unitsFor(a);if(!us.length)return '<p>'+E(summary(a))+'</p>'+sourceBlock(refWords(a),'',1);return us.map(u=>{const z=actualState(u),d=z.doc||{},v=z.actual;return '<div class="r924-print-unit"><b>'+E(a.key+' · '+(u.assetNo||u.label))+'</b><p>'+E(z.verified?v.model+' · '+v.lengthMm+' × '+v.widthMm+' × '+v.heightMm+' mm · '+v.massKg+' kg':'Actual transport specifications not verified')+'</p>'+(z.verified?'<p>'+E(v.configuration)+' · Evidence: '+E(v.source)+'</p>':sourceBlock(u.item+' '+u.label,d.guideId,1))+(z.method?'<p><b>'+E(z.method.name)+'</b> · '+E(d.methodConfirmed?'applicability recorded':'applicability to confirm')+'<br>'+E(z.method.words)+'<br>Guide pages '+methodLinks(z.method)+'</p>':'<p>Applicable method to confirm · '+methodCandidates(u.item+' '+u.label).map(m=>E(m.name)+' '+link(m.pages[0])).join('; ')+'</p>')+'</div>';}).join('');}
function addChecks(m,assets){if(!m)return m;const seen=new Set();for(const a of assets.filter(Boolean)){if(seen.has(a.key))continue;seen.add(a.key);const us=unitsFor(a),missing=!us.length||us.some(u=>!actualState(u).verified);const text=summary(a);if(missing)m.warnings.push({key:a.key,text});else m.report.push(text);}if(!m.checks.some(c=>c.id==='transport-recorded924'))m.checks.push({id:'transport-recorded924',text:'I checked the actual unit identities, travelling dimensions and mass, truck payload/axles, rated anchors and the complete applicable restraint arrangement with the driver.'});return m;}
function findLoad(day,id){if(id.startsWith('demob924/')){const lists=[trucks816(day,'all')];if(typeof DM816!=='undefined'&&DM816.branch&&DM816.branch!=='all')lists.push(trucks816(day,DM816.branch));for(const ls of lists){const same=ls.filter(L=>demobId(L)===id);if(same.length>1)return null;if(same.length===1)return demobGroup(same[0]);}return null;}const d=programmeDays().find(x=>x.iso===day);if(!d)return null;const ls=dpLoads(d);if(id.startsWith('pair924/')){let ids;try{ids=JSON.parse(id.slice(8));}catch(e){return null;}if(!Array.isArray(ids)||ids.length!==2||ids[0]===ids[1])return null;const parts=ids.map(k=>ls.find(g=>ldId(d,g)===k));if(parts.some(x=>!x))return null;return {rows:parts.flatMap(g=>g.rows),_restraintId924:id,kind:'deliveries'};}return ls.find(g=>ldId(d,g)===id)||null;}
document.addEventListener('input',e=>{const f=e.target.closest('.r924-unit');if(f&&!['verified','methodConfirmed'].includes(e.target.dataset.r924Field)){for(const k of ['verified','methodConfirmed']){const c=f.querySelector('[data-r924-field="'+k+'"]');if(c)c.checked=false;}}const p=e.target.closest('.r924-truck');if(p&&!/Checked$|^completeCargo$/.test(e.target.dataset.r924Field||''))p.querySelectorAll('input[data-r924-field$="Checked"]').forEach(n=>n.checked=false);});
document.addEventListener('click',e=>{const b=e.target.closest('[data-r924-save],[data-r924-copy],[data-r924-slot],[data-r924-plan-save]');if(!b)return;e.preventDefault();if(!canEdit())return;
 if(b.hasAttribute('data-r924-slot')){const box=b.closest('.r924'),v=values(b.closest('.r924-slot')),a=assetOf(box.dataset.r924Ref);if(!a||!has(v.label)||!has(v.item)){flash('Name the individual unit and equipment type.');return;}const owner=ownerKey(v.owner),id=unitId(a.key,owner,'slot:'+crypto.randomUUID(),'');const u={id,ref:a.key,owner,assetNo:'',label:v.label,item:v.item};if(writeDoc(unitDocKey(id),{kind:'restraint924-unit',unitId:id,ref:a.key,owner,assetNo:'',label:v.label,item:v.item,slot:true,identity:fingerprintUnit(u),actual:{verified:false}}))flash('Individual transport unit recorded.');return;}
 if(b.hasAttribute('data-r924-plan-save')){const box=b.closest('[data-r924-load]'),g=findLoad(box.dataset.r924Day,box.dataset.r924Load);if(!g)return;const form=b.closest('.r924-truck'),currentScope=scopeFingerprint(loadStates(g).states);if(form.dataset.r924Scope!==currentScope){form.querySelectorAll('input[type="checkbox"]').forEach(n=>n.checked=false);flash('Unit data changed while this arrangement was open. Close and reopen the transport section, then check the arrangement again.');const outer=box.closest('[data-r924-lazy]')||box;delete outer.dataset.r924Ready;return;}const v=values(form),placements=[...form.querySelectorAll('[data-r924-position]')].map(f=>Object.assign(values(f),{unitId:f.dataset.r924Position})).map(p=>Object.assign(p,{rotation:Number(p.rotation)}));const vehicle={};for(const k of ['id','source','deckLengthMm','deckWidthMm','payloadKg','extraMassKg','deckHeightMm','heightLimitMm','axleEvidence','axleChecked','anchorEvidence','anchorChecked','restraintEvidence','restraintChecked'])vehicle[k]=v[k];const data={kind:'restraint924-load',day:box.dataset.r924Day,loadId:box.dataset.r924Load,scope:currentScope,vehicle,placements,completeCargo:v.completeCargo===true};if(writeDoc(planKey(data.day,data.loadId),data))flash('Load arrangement recorded; review the calculations and outstanding restraint assessment.');return;}
 const box=b.closest('[data-r924-unit]'),a=assetOf(box.dataset.r924Ref),u=a&&unitsFor(a).find(x=>x.id===box.dataset.r924Unit);if(!u){flash('This physical unit changed. Reopen its record before saving transport specifications.');return;}if(b.hasAttribute('data-r924-save')&&box.dataset.r924UnitScope!==scopeFingerprint([actualState(u)])){box.querySelectorAll('input[type="checkbox"]').forEach(n=>n.checked=false);const outer=box.closest('[data-r924-lazy]');if(outer)delete outer.dataset.r924Ready;flash('The unit or its recorded specifications changed while this form was open. Close and reopen the transport section, then confirm the actual unit again.');return;}const v=values(box),g=GUIDE.find(x=>x.id===v.guideId);
 if(b.hasAttribute('data-r924-copy')){if(!g){flash('Select the matching source row first.');return;}for(const k of ['lengthMm','widthMm','heightMm','massKg'])box.querySelector('[data-r924-field="'+k+'"]').value=g[k]==null?'':g[k];box.querySelector('[data-r924-field="baseWidthMm"]').value='';box.querySelector('[data-r924-field="model"]').value=(g.make?g.make+' ':'')+g.description;box.querySelector('[data-r924-field="source"]').value='Coates 2023 guide p'+g.page+' — confirm against actual unit';box.querySelector('[data-r924-field="verified"]').checked=false;box.querySelector('[data-r924-field="methodConfirmed"]').checked=false;return;}
 const actual={};for(const k of ['model','source','lengthMm','widthMm','heightMm','massKg','baseWidthMm','configuration','verified'])actual[k]=v[k];if(v.verified&&(![actual.lengthMm,actual.widthMm,actual.heightMm,actual.massKg].every(positive)||![actual.model,actual.source,actual.configuration].every(has))){flash('Complete the actual model, transport dimensions/mass, condition and evidence before marking checked.');return;}if(v.methodConfirmed&&(!METHODS.some(m=>m.id===v.methodId)||!has(v.methodEvidence))){flash('Select the method and record its applicability evidence.');return;}const data={kind:'restraint924-unit',unitId:u.id,ref:u.ref,owner:u.owner,assetNo:u.assetNo,item:u.item,label:u.label,slot:!!u.slot,identity:fingerprintUnit(u),guideId:g?g.id:'',actual,methodId:v.methodId,methodConfirmed:v.methodConfirmed===true,methodEvidence:v.methodEvidence};if(writeDoc(unitDocKey(u.id),data)){box.dataset.r924UnitScope=scopeFingerprint([actualState(u)]);flash('Transport specifications saved for '+(u.assetNo||u.label)+'.');}
});
function pairId(a,b){return 'pair924/'+JSON.stringify([a.id,b.id].sort());}
function share(d,a,b){const id=pairId(a,b),g={rows:a.g.rows.concat(b.g.rows),kind:'deliveries',_restraintId924:id},x=loadAssessment(d.iso,id,g);return {fits:x.fits?true:null,why:x.why,planId:id};}
API.share=share;API.editor=editor;API.loadEditor=loadEditor;API.loadStates=loadStates;API.loadAssessment=loadAssessment;API.summary=summary;API.findLoad=findLoad;API.demobId=demobId;API.demobGroup=demobGroup;
const beforeUnit=unitBlockInline;unitBlockInline=function(a){return beforeUnit.apply(this,arguments)+editor(a);};
const beforeActions=timeline841Actions;timeline841Actions=function(d,g,n){return beforeActions.apply(this,arguments)+(g.kind==='deliveries'||g.kind==='removals'?loadEditor(d,g):'');};
const beforeFlow=flow891Build;flow891Build=function(d){const m=beforeFlow.apply(this,arguments);m.share=m.share.map(s=>Object.assign({},s,share(d,s.a,s.b)));return m;};
const beforeFlowCard=flow891Card;flow891Card=function(d){let h=beforeFlowCard.apply(this,arguments);h=h.replace('weights and dimensions are not on the page, so nothing is suggested','a verified combined arrangement has not been recorded, so sharing is not suggested');const m=flow891Day(d);if(m.share.length){h+='<details class="loading872 r924"><summary>Review combined-load proposals · '+m.share.length+'</summary>'+m.share.slice(0,12).map(s=>'<details><summary>Load '+s.a.n+' + Load '+s.b.n+' · '+E(s.area)+'</summary>'+loadEditor(d,{rows:s.a.g.rows.concat(s.b.g.rows),kind:'deliveries',_restraintId924:pairId(s.a,s.b)})+'</details>').join('')+(m.share.length>12?'<p>First 12 combinations shown. Review further combinations with the transport planner.</p>':'')+'</details>';}return h;};
const beforeDriver=driverModel826;driverModel826=function(iso,only){const m=beforeDriver.apply(this,arguments),sel=selectedDriver826(iso,only);if(!m||!sel)return m;addChecks(m,sel.loads.flatMap(x=>x.g.rows.map(r=>r.a)));const d=programmeDays().find(x=>x.iso===iso);if(d)for(const x of sel.loads){const r=loadAssessment(iso,ldId(d,x.g),x.g);if(!r.fits)m.warnings.push({text:'Load '+(x.i+1)+' transport arrangement: '+r.why});else m.report.push('Load '+(x.i+1)+': '+r.why);}return m;};
const beforeDemob=demobModel826;demobModel826=function(iso,br,what,n){const selected=selectedDemob826(iso,br,what,n),m=addChecks(beforeDemob.apply(this,arguments),selected.flatMap(l=>l.stops.map(s=>assetOf(s.r.key))));if(m)for(const L of selected){const g=demobGroup(L),x=loadAssessment(iso,g._restraintId924,g);if(x.fits)m.report.push('Pick-up load '+L.n+': '+x.why);else m.warnings.push({text:'Pick-up load '+L.n+' transport arrangement: '+x.why});}return m;};
const beforeTrucks=trucksHtml816;trucksHtml816=function(Dy,T){return beforeTrucks.apply(this,arguments)+(T.length?'<details class="loading872 r924"><summary>Transport specifications and restraint for these pick-up loads</summary>'+T.map(L=>'<details><summary>Pick-up load '+L.n+' · '+E(L.group)+'</summary>'+loadEditor({iso:Dy.iso||DM816.sel},demobGroup(L))+'</details>').join('')+'</details>':'');};
function printPages(d,g,loadNumber){const chunks=[];for(const r of g.rows||[]){const temp=document.createElement('div');temp.innerHTML=printDetails(r.a);const units=[...temp.querySelectorAll('.r924-print-unit')];if(units.length)chunks.push(...units.map(n=>n.outerHTML));else chunks.push('<div class="r924-print-unit">'+temp.innerHTML+'</div>');}if(!chunks.length)return '';const pages=[];for(let i=0;i<chunks.length;i+=2)pages.push(chunks.slice(i,i+2));const id=g._restraintId924||ldId(d,g),fit=loadAssessment(d.iso,id,g);return pages.map((body,i)=>'<div class="dp-page dp-drv r924-paper"><header class="dp-hd"><div class="dp-hd-l"><b>Coates</b><span>Industrial Solutions</span></div><div class="dp-hd-m"><span>Load '+loadNumber+' · '+E(d.iso)+'</span><h1>Transport &amp; restraint</h1></div><div class="dp-hd-r">'+(i+1)+' of '+pages.length+'</div></header><section class="dp-sec"><p><b>'+E(fit.geometryFits?'Recorded envelope and payload calculations pass · restraint approval required':'Transport arrangement checks outstanding')+'</b></p><p>'+E(fit.why)+'</p>'+calculationSummary(fit)+body.join('')+'</section><div class="dp-ft">Author: Andrew Fisher · Load '+loadNumber+' · Restraint supplement '+(i+1)+' of '+pages.length+' · Driver’s actual loading and pre-departure checks remain required.</div></div>').join('');}
const beforePage=dpPage;dpPage=function(d,g,doc,i,n){return beforePage.apply(this,arguments)+(doc==='drv'?printPages(d,g,i):'');};
const beforeDemobSheet=sheet816;sheet816=function(iso,L){return beforeDemobSheet.apply(this,arguments)+printPages({iso},demobGroup(L),L.n);};
const beforeDrop=dropPage;dropPage=function(a){return beforeDrop.apply(this,arguments).replace('<div class="rs-go">','<div class="loading872-sheet"><b>Transport &amp; restraint</b><p>'+E(summary(a))+'</p>'+link(4,'Full guide and applicable equipment sections')+'</div><div class="rs-go">');};
const beforeDocs=docsBlock;docsBlock=function(a){return beforeDocs.apply(this,arguments)+'<p class="hint">Transport reference: '+methodCandidates(refWords(a)).map(m=>E(m.name)+' · '+link(m.pages[0])).join('; ')+'</p>';};
function catalogueHtml(q){const query=txt(q).toLowerCase(),rows=GUIDE.filter(g=>!query||((g.make?g.make+' ':'')+g.description+' '+g.page).toLowerCase().includes(query));return '<p>'+rows.length+' source rows · values describe the listed equipment, not confirmed GC500 assets.</p>'+rows.slice(0,40).map(g=>'<p><b>'+E((g.make?g.make+' · ':'')+g.description)+'</b><br>'+E(fmtSpec(g))+' · '+link(g.page)+'</p>').join('')+(rows.length>40?'<p>Refine the search to see the remaining source rows.</p>':'');}
const beforeRenderDocs=renderDocs;renderDocs=function(){const r=beforeRenderDocs.apply(this,arguments),pane=document.getElementById('pane-docs');if(pane&&!pane.querySelector('#r924-catalogue'))pane.insertAdjacentHTML('beforeend','<details id="r924-catalogue" class="loading872 r924"><summary>Load restraint · equipment size and weight references</summary><div class="r924-body"><label class="f"><span>Find a make or equipment type in the guide</span><input type="search" data-ro data-r924-catalogue placeholder="Cummins, forklift, toilet, VMS"></label><div data-r924-catalogue-results>'+catalogueHtml('')+'</div></div></details>');return r;};
document.addEventListener('input',e=>{if(e.target.matches('[data-r924-catalogue]'))e.target.closest('#r924-catalogue').querySelector('[data-r924-catalogue-results]').innerHTML=catalogueHtml(e.target.value);});
const css=document.createElement('style');css.id='restraint924-style';css.textContent=`
.r924{width:100%;min-width:0;margin:8px 0}.r924 .r924-body{padding:10px;min-width:0}.r924 p{margin:6px 0;overflow-wrap:anywhere}.r924 details{margin:8px 0}.r924 summary{cursor:pointer;line-height:1.5}.r924 .row2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.r924 .f{display:grid;gap:4px;min-width:0;margin:5px 0}.r924 input,.r924 select{min-width:0;width:100%;max-width:100%;box-sizing:border-box;font:inherit;color:var(--text,#172d2b);background:var(--paper,#fff)}.r924 input:not([type=checkbox]),.r924 select{min-height:40px;padding:8px 10px;border:1px solid var(--hair,#d7dbde);border-radius:8px}.r924 select option{background:#fff;color:#172d2b}.r924 .r924-check{display:flex;align-items:flex-start;gap:8px;margin:9px 0}.r924 .r924-check input{width:18px;flex:0 0 18px;margin-top:3px}.r924-source{border-left:3px solid #df9200;padding:5px 9px;margin:8px 0}.r924 fieldset{min-width:0}.r924-unit>summary{padding:5px 0}.r924-paper .r924-print-unit{border-top:1px solid #c9d0cc;padding:10px 0;break-inside:avoid}.r924-paper p{font-size:11px;line-height:1.4;overflow-wrap:anywhere;margin:6px 0}.r924-paper .r924-source p{font-size:10px}.r924-paper{color:#172d2b;background:#fff}.r924-paper a{color:#174c42;text-decoration:underline}.r924-paper .dp-sec{overflow:visible}.r924-paper .dp-ft{margin-top:auto}
@media(max-width:500px){.r924 .row2{grid-template-columns:1fr}.r924 .r924-body{padding:8px}.r924 select,.r924 input{font-size:16px}}
`;document.head.appendChild(css);
})(typeof window!=='undefined'?window:globalThis);
