// Author: Andrew Fisher. Association isolation and upload race guards; no service writes.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
let passed=0;
const a={key:'WC09',product:'Toilet',discipline:'Toilets & amenities'};
const fwf={id:'fwf-0085',item:'FWF',owner:'event-portables',assetNo:'0085',physical:true};
const block={id:'block-1268858',item:'Toilet Block 6m',owner:'coates',assetNo:'1268858',physical:true};
let model={rows:[fwf,block],groups:[{item:'FWF',quantity:4,units:[fwf]},{item:'Pee Panel',quantity:6,units:[]},{item:'Toilet Block 6m',quantity:2,units:[block]}]},assets={WC09:a},models={WC09:model},all=[],owned=true,token='native-one',away=false,sub=[];
const ctx={module:{exports:{}},holdAssets:f=>f(),assetOf:ref=>assets[ref],gcModel925:a=>models[a.key],Units925:{owner:x=>x,company:x=>({'event-portables':'Event Portables',coates:'Coates',unknown:'Owner not recorded'}[x]||x)},quantitySubhire964Read:()=>owned?{valid:true,row:{owner:'event-portables',company:'Event Portables',source:'Q6845'}}:{valid:false,reason:'Not recorded'},quantitySubhire964Token:()=>token,toiletItem962:()=>({arrived:6,done:6}),deliveryAsOf:()=>({}),todayIso:()=> '2026-10-09',itemRows:()=>[],subOf:()=>sub,movedAway:()=>away,PHOTO_OUTBOX:new Map(),dropPhotosOf:()=>all,DROP_MAX:4,SYNC:{readonly:false},photoFor:()=>({state:'missing'}),DROP_SLOTS:[]};
ctx.S={loads:{},stamps:{},by:{}};let changes=0;ctx.mayWrite=()=>true;ctx.whoAmI=()=> 'Andrew Fisher';ctx.stampIt=(coll,key,by)=>{ctx.S.stamps[coll+'/'+key]='2026-10-09T07:00:00Z';ctx.S.by[coll+'/'+key]=by;};ctx.bump=()=>{changes++;};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/items965.js','utf8'),ctx);const I=ctx.module.exports;
function test(name,f){try{f();passed++;}catch(e){e.message=name+': '+e.message;throw e;}}
const j=x=>JSON.parse(JSON.stringify(x));
const pee=()=>I.group(a,'Pee Panel',model),id=I.token('WC09','Pee Panel');
test('only supported quantity items',()=>{assert(pee());assert.equal(I.group(a,'FWF',model),null);assert.equal(I.group(a,'Toilet Block 6m',model),null);});
test('Pee owner and progress remain item-specific',()=>assert.deepEqual(j([pee().quantity,pee().received,pee().installed,pee().company]),[6,6,6,'Event Portables']));
test('group token is not a physical identity',()=>{assert.equal(JSON.parse(id).length,3);assert.equal(pee().physical,undefined);assert.equal(pee().assetNo,undefined);});
test('bad and cross-reference tokens refused',()=>{for(const x of ['006','{}','[]','["quantity-item965","WC09",6]','["quantity-item965","WC09","Pee Panel","extra"]'])assert.equal(I.parse(x),null);assert.equal(I.read('WC31',id),null);});
test('only photos of the selected group',()=>{all=[{id:'pee',unit:id,slot:0},{id:'fwf',unit:'fwf-0085',slot:0},{id:'block',unit:'1268858',slot:0},{id:'location',unit:'',slot:0}];assert.deepEqual(j(I.photos(pee(),all).map(p=>p.id)),['pee']);});
test('existing location photos stay unassigned',()=>assert.deepEqual(j(I.assigned(a,model,all).map(p=>p.id)),['pee']));
test('pending uploads reserve the exact group slot',()=>{ctx.PHOTO_OUTBOX.set('pending',{key:'WC09',unit:id,slot:1});assert.equal(I.firstFree(pee(),all,I.pending('WC09'),4),2);});
test('fresh target accepted',()=>assert.equal(I.guard('WC09',id,2,I.signature(pee()),null),''));
test('used and invalid slots refused',()=>{for(const n of [0,1,4,-1,1.5])assert.notEqual(I.guard('WC09',id,n,I.signature(pee()),null),'');});
test('same old photo replacement accepted',()=>assert.equal(I.guard('WC09',id,0,I.signature(pee()),{id:'pee',unit:id,slot:0}),''));
test('cross item and stale replacement refused',()=>{for(const r of [{id:'fwf',unit:'fwf-0085',slot:0},{id:'pee',unit:id,slot:1},{id:'gone',unit:id,slot:0}])assert.notEqual(I.guard('WC09',id,0,I.signature(pee()),r),'');});
test('quantity changes during image processing refused',()=>{const s=I.signature(pee());model.groups[1].quantity=7;assert.notEqual(I.guard('WC09',id,2,s,null),'');model.groups[1].quantity=6;});
test('ownership changes during image processing refused',()=>{const s=I.signature(pee());token='native-two';assert.notEqual(I.guard('WC09',id,2,s,null),'');token='native-one';});
test('withdrawn ownership never borrows another supplier',()=>{owned=false;assert.equal(pee().owner,'unknown');owned=true;});
test('a new physical identity blocks aggregate card',()=>{model.groups[1].units=[{physical:true,item:'Pee Panel',assetNo:'NEW'}];assert.equal(pee(),null);model.groups[1].units=[];});
test('ambiguous duplicate groups refused',()=>{model.groups.push({...model.groups[1]});assert.equal(pee(),null);model.groups.pop();});
test('unknown or invalid quantity refused',()=>{for(const v of [null,-1,0,6.5,'6']){model.groups[1].quantity=v;assert.equal(pee(),null);}model.groups[1].quantity=6;});
test('cancelled and moved upload scopes refused',()=>{const s=I.signature(pee());a._cancelled=true;assert.notEqual(I.guard('WC09',id,2,s,null),'');delete a._cancelled;away=true;assert.notEqual(I.guard('WC09',id,2,s,null),'');away=false;});
test('quantity cards do not offer physical identity fields',()=>{const h=I.card(a,pee());assert.match(h,/data-item965-add/);assert.match(h,/SUB-HIRED — Event Portables/);assert.doesNotMatch(h,/data-unit925-id|data-item933-add|Identify another|1268858|0085/);});
test('readonly quantity card has no upload or delete',()=>{ctx.SYNC.readonly=true;const h=I.card(a,pee());assert.doesNotMatch(h,/data-item965-add|data-item933-remove/);ctx.SYNC.readonly=false;});
test('selected header isolates owners and identities',()=>{const h=I.selection(a,model.groups[1],model).html;assert.match(h,/Event Portables/);assert.doesNotMatch(h,/1268858|0085|Coates/);const f=I.selection(a,model.groups[0],model).html;assert.match(f,/0085/);assert.doesNotMatch(f,/1268858/);});
const mat={key:'T0025',product:'Trakmat',discipline:'Ground protection'},u={id:'["T0025","coates","asset","TRAKMAT2.4X1.1"]',owner:'coates',assetNo:'TRAKMAT2.4X1.1',nativeId:'',physical:true,item:'Trakmat'},mm={rows:[u],groups:[{item:'Trakmat',quantity:20,units:[u]}]};assets.T0025=mat;models.T0025=mm;
test('known legacy Trakmat catalogue code retains old photos',()=>{const g=I.group(mat,'Trakmat',mm);assert.deepEqual(j(g.aliases),[I.token('T0025','Trakmat'),u.id,u.assetNo]);assert.deepEqual(j(I.photos(g,[{id:'old',unit:u.assetNo},{id:'new',unit:g.id},{id:'other',unit:'0085'}]).map(p=>p.id)),['old','new']);});
test('catalogue alias cannot hide a real serial',()=>{u.assetNo='1234567';assert.equal(I.group(mat,'Trakmat',mm),null);u.assetNo='TRAKMAT2.4X1.1';u.nativeId='fleet-entry';assert.equal(I.group(mat,'Trakmat',mm),null);u.nativeId='';});
test('legacy replacement retains original photo home',()=>{const g=I.group(mat,'Trakmat',mm);all=[{id:'legacy',unit:u.assetNo,slot:0}];assert.equal(I.guard('T0025',g.id,0,I.signature(g),{id:'legacy',unit:u.assetNo,slot:0}), '');});
const wb={key:'WB01',product:'WFB',discipline:'Water-filled barriers'},wm={rows:[],groups:[{item:'TL2',quantity:12,units:[]}]};assets.WB01=wb;models.WB01=wm;
test('water barriers support quantity photos without serial prompts',()=>{const g=I.group(wb,'TL2',wm);assert.equal(g.quantity,12);assert.equal(g.owner,'coates');assert.match(I.card(wb,g),/No fleet numbers/);});
test('single group explicit subhire shown; conflicting owners stay unknown',()=>{sub=[{co:'event-portables'}];assert.equal(I.group(wb,'TL2',wm).owner,'event-portables');sub.push({co:'another-company'});assert.equal(I.group(wb,'TL2',wm).owner,'unknown');sub=[];});
test('no blank note record created',()=>{assert(I.noteSave('WC09',id,'',I.noteToken('WC09','Pee Panel'),I.signature(pee())).unchanged);assert.equal(Object.keys(ctx.S.loads).length,0);});
test('site note is a separate stamped item record',()=>{const r=I.noteSave('WC09',id,'Beside gate',I.noteToken('WC09','Pee Panel'),I.signature(pee()));assert(r.ok);assert.equal(changes,1);assert.equal(I.noteRead('WC09','Pee Panel').note,'Beside gate');assert.equal(I.noteRead('WC09','FWF'),null);assert.equal(I.noteRead('WC31','Pee Panel'),null);assert.equal(Object.keys(ctx.S.loads).length,1);assert.equal(Object.keys(ctx.S.stamps).length,1);});
test('repeat identical site note is idempotent',()=>{assert(I.noteSave('WC09',id,'Beside gate',I.noteToken('WC09','Pee Panel'),I.signature(pee())).unchanged);assert.equal(changes,1);});
test('stale note and wrong item scopes refused',()=>{assert.equal(I.noteSave('WC09',id,'New','null',I.signature(pee())).ok,false);assert.equal(I.noteSave('WC31',id,'New',I.noteToken('WC09','Pee Panel'),I.signature(pee())).ok,false);assert.equal(changes,1);});
test('note write requires named current edit session',()=>{ctx.SYNC.readonly=true;assert.equal(I.noteSave('WC09',id,'New',I.noteToken('WC09','Pee Panel'),I.signature(pee())).ok,false);ctx.SYNC.readonly=false;ctx.whoAmI=()=>'';assert.equal(I.noteSave('WC09',id,'New',I.noteToken('WC09','Pee Panel'),I.signature(pee())).ok,false);ctx.whoAmI=()=> 'Andrew Fisher';});
test('note text escapes in readonly detail view',()=>{I.noteSave('WC09',id,'<script>site</script>',I.noteToken('WC09','Pee Panel'),I.signature(pee()));ctx.SYNC.readonly=true;assert.match(I.noteHtml(pee()),/&lt;script&gt;/);assert.doesNotMatch(I.noteHtml(pee()),/<form|<script>/);ctx.SYNC.readonly=false;});
test('note rejects oversized value and reports local save failure',()=>{assert.equal(I.noteSave('WC09',id,'x'.repeat(1001),I.noteToken('WC09','Pee Panel'),I.signature(pee())).ok,false);ctx.bump.kept=false;const r=I.noteSave('WC09',id,'Recorded locally',I.noteToken('WC09','Pee Panel'),I.signature(pee()));assert.equal(r.kept,false);assert.match(r.reason,/device/);ctx.bump.kept=true;});
test('noncanonical photo target refused',()=>assert.equal(I.read('WC09','["quantity-item965", "WC09", "Pee Panel"]'),null));
test('reserved note key cannot overwrite an unrelated document',()=>{const k=I.noteKey('WC09','Pee Panel');ctx.S.loads[k]={kind:'another-record',note:'keep'};assert.equal(I.noteSave('WC09',id,'New',I.noteToken('WC09','Pee Panel'),I.signature(pee())).ok,false);assert.equal(ctx.S.loads[k].note,'keep');});
console.log(JSON.stringify({passed,source:'items965.js',writes:0}));
