/* Author: Andrew Fisher. Focused native navigation probes. Every service mutation is blocked. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const assert=require('node:assert/strict'),Module=require('module');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));
const original=fs.readFileSync(hp,'utf8');assert.match(original,/const okPost = [^;]+;/);assert(original.includes('counts.blocked++;'));
hm._compile(original.replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++; (counts.blockedPaths ||= []).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const {open}=hm.exports;
async function guard(p){await p.evaluate(()=>{if(Array.isArray(SYNC.unsub)){SYNC.unsub.forEach(fn=>fn());SYNC.unsub=[];}window.__exits946Writes=[];window.bump=()=>{__exits946Writes.push('bump');throw Error('Keyboard navigation must not save');};if(SYNC.db&&typeof SYNC.db.doc==='function'){const native=SYNC.db.doc.bind(SYNC.db);SYNC.db.doc=(...args)=>{const doc=native(...args);for(const m of ['set','update','delete'])if(typeof doc[m]==='function')doc[m]=()=>{__exits946Writes.push(m);throw Error('Keyboard navigation must not write');};return doc;};}});}
async function assertNoWrites(p,s){assert.deepEqual(await p.evaluate(()=>__exits946Writes),[]);assert((s.counts.blockedPaths||[]).every(x=>x.method==='POST'&&x.origin==='https://tile.googleapis.com'&&x.path==='/v1/createSession'));}

const file=process.env.PAGE||'/workspace/private-exits946/candidate.html',out=process.env.EXIT_OUT||'/workspace/private-exits946/evidence';fs.mkdirSync(out,{recursive:true});const result={sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),checks:[],sessions:[]};
function note(name,pass,data){result.checks.push({name,pass,...(data?{data}:{})});console.log((pass?'PASS ':'FAIL ')+name);fs.writeFileSync(out+'/results.json',JSON.stringify(result,null,2));}
async function visibleExits(p,selector){return p.locator(selector).evaluate(n=>[...n.querySelectorAll('.exit946 button')].map(b=>{const r=b.getBoundingClientRect();return{text:b.textContent,x:r.x,y:r.y,right:r.right,bottom:r.bottom,visible:r.width>0&&r.height>0&&r.x>=0&&r.right<=document.documentElement.clientWidth+1&&r.y>=0&&r.bottom<=visualViewport.height+1}}));}
async function captions(p){return p.evaluate(()=>{const nav=document.getElementById('tabs'),buttons=[...nav.querySelectorAll('[data-tab]')],saved=buttons.map(b=>b.getAttribute('aria-selected')),fail=[];for(const selected of buttons){buttons.forEach(b=>b.setAttribute('aria-selected',String(b===selected)));for(const b of buttons){const tw=b.querySelector('.tw'),r=b.getBoundingClientRect(),walker=document.createTreeWalker(tw,NodeFilter.SHOW_TEXT);for(let t=walker.nextNode();t;t=walker.nextNode()){const range=document.createRange();range.selectNodeContents(t);for(const x of range.getClientRects())if(x.width&& (x.left<r.left-1||x.right>r.right+1||x.bottom>nav.getBoundingClientRect().bottom+1))fail.push({selected:selected.dataset.tab,label:b.dataset.tab,left:x.left,right:x.right,buttonRight:r.right,bottom:x.bottom,navBottom:nav.getBoundingClientRect().bottom});}}}buttons.forEach((b,i)=>b.setAttribute('aria-selected',saved[i]));return{width:document.documentElement.clientWidth,fail,navWidth:nav.scrollWidth,navClient:nav.clientWidth};});}
(async()=>{for(const width of [390,1440]){let session;try{session=await open({pageFile:file,hash:'#today',W:width,H:844,mobile:width===390});const p=session.page;await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live',null,{timeout:120000});await guard(p);const before=await p.evaluate(()=>JSON.stringify(S));await p.evaluate(()=>{window.__prints946=0;window.__done946=0;window.print=()=>{__prints946++}});
 for(const w of width===390?[390,360,320]:[1440]){await p.setViewportSize({width:w,height:844});await p.waitForTimeout(80);const x=await captions(p);note(w+' all primary captions fit in every selected state',x.fail.length===0&&x.navWidth<=x.navClient+1,x);}await p.setViewportSize({width,height:844});await p.waitForTimeout(100);if(width===390)await p.screenshot({path:out+'/tabs-390.png'});
 const model=await p.evaluate(()=>holdAssets(()=>JSON.stringify(modelSnap826(driverModel826('2026-10-14',null)))));
 for(const exit of ['Close','Back','Escape']){await p.evaluate(()=>holdAssets(()=>drvCheck826('2026-10-14',null,()=>{__done946++})));await p.waitForTimeout(100);const controls=await visibleExits(p,'#drv782');note(width+' driver '+exit+' stays visible above scrolled checks',controls.length===2&&controls.every(x=>x.visible),controls);note(width+' driver checks remain unchecked and approval disabled',await p.locator('#drv782').evaluate(n=>[...n.querySelectorAll('input[type=checkbox]')].every(c=>!c.checked)&&n.querySelector('.b-go').disabled));if(width===390&&exit==='Close')await p.screenshot({path:out+'/driver-390.png'});if(exit==='Escape')await p.keyboard.press('Escape');else await p.locator(exit==='Back'?'#drv782 [data-nav934-back]':'#drv782 [data-print946-close]').click();note(width+' driver '+exit+' exits without approval',await p.locator('#drv782').count()===0&&await p.evaluate(()=>__done946===0));}
 note(width+' driver warnings and readiness model unchanged',await p.evaluate(expected=>holdAssets(()=>JSON.stringify(modelSnap826(driverModel826('2026-10-14',null))))===expected,model));
 for(const [ref,exit] of [['GN01','Close'],['P55','Back']]){await p.evaluate(ref=>{go('plant');holdAssets(()=>openAsset(ref))},ref);await p.waitForTimeout(500);await p.locator('#dropSheet').click();await p.waitForSelector('.printask',{timeout:25000});const x=await p.evaluate(()=>({inner:innerWidth,client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,visual:visualViewport.width,box:document.querySelector('.printask-box').getBoundingClientRect().toJSON(),sheet:[...document.querySelector('#dayprint').children].filter(n=>n.tagName!=='STYLE').map(n=>n.getBoundingClientRect().width)}));note(width+' '+ref+' print warning fits viewport',x.scroll<=x.client+1&&x.box.x>=0&&x.box.right<=x.client+1,x);const exits=await visibleExits(p,'.printask');note(width+' '+ref+' top Back and Close are reachable',exits.length===2&&exits.every(x=>x.visible),exits);note(width+' '+ref+' A4 sheet retains its measurement width',x.sheet.some(w=>w>650),x.sheet);if(width===390)await p.screenshot({path:out+'/'+ref+'-390.png'});await p.locator(exit==='Back'?'.printask [data-nav934-back]':'.printask [data-print946-close]').click();note(width+' '+ref+' '+exit+' returns to equipment without printing',await p.evaluate(()=>!document.querySelector('.printask')&&!document.body.classList.contains('printing-day')&&__prints946===0&&document.getElementById('drawer').classList.contains('on')));await p.locator('#dclose').click();}
 await p.evaluate(()=>{window.__cancel946=0;printAsk({failed:1,over:[]},()=>{__prints946++},()=>{__cancel946++})});await p.keyboard.press('Escape');note(width+' preflight Escape uses native cancellation once',await p.evaluate(()=>__cancel946===1&&__prints946===0&&!document.querySelector('.printask')));
 note(width+' native record unchanged',await p.evaluate(v=>JSON.stringify(S)===v,before));await assertNoWrites(p,session);note(width+' zero runtime errors',session.errors.length===0,session.errors);result.sessions.push({width,errors:session.errors,requests:session.counts});
 }catch(e){result.error=e.stack;console.error(e.stack);}finally{if(session)await session.browser.close();fs.writeFileSync(out+'/results.json',JSON.stringify(result,null,2));}if(result.error)break;}
 console.log(result.checks.filter(c=>c.pass).length+'/'+result.checks.length+' checks passed');if(result.error||result.checks.some(c=>!c.pass))process.exitCode=1;})();
