// Author: Andrew Fisher. Read-only local Creator and playback validation.
const {chromium}=require('playwright');
const fs=require('fs'), path=require('path'),assert=require('assert/strict');
const root=__dirname, out=process.env.MOTION_OUTPUT||'/workspace/gc500-motion-preview';
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(path.join(out,'frames'),{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-gpu']});const evidence={author:'Andrew Fisher',checks:[],errors:[],externalRequests:[],creator:[]};
try{const context=await browser.newContext({viewport:{width:1280,height:900},deviceScaleFactor:1});await context.route('**/*',r=>{const url=new URL(r.request().url());if(url.pathname==='/__motion/preview.html')return r.fulfill({path:path.join(root,'GC500-motion-preview.html'),contentType:'text/html'});if(url.pathname.startsWith('/__creator/')){const name=path.basename(url.pathname);const file=path.join('/workspace/private-v809-support/lottie-link',name);if(['index.html','app.js','styles.css'].includes(name))return r.fulfill({path:file,contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html'})}evidence.externalRequests.push(r.request().url());return r.abort()});
const p=await context.newPage();p.on('pageerror',e=>evidence.errors.push(e.message));p.on('console',e=>{if(e.type()==='error')evidence.errors.push(e.text())});
await p.goto('https://gc500-production.up.railway.app/__motion/preview.html');await p.waitForFunction(()=>window.gc500MotionPreview?.getState().ready);await p.waitForTimeout(1400);let s=await p.evaluate(()=>gc500MotionPreview.getState());assert(s.frames.every(x=>x.paused));assert.equal(s.loaded,3);evidence.checks.push('Three main players load and stop after one play; marker-size examples use static SVGs');
await p.screenshot({path:path.join(out,'desktop.png')});
await p.locator('#replay').click();await p.waitForTimeout(250);s=await p.evaluate(()=>gc500MotionPreview.getState());assert(s.frames.some(x=>!x.paused));evidence.checks.push('Replay restarts visible main examples');await p.waitForTimeout(1300);
await p.locator('#still').check();assert(await p.locator('#replay').isDisabled());assert((await p.evaluate(()=>gc500MotionPreview.getState())).frames.every(x=>x.paused));evidence.checks.push('Still view stops animation and disables replay');
await p.locator('#still').uncheck();
for(let f=0;f<60;f++){await p.evaluate(frame=>gc500MotionPreview.seek(Math.min(frame,35)),f);await p.screenshot({path:path.join(out,'frames',String(f).padStart(3,'0')+'.png')});}
for(const name of ['equipment-selected','equipment-complete','photo-saved']){const anchor=p.locator(`[data-animation="${name}"] [data-download="project"]`);const [dl]=await Promise.all([p.waitForEvent('download'),anchor.click()]);assert.equal(dl.suggestedFilename(),name+'.project.json');}evidence.checks.push('Three editable project downloads work');
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(150);await p.screenshot({path:path.join(out,'phone.png'),fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#replay').click();await p.waitForTimeout(80);s=await p.evaluate(()=>gc500MotionPreview.getState());assert(s.frames.filter(x=>!x.visible).every(x=>x.paused));evidence.checks.push('Phone fits 390px with offscreen animation paused');assert(await p.locator('.mini svg').evaluateAll(nodes=>nodes.every(n=>n.getBoundingClientRect().width===44&&n.getBoundingClientRect().height===44)));evidence.checks.push('Marker-size SVGs fit their 44px boxes');
await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(80);s=await p.evaluate(()=>gc500MotionPreview.getState());assert(s.reduced&&s.frames.every(x=>x.paused));assert(await p.locator('#replay').isDisabled());assert(await p.locator('#still').isDisabled());evidence.checks.push('System reduced motion settles all players without an override');await p.screenshot({path:path.join(out,'phone-still.png'),fullPage:true});
assert.equal(evidence.externalRequests.length,0);evidence.previewExternalRequests=evidence.externalRequests.slice();evidence.checks.push('Self-contained preview makes zero HTTP requests');
// Import into an isolated local copy of the actual editor; never the user's tab/storage.
const editor=await context.newPage();await editor.goto('https://gc500-production.up.railway.app/__creator/index.html');await editor.waitForFunction(()=>window.LottieCreator);await editor.locator('#loop-btn').click();
for(const name of ['equipment-selected','equipment-complete','photo-saved']){const project=JSON.parse(fs.readFileSync(path.join(root,'assets',name+'.project.json')));await editor.locator('#import-file').setInputFiles(path.join(root,'assets',name+'.project.json'));await editor.waitForFunction(n=>window.LottieCreator.getProject().name===n,project.name);const current=await editor.evaluate(()=>({project:LottieCreator.getProject(),lottie:LottieCreator.getLottie()}));assert.equal(current.project.layers.length,project.layers.length);const expected=JSON.parse(fs.readFileSync(path.join(root,'assets',name+'.creator-export.json')));assert.deepEqual(current.lottie.layers,expected.layers);assert.equal(current.lottie.op,36);evidence.creator.push({asset:name,layers:project.layers.length,actualEditorExportLayersExact:true});}
await editor.screenshot({path:path.join(out,'creator-import.png')});evidence.checks.push('All three native projects import into actual Creator and export exact layers');
assert.equal(evidence.errors.length,0);fs.writeFileSync(path.join(root,'evidence.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({checks:evidence.checks,creator:evidence.creator,errors:evidence.errors}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
