/* Author: Andrew Fisher. Public read-only notes and captured native editing, never service writes. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),Module=require('module'),crypto=require('crypto');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));
hm._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;').replace('const errors = [];',"const errors = [], warnings=[];page.on('console',m=>{if(m.type()==='warning')warnings.push(m.text());});").replace('return {browser, page, errors, counts};','return {browser, page, errors, counts,warnings};'),hp);const {open}=hm.exports;
const pageFile=process.env.PAGE,out=process.env.OUT947;assert(pageFile&&out,'Provide PAGE and private OUT947');fs.mkdirSync(out,{recursive:true});
(async()=>{const results=[];for(const W of [1440,390]){console.log('START947 '+W);const s=await open({pageFile,hash:'#today',W,H:W===390?844:1000,mobile:W===390}),p=s.page;try{
 await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live'&&typeof correctionNote947==='function',null,{timeout:90000});
 const initial=await p.evaluate(()=>holdAssets(()=>{window.__note947State=JSON.stringify(S);openAsset('WC20');const raw=assetOf('WC20')._note,parts=correctionNote947(raw),fold=document.querySelector('#drawer .note947-original');return{modern:!!document.querySelector('#drawer .sum816'),recognised:!!parts,folded:!!fold&&!fold.open,completeEvidence:fold?.querySelector('pre').textContent===parts?.evidence,reconstruction:parts&&parts.prefix+parts.marker+parts.evidence+parts.suffix===raw,rawLength:raw.length,recordSame:JSON.stringify(S)===__note947State};}));
 assert(initial.modern&&initial.recognised&&initial.folded&&initial.completeEvidence&&initial.reconstruction&&initial.recordSame);
 const history=p.locator('#drawer [data-f816="history"]');if(!await history.evaluate(n=>n.open))await history.locator(':scope > summary').click();
 const note=p.locator('#drawer .note947-original');await note.scrollIntoViewIfNeeded();await p.waitForTimeout(200);await p.screenshot({path:path.join(out,'WC20-note-'+W+'.png')});
 await note.locator(':scope > summary').focus();await p.keyboard.press('Enter');assert(await note.evaluate(n=>n.open));
 const measure=await p.evaluate(()=>{const drawer=document.querySelector('#drawer'),pre=drawer.querySelector('.note947-original pre');return{drawerOverflow:drawer.scrollWidth>drawer.clientWidth+1,evidenceOverflow:pre.scrollWidth>pre.clientWidth+1,readOnly:SYNC.readonly,editableNoteVisible:!![...drawer.querySelectorAll('#noteBox,#noteSave')].find(n=>n.getClientRects().length&&getComputedStyle(n).visibility!=='hidden')};});assert(!measure.drawerOverflow&&!measure.evidenceOverflow&&measure.readOnly&&!measure.editableNoteVisible);await p.screenshot({path:path.join(out,'WC20-evidence-'+W+'.png')});
 const fallback=await p.evaluate(()=>{const box=document.createElement('section'),raw='Human prefix\nOriginal evidence retained exactly below:\n{bad JSON}\nHuman suffix';appendNote947(box,raw);return{whole:box.textContent===raw,folds:box.querySelectorAll('details').length};});assert(fallback.whole&&fallback.folds===0);
 const version=await p.evaluate(async()=>await(await fetch('/api/version')).json());version.level='edit';await p.route('**/api/version**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(version)}));await p.waitForTimeout(4500);
 const edit=await p.evaluate(()=>holdAssets(()=>{SYNC.readonly=false;SYNC.level='edit';capability=()=> 'edit';mayWrite=()=>true;whoAmI=()=> 'Captured note test';openAsset('WC20');const raw=assetOf('WC20')._note,box=document.querySelector('#noteBox'),notes=S.notes,captures=[];const originalStamp=stampIt,originalBump=bump;S.notes=new Proxy(notes,{set(target,key,value){captures.push({key,value});return true;}});stampIt=()=>{};bump=()=>{};try{document.querySelector('#noteSave').click();return {fullValue:box.value===raw,capturedWhole:captures.length===1&&captures[0].key==='WC20'&&captures[0].value===raw,storedSame:notes.WC20===raw,foldedEditor:!!document.querySelector('.note947-original')};}finally{S.notes=notes;stampIt=originalStamp;bump=originalBump;}}));assert(edit.fullValue&&edit.capturedWhole&&edit.storedSame&&!edit.foldedEditor);
 const unchanged=await p.evaluate(()=>JSON.stringify(S)===__note947State);assert(unchanged);assert.equal(s.errors.length,0);assert(!s.warnings.some(x=>/drawer|TypeError|Cannot read/.test(x)),s.warnings.join('\n'));
 results.push({W,initial,measure,fallback,edit,recordUnchanged:unchanged,errors:s.errors,warnings:s.warnings,requests:s.counts});fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({author:'Andrew Fisher',pageSHA:crypto.createHash('sha256').update(fs.readFileSync(pageFile)).digest('hex'),results},null,2));console.log('PASS947 '+W);
 }finally{await s.browser.close();}}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
