// Author: Andrew Fisher. GET-only financial-area and operational preservation checks.
const fs=require('fs'),assert=require('assert'),R=process.env.REPO,O=process.env.OUT;
const {installWriteGuard,ready840,nativeSnapshot}=require(R+'/v8.40_today_work_progress_LIVE/test_today840.cjs');const {open}=require(R+'/toolchain/harness/open_page.js');const guard=installWriteGuard();fs.mkdirSync(O,{recursive:true});
(async()=>{let s;try{for(const W of [1366,390]){s=await open({pageFile:process.env.PAGE,hash:'#today',W,H:900,mobile:W===390});const p=s.page;await ready840(p).catch(async e=>{console.log('Hydration diagnostic',s.errors,await p.evaluate(()=>({status:SYNC.status,first:SYNC.first.size,total:Object.keys(SYNC_COLLS).length})));throw e;});console.log('Hydrated',W);await p.evaluate(()=>go('costs'));await p.waitForFunction(()=>moneySummary().charge.labour>0,null,{timeout:15000});await p.evaluate(()=>go('today'));const before=await nativeSnapshot(p);const model=await p.evaluate(()=>JSON.stringify({money:moneySummary(),pl:pl770Model()}));
for(const tab of ['today','timeline','plant','demob','map','coatesway','fencing']){
 await p.evaluate(t=>go(t),tab);await p.waitForTimeout(tab==='fencing'?800:200);
 const audit=await p.evaluate(()=>{const root=document.getElementById('pane-'+state.tab);return {tab:state.tab,dollars:[...root.querySelectorAll('*')].filter(x=>!x.children.length&&/\$\s*[\d,]+/.test(x.textContent)).map(x=>({text:x.textContent.slice(0,170),class:x.className,parent:x.parentElement.outerHTML.slice(0,450)})),nav:[...document.querySelectorAll('#tabs [data-tab]')].map(x=>x.dataset.tab)};});
 fs.writeFileSync(O+'/'+tab+'-'+W+'.json',JSON.stringify(audit,null,2));assert.equal(audit.dollars.length,0,tab+' contains monetary displays');assert(!audit.nav.includes('costs')&&!audit.nav.includes('pricing'));
}
await p.evaluate(()=>go('today'));assert.equal(await p.locator('#pane-today details[data-fold=\"By branch\"],#pane-today details[data-fold=\"Money\"]').count(),0,'Financial lazy folds removed at source');await p.evaluate(()=>renderProgress());assert.equal(await p.locator('#pane-today details[data-fold=\"By branch\"],#pane-today details[data-fold=\"Money\"]').count(),0);await p.screenshot({path:O+'/today-'+W+'.png'});
await p.evaluate(()=>go('costs'));assert.equal(await p.locator('#pane-costs .finance857-nav').count(),1);assert.equal(await p.locator('#tabs [data-tab="costs"]').count(),0);assert(await p.locator('#pane-costs').innerText().then(x=>/Revenue/.test(x)));
await p.locator('[data-finance857="pricing"]').click();await p.waitForFunction(()=>state.tab==='costs'&&!!document.querySelector('#pane-costs #pane-pricing'));assert(await p.locator('#pane-costs #pane-pricing').innerText().then(x=>/Rate card/.test(x)));assert.equal(await p.evaluate(()=>document.querySelector('#pane-pricing').hidden),false);await p.screenshot({path:O+'/rates-'+W+'.png'});
await p.locator('[data-finance857="fencing"]').click();await p.waitForFunction(()=>!!document.querySelector('#pane-costs #pane-fencing'));assert(await p.locator('#pane-costs #pane-fencing').innerText().then(x=>/\$/.test(x)));await p.screenshot({path:O+'/fencing-costs-'+W+'.png'});
await p.locator('[data-finance857="summary"]').click();assert.equal(await p.locator('#pane-costs #pane-fencing').count(),0);assert.equal(await p.evaluate(()=>document.querySelectorAll('#pane-fencing').length),1);
await p.evaluate(()=>go('pricing'));assert.equal(await p.evaluate(()=>state.tab),'costs');await p.evaluate(()=>go('plant'));assert.equal(await p.evaluate(()=>document.querySelector('#pane-pricing').closest('#pane-costs')),null);await p.evaluate(()=>go('fencing'));assert(!await p.locator('#pane-fencing').innerText().then(x=>/\$\s*[\d,]+/.test(x)));
await p.evaluate(()=>go('today'));const after=await nativeSnapshot(p);assert.deepStrictEqual(after.collections,before.collections);assert.equal(await p.evaluate(()=>JSON.stringify({money:moneySummary(),pl:pl770Model()})),model);assert.equal(s.errors.length,0,s.errors.join('\n'));console.log('PASS '+W+' operational money removal, single Costs area, pricing/fencing sections, route restoration, native financial models and records');await s.browser.close();s=null;}
assert.equal(guard.nonGetSeen.filter(x=>x.operational).length,0);}finally{if(s)await s.browser.close();await guard.closeAll();}})().catch(e=>{console.error(e.stack);process.exitCode=1});
