// Author: Andrew Fisher. Generic fixtures only; no production financial record.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const code=fs.readFileSync(path.join(__dirname,'transport953.js'),'utf8');let checks=0;
const ctx={transport888Build:()=>{},DATA:{rehire_quotes:{authorisation:{state:'approved'},quotes:[{quote:'Q6845',delivery_charge:10,pickup:10}]}},EP819:{version:'v10',quote:{quote:'Q6845'},loads:[{n:1,stops:[{drops:[{ref:'P1',fwf:2},{ref:null,fwf:7}]}]}]}};vm.createContext(ctx);vm.runInContext(code,ctx);
function test(name,f){f();checks++;console.log('PASS',name);}
const plain=o=>JSON.parse(JSON.stringify(o));
function row(key='P1',task='T1',extra={}){return Object.assign({id:key+task,src:'planned',key,task,a:{key},e:{quantity_raw:1},date:'2026-10-01',leg:'demob',movement:'remove',item:'Building 6m',qty:'1',branch:'B1',forecast:{kind:'planned',raw:0,amount:0}},extra);}
function model(planned=[],rows=[]){return {rows,planned,ourRefs:new Set(),OCL:[],schedT:{counted:9},forecast:{total:rows.reduce((s,r)=>s+(r.forecast.amount||0),0)},weights:{toDate:{B1:9},toDateNone:0},demob:{},toDate:9};}
function env(extra={}){return Object.assign({off:()=>false,coverage:()=>null,demand:(r,rs)=>({known:true,amount:100.12345*Number(r.qty),reason:'numeric cost × explicit quantity'})},extra);}
const run=(T,e=env())=>ctx.transport953Reconcile(T,e);
test('one planned allowance, actual model untouched',()=>{const T=run(model([row()]));assert.equal(T.forecast.total,100.12);assert.equal(T.rows.length,0);assert.equal(T.toDate,9);assert.deepEqual(T.schedT,{counted:9});assert.deepEqual(T.weights.toDate,{B1:9});assert.equal(T.demob.total,100.12);});
test('exact duplicate once',()=>{const T=run(model([row(),row()]));assert.equal(T.forecast.total,100.12);assert.equal(T.forecast.plannedAllowances953,1);});
test('two references allocated from same task both count',()=>{const T=run(model([row('P1','T1'),row('P2','T1')]));assert.equal(T.forecast.total,200.25);assert.equal(T.forecast.plannedAllowances953,2);});
test('different legs are separate each-way allowances',()=>{const T=run(model([row(),row('P1','T1',{leg:'inbound',movement:'place'})]));assert.equal(T.forecast.plannedAllowances953,2);});
test('same-task stand-in already averaged',()=>{const a=row('T1','T1',{src:'unref',standin:true,forecast:{kind:'average',amount:21,raw:21}});const T=run(model([row()], [a]));assert.equal(T.forecast.total,21);assert.equal(T.planned[0].forecast.kind,'represented953');assert.equal(T.demob.total,21);});
test('actual or Internal task suppresses duplicate',()=>{for(const t of [{internal:true},{amount:99}]){const T=run(model([row()],[row('T1','T1',{src:'unref',standin:true,t,forecast:{kind:'figure',raw:0,amount:0}})]));assert.equal(T.forecast.total,0);}});
test('task collision with different scope is held',()=>{const T=run(model([row()],[row('T1','T1',{src:'unref',standin:true,item:'FWF',t:{internal:true},forecast:{kind:'figure',raw:0,amount:0}})]));assert.equal(T.planned[0].forecast.kind,'held');assert.equal(T.forecast.total,0);});
test('conflicting planned duplicate held',()=>{const T=run(model([row(),row('P1','T1',{qty:'2',e:{quantity_raw:2}})]));assert.equal(T.forecast.total,0);assert(T.planned.every(r=>r.forecast.kind==='held'));});
test('cancelled/off/rest-of and removed tasks do not create allowance',()=>{for(const extra of [{cancelled:true},{off:true},{rest_of:true},{}]){const T=run(model([row('P1','T1',extra)]),env({off:k=>!Object.keys(extra).length&&k==='T1'}));assert.equal(T.forecast.total,0);}});
test('missing, zero, fractional and negative physical qty held',()=>{for(const q of ['',0,1.5,-1,'unknown']){const T=run(model([row('P1','T1',{qty:String(q),e:{quantity_raw:q}})]));assert.equal(T.forecast.total,0);assert.equal(T.planned[0].forecast.kind,'held');}});
test('POA and over-demand held',()=>{const T=run(model([row()]),env({demand:()=>({known:false,reason:'POA or demand exceeds equipment'})}));assert.equal(T.forecast.total,0);assert.equal(T.planned[0].forecast.kind,'held');});
test('numeric zero source cost is allowed without unknown inflation',()=>{const T=run(model([row()]),env({demand:()=>({known:true,amount:0,reason:'explicit zero'})}));assert.equal(T.planned[0].forecast.kind,'card');assert.equal(T.demob.noBasis,0);});
test('relocations are not inferred',()=>{const T=run(model([row('P1','T1',{movement:'relocate'})]));assert.equal(T.forecast.total,0);});
test('typed reference cost preserves existing exclusion',()=>{const T=model([row()]);T.ourRefs.add('P1');assert.equal(run(T).forecast.total,0);});
test('raw precision and all row cents/branch weights tie',()=>{const T=run(model([row(),row('P2','T2'),row('P3','T3',{branch:null})]));assert.equal(T.forecast.total,300.37);assert.equal(Math.round(T.planned.reduce((s,r)=>s+r.forecast.amount,0)*100),30037);assert.equal(Math.round((Object.values(T.weights.toCome).reduce((a,b)=>a+b,0)+T.weights.toComeNone)*100),30037);});
test('existing average and actual remain unchanged',()=>{const r=row('X','TA',{src:'unref',forecast:{kind:'average',amount:20,raw:20}}),before=plain(r);const T=run(model([row()],[r]));assert.deepEqual(plain(T.rows[0]),before);});
test('supplier-covered numeric and average removed once',()=>{const rs=[row('A','TA',{src:'asset',forecast:{kind:'card',amount:20,raw:20}}),row('B','TB',{src:'unref',forecast:{kind:'average',amount:10,raw:10}})];const T=run(model([],rs),env({coverage:()=>({state:'covered',reason:'quote'})}));assert.equal(T.forecast.total,0);assert.equal(T.audit953.excluded.length,2);});
test('WC81 review retains existing numeric allowance',()=>{const T=run(model([],[row('WC81','T81',{src:'asset',forecast:{kind:'card',amount:20,raw:20}})]),env({coverage:()=>({state:'review',reason:'coverage review'})}));assert.equal(T.forecast.total,20);assert(T.rows[0].forecast.review953);});
test('partial supplier scope never produces extra price',()=>{const T=run(model([row()]),env({coverage:()=>({state:'review',reason:'partial'})}));assert.equal(T.forecast.total,0);assert.equal(T.planned[0].forecast.kind,'held');});
test('exact EP ref/item/quantity covered',()=>{const r=row('P1','T1',{item:'FWF',qty:'2',e:{quantity_raw:2}});assert.equal(ctx.transport953Coverage(r,[r]).state,'covered');});
test('unknown null reference cannot borrow unrelated supplier drops',()=>{const r=row(null,'T9999',{item:'FWF'});assert.equal(ctx.transport953Coverage(r,[r]),null);});
test('EP quantity expansion held',()=>{const r=row('P1','T1',{item:'FWF',qty:'3',e:{quantity_raw:3}});assert.equal(ctx.transport953Coverage(r,[r]).state,'review');});
test('EP item does not cover other item',()=>{const r=row('P1','T1',{item:'Accessible Toilet'});assert.equal(ctx.transport953Coverage(r,[r]),null);});
test('explicit task source and date required',()=>{const r=row('T0162','T0162',{date:'2026-10-19',item:'FWF',leg:'inbound',movement:'place'});assert.equal(ctx.transport953Coverage(r,[r]).state,'covered');r.date='2026-10-20';assert.equal(ctx.transport953Coverage(r,[r]).state,'review');});
test('on-site allocation covers exact item but WC81 stays review',()=>{const r=row('WC44','T1',{item:'FWF',qty:'2',e:{quantity_raw:2}});assert.equal(ctx.transport953Coverage(r,[r]).state,'covered');r.key='WC81';assert.equal(ctx.transport953Coverage(r,[r]).state,'review');});
console.log(`${checks}/${checks} checks passed`);
