/* Author: Andrew Fisher. Actual individual item and photo targets; strict public GET harness. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),Module=require('module');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));hm._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++;(counts.denied||=[]).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const{open}=hm.exports;
const out=process.env.OUT933||'/workspace/private-items933',pageFile=process.env.PAGE||path.join(out,'candidate.html');fs.mkdirSync(out,{recursive:true});
(async()=>{const all=[];for(const W of (process.env.W933?[Number(process.env.W933)]:[1440,390])){console.log('START '+W);const s=await open({pageFile,hash:'#today',W,H:W===390?844:1100,mobile:W===390,gl:false}),p=s.page;try{
 await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live'&&window.Items933,null,{timeout:90000});
 await p.evaluate(()=>{window.__photo933Record=JSON.stringify(S);window.__photo933Bumps=0;window.bump=()=>{__photo933Bumps++;throw Error('Read test cannot save');};});
 const views=[];for(const ref of ['T0103','WC09','WC20']){console.log('OPEN '+ref);await p.evaluate(ref=>holdAssets(()=>openAsset(ref)),ref);await p.waitForTimeout(350);const v=await p.evaluate(ref=>holdAssets(()=>{const a=assetOf(ref),m=gcModel925(a),ph=dropPhotosOf(ref),drawer=document.getElementById('drawer');return{ref,rows:m.rows,targets:dropPhotoUnits(a),pins:pinUnits(a),photos:ph.map(p=>({id:p.id,unit:p.unit,slot:p.slot})),association:m.rows.map(u=>({no:u.assetNo,photos:Units925.photos(u,m.rows,ph).map(p=>p.id)})),text:drawer.innerText,html:drawer.innerHTML,overflow:drawer.scrollWidth>drawer.clientWidth+1,recordSame:JSON.stringify(S)===__photo933Record};}),ref);assert(v.recordSame&&!v.overflow);if(ref==='T0103'){assert.equal(v.rows.filter(r=>r.physical).length,2);assert.deepEqual(v.rows.map(r=>r.assetNo),['1211404','120T']);assert(v.text.includes('SUB-HIRED — PremAir Hire'));}if(ref==='WC09'){assert.equal(v.association.find(x=>x.no==='1268858').photos.length,2);assert.equal(v.association.find(x=>x.no==='1311146').photos.length,0);assert(v.text.includes('Location / unassigned photos · 2'));}if(ref==='WC20')assert.equal(v.targets.filter(x=>x.startsWith('[')).length,4);await p.locator('[data-units925]').screenshot({path:path.join(out,ref+'-items-'+W+'.png')});if(ref==='T0103')await p.screenshot({path:path.join(out,ref+'-drawer-'+W+'.png')});fs.writeFileSync(path.join(out,ref+'-drawer-'+W+'.txt'),v.text);delete v.html;delete v.text;views.push(v);}
 // Exercise actual file input and native shrink/outbox path, but replace outbox storage/send with captures.
 const version=await p.evaluate(async()=>await(await fetch('/api/version')).json());version.level='edit';await p.route('**/api/version**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(version)}));
 await p.waitForTimeout(4500);await p.evaluate(()=>{window.capability=()=> 'edit';window.mayWrite=()=>true;window.whoAmI=()=> 'Captured photo test';SYNC.readonly=false;SYNC.level='edit';window.__photo933Outbox=[];window.photoOutboxPut=async e=>{__photo933Outbox.push({...e,blob:null});return true;};window.photoSend=async(e,tell)=>{tell('Captured only');return true;};window.photoDrawerRedraw=()=>{};holdAssets(()=>openAsset('WC09'));});
 await p.locator('[data-units925]').screenshot({path:path.join(out,'WC09-edit-'+W+'.png')});const target=await p.locator('[data-unit925-id]').filter({hasText:'1268858'}).locator('input[data-item933-add]').first();assert(await target.count());await target.setInputFiles({name:'sample.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=','base64')});try{await p.waitForFunction(()=>__photo933Outbox.length===1,null,{timeout:15000});}catch(e){fs.writeFileSync(path.join(out,'capture-failure-'+W+'.json'),JSON.stringify(await p.evaluate(()=>({status:[...document.querySelectorAll('.item933-status')].map(n=>n.textContent),ro:SYNC.readonly,level:SYNC.level,capture:__photo933Outbox,who:whoAmI()})),null,2));throw e;}
 const capture=await p.evaluate(()=>({entry:__photo933Outbox[0],recordSame:JSON.stringify(S)===__photo933Record,bumps:__photo933Bumps}));assert.equal(capture.entry.unit,JSON.stringify(['WC09','coates','asset','1268858']));assert.equal(capture.entry.slot,2);assert.equal(capture.entry.previousId,null);assert(!capture.entry.title.includes('['));assert(capture.recordSame&&capture.bumps===0);assert.equal(s.errors.length,0);all.push({W,views,capture,errors:s.errors,requests:s.counts});fs.writeFileSync(path.join(out,'browser-'+W+'.json'),JSON.stringify(all.at(-1),null,2));console.log('PASS '+W);
 }finally{await s.browser.close();}}
 fs.writeFileSync(path.join(out,'browser933.json'),JSON.stringify(all,null,2));})().catch(e=>{console.error(e.stack);process.exitCode=1});
