/* Author: Andrew Fisher. Historical item visibility and stale removal regressions. */
const assert=require('assert/strict'),fs=require('fs'),vm=require('vm');let n=0;const test=(s,f)=>{f();n++;console.log('PASS '+s);};
test('a historical item remains visible when its description also has current rows',()=>{const row={id:'old',assetNo:'old-12',ref:'X',owner:'coates',item:'Block',source:'history',physical:false,identityReview:'Previous record'},model={rows:[row],groups:[{item:'Block',units:[],quantity:0,pending:0}]},c={selected:new Map(),gcModel925:()=>model,dropPhotosOf:()=>[],photos925:()=>[],esc925:String,work925:()=>({lines:[]}),branch925:()=>({code:'BR'}),company925:()=> 'Coates',Items933:{cardPhotos:()=>'',locationPhotos:()=>''},SYNC:{readonly:true}};vm.createContext(c);vm.runInContext(fs.readFileSync(require.resolve('../rows933.js'),'utf8'),c);const html=c.panel925({key:'X'});assert(html.includes('Previously recorded items · 1'));assert(html.includes('old-12'));assert.equal(html.split('data-unit925-id="old"').length,2);});
function removeFixture(){const handlers={},photos=[{id:'photo',unit:'first',slot:0}],removed=[],c={window:{confirm:()=>true},document:{addEventListener:(ev,f)=>handlers[ev]=f},dropPhotoUnits:()=>[],dropPhotosOf:()=>photos,buildingNumbersOf:()=>[],mayWrite:()=>true,whoAmI:()=> 'Actor',flash:()=>{},photoLinkRemove:(r,p,w)=>removed.push({r,p,w}),bump:()=>{},photoDrawerRedraw:()=>{}};vm.createContext(c);vm.runInContext(fs.readFileSync(require.resolve('../items933.js'),'utf8'),c);const button={dataset:{item933Remove:'photo',item933RemoveHome:'first',item933RemoveSlot:'0',item933Ref:'X'}};return{c,photos,removed,click:()=>handlers.click({target:{closest:q=>q==='[data-item933-remove]'?button:null}})};}
test('stale Remove cannot remove a photo reassigned to another unit',()=>{const f=removeFixture();f.photos[0].unit='second';f.click();assert.equal(f.removed.length,0);});
test('Remove rechecks the original photo association after confirmation',()=>{const f=removeFixture();f.c.window.confirm=()=>{f.photos[0].slot=1;return true;};f.click();assert.equal(f.removed.length,0);});
test('Remove uses exactly one native photo document after explicit confirmation',()=>{const f=removeFixture();f.click();assert.equal(f.removed.length,1);assert.equal(f.removed[0].p.id,'photo');assert.equal(f.removed[0].p.unit,'first');});
test('Remove preserves the record if editing actor changes during confirmation',()=>{const f=removeFixture();f.c.window.confirm=()=>{f.c.whoAmI=()=> 'Other';return true;};f.click();assert.equal(f.removed.length,0);});
console.log(n+' history/removal checks passed');
