/* Author: Andrew Fisher. Identity, association and native upload freshness regressions. */
const assert=require('assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),items=require('../items933.js');let n=0;const test=(s,f)=>{f();n++;console.log('PASS '+s);};
const page=fs.readFileSync(process.env.PAGE||'/workspace/private-items933/candidate.html','utf8'),unitScript=page.match(/<script id="units925-script">([\s\S]*?)<\/script>/)[1],c={module:{exports:{}},Items933:items};vm.createContext(c);vm.runInContext(unitScript,c);const units=c.module.exports;
const id=(r,o,n,a)=>JSON.stringify([r,o,n?'native':'asset',n||a]);
test('exact contract and line resolve the supplier placeholder',()=>{assert.equal(items.sourceAsset({contract:'9961265',line:13,asset:null},[{rental_contract:'9961265',line:13,asset_no:'sub-17093'},{rental_contract:'other',line:13,asset_no:'different'}]),'sub-17093');assert.equal(items.sourceAsset({contract:'9961265',line:12,asset:'1211404'},[]),'1211404');});
test('ambiguous or absent contract source never guesses placeholder',()=>{assert.equal(items.sourceAsset({contract:'a',line:1},[{rental_contract:'a',line:1,asset_no:'x'},{rental_contract:'a',line:1,asset_no:'y'}]),'');assert.equal(items.sourceAsset({contract:'a',line:2},[{rental_contract:'a',line:1,asset_no:'x'}]),'');});
const rows=[{id:id('T0103','coates','vms:VMS09','1211404'),assetNo:'1211404',owner:'coates',physical:true},{id:id('T0103','prem-air-hire','vms:VMS10','120T'),assetNo:'120T',owner:'prem-air-hire',physical:true}];
test('two actual VMS boards replace only their exact contract placeholder projection',()=>{const e={units:()=>[],numbers:()=>['sub-17093'],coatesNumbers:()=>['sub-17093'],items:()=>['VMS'],itemOf:()=> 'VMS',loading:()=>[],identity:id,lines:()=>[{item:'VMS',qty:2}],qty:l=>l.qty,loads:{},vms:()=>[{nativeId:'vms:VMS09',asset_no:'1211404',sourceAssetNo:'1211404',owner:'coates',item:'VMS'},{nativeId:'vms:VMS10',asset_no:'120T',sourceAssetNo:'sub-17093',owner:'prem-air-hire',item:'VMS'}]};const model=units.model({key:'T0103'},e);assert.equal(model.rows.length,2);assert.deepEqual(Array.from(model.rows,r=>r.assetNo),['1211404','120T']);assert.equal(model.groups[0].pending,0);});
test('canonical picker includes every physical row and retains historical photo homes',()=>{assert.deepEqual(items.photoUnits(rows,[{unit:'old'}]),rows.map(r=>r.id).concat('old'));assert(!items.photoUnits(rows,[]).includes('sub-17093'));});
const block={id:'canonical',assetNo:'1268858',physical:true},other={id:'other',assetNo:'1311146',physical:true},photos=[{id:'one',unit:'1268858',slot:0},{id:'two',unit:'1268858',slot:1},{id:'site1',unit:'',slot:0},{id:'site2',unit:'',slot:1}];
test('location photos stay separate and never fill the second block',()=>{assert.equal(units.photos(block,[block,other],photos).length,2);assert.equal(units.photos(other,[block,other],photos).length,0);});
test('Add skips legacy, canonical and pending photo places',()=>assert.equal(items.firstFree(block,[block,other],photos.concat({unit:'canonical',slot:2}),[{unit:'canonical',slot:3}],5),4));
test('all five occupied requires explicit replacement',()=>assert.equal(items.firstFree(block,[block],Array.from({length:5},(_,slot)=>({unit:'canonical',slot})),[],5),-1));
test('historical owner collision never borrows legacy photo occupancy or links',()=>{const old={id:'old',assetNo:'1268858',source:'history'};assert.equal(items.firstFree(block,[block,old],photos,[],5),0);assert.equal(units.photos(block,[block,old],photos).length,0);});
test('physical identity signature changes with owner/item/number',()=>{for(const field of ['id','owner','assetNo','item'])assert.notEqual(items.signature({...block,item:'Block',owner:'coates'}),items.signature({...block,item:'Block',owner:'coates',[field]:'changed'}));});
test('native add guard occurs after shrink and before file queue',()=>{const start=page.indexOf('async function dropPhotoAddUnlocked('),end=page.indexOf('async function dropPhotoRemove(',start),s=page.slice(start,end);assert(s.indexOf('await dropShrink')<s.indexOf('Items933.guard'));assert(s.indexOf('Items933.guard')<s.indexOf('await photoOutboxPut'));assert(s.includes('item933.replace.id'));assert(s.includes('whoAmI()!==item933.actor'));assert(s.includes('previousId: was'));});
test('native geographic pin identities exclude new photo canonical ids',()=>{const s=fs.readFileSync(path.join(__dirname,'../items933.js'),'utf8');assert(s.includes("pinUnits=function(a){const nums=buildingNumbersOf(a)"));assert(s.includes("!/^\\s*\\[/.test(u)"));});
test('patch replaces only owned 925 functions, not company navigation',()=>{const patch=fs.readFileSync(path.join(__dirname,'../patch_v933.py'),'utf8');assert(!patch.includes("('companyHtml925'"));assert(!patch.includes("('companyModel925'"));});
console.log(n+' checks passed');
