// Author: Andrew Fisher. Exercise actual patched native hydration and polling without requests.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
if(!process.env.CACHE975_PAGE)throw Error('Set CACHE975_PAGE to the patched HTML');
const page=fs.readFileSync(process.env.CACHE975_PAGE,'utf8'),start=page.indexOf('function sharedCache975(){'),stop=page.indexOf('/* redraw after remote changes',start);assert(start>0&&stop>start);const source=page.slice(start,stop);let checks=0;const ok=(x,m)=>{assert(x,m);checks++;};
const first={T0022:{lat:-27.98,lon:153.42}},newer={T0022:{lat:-27.981,lon:153.421}};
let persistCalls=0,renderCalls=0,sendCalls=0;const ctx={S:{fixes:{}},SYNC:{readonly:true,last:{},queue:{},pending:{},first:new Set(),ftimer:null},SYNC_COLLS:{fixes:{get:()=>ctx.S.fixes,set:v=>{ctx.S.fixes=v}}},RENDER_MEMO:new Map([['pinsNow',{}],['money:2026-10-09',{total:'stale'}]]),HELD_MEMO:new Map([['reference966-rows',['stale']]]),ASSETS_HELD:[{key:'stale'}],HELD_STALE775:false,fromDocs:(n,d)=>d,persist:()=>persistCalls++,syncRedraw:()=>renderCalls++,syncSend:()=>sendCalls++,mergeRecords:(s,t)=>({merged:{...s,...t},report:{clashes:[]}}),toDocs:n=>ctx.S[n],clearTimeout:()=>{},setTimeout:()=>{},window:{}};
vm.createContext(ctx);vm.runInContext(source,ctx);
ctx.syncFold('fixes',first);ok(JSON.stringify(ctx.S.fixes)===JSON.stringify(first),'Received native fixes retained');ok(ctx.RENDER_MEMO.size===0,'Native pin and financial caches invalidated immediately');ok(ctx.HELD_STALE775,'Active asset snapshot marked stale before deferred redraw');ok(renderCalls===0&&persistCalls===0,'Cache helper does not redraw or persist');
ctx.ASSETS_HELD=null;ctx.sharedCache975();ok(ctx.HELD_MEMO.size===0,'Unheld memo cleared');ctx.RENDER_MEMO.set('pinsNow',first);ctx.HELD_STALE775=false;ok(ctx.syncFold('fixes',first)===false,'Unchanged poll skips invalidation');ok(ctx.RENDER_MEMO.size===1&&!ctx.HELD_STALE775,'Unchanged poll preserves memo');
ctx.syncFold('fixes',newer);ok(JSON.stringify(ctx.S.fixes)===JSON.stringify(newer)&&ctx.RENDER_MEMO.size===0,'Changed poll updates pin cache immediately');
ctx.RENDER_MEMO.set('pinsNow',{});ctx.SYNC.pending={fixes:first};ctx.syncFirst();ok(JSON.stringify(ctx.S.fixes)===JSON.stringify(first)&&ctx.RENDER_MEMO.size===0,'Read-only initial hydration invalidates');ok(ctx.SYNC.first.has('fixes'),'First snapshot tracked');ok(sendCalls===0,'Read-only hydration sends nothing');
ctx.SYNC.readonly=false;ctx.SYNC.first=new Set();ctx.SYNC.pending={fixes:newer};ctx.RENDER_MEMO.set('pinsNow',{});ctx.syncFirst();ok(JSON.stringify(ctx.S.fixes)===JSON.stringify(newer)&&ctx.RENDER_MEMO.size===0,'Editable initial merge invalidates');ok(sendCalls===1,'Existing editable send path retained');
console.log(JSON.stringify({author:'Andrew Fisher',checks,passed:true,networkRequests:0}));
