// Author: Andrew Fisher. Exact final phone checks with GET-only reads and capture-only edit controls.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const {open}=require('../../toolchain/harness/open_page');
(async()=>{const file=process.env.PAGE,out=process.env.OUTDIR;assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),process.env.EXPECTED_SHA);fs.mkdirSync(out,{recursive:true});const h=await open({pageFile:file,W:390,H:844,mobile:true}),p=h.page;try{
await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:150000});const original=await p.evaluate(()=>JSON.stringify(S));
const r=await p.evaluate(()=>holdAssets(()=>{const assets=allAssets(),rows=assets.flatMap(a=>arrivedChargeRows975(a).filter(r=>r.charges.length));const fwf=rows.filter(r=>r.item==='FWF'),block=rows.find(r=>r.ref==='WC09'&&r.item==='Toilet Block 6m');return {rows:rows.length,fwf:fwf.length,fwfCorrect:fwf.length>0&&fwf.every(r=>r.charges.some(c=>c.key==='install')&&r.charges.some(c=>c.key==='demob')&&!r.charges.some(c=>c.key==='cleaning')),blockKeys:block.charges.map(c=>c.key),zeroFake:rows.every(r=>r.charges.length>0),remaining:Subhire975.remainingRows().reduce((n,r)=>n+r.remaining,0)};}));
assert(r.fwfCorrect&&r.zeroFake);assert.deepEqual(r.blockKeys.sort(),['cleaning','demob','install','levelling','steps']);assert.equal(r.remaining,35);
await p.evaluate(()=>openAsset('WC09'));await p.waitForSelector('[data-charges952="WC09"]');const text=await p.locator('[data-charges952="WC09"]').innerText();assert(text.includes('Customer charges · arrived equipment'));assert(text.includes('Toilet Block 6m × 2'));assert(text.includes('Pee Panel × 6'));
await p.locator('[data-charges952="WC09"] details').filter({hasText:'Toilet Block 6m'}).evaluate(e=>{for(let n=e;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;});await p.locator('[data-charges952="WC09"]').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/charges-view-phone.png',timeout:120000});
await p.route('**/api/version',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({version:5174,level:'edit'})}));
await p.evaluate(()=>{window.capability=()=> 'edit';window.mayWrite=()=>true;SYNC.readonly=false;SYNC.level='edit';openAsset('WC09');document.querySelector('[data-charges952="WC09"] details').open=true;});
await p.locator('[data-charges952="WC09"] details').filter({hasText:'Toilet Block 6m'}).evaluate(e=>{for(let n=e;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;});await p.locator('[data-charges952="WC09"] details').filter({hasText:'Toilet Block 6m'}).locator('[data-stairs975-action]').first().scrollIntoViewIfNeeded();assert(await p.locator('[data-charges952="WC09"] details').filter({hasText:'Toilet Block 6m'}).locator('[data-stairs975-action]').first().isVisible());await p.screenshot({path:out+'/stairs-edit-phone.png',timeout:120000});
assert.equal(await p.evaluate(b=>JSON.stringify(S)===b,original),true);assert.equal(h.counts.blocked,0);assert.equal(h.errors.length,0);const report={author:'Andrew Fisher',pass:true,sha256:process.env.EXPECTED_SHA,checks:['All arrived FWF install/demob without cleaning','WC09 all five applicable charges','Six pee panels retain own item scope','Remaining supplier deliveries35','Charge data visible in view mode','Per-unit stairs controls in capture-only edit mode','Native unchanged','Zero operational writes/errors'],observations:r};fs.writeFileSync(out+'/ui975.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:true,checks:report.checks.length,observations:r}));
}finally{await h.browser.close();}})().catch(e=>{console.error(e.stack);process.exit(1)});
