// Author: Andrew Fisher. Bounded wheel/reachability proof for the short 125% zoom-equivalent viewport.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {open}=require('../toolchain/harness/open_page.js'),{ready840,installWriteGuard,nativeSnapshot}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const {read,reachable,settle}=require('./test_today845.cjs');
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
async function run(){const {PAGE,OUT,CANDIDATE_SHA}=process.env;if(!PAGE||!OUT||!CANDIDATE_SHA)throw Error('Frozen PAGE/SHA and private OUT required');const bytes=fs.readFileSync(PAGE);if(sha(bytes)!==CANDIDATE_SHA)throw Error('Candidate changed');fs.mkdirSync(OUT,{recursive:true});const guard=installWriteGuard(),checks=[];let s;const check=(name,pass,evidence)=>checks.push({name,pass:!!pass,evidence});
try{s=await open({pageFile:PAGE,hash:'#today',W:1093,H:614,dpr:1.25});const p=s.page;await ready840(p);await p.waitForFunction(()=>TodayWork840.report().typesMerged);await settle(p);const before=await nativeSnapshot(p);await p.locator('[data-tw840-jump="toilets"]').click();await settle(p);const initial=await read(p),proof=await reachable(p,initial,OUT,'zoom-equivalent125');check('Initial heading and readings exist with horizontal fit; short viewport requires vertical scrolling',proof.heading&&proof.needWheel&&!initial.geometry.horizontal,initial.geometry);check('Real wheel reveals all three readings and their exact count buttons pass hit testing',proof.pass,proof);check('Reverse wheel restores navigation without a scroll trap',proof.returned<proof.after.scroll-20&&Math.abs(proof.returned-proof.before)<=2,proof);const after=await nativeSnapshot(p);check('Native records and media remain unchanged with no runtime errors',JSON.stringify(before.collections)===JSON.stringify(after.collections)&&JSON.stringify(before.media)===JSON.stringify(after.media)&&!s.errors.length,s.errors);
}catch(e){check('Focused scroll execution',false,e.stack);}finally{if(s)await s.browser.close();await guard.closeAll();check('Every non-GET blocked and no operational write attempted',guard.nonGetSeen.length===guard.blocked.length&&!guard.nonGetSeen.some(r=>r.operational),guard.nonGetSeen);const unexpected=guard.consoleErrors.filter(e=>!(/Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(e.text)&&guard.blocked.some(b=>!b.operational&&b.url===e.url)));check('No unexpected console errors and candidate unchanged',!unexpected.length&&sha(fs.readFileSync(PAGE))===CANDIDATE_SHA,unexpected);const result={author:'Andrew Fisher',candidate:CANDIDATE_SHA,passed:checks.filter(c=>c.pass).length,total:checks.length,checks};fs.writeFileSync(path.join(OUT,'scroll845.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,total:result.total}));if(result.passed!==result.total)process.exitCode=1;}}
run().catch(e=>{console.error(e.message);process.exitCode=2;});
