// Author: Andrew Fisher. Focused rendered Toilet and font verification; every live write is blocked.
// PAGE, OUT and CANDIDATE_SHA required. LIVE=1 reads the public host without HTML substitution.
// The zoom-equivalent view approximates desktop layout/raster density, not a native browser-zoom action.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {open}=require('../toolchain/harness/open_page.js');
const {installWriteGuard,ready840,nativeSnapshot}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const {openType844,close844,readDialog844}=require('../v8.44_linked_completion_LIVE/test_linked_ui844.cjs');
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const finite=n=>typeof n==='number'&&Number.isFinite(n),fmt=n=>finite(n)?n.toLocaleString('en-AU',{maximumFractionDigits:2}):'—';
const pct=t=>finite(t.pct)?(t.pctKind==='lower-bound'?'≥':'')+fmt(t.pctKind==='lower-bound'?Math.floor((Math.min(100,t.pct)+1e-9)*100)/100:Math.min(100,t.pct))+'%':'—';
const card='[data-tw840-area="toilets"]',title=card+' .tw840-top h3';
async function fonts(page,selector){
  const cdp=await page.context().newCDPSession(page);
  try{await cdp.send('DOM.enable');await cdp.send('CSS.enable');const {root}=await cdp.send('DOM.getDocument');const {nodeId}=await cdp.send('DOM.querySelector',{nodeId:root.nodeId,selector});if(!nodeId)throw Error('Font target missing: '+selector);return (await cdp.send('CSS.getPlatformFontsForNode',{nodeId})).fonts;}
  finally{await cdp.detach();}
}
const inter=rows=>rows.length>0&&rows.every(f=>f.glyphCount===0||f.isCustomFont&&/^Inter(?:$|[ -])/i.test(f.familyName));
async function settle(page){await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function read(page){return page.evaluate(()=>{
 const day=TodayWork840.report().asOf,areas=todayWorkMetrics840(day),groups=todayGroupDetails841(day,areas),fence=todayFencingSummary841(day),summary=todayWorkSummary842(day,areas,groups,fence),types=todayTypeMetrics843(day,groups,summary),c=document.querySelector('[data-tw840-area="toilets"]');
 const rect=e=>e?.getBoundingClientRect().toJSON(),style=e=>{const s=getComputedStyle(e);return {font:s.fontFamily,size:parseFloat(s.fontSize),weight:s.fontWeight,style:s.fontStyle,synthesis:s.fontSynthesis,transform:s.transform,filter:s.filter,shadow:s.textShadow,opacity:s.opacity,animation:s.animationName};};
 const ancestors=e=>{const out=[];while(e){out.push({tag:e.tagName,id:e.id,class:e.className,rect:rect(e),style:style(e)});e=e.parentElement;}return out;};
 const headings=[...document.querySelectorAll('#gc500-work-board840 .tw840-top h3,#gc500-work-board840 .tw843-type-instrument h5')].map(e=>({text:e.textContent,rect:rect(e),style:style(e),scroll:e.scrollWidth,client:e.clientWidth}));
 const main=document.querySelector('main'),nav=document.querySelector('.tw840-nav'),nodes=[c.querySelector('.tw840-top h3'),c.querySelector('.tw840-reading'),...c.querySelectorAll('[data-tw842-quantity]')];
 return {day,report:TodayWork840.report(),area:areas.find(a=>a.id==='toilets'),summary:summary.byId.toilets,types:types.byCard.toilets,shown:{heading:c.querySelector('.tw840-top h3').textContent,percent:c.querySelector('.tw840-reading').textContent.replace(/\s/g,''),counts:Object.fromEntries([...c.querySelectorAll('[data-tw842-quantity]')].map(e=>[e.dataset.tw842Quantity,e.textContent])),types:[...c.querySelectorAll('[data-tw843-type-id]')].map(e=>({id:e.dataset.tw843TypeId,name:e.querySelector('h5')?.textContent,percent:e.querySelector('.tw843-type-percent')?.textContent.replace(/\s/g,''),counts:Object.fromEntries([...e.querySelectorAll('[data-tw843-quantity]')].map(b=>[b.dataset.tw843Quantity,b.querySelector('strong').textContent])),overflow:e.scrollWidth>e.clientWidth+1}))},headings,ancestors:ancestors(c.querySelector('.tw840-top h3')),geometry:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,viewportScale:visualViewport.scale,main:rect(main),nav:rect(nav),nodes:nodes.map(e=>({text:e.textContent,rect:rect(e),style:style(e)})),horizontal:document.documentElement.scrollWidth>innerWidth+1||main.scrollWidth>main.clientWidth+1},labels:[...c.querySelectorAll('.tw843-type-unit,.tw843-type-caption,.tw843-type-counts button,.tw843-type-onsite,.tw843-type-review,.tw843-type-scope,.tw843-type-plan')].map(e=>({text:e.textContent,style:style(e)}))};
 });}
async function reachable(page,initial,out,name){
 const g=initial.geometry,top=Math.max(g.main.top,g.nav.bottom),bottom=Math.min(g.main.bottom,g.height),inside=n=>n.rect.top>=top-1&&n.rect.bottom<=bottom+1;
 const heading=inside(g.nodes[0]),needWheel=g.nodes.slice(2).some(n=>!inside(n)),before=await page.locator('main').evaluate(e=>e.scrollTop);
 if(needWheel){await page.mouse.move(Math.min(g.width-40,g.nodes[1].rect.x+g.nodes[1].rect.width/2),Math.min(bottom-60,g.nodes[1].rect.y+20));await page.mouse.wheel(0,120);await page.waitForFunction(top=>document.querySelector('main').scrollTop>top+20,before);await settle(page);}
 const after=await page.evaluate(()=>{const m=document.querySelector('main'),mr=m.getBoundingClientRect(),nav=document.querySelector('.tw840-nav').getBoundingClientRect();return {scroll:m.scrollTop,main:mr.toJSON(),nav:nav.toJSON(),counts:[...document.querySelectorAll('[data-tw840-area="toilets"] [data-tw842-quantity]')].map(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {text:e.textContent,rect:r.toJSON(),visible:r.width>0&&r.top>=Math.max(mr.top,nav.bottom)-1&&r.bottom<=Math.min(mr.bottom,innerHeight)+1,hit:hit?.closest('button')===e.closest('button')};})};});
 if(needWheel){await page.screenshot({path:path.join(out,'today845-'+name+'-counts-revealed.png')});await page.mouse.wheel(0,-120);await page.waitForFunction(top=>document.querySelector('main').scrollTop<top-20,after.scroll);await settle(page);}
 const returned=await page.locator('main').evaluate(e=>e.scrollTop);
 return {heading,needWheel,before,after,returned,pass:heading&&!g.horizontal&&g.nodes.every(n=>n.text.trim()&&n.rect.width>0&&n.rect.height>0&&n.rect.left>=g.main.left-1&&n.rect.right<=g.main.right+1&&n.style.opacity==='1'&&n.style.filter==='none')&&after.counts.length===3&&after.counts.every(n=>n.visible&&n.hit)&&(!needWheel||returned<after.scroll-20)};
}
async function run(){
 const {PAGE,OUT,CANDIDATE_SHA}=process.env;if(!PAGE||!OUT||!CANDIDATE_SHA)throw Error('Frozen PAGE/SHA and private OUT required');
 const bytes=fs.readFileSync(PAGE),css=fs.readFileSync(path.join(__dirname,'text_clarity845_src.css'),'utf8');if(sha(bytes)!==CANDIDATE_SHA)throw Error('Candidate bytes differ');fs.mkdirSync(OUT,{recursive:true});
 const live=process.env.LIVE==='1',report={author:'Andrew Fisher',at:new Date().toISOString(),candidate:CANDIDATE_SHA,bytes:bytes.length,css:sha(css),live,checks:[],views:[]},guard=installWriteGuard();let session;
 const check=(name,pass,evidence)=>{report.checks.push({name,pass:!!pass,evidence});fs.writeFileSync(path.join(OUT,'checks845.json'),JSON.stringify({count:report.checks.length,passed:report.checks.filter(c=>c.pass).length,failures:report.checks.filter(c=>!c.pass),last:name},null,2));if(!pass)console.log('FAIL '+name);};
 const views=[{name:'laptop1366',W:1366,H:768,dpr:1},{name:'laptop1280',W:1280,H:800,dpr:1},{name:'laptop1366-dpr125',W:1366,H:768,dpr:1.25},{name:'laptop1280-dpr125',W:1280,H:800,dpr:1.25},{name:'zoom-equivalent125',W:1093,H:614,dpr:1.25,approximation:'1366×768 physical pixels /1.25; not native browser zoom'},{name:'phone',W:390,H:844,dpr:2,mobile:true}].filter(v=>!process.env.VIEWS||process.env.VIEWS.split(',').includes(v.name));
 check('Frozen CSS is embedded exactly and contains only scoped presentation rules',bytes.toString('utf8').includes(css.trim())&&/^#pane-today\s*\{\s*animation:none!important;\s*transform:none!important;/m.test(css)&&!/@import|url\(|@font-face/i.test(css),{css:sha(css)});
 try{for(const view of views){console.log('START '+view.name);session=await open({pageFile:live?undefined:PAGE,hash:'#today',...view});const p=session.page;
  if(live){const up=guard.fulfilledDocuments.at(-1),got=guard.documentResponses.at(-1),bom=bytes.subarray(0,3).equals(Buffer.from([239,187,191])),stripped=bom&&got?.sha===sha(bytes.subarray(3))&&got.bytes===bytes.length-3;check(view.name+' exact upstream and browser bytes without local substitution',up?.status===200&&up.sha===CANDIDATE_SHA&&up.bytes===bytes.length&&got?.status===200&&(got.sha===CANDIDATE_SHA&&got.bytes===bytes.length||stripped)&&session.counts.page===0,{up,got,stripped,counts:session.counts});}
  await ready840(p);await p.waitForFunction(()=>TodayWork840.report().typesMerged);await p.evaluate(()=>photoIndex());await p.waitForFunction(()=>['ready','failed'].includes(DOCS.state));await settle(p);
  const before=await nativeSnapshot(p);await p.locator('[data-tw840-jump="toilets"]').click();await settle(p);const initial=await read(p),e={view,initial,dialogs:[]};report.views.push(e);
  check(view.name+' ready Toilet summary and every supported type show exact known counts and percentages',!initial.area.loading&&initial.area.health.ready&&initial.report.typesMerged&&['total','done','left'].every(k=>finite(initial.summary[k])&&initial.shown.counts[k]===fmt(initial.summary[k]))&&initial.shown.percent===pct(initial.summary)&&initial.types.length>0&&same(initial.shown.types.map(t=>t.id),initial.types.map(t=>t.id))&&initial.types.every(t=>{const s=initial.shown.types.find(s=>s.id===t.id);return s.name===t.name&&s.percent===pct(t)&&['total','done','left'].every(k=>s.counts[k]===fmt(t[k]));}),initial);
  const reach=await reachable(p,initial,OUT,view.name);e.reachability=reach;
  check(view.name+' Toilet heading is visible and readings are nonblank, fit horizontally and are reachable by normal scrolling',reach.pass&&initial.shown.types.every(t=>!t.overflow),reach);
  await p.screenshot({path:path.join(OUT,'today845-'+view.name+'-toilets-main.png')});
  const f1=await fonts(p,title),f2=await fonts(p,card+' .tw843-type-instrument h5');e.fonts={category:f1,type:f2};
  check(view.name+' category and type names use loaded upright Inter700 without synthetic faces',inter(f1)&&inter(f2)&&initial.headings.every(h=>h.style.font.includes('Inter')&&h.style.style==='normal'&&h.style.weight==='700'&&h.style.synthesis==='none'&&h.style.shadow==='none'&&h.rect.width>0&&h.rect.height>0&&h.scroll<=h.client+1),e.fonts);
  check(view.name+' settled heading ancestors have no transform or blur and subtype labels remain readable',initial.ancestors.every(a=>a.style.transform==='none'&&a.style.filter==='none'&&a.style.opacity==='1')&&initial.ancestors.find(a=>a.id==='pane-today').style.animation==='none'&&initial.labels.length>0&&initial.labels.every(l=>l.style.size>=15),{ancestors:initial.ancestors,labels:initial.labels});
  await p.waitForFunction(()=>TodayWork840.report().runningInstrument);const motion=await p.evaluate(()=>{const report=TodayWork840.report(),run=report.runningInstrument,node=run.kind==='parent'?document.querySelector('[data-tw840-area='+CSS.escape(run.cardId)+'] .tw841-motion-track'):document.querySelector('[data-tw843-type-id="'+CSS.escape(run.id)+'"] .tw843-leds'),r=node?.getBoundingClientRect(),m=document.querySelector('main').getBoundingClientRect(),n=document.querySelector('.tw840-nav').getBoundingClientRect();return {report,rect:r?.toJSON(),visible:!!r&&r.width>0&&r.bottom>Math.max(m.top,n.bottom)&&r.top<Math.min(m.bottom,innerHeight),targets:document.querySelectorAll('#gc500-work-board840 .tw840-running,#gc500-work-board840 .tw843-running').length,readings:[...document.querySelectorAll('[data-tw840-area="toilets"] .tw840-reading,[data-tw840-area="toilets"] .tw843-type-percent')].map(e=>getComputedStyle(e).animationName)};});check(view.name+' one visible instrument moves while all numeric readings remain still',motion.visible&&motion.targets===1&&motion.readings.every(x=>x==='none'),motion);
  const samples=['FWF','Toilet Block 6m','Waste tank'].map(name=>initial.types.find(t=>t.name===name));if(samples.some(t=>!t))throw Error('Required native Toilet family missing');
  for(const t of samples){if(t.name==='FWF'){await p.evaluate(id=>{const node=document.querySelector('[data-tw843-type-id="'+CSS.escape(id)+'"]'),main=document.querySelector('main'),nav=document.querySelector('.tw840-nav');main.scrollTop+=node.getBoundingClientRect().top-main.getBoundingClientRect().top-nav.getBoundingClientRect().height-15;},t.id);await settle(p);await p.screenshot({path:path.join(OUT,'today845-'+view.name+'-fwf-type.png')});}const pair=[];for(const mode of ['total','left']){
   await openType844(p,t.id,mode,true);await settle(p);const d=await readDialog844(p),expected=mode==='total'?t.rows:t.rows.filter(r=>!r.complete||!finite(r.left)||r.left>0),font=await fonts(p,'#gc500-work-dialog840 h2');
   const style=await p.locator('#gc500-work-dialog840 h2').evaluate(e=>{const s=getComputedStyle(e);return {style:s.fontStyle,weight:s.fontWeight,synthesis:s.fontSynthesis,shadow:s.textShadow};});
   pair.push({mode,shown:d,expected:expected.map(r=>({key:r.key,quantity:r.quantity,left:r.left})),font,style,pass:d.selected===initial.day&&d.subtitle.startsWith(fmt(t[mode])+' ')&&same(d.rows.map(r=>r.key),expected.map(r=>r.key))&&d.rows.every((r,i)=>r.value===fmt(expected[i][mode==='total'?'quantity':'left'])&&r.current?.trim()&&r.destination?.trim()&&r.actions.some(a=>a.kind==='record'&&a.key===r.key))&&d.scroll<=d.client+1&&d.rows.every(r=>!r.overflow)&&inter(font)&&style.style==='normal'&&style.weight==='700'&&style.synthesis==='none'&&style.shadow==='none'});
   if(mode==='left'&&t.name==='Waste tank')await p.screenshot({path:path.join(OUT,'today845-'+view.name+'-tank-left.png')});await close844(p);
  }e.dialogs.push({name:t.name,pair});check(view.name+' '+t.name+' Total and Left retain exact reference scope and legible native details',pair.every(x=>x.pass),pair);}
  await p.locator('[data-tw840-jump="toilets"]').click();await p.evaluate(()=>renderToday());await settle(p);const refreshed=await read(p),after=await nativeSnapshot(p);
  check(view.name+' refresh keeps Toilet content coherent and records/media/error state unchanged',same(initial.shown,refreshed.shown)&&same(before.collections,after.collections)&&same(before.media,after.media)&&!session.errors.length,{errors:session.errors,day:refreshed.day});
  if(view.name==='phone'){await p.setViewportSize({width:320,height:844});await p.locator('[data-tw840-jump="equipment"]').click();await settle(p);const narrow=await read(p);check('320px upright category and subtype headings fit without horizontal clipping',!narrow.geometry.horizontal&&narrow.headings.every(h=>h.scroll<=h.client+1),narrow.headings);await p.screenshot({path:path.join(OUT,'today845-phone320-equipment.png')});}
  await session.browser.close();session=null;console.log('DONE '+view.name+' '+report.checks.filter(c=>c.pass).length+'/'+report.checks.length);
 }}catch(error){check('Focused browser execution',false,error.stack);}finally{if(session)await session.browser.close();await guard.closeAll();report.guard=guard;check('Frozen candidate and scoped CSS remain unchanged',sha(fs.readFileSync(PAGE))===CANDIDATE_SHA&&sha(fs.readFileSync(path.join(__dirname,'text_clarity845_src.css')))==report.css);check('Every non-GET blocked and no operational write attempted',guard.nonGetSeen.length===guard.blocked.length&&!guard.nonGetSeen.some(r=>r.operational),guard.nonGetSeen);const unexpected=guard.consoleErrors.filter(e=>!(/Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(e.text)&&guard.blocked.some(b=>!b.operational&&b.url===e.url)));check('No unexpected console errors',!unexpected.length,unexpected);report.passed=report.checks.filter(c=>c.pass).length;report.total=report.checks.length;fs.writeFileSync(path.join(OUT,'today845.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,total:report.total,candidate:CANDIDATE_SHA}));if(report.passed!==report.total)process.exitCode=1;}
}
if(require.main===module)run().catch(e=>{console.error(e.message);process.exitCode=2;});
module.exports={read,reachable,settle};
