// Author: Andrew Fisher. Focused linked completion browser verification; all live writes blocked.
// PAGE, OUT, CANDIDATE_SHA required. LIVE=1 uses actual public HTML with no substitutions.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {installWriteGuard,ready840,nativeSnapshot}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const oracle=require('./test_linked_oracle844.cjs'),fence=require('./test_fencing844.cjs'),ui=require('./test_linked_ui844.cjs'),completion=require('./test_completion844.cjs');
const {typeInputs843,typeOracle843}=require('../v8.43_type_instruments_LIVE/test_type_oracle843.cjs');
const {open}=require('../toolchain/harness/open_page.js');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
async function run(){const {PAGE,OUT,CANDIDATE_SHA}=process.env;if(!PAGE||!OUT||!CANDIDATE_SHA)throw Error('Frozen PAGE/SHA and private OUT required');const bytes=fs.readFileSync(PAGE);if(sha(bytes)!==CANDIDATE_SHA)throw Error('Wrong candidate bytes');fs.mkdirSync(OUT,{recursive:true});const live=process.env.LIVE==='1',smoke=process.env.INITIAL_ONLY==='1',report={author:'Andrew Fisher',at:new Date().toISOString(),candidate:CANDIDATE_SHA,bytes:bytes.length,live,smoke,checks:[],views:[]},guard=installWriteGuard();let session;
 const check=(name,pass,evidence)=>{report.checks.push({name,pass:!!pass,evidence});if(!pass)console.log('FAIL '+name);if(report.checks.length%25===0||!pass)fs.writeFileSync(path.join(OUT,'checks844.json'),JSON.stringify({count:report.checks.length,passed:report.checks.filter(c=>c.pass).length,failures:report.checks.filter(c=>!c.pass),last:name},null,2));};
 const views=[{name:'laptop1366',W:1366,H:768,dpr:1},{name:'laptop1280',W:1280,H:800,dpr:1},{name:'phone',W:390,H:844,dpr:2,mobile:true},{name:'4k',W:3840,H:2160,dpr:1}].filter(v=>!process.env.VIEWS||process.env.VIEWS.split(',').includes(v.name));
 try{for(const view of views){console.log('START '+view.name);session=await open({pageFile:live?undefined:PAGE,hash:'#today',...view});const p=session.page;
  if(live){const up=guard.fulfilledDocuments.at(-1),got=guard.documentResponses.at(-1),bom=bytes.subarray(0,3).equals(Buffer.from([239,187,191])),stripped=bom&&got?.sha===sha(bytes.subarray(3))&&got.bytes===bytes.length-3;const exact=up?.status===200&&up.sha===CANDIDATE_SHA&&up.bytes===bytes.length&&got?.status===200&&(got.sha===CANDIDATE_SHA&&got.bytes===bytes.length||stripped)&&session.counts.page===0;check(view.name+' exact public upstream and browser bytes without local HTML substitution',exact,{up,got,stripped,counts:session.counts});if(!exact)throw Error('Public source identity differs');}
  await ready840(p);await p.waitForFunction(()=>typeof todayLinkedReferences844==='function'&&typeof todayLinkedFencing844==='function'&&TodayWork840.report().typesMerged);await p.evaluate(()=>photoIndex());await p.waitForFunction(()=>DOCS.state==='ready'||DOCS.state==='failed',null,{timeout:30000});
  const before=await nativeSnapshot(p),day=await p.evaluate(()=>TodayWork840.report().asOf),e=await oracle.linkedEvidence844(p,day),fn=await fence.nativeFencing844(p,day);report.views.push({view,evidence:e,nativeFencing:fn});
  check(view.name+' linked page is hydrated and public read only',await p.evaluate(()=>capability()==='view'&&SYNC.readonly&&location.pathname.startsWith('/v/Coates-GC500-2026'))&&e.linked.ready);
  oracle.assertLinked844(check,view.name,e);fence.assertFencing844(check,view.name,e.fences,fn);
  if(view.name==='laptop1366'){const expected=typeOracle843(await typeInputs843(p,day));for(const t of expected.instruments){const actual=e.types.instruments.find(x=>x.cardId===t.cardId&&x.groupId===t.groupId&&x.name===t.name),fields=['total','done','left','pct','pctKind','keys'];check(view.name+' '+t.name+' linked presentation preserves independently verified quantities',actual&&fields.every(k=>oracle.same(actual[k],t[k]))&&t.rows.every(row=>{const a=actual.rows.find(x=>x.key===row.key);return a&&['quantity','knownQuantity','done','left','complete','conflict'].every(k=>oracle.same(a[k],row[k]));}),{expected:t,actual});}}
  await ui.checkTypeRows844(p,check,view.name,e,!smoke&&view.name==='laptop1366');await ui.routes844(p,check,view.name,e,OUT);await ui.fencingUI844(p,check,view.name,e,OUT,!smoke&&view.name==='laptop1366');
  if(!smoke&&view.name==='laptop1366'){await ui.photoStates844(p,check,view.name,e);const captured=await completion.capturedCompletion844(p);completion.assertCompletion844(check,view.name,captured);report.completion=captured;
   const past=new Date(day+'T00:00:00Z');past.setUTCDate(past.getUTCDate()-1);const selected=past.toISOString().slice(0,10);await p.locator('#asOf').fill(selected);await p.locator('#asOf').press('Tab');await p.waitForFunction(day=>TodayWork840.report().asOf===day,selected);const replay=await oracle.linkedEvidence844(p,selected);check(view.name+' selected-day quantities and current shared status remain explicitly separate',replay.linked.asOf===selected&&replay.linked.currentDay===e.linked.currentDay&&oracle.same(replay.linked.rows.map(r=>[r.key,r.current]),e.linked.rows.map(r=>[r.key,r.current])),{selected,currentDay:replay.linked.currentDay});await ui.checkTypeRows844(p,check,view.name+' replay',replay,false);await p.locator('#asOf').fill(day);await p.locator('#asOf').press('Tab');await p.waitForFunction(day=>TodayWork840.report().asOf===day,day);
  }
  const after=await nativeSnapshot(p);check(view.name+' native collections and media remain unchanged',oracle.same(before.collections,after.collections)&&oracle.same(before.media,after.media));check(view.name+' no runtime errors',!session.errors.length,session.errors);await session.browser.close();session=null;console.log('DONE '+view.name+' '+report.checks.filter(c=>c.pass).length+'/'+report.checks.length);
 }}catch(e){check('Focused browser execution',false,e.stack);}finally{if(session)await session.browser.close();await guard.closeAll();report.guard=guard;check('Frozen candidate bytes unchanged',sha(fs.readFileSync(PAGE))===CANDIDATE_SHA);check('All non-GET requests blocked and no operational write attempted',guard.nonGetSeen.length===guard.blocked.length&&!guard.nonGetSeen.some(r=>r.operational),guard.nonGetSeen);const unexpected=guard.consoleErrors.filter(e=>!(/Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(e.text)&&guard.blocked.some(b=>!b.operational&&b.url===e.url)));check('No unexpected console errors',!unexpected.length,unexpected);report.passed=report.checks.filter(c=>c.pass).length;report.total=report.checks.length;fs.writeFileSync(path.join(OUT,'today844.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,total:report.total,candidate:CANDIDATE_SHA}));if(report.passed!==report.total)process.exitCode=1;}}
if(require.main===module)run().catch(e=>{console.error(e.message);process.exitCode=2;});
