// Author: Andrew Fisher. Exact reference cards, native routes and Back-to-breakdown.
'use strict';
const path=require('node:path'),{same,finite}=require('./test_linked_oracle844.cjs');
const fmt=n=>finite(n)?n.toLocaleString('en-AU',{maximumFractionDigits:2}):'—';
async function openType844(page,id,mode='left',real=false){const selector='[data-tw843-type-detail='+JSON.stringify(id)+'][data-tw843-type-mode='+mode+']:not([data-tw844-indicator])';if(real)await page.locator(selector).click();else await page.locator(selector).evaluate(b=>{b.focus({preventScroll:true});b.click();});await page.waitForFunction(({id,mode})=>{const d=document.querySelector('#gc500-work-dialog840');return d?.open&&d.querySelector('[data-tw843-detail-id]')?.dataset.tw843DetailId===id&&d.querySelector('[data-tw843-detail-mode]')?.dataset.tw843DetailMode===mode;},{id,mode});}
async function close844(page){await page.evaluate(()=>{window.__closed844=false;document.querySelector('#gc500-work-dialog840').addEventListener('close',()=>{__closed844=true;},{once:true});});await page.keyboard.press('Escape');await page.waitForFunction(()=>__closed844&&!document.querySelector('#gc500-work-dialog840').open);}
async function readDialog844(page){return page.locator('#gc500-work-dialog840').evaluate(d=>({text:d.textContent,subtitle:d.querySelector('.tw840-dialog-top p')?.textContent,selected:d.querySelector('[data-tw844-selected-day]')?.dataset.tw844SelectedDay,top:d.scrollTop,client:d.clientWidth,scroll:d.scrollWidth,rect:d.getBoundingClientRect().toJSON(),rows:[...d.querySelectorAll('[data-tw844-reference]')].map(r=>({key:r.dataset.tw844Reference,text:r.textContent,value:r.querySelector('[data-tw844-quantity]')?.textContent,current:r.querySelector('[data-tw844-current]')?.textContent,currentDay:r.querySelector('[data-tw844-current-day]')?.dataset.tw844CurrentDay,destination:r.querySelector('[data-tw844-destination]')?.textContent,actions:[...r.querySelectorAll('[data-tw844-action]')].map(b=>({kind:b.dataset.tw844Action,key:b.dataset.tw844Key})),photos:[...r.querySelectorAll('[data-tw844-photo]')].map(p=>({id:p.dataset.tw844Photo,state:p.dataset.tw844PhotoState,src:p.querySelector('img')?.getAttribute('src')||null,href:p.querySelector('a')?.getAttribute('href')||null,caption:p.querySelector('figcaption')?.textContent})),overflow:r.scrollWidth>r.clientWidth+1,labels:[...r.querySelectorAll('h3,h4,p,button,.tw844-item-quantity span')].map(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {font:parseFloat(s.fontSize),filter:s.filter,shadow:s.textShadow,tag:e.tagName,width:r.width,height:r.height};})}))}));}
async function checkTypeRows844(page,check,label,e,all){const assets=e.types.instruments.filter(t=>t.kind==='asset-type'),selected=all?assets:assets.filter((t,i)=>i===0||t.pctKind==='lower-bound'||t.total==null||/tank/i.test(t.name)||t===assets.find(x=>x.cardId===t.cardId));
 for(const t of selected){await openType844(page,t.id);const d=await readDialog844(page),expected=t.rows.filter(r=>!r.complete||!finite(r.left)||r.left>0),links=e.byType.find(x=>x.id===t.id).linked.rowsByKey;
  const bad=d.rows.filter(r=>{const n=expected.find(x=>x.key===r.key),link=links[r.key];return !n||r.value!==fmt(n.left)||!r.current?.includes(link.current.label)||!r.destination?.includes(link.destination.text)||r.currentDay!==e.linked.currentDay||r.actions.some(a=>a.key!==r.key)||!r.actions.some(a=>a.kind==='record')||!r.actions.some(a=>a.kind==='photos')||!link.photos.length&&!r.text.includes({ready:'No reference photographs recorded.',loading:'Checking reference photographs.',failed:'Reference photographs could not be checked.',unavailable:'Photo registry unavailable.'}[link.photoState]||'No reference photographs recorded.')||r.photos.some(p=>{const q=link.photos.find(q=>q.id===p.id);return !q||p.state!==q.availability||p.src!==(q.src||null)||p.href!==(q.fullSrc||null);});});
  check(label+' '+t.name+' Left opens exact linked reference quantities and current evidence',same(d.rows.map(r=>r.key),expected.map(r=>r.key))&&!bad.length&&d.selected===e.day&&/current record/.test(d.text)&&d.subtitle.includes(fmt(t.left))&&d.subtitle.includes('across '+expected.length+' references')&&d.rows.every(r=>!r.photos.length||/do not identify which units remain/.test(r.text)),{id:t.id,left:t.left,expected,shown:d,bad});
  check(label+' '+t.name+' linked detail fits and keeps readable labels and touch controls',d.scroll<=d.client+1&&d.rect.left>=0&&d.rect.right<=page.viewportSize().width+1&&d.rows.every(r=>!r.overflow&&r.labels.every(s=>s.font>=14&&s.filter==='none'&&s.shadow==='none'&&(s.tag!=='BUTTON'||s.height>=44&&s.width>=44))),{id:t.id,geometry:d.rect,rows:d.rows.map(r=>({key:r.key,overflow:r.overflow,labels:r.labels}))});await close844(page);
 }
}
async function routes844(page,check,label,e,out){
 const t=e.types.instruments.find(t=>t.kind==='asset-type'&&t.rows.some(r=>!r.complete&&finite(r.left)&&r.left>0)),target=t.rows.find(r=>!r.complete&&finite(r.left)&&r.left>0),key=target.key;
 await openType844(page,t.id,'left',true);const selectors=['record','map','photos'];
 for(const kind of selectors){const button=page.locator('[data-tw844-reference='+JSON.stringify(key)+'] [data-tw844-action='+kind+']');if(!await button.count())continue;await button.scrollIntoViewIfNeeded();await button.focus();const before=await page.evaluate(()=>({token:document.activeElement.dataset.tw840Focus,top:document.querySelector('#gc500-work-dialog840').scrollTop,main:document.querySelector('main').scrollTop,x:scrollX,y:scrollY}));await button.click();await page.waitForFunction(()=>document.querySelector('[data-tw844-return]'));
  const route=await page.evaluate(()=>({tab:state.tab,key:state.sel,docTile:state.docTile815,docOpen:state.docOpen815,drawer:document.querySelector('#drawer').classList.contains('on'),returns:document.querySelectorAll('[data-tw844-return]').length,dialog:document.querySelector('#gc500-work-dialog840')?.open}));
  check(label+' '+kind+' opens the exact native reference destination',route.returns===1&&!route.dialog&&(kind==='record'?route.drawer&&route.key===key:kind==='map'?route.tab==='map'&&route.key===key:route.tab==='docs'&&route.docTile==='photos'&&route.docOpen?.['ph:'+key]),{key,kind,route});
  if(kind==='record')await page.screenshot({path:path.join(out,'linked844-'+label+'-record-return.png')});await page.locator('[data-tw844-return]').click();await page.waitForFunction(()=>document.querySelector('#gc500-work-dialog840')?.open);await page.waitForFunction(token=>document.activeElement?.dataset.tw840Focus===token,before.token);const after=await page.evaluate(()=>({token:document.activeElement.dataset.tw840Focus,top:document.querySelector('#gc500-work-dialog840').scrollTop,main:document.querySelector('main').scrollTop,x:scrollX,y:scrollY,returns:document.querySelectorAll('[data-tw844-return]').length,mode:document.querySelector('[data-tw843-detail-mode]')?.dataset.tw843DetailMode,id:document.querySelector('[data-tw843-detail-id]')?.dataset.tw843DetailId}));
  check(label+' '+kind+' Back restores exact breakdown mode row focus and scroll',after.id===t.id&&after.mode==='left'&&after.token===before.token&&Math.abs(after.top-before.top)<=1&&after.returns===0&&after.x===before.x&&after.y===before.y,{before,after});
 }
 await page.locator('[data-tw844-reference='+JSON.stringify(key)+']').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'linked844-'+label+'-reference.png')});await close844(page);
 const sample=e.types.instruments.find(t=>t.kind==='asset-type'&&t.cardId==='toilets'&&t.pctKind==='lower-bound')||t;await openType844(page,sample.id,'left',true);await page.screenshot({path:path.join(out,'linked844-'+label+'-toilets.png')});await close844(page);
 // The percentage is an additional native Total entry, not another numeric record.
 for(const selector of ['[data-tw844-indicator][data-tw840-detail=buildings]','[data-tw844-indicator][data-tw843-type-detail='+JSON.stringify(t.id)+']']){const b=page.locator(selector);await b.click();await page.waitForFunction(()=>document.querySelector('#gc500-work-dialog840')?.open);const mode=await page.locator('#gc500-work-dialog840').getAttribute('data-mode');check(label+' percentage instrument opens total breakdown '+selector,mode==='total',mode);await close844(page);}
}
module.exports={openType844,close844,readDialog844,checkTypeRows844,routes844,fmt};
async function fencingUI844(page,check,label,e,out,all){
 const selected=all?e.fences:e.fences.slice(0,1);
 for(const entry of selected){const f=entry.linked;await page.locator('[data-tw840-fence-detail='+JSON.stringify(f.typeId)+']').click();await page.waitForFunction(()=>document.querySelector('#gc500-work-dialog840')?.open);const d=await page.locator('#gc500-work-dialog840').evaluate(d=>({text:d.textContent,scroll:d.scrollWidth,client:d.clientWidth,dockets:[...d.querySelectorAll('[data-tw844-docket]')].map(r=>({key:r.dataset.tw844Docket,value:r.querySelector('header strong')?.textContent,text:r.textContent,actions:[...r.querySelectorAll('[data-tw844-source-action]')].map(b=>JSON.parse(decodeURIComponent(b.dataset.tw844SourceAction)))})),planned:[...d.querySelectorAll('[data-tw844-planned-location]')].map(r=>({id:r.dataset.tw844PlannedLocation,value:r.querySelector('header strong')?.textContent,text:r.textContent,actions:[...r.querySelectorAll('[data-tw844-source-action]')].map(b=>JSON.parse(decodeURIComponent(b.dataset.tw844SourceAction)))}))}));
  check(label+' '+f.typeId+' supports exact docket and planned source links without allocating residuals',same(d.dockets.map(r=>r.key),f.dockets.map(r=>r.key))&&same(d.planned.map(r=>r.id),f.plannedLocations.map(r=>r.id))&&f.dockets.every(r=>{const x=d.dockets.find(x=>x.key===r.key);return x.value===fmt(r.quantity)&&same(x.actions,[r.recordAction,...r.areas.map(a=>a.action)])&&x.text.includes(r.location);})&&f.plannedLocations.every(r=>{const x=d.planned.find(x=>x.id===r.id);return x.value===fmt(r.quantity)&&same(x.actions,[...(r.sourceAction?[r.sourceAction]:[]),...r.mapIds.map(id=>({kind:'fencing-map',id}))]);})&&d.text.includes(f.basis)&&/not a list of the areas left/.test(d.text)&&d.scroll<=d.client+1,{id:entry.id,shown:d});
  if(f===selected[0].linked){const evidence=page.locator('[data-tw844-docket] header,[data-tw844-planned-location] header').first();if(await evidence.count())await evidence.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'linked844-'+label+'-fencing.png')});}await close844(page);
 }
 await page.locator('[data-tw840-detail=toilets][data-tw840-mode=left]').click();await page.waitForFunction(()=>document.querySelector('#gc500-work-dialog840')?.open);const b=page.locator('.tw844-supplier [data-tw844-source-action]'),action=await b.getAttribute('data-tw844-source-action');check(label+' toilet supplier shortcut retains native route-only contract',same(JSON.parse(decodeURIComponent(action)),e.supplier.action));await b.click();await page.waitForFunction(()=>state.tab==='timeline'&&document.querySelector('[data-tw844-return]'));await page.waitForFunction(()=>document.activeElement?.id==='ep819h',null,{timeout:2000}).catch(()=>{});const target=await page.evaluate(()=>({tab:state.tab,active:document.activeElement.id,rect:document.querySelector('#ep819').getBoundingClientRect().toJSON(),returns:document.querySelectorAll('[data-tw844-return]').length}));check(label+' toilet supplier shortcut opens its native Timeline plan',target.active==='ep819h'&&target.rect.height>0&&target.returns===1,target);await page.locator('[data-tw844-return]').click();await page.waitForFunction(()=>document.querySelector('#gc500-work-dialog840')?.open);check(label+' supplier Back restores the original Toilet Left breakdown',await page.locator('#gc500-work-dialog840').getAttribute('data-mode')==='left'&&await page.locator('.tw844-supplier').count()===1);await close844(page);
}
async function photoStates844(page,check,label,e){
 const t=e.types.instruments.find(t=>t.kind==='asset-type'&&t.rows.length),result=await page.evaluate(id=>{
  const original=todayLinkedReferences844,states=['ready','checking','unchecked','ambiguous','missing'];let selected='ready';const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=';const evidence=[];
  try{todayLinkedReferences844=(keys,o)=>{const value=original(keys,o);if(value.rows[0]){const r=value.rows[0];r.photos=[{id:'qa-state-photo844',availability:selected,src:selected==='ready'?png:null,fullSrc:selected==='ready'?png:null,caption:'Synthetic reference context — not proof of remaining units',kind:'drop',unit:null,slot:null,source:'drop'}];r.photoCount=1;r.readyPhotoCount=selected==='ready'?1:0;}return value;};
   const b=[...document.querySelectorAll('[data-tw843-type-detail]')].find(b=>b.dataset.tw843TypeDetail===id&&b.dataset.tw843TypeMode==='total'&&!b.hasAttribute('data-tw844-indicator'));b.focus({preventScroll:true});b.click();
   for(const state of states){selected=state;renderToday();const p=document.querySelector('[data-tw844-photo="qa-state-photo844"]');evidence.push({state,text:p?.textContent,img:p?.querySelector('img')?.getAttribute('src')||null,href:p?.querySelector('a')?.getAttribute('href')||null,caption:p?.querySelector('figcaption')?.textContent});}
  }finally{todayLinkedReferences844=original;renderToday();}return evidence;
 },t.id);
 for(const r of result)check(label+' synthetic '+r.state+' photograph preserves availability meaning and no stock fallback',r.caption?.includes('not proof')&&(r.state==='ready'?r.img?.startsWith('data:image/png;')&&r.href===r.img:!r.img&&!r.href&&(r.state==='checking'?/checking/i.test(r.text):r.state==='unchecked'?/could not|unable|not checked/i.test(r.text):r.state==='ambiguous'?/ambiguous|match|unavailable|identity.*review/i.test(r.text):/missing|unavailable|not available/i.test(r.text))),r);await close844(page);
}
module.exports.fencingUI844=fencingUI844;module.exports.photoStates844=photoStates844;
async function parentRows844(page,check,label,e,all){
 const areas=e.areas.filter(a=>a.id!=='fencing'&&(all||['buildings','toilets'].includes(a.id)));
 for(const a of areas){const button=page.locator('[data-tw840-detail='+a.id+'][data-tw840-mode=left]');await button.evaluate(b=>{b.focus({preventScroll:true});b.click();});await page.waitForFunction(()=>document.querySelector('#gc500-work-dialog840')?.open);const d=await readDialog844(page),rows=a.rows.filter(r=>!r.complete||finite(r.remaining)&&r.remaining>0),values=rows.map(r=>finite(r.quantity)&&finite(r.done)?Math.max(0,r.quantity-r.done):null),summary=e.summary.byId[a.id],review=rows.filter(r=>r.recordedComplete&&!r.complete),reviewKnown=review.every(r=>finite(r.quantity)),reviewQuantity=reviewKnown?review.reduce((n,r)=>n+r.quantity,0):null;
  check(label+' '+a.id+' parent Left connects its own quantities and review references',same(d.rows.map(r=>r.key),rows.map(r=>r.key))&&d.rows.every((r,i)=>r.value===fmt(values[i])&&(!(rows[i].recordedComplete&&!rows[i].complete)||/Requiring review/.test(r.text)))&&d.subtitle.startsWith(fmt(summary.left)+' ')&&d.subtitle.includes('across '+rows.length+' references')&&same(review.map(r=>r.key),summary.reviewRefs)&&reviewQuantity===summary.reviewQuantity&&/requiring review/.test(summary.basis)&&(!finite(summary.left)||values.every(finite)&&Math.abs(values.reduce((n,q)=>n+q,0)-summary.left)<1e-6),{id:a.id,left:summary.left,reviewKeys:review.map(r=>r.key),reviewQuantity,basis:summary.basis,keys:rows.map(r=>r.key),values,shown:d.rows.map(r=>({key:r.key,value:r.value,text:r.text}))});await close844(page);
 }
}
module.exports.parentRows844=parentRows844;
