// Author: Andrew Fisher. Paired native-record verification. Run under the shared browser lock.
const fs=require('fs'),path=require('path'),vm=require('module'),assert=require('assert/strict'),crypto=require('crypto');
const out=process.env.OUT938||'/tmp/gc500-record938';fs.mkdirSync(out,{recursive:true});
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),m=new vm.Module(hp,module);m.filename=hp;m.paths=vm.Module._nodeModulePaths(path.dirname(hp));let src=fs.readFileSync(hp,'utf8');assert(src.includes('const okPost =')&&src.includes('counts.blocked++;'));
src=src.replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++;(counts.blockedPaths||=[]).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});");
src=src.replace("if (u.startsWith('data:')",`if(process.env.REPLAY938&&r.method()==='GET'&&['/api/state','/api/version'].includes(new URL(u).pathname)){const st=JSON.parse(fs.readFileSync(process.env.REPLAY938)),v=new URL(u).pathname==='/api/state'?st:{version:st.version,level:'view'};return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(v)});}if (u.startsWith('data:')`);m._compile(src,hp);const {open}=m.exports;
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
async function read(p){return p.evaluate(()=>holdAssets(()=>({state:S,refs:allAssets().map(a=>({key:a.key,cancelled:a._cancelled||false,status:deliveryOf(a.key),dates:effectiveDates(a),units:unitsOf(a.key),numbers:assetNumbersOf(a),items:itemRows(a),notes:S.notes[a.key],unloading:handling875Record(a),doors:loading872Rows(a).map(r=>({...r,side:loading872Side(a,r.id)})),physical:gcUnits925(a)})),inventory:inventory(),today:todayFigures(),dsn:dsnState(todayIso()),equipment:plantGroups().map(([name,rows])=>({name,keys:rows.map(a=>a.key)})),timeline:programmeDays().map(d=>({iso:d.iso,deliveries:(d.deliveries||[]).map(r=>({key:r.a.key,items:dpItems(r),booked:r.a._bookingNumbers801}))})),money:{M:moneySummary(),X:cj764Model(),P:pl770Model(),B:pl752Rows(),V:transport888View(),R:recon888Model(),RH:rh766Model(),contract:contractFigures(ONHIRE_ROWS),quotes:DATA.rehire_quotes}})));}
async function run(file,label,mobile){const s=await open({pageFile:file,hash:'#plant',mobile,W:mobile?390:1400,H:mobile?844:1000});try{const p=s.page;await p.waitForFunction(()=>SYNC.status==='live'&&Object.keys(SYNC_COLLS).every(k=>SYNC.first.has(k)),null,{timeout:180000});if(!process.env.REPLAY938){const raw=await p.evaluate(async()=>{const r=await fetch('/api/state',{headers:{'x-gc500-token':localStorage.getItem('gc500.view')||location.pathname.split('/')[2]},cache:'no-store'});if(!r.ok)throw Error('Snapshot refused');return r.json();});fs.writeFileSync(path.join(out,'authenticated-state.json'),JSON.stringify(raw));}
await p.evaluate(()=>{SYNC.unsub.forEach(f=>f());SYNC.unsub=[];window.__writes938=[];window.bump=()=>{__writes938.push('bump');throw Error('Read-only test attempted save')};const native=SYNC.db.doc.bind(SYNC.db);SYNC.db.doc=(...args)=>{const d=native(...args);for(const k of ['set','delete','update'])if(typeof d[k]==='function')d[k]=()=>{__writes938.push(k);throw Error('Read-only test attempted document write')};return d;};window.__before938=JSON.stringify(S);});
const data=await read(p);fs.writeFileSync(path.join(out,label+'-models.json'),JSON.stringify(data));const result={sha:hash(file),refs:data.refs.length,recordVersion:JSON.parse(fs.readFileSync(path.join(out,'authenticated-state.json'))).version};
if(label!=='before'){
 const wc=data.refs.find(a=>a.key==='WC31'),vms=data.refs.find(a=>a.key==='T0103');assert(wc.doors.some(x=>x.no==='12'&&x.item==='16Pan Block'));assert(!wc.doors.some(x=>x.no==='12'&&x.item==='Accessible Toilet'));assert(wc.physical.some(x=>x.assetNo==='12'&&x.loadingId==='u12'));
 const vrow=data.inventory.list.find(r=>r.item==='VMS'),vr=vrow.refs.T0103,vu=vms.physical;assert.equal(vr.on,2);assert.equal(vu.length,2);assert.equal(vr.coates,1);assert.equal(vr.sub,1);assert.equal(vr.nonum,0);assert.equal(vr.cos['PremAir Hire'],1);
 result.print=await p.evaluate(()=>{const a=assetOf('WC31'),h=loading872Sheet(a);const legacy=['F01','T0233','T0235','T0242','T0245'].map(ref=>({ref,entries:journal({ref}).length}));return {sheet:h,legacy};});assert(result.print.sheet.includes('16Pan Block')&&result.print.sheet.includes('12')&&!result.print.sheet.includes('Accessible Toilet'));assert(result.print.legacy.every(x=>x.entries>0));
 await p.evaluate(()=>openAsset('WC31'));await p.waitForTimeout(400);const wcbox=p.locator('#drawer .loading872').filter({hasText:'Loading ·'}).first();await wcbox.evaluate(el=>{for(let n=el;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;const sc=el.closest('.db');if(sc)sc.scrollTop+=el.getBoundingClientRect().top-sc.getBoundingClientRect().top-20;});result.drawerBounds=await p.locator('#drawer').evaluate(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,width:innerWidth};});assert(result.drawerBounds.left>=-2&&result.drawerBounds.right<=result.drawerBounds.width+2);await p.screenshot({path:path.join(out,label+'-wc31.png')});await p.evaluate(()=>document.getElementById('dclose')?.click());
 await p.evaluate(()=>{state.q='';state.light='';state.plantGroup='VMS boards';go('plant');render();});await p.locator('[data-invdrill="Variable message signs|VMS|sub"]').click();result.supplierDrill=await p.locator('#invDrill').innerText();assert(result.supplierDrill.includes('T0103')&&result.supplierDrill.includes('PremAir Hire 1'));await p.locator('#invDrill').evaluate(el=>el.scrollIntoView({block:'start'}));await p.screenshot({path:path.join(out,label+'-vms.png')});await p.locator('[data-invdrill="Variable message signs|VMS|coates"]').click();const ct=await p.locator('#invDrill').innerText();assert(ct.includes('1211404')&&!ct.includes('sub-17093'));result.inventoryNumbersCorrect=true;
}
result.unchanged=await p.evaluate(()=>JSON.stringify(S)===__before938);assert(result.unchanged);assert.deepEqual(await p.evaluate(()=>__writes938),[]);result.errors=s.errors;assert.deepEqual(s.errors,[]);result.requests=s.counts;assert((s.counts.blockedPaths||[]).every(x=>x.method==='POST'&&x.origin==='https://tile.googleapis.com'&&x.path==='/v1/createSession'));fs.writeFileSync(path.join(out,label+'-result.json'),JSON.stringify(result,null,2));return {data,result};
}finally{await s.browser.close();}}
(async()=>{if(process.env.PHONE938_ONLY){process.env.REPLAY938=path.join(out,'authenticated-state.json');const p=await run(process.env.PAGE,'phone',true);console.log(JSON.stringify({phoneErrors:p.result.errors,drawerBounds:p.result.drawerBounds}));return;}delete process.env.REPLAY938;const before=await run(process.env.BEFORE938,'before',false);process.env.REPLAY938=path.join(out,'authenticated-state.json');const after=await run(process.env.PAGE,'desktop',false),A=after.data,B=before.data;
for(const k of ['state','today','dsn','equipment','timeline','money'])assert.deepEqual(A[k],B[k],k+' changed');const changes=[];for(const a of A.refs){const b=B.refs.find(x=>x.key===a.key);for(const k of Object.keys(a)){if(k==='doors'||k==='physical')continue;assert.deepEqual(a[k],b[k],a.key+' '+k+' changed');}for(const k of ['doors','physical'])if(JSON.stringify(a[k])!==JSON.stringify(b[k]))changes.push({ref:a.key,field:k});}assert(changes.every(x=>x.ref==='WC31'));
for(const a of A.inventory.list){const b=B.inventory.list.find(x=>x.type===a.type);for(const k of ['asked','on','spares','spareC','spareSub'])assert.deepEqual(a[k],b[k],a.item+' quantity changed');for(const r of Object.values(a.refs||{})){const old=b.refs[r.key];for(const k of ['asked','on','onsite'])assert.deepEqual(r[k],old[k],r.key+' '+k+' changed');if(r.key!=='T0103')assert.deepEqual(r,old,r.key+' unrelated Inventory changed');}}
const phone=await run(process.env.PAGE,'phone',true);const safe={author:'Andrew Fisher',baseSha:before.result.sha,candidateSha:after.result.sha,recordVersion:after.result.recordVersion,references:A.refs.length,changedReferenceFields:changes,operationalStateUnchanged:true,moneyUnchanged:true,allInventoryQuantitiesUnchanged:true,onlyInventoryReferenceChanged:'T0103',legacyJournalPreserved:true,desktopErrors:after.result.errors,phoneErrors:phone.result.errors,desktopDenied:after.result.requests.blockedPaths||[],phoneDenied:phone.result.requests.blockedPaths||[],phoneAndDesktopInspected:false};fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(safe,null,2));console.log(JSON.stringify(safe,null,2));})().catch(e=>{console.error(e.stack);process.exitCode=1});
