// Author: Andrew Fisher. Typed identity regressions and optional native snapshot verification.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const history=[['R16','done','VMS boards — 22 required','Supply remains 22 VMS boards. Confirmation recorded 01 Oct 2026.']];
const box={QHIST:history,DATA:{schedule_review875:{vms_boq:23},schedule_review950:{source:'GC500 26 Schedule (7).xlsx',reviewed:'2026-10-09'}}};vm.createContext(box);for(const f of ['inventory960.js','scope960.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,f),'utf8'),box);
const {allocation,reconcileInventory}=box.Inventory960,copy=x=>JSON.parse(JSON.stringify(x));
const company=o=>({'coates':'Coates','event-portables':'Event Portables','prem-air-hire':'PremAir Hire'}[o]||o);
const unit=(ref,item,owner,assetNo)=>({ref,item,owner,assetNo,physical:true,id:JSON.stringify([ref,owner,assetNo])});
const wc09={groups:[{item:'FWF',quantity:4},{item:'Pee Panel',quantity:6},{item:'Toilet Block 6m',quantity:2}],rows:[...['0085','0551','0450','0585'].map(n=>unit('WC09','FWF','event-portables',n)),...['1268858','1311146'].map(n=>unit('WC09','Toilet Block 6m','coates',n))]};
assert.equal(allocation(wc09,'FWF',4,company,'WC09').sub,4);
assert.equal(allocation(wc09,'Pee Panel',6,company,'WC09').sub,0);
assert.equal(allocation(wc09,'Pee Panel',6,company,'WC09').nonum,0);
assert.equal(allocation(wc09,'Pee Panel',6,company,'WC09').quantityOnly,true);
assert.equal(box.Inventory960.unitDescription(wc09,'WC09','event-portables','0085'),'FWF','supplier subtotal reads the same type as Inventory');
assert.equal(box.Inventory960.unitDescription(wc09,'WC40','event-portables','0085'),'','supplier description cannot borrow another reference');
assert.deepEqual(copy(allocation(wc09,'Toilet Block 6m',2,company,'WC09').numbers),['1268858','1311146']);
assert.equal(allocation(wc09,'FWF',0,company,'WC09'),null,'not arrived does not become stock');
assert.equal(allocation(wc09,'FWF',2,company,'WC09').sub,0,'partial arrival never selects first two identities');
assert.equal(allocation(wc09,'FWF',2,company,'WC09').nonum,2);
const duplicate=copy(wc09);duplicate.rows[1]=copy(duplicate.rows[0]);
assert.equal(allocation(duplicate,'FWF',4,company,'WC09').sub,0,'duplicate identity is not double-counted');
assert.equal(box.Inventory960.unitDescription(duplicate,'WC09','event-portables','0085'),'','ambiguous identity has no inferred description');
const unknown=copy(wc09);unknown.rows.forEach(u=>{u.item='Description to confirm';});
assert.equal(allocation(unknown,'FWF',4,company,'WC09').sub,0,'ambiguous item does not borrow identities');
assert.equal(allocation(unknown,'FWF',4,company,'WC09').nonum,4);
const wrongref=copy(wc09);wrongref.rows[0].ref='WC40';
assert.equal(allocation(wrongref,'FWF',4,company,'WC09').sub,0,'cross-reference identity cannot move silently');
const vms={groups:[{item:'VMS',quantity:2}],rows:[unit('T0103','VMS','coates','1211404'),unit('T0103','VMS','prem-air-hire','120T')]};
assert.equal(allocation(vms,'VMS',2,company,'T0103').coates,1);
assert.equal(allocation(vms,'VMS',2,company,'T0103').sub,1);
assert.deepEqual(copy(allocation(vms,'VMS',2,company,'T0103').cos),{'PremAir Hire':1});
const scope={total:24,done:10,left:14,pct:41.67,pctKind:'confirmed',basis:'Native',issues:[]};
box.Scope960.applyScope(scope);
assert.equal(scope.pctKind,'provisional-scope');assert.equal(scope.scopeProvisional960,true);
assert.deepEqual([scope.total,scope.done,scope.left,scope.pct],[24,10,14,41.67]);
for(const term of ['22','01 Oct 2026','23','24','2026-10-09','Schedule (7)'])assert.ok(scope.scopeNote960.includes(term));
assert.equal(box.Scope960.applyScope({total:22,pct:45.45,pctKind:'confirmed'}).scopeProvisional960,false);
box.QHIST=[['R16','done','VMS boards — 24 required','Supply remains 24 VMS boards. Confirmation recorded 10 Oct 2026.']];
assert.equal(box.Scope960.applyScope({total:24,pct:41.67,pctKind:'confirmed'}).scopeProvisional960,false,'new canonical requirement must flow into Today');
assert.match(box.Scope960.requirementHtml(24),/requirement: 24 boards/,'new canonical requirement must flow into Equipment');
assert.match(box.Scope960.requirementHtml(24),/schedule and recorded requirement agree/);
assert.doesNotMatch(box.Scope960.requirementHtml(24),/22|unresolved/);
box.QHIST=[];assert.equal(box.Scope960.applyScope({total:24,pct:41.67,pctKind:'confirmed'}).scopeProvisional960,true,'missing requirement is not silently settled');
box.QHIST=history;
assert.match(box.Scope960.lightingNote({done:4,total:6,scope894:{confirmed:true,complete:5,recorded:7,surplus:[{surplus:1}]}}),/4 of 6.*5 complete of 7 recorded.*1 surplus/);
if(process.argv[2]){
 const data=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),refs=new Map(data.refs.map(r=>[r.key,r])),before=copy(data.inventory),source=JSON.stringify(data);
 const after=reconcileInventory(copy(before),key=>refs.get(key)?.gcModel,company);
 const totals=i=>i.list.map(r=>[r.type,r.asked,r.on,r.spares,r.spareC,r.spareSub,Object.values(r.refs).map(x=>[x.key,x.asked,x.on,x.onsite])]);
 assert.deepEqual(totals(after),totals(before),'all quantity, spare and arrival facts unchanged');
 assert.equal(JSON.stringify(data),source,'source record and models unchanged');
 assert.deepEqual(copy(after.cos),before.cos,'overall supplier stock unchanged by item reclassification');
 const find=(item,key)=>after.list.find(r=>r.item===item&&r.refs[key]).refs[key];
 assert.equal(find('FWF','WC09').sub,4);assert.equal(find('Pee Panel','WC09').sub,0);
 assert.equal(find('Pee Panel','WC09').on,6);assert.equal(find('Pee Panel','WC09').nonum,0);
 assert.equal(find('Toilet Block 6m','WC09').coates,2);
 assert.equal(find('FWF','WC69').on,0);assert.equal(find('FWF','WC40').on,0);
 assert.deepEqual(refs.get('WC69').gcUnits.map(u=>u.assetNo),['0152','0078','0010','0070','0958','0647']);
 assert.equal(refs.get('WC40').gcUnits.length,0);
 assert.equal(find('VMS','T0103').coates,1);assert.equal(find('VMS','T0103').sub,1);assert.equal(find('VMS','T0103').on,2);
 const changes=after.list.filter((r,i)=>JSON.stringify(r)!==JSON.stringify(before.list[i])).map(r=>({item:r.item,on:r.on,coates:r.coates,sub:r.sub,nonum:r.nonum,unnumbered:!!r.unnum}));
 console.log(JSON.stringify({nativeSnapshot:'passed',quantityAndSourceUnchanged:true,changes},null,2));
}
if(process.argv[3]&&process.argv[4]){
 const native=JSON.parse(fs.readFileSync(process.argv[3],'utf8')),html=fs.readFileSync(process.argv[4],'utf8');
 const start=html.indexOf('function progress881Model(day, suppliedSummary, suppliedFence) {'),end=html.indexOf('/* Author: Andrew Fisher. v8.85',start);
 assert.ok(start>0&&end>start);vm.runInContext(html.slice(start,end),box);
 const summary=copy(native.models.summary),fence=copy(native.models.fenceOverall853),before=box.progress881Model(summary.asOf,summary,fence);
 box.Scope960.applyScope(summary.byId.vms);
 const after=box.progress881Model(summary.asOf,summary,fence),vms=after.rows.find(r=>r.id==='vms');
 assert.equal(after.ready,true);assert.equal(vms.provisional,true);assert.equal(vms.min,41.67);assert.equal(vms.done,10);assert.equal(vms.total,24);
 assert.equal(after.pct.min,before.pct.min);assert.equal(after.pct.max,before.pct.max);assert.equal(after.allGreen,false);
 const all=copy(summary);for(const id of ['buildings','toilets','generators','lighting','vms','equipment'])Object.assign(all.byId[id],{pct:100,pctKind:id==='vms'?'provisional-scope':'confirmed',reviewQuantity:0,unquantifiedRefs:0});
 const complete=box.progress881Model(all.asOf,all,{state:'ready',pct:{min:100,max:100},provisional:false});
 assert.equal(complete.allGreen,false,'100% against unresolved scope is not a finished whole job');
 assert.equal(complete.reached,4);assert.match(box.Scope960.lightingNote(summary.byId.lighting),/4 of 6.*5 complete of 7 recorded.*1 surplus/);
 console.log('Native shared scope/whole-job progress tests passed');
}
console.log('v9.60 typed allocation and scope tests passed');
