/* Author: Andrew Fisher. Current CW1 evidence within the existing native planning cards. */
function cw1ForecastText954(){
 const r=DATA.fencing && DATA.fencing.source_review954;
 return r ? `CW1 uses the 9 October PDF and email. ${r.provisional_task_count} prior task allowances remain provisional pending source review; they have not been confirmed as extra work. The 50 m Gate 6 CCB stockpile is not added as another installation.` : '';
}
function cw1Plan954(u){
 const words=fields=>Object.entries(fields||{}).filter(([,n])=>n!==0).map(([key,n])=>{
  const c=FCOL.find(x=>x.programme_type===key);return `${esc(fmtQty(n,c?c.unit:/\(m\)/.test(key)?'m':'each'))} ${esc(c?c.name_as_written:key)}`;
 }).join('<br>')||'<span class="todo">Quantity not stated — not zero</span>';
 const issues=new Map((u.conflicts||[]).map(x=>[x.id,x]));
 const rowHtml=row=>`<tr data-cw1-task954="${esc(row.id)}" data-cw1-review954="${esc(row.review_state954)}"><td><b>${esc(row.location)}</b><br>${esc(row.description)}<br><span class="w">${row.source_pages954.length?'PDF pp. '+esc(row.source_pages954.join(', ')):esc(row.programme_source954)}</span>${row.review_state954==='prior allowance pending review'?'<br><span class="chip cand">Prior allowance · review pending</span>':''}</td><td>${words(row.fields)}${(row.conflicts||[]).map(id=>{const x=issues.get(id);return x?`<details class="pdetail"><summary>${esc(x.state==='dated update supported'?'Source date discrepancy':'Source review required')}</summary><p>${esc(x.summary)}</p><p>${esc(x.detail)}</p></details>`:''}).join('')}</td><td>${row.note?`<p>${esc(row.note)}</p>`:''}${(row.requirements||[]).length?`<ul class="hublist compact">${row.requirements.map(x=>`<li><b>Condition: </b>${esc(x.text)} <span class="w">(p. ${esc(x.page)})</span></li>`).join('')}</ul>`:''}</td></tr>`;
 return `<style>[data-cw1-plan954] .tblwrap td:first-child,[data-cw1-plan954] .tblwrap th:first-child{position:static;box-shadow:none}[data-cw1-plan954] .tblwrap td{vertical-align:top}</style><div class="planupd" data-cw1-plan954><h3>${esc(u.title)} — reviewed 9 Oct 2026</h3>
 <p>${esc(u.basis)}</p><p class="w">${esc(u.file)} · ${u.pages} pages · John Brett · ${esc(u.created_display)}. Supplied email: ${esc(u.email954.sent_display)}.</p>
 <p class="notice warn"><b>Provisional forecast, not confirmed work.</b> ${esc(cw1ForecastText954())} Signed dockets, supplier costs, rates and site completion are unchanged.</p>
 ${(u.rows_by_day||[]).map(day=>`<details class="fp-evidence" data-cw1-day954="${esc(day.date)}"><summary>${esc(fmtDate(day.date))} · ${day.rows.length} planned tasks${day.rows.some(r=>r.review_state954==='prior allowance pending review')?' · includes allowances awaiting review':''}</summary><div class="fp-evidence-body"><p>${esc(u.email954.highlights[day.date]||'')}</p><div class="tblwrap" tabindex="0" aria-label="CW1 ${esc(day.date)} tasks and source conditions"><table class="daytbl"><thead><tr><th>Task / source</th><th>Forecast quantity and review</th><th>Access, crew and conditions</th></tr></thead><tbody>${day.rows.map(rowHtml).join('')}</tbody></table></div></div></details>`).join('')}
 <details class="fp-evidence" data-cw1-stockpile954><summary>50 m CCB stockpile · source evidence only</summary><div class="fp-evidence-body">${u.stockpile_evidence954.map(x=>`<p>${esc(fmtDate(x.date))} · ${esc(x.location)} · PDF p. ${esc(x.page)}<br>${esc(x.note)}</p>`).join('')}<p>No additional installation or unique hire stock has been added to the forecast.</p></div></details>
 <details class="fp-evidence"><summary>Programme comparator and calculation basis</summary><div class="fp-evidence-body"><p>Selected task rows are added once. Printed PDF subtotals mix stale dates, crossed-out work and different scope; they are not used. Cypress pp. 21–22 are identical and counted once. Earlier programme rows, including omitted tasks, remain in the source-history fold.</p><div class="tblwrap" tabindex="0" aria-label="CW1 earlier programme and selected forecast quantities"><table class="daytbl"><thead><tr><th>Day</th><th>Earlier programme</th><th>Current supported updates plus provisional allowances</th></tr></thead><tbody>${u.differences.map(x=>`<tr><td>${esc(fmtDate(x.date))}</td><td>${words(x.programme)}</td><td>${words(x.plan)}</td></tr>`).join('')}</tbody></table></div></div></details>
 </div>`;
}
