/* Author: Andrew Fisher. Tabbable scope, single-trap boundaries and supplier presentation only. */
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const document={activeElement:null},root={},context={document,root,txt:v=>String(v??'').trim(),getComputedStyle:b=>({visibility:b.visibility||'visible'})};vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../focus939.js'),'utf8')+'\n'+fs.readFileSync(path.join(__dirname,'../supplier939.js'),'utf8')+'\nthis.api={tabStops939,tabKey939,supplierLabel939};',context);const api=context.api;
function node(label,opts={}){return Object.assign({label,tagName:'BUTTON',tabIndex:0,disabled:false,hidden:false,isContentEditable:false,form:null,focus(){document.activeElement=this;},matches(q){return q===':disabled'&&!!this.fieldsetDisabled},closest(){return this.inertOrHidden?{}:null},getClientRects(){return this.noBox?[]:[{}]},hasAttribute(k){return k==='tabindex'&&!!this.explicitTabIndex}},opts)}
const box=rows=>({querySelectorAll:()=>rows,contains:b=>rows.includes(b)||b?.inside});
const labels=n=>Array.from(api.tabStops939(n),b=>b.label);
function event(shift=false){return{shiftKey:shift,stopped:false,prevented:false,stopImmediatePropagation(){this.stopped=true},preventDefault(){this.prevented=true}}}
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name)}
test('native summaries are part of the tab sequence',()=>assert.deepEqual(labels(box([node('first'),node('summary',{tagName:'SUMMARY'}),node('next')])),['first','summary','next']));
test('disabled and disabled-fieldset controls are omitted',()=>assert.deepEqual(labels(box([node('disabled',{disabled:true}),node('fieldset',{fieldsetDisabled:true}),node('ok')])),['ok']));
test('hidden/inert/display-none/visibility-hidden controls are omitted',()=>assert.deepEqual(labels(box([node('a',{hidden:true}),node('b',{inertOrHidden:true}),node('c',{noBox:true}),node('d',{visibility:'hidden'}),node('e',{visibility:'collapse'}),node('ok')])),['ok']));
test('closed details omit retained hidden layout boxes but keep first summary',()=>{const summary=node('summary',{tagName:'SUMMARY'}),hidden=node('hidden');const d={children:[summary],parentElement:null};summary.contains=b=>b===summary;summary.parentElement=hidden.parentElement={closest:()=>d};assert.deepEqual(labels(box([summary,hidden,node('ok')])),['summary','ok'])});
test('negative tabIndex excludes buttons and summaries',()=>assert.deepEqual(labels(box([node('a',{tabIndex:-1}),node('b',{tagName:'SUMMARY',tabIndex:-1}),node('ok')])),['ok']));
test('native editable element without explicit tabindex is included',()=>assert.deepEqual(labels(box([node('edit',{isContentEditable:true,tabIndex:-1}),node('skipped',{isContentEditable:true,tabIndex:-1,explicitTabIndex:true})])),['edit']));
test('positive tabindex comes first and ties preserve document order',()=>assert.deepEqual(labels(box([node('normal'),node('two',{tabIndex:2}),node('oneA',{tabIndex:1}),node('oneB',{tabIndex:1}),node('normal2')])),['oneA','oneB','two','normal','normal2']));
test('checked named radio is the group tab stop',()=>assert.deepEqual(labels(box([node('one',{tagName:'INPUT',type:'radio',name:'x'}),node('two',{tagName:'INPUT',type:'radio',name:'x',checked:true}),node('other',{tagName:'INPUT',type:'radio',name:'y'})])),['two','other']));
test('same radio name in distinct forms remains independent',()=>assert.deepEqual(labels(box([node('a',{tagName:'INPUT',type:'radio',name:'x',form:{}}),node('b',{tagName:'INPUT',type:'radio',name:'x',form:{}})])),['a','b']));
test('interior summary allows native Tab and prevents competing traps',()=>{const a=node('first'),s=node('summary',{tagName:'SUMMARY'}),last=node('last');document.activeElement=s;const e=event();api.tabKey939(e,box([a,s,last]));assert(e.stopped);assert(!e.prevented);assert.equal(document.activeElement,s)});
test('programmatically focused interior element is not sent to header',()=>{const a=node('first'),inner=node('inner',{tabIndex:-1}),last=node('last');document.activeElement=inner;const e=event();api.tabKey939(e,box([a,inner,last]));assert(e.stopped);assert(!e.prevented);assert.equal(document.activeElement,inner)});
test('forward last-control boundary wraps to first',()=>{const a=node('first'),b=node('last');document.activeElement=b;const e=event();api.tabKey939(e,box([a,b]));assert(e.stopped&&e.prevented);assert.equal(document.activeElement,a)});
test('reverse first-control boundary wraps to last',()=>{const a=node('first'),b=node('last',{tagName:'SUMMARY'});document.activeElement=a;const e=event(true);api.tabKey939(e,box([a,b]));assert(e.stopped&&e.prevented);assert.equal(document.activeElement,b)});
test('outside focus is brought into active overlay',()=>{const a=node('first');document.activeElement=node('outside');const e=event();api.tabKey939(e,box([a]));assert(e.stopped&&e.prevented);assert.equal(document.activeElement,a)});
test('empty overlay does not consume native keyboard handlers',()=>{const e=event();api.tabKey939(e,box([]));assert(!e.stopped&&!e.prevented)});
test('unnamed-supplier fallback is readable',()=>assert.equal(api.supplierLabel939('other:supplier-not-named'),'Supplier Not Named'));
test('known supplier names remain correct',()=>{assert.equal(api.supplierLabel939('event-portables'),'Event Portables');assert.equal(api.supplierLabel939('prem-air-hire'),'PremAir Hire');assert.equal(api.supplierLabel939('other:example-company'),'Example Company')});
test('native supplier formatter is used without changing stored key',()=>{const calls=[];root.Units925={company:key=>{calls.push(key);return 'Native company'}};assert.equal(api.supplierLabel939('other:supplier-not-named'),'Native company');assert.deepEqual(calls,['other:supplier-not-named'])});
console.log(checks+'/'+checks+' checks passed');
