// Author: Andrew Fisher. Private actual desktop/phone Arrange-load samples.
const fs=require('fs'),assert=require('assert/strict');const {open}=require('./nativeHarness942.cjs');const pv=require('./preservation942.cjs');
const out=process.env.OUT942||'/tmp/private-shapes942',file=process.env.PAGE;if(!file)throw Error('Set PAGE to the candidate');process.env.RECORD942=out+'/authenticated-state.json';
async function run(mobile){const label=mobile?'phone':'desktop',s=await open({pageFile:file,hash:'#timeline',mobile,W:mobile?390:1400,H:mobile?844:1000});try{const p=s.page;await p.waitForFunction(()=>SYNC.status==='live'&&Object.keys(SYNC_COLLS).every(k=>SYNC.first.has(k)),null,{timeout:180000});await pv.guard(p);const before=await pv.capture(p),results=[];const samples=process.env.BLOCK_ONLY?[['2026-10-07','WC20']]:mobile?[['2026-10-07','WC20'],['2026-10-09','WC09'],['2026-09-17','P36'],['2026-10-19','']]:[['2026-10-09','WC09'],['2026-10-07','WC20'],['2026-09-17','P36']];for(const [day,ref] of samples){await p.evaluate(({day})=>{document.querySelector('[data-drop911-close]')?.click();state.day=day;state.tlView='day';state.q='';state.disc='';state.light='';go('timeline');render();},{day});const id=await p.evaluate(ref=>{const r=Drops911.report();return (r.model.loads.find(l=>l.refs.some(x=>x.key===ref)&&(ref!=='WC20'||l.id.includes('dd-26112783')))||r.model.loads[0]).id;},ref);const opener=p.locator('[data-drop911-open]').filter({has:p.locator('never-matches')});await p.evaluate(id=>[...document.querySelectorAll('[data-drop911-open]')].find(b=>b.dataset.drop911Open===id)?.click(),id);await p.waitForFunction(()=>['ready','unavailable'].includes(Drops911.report().status),null,{timeout:100000});await p.waitForTimeout(150);const result=await p.evaluate(()=>{const report=Drops911.report(),el=document.getElementById('drops911-workspace');return {day:report.day,status:report.status,selected:report.selected,model:report.model,markers:[...el.querySelectorAll('[data-drop911-marker]')].map(b=>({id:b.dataset.drop911Marker,key:b.dataset.destination930Key,label:b.getAttribute('aria-label'),refs:b.title,n:b.querySelector('.destination930-number').textContent,rect:(()=>{const r=b.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}})()})),shapes:[...el.querySelectorAll('[data-shape926-unit]')].map(b=>({id:b.dataset.shape926Unit,text:b.innerText,svgLabel:b.querySelector('svg')?.getAttribute('aria-label'),classes:[...b.querySelectorAll('svg .ms926-comp')].map(x=>x.getAttribute('class'))})),productCards:[...el.querySelectorAll('[data-shape942-product]')].map(b=>({item:b.dataset.shape942Product,text:b.innerText})),mapOutlines:[...el.querySelectorAll('[data-shape926-map-ref]')].map(b=>b.dataset.shape926MapRef),overflow:document.documentElement.scrollWidth>innerWidth+2};});
assert.equal(result.day,day);if(ref==='WC09'){assert.equal(result.shapes.length,0);assert.deepEqual(result.productCards.map(x=>x.item),['FWF','Pee Panel']);}if(ref==='P36'){assert.equal(result.shapes.length,0);assert.equal(result.productCards[0].item,'Building 6m');}if(ref==='WC20'){assert.equal(result.shapes.length,1);assert(!result.shapes[0].text.includes('WASTE TANK'));assert(result.shapes[0].text.includes('driver side'));}for(const b of result.markers){const l=result.model.loads.find(l=>l.id===b.id);assert(l,'marker has no native load');assert.equal(String(l.n),b.n);for(const r of b.refs.split(' · '))assert(l.refs.some(x=>x.key===r));}assert.equal(result.overflow,false);await p.locator('.shapes926').evaluate(el=>el.scrollIntoView({block:'start'}));await p.screenshot({path:out+'/'+label+'-'+day+'-'+(ref||'dense')+(process.env.BLOCK_ONLY?'-block':'')+'-shapes.png'});await p.locator('.drops911-view').evaluate(el=>el.scrollIntoView({block:'center'}));await p.screenshot({path:out+'/'+label+'-'+day+'-'+(ref||'dense')+(process.env.BLOCK_ONLY?'-block':'')+'-map.png'});
const marker=p.locator('[data-drop911-marker]').first();if(await marker.count()){const target=await marker.getAttribute('data-drop911-marker');await marker.click({force:true});assert.equal(await p.evaluate(()=>Drops911.report().selected),target);result.markerSelection=true;}
result.readonly=await pv.inspectReadonly(p,'.r931');assert(result.readonly.every(x=>!x.controls.length&&!x.saveButtons.length&&!x.emptyRows.length));results.push(result);await p.locator('[data-drop911-close]').click({force:true});assert.equal(await p.locator('#drops911-workspace').count(),0);console.log(label+' '+day+' '+ref+' checked');}
pv.unchanged(before,await pv.capture(p));const denied=await pv.assertNoWrites(p,s);assert.deepEqual(s.errors,[]);fs.writeFileSync(out+'/'+label+(process.env.BLOCK_ONLY?'-block':'')+'-visible.json',JSON.stringify({results,denied,errors:s.errors,stateUnchanged:true,financeUnchanged:true},null,2));}finally{await s.browser.close();}}
(async()=>{await run(false);await run(true);})().catch(e=>{console.error(e.stack);process.exitCode=1;});
