/* Author: Andrew Fisher. Current ownership and identity regression checks. */
const assert=require('node:assert/strict');
const {select}=require('../item_identity979');
const line=(number,ref='OLD',item='Requested building')=>({rental_contract:'C1',line:1,asset_no:number,asset_no_is_plant_number:true,register_type:item,match:{key:ref}});
const unit=(owner,number,item='Building')=>({physical:true,owner,assetNo:number,item});
const run=(units,rows)=>select('WC20','Building',rows,units);
assert.equal(run([unit('coates','123')],[line('123')]).length,1);
assert.equal(run([unit('event-portables','123')],[line('123')]).length,0);
assert.equal(run([unit('unknown','123')],[line('123')]).length,0);
assert.equal(run([unit('coates','456')],[line('123','WC20','Building')]).length,0);
assert.equal(run([unit('coates','123','Tank')],[line('123')]).length,0);
assert.equal(run([{...unit('coates','123'),physical:false}],[line('123')]).length,0);
const bulk={...line('MISCITEM','WC20','Building'),asset_no_is_plant_number:false};
assert.equal(run([unit('event-portables','123')],[bulk]).length,1);
assert.equal(run([],[{...bulk,match:{task_id:'WC20'}}]).length,1);
assert.equal(run([],[{...bulk,register_type:'Tank'}]).length,0);
assert.equal(run([unit('coates',' 123 ')],[line('123')]).length,1);
const source=line('123'); const result=run([unit('coates','123')],[source]);
assert.equal(source.match.key,'OLD');assert.equal(result[0].match.key,'WC20');assert.equal(result[0].register_type,'Building');
const delivered={...line('123'),status_as_written:'Delivered',start_date:'2026-09-14'};
const pending={...line('123'),line:2,status_as_written:'Pending',start_date:null};
assert.deepEqual(run([unit('coates','123')],[delivered,pending]).map(r=>r.line),[1]);
assert.equal(run([unit('coates','123')],[pending]).length,1);
assert.equal(run([unit('coates','123')],[delivered,{...pending,start_date:'2026-10-01'}]).length,2);
assert.equal(run([unit('coates','123')],[delivered,{...pending,asset_no:'456'}]).length,1);
assert.equal(run([],[{...bulk,match:{},description:'WC20 Building'}]).length,1);
assert.equal(run([],[{...bulk,match:{key:'P04'},description:'WC20 Building'}]).length,0);
assert.equal(run([],[{...bulk,match:{},description:'WC200 Building'}]).length,0);
const container={...bulk,register_type:'Event Container',description:'Container 3.0M x 2.4M',match:{task_id:'T0258'}};
assert.equal(select('T0258','3.0m Cont',[container],[]).length,1);
assert.equal(select('T0258','3.0m Cont',[{...container,description:'Container 6.0M x 2.4M'}],[]).length,0);
console.log('20 current identity checks passed');
