// Author: Andrew Fisher. Source mutations must retain the original held state.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const page=fs.readFileSync(process.env.PAGE,'utf8'),snapshot=JSON.parse(fs.readFileSync(process.env.STATE,'utf8'));
const sources=snapshot.preservation.embeddedData.rental_on_hire.rows,assets=snapshot.preservation.assets.map(x=>x.asset),poa='Transport is POA; unit quantities do not establish a priced customer load';
const building={id:'T0025|Trakmat',ref:'T0025',item:'Trakmat',quantity:20,numbers:['TRAKMAT2.4X1.1'],branch:'STPS',contracts:['9973079'],lineKeys:[],rate:null,holdReasons:[poa],holdReasonsByLeg:{}};
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../trackmat979.js','utf8'),c);vm.runInContext(page.slice(page.indexOf('function buildingTransport831(input){'),page.indexOf('function buildingTransportSource831')),c);
const clone=x=>JSON.parse(JSON.stringify(x));let checks=0;const ck=v=>{assert(v);checks++;};
const baseline=c.buildingTransport831({buildings:[building],coverage:[]});const bs=clone([building]),readonly=JSON.stringify({sources,assets});const override=c.trackmatDeliveryCoverage979(bs,sources,assets);ck(!!override);const after=c.buildingTransport831({buildings:bs,coverage:[override]});ck(after.rows[0].state==='covered');ck(after.rows[0].coveredQuantity===20);ck(after.rows[0].coverage[0].amount===103.3);ck(after.rows[1].state==='held');ck(after.rows[1].coveredQuantity===0);ck(after.uncoveredAdditional===baseline.uncoveredAdditional);ck(after.heldEstimate===baseline.heldEstimate);ck(JSON.stringify({sources,assets})===readonly);ck(after.rows[0].rate===null);ck(after.rows[0].additional===0);
for(const [type,field,value] of [['charge','price',104],['charge','description','Delivery for HA Line Item(s) 1,3 15 Sep 2026'],['charge','quantity',2],['charge','delivery_number','changed'],['charge','branch_code','KINP'],['charge','status_as_written','Cancelled'],['charge','hold_billing',true],['charge','return_number','123'],['hire','quantity',21],['hire','line',3],['hire','delivery_number','changed'],['hire','asset_no_is_plant_number',true],['hire','start_date','2026-09-16'],['asset','_cancelled',true],['asset','relocation',true],['asset','asset_numbers',['other']],['building','quantity',21],['building','branch','KINP'],['building','rate',100]]){
 const ss=clone(sources),aa=clone(assets),bb=clone([building]);const target=type==='charge'?ss.find(r=>r.rental_contract==='9973079'&&r.line===2):type==='hire'?ss.find(r=>r.rental_contract==='9973079'&&r.line===1):type==='asset'?aa.find(a=>a.key==='T0025'):bb[0];target[field]=value;const before=JSON.stringify(bb);ck(c.trackmatDeliveryCoverage979(bb,ss,aa)===null);ck(JSON.stringify(bb)===before);
}
for(const mutate of [ss=>ss.push({...ss.find(r=>r.rental_contract==='9973079'&&r.line===1),line:3}),ss=>ss.push({...ss.find(r=>r.rental_contract==='9973079'&&r.line===2)}),ss=>ss.find(r=>r.rental_contract==='9973079'&&r.line===1).match.task_id='OTHER']){const ss=clone(sources),bb=clone([building]);mutate(ss);ck(c.trackmatDeliveryCoverage979(bb,ss,assets)===null);}
ck(c.trackmatDeliveryCoverage979([clone(building),clone(building)],sources,assets)===null);
console.log(JSON.stringify({author:'Andrew Fisher',checks,pass:true,delivery:'On contract',pickup:'POA',existingCharge:103.3,additionalRevenueDelta:after.uncoveredAdditional-baseline.uncoveredAdditional,recordedRevenuePosting:0},null,2));
