// Author: Andrew Fisher. Actual native Crew controls; synthetic names and isolated in-memory saves only.
// Run with PAGE and private absolute EVIDENCE_DIR under flock /tmp/gc500-browser.lock.
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{open}=require('../../toolchain/harness/open_page');
(async()=>{let s;try{
 const out=process.env.EVIDENCE_DIR,pageFile=process.env.PAGE;
 if(!out||!path.isAbsolute(out)||!pageFile||!fs.existsSync(pageFile))throw Error('PAGE and absolute private EVIDENCE_DIR are required');
 fs.mkdirSync(out,{recursive:true});
 const source=fs.readFileSync(pageFile,'utf8');if(!source.includes('StaffNames910'))throw Error('Expected v9.10 staff candidate');
 s=await open({pageFile,hash:'#timeline',W:390,H:844});const p=s.page,blocked=[],checks=[];
 const ok=(name,pass,detail)=>checks.push({name,pass:!!pass,...(detail===undefined?{}:{detail})});
 await p.context().route('**/*',r=>{if(r.request().method()!=='GET'){const u=new URL(r.request().url());blocked.push({method:r.request().method(),host:u.host,path:u.pathname});return r.abort();}return r.fallback();});
 await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:180000});
 const actualRosterCounts=await p.evaluate(()=>Object.fromEntries(['2026-10-08','2026-10-09','2026-10-12','2026-10-14'].map(d=>[d,StaffNames910.roster(d).length])));
 const finalDisabledGuard=await p.evaluate(()=>document.getElementById('staff910-style').textContent.includes('transition:none'));
 const version=await p.evaluate(()=>SYNC.db.readVersion821());
 await p.context().route('**/api/version',r=>r.request().method()==='GET'?r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({level:'edit',version})}):r.abort());
 const context=await p.evaluate(()=>{
  const t=window.STAFF_ACTUAL910={before:JSON.stringify(S),original:{bump,save,capability,mayWrite,whoAmI,flash,ourCosts,doc:SYNC.db.doc,readonly:SYNC.readonly,level:SYNC.level},saves:[],unexpected:[],flashes:[],storageFailure:false};
  // All persistence paths are captured before granting isolated practice edit capability.
  save=()=>{t.unexpected.push('save');return false;};
  SYNC.db.doc=()=>({set:async()=>{t.unexpected.push('database set');},delete:async()=>{t.unexpected.push('database delete');}});
  bump=()=>{t.saves.push({availability:JSON.parse(JSON.stringify(S.loads[t.dayKey]||null)),plan:JSON.parse(JSON.stringify(S.loads[t.planKey]||null))});bump.kept=!t.storageFailure;render();};
  capability=()=> 'edit';mayWrite=()=>true;whoAmI=()=> 'Isolated staff check';flash=m=>t.flashes.push(String(m));SYNC.readonly=false;SYNC.level='edit';
  const d=programmeDays().find(x=>x.iso==='2026-10-06'&&dpLoads(x).length)||programmeDays().find(x=>x.iso<todayIso()&&dpLoads(x).length);
  if(!d)throw Error('No past programme day with native loads');state.day=d.iso;state.tlView='day';go('timeline');render();
  const el=document.querySelector('#pane-timeline .crew883');if(!el)throw Error('Native crew editor not found');
  t.day=el.dataset.crew883Day;t.ref=el.dataset.crew883Ref;t.dayKey=crew883Key(t.day);t.planKey=crew883Key(t.day,t.ref);
  t.cleanLoads=JSON.parse(JSON.stringify(S.loads||{}));for(const [k,v]of Object.entries(t.cleanLoads))if(v.kind==='crew883'&&v.day===t.day)delete t.cleanLoads[k];
  t.finance=JSON.stringify({costs:S.costs,finance:S.finance745,dayStaffOn:S.dayStaffOn});
  t.install=cfg=>{
   S.loads=JSON.parse(JSON.stringify(t.cleanLoads));t.saves=[];t.flashes=[];t.storageFailure=false;
   t.rows=(cfg.rows||['Practice Alpha','Practice Bravo','Practice Charlie']).map((name,i)=>Object.assign({id:'staff910-practice-'+i,kind:'labour',usable:true,date:t.day,person:typeof name==='string'?name:'',hours:8,start:'06:00',finish:'14:00',break_min:0},typeof name==='object'?name:{}));
   ourCosts=()=>t.rows;
   if(cfg.count!==undefined)S.loads[t.dayKey]={kind:'crew883',day:t.day,ref:'',count:cfg.count,names:cfg.names||[],by:'Isolated staff check',at:'2026-10-01T00:00:00.000Z'};
   S.loads[t.planKey]=Object.assign({kind:'crew883',day:t.day,ref:t.ref,order:null,people:[{slot:null,roles:['installer']}],start:'',finish:'',location:'Practice area',by:'Isolated staff check',at:'2026-10-01T00:00:00.000Z'},cfg.plan||{});
   state.day=t.day;state.tlView='day';render();
  };
  t.install({count:4,names:[]});return {day:t.day,ref:t.ref};
 });
 const selector='#pane-timeline .crew883[data-crew883-ref="'+context.ref+'"][data-crew883-day="'+context.day+'"]';
 const editor=()=>p.locator(selector).first();
 const expand=async()=>editor().evaluate(e=>{e.open=true;e.querySelectorAll('details').forEach(d=>d.open=true);});
 const install=async cfg=>{await p.evaluate(cfg=>STAFF_ACTUAL910.install(cfg),cfg);await expand();};
 const chooseName=async(slot,name)=>{const select=editor().locator('[data-staff910-name-slot="'+slot+'"]');const value=await select.locator('option').evaluateAll((es,name)=>es.find(e=>e.textContent.includes(name))?.value,name);if(value==null)throw Error('Missing synthetic name option');await select.selectOption(value);};
 const feedback=()=>editor().locator('[data-staff910-message]').allTextContents();
 const writeCount=()=>p.evaluate(()=>STAFF_ACTUAL910.saves.length);
 const field=async(attr,value)=>{const el=editor().locator('['+attr+']');if(await el.evaluate(e=>e.tagName)==='SELECT')await el.selectOption(value);else await el.fill(value);};
 const unchanged=()=>p.evaluate(()=>{const t=STAFF_ACTUAL910;return !t.saves.length&&JSON.stringify({costs:S.costs,finance:S.finance745,dayStaffOn:S.dayStaffOn})===t.finance;});
 const contrast=()=>editor().evaluate(root=>{
  const rgba=s=>{const a=(s.match(/[\d.]+/g)||[]).map(Number);return [a[0]||0,a[1]||0,a[2]||0,a.length>3?a[3]:1];};
  const mix=(a,b)=>a.slice(0,3).map((v,i)=>v*a[3]+b[i]*(1-a[3])).concat(1);
  const back=e=>{if(!e)return [255,255,255,1];const c=rgba(getComputedStyle(e).backgroundColor);return c[3]>=1?c:mix(c,back(e.parentElement));};
  const lum=c=>c.slice(0,3).map(x=>{x/=255;return x<=0.04045?x/12.92:((x+0.055)/1.055)**2.4;}).reduce((n,x,i)=>n+x*[0.2126,0.7152,0.0722][i],0);
  return [...root.querySelectorAll('button,input,select,textarea')].filter(e=>e.getClientRects().length&&!['checkbox','radio','hidden'].includes(e.type)).map(e=>{const s=getComputedStyle(e),parent=back(e.parentElement),opacity=Number(s.opacity),bg=mix(back(e).slice(0,3).concat(opacity),parent),fg=mix(mix(rgba(s.webkitTextFillColor||s.color),back(e)).slice(0,3).concat(opacity),parent),a=lum(fg),b=lum(bg),r=e.getBoundingClientRect();return {tag:e.tagName,selector:[...e.attributes].filter(a=>a.name.startsWith('data-')).map(a=>a.name).join(','),disabled:e.disabled,ratio:(Math.max(a,b)+0.05)/(Math.min(a,b)+0.05),colour:s.color,background:s.backgroundColor,opacity,fits:r.left>=0&&r.right<=innerWidth};});
 });
 await expand();
 ok('enhanced native crew editor is present',await editor().getAttribute('data-staff910')!==null);
 ok('opening a count-four unnamed day does not persist anything',await writeCount()===0);
 ok('saved count-four blank slots remain four separate name choices',await editor().locator('[data-staff910-name-slot]').count()===4&&await p.evaluate(()=>crew883Day(STAFF_ACTUAL910.day).count===4&&crew883Day(STAFF_ACTUAL910.day).names.length===0));
 await chooseName(1,'Practice Alpha');await chooseName(3,'Practice Bravo');
 await field('data-crew883-order','2');await field('data-crew883-location','Practice unloading area');
 await editor().locator('[data-crew883-slot]').first().selectOption('3');
 await editor().locator('[data-crew883-role="escort"]').first().check();
 ok('name and task selections are drafts until their own Save action',await unchanged());
 await editor().locator('[data-crew883-day-save]').click();await expand();
 ok('Save day writes only the day mapping with blank slot positions intact',await p.evaluate(()=>{const t=STAFF_ACTUAL910,d=crew883Day(t.day),a=crew883Plan(t.day,t.ref);return t.saves.length===1&&d.count===4&&d.names[0]==='Practice Alpha'&&!d.names[1]&&d.names[2]==='Practice Bravo'&&!d.names[3]&&a.order===null&&a.location==='Practice area'&&a.people[0].slot===null&&a.start===''&&a.finish==='';}));
 ok('Save day retains unsaved order, location, task person and multiple roles in the form',await editor().evaluate(e=>e.querySelector('[data-crew883-order]').value==='2'&&e.querySelector('[data-crew883-location]').value==='Practice unloading area'&&e.querySelector('[data-crew883-slot]').value==='3'&&e.querySelector('[data-crew883-role="installer"]').checked&&e.querySelector('[data-crew883-role="escort"]').checked));
 ok('historical unknown unloading times remain blank after the day save',await editor().evaluate(e=>e.querySelector('[data-crew883-start]').value===''&&e.querySelector('[data-crew883-finish]').value===''));
 ok('task dropdown names use saved positions including the unnamed second person',await editor().locator('[data-crew883-slot]').first().evaluate(e=>e.options[1].textContent.includes('Practice Alpha')&&e.options[2].textContent.includes('Person 2')&&e.options[3].textContent.includes('Practice Bravo')));
 await editor().locator('[data-crew883-save]').click();await expand();
 ok('Save crew plan assigns one named person with multiple roles and no inferred times',await p.evaluate(()=>{const t=STAFF_ACTUAL910,a=crew883Plan(t.day,t.ref);return t.saves.length===2&&a.people.length===1&&a.people[0].slot===3&&a.people[0].roles.length===2&&a.people[0].roles.includes('installer')&&a.people[0].roles.includes('escort')&&a.order===2&&a.location==='Practice unloading area'&&a.start===''&&a.finish==='';}));
 let colours=await contrast();ok('all enabled Crew buttons and selectors are readable on phone',colours.length>5&&colours.filter(x=>!x.disabled).every(x=>x.ratio>=4.5),colours);
 ok('all visible Crew controls fit the phone width',colours.every(x=>x.fits));
 await editor().locator('[data-staff910-name-slot="1"]').evaluate(e=>e.scrollIntoView({block:'center'}));await p.waitForTimeout(180);
 await p.screenshot({path:path.join(out,'staff-names-phone-390.png')});
 await editor().locator('[data-crew883-save]').evaluate(e=>e.scrollIntoView({block:'center'}));await p.waitForTimeout(180);
 await p.screenshot({path:path.join(out,'staff-buttons-phone-390.png')});
 await editor().evaluate(e=>e.querySelectorAll('button,input,select,textarea').forEach(x=>x.disabled=true));
 if(finalDisabledGuard){const immediate=await contrast();ok('disabled Crew controls are readable immediately without a pale transition frame',immediate.every(x=>x.ratio>=3),immediate);}
 await p.waitForTimeout(250); // Let the native background transition reach its final disabled colour.
 const disabledColours=await contrast();ok('disabled Crew buttons and selectors stay readable',disabledColours.length>5&&disabledColours.every(x=>x.ratio>=3),disabledColours);
 if(!process.env.STAFF910_CONTRAST_ONLY){
 await install({count:0,names:[]});
 ok('manual zero availability is not replaced by three roster names',await editor().locator('[data-crew883-count]').inputValue()==='0'&&await editor().locator('[data-staff910-name-slot]').count()===0&&await unchanged());
 await install({count:4,names:[]});await field('data-crew883-count','500');await editor().locator('[data-crew883-count]').press('Tab');
 ok('invalid count cannot render hundreds of person controls',await editor().locator('[data-staff910-name-slot]').count()<=50);
 await editor().locator('[data-crew883-day-save]').click();ok('invalid count is rejected without changing saved availability',await p.evaluate(()=>!STAFF_ACTUAL910.saves.length&&crew883Day(STAFF_ACTUAL910.day).count===4));
 await install({count:null,names:[]});
 ok('saved unknown availability stays unknown when roster suggestions exist',await editor().locator('[data-crew883-count]').inputValue()===''&&await p.evaluate(()=>crew883Day(STAFF_ACTUAL910.day).count===null)&&await unchanged());
 await install({rows:[]});
 ok('no dated roster leaves availability unknown without creating zero',await p.evaluate(()=>!S.loads[STAFF_ACTUAL910.dayKey]&&crew883Day(STAFF_ACTUAL910.day).count===null)&&await unchanged());
 await install({});await editor().locator('[data-staff910-use-roster]').click();
 ok('Use roster stages names and count without creating availability or task records',await editor().locator('[data-crew883-count]').inputValue()==='3'&&await writeCount()===0&&await p.evaluate(()=>!S.loads[STAFF_ACTUAL910.dayKey]));
 ok('unsaved roster names cannot yet be selected for a task',await editor().locator('[data-crew883-slot]').first().locator('option').count()===1);
 await editor().locator('[data-crew883-day-save]').click();await expand();
 ok('explicit day save makes roster names selectable while leaving the task unassigned',await editor().locator('[data-crew883-slot]').first().locator('option').count()===4&&await p.evaluate(()=>STAFF_ACTUAL910.saves.length===1&&crew883Plan(STAFF_ACTUAL910.day,STAFF_ACTUAL910.ref).people[0].slot===null));
 await install({count:2,names:[],rows:['Practice Eligible',{person:'Practice Wrong Day',date:'2026-11-30'},{person:'Practice Contact Only',kind:'person'},{person:'Practice Invalid',usable:false},{person:'Practice Zero Hours',hours:0,start:'',finish:''},{person:'Fencing crew',group:true}]});
 ok('suggestions include only eligible named labour on the exact selected day',await editor().locator('[data-staff910-name-slot]').first().evaluate(e=>{const text=e.textContent;return text.includes('Practice Eligible')&&!/Wrong Day|Contact Only|Practice Invalid|Zero Hours|Fencing crew/.test(text);}));
 await install({count:2,names:['Practice Existing Off Roster','']});
 ok('saved names remain selectable even when no longer on the forecast',await editor().locator('[data-staff910-name-slot]').first().evaluate(e=>e.selectedOptions[0].textContent.includes('Practice Existing Off Roster')));
 await install({count:4,names:['Practice Alpha','','',''],plan:{people:[{slot:4,roles:['spotter']}]}});
 await chooseName(2,'Practice Bravo');await editor().locator('[data-crew883-day-save]').click();await expand();
 ok('adding a name preserves existing unnamed assigned slot four',await p.evaluate(()=>{const t=STAFF_ACTUAL910,d=crew883Day(t.day),a=crew883Plan(t.day,t.ref);return d.names[0]==='Practice Alpha'&&d.names[1]==='Practice Bravo'&&!d.names[2]&&!d.names[3]&&a.people[0].slot===4;}));
 await install({count:1,names:['Practice Alpha'],plan:{people:[{slot:4,roles:['installer']}]}});
 ok('existing out-of-count assignment is still visible and selected',await editor().locator('[data-crew883-slot]').first().inputValue()==='4');
 await editor().locator('[data-crew883-save]').click();
 ok('saving an unchanged legacy assignment does not silently renumber it',await p.evaluate(()=>crew883Plan(STAFF_ACTUAL910.day,STAFF_ACTUAL910.ref).people[0].slot===4));
 await install({count:2,names:['Practice Alpha','Practice Bravo']});
 await chooseName(2,'Practice Charlie');
 await p.evaluate(()=>{S.loads[STAFF_ACTUAL910.dayKey].names[0]='Practice Concurrent';});
 await editor().locator('[data-crew883-day-save]').click();
 ok('stale day editor cannot overwrite a newer slot mapping',await p.evaluate(()=>!STAFF_ACTUAL910.saves.length&&crew883Day(STAFF_ACTUAL910.day).names[0]==='Practice Concurrent'));
 ok('stale day refusal is visible in the form',(await feedback()).join(' ').match(/changed|refresh|reopen/i));
 await install({count:2,names:['Practice Alpha','Practice Bravo']});
 await p.evaluate(selector=>{const t=STAFF_ACTUAL910,origin=document.querySelector(selector),duplicate=origin.cloneNode(true);duplicate.id='staff910-stale-practice';document.body.append(duplicate);t.staleToken=duplicate.dataset.staff910DayToken;S.loads[t.dayKey].names[0]='Practice Concurrent';duplicate.querySelector('[data-crew883-names]').value='Practice Concurrent\nPractice Bravo';StaffNames910.refresh(origin);},selector);
 await expand();await chooseName(2,'Practice Charlie');await editor().locator('[data-crew883-day-save]').click();
 ok('saving another day form does not clear an already-stale task mapping token',await p.evaluate(()=>{const e=document.getElementById('staff910-stale-practice'),kept=e&&e.dataset.staff910DayToken===STAFF_ACTUAL910.staleToken;if(e)e.remove();return kept;}));
 await install({count:2,names:['Practice Alpha','Practice Bravo']});
 await editor().locator('[data-crew883-slot]').first().selectOption('1');
 await p.evaluate(()=>{S.loads[STAFF_ACTUAL910.planKey].location='Practice updated elsewhere';});
 await editor().locator('[data-crew883-save]').click();
 ok('stale task editor cannot overwrite a newer task plan',await p.evaluate(()=>!STAFF_ACTUAL910.saves.length&&crew883Plan(STAFF_ACTUAL910.day,STAFF_ACTUAL910.ref).location==='Practice updated elsewhere'));
 await install({count:2,names:['Practice Alpha','Practice Alpha']});
 await editor().locator('[data-crew883-day-save]').click();
 ok('unchanged duplicate names accepted by the old form can be retained',await p.evaluate(()=>STAFF_ACTUAL910.saves.length===1&&JSON.stringify(crew883Day(STAFF_ACTUAL910.day).names)===JSON.stringify(['Practice Alpha','Practice Alpha'])));
 await install({count:2,names:['Practice Alpha','Practice Bravo']});
 await editor().locator('[data-crew883-add]').click();await expand();
 const people=editor().locator('[data-crew883-person]');await people.nth(0).locator('[data-crew883-slot]').selectOption('1');await people.nth(1).locator('[data-crew883-slot]').selectOption('1');await people.nth(1).locator('[data-crew883-role="escort"]').check();
 await editor().locator('[data-crew883-save]').click();
 ok('same person cannot be saved as two separate people on one task',await writeCount()===0);
 await install({count:2,names:[]});await chooseName(1,'Practice Alpha');
 await p.evaluate(()=>{STAFF_ACTUAL910.storageFailure=true;});await editor().locator('[data-crew883-day-save]').click();await expand();
 ok('storage failure reports uncertainty instead of durable success',/not.*sav|could not|unsaved|couldn.t|not confirmed/i.test((await feedback()).join(' ')));
 ok('storage failure does not roll back or manufacture a second task save',await p.evaluate(()=>{const t=STAFF_ACTUAL910;return t.saves.length===1&&crew883Day(t.day).names[0]==='Practice Alpha'&&crew883Plan(t.day,t.ref).people[0].slot===null;}));
 await install({count:2,names:[]});await chooseName(1,'Practice Alpha');await p.evaluate(()=>{whoAmI=()=>null;});await editor().locator('[data-crew883-day-save]').click();
 ok('native missing-operator refusal makes no availability change',await p.evaluate(()=>!STAFF_ACTUAL910.saves.length&&crew883Day(STAFF_ACTUAL910.day).names.length===0));
 await p.evaluate(()=>{whoAmI=()=> 'Isolated staff check';});
 await install({count:2,names:['Practice Alpha','Practice Bravo']});
 await p.evaluate(()=>{capability=()=> 'view';SYNC.readonly=true;render();});await expand();
 ok('view-only crew editor cannot offer save actions',await editor().locator('[data-crew883-save],[data-crew883-day-save]').count()===0);
 ok('view-only person and time selectors stay disabled',await editor().locator('[data-crew883-slot],[data-crew883-start],[data-crew883-finish]').evaluateAll(es=>es.length===3&&es.every(e=>e.disabled)));
 }
 const restored=await p.evaluate(()=>{const t=STAFF_ACTUAL910,unexpected=t.unexpected.slice(),financeUntouched=JSON.stringify({costs:S.costs,finance:S.finance745,dayStaffOn:S.dayStaffOn})===t.finance;S=JSON.parse(t.before);bump=t.original.bump;save=t.original.save;capability=t.original.capability;mayWrite=t.original.mayWrite;whoAmI=t.original.whoAmI;flash=t.original.flash;ourCosts=t.original.ourCosts;SYNC.db.doc=t.original.doc;SYNC.readonly=t.original.readonly;SYNC.level=t.original.level;return {unchanged:JSON.stringify(S)===t.before,financeUntouched,unexpected};});
 ok('all synthetic state restored without attendance or finance writes',restored.unchanged&&restored.financeUntouched&&!restored.unexpected.length,restored);
 ok('no operational network write attempted',!blocked.some(x=>x.host==='gc500-production.up.railway.app')&&!s.counts.blocked,{blocked});
 ok('no runtime errors',!s.errors.length,s.errors);
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({candidateSha256:crypto.createHash('sha256').update(source).digest('hex'),finalDisabledGuard,actualRosterCounts,checks,context,restored,blocked,errors:s.errors},null,2));checks.forEach(c=>console.log((c.pass?'PASS ':'FAIL ')+c.name));console.log(checks.filter(c=>c.pass).length+'/'+checks.length);if(checks.some(c=>!c.pass))process.exitCode=1;
}finally{if(s)await s.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
