// Author: Andrew Fisher. Actual served page only: no local page substitution and no writes.
const fs=require('fs');const {open}=require(require('path').join(process.env.GC500_TOOLCHAIN||require('path').resolve(__dirname,'../../toolchain'),'harness/open_page.js'));
if(!process.env.OUT)throw Error('Set a private OUT directory');fs.mkdirSync(process.env.OUT,{recursive:true});const OUT=process.env.OUT,report={author:'Andrew Fisher',scope:'Actual public v8.27 desktop and phone Chromium playback smoke; no physical-device claim',at:new Date().toISOString(),checks:[],views:[]};
const check=(name,pass,evidence)=>{report.checks.push({name,pass:!!pass,evidence});console.log((pass?'PASS ':'FAIL ')+name)};
(async()=>{for(const mobile of [false,true]){let s;const tag=mobile?'phone':'desktop';try{
 s=await open({W:mobile?390:1440,H:mobile?844:1000,mobile,dpr:mobile?2:1});const p=s.page;await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:180000});
 const release=await p.locator('meta[name="gc500-release"]').getAttribute('content');check(tag+': served release is v8.27',release==='v8.27',release);check(tag+': no local page override',s.counts.page===0);
 await p.evaluate(()=>{localStorage.setItem('gc500.band','shown');go('today')});const fig=p.locator('#pane-today .bhero[data-board="video"]');await fig.scrollIntoViewIfNeeded();await p.waitForTimeout(250);
 if(mobile)await p.emulateMedia({reducedMotion:'reduce'});
 const still=await fig.evaluate(f=>f.querySelector('video').paused&&!!f.querySelector('.bplay').onclick&&!f.querySelector('.bplay').disabled);check(tag+': loaded still with enabled explicit Play',still);
 await fig.locator('.bplay').click();await p.waitForFunction(()=>{const v=document.querySelector('#pane-today .bhero video');return v&&!v.paused&&v.currentTime>.5},null,{timeout:15000});const media=await fig.evaluate(f=>{const v=f.querySelector('video');return{time:v.currentTime,paused:v.paused,playing:f.classList.contains('playing'),display:getComputedStyle(v).display,muted:v.muted,source:v.currentSrc,motionOff:motionOff(),boardTimer:!!BOARD_RUN.timer,selectedCard:TodayMotion820.report().running}});check(tag+': real media visibly advances with sound',media.playing&&media.display!=='none'&&!media.muted&&media.time>.5,media);if(mobile)check('phone: reduced preference retains no decorative animation',media.motionOff&&!media.boardTimer&&media.selectedCard===null);
 await fig.locator('.bplay').click();check(tag+': Stop restores still',await fig.evaluate(f=>f.querySelector('video').paused&&!f.classList.contains('playing')));await p.screenshot({path:OUT+'/public-'+tag+'-video.png'});
 await p.evaluate(()=>go('register'));await p.evaluate(()=>go('today'));check(tag+': return does not autoplay',await p.locator('#pane-today .bhero video').evaluate(v=>v.paused));check(tag+': no page errors or operational writes',s.errors.length===0&&s.counts.blocked===0,{errors:s.errors,blocked:s.counts.blocked});report.views.push({viewport:tag,counts:s.counts});
 }catch(e){check(tag+': execution',false,e.message)}finally{if(s)await s.browser.close()}}
 report.passed=report.checks.filter(c=>c.pass).length;report.total=report.checks.length;fs.writeFileSync(OUT+'/public-video-smoke.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,total:report.total}));if(report.passed!==report.total)process.exitCode=1;
})().catch(e=>{console.error(e.message);process.exitCode=1});
