// Author: Andrew Fisher. Native media lifecycle; visibility is deliberately simulated.
const fs=require('fs'),crypto=require('crypto');const {open}=require(require('path').join(process.env.GC500_TOOLCHAIN||require('path').resolve(__dirname,'../../toolchain'),'harness/open_page.js'));
if(!process.env.PAGE||!process.env.OUT)throw Error('Set PAGE and a private OUT directory');fs.mkdirSync(process.env.OUT,{recursive:true});const file=process.env.PAGE,checks=[];let s;const check=(name,pass)=>{checks.push({name,pass:!!pass});console.log((pass?'PASS ':'FAIL ')+name)};
const b='#pane-today .bhero .bplay',f='#pane-today .bhero';
async function play(p){await p.locator(b).click();await p.waitForFunction(()=>{let v=document.querySelector('#pane-today .bhero video');return v&&!v.paused&&v.currentTime>.4},null,{timeout:15000})}
async function quiet(p){return p.locator(f).evaluate(f=>{const v=f.querySelector('video');return v.paused&&!f.classList.contains('playing')&&f.querySelector('.bplay span').textContent==='Play with sound'})}
(async()=>{try{s=await open({pageFile:file,W:1440,H:1000});const p=s.page;await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:180000});await p.evaluate(()=>{localStorage.setItem('gc500.band','shown');go('today')});await p.locator(f).scrollIntoViewIfNeeded();await p.waitForTimeout(200);await play(p);check('Real clip starts before lifecycle exercise',true);
 await p.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,get:()=> 'hidden'});document.dispatchEvent(new Event('visibilitychange'))});check('Document-hidden event pauses actual media and restores still',await quiet(p));
 await p.evaluate(()=>{delete document.visibilityState;document.dispatchEvent(new Event('visibilitychange'))});await p.waitForTimeout(250);check('Visible again does not automatically resume media',await quiet(p));await play(p);check('Explicit replay after visibility restoration advances media',true);
 await p.evaluate(()=>{window.__oldClip=document.querySelector('#pane-today .bhero video');window.__oldPlay=document.querySelector('#pane-today .bhero .bplay');renderToday()});await p.locator(f).scrollIntoViewIfNeeded();await p.waitForTimeout(250);check('Today redraw disposes and pauses the replaced media',await p.evaluate(()=>window.__oldClip.paused&&window.__oldPlay.onclick===null));check('Replacement player waits for another explicit Play',await quiet(p));await play(p);
 await p.locator('#pane-today #bOpen').click();check('Folding stops current playback',await quiet(p));await p.locator('#pane-today #bOpen').click();await p.waitForTimeout(200);check('Unfolding does not autoplay',await quiet(p));await play(p);await p.locator(b).click();await p.locator(b).click();await p.waitForFunction(()=>{let v=document.querySelector('#pane-today .bhero video');return v&&!v.paused&&v.currentTime>.4},null,{timeout:15000});check('Immediate Stop followed by Play advances only the new request',true);
 check('No page errors',s.errors.length===0);check('No outgoing record writes',s.counts.blocked===0);
 }catch(e){checks.push({name:'Execution',pass:false,error:e.message})}finally{if(s)await s.browser.close();const result={author:'Andrew Fisher',candidate_sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),scope:'Actual native media; document-hidden event is simulated, not a physical-device claim',passed:checks.filter(c=>c.pass).length,total:checks.length,checks};fs.writeFileSync(process.env.OUT+'/video-lifecycle-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(result.passed!==result.total)process.exitCode=1}})();
