// Author: Andrew Fisher. Read-only real-media reproduction on original/candidate page.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {open}=require(require('path').join(process.env.GC500_TOOLCHAIN||require('path').resolve(__dirname,'../../toolchain'),'harness/open_page.js'));
if(!process.env.BASE||!process.env.PAGE||!process.env.OUT)throw Error('Set BASE, PAGE and a private OUT directory');
const ROOT=process.env.OUT,checks=[];fs.mkdirSync(ROOT,{recursive:true});let s;
const check=(name,pass,evidence)=>{checks.push({name,pass:!!pass,evidence});console.log((pass?'PASS ':'FAIL ')+name)};
async function stat(p){return p.locator('#pane-today .bhero[data-board="video"]').evaluate(f=>{let v=f.querySelector('video'),b=f.querySelector('.bplay');return{buttonDisabled:b.disabled,hasHandler:typeof b.onclick==='function',label:b.innerText,playing:f.classList.contains('playing'),paused:v.paused,time:v.currentTime,error:v.error&&{code:v.error.code,message:v.error.message},source:v.currentSrc,display:getComputedStyle(v).display,opacity:getComputedStyle(v).opacity,muted:v.muted,volume:v.volume,timer:!!BOARD_RUN.timer,seen:BOARD_RUN.seen,visibility:document.visibilityState,pane:document.querySelector('#pane-today').className,motion:motionOff(),readyState:v.readyState,networkState:v.networkState,sourceElements:[...v.querySelectorAll('source')].map(x=>({type:x.type,src:x.src})),status:f.querySelector('.bload')?.innerText}})};
async function ready(p){await p.waitForFunction(()=>typeof SYNC!=='undefined'&&SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:180000});await p.evaluate(()=>{localStorage.setItem('gc500.band','shown');go('today')});await p.locator('#pane-today .bhero[data-board="video"]').scrollIntoViewIfNeeded();await p.waitForTimeout(300);}
async function play(p,name){await p.locator('#pane-today .bhero .bplay').click();try{await p.waitForFunction(()=>{let v=document.querySelector('#pane-today .bhero video');return v&&!v.paused&&v.currentTime>.4},null,{timeout:15000});}catch(e){let evidence=await stat(p);fs.writeFileSync(ROOT+'/failure-player-state.json',JSON.stringify(evidence,null,2));await p.screenshot({path:ROOT+'/failure-player.png'});throw new Error(name+': '+e.message+' '+JSON.stringify(evidence));}let z=await stat(p);check(name,z.playing&&!z.paused&&z.time>.4&&z.display!=='none'&&!z.muted,z);return z;}
(async()=>{
 try{
 s=await open({pageFile:process.env.BASE,W:1440,H:1000});let p=s.page;await ready(p);const sourceUrls=await p.locator('#pane-today .bhero video source').evaluateAll(xs=>xs.map(x=>({type:x.type,url:x.src})));const webmUrl=sourceUrls.find(x=>x.type==='video/webm').url,mp4Url=sourceUrls.find(x=>x.type==='video/mp4').url;let normalOriginal=await stat(p);check('Original normal preference reproduces missing Play handler',!normalOriginal.hasHandler&&normalOriginal.paused,normalOriginal);
 await p.evaluate(()=>{localStorage.setItem('gc500.motion','off');motionApply()});let z=await stat(p);check('Original Tools Off hides the clip',z.display==='none',z);
 await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>{localStorage.setItem('gc500.motion','subtle');motionApply()});z=await stat(p);check('Original OS reduced hides the clip',z.display==='none',z);
 await p.route('**/v/Coates-GC500-2026/',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:fs.readFileSync(process.env.PAGE)}));
 await p.reload({waitUntil:'load',timeout:180000});await ready(p);check('Candidate reduced mount does not autoplay',(await stat(p)).paused);await play(p,'Candidate OS reduced allows explicit real playback');z=await stat(p);check('Reduced preference keeps decorative board timer off',!z.timer,z);
 await p.locator('#pane-today .bhero .bplay').click();z=await stat(p);check('Stop returns to still',z.paused&&!z.playing&&z.label==='Play with sound',z);
 await p.emulateMedia({reducedMotion:'no-preference'});await p.evaluate(()=>{localStorage.setItem('gc500.motion','off');motionApply()});await play(p,'Candidate Tools Off allows explicit playback');await p.locator('#pane-today .bhero .bplay').click();
 await p.evaluate(()=>{localStorage.setItem('gc500.motion','subtle');motionApply()});await play(p,'Candidate normal allows explicit playback');await p.screenshot({path:ROOT+'/candidate-desktop-playing.png'});
 await p.evaluate(()=>go('register'));await p.waitForTimeout(250);check('Leaving Today stops media resources',await p.evaluate(()=>!BOARD_RUN.stopMedia&&!BOARD_RUN.disposeMedia));await p.evaluate(()=>go('today'));await p.locator('#pane-today .bhero[data-board="video"]').scrollIntoViewIfNeeded();await p.waitForTimeout(250);check('Returning Today does not autoplay',(await stat(p)).paused);
 await p.route(webmUrl,r=>r.fulfill({status:404,body:''}));await p.evaluate(()=>renderToday());await p.locator('#pane-today .bhero[data-board="video"]').scrollIntoViewIfNeeded();await p.waitForTimeout(250);await play(p,'Failed WebM falls back to MP4 through native sources');z=await stat(p);check('Fallback current source is original MP4',z.source.endsWith('.mp4'),z);await p.locator('#pane-today .bhero .bplay').click();
 await p.setViewportSize({width:390,height:844});await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>renderToday());await p.locator('#pane-today .bhero[data-board="video"]').scrollIntoViewIfNeeded();await p.waitForTimeout(250);await play(p,'Phone-width reduced preference plays MP4');await p.screenshot({path:ROOT+'/candidate-phone-playing.png'});check('Phone-width page has no horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#pane-today .bhero .bplay').click();
 await p.route(mp4Url,r=>r.fulfill({status:404,body:''}));await p.evaluate(()=>renderToday());await p.locator('#pane-today .bhero[data-board="video"]').scrollIntoViewIfNeeded();await p.waitForTimeout(250);await p.locator('#pane-today .bhero .bplay').click();await p.waitForFunction(()=>document.querySelector('#pane-today .bhero .bplay span')?.textContent==='Retry clip',null,{timeout:23000});z=await stat(p);check('All unavailable sources recover to still and Retry without a stuck loader',z.paused&&!z.playing&&z.label==='Retry clip',z);
 check('No page errors',s.errors.length===0,s.errors);check('No outgoing record writes',s.counts.blocked===0,s.counts);
 }catch(e){checks.push({name:'Browser execution',pass:false,error:String(e.message)});console.error(e.message)}finally{if(s)await s.browser.close();let report={author:'Andrew Fisher',scope:'Read-only original/candidate native browser and real media, Chromium desktop plus phone-width emulation',at:new Date().toISOString(),candidate:crypto.createHash('sha256').update(fs.readFileSync(process.env.PAGE)).digest('hex'),passed:checks.filter(x=>x.pass).length,total:checks.length,checks};fs.writeFileSync(process.env.REPORT||ROOT+'/browser_video_checks.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,total:report.total}));if(report.passed!==report.total)process.exitCode=1;}
})();
