/* Author: Andrew Fisher. Focused native navigation probes. Every service mutation is blocked. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const assert=require('node:assert/strict'),Module=require('module');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));
const original=fs.readFileSync(hp,'utf8');assert.match(original,/const okPost = [^;]+;/);assert(original.includes('counts.blocked++;'));
hm._compile(original.replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++; (counts.blockedPaths ||= []).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const {open}=hm.exports;
async function guard(p){await p.evaluate(()=>{if(Array.isArray(SYNC.unsub)){SYNC.unsub.forEach(fn=>fn());SYNC.unsub=[];}window.__popup945Writes=[];window.bump=()=>{__popup945Writes.push('bump');throw Error('Popup navigation must not save');};if(SYNC.db&&typeof SYNC.db.doc==='function'){const native=SYNC.db.doc.bind(SYNC.db);SYNC.db.doc=(...args)=>{const doc=native(...args);for(const m of ['set','update','delete'])if(typeof doc[m]==='function')doc[m]=()=>{__popup945Writes.push(m);throw Error('Popup navigation must not write');};return doc;};}});}
async function assertNoWrites(p,s){assert.deepEqual(await p.evaluate(()=>__popup945Writes),[]);assert((s.counts.blockedPaths||[]).every(x=>x.method==='POST'&&x.origin==='https://tile.googleapis.com'&&x.path==='/v1/createSession'));}

const file=process.env.PAGE||'/workspace/private-popup945/candidate.html',out=process.env.POPUP_OUT||'/workspace/private-popup945/evidence';fs.mkdirSync(out,{recursive:true});const result={sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),checks:[],sessions:[]};
function note(name,pass,data){result.checks.push({name,pass,...(data?{data}:{})});console.log((pass?'PASS ':'FAIL ')+name);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));}
async function show(p,kind){await p.evaluate(kind=>{if(kind==='choice')pickMarker([{key:'WC20',label:'WC20'},{key:'WC09',label:'WC09'}],100,100);else if(kind==='information')layerCallout({label:'Navigation test',note:'Read-only fixture',src:'Test fixture'});else emptyCallout(DATA.sheets.find(x=>x.master)||DATA.sheets[0],['Unassigned test']);},kind);await p.waitForTimeout(30);}
async function stateOf(p){return p.evaluate(()=>({popups:document.querySelectorAll('.mkpick').length,listeners:__popupListeners.size,tab:state.tab,hash:location.hash}));}
(async()=>{for(const width of [390,1440]){let s;try{s=await open({pageFile:file,hash:'#today',W:width,H:900,mobile:width===390});const p=s.page;await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live',null,{timeout:120000});await guard(p);const before=await p.evaluate(()=>JSON.stringify(S));await p.evaluate(()=>{window.__popupListeners=new Set();const add=document.addEventListener.bind(document),remove=document.removeEventListener.bind(document);document.addEventListener=function(type,fn,...rest){if(type==='keydown'&&String(fn).includes("e.key === 'Escape'")&&String(fn).includes('close();'))__popupListeners.add(fn);return add(type,fn,...rest)};document.removeEventListener=function(type,fn,...rest){if(type==='keydown')__popupListeners.delete(fn);return remove(type,fn,...rest)};});
 await p.evaluate(()=>go('map'));await p.waitForTimeout(100);
 for(const kind of ['information','choice','empty']){await show(p,kind);let x=await stateOf(p);note(width+' '+kind+' opens one native popup and listener',x.popups===1&&x.listeners===1,x);await p.locator('.mkpick button.close').click();x=await stateOf(p);note(width+' '+kind+' Close retires popup and listener',x.popups===0&&x.listeners===0,x);await show(p,kind);await p.keyboard.press('Escape');x=await stateOf(p);note(width+' '+kind+' Escape retires popup and listener',x.popups===0&&x.listeners===0&&x.tab==='map',x);}
 for(let i=0;i<24;i++)await show(p,['information','choice','empty'][i%3]);let x=await stateOf(p);note(width+' repeated replacements keep one popup and Escape listener',x.popups===1&&x.listeners===1,x);await p.locator('.mkpick button.close').click();x=await stateOf(p);note(width+' replacements leave no Escape listener after Close',x.popups===0&&x.listeners===0,x);
 await show(p,'choice');await p.locator('.mkpick [data-pick="WC20"]').click();await p.waitForTimeout(500);x=await stateOf(p);note(width+' native choice still opens selected reference',x.popups===0&&x.listeners===0&&await p.locator('#drawer').evaluate(n=>n.classList.contains('on')&&n.textContent.includes('WC20')),x);await p.locator('#dclose').click();
 await p.evaluate(()=>go('today'));await p.waitForTimeout(100);await p.evaluate(()=>go('map'));await p.waitForTimeout(100);await show(p,'choice');await p.locator('#navBack').click();await p.waitForFunction(()=>state.tab==='today');x=await stateOf(p);note(width+' visible Back clears map popup and listener',x.popups===0&&x.listeners===0,x);
 await p.evaluate(()=>go('map'));await p.waitForTimeout(100);await show(p,'information');await p.goBack();await p.waitForFunction(()=>state.tab==='today');x=await stateOf(p);note(width+' browser Back clears map popup and listener',x.popups===0&&x.listeners===0,x);
 await p.evaluate(()=>go('map'));await show(p,'empty');await p.evaluate(()=>go('today'));x=await stateOf(p);note(width+' tab departure clears map popup and listener',x.popups===0&&x.listeners===0&&x.tab==='today',x);if(width===390)await p.screenshot({path:path.join(out,'today-after-popup-390.png')});
 note(width+' native record unchanged',await p.evaluate(v=>JSON.stringify(S)===v,before));await assertNoWrites(p,s);note(width+' zero runtime errors',s.errors.length===0);result.sessions.push({width,errors:s.errors,requests:s.counts});
 }catch(e){result.error=e.stack;console.error(e.stack);}finally{if(s)await s.browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));}if(result.error)break;}
 console.log(result.checks.filter(c=>c.pass).length+'/'+result.checks.length+' checks passed');if(result.error||result.checks.some(c=>!c.pass))process.exitCode=1;})();
