const {open} = require('/home/user/fish/03_GC500_Delivery_Control/toolchain/harness/open_page'); const fs = require('fs');
(async () => { const s = await open({pageFile: process.env.PAGE, W: 1440, H: 900}); const p = s.page;
  await p.waitForFunction(() => typeof go === 'function' && typeof TABS !== 'undefined', null, {timeout: 150000}); await p.waitForTimeout(3000);
  await p.evaluate(() => go('costs')); await p.waitForFunction(() => { try { return moneySummary().charge.labour >= 0; } catch (e) { return false; } }, null, {timeout: 30000}); await p.waitForTimeout(1000);
  const r = await p.evaluate(() => { const safe = o => JSON.parse(JSON.stringify(o, (k, v) => v instanceof Map ? Object.fromEntries(v) : v)); const out = {};
    const tryf = (name, f) => { try { out[name] = safe(f()); } catch (e) { out[name] = 'ERR ' + e.message; } };
    tryf('fencePaidSplit', () => fencePaidSplit());
    tryf('labourPlan', () => { const L = labourPlan(); return {all: L.all, byLine: L.byLine, byBranch: L.byBranch, slots: L.slots.length, states: L.slots.reduce((m, s) => (m[s.state] = (m[s.state] || 0) + 1, m), {})}; });
    tryf('acc761Labour', () => acc761Labour());
    tryf('fenceDerived', () => { const f = fenceDerived(); return Object.fromEntries(Object.entries(f).filter(([k, v]) => typeof v !== 'object' || Array.isArray(v) && v.length < 10)); });
    tryf('costCategories', () => costCategories());
    tryf('costTotals', () => costTotals(allCosts()));
    tryf('ourCosts', () => ourCosts().map(c => ({kind: c.kind, amount: c.amount, usable: c.usable, cat: c.category, desc: String(c.description || '').slice(0, 60), ref: c.ref, date: c.date, where: c._where})));
    tryf('moneyStreams', () => moneyStreams());
    tryf('names', () => Object.getOwnPropertyNames(window).filter(n => /staff|roster|runsheet|wage|fin745|acc76|cj76|pl7|rh76|labour|Labour/.test(n) && typeof window[n] === 'function'));
    tryf('eventStaffing', () => { const f = Object.getOwnPropertyNames(window).find(n => /eventStaffing\d*$/.test(n) || /staffing833Model|eventStaffingModel/.test(n)); return f ? {fn: f, v: window[f]()} : null; });
    tryf('rosterCosts', () => { const f = Object.getOwnPropertyNames(window).find(n => /roster\w*(Cost|Total|Model)\w*/.test(n) && typeof window[n] === 'function'); return f ? {fn: f, v: window[f]()} : Object.getOwnPropertyNames(window).filter(n => /roster/i.test(n)); });
    tryf('fin745Rows', () => { const F = fin745Summary(null); return {n: F.rows.length, sample: F.rows.slice(0, 3), unpricedSample: F.rows.filter(r => r.unpriced || r.rate == null).slice(0, 3)}; });
    tryf('labour858Missing', () => labourRevenue858().missing);
    return out; });
  fs.writeFileSync(process.env.OUT + '/models2.json', JSON.stringify(r, null, 1)); console.log(JSON.stringify(r).slice(0, 6000)); await s.browser.close(); })().catch(e => { console.error('FAIL', e.stack); process.exit(1); });
