// Author: Andrew Fisher. Native media/scroll event timing probe, GET only.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {installWriteGuard,ready840,nativeSnapshot}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const {open}=require('../toolchain/harness/open_page.js');
const {PAGE,OUT,CANDIDATE_SHA}=process.env,sha=b=>crypto.createHash('sha256').update(b).digest('hex');if(!PAGE||!OUT||sha(fs.readFileSync(PAGE))!==CANDIDATE_SHA)throw Error('Frozen candidate/private OUT required');
fs.mkdirSync(OUT,{recursive:true});const report={author:'Andrew Fisher',candidate:CANDIDATE_SHA,checks:[],cycles:[]},check=(name,pass,evidence)=>{report.checks.push({name,pass:!!pass,evidence});console.log((pass?'PASS ':'FAIL ')+name);};const guard=installWriteGuard();let session;
(async()=>{try{session=await open({pageFile:PAGE,hash:'#today',W:3840,H:2160,dpr:1});const p=session.page;await ready840(p);await p.waitForFunction(()=>TodayWork840.report().typesMerged);const before=await nativeSnapshot(p);
 await p.evaluate(()=>{
  window.__motionEvents843=[];
  window.__motionSample843=stage=>{const b=document.querySelector('#gc500-work-board840'),main=document.querySelector('main'),m=main.getBoundingClientRect(),nav=b.querySelector('.tw840-nav').getBoundingClientRect(),top=Math.max(0,m.top,nav.bottom>m.top&&nav.top<m.bottom?nav.bottom:0),rect=n=>{const r=n.getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,height:r.height};},visible=n=>{const r=rect(n);return r.bottom>top&&r.top<Math.min(innerHeight,m.bottom)&&r.right>m.left&&r.left<m.right;};
   const report=TodayWork840.report(),bars=[...b.querySelectorAll('.tw841-motion-track,[data-tw843-type-id] .tw843-leds')].map(n=>({id:n.closest('[data-tw843-type-id]')?'type:'+n.closest('[data-tw843-type-id]').dataset.tw843TypeId:'parent:'+n.closest('[data-tw840-area]').dataset.tw840Area,visible:visible(n),rect:rect(n)})),animations=document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.target instanceof Element&&a.effect.target.closest('#gc500-work-board840')&&a.animationName!=='gc-lit').map(a=>({name:a.animationName,id:a.effect.target.closest('[data-tw843-type-id]')?'type:'+a.effect.target.closest('[data-tw843-type-id]').dataset.tw843TypeId:'parent:'+a.effect.target.closest('[data-tw840-area]')?.dataset.tw840Area})),target=report.runningInstrument?(report.runningInstrument.kind==='type'?'type:':'parent:')+report.runningInstrument.id:null;
   return {stage,time:performance.now(),main:main.scrollTop,scrollBehavior:getComputedStyle(main).scrollBehavior,mainClip:rect(main),nav:rect(b.querySelector('.tw840-nav')),report,bars,animations,target,active:!!target&&bars.some(b=>b.id===target&&b.visible)&&animations.length>0&&animations.every(a=>a.id===target),stopped:!report.running&&!report.runningInstrument&&!animations.length};};
  const event=(kind,detail={})=>{__motionEvents843.push({kind,detail,state:__motionSample843('event '+kind)});requestAnimationFrame(()=>__motionEvents843.push({kind:kind+' frame',detail,state:__motionSample843('event frame '+kind)}));};
  window.addEventListener('scroll',e=>event('scroll',{target:e.target.tagName||'window'}),{capture:true,passive:true});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>event('media',{matches:e.matches}));document.querySelector('#gc500-work-dialog840').addEventListener('close',()=>event('close'));
 });
 const id=await p.evaluate(()=>todayTypeMetrics843(TodayWork840.report().asOf).instruments.find(t=>t.cardId==='buildings'&&t.kind==='asset-type').id);
 const reveal=async()=>{const setup=await p.evaluate(id=>{const m=document.querySelector('main'),bar=[...document.querySelectorAll('[data-tw843-type-id]')].find(n=>n.dataset.tw843TypeId===id).querySelector('.tw843-leds'),nav=document.querySelector('.tw840-nav');const before=__motionSample843('before requested scroll'),want=m.scrollTop+bar.getBoundingClientRect().top-m.getBoundingClientRect().top-nav.getBoundingClientRect().height-30;__motionEvents843.length=0;m.scrollTop=want;return {before,want,immediate:__motionSample843('immediate requested scroll')};},id);await p.waitForTimeout(200);const early=await p.evaluate(()=>__motionSample843('200ms'));await p.waitForFunction(()=>__motionSample843('condition').active,null,{timeout:2000}).catch(()=>{});await p.waitForTimeout(100);const settled=await p.evaluate(()=>__motionSample843('settled')),events=await p.evaluate(()=>__motionEvents843);return {setup,early,settled,events};};
 for(let i=0;i<5;i++){
  await p.locator('[data-tw840-jump=buildings]').click();await p.waitForTimeout(250);const initial=await reveal();check('cycle '+i+' settled child motion has one visible target',initial.settled.active&&initial.settled.report.runningInstrument?.kind==='type',initial);
  await p.evaluate(()=>{__motionEvents843.length=0;});await p.emulateMedia({reducedMotion:'reduce'});const immediate=await p.evaluate(()=>__motionSample843('immediate media'));await p.waitForTimeout(100);const early=await p.evaluate(()=>__motionSample843('100ms media'));await p.waitForFunction(()=>__motionEvents843.some(e=>e.kind==='media'&&e.detail.matches===true),null,{timeout:2000}).catch(()=>{});await p.waitForFunction(()=>__motionSample843('media condition').stopped,null,{timeout:2000}).catch(()=>{});await p.waitForTimeout(100);const reduced=await p.evaluate(()=>({state:__motionSample843('settled media'),events:__motionEvents843}));check('cycle '+i+' reduced CSS blocks motion immediately',immediate.animations.length===0,{immediate,early});check('cycle '+i+' native media event converges to a stopped controller',reduced.state.stopped&&reduced.events.some(e=>e.kind==='media'&&e.detail.matches===true),reduced);
  await p.emulateMedia({reducedMotion:'no-preference'});await p.waitForFunction(()=>__motionSample843('normal condition').active,null,{timeout:2000});
  await p.locator('[data-tw843-type-detail='+JSON.stringify(id)+'][data-tw843-type-mode=total]').click();await p.waitForTimeout(100);await p.evaluate(()=>{window.__closeDone843=false;document.querySelector('#gc500-work-dialog840').addEventListener('close',()=>{window.__closeDone843=true;},{once:true});});await p.keyboard.press('Escape');await p.waitForFunction(()=>__closeDone843);const afterClose=await reveal();check('cycle '+i+' post-dialog native scroll converges to one visible target',afterClose.settled.active&&afterClose.settled.report.runningInstrument?.kind==='type'&&afterClose.events.some(e=>e.kind==='scroll')||Math.abs(afterClose.setup.before.main-afterClose.setup.want)<=1&&afterClose.settled.active,afterClose);
  const stableBefore=await p.evaluate(()=>__motionSample843('before layout-only refresh'));await p.evaluate(()=>renderToday());await p.waitForTimeout(600);const stableAfter=await p.evaluate(()=>__motionSample843('after layout-only refresh'));check('cycle '+i+' settled redraw cannot leave animation on an offscreen target',!stableAfter.animations.length||stableAfter.active,{before:stableBefore,after:stableAfter});
  report.cycles.push({i,initial,immediate,early,reduced,afterClose,stableBefore,stableAfter});
 }
 check('Native records unchanged',JSON.stringify(before.collections)===JSON.stringify((await nativeSnapshot(p)).collections));check('No runtime errors',session.errors.length===0,session.errors);check('Frozen candidate unchanged',sha(fs.readFileSync(PAGE))===CANDIDATE_SHA);
 }catch(e){check('Focused motion timing execution',false,e.stack);}finally{if(session)await session.browser.close();await guard.closeAll();report.guard=guard;check('Every non-GET blocked and no operational write attempted',guard.nonGetSeen.length===guard.blocked.length&&!guard.nonGetSeen.some(r=>r.operational),guard.nonGetSeen);const unexpected=guard.consoleErrors.filter(e=>!(/Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(e.text)&&guard.blocked.some(b=>!b.operational&&b.url===e.url)));check('No unexpected console errors',!unexpected.length,unexpected);report.passed=report.checks.filter(c=>c.pass).length;report.total=report.checks.length;fs.writeFileSync(path.join(OUT,'motion-timing843.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,total:report.total,candidate:CANDIDATE_SHA}));if(report.passed!==report.total)process.exitCode=1;}})().catch(e=>{console.error(e.message);process.exitCode=2;});
