// Author: Andrew Fisher. Existing movement identity and fail-closed assessment adapters.
const E=esc924;
const link=(p,label)=>'<a href="'+GUIDE_URL+'#page='+p+'" target="_blank" rel="noopener">'+E(label||'Guide p'+p)+'</a>';
function links931(pages){const values=[...new Set(pages)].filter(Number.isInteger).sort((a,b)=>a-b),runs=[];for(const p of values){const last=runs[runs.length-1];if(last&&last[1]===p-1)last[1]=p;else runs.push([p,p]);}return runs.map(([a,b],i)=>link(a,(i?'':'Guide ')+(a===b?'p'+a:'pp'+a+'–'+b))).join(' · ');}
function savedUnit931(p){const d=p.record;if(!d)return '';const v=d.actual||{},values=[v.model,...facts931(v),v.configuration,v.source,d.methodEvidence].filter(has),m=METHODS.find(m=>m.id===d.methodId);if(m)values.push(m.name);return '<details class="r931-history"><summary>Saved transport evidence'+(!p.recordCurrent?' · previous unit details':'')+'</summary>'+values.map(t=>'<p>'+E(t)+'</p>').join('')+(d.by?'<p class="hint">'+E(d.by)+(d.at?' · '+E(d.at):'')+'</p>':'')+'</details>';}
function productHtml931(p,print){const us=p.units||[],ids=us.map(u=>u.assetNo||u.label).filter(Boolean),owner=p.owner||(p.unit&&p.unit.owner),sub=owner&&owner!=='coates'&&owner!=='unknown',supplier={'event-portables':'Event Portables','prem-air-hire':'PremAir Hire'}[owner]||txt(owner).replace(/^other:/,'');return '<section class="r931-product'+(print?' r924-print-unit':'')+'" data-r931-product="'+E(p.item)+'"><b>'+E(p.ref+' · '+(p.qty?p.qty+' × ':'')+p.item)+'</b>'+(sub?'<p class="hint"><b>SUB-HIRED — '+E(supplier)+'</b></p>':'')+(ids.length?'<p class="hint">'+E(ids.join(' · '))+'</p>':'')+p.facts.map(f=>'<p class="r931-fact"><span>'+E(f.label)+'</span><strong>'+E(f.values.join(' · '))+'</strong>'+(f.pages?' '+links931(f.pages):f.source?' <small>'+E(f.source)+'</small>':'')+'</p>').join('')+'<p><b>Loading</b> · '+E(p.guidance.text)+'</p>'+(p.guidance.scope?'<p class="hint">'+E(p.guidance.scope)+'</p>':'')+'<p class="hint">'+links931(p.guidance.pages)+'</p>'+savedUnit931(p)+'</section>';}
const note931='Guide model figures are reference values; the complete method and carrier requirements apply.';
function panel931(products,attrs){if(!products.length)return '';return '<details open class="loading872 r924 r931" '+(attrs||'')+'><summary>Loading information</summary><div class="r924-body">'+products.map(p=>productHtml931(p,false)).join('')+'<p class="hint">'+E(note931)+'</p></div></details>';}
function editor(a){return a&&a.key?panel931(referenceProducts931(a),'data-r931-ref="'+E(a.key)+'"'):'';}
function savedPlan931(day,id){const p=planFor(day,id);if(!p)return '';const v=p.vehicle||{},fields=[['id','Truck'],['source','Source'],['deckLengthMm','Deck length (mm)'],['deckWidthMm','Deck width (mm)'],['payloadKg','Payload allowance (kg)'],['extraMassKg','Additional support/restraint mass (kg)'],['deckHeightMm','Deck height (mm)'],['heightLimitMm','Height limit (mm)'],['axleEvidence','Axle assessment'],['anchorEvidence','Anchor assessment'],['restraintEvidence','Restraint assessment']];return '<details class="r931-history"><summary>Saved transport arrangement</summary>'+fields.filter(([k])=>v[k]!==null&&v[k]!==undefined&&txt(v[k])!=='').map(([k,label])=>'<p><b>'+label+'</b> · '+E(v[k])+'</p>').join('')+(p.by?'<p class="hint">'+E(p.by)+(p.at?' · '+E(p.at):'')+'</p>':'')+'<p class="hint">Recorded arrangement retained as evidence; this display does not approve a load.</p></details>';}
function loadEditor(d,g){if(!g||!g.rows)return '';const id=g._restraintId924||ldId(d,g);return panel931(loadProducts931(g),'data-r931-load="'+E(id)+'"')+savedPlan931(d.iso,id);}
function summary(a){return referenceProducts931(a).map(p=>p.ref+' · '+p.item+': '+p.facts.map(f=>f.label+' — '+f.values.join(' · ')).concat(p.guidance.text).join(' · ')).join(' | ');}
function printPages(d,g,n){const products=loadProducts931(g);if(!products.length)return '';const pages=[];for(let i=0;i<products.length;i+=3)pages.push(products.slice(i,i+3));return pages.map((rows,i)=>'<div class="dp-page dp-drv r924-paper r931-paper"><header class="dp-hd"><div class="dp-hd-l"><b>Coates</b><span>Industrial Solutions</span></div><div class="dp-hd-m"><span>Load '+E(n)+' · '+E(d.iso)+'</span><h1>Loading information</h1></div><div class="dp-hd-r">'+(i+1)+' of '+pages.length+'</div></header><section class="dp-sec">'+rows.map(p=>productHtml931(p,true)).join('')+'</section><div class="dp-ft">Author: Andrew Fisher · '+E(note931)+'</div></div>').join('');}
function pairId(a,b){return 'pair924/'+JSON.stringify([a.id,b.id].sort());}
function share(d,a,b){return {fits:null,why:'Product loading information is provided for planning; the carrier determines the complete load and restraint arrangement.',planId:pairId(a,b)};}
const API={guide:GUIDE,methods:METHODS,ownerKey,unitId,keyHash,unitDocKey,getDoc,guideCandidates,methodCandidates,unitsFor,actualState,fingerprintUnit,planKey,planFor,scopeFingerprint,editablePlan,editableUnit,methodIssues,assess,family931,nominal931,contractRows931,source931,guideRows931,guideSummary931,guidance931,info931,links931,products931,referenceProducts931,loadProducts931,productHtml931,editor,loadEditor,loadStates,loadAssessment,summary,findLoad,demobId,demobGroup,share,printPages};
root.Restraint924=API;root.Loading931=API;root.getTransportUnits924=unitsFor;root.transportUnitId924=unitId;
if(typeof module!=='undefined'&&module.exports)module.exports=API;
if(typeof document==='undefined')return;
const beforeUnit=unitBlockInline;unitBlockInline=function(a){return beforeUnit.apply(this,arguments)+editor(a);};
const beforeActions=timeline841Actions;timeline841Actions=function(d,g,n){return beforeActions.apply(this,arguments)+(g.kind==='deliveries'||g.kind==='removals'?loadEditor(d,g):'');};
const beforeFlow=flow891Build;flow891Build=function(d){const m=beforeFlow.apply(this,arguments);m.share=m.share.map(s=>Object.assign({},s,share(d,s.a,s.b)));return m;};
const beforeFlowCard=flow891Card;flow891Card=function(d){return beforeFlowCard.apply(this,arguments).replace('weights and dimensions are not on the page, so nothing is suggested','product loading information is shown with each load; sharing remains a carrier planning decision');};
// Existing driver/pre-departure and unloading workflows remain native. No new data-entry checks or warnings are added.
const beforeTrucks=trucksHtml816;trucksHtml816=function(Dy,T){return beforeTrucks.apply(this,arguments)+(T.length?T.map(L=>'<details class="loading872"><summary>Pick-up load '+L.n+' · loading information</summary>'+loadEditor({iso:Dy.iso||DM816.sel},demobGroup(L))+'</details>').join(''):'');};
const beforePage=dpPage;dpPage=function(d,g,doc,i,n){return beforePage.apply(this,arguments)+(doc==='drv'?printPages(d,g,i):'');};
const beforeDemobSheet=sheet816;sheet816=function(iso,L){return beforeDemobSheet.apply(this,arguments)+printPages({iso},demobGroup(L),L.n);};
const beforeDrop=dropPage;dropPage=function(a,events){const info=products931(a,dpItems({a,events:events||[]}),sources931(),{load:true}).map(p=>productHtml931(p,true)).join('');return beforeDrop.apply(this,arguments).replace('<div class="rs-go">',info?'<div class="loading872-sheet r931"><b>Loading information</b>'+info+'</div><div class="rs-go">':'<div class="rs-go">');};
function catalogueHtml(q){const query=txt(q).toLowerCase(),rows=GUIDE.filter(g=>!query||((g.make?g.make+' ':'')+g.description+' '+g.page).toLowerCase().includes(query));return '<p>'+rows.length+' published model references.</p>'+rows.slice(0,40).map(g=>'<p><b>'+E((g.make?g.make+' · ':'')+g.description)+'</b><br>'+E(facts931(g).join(' · '))+' · '+link(g.page)+'</p>').join('')+(rows.length>40?'<p>Showing the first 40 references.</p>':'');}
const beforeRenderDocs=renderDocs;renderDocs=function(){const r=beforeRenderDocs.apply(this,arguments),pane=document.getElementById('pane-docs');if(pane&&!pane.querySelector('#r924-catalogue'))pane.insertAdjacentHTML('beforeend','<details id="r924-catalogue" class="loading872 r924"><summary>Load restraint guide · full model catalogue</summary><div class="r924-body"><label class="f"><span>Search the reference catalogue</span><input type="search" data-ro data-r924-catalogue placeholder="Make or equipment type"></label><div data-r924-catalogue-results>'+catalogueHtml('')+'</div></div></details>');return r;};
document.addEventListener('input',e=>{if(e.target.matches('[data-r924-catalogue]'))e.target.closest('#r924-catalogue').querySelector('[data-r924-catalogue-results]').innerHTML=catalogueHtml(e.target.value);});
const css=document.createElement('style');css.id='loading931-style';css.textContent=`
.r924{width:100%;min-width:0;margin:8px 0}.r924 .r924-body{padding:10px;min-width:0}.r924 p{margin:6px 0;overflow-wrap:anywhere}.r924 summary{cursor:pointer;line-height:1.5}.r931-product{padding:8px 0;border-bottom:1px solid var(--hair,#d7dbde)}.r931-product:last-of-type{border-bottom:0}.r931-fact span{font-size:.86em;color:inherit;opacity:.85}.r931-fact strong{display:block}.r931-fact small{display:block;color:inherit;opacity:.85}.r931-history{margin:8px 0;font-size:.9em}.r924 .f{display:grid;gap:4px;min-width:0}.r924 input[type=search]{width:100%;min-width:0;min-height:40px;font:inherit;padding:8px 10px;box-sizing:border-box}.r931-paper{color:#15181a;background:#fff}.r931-paper .r931-product{break-inside:avoid;padding:8px 0}.r931-paper p{font-size:10px;line-height:1.3;margin:5px 0;overflow-wrap:anywhere}.r931-paper .r931-fact strong{display:inline;margin-left:5px}.r931-paper .hint{color:#52605b}.r931-paper .dp-sec{overflow:visible}.r931-paper .dp-ft{margin-top:auto}.r931-paper a{color:#174c42;text-decoration:underline}
@media(max-width:500px){.r924 .r924-body{padding:8px}.r924 input[type=search]{font-size:16px}}
`;document.head.appendChild(css);
function demobId(L){return 'demob924/'+JSON.stringify([L.kind,L.group||'',L.co||'',(L.stops||[]).map(s=>[s.r.key,s.part||'',!!s.tankOnly,(s.parts||[]).map(p=>[p.type,p.n,!!p.unknown,!!p.tank]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))]);}
function demobGroup(L){const refs=[...new Set((L.stops||[]).map(s=>s.r.key))];return {kind:'removals',_restraintId924:demobId(L),_restraintDemob924:L,rows:refs.map(key=>({a:assetOf(key)})).filter(r=>r.a)};}
function loadStates(g){const out=[],seen=new Set(),gaps=[];for(const r of g.rows||[]){let us=unitsFor(r.a);if(g._restraintDemob924){const L=g._restraintDemob924,parts=L.stops.filter(s=>s.r.key===r.a.key).flatMap(s=>s.parts||[]);if(L.kind==='toilets')us=us.filter(u=>u.owner==='coates');if(L.kind==='supplier')us=us.filter(u=>u.owner!=='coates'&&u.owner!=='unknown');const count=parts.reduce((n,p)=>n+(Number.isInteger(p.n)?p.n:0),0);if(parts.some(p=>p.unknown||!Number.isInteger(p.n)||p.n<0)||count!==us.length)gaps.push(r.a.key+': this pick-up portion needs the exact individual units allocated before a fit can be recorded');}if(Array.isArray(r.a._bookingNumbers801)){const set=new Set(asset873Numbers(r.a).map(String));us=us.filter(u=>u.assetNo&&set.has(u.assetNo));}if(!us.length)gaps.push(r.a.key+': identify individual units');for(const u of us){if(seen.has(u.id)){gaps.push('Repeated unit '+u.label);continue;}seen.add(u.id);out.push(actualState(u));}}return {states:out,gaps};}
function loadAssessment(day,id,g){const x=loadStates(g),p=planFor(day,id),a=assess(x.states,p);const gaps=x.gaps.slice();if(!p||p.completeCargo!==true)gaps.push('Confirm that every item, attachment and loose load is included');return Object.assign(a,{fits:false,geometryFits:a.geometryFits&&!gaps.length,why:[a.why,...gaps].filter(Boolean).join(' · '),states:x.states,plan:p,gaps});}
function findLoad(day,id){if(id.startsWith('demob924/')){const lists=[trucks816(day,'all')];if(typeof DM816!=='undefined'&&DM816.branch&&DM816.branch!=='all')lists.push(trucks816(day,DM816.branch));for(const ls of lists){const same=ls.filter(L=>demobId(L)===id);if(same.length>1)return null;if(same.length===1)return demobGroup(same[0]);}return null;}const d=programmeDays().find(x=>x.iso===day);if(!d)return null;const ls=dpLoads(d);if(id.startsWith('pair924/')){let ids;try{ids=JSON.parse(id.slice(8));}catch(e){return null;}if(!Array.isArray(ids)||ids.length!==2||ids[0]===ids[1])return null;const parts=ids.map(k=>ls.find(g=>ldId(d,g)===k));if(parts.some(x=>!x))return null;return {rows:parts.flatMap(g=>g.rows),_restraintId924:id,kind:'deliveries'};}return ls.find(g=>ldId(d,g)===id)||null;}
})(typeof window!=='undefined'?window:globalThis);
