// Local stand-in for the live /w/<token>/ machine route: same MIME table, same extension allowlist, same page CSP,
// no Content-Encoding (the live route never compresses machine files). Usage: node serve.js <root> <port>
const http=require('http'),fs=require('fs'),path=require('path');
const root=path.resolve(process.argv[2]||'.'),port=+(process.argv[3]||8770);
const TYPES={html:'text/html; charset=utf-8',css:'text/css; charset=utf-8',js:'text/javascript; charset=utf-8',mjs:'text/javascript; charset=utf-8',json:'application/json; charset=utf-8',csv:'text/csv; charset=utf-8',md:'text/plain; charset=utf-8',txt:'text/plain; charset=utf-8',glb:'model/gltf-binary',gltf:'model/gltf+json',bin:'application/octet-stream',hdr:'image/vnd.radiance',ktx2:'image/ktx2',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',svg:'image/svg+xml',ico:'image/x-icon',mp3:'audio/mpeg',ogg:'audio/ogg',wav:'audio/wav',m4a:'audio/mp4',woff2:'font/woff2',woff:'font/woff',wasm:'application/wasm'};
const CSP="default-src 'self'; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://api.mapbox.com https://*.googleapis.com https://cdn.jsdelivr.net; media-src 'self' blob:; connect-src 'self' blob: data: https://api.mapbox.com https://events.mapbox.com https://tile.googleapis.com https://*.googleapis.com https://cdn.jsdelivr.net; worker-src 'self' blob:; frame-ancestors 'self'; base-uri 'none'; form-action 'none'";
http.createServer((req,res)=>{let rel=decodeURIComponent(req.url.split('?')[0]).replace(/^\/+/,'')||'index.html';const ext=(rel.match(/\.([a-z0-9]+)$/i)||[])[1];
 const fp=path.join(root,rel);if(!fp.startsWith(root)||!ext||!TYPES[ext.toLowerCase()]||rel.startsWith('_qa/')||!fs.existsSync(fp)||!fs.statSync(fp).isFile()){res.writeHead(404,{'Content-Type':'application/json'});return res.end('{"error":"no such machine file"}');}
 const h={'Content-Type':TYPES[ext.toLowerCase()],'Content-Length':fs.statSync(fp).size,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};if(ext==='html')h['Content-Security-Policy']=CSP;
 res.writeHead(200,h);fs.createReadStream(fp).pipe(res);}).listen(port,'127.0.0.1',()=>console.log('serving',root,'on',port));
