/* Author: Andrew Fisher. Confirmed 14 Oct arrival instructions; native records remain authoritative. */
const ARRIVAL943={day:'2026-10-14',refs:['P25','P66','P65','P67'],sides:['passenger','driver','passenger','driver'],png:'__ARRIVAL943_PNG__',png2:'__ARRIVAL943_PNG2__',pdf:'__ARRIVAL943_PDF__'};
function arrival943Model(){return holdAssets(arrival943Build);}
function arrival943Build(){
 const d=programmeDays().find(d=>d.iso===ARRIVAL943.day);if(!d)return null;
 const loads=dpLoads(d).filter(g=>g.kind==='deliveries');
 const rows=loads.flatMap(g=>g.rows.filter(r=>ARRIVAL943.refs.includes(r.a.key)).map(r=>({a:r.a,g,units:loading872Rows(r.a)})));
 if(!rows.length)return null;
 const refs=rows.map(r=>r.a.key),same=JSON.stringify(refs)===JSON.stringify(ARRIVAL943.refs);
 const doors=rows.every(r=>r.units.length&&r.units.every(u=>loading872Side(r.a,u.id)===ARRIVAL943.sides[ARRIVAL943.refs.indexOf(r.a.key)]));
 const types=rows.every(r=>r.units.length===1&&r.units.every(u=>new RegExp('^building\\s+'+(r.a.key==='P25'?'4[ .]8':'6')+'\\s*m$','i').test(String(u.item).trim())));
 const p25=rows.find(r=>r.a.key==='P25'),number=!!p25&&p25.units.some(u=>String(u.no)==='1189408');
 const trucks=new Set(rows.map(r=>r.g)).size===4&&rows.every(r=>r.g.rows.length===1);
 const lifting=rows.every(r=>{const h=handling875Record(r.a);return h&&h.method==='tilt-tray';});
 return {d,rows,refs,artifactCurrent:same&&doors&&types&&number&&lifting&&trucks};
}
function arrival943Words(M){if(!M)return '';
 const units=M.rows.map(r=>r.a.key+': '+r.units.map(u=>u.item+(u.no?' · Asset '+u.no:'')+' · '+loading872Words(loading872Side(r.a,u.id))+' · '+handling875Words((handling875Record(r.a)||{}).method)).join('; '));
 return ['ALL TRUCKS ON SITE BEFORE 07:00 — load restriction curfew (no travel 07:00–09:00). 14 Oct 2026 · Esplanade arrival plan. Leave Kingston by 05:00. Traffic controllers from 06:00; follow their directions.',
 'Current arrival order: '+M.refs.join(' → ')+'. Front at the Higman Street end, remaining trucks close behind in this order. Limited space: no overtaking or queue-jumping.',
 'Way in: Gold Coast Highway south over Sundale Bridge → left into Waterways Drive → MacArthur Parade → Main Beach Parade south → keep LEFT onto the Esplanade at the red pedestrian crossing. Do not carry straight on. Stay in the holding strip; move to the drop area only when traffic control calls you.',...units,
 M.artifactCurrent?'Approved arrival map matches the current order, building types, P25 asset, door sides and tilt-tray method.':'The approved map snapshot is stale: current loads or door sides differ. Use the current details above and confirm the revised holding arrangement before dispatch.'].join('\n');}
function arrival943Html(M,print){return M?'<div class="arrival943"><p>'+esc(arrival943Words(M)).replace(/\n/g,'</p><p>')+'</p>'+(print?'':M.artifactCurrent?'<details><summary>Approved arrival map and PDF</summary><p><a href="'+ARRIVAL943.pdf+'" target="_blank" rel="noopener">Open arrival plan PDF</a></p><img data-arrival943-map data-arrival943-page="1" width="794" height="1123" style="width:100%;height:auto" alt="14 October Esplanade arrival order and holding map"><img data-arrival943-map data-arrival943-page="2" width="794" height="1123" style="width:100%;height:auto" alt="14 October aerial: left turn at red pedestrian crossing and parking order"></details>':'')+'</div>':'';}
const arrival943Flow=flow891Card;flow891Card=function(d){let h=arrival943Flow.apply(this,arguments);if(d.iso!==ARRIVAL943.day)return h;const M=arrival943Model();h=h.replace(/(<span class="flow891-seq">[\s\S]*?) <em>[^<]*<\/em>/g,'$1');return h+(M?'<section class="card"><h3>Esplanade arrival plan</h3>'+arrival943Html(M,false)+'</section>':'');};
document.addEventListener('toggle',e=>{const box=e.target;if(!box.matches||!box.matches('.arrival943 details')||!box.open)return;box.querySelectorAll('[data-arrival943-map]').forEach(im=>{if(!im.src)im.src=im.dataset.arrival943Page==='2'?ARRIVAL943.png2:ARRIVAL943.png;});},true);
const arrival943Page=dpPage;dpPage=function(d,g,doc,i,n){const args=arguments;let h=arrival943Scoped(d.iso,()=>arrival943Page.apply(this,args));if(d.iso!==ARRIVAL943.day||g.kind!=='deliveries'||!g.rows.some(r=>ARRIVAL943.refs.includes(r.a.key)))return h;const M=arrival943Model();if(M&&!M.artifactCurrent)h=h.replace('<section class="dp-sec',dpSec('Esplanade arrival plan',arrival943Html(M,true))+'<section class="dp-sec');return h+(M&&M.artifactCurrent?[ARRIVAL943.png,ARRIVAL943.png2].map(src=>'<div class="dp-page pl782 arrival943-map" style="padding:0;border:0" data-load="'+i+'"><div class="dp-win" style="width:100%;height:100%;flex:1"><img src="'+src+'" alt="Approved 14 October arrival plan" style="position:static;width:100%;height:100%;object-fit:contain"></div></div>').join(''):'');};
const arrival943Sms=dropSmsLong;dropSmsLong=function(a){const text=arrival943Sms.apply(this,arguments);const M=arrival943Model();return M&&!inPlace782(a.key)&&M.rows.some(r=>r.a.key===a.key)?text+'\n\n'+arrival943Words(M):text;};
const arrival943Mail=pdf7MailText;pdf7MailText=function(kind,iso,only,part,cap){const result=arrival943Mail.apply(this,arguments);if(result&&iso===ARRIVAL943.day){const M=arrival943Model();if(M){const d=M.d,L=dpLoads(d),pick=only!=null?[only]:part?part.loads:L.map((g,i)=>i);if(pick.some(i=>L[i]&&L[i].kind==='deliveries'&&L[i].rows.some(r=>ARRIVAL943.refs.includes(r.a.key)))){const full='\n\n'+arrival943Words(M);if(!cap||mailto(result.subject,result.text+full).length<=cap)result.text+=full;else{const brief='\n\n'+ARRIVAL943_CURFEW+'. Order '+M.refs.join(' → ')+'. TC from 06:00. Leave Kingston by 05:00. Arrival route and current unit/door details are in the attached PDFs.';const allowance=cap-(mailto('',brief).length-mailto('','').length);const compact=arrival943Mail(kind,iso,only,part,allowance);result.text=compact.text+brief;}}}}return result;};
const ARRIVAL943_CURFEW='ALL TRUCKS ON SITE BEFORE 07:00 — load restriction curfew (no travel 07:00–09:00)';
let arrival943Scope=null;
function arrival943Scoped(iso,fn){const prior=arrival943Scope;arrival943Scope=iso===ARRIVAL943.day;try{return fn();}finally{arrival943Scope=prior;}}
function arrival943Ref(a){if(!a||!ARRIVAL943.refs.includes(a.key))return null;if(arrival943Scope===false||a&&Array.isArray(a.events)&&a.events.length&&a.events.every(e=>e.movement==='remove'))return null;const M=arrival943Model();return M&&a&&M.rows.some(r=>r.a.key===a.key)?M:null;}
const arrival943Order=order782;order782=function(a){const old=arrival943Order.apply(this,arguments),M=arrival943Ref(a);if(!M)return old;return Object.assign({},old||{},{ref:a.key,sms:'ORDER: '+M.refs.join(' → ')+'. No queue-jumping. '+ARRIVAL943_CURFEW+'. Traffic control from 06:00.',seq:false});};
const arrival943Entry=entry782;entry782=function(a){const M=arrival943Ref(a);if(!M)return arrival943Entry.apply(this,arguments);const words=arrival943Words(M).split('\n').find(s=>s.startsWith('Way in:'));return {side:'Esplanade holding strip',zone:'given',sms:'ENTRY: '+words,words};};
const arrival943Head=flow891HeadLines;flow891HeadLines=function(d,g,doc,i,n){return d.iso===ARRIVAL943.day&&g.kind==='deliveries'?'<span class="dp891-rl"><b>'+esc(ARRIVAL943_CURFEW)+'</b> · current order '+esc((arrival943Model()||{refs:[]}).refs.join(' → '))+' · TC from 06:00</span>':arrival943Head.apply(this,arguments);};
const arrival943Daily=daily821Model;daily821Model=function(iso){const args=arguments,M=arrival943Scoped(iso,()=>arrival943Daily.apply(this,args));if(iso!==ARRIVAL943.day)return M;const A=arrival943Model();if(!A)return M;M.loads.forEach(l=>(l.rows||[]).forEach(r=>{r.notes=(r.notes||[]).map(s=>s.replace(/Arrival window [^.]+\./g,ARRIVAL943_CURFEW+'.'));if(A.refs.includes(r.key))r.notes.push(arrival943Words(A));}));return M;};
const arrival943DailyText=daily861Body;daily861Body=function(iso,team,url,weather){const text=arrival943DailyText.apply(this,arguments);if(iso!==ARRIVAL943.day)return text;const M=arrival943Model();return M?text+'\n\n'+daily861Gsm(ARRIVAL943_CURFEW+'. Order '+M.refs.join(' → ')+'. TC from 06:00. Leave Kingston by 05:00. No queue-jumping.'):text;};
const arrival943Hero=dpHero;dpHero=function(d,g,doc){const h=arrival943Hero.apply(this,arguments);return d.iso===ARRIVAL943.day&&g.kind==='deliveries'?h.replace(/<label>On site<\/label>[\s\S]*?<\/div>/,'<label>On site</label><b>Before 07:00</b><span>Load restriction curfew · no travel 07:00–09:00</span></div>'):h;};
