// Author: Andrew Fisher. v8.95 checks - the 7 Oct Baseplan export on the page. Read-only against the live record (open_page aborts every write).
// The new lines appear, statuses follow the 7 Oct export, Andrew's recorded asset numbers still win, and the P&L, Costs to job end,
// the Finance handover and the Transport view all reconcile. No $ amount is printed: money is reported as a share or a direction.
//   PAGE=build/GC500_v8.95/GC500_Delivery_Control_hosted.html [MOB=1] [OUT=dir] node v8.95_baseplan_07oct_DRAFT/tests/test_contracts895.cjs
const fs = require('fs'), {open} = require('../../toolchain/harness/open_page');
(async () => { let s; try { const MOB = !!process.env.MOB, R = []; const ok = (name, pass, detail) => R.push({name, pass: !!pass, detail});
  s = await open(MOB ? {pageFile: process.env.PAGE, W: 390, H: 844, dpr: 2, mobile: true} : {pageFile: process.env.PAGE, W: 1440, H: 900}); const p = s.page;
  await p.waitForFunction(() => typeof go === 'function' && typeof TABS !== 'undefined' && typeof SYNC !== 'undefined' && SYNC.status === 'live' && typeof transport888Core === 'function', null, {timeout: 150000}); await p.waitForTimeout(2500);
  await p.evaluate(() => go('costs')); await p.waitForFunction(() => { try { return moneySummary().charge.labour >= 0 && !!document.getElementById('recon888'); } catch (e) { return false; } }, null, {timeout: 30000}); await p.waitForTimeout(1200);
  const near = (a, b, eps = 0.005) => typeof a === 'number' && typeof b === 'number' && Math.abs(a - b) < eps;
  const pct = (part, whole) => typeof part === 'number' && typeof whole === 'number' && whole ? Math.round(part / whole * 10000) / 100 + '%' : 'n/a';
  const X = await p.evaluate(() => holdAssets(() => { const row = k => ONHIRE_ROWS.find(r => r.rental_contract + '/' + r.line === k) || null; const A = k => allAssets().find(a => a.key === k) || null;
    const M = moneySummary(), C = cj764Model(), H = fh866Model(), P = pl770Model(), B = pl752Rows(), V = transport888View(), T = transport888Core(), RC = recon888Model();
    const r2 = v => Math.round((v + Number.EPSILON) * 100) / 100;
    const WC07 = ['1002566', '1317640', '1211959', '1317649', '1317647', '1317626', '1317652', '1317648', '1212552', '1200595', '1181004', '1002538', '1317658', '1317632', '1317643', '1317641', '1002715', '1083300', '1192643', '1002651'];
    const wc07Lines = []; for (let l = 24; l <= 43; l++) wc07Lines.push(row('9968955/' + l));
    const gens = [row('9961976/42'), row('9961976/43')].map(r => r && Object.assign({r}, {ch: contractCharge(r), f: lr748For(r), d: days748(r), rd: rentalOf('GN?')}));
    const forkCh = contractCharge(row('9961976/27'));
    /* Andrew's numbers: the record's WC07 numbers (as supplied, 22 Sep) against the lines' numbers; a joined number may never sit on another reference's record */
    const wc07Nums = assetNumbersOf(A('WC07')), rentalWC07 = rentalOf('WC07');
    const typed = Object.assign({}, S.assetNumbers || {}), suppliedNums = {}; Object.entries(S.supplied || {}).forEach(([k, v]) => { suppliedNums[k] = [].concat(v.asset_numbers || [], ...(v.items || []).map(i => i.nums || [])).map(String); });
    const opsNums = {}; (DATA.ops.rows || []).forEach(r => { if (r.recorded_by) (r.asset_numbers_supplied || []).forEach(n => { opsNums[String(n)] = r.key; }); });
    const recordOf = n => { for (const [k, v] of Object.entries(typed)) if ((v || []).map(String).includes(n)) return k; for (const [k, v] of Object.entries(suppliedNums)) if (v.includes(n)) return k; return opsNums[n] || null; };
    const contradictions = ONHIRE_ROWS.filter(r => r.asset_no_is_plant_number && r.match && r.match.to === 'asset' && r.match.key && recordOf(String(r.asset_no)) && recordOf(String(r.asset_no)) !== r.match.key).map(r => r.rental_contract + '/' + r.line);
    /* the two references on two records at once the page already knows about (1264929 T0002/NVLT, 1197839 T0004/FL02) are register facts, not contract joins */
    const nvac = B.find(b => b.code === 'NVAC') || {}, kinp = B.find(b => b.code === 'KINP') || {};
    const genCharge = r2(gens.reduce((s, g) => s + ((g && g.ch && typeof g.ch.amount === 'number') ? g.ch.amount : 0), 0));
    const toiletCharge = r2(wc07Lines.reduce((s, r) => s + (contractCharge(r).amount || 0), 0));
    const xT = (C.rows || []).find(r => /^Transport/.test(r.stream)) || {}, hT = (H.costs || []).find(r => r.kind === 'transport') || {by: {}};
    const invBy = (H.inv || H.invTotal || {}); const pane = document.getElementById('pane-costs'); document.querySelectorAll('#pane-costs details').forEach(d => d.open = true); const txt = pane ? pane.innerText : '';
    return {on: ONHIRE.supplied_on, workbook: ONHIRE.workbook, lines: ONHIRE_ROWS.length, contracts: ONHIRE.contracts.length, sup: (ONHIRE.supplements || []).slice(-1)[0],
      gens: gens.map(g => g && {status: g.r.status_as_written, start: g.r.start_date, demob: g.r.demob_date, booked: g.r.booked_delivery_date, kind: g.r.kind, rate: g.r.rate_1, match: (g.r.match || {}).key, how: g.ch.how, filled: g.ch.filled || null, hasAmount: typeof g.ch.amount === 'number' && g.ch.amount > 0,
        cardLine: g.f && g.f.plant && g.f.plant.line, per: g.f && g.f.per, days: g.d && g.d.days, eventWindow: g.d && [g.d.from, g.d.to], why: g.f && g.f.plant && g.f.plant.why, basisSaysEvent: /event days/.test(g.ch.basis || ''), amountIsCardTimesDays: !!(g.f && g.d && typeof g.ch.amount === 'number' && Math.abs(g.ch.amount - Math.round(g.f.plant.daily * g.d.days * 100) / 100) < 0.005), onSite: !!(g.rd && g.rd.from)}),
      genShareOfNVAC: nvac.total ? genCharge / nvac.total : null, genShareOfContracts: M.charge.contracts ? genCharge / M.charge.contracts : null, genShareOfRevenue: M.charge.total ? genCharge / M.charge.total : null, nvacCardLines: nvac.cardLines,
      wc07: {statuses: [...new Set(wc07Lines.map(r => r && r.status_as_written))], starts: [...new Set(wc07Lines.map(r => r && r.start_date))], nums: wc07Lines.map(r => r && r.asset_no), joined: wc07Lines.filter(r => r && r.match && r.match.key === 'WC07').map(r => r.line), unjoined: wc07Lines.filter(r => r && !(r.match && r.match.key)).map(r => [r.line, r.asset_no]),
        recordNums: wc07Nums.length, has1317743: wc07Nums.includes('1317743'), has1317643: wc07Nums.includes('1317643'), rentalLines: rentalWC07 ? rentalWC07.lines.length : 0, rentalFrom: rentalWC07 && rentalWC07.from, branch: (branchOf('WC07') || {}).code, hows: [...new Set(wc07Lines.map(r => contractCharge(r).how))], toiletShareOfKINP: kinp.total ? toiletCharge / kinp.total : null},
      p56: {status: row('9968862/89').status_as_written, start: row('9968862/89').start_date, from: (rentalOf('P56') || {}).from, match: (row('9968862/89').match || {}).key, how: contractCharge(row('9968862/89')).how},
      dockets: [['9968955/97', 'WC31', '26115307'], ['9968955/103', 'WC09', '26115312'], ['9968955/105', 'WC09', '26115316']].map(([k, ref, dn]) => { const r = row(k); return {k, status: r.status_as_written, dn: r.delivery_number, match: (r.match || {}).key, via: (r.match || {}).via, start: r.start_date, want: [ref, dn], refLines: (rentalOf(ref) || {lines: []}).lines.length, refFrom: (rentalOf(ref) || {}).from}; }),
      fork: {what: row('9961976/27').what, how: forkCh.how, filled: forkCh.filled || null},
      p52: (() => { const a = A('P52'), ev = (a.events || [])[0] || {}, bk = ev.booking801 || {}; const all = JSON.stringify(DATA); return {register: a.asset_numbers, page: assetNumbersOf(a), rental: (rentalOf('P52') || {numbers: []}).numbers, bookingText: bk.asset_text, bookingNums: ((bk.loads || [])[0] || {}).asset_numbers, ops: ((DATA.ops.rows || []).find(r => r.key === 'P52') || {}).asset_numbers_scheduled, wrongInData: all.includes('13227211'), rightCount: (all.match(/(?<!\d)1327211(?!\d)/g) || []).length, wrongInPage: document.documentElement.outerHTML.includes('13227211')}; })(),
      record: [['9968862/50', 'P37'], ['9968862/79', 'P52']].map(([k, ref]) => { const r = row(k), rt = rentalOf(ref) || {lines: []}, ch = contractCharge(r); return {k, ref, match: (r.match || {}).key, via: (r.match || {}).via, status: r.status_as_written, start: r.start_date, how: ch.how, filled: ch.filled || null, refLines: rt.lines.length, refFrom: rt.from || null, numbers: assetNumbersOf(A(ref)), branch: (branchOf(ref) || {}).code}; }),
      contradictions, recordRefs: Object.keys(typed).length,
      pending: {n: ONHIRE_ROWS.filter(r => r.status_as_written === 'Pending').length, onHire: ONHIRE_ROWS.filter(r => r.status_as_written === 'Pending' && (r.start_date || r.delivered)).length},
      recon: {ok: RC.ok, bad: RC.bad, count: RC.count, failing: RC.ties.filter(t => !t.ok).map(t => t.what)}, pl770: P.checks, fh: {costCheck: H.costCheck, invCheck: H.invCheck, peopleCheck: H.peopleCheck},
      ties: {revRecord: [M.charge.total, H.invTotal.onRecord, (P.rev || []).reduce((s, l) => s + (l.now || 0), 0)], revJob: [C.revenue.job, P.revJob, H.invTotal.job], transportToDate: [V.tot.actual, M.cost.transport.amount, xT.toDate, hT.toDate], transportToCome: [V.tot.toCome, xT.toCome, hT.toCome, T.forecast.total],
        transportRevenue: [V.revenueTotal, M.charge.delivery], branchesAddUp: Math.abs(r2(B.reduce((s, b) => s + b.total, 0)) - M.charge.contracts) < 0.02 && Math.abs(r2(M.charge.by_branch.reduce((s, b) => s + b.charge, 0)) - M.charge.contracts) < 0.02 && Math.abs(r2(B.reduce((s, b) => s + b.transport, 0)) - M.charge.delivery) < 0.02, branches: B.length},
      words: {dateShown: /7 Oct 2026|2026-10-07/.test(txt), oldDate: /Baseplan export of 6 Oct 2026/.test(txt), phone: !/\b0[45]\d{2}[ -]?\d{3}[ -]?\d{3}\b/.test(txt), author: /Author: Andrew Fisher/.test(document.body.innerText)},
      overflow: document.documentElement.scrollWidth <= innerWidth + 2}; }));
  ok('the contracts are the 7 Oct export: 323 lines on 11 contracts, supplement v8.95 bound by SHA-256', X.on === '2026-10-07' && X.workbook === 'Baseplan_SuperCars_07Oct.xlsx' && X.lines === 323 && X.contracts === 11 && X.sup && X.sup.applied === 'v8.95' && /^8a18bd1f/.test(X.sup.sha256), {on: X.on, lines: X.lines, contracts: X.contracts});
  ok('the two new NVAC lines (9961976/42, 43) are on the page: 200 kVA generators, Pending, booked 12-26 Oct, no rate, joined to GN?', X.gens.every(g => g && g.status === 'Pending' && g.kind === 'generator' && g.rate === null && g.match === 'GN?' && g.booked === '2026-10-12' && g.demob === '2026-10-26'), X.gens);
  ok('how the page treats a Pending line: not on hire (no start date, GN? not on site by the rental system), but charged - a generator with no rate goes at the card\'s 200 kVA line once, for the three event days', X.gens.every(g => g && g.start === null && !g.onSite && g.how === 'whole event' && g.filled === 'card' && g.hasAmount && g.cardLine === 'Generator 200 KVA' && g.per === 'event' && g.days === 3 && g.basisSaysEvent && g.amountIsCardTimesDays && !g.why), X.gens);
  ok('the two generators are a small share of NVAC\'s contract revenue and of the contracts total (' + pct(X.genShareOfNVAC, 1) + ' of NVAC, ' + pct(X.genShareOfContracts, 1) + ' of the contracts, ' + pct(X.genShareOfRevenue, 1) + ' of Revenue on the record) and count among NVAC\'s card-filled lines', X.genShareOfNVAC > 0 && X.genShareOfNVAC < 0.25 && X.genShareOfContracts > 0 && X.genShareOfContracts < 0.05 && X.nvacCardLines >= 2, {nvac: pct(X.genShareOfNVAC, 1), contracts: pct(X.genShareOfContracts, 1)});
  ok('WC07\'s 20 FWF lines follow the 7 Oct export: Delivered, on hire from 22 Sep, each with its asset number', X.wc07.statuses.join() === 'Delivered' && X.wc07.starts.join() === '2026-09-22' && X.wc07.nums.every(n => /^\d{7}$/.test(n || '')), X.wc07);
  ok('Andrew\'s recorded numbers win on WC07: 19 lines join WC07, line 38 (1317643) does not; the page shows his 20 numbers with 1317743 and never 1317643', X.wc07.joined.length === 19 && X.wc07.unjoined.length === 1 && X.wc07.unjoined[0][0] === 38 && X.wc07.unjoined[0][1] === '1317643' && X.wc07.recordNums === 20 && X.wc07.has1317743 && !X.wc07.has1317643 && X.wc07.rentalLines === 19 && X.wc07.rentalFrom === '2026-09-22' && X.wc07.branch === 'KINP', X.wc07);
  ok('the toilet lines\' charge is the whole-event rate and did not move with the status (' + pct(X.wc07.toiletShareOfKINP, 1) + ' of KINP\'s contract revenue)', X.wc07.hows.join() === 'whole event' && X.wc07.toiletShareOfKINP > 0, X.wc07.hows);
  ok('P56 (9968862/89): Delivered, on hire from 7 Oct by the rental system, still joined to P56, charged once (whole event)', X.p56.status === 'Delivered' && X.p56.start === '2026-10-07' && X.p56.from === '2026-10-07' && X.p56.match === 'P56' && X.p56.how === 'whole event', X.p56);
  ok('the three Del Req lines carry their dockets and join WC31 and WC09 by them, not yet on hire', X.dockets.every(d => d.status === 'Del Req' && d.dn === d.want[1] && d.match === d.want[0] && d.via === 'delivery docket' && d.start === null && d.refLines >= 1 && !d.refFrom), X.dockets);
  ok('the NVAC forklift line (9961976/27) now reads Forklift 3.5t Diesel and still goes by the card\'s day rate', X.fork.what === 'Forklift 3.5t Diesel' && X.fork.how === 'per day' && X.fork.filled === 'card', X.fork);
  ok('no contract line joins a reference that contradicts a number on Andrew\'s record (' + X.recordRefs + ' references with typed numbers)', X.contradictions.length === 0, X.contradictions.slice(0, 6));
  ok('Andrew\'s record joins two more lines under his rule: 9968862/50 (1105053) to P37, on hire from 17 Sep by the rental system; 9968862/79 (1327211) to P52 beside its docket line; both charged once (whole event), no card fill',
     X.record[0].match === 'P37' && X.record[0].via === 'asset number' && X.record[0].status === 'Delivered' && X.record[0].start === '2026-09-17' && X.record[0].refLines === 1 && X.record[0].refFrom === '2026-09-17' && X.record[0].numbers.includes('1105053') && X.record[0].branch === 'KINP'
     && X.record[1].match === 'P52' && X.record[1].via === 'asset number' && X.record[1].status === 'Del Req' && X.record[1].start === null && X.record[1].refLines === 2 && X.record[1].numbers.includes('1327211') && X.record[1].branch === 'KINP'
     && X.record.every(r => r.how === 'whole event' && r.filled === null), X.record);
  ok('P52 shows 1327211 everywhere (register, booking, as-supplied, its contract line, the page\'s numbers) and never 13227211 (Andrew, 8 Oct 2026: "1327211 is correct")',
     JSON.stringify(X.p52.register) === '["1327211"]' && JSON.stringify(X.p52.page) === '["1327211"]' && X.p52.rental.includes('1327211') && X.p52.bookingText === '1327211' && JSON.stringify(X.p52.bookingNums) === '["1327211"]' && JSON.stringify(X.p52.ops) === '["1327211"]' && !X.p52.wrongInData && !X.p52.wrongInPage && X.p52.rightCount >= 8, X.p52);
  ok('every Pending line is off hire (v8.71\'s rule): none has a start date or is delivered (' + X.pending.n + ' Pending lines)', X.pending.n > 100 && X.pending.onHire === 0, X.pending);
  ok('Everything reconciles: all ' + X.recon.count + ' tie-outs tied', X.recon.ok && X.recon.bad === 0 && X.recon.count >= 17, X.recon);
  ok('the P&L reconciles (revenue, costs, job end) and the Finance handover\'s checks hold (costs, invoice, people)', X.pl770.revenue === true && X.pl770.costs === true && X.pl770.revenueJob === true && X.pl770.costsJob === true && X.fh.costCheck && X.fh.invCheck.record && X.fh.invCheck.job && X.fh.peopleCheck, {pl770: X.pl770, fh: X.fh});
  const allNear = arr => arr.every(v => near(v, arr[0]));
  ok('Revenue on the record and to job end read the same on the P&L, the business\'s lines and the Finance handover', allNear(X.ties.revRecord) && allNear(X.ties.revJob), {record: X.ties.revRecord.map((v, i, a) => near(v, a[0])), job: X.ties.revJob.map((v, i, a) => near(v, a[0]))});
  ok('Transport to date, still to come and Transport Revenue read the same on the Transport view, the P&L, Costs to job end and the handover', allNear(X.ties.transportToDate) && allNear(X.ties.transportToCome) && allNear(X.ties.transportRevenue), {toDate: X.ties.transportToDate.map((v, i, a) => near(v, a[0])), toCome: X.ties.transportToCome.map((v, i, a) => near(v, a[0])), rev: X.ties.transportRevenue.map((v, i, a) => near(v, a[0]))});
  ok('the branches\' contract revenue (By branch) adds to the P&L\'s contracts charge, and their charge lines to Transport Revenue', X.ties.branchesAddUp, {branches: X.ties.branches});
  ok('the Costs tab names the 7 Oct export and no longer the 6 Oct one; no phone number; the author line stands', X.words.dateShown && !X.words.oldDate && X.words.phone && X.words.author, X.words);
  /* the reference drawer: WC07 shows its contract lines; the Equipment tab opens */
  await p.evaluate(() => { go('plant'); }); await p.waitForTimeout(1200);
  await p.evaluate(() => { openAsset('WC07'); }); await p.waitForTimeout(1500);
  /* the drawer's asset pills and the driver's card sit in folds, so the drawer's HTML is read, not its visible text */
  const D = await p.evaluate(() => { const d = document.getElementById('drawer'); const h = d ? d.innerHTML : '', t = d ? d.innerText : ''; return {on: !!d && d.classList.contains('on'), sel: state.sel, rental9968955: /Rental <b>9968955<\/b>/.test(h), numbers: ['1317743', '1002566', '1002651', '1317626'].map(n => h.includes('asset ' + n) || h.includes('<b>' + n + '</b>')), twenty: /20 asset numbers/.test(t), wrong: h.includes('1317643'), since: /since 22 Sep/.test(t), overflow: document.documentElement.scrollWidth <= innerWidth + 2}; });
  ok('WC07\'s drawer opens on Equipment: on site since 22 Sep, Rental 9968955, his 20 asset numbers with 1317743, and never 1317643', D.on && D.sel === 'WC07' && D.rental9968955 && D.numbers.every(Boolean) && D.twenty && D.since && !D.wrong, D);
  if (process.env.OUT) { fs.mkdirSync(process.env.OUT, {recursive: true}); await p.screenshot({path: process.env.OUT + '/wc07-drawer-' + (MOB ? 'phone' : 'laptop') + '.png'}); }
  await p.evaluate(() => { if (state.drawerClose) state.drawerClose(); }); await p.waitForTimeout(400);
  await p.evaluate(() => { openAsset('P52'); }); await p.waitForTimeout(1500);
  const D52 = await p.evaluate(() => { const d = document.getElementById('drawer'); const h = d ? d.innerHTML : '', t = d ? d.innerText : ''; return {on: !!d && d.classList.contains('on'), sel: state.sel, right: h.includes('1327211'), wrong: h.includes('13227211'), head: t.slice(0, 160).replace(/\n/g, ' ')}; });
  ok('P52\'s drawer names 1327211 and never 13227211', D52.on && D52.sel === 'P52' && D52.right && !D52.wrong, D52);
  if (process.env.OUT) await p.screenshot({path: process.env.OUT + '/p52-drawer-' + (MOB ? 'phone' : 'laptop') + '.png'});
  await p.evaluate(() => { if (state.drawerClose) state.drawerClose(); go('costs'); }); await p.waitForTimeout(1500);
  if (process.env.OUT) { await p.evaluate(() => { const el = document.getElementById('recon888'); if (el) { el.open = true; el.scrollIntoView({block: 'start'}); } }); await p.waitForTimeout(400); await p.screenshot({path: process.env.OUT + '/reconciles-' + (MOB ? 'phone' : 'laptop') + '.png'}); }
  ok(MOB ? 'phone: no page-wide horizontal overflow on Costs or Equipment' : 'laptop: no page-wide horizontal overflow on Costs or Equipment', X.overflow && D.overflow, {costs: X.overflow, plant: D.overflow});
  const same = await p.evaluate(() => { const b = JSON.stringify([moneySummary(), cj764Model().job, fh866Model().costTotal]); render(); return b === JSON.stringify([moneySummary(), cj764Model().job, fh866Model().costTotal]); });
  ok('a redraw changes no figure', same, {});
  ok('no page errors', s.errors.length === 0, s.errors.slice(0, 4));
  ok('no writes attempted', s.counts.blocked === 0, s.counts);
  R.forEach(r => console.log(`${r.pass ? 'PASS' : 'FAIL'}  ${r.name}${r.pass ? '' : '  ' + JSON.stringify(r.detail).slice(0, 700)}`));
  const fails = R.filter(r => !r.pass).length; console.log(`${MOB ? 'phone' : 'desktop'}: ${R.length - fails}/${R.length} pass`); process.exitCode = fails ? 1 : 0;
} finally { if (s) await s.browser.close(); } })().catch(e => { console.error('TEST FAIL', e); process.exit(2); });
