/* Author: Andrew Fisher. Focused native navigation probes. Every service mutation is blocked. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const assert=require('node:assert/strict'),Module=require('module');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));
const original=fs.readFileSync(hp,'utf8');assert.match(original,/const okPost = [^;]+;/);assert(original.includes('counts.blocked++;'));
hm._compile(original.replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++; (counts.blockedPaths ||= []).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const {open}=hm.exports;
async function guard(p){await p.evaluate(()=>{if(Array.isArray(SYNC.unsub)){SYNC.unsub.forEach(fn=>fn());SYNC.unsub=[];}window.__timeline937Writes=[];window.bump=()=>{__timeline937Writes.push('bump');throw Error('Timeline navigation must not save');};if(SYNC.db&&typeof SYNC.db.doc==='function'){const native=SYNC.db.doc.bind(SYNC.db);SYNC.db.doc=(...args)=>{const doc=native(...args);for(const m of ['set','update','delete'])if(typeof doc[m]==='function')doc[m]=()=>{__timeline937Writes.push(m);throw Error('Timeline navigation must not write');};return doc;};}});}
async function assertNoWrites(p,s){assert.deepEqual(await p.evaluate(()=>__timeline937Writes),[]);assert((s.counts.blockedPaths||[]).every(x=>x.method==='POST'&&x.origin==='https://tile.googleapis.com'&&x.path==='/v1/createSession'));}

const file=process.env.PAGE||'/workspace/private-timeline937/candidate.html',out=process.env.TIMELINE_OUT||'/workspace/private-timeline937/evidence';fs.mkdirSync(out,{recursive:true});
const result={sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),checks:[],sessions:[]};
function note(name,pass,data){result.checks.push({name,pass,...(data?{data}:{})});console.log((pass?'PASS ':'FAIL ')+name);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));}
async function measure(p){return p.evaluate(()=>{const st=document.querySelector('#pane-timeline .daystrip'),on=st?.querySelector('.day.on'),r=st?.getBoundingClientRect(),q=on?.getBoundingClientRect();return{date:on?.dataset.day,expected:pickDay(calendarDays()),visible:!!r&&r.width>0&&q.width>0&&q.left>=r.left-2&&q.right<=r.right+2,left:st?.scrollLeft,main:document.querySelector('main').scrollTop,doc:window.scrollY,maxMain:document.querySelector('main').scrollHeight-document.querySelector('main').clientHeight,focus:document.activeElement?.outerHTML.slice(0,160),hash:location.hash};});}
async function ready(p){await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live',null,{timeout:120000});await p.waitForTimeout(120);await guard(p);}
(async()=>{for(const width of [390,1440]){let s;
 try{s=await open({pageFile:file,hash:'#timeline',W:width,H:900,mobile:width===390}),p=s.page;await ready(p);let before=await p.evaluate(()=>JSON.stringify(S));let m=await measure(p);note(width+' fresh Timeline selected day visible',m.visible&&m.date===m.expected,{date:m.date});note(width+' fresh Timeline does not scroll document',m.doc===0&&m.main===0);
 await p.locator('#pane-timeline .daystrip').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'timeline-'+width+'.png')});
 await p.reload({waitUntil:'load'});await ready(p);before=await p.evaluate(()=>JSON.stringify(S));m=await measure(p);note(width+' refresh retains visible selected day',m.visible&&m.date===m.expected);
 await p.evaluate(()=>{location.hash='#day/2026-10-23';});await p.waitForTimeout(150);await p.reload({waitUntil:'load'});await ready(p);before=await p.evaluate(()=>JSON.stringify(S));m=await measure(p);note(width+' fresh explicit day link is honoured and visible',m.visible&&m.date==='2026-10-23'&&m.hash==='#day/2026-10-23');
 for(const [selector,label] of [['[data-day-step="-1"]','Prev'],['[data-day-step="1"]','Next'],['.daynav [data-day]','Today']]){const expected=await p.evaluate(sel=>{const b=document.querySelector('#pane-timeline '+sel),days=calendarDays(),i=days.findIndex(d=>d.iso===pickDay(days));return b.hasAttribute('data-day-step')?days[i+Number(b.dataset.dayStep)].iso:b.dataset.day;},selector);const position=await p.evaluate(sel=>{const main=document.querySelector('main');main.scrollTop=200;const before={main:main.scrollTop,doc:scrollY};document.querySelector('#pane-timeline '+sel).click();return before;},selector);await p.waitForTimeout(100);m=await measure(p);note(width+' '+label+' selects visible day',m.visible&&m.date===expected);note(width+' '+label+' preserves document/main scroll',m.doc===position.doc&&m.main===Math.min(position.main,m.maxMain),{before:position,after:{main:m.main,doc:m.doc,maxMain:m.maxMain}});}
 // Rapid stepping must use the final render, without stale callbacks.
 const rapid=await p.evaluate(()=>{for(let i=0;i<3;i++)document.querySelector('#pane-timeline [data-day-step="1"]').click();return state.day;});await p.waitForTimeout(100);m=await measure(p);note(width+' rapid Next uses final selected day',m.visible&&m.date===rapid);
 const selected=m.date;await p.evaluate(()=>{go('today');go('timeline');});await p.waitForTimeout(150);m=await measure(p);note(width+' return from Today preserves selected day',m.visible&&m.date===selected);
 const stationary=await p.evaluate(()=>{const main=document.querySelector('main'),strip=document.querySelector('#pane-timeline .daystrip');main.scrollTop=250;strip.scrollLeft=0;document.querySelector('#pane-timeline [data-day-step="1"]').focus({preventScroll:true});const before={main:main.scrollTop,doc:scrollY,focus:document.activeElement};TimelineStrip937.reveal();return{same:main.scrollTop===before.main&&scrollY===before.doc&&document.activeElement===before.focus};});m=await measure(p);note(width+' reveal moves only strip, preserving focus',stationary.same&&m.visible);
 await p.evaluate(()=>{go('today');window.dispatchEvent(new Event('resize'));});note(width+' resize after leaving stays on Today',await p.evaluate(()=>state.tab==='today'));
 note(width+' operational record unchanged',await p.evaluate(v=>JSON.stringify(S)===v,before));await assertNoWrites(p,s);note(width+' no runtime errors',s.errors.length===0);result.sessions.push({width,errors:s.errors,requests:s.counts});
 }catch(e){result.error=e.stack;console.error(e.stack);}finally{if(s)await s.browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));}if(result.error)break;}
 console.log(result.checks.filter(c=>c.pass).length+'/'+result.checks.length+' checks passed');if(result.error||result.checks.some(c=>!c.pass))process.exitCode=1;
})();
