// Author: Andrew Fisher. Read-only ownership projection and exact scoped labels.
'use strict';
const assert=require('assert/strict'),vm=require('vm'),fs=require('fs'),path=require('path');
const a={key:'WC09'}, rows=[
 {id:'b1',ref:'WC09',physical:true,item:'Toilet Block 6m',owner:'coates',assetNo:'1268858'},
 {id:'b2',ref:'WC09',physical:true,item:'Toilet Block 6m',owner:'coates',assetNo:'1311146'},
 {id:'f1',ref:'WC09',physical:true,item:'FWF',owner:'event-portables',assetNo:'0085',label:'Sub-hire: Event Portables'},
 {id:'f2',ref:'WC09',physical:true,item:'FWF',owner:'event-portables',assetNo:'0551'}
],quantity={ref:'WC09',item:'Pee Panel',owner:'event-portables',quantity:6,quantityOnly:true,received:6,installed:6};
let moved=false;const box={module:{exports:{}},Units925:{company:v=>({'coates':'Coates','event-portables':'Event Portables','prem-air-hire':'PremAir Hire','unknown':'Owner unconfirmed'})[v]||v},gcModel925:()=>({rows}),movedAway:()=>moved,assetOf:()=>a,heldMemo:(_k,f)=>f(),quantitySubhire964List:()=>({rows:[quantity]}),chargeLines:x=>x.lines||[],qtyOf:l=>l.quantity};
vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(__dirname,'ownership969.js'),'utf8'),box);const p=box.module.exports;let count=0;const eq=(x,y,m)=>{assert.deepEqual(JSON.parse(JSON.stringify(x)),y,m);count++;},has=(x,re,m)=>{assert.match(x,re,m);count++;};
const before=JSON.stringify([a,rows,quantity]),m=p.project(a,rows,[quantity]);eq(m.active,true,'mixed item suppliers activate labels');eq(m.rows.map(g=>[g.item,g.owner,g.quantity]),[['Toilet Block 6m','coates',2],['FWF','event-portables',2],['Pee Panel','event-portables',6]],'quantities keep exact item owner');
has(p.html(a),/SUB-HIRED · Event Portables · Pee Panel/,'quantity ownership is explicit');has(p.text(a),/Coates · Toilet Block 6m · asset 1268858, asset 1311146/,'owned blocks not supplier marked');has(p.text(a),/quantity 6 \(no fleet numbers\)/,'quantity-only cannot become identities');eq(JSON.stringify([a,rows,quantity]),before,'projection does not mutate sources');
eq(p.project(a,rows.concat(rows),[quantity]).rows[0].quantity,2,'repeated identities counted once');eq(p.project(a,rows,[quantity,{...quantity}]).rows.length,2,'duplicate quantity records omitted');eq(p.project(a,rows,[{...quantity,quantity:6.5}]).rows.length,2,'noninteger quantity omitted');eq(p.project(a,rows,[{...quantity,ref:'WC31'}]).rows.length,2,'quantity from another location omitted');eq(p.project(a,rows.concat([{id:'pee1',ref:'WC09',physical:true,item:'Pee Panel',owner:'event-portables',assetNo:'7'}]),[quantity]).rows.find(g=>g.item==='Pee Panel').quantity,1,'physical overlap never doubles quantity stock');
eq(p.project(a,rows.concat([{...rows[0],id:'old',physical:false}]),[quantity]).rows[0].quantity,2,'history excluded');eq(p.project(a,rows.concat([{...rows[0],id:'another-ref',ref:'WC31'}]),[quantity]).rows[0].quantity,2,'foreign identities excluded');
for(const flag of ['_cancelled','relocation','rest_of','_movedTo','_locationMoved'])eq(p.project({...a,[flag]:true},rows,[quantity]).active,false,flag+' excluded');
eq(p.project(a,rows.filter(r=>r.owner==='coates'),[]).active,false,'ordinary owned reference retains existing display');moved=true;eq(p.read(a).active,false,'moved location omitted');moved=false;
eq(p.project(a,rows,[quantity],{items:['FWF'],numbers:['0085']}).rows.map(g=>[g.item,g.quantity,g.units[0].number]),[['FWF',1,'0085']],'split load shows only explicit booked identity');eq(p.project(a,rows,[quantity],{items:['Toilet Block 6m'],numbers:['1268858']}).rows[0].owner,'coates','Coates-only split does not inherit EP ownership');eq(p.project(a,rows,[quantity],{items:['Pee Panel'],quantity:{'Pee Panel':2}}).rows[0].quantity,2,'quantity load share remains a share');eq(p.project(a,rows,[quantity],{items:['Pee Panel'],quantity:{'Pee Panel':7}}).rows.length,0,'load share cannot exceed owned quantity');
eq(p.project(a,[],[{...quantity,owner:''}]).rows[0].owner,'unknown','unknown quantity owner is not labelled as a supplier');
const mat={key:'T0416',product:'Trakmat'},matUnit={id:'catalogue',ref:'T0416',physical:true,item:'Trakmat',owner:'coates',assetNo:'TRAKMAT2.4X1.1'};box.assetOf=()=>mat;box.gcModel925=()=>({rows:[matUnit],groups:[{item:'Trakmat'}]});box.ItemPhotos965={group:()=>({ref:'T0416',item:'Trakmat',owner:'coates',quantity:20,active:true}),catalogue:(_a,u)=>u.assetNo==='TRAKMAT2.4X1.1'};
eq(p.read(mat).rows.map(g=>[g.owner,g.quantity,g.quantityOnly]),[['coates',20,true]],'reviewed Trakmat scope is quantity20, not one catalogue asset');has(p.text(mat),/Coates · Trakmat · quantity 20 \(no fleet numbers\)/,'Trakmat presentation uses quantity');eq(p.text(mat).includes('TRAKMAT2.4X1.1'),false,'catalogue product code not shown as fleet identity');
box.assetOf=()=>a;box.gcModel925=()=>({rows});delete box.ItemPhotos965;
const va={key:'T0103'},vr=[{id:'vms9',ref:'T0103',physical:true,item:'VMS',owner:'coates',assetNo:'1211404',label:'VMS09'},{id:'vms10',ref:'T0103',physical:true,item:'VMS',owner:'prem-air-hire',assetNo:'120T',label:'VMS10',registration:'V14221'}],vs=p.project(va,vr,[]);eq(vs.rows.length,2,'two VMS owner groups');has(vs.rows.map(p.words).join('|'),/SUB-HIRED · PremAir Hire · VMS · VMS10 · asset 120T · rego V14221/,'PremAir identity and registration explicit');eq(vs.rows.map(p.words).join('|').includes('sub-17093'),false,'obsolete contract placeholder absent');
has(p.html({...a}),/data-ownership969="WC09"/,'stable selector');box.Units925.company=()=>'<script>unsafe</script>';eq(p.html(a).includes('<script>'),false,'owner text escaped');
console.log(JSON.stringify({author:'Andrew Fisher',passed:count,writes:0}));
