// Author: Andrew Fisher. Fencing evidence remains separate from residual quantities.
'use strict';
const {same,safeURL}=require('./test_linked_oracle844.cjs');
async function nativeFencing844(page,day){return page.evaluate(day=>({day,weeks:DATA.weeks,columns:FCOL,plans:DATA.weeks.filter(w=>w.phase==='Build').map(w=>progSheetOf(w.sheet)).filter(Boolean),records:allDockets().map(d=>({id:String(d.id),date:d.date,week:d.week,usable:!!d.usable,scope:d.scope||'programme',quantities:d.quantities||{},location:String(d.location||'').trim(),status:d.location?fenceAreaDoneAsOf(d.location,day):null,traceKey:window.GC500FencingTrace837?.key(d)||null,papers:[...docketPapersOf(d.id),...docketPapersByName(d)].filter(p=>p&&p.id).map(p=>({id:String(p.id),state:photoFor(p).state,url:photoFor(p).url||null,thumb:photoFor(p).thumb||null}))})),catalogue:gc500FencingTraceCatalogue837(),trace:fenceTraceCurrent837()}),day);}
function assertFencing844(check,label,actual,native){
 const build=new Set(native.weeks.filter(w=>w.phase==='Build').map(w=>w.sheet)),number=q=>q==null||String(q).trim()===''||!Number.isFinite(Number(q))?null:Number(q);
 for(const {id,linked:l} of actual){const c=native.columns.find(c=>c.key===l.typeId),want=native.records.filter(d=>{const q=number(d.quantities[l.typeId]),w=native.weeks.find(w=>w.start&&w.end&&w.start<=d.date&&w.end>=d.date);return d.usable&&/^\d{4}-\d{2}-\d{2}$/.test(d.date||'')&&d.date<=native.day&&build.has(d.week)&&(!w||w.phase==='Build'&&w.sheet===d.week)&&d.scope==='programme'&&q>0&&(c.unit!=='each'||Number.isInteger(q));});
  const quantities=rows=>rows.map(d=>({id:d.id,date:d.date,quantity:Number(d.quantity??d.quantities[l.typeId]),location:d.location}));
  check(label+' '+l.typeId+' linked docket evidence matches the exact Build numerator',l.state==='ready'&&same(quantities(l.dockets),quantities(want))&&l.unit===(c.unit==='hr'?'h':c.unit),{id,expected:quantities(want),actual:quantities(l.dockets)});
  check(label+' '+l.typeId+' residual work is never invented per area or planned section',/not allocated/.test(l.basis)&&l.plannedLocations.every(p=>p.status==='planned-context'&&!Object.hasOwn(p,'left')&&!Object.hasOwn(p,'remaining')&&!Object.hasOwn(p,'done'))&&l.areas.every(a=>!Object.hasOwn(a,'quantity')&&!Object.hasOwn(a,'left')&&!Object.hasOwn(a,'remaining')),{basis:l.basis,areas:l.areas,planned:l.plannedLocations});
  const bad=[];for(const d of l.dockets){const n=want.find(n=>n.id===d.id&&n.date===d.date&&n.location===d.location);if(!n){bad.push(d);continue;}const traced=n.traceKey&&native.records.filter(x=>x.traceKey===n.traceKey).length===1?[...(native.trace.rows||[]),...(native.trace.unmapped||[])].filter(x=>x.key===n.traceKey):[],tr=traced.length===1?traced[0]:null,action=tr?{kind:'fencing-docket',key:n.traceKey}:{kind:'fencing'},allowed=tr?.state==='current'?(native.trace.areas||[]).filter(a=>a.state==='current'&&tr.area_ids.includes(a.id)&&native.catalogue.geometry.filter(g=>g.id===a.geometry_id).length===1):[];if(!same(d.recordAction,action)||!same(d.areas.map(a=>a.id).sort(),allowed.map(a=>a.id).sort())||!same(d.papers.map(p=>p.id).sort(),[...new Set(n.papers.map(p=>p.id))].sort()))bad.push({id:d.id,action:d.recordAction,expectedAction:action,areas:d.areas,allowed,papers:d.papers,nativePapers:n.papers});for(const p of d.papers){const x=n.papers.find(x=>x.id===p.id);if(!x||p.state!==x.state||p.state==='ready'&&(!safeURL(p.url)||p.url!==x.url)||p.state!=='ready'&&p.url)bad.push({id:d.id,paper:p,native:x});}if(d.recordAction.kind==='fencing-docket'&&d.recordAction.key!==n.traceKey)bad.push({id:d.id,action:d.recordAction,expected:n.traceKey});for(const a of d.areas){const tr=(native.trace.areas||[]).find(t=>t.id===a.id&&t.state==='current'),g=(native.catalogue.geometry||[]).find(g=>g.id===a.geometryId);if(!tr||!g||tr.geometry_id!==g.id||a.action.kind!=='fencing-map'||a.action.id!==g.id)bad.push({id:d.id,area:a});}if(d.areaStatus?.done!==n.status?.done)bad.push({id:d.id,areaStatus:d.areaStatus,native:n.status});}
  const expectedPlans=new Map(),seenSheets=new Set();for(const sheet of native.plans){if(seenSheets.has(sheet.sheet))continue;seenSheets.add(sheet.sheet);const plan=sheet.plan_update;if(!plan||!c.programme_type)continue;const sources=native.catalogue.sources.filter(src=>src.sha256.slice(0,16)===plan.sha256_16&&(!plan.sha256||src.sha256===plan.sha256));if(sources.length!==1)continue;const src=sources[0];for(const dated of plan.rows_by_day||[])for(const [i,r] of (dated.rows||[]).entries()){const q=number(r.fields?.[c.programme_type]);if(!(q>0)||c.unit==='each'&&!Number.isInteger(q))continue;const id=src.id+':'+String(r.id||dated.date+':'+(r.page||1)+':'+i);if(!expectedPlans.has(id))expectedPlans.set(id,{id,date:r.date||dated.date||null,location:String(r.location||''),description:String(r.description||''),quantity:q,sourceId:src.id,page:Number(r.page||1)});}}
  const tuple=p=>({id:p.id,date:p.date,location:p.location,description:p.description,quantity:p.quantity,sourceId:p.sourceId,page:p.page}),sort=items=>items.map(tuple).sort((a,b)=>a.id.localeCompare(b.id));check(label+' '+l.typeId+' every source-authored planned location remains context once',same(sort(l.plannedLocations),sort([...expectedPlans.values()])),{expected:sort([...expectedPlans.values()]),actual:sort(l.plannedLocations)});
  for(const p of l.plannedLocations){const src=native.catalogue.sources.find(s=>s.id===p.sourceId);if(!src||p.sourceAction&&(p.sourceAction.kind!=='fencing-source'||p.sourceAction.id!==src.id||p.sourceAction.page!==p.page||p.page>src.pages))bad.push({planned:p});for(const id of p.mapIds)if(!native.catalogue.geometry.some(g=>g.id===id&&g.source_sha256===src.sha256&&g.task_ids.includes(p.id)))bad.push({planned:p,map:id});}
  check(label+' '+l.typeId+' exact source actions current reviewed areas and photo states preserve provenance',!bad.length,bad);
 }
}
module.exports={nativeFencing844,assertFencing844};
