// Author: Andrew Fisher. Independent native links and provenance checks, private evidence only.
'use strict';
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),finite=n=>typeof n==='number'&&Number.isFinite(n);
const safeURL=value=>{if(!value)return false;try{return ['https:','http:'].includes(new URL(value,'https://gc500-production.up.railway.app').protocol)||/^data:image\/(png|jpeg|webp|gif|bmp);base64,/i.test(value);}catch{return false;}};
async function linkedEvidence844(page,day){return page.evaluate(day=>{
 const types=todayTypeMetrics843(day),keys=[...new Set(types.instruments.filter(t=>t.kind==='asset-type').flatMap(t=>t.keys))];
 const native=keys.map(key=>{const a=assetOf(key),d=deliveryOf(key),v=timeline841State(a),drop=dropPhotosOf(key),filed=filedPhotosOf(key),photo=new Map();
  for(const raw of [...drop,...(filed.files||[])])if(raw?.id&&!photo.has(String(raw.id))){const stored=drop.some(x=>String(x.id)===String(raw.id)),p=stored?raw:{id:raw.id,name:raw.name},media=photoFor(p);photo.set(String(p.id),{id:String(p.id),unit:p.unit==null?null:String(p.unit),slot:Number.isInteger(p.slot)?p.slot:null,kind:stored?(DROP_SLOTS[p.slot]?.aerial?'aerial':'drop'):'reference',source:stored?'drop':'filed',media:{state:media.state,url:media.url||null,thumb:media.thumb||null,fileId:media.file?.id||null}});}
  return {key,name:a.name||key,current:{done:!!d.done,state:d.state,recorded:!!d.recorded,where:d.where,stage:v.stage,label:v.label,tone:v.tone,why:v.why},selected:deliveryAsOf(key,day),written:destinationOf(a),route:dest782(a),master:masterLoc(key),masterUnit:masterUnit(key),pin:bestPinFor(a),target:navTargetFor(a),map:mapPlaceFor(a),sheet:mapSheetFor(a),identifierValues:[...unitsOf(key).map(u=>u.asset_no||u.label),...subOf(key).map(u=>u.no),...assetNumbersOf(a)].filter(v=>v!=null&&String(v).trim()&&!/^MISCITEM$/i.test(String(v).trim())).map(v=>String(v).trim()),associations:itemNumbersOf(a),filedState:filed.state,photos:[...photo.values()],numbers:displayNumbers744(a)};
 });
 return {day,types,areas:todayWorkMetrics840(day),summary:todayWorkSummary842(day),native,linked:todayLinkedReferences844(keys,{asOf:day}),byType:types.instruments.filter(t=>t.kind==='asset-type').map(t=>({id:t.id,linked:todayLinkedReferences844(t.keys,{itemName:t.name,asOf:day})})),fences:types.instruments.filter(t=>t.kind==='fence-work').map(t=>({id:t.id,linked:todayLinkedFencing844(t.fenceId,day)})),supplier:todayLinkedToiletSupplier844(),invalid:todayLinkedReferences844(['__qa_unknown_reference844__'],{asOf:day})};
 },day);}
function assertLinked844(check,label,e){
 const source=new Map(e.native.map(r=>[r.key,r])),rows=e.linked.rows;
 check(label+' linked reference coverage contains each native key once',e.linked.ready&&same(rows.map(r=>r.key),e.native.map(r=>r.key))&&new Set(rows.map(r=>r.key)).size===rows.length&&Object.keys(e.linked.rowsByKey).length===rows.length,{expected:e.native.map(r=>r.key),actual:rows.map(r=>r.key)});
 for(const r of rows){const n=source.get(r.key),ph=new Map(n.photos.map(p=>[p.id,p]));
  check(label+' '+r.key+' current status and exact native actions share one record',r.found&&r.current.done===n.current.done&&r.current.state===n.current.state&&r.current.recorded===n.current.recorded&&r.current.stage===n.current.stage&&r.current.label===n.current.label&&r.actions.referenceKey===r.key&&(!r.actions.mapKey||r.actions.mapKey===r.key),{key:r.key,current:r.current,native:n.current,actions:r.actions});
  check(label+' '+r.key+' available photos preserve exact provenance and safe native URLs',new Set(r.photos.map(p=>p.id)).size===r.photos.length&&same(r.photos.map(p=>p.id).sort(),n.photos.map(p=>p.id).sort())&&r.photoCount===r.photos.length&&r.readyPhotoCount===r.photos.filter(p=>p.availability==='ready'&&p.fullSrc).length&&r.photos.every(p=>{const q=ph.get(p.id);return q&&p.availability===q.media.state&&(p.availability==='ready'?(p.src==null&&!q.media.thumb||safeURL(p.src)&&p.src===q.media.thumb)&&safeURL(p.fullSrc)&&p.fullSrc===q.media.url:!p.src&&!p.fullSrc)&&p.unit===q.unit&&p.slot===q.slot&&p.kind===q.kind&&p.source===q.source;}),{key:r.key,photos:r.photos,native:n.photos});
  check(label+' '+r.key+' destination keeps written and routing confidence distinct',r.destination&&typeof r.destination.known==='boolean'&&(!n.route||r.destination.kind===n.route.kind)&&r.destination.approx===!!n.route?.approx&&r.destination.hasMap===!!(n.map||n.sheet)&&(!n.masterUnit||n.pin?.fix?.master&&n.pin.fix.lat===n.masterUnit.ll[0]&&n.pin.fix.lon===n.masterUnit.ll[1])&&(n.route?.kind!=='report'||r.destination.known===false&&/final drop-off/.test(r.destination.text)),{key:r.key,destination:r.destination,native:{written:n.written,route:n.route,master:n.master,masterUnit:n.masterUnit,pin:n.pin,target:n.target}});
  check(label+' '+r.key+' identifiers remain recorded reference context',same(r.identifiers.map(i=>i.value).sort(),[...new Set(n.identifierValues)].sort())&&r.identifiers.every(i=>i.scope==='reference'&&i.itemName===null)&&/which units remain/.test(r.identifierBasis),{key:r.key,ids:r.identifiers,native:n.identifierValues,basis:r.identifierBasis});
 }
 for(const t of e.types.instruments.filter(t=>t.kind==='asset-type')){const linked=e.byType.find(x=>x.id===t.id).linked,left=t.rows.filter(r=>!r.complete||!finite(r.left)||r.left>0),sum=left.reduce((n,r)=>n+(finite(r.left)?r.left:0),0);
  check(label+' '+t.name+' exact type references retain quantity versus reference scope',same(linked.rows.map(r=>r.key),t.keys)&&linked.rows.every(r=>r.actions.referenceKey===r.key&&r.identifiers.every(i=>i.scope==='reference'||i.scope==='native-item-association'&&i.itemName===t.name&&source.get(r.key).associations?.[t.name]?.map(String).includes(i.value)))&&(!finite(t.left)||left.every(r=>finite(r.left))&&Math.abs(sum-t.left)<1e-6),{id:t.id,left:t.left,sum,referenceCount:left.length,keys:linked.rows.map(r=>r.key),unknown:left.filter(r=>!finite(r.left)).map(r=>r.key)});
 }
 check(label+' unknown reference never gains an actionable native key',e.invalid.rows.every(r=>!r.found&&!r.actions?.referenceKey&&!r.actions?.mapKey),e.invalid);
 check(label+' supplier shortcut routes to native plan without quantity ownership',e.supplier.action.kind==='toilet-supplier'&&e.supplier.action.tab==='timeline'&&e.supplier.action.anchor==='ep819'&&!['total','done','left','quantity'].some(k=>Object.hasOwn(e.supplier,k)),e.supplier);
}
module.exports={linkedEvidence844,assertLinked844,same,safeURL,finite};
