/* Author: Andrew Fisher. Synthetic read-only fencing evidence; no private data or network. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync(path.join(__dirname,'linked_fencing844_src.js'),'utf8');
const existing=fs.readFileSync(path.join(__dirname,'../v8.41_timeline_fencing_clarity_LIVE/fencing_metrics841_src.js'),'utf8');
const clone=x=>JSON.parse(JSON.stringify(x)),plain=x=>clone(x),tests=[];
const test=(name,run)=>tests.push({name,run});
const H='a'.repeat(64),M='b'.repeat(64),key=d=>String(d.id)+'|'+String(d.docket_no);
function fixture(change=()=>{}) {
 const data={ready:true,stale:false,records:[{id:'SYN-D1',docket_no:'SYN-101',date:'2026-10-02',week:'Build 1',usable:true,location:'Synthetic north',scope:'programme',quantities:{clean:12.5,v_gates:2,labour:3}}],
  columns:[{key:'clean',unit:'m',programme_type:'Clean'},{key:'v_gates',unit:'each',programme_type:'Vehicle gates'},{key:'scrim',unit:'m',programme_type:'Scrim'},{key:'labour',unit:'hr',programme_type:null},{key:'team_leader',unit:null}],
  weeks:[{sheet:'Build 1',phase:'Build',start:'2026-10-01',end:'2026-10-07'},{sheet:'Build 2',phase:'Build',start:'2026-10-08',end:'2026-10-14'},{sheet:'Event',phase:'Event',start:'2026-10-23',end:'2026-10-25'},{sheet:'Demob',phase:'Demob',start:'2026-10-26',end:'2026-11-01'}],
  plans:{'Build 1':{sheet:'PLAN-1',year:2026,rolled_forward:true,totals:{Clean:100,'Vehicle gates':5,Scrim:20},plan_update:{sha256:H,sha256_16:H.slice(0,16),rows_by_day:[{date:'2026-10-03',rows:[{id:'SYN-T1',location:'Synthetic north',description:'Planned clean work',page:1,fields:{Clean:40,'Vehicle gates':2},requirements:[{text:'Check access',kind:'hold'}],conflicts:['Source quantity review']}]}]}},'Build 2':{sheet:'PLAN-2',year:2026,rolled_forward:true,totals:{Clean:50,'Vehicle gates':1,Scrim:10}}},
  catalogue:{master_sha256:M,sources:[{id:'SYN-SOURCE',sha256:H,pages:2,label:'Synthetic source'}],geometry:[{id:'SYN-G1',task_ids:['SYN-SOURCE:SYN-T1'],source_sha256:H,master_sha256:M,source_page:1,kind:'line',points:[[1,2],[3,4]],region:'main',confidence:'reviewed',alignment:{method:'Synthetic'},category:'clean'}]},
  trace:{rows:[{key:'SYN-D1|SYN-101',state:'current',area_ids:['SYN-A1'],links:[]}],unmapped:[],areas:[{id:'SYN-A1',state:'current',geometry_id:'SYN-G1',label:'Synthetic reviewed area'}]},
  linked:[{id:'SYN-P1',by:'Synthetic operator',at:'2026-10-02'}],named:[{id:'SYN-P1',byName:true},{id:'SYN-P2',byName:true}],
  media:{'SYN-P1':{state:'ready',url:'https://synthetic.invalid/p1',thumb:'https://synthetic.invalid/t1',file:{name:'Signed synthetic docket'}},'SYN-P2':{state:'checking',url:'https://synthetic.invalid/should-not-appear'}},areaDone:true,areaCalls:[]};
 change(data);
 const context=vm.createContext({Date,Map,Set,URL,window:{GC500FencingTrace837:{key}},DATA:{weeks:data.weeks},FCOL:data.columns,todayIso:()=> '2026-10-04',
  todayGroupHealth841:()=>({ready:data.ready,stale:data.stale,basis:'Synthetic shared health'}),todayWorkHealth840:()=>({ready:data.ready,stale:data.stale,basis:'Synthetic shared health'}),
  allDockets:()=>data.records,progSheetOf:week=>data.plans[week],gc500FencingTraceCatalogue837:()=>data.catalogue,fenceTraceCurrent837:()=>data.trace,
  docketPapersOf:()=>data.linked,docketPapersByName:()=>data.named,photoFor:p=>data.media[p.id]||{state:'missing'},photoIndex:()=>({state:'ready'}),
  fenceAreaKey:n=>String(n).trim().toLowerCase().replace(/\s+/g,' '),fenceAreaDoneAsOf:(name,day)=>{data.areaCalls.push({name,day});return {done:data.areaDone&&day>='2026-10-03',by:'Synthetic operator',at:'2026-10-03T00:00:00Z',where:'local'};}});
 vm.runInContext(src+'\n'+existing,context);
 return {data,context,read:(id='clean',day='2026-10-04')=>context.todayLinkedFencing844(id,day)};
}
test('contributing rows reconcile to unchanged native841 scope across all exclusion branches',()=>{
 const f=fixture(d=>{const original=d.records[0];for(const [suffix,props] of Object.entries({future:{date:'2026-10-06'},undated:{date:''},badDate:{date:'yesterday'},unusable:{usable:false},event:{date:'2026-10-23',week:'Event'},demob:{date:'2026-10-26',week:'Demob'},wrongWeek:{week:'Build 2'},notBuild:{week:'Other'},offPlan:{scope:'yard'},zero:{quantities:{clean:0}},negative:{quantities:{clean:-1}},badQty:{quantities:{clean:'unreadable'}}}))d.records.push({...clone(original),id:'SYN-'+suffix,docket_no:suffix,...props});d.records.push({...clone(original),id:'SYN-D2',docket_no:'SYN-102',quantities:{clean:'7.25'}});});
 const r=f.read(),native=f.context.todayFencingSummary841('2026-10-04').summaryRows.find(r=>r.id==='clean');assert.equal(r.dockets.length,2);assert.equal(r.dockets.reduce((n,r)=>n+r.quantity,0),native.recorded);assert.equal(native.recorded,19.75);
});
test('native out-of-calendar dated Build records follow the same841 inclusion instead of guessed dates',()=>{const f=fixture(d=>{d.records[0].date='2026-09-29';});assert.equal(f.read().dockets.length,1);assert.equal(f.context.todayFencingSummary841('2026-10-04').summaryRows[0].recorded,12.5);});
test('encoded type IDs resolve exactly and malformed unknown types fail closed',()=>{const f=fixture();assert.equal(f.read('type843-fence-clean').typeId,'clean');for(const id of ['team_leader','unknown','type843-fence-%E0%A4%A'])assert.equal(f.read(id).state,'unavailable');});
test('missing duplicate or unsupported native columns cannot produce links',()=>{for(const mode of ['missing','duplicate','unit']){const f=fixture(d=>{if(mode==='missing')d.columns=[];if(mode==='duplicate')d.columns.push(clone(d.columns[0]));if(mode==='unit')d.columns[0].unit='unknown';});assert.equal(f.read().state,'unavailable');assert.equal(f.read().dockets.length,0);}});
test('pending hydration yields no speculative records or maps',()=>{const f=fixture(d=>{d.ready=false;});assert.equal(f.read().state,'loading');assert.equal(f.read().dockets.length,0);assert.equal(f.read().plannedLocations.length,0);});
test('integer gates and hour labels stay separate from metres',()=>{const f=fixture(d=>{d.records.push({...clone(d.records[0]),id:'SYN-FRACTION',docket_no:'fraction',quantities:{v_gates:1.5}});});assert.equal(f.read('v_gates').dockets.length,1);assert.equal(f.read('v_gates').unit,'each');assert.equal(f.read('labour').unit,'h');assert.equal(f.read('labour').plannedLocations.length,0);});
test('current reviewed trace gives exact native record and area geometry actions',()=>{const r=fixture().read().dockets[0];assert.deepEqual(plain(r.recordAction),{kind:'fencing-docket',key:'SYN-D1|SYN-101'});assert.deepEqual(plain(r.areas[0].action),{kind:'fencing-map',id:'SYN-G1'});assert.equal(r.location,'Synthetic north');});
test('stale trace retains record route but never publishes a map association',()=>{const f=fixture(d=>{d.trace.rows[0].state='unavailable';d.trace.rows[0].reason='Source changed';});const r=f.read().dockets[0];assert.equal(r.recordAction.kind,'fencing-docket');assert.equal(r.areas.length,0);assert.equal(r.mapState,'needs-review');});
test('explicit native unmapped records retain their exact docket route without becoming stale map claims',()=>{const f=fixture(d=>{d.trace.rows=[];d.trace.unmapped=[{key:'SYN-D1|SYN-101',reason:'Location has not been reviewed'}];});const r=f.read().dockets[0];assert.equal(r.recordAction.kind,'fencing-docket');assert.equal(r.mapState,'unmapped');assert.equal(r.areas.length,0);});
test('missing area or geometry and ambiguous geometry never create map targets',()=>{for(const mode of ['area','geometry','duplicate']){const f=fixture(d=>{if(mode==='area')d.trace.areas[0].state='unavailable';if(mode==='geometry')d.catalogue.geometry=[];if(mode==='duplicate')d.catalogue.geometry.push(clone(d.catalogue.geometry[0]));});assert.equal(f.read().dockets[0].areas.length,0);}});
test('unreviewed or duplicate docket identities use generic Fencing fallback without dropping quantities',()=>{for(const mode of ['unreviewed','duplicate']){const f=fixture(d=>{if(mode==='unreviewed')d.trace.rows=[];else d.records.push(clone(d.records[0]));});const r=f.read();assert.ok(r.dockets.every(row=>row.recordAction.kind==='fencing'));assert.equal(new Set(r.dockets.map(row=>row.key)).size,r.dockets.length);}});
test('native trace failure degrades to sources rather than losing work records',()=>{const f=fixture();f.context.fenceTraceCurrent837=()=>{throw Error('Synthetic unavailable');};const r=f.read();assert.equal(r.dockets.length,1);assert.equal(r.dockets[0].recordAction.kind,'fencing');assert.ok(r.issues.length);});
test('paper pointers deduplicate and retain named match provenance and native registry state',()=>{const r=fixture().read().dockets[0];assert.equal(r.papers.length,2);assert.equal(r.papers[0].name,'Signed synthetic docket');assert.equal(r.papers[0].byName,false);assert.equal(r.papers[1].byName,true);assert.equal(r.papers[1].state,'checking');assert.equal(r.papers[1].url,undefined);});
test('only ready paper results expose URLs or thumbnails',()=>{for(const state of ['checking','unchecked','ambiguous','missing','none']){const f=fixture(d=>{d.media['SYN-P1']={state,url:'https://synthetic.invalid/guess',thumb:'https://synthetic.invalid/guess-thumb'};});const p=f.read().dockets[0].papers[0];assert.equal(p.state,state);assert.equal(p.url,undefined);assert.equal(p.thumb,undefined);}});
test('paper lookup exceptions remain unchecked without a guessed URL',()=>{const f=fixture();f.context.photoFor=()=>{throw Error('Synthetic failure');};assert.equal(f.read().dockets[0].papers[0].state,'unchecked');assert.equal(f.read().dockets[0].papers[0].url,undefined);});
test('unsafe stored ready URLs and source links fail closed',()=>{for(const url of ['javascript:alert(1)','data:text/html,unsafe','java\tscript:alert(1)','file:///private','https://user:pass@synthetic.invalid/a']){const f=fixture(d=>{d.media['SYN-P1'].url=url;d.trace.rows[0].links=[{url,label:'Unsafe'}];});const r=f.read().dockets[0];assert.equal(r.papers[0].state,'unavailable');assert.equal(r.papers[0].url,undefined);assert.equal(r.sourceLinks.length,0);}});
test('native HTTP and relative source URLs remain usable and thumbnails permit only raster data images',()=>{const f=fixture(d=>{d.media['SYN-P1'].url='/files/synthetic';d.media['SYN-P1'].thumb='data:image/png;base64,YQ==';d.trace.rows[0].links=[{url:'../sources/synthetic.pdf',label:'Source'}];});let r=f.read().dockets[0];assert.equal(r.papers[0].url,'/files/synthetic');assert.equal(r.papers[0].thumb,'data:image/png;base64,YQ==');assert.equal(r.sourceLinks.length,1);f.data.media['SYN-P1'].thumb='data:image/svg+xml,<svg/>';r=f.read().dockets[0];assert.equal(r.papers[0].thumb,undefined);});
test('empty paper list distinguishes a cold or failed registry from checked absence',()=>{for(const [native,expected] of [['loading','checking'],['failed','unchecked'],['none','unavailable'],['ready','ready']]){const f=fixture(d=>{d.linked=[];d.named=[];});f.context.photoIndex=()=>({state:native});const r=f.read().dockets[0];assert.equal(r.papers.length,0);assert.equal(r.papersState,expected);}});
test('past area checklist uses selected-day native signoff rather than current completion',()=>{const f=fixture();const r=f.read('clean','2026-10-02');assert.equal(r.areas[0].status.done,false);assert.equal(r.dockets[0].areaStatus.done,false);assert.ok(f.data.areaCalls.every(c=>c.day==='2026-10-02'));});
test('area tick never changes contributing quantities or manufactures a per-area residual',()=>{const f=fixture();const before=f.read();f.data.areaDone=false;const after=f.read();assert.equal(before.dockets[0].quantity,after.dockets[0].quantity);for(const r of [...before.areas,...before.plannedLocations])for(const field of ['left','remaining','doneQuantity','pct'])assert.equal(field in r,false);assert.match(before.basis,/not allocated/);});
test('future planned locations stay planned context with source and prerequisite warnings',()=>{const f=fixture(d=>{d.plans['Build 1'].plan_update.rows_by_day[0].date='2026-10-06';});const r=f.read().plannedLocations[0];assert.equal(r.date,'2026-10-06');assert.equal(r.status,'planned-context');assert.equal(r.quantity,40);assert.equal(r.requirements[0].kind,'hold');assert.equal(r.conflicts.length,1);assert.deepEqual(plain(r.sourceAction),{kind:'fencing-source',id:'SYN-SOURCE',page:1});assert.deepEqual(plain(r.mapIds),['SYN-G1']);});
test('planned type matching is exact and never uses description words',()=>{const f=fixture(d=>{d.plans['Build 1'].plan_update.rows_by_day[0].rows[0].description='clean clean scrim';});assert.equal(f.read('scrim').plannedLocations.length,0);assert.equal(f.read('v_gates').plannedLocations[0].quantity,2);});
test('native conflict IDs resolve to the same source plan details and retain simultaneous notes',()=>{const f=fixture(d=>{const p=d.plans['Build 1'].plan_update,r=p.rows_by_day[0].rows[0];r.conflicts=['synthetic-conflict','missing-id'];p.conflicts=[{id:'synthetic-conflict',description:'Synthetic gate discrepancy',summary:'2 gates',detail:'3 gates',state:'awaiting confirmation'}];r.note='First note';r.comment='Second note';r.flag='Third note';});const r=f.read().plannedLocations[0];for(const word of ['Synthetic gate discrepancy','2 gates','3 gates','awaiting confirmation'])assert.ok(r.conflicts[0].includes(word));assert.match(r.conflicts[1],/details unavailable/);for(const word of ['First note','Second note','Third note'])assert.ok(r.note.includes(word));});
test('changed or ambiguous source revisions suppress source and geometry claims',()=>{for(const mode of ['changed','duplicate']){const f=fixture(d=>{if(mode==='changed')d.plans['Build 1'].plan_update.sha256='c'.repeat(64);else d.catalogue.sources.push(clone(d.catalogue.sources[0]));});assert.equal(f.read().plannedLocations.length,0);assert.ok(f.read().issues.length);}});
test('bad source page remains explicit context without an opening action',()=>{const f=fixture(d=>{d.plans['Build 1'].plan_update.rows_by_day[0].rows[0].page=3;});const r=f.read().plannedLocations[0];assert.equal(r.sourceAction,null);assert.equal(r.mapIds.length,0);});
test('geometry never crosses master/source/task boundaries or invalid drawing coordinates',()=>{for(const field of ['master','source','task','points','category']){const f=fixture(d=>{const g=d.catalogue.geometry[0];if(field==='master')g.master_sha256='c'.repeat(64);if(field==='source')g.source_sha256='c'.repeat(64);if(field==='task')g.task_ids=['other'];if(field==='points')g.points=[[99999,2],[3,4]];if(field==='category')g.category='invented';});assert.equal(f.read().plannedLocations[0].mapIds.length,0);}});
test('unmapped planned source rows retain location and source context',()=>{const f=fixture(d=>{d.catalogue.geometry=[];});const r=f.read().plannedLocations[0];assert.equal(r.location,'Synthetic north');assert.equal(r.mapIds.length,0);assert.equal(r.sourceAction.kind,'fencing-source');});
test('duplicate source-sheet/task identities do not double-list planned locations',()=>{const f=fixture(d=>{d.plans['Build 2']=d.plans['Build 1'];d.plans['Build 1'].plan_update.rows_by_day.push(clone(d.plans['Build 1'].plan_update.rows_by_day[0]));});assert.equal(f.read().plannedLocations.length,1);});
test('malformed optional source notes cannot crash the evidence sidecar',()=>{const f=fixture(d=>{const p=d.plans['Build 1'].plan_update;p.rows_by_day.push(null);p.rows_by_day[0].rows.push(null);p.rows_by_day[0].rows[0].requirements=[null,'bad',{text:'Hold',kind:'hold'}];p.rows_by_day[0].rows[0].conflicts=[null,'Review'];});assert.equal(f.read().plannedLocations[0].requirements.length,1);});
test('offline provenance remains explicit and stable rows survive record reordering',()=>{const f=fixture(d=>{d.stale=true;d.records.push({...clone(d.records[0]),id:'SYN-D2',docket_no:'SYN-102'});});const before=f.read();f.data.records.reverse();const after=f.read();assert.equal(before.dockets[0].key,after.dockets[1].key);assert.ok(after.issues.some(x=>x.includes('Synthetic shared health')));});
test('read-only evidence calls do not mutate source records or source geometry',()=>{const f=fixture(),before=JSON.stringify({records:f.data.records,plans:f.data.plans,catalogue:f.data.catalogue,trace:f.data.trace});f.read();assert.equal(JSON.stringify({records:f.data.records,plans:f.data.plans,catalogue:f.data.catalogue,trace:f.data.trace}),before);});
test('supplier-unallocated shortcut is only the existing native route and includes no quantities',()=>{const f=fixture(),r=f.context.todayLinkedToiletSupplier844();assert.deepEqual(plain(r.action),{kind:'toilet-supplier',tab:'timeline',anchor:'ep819',heading:'ep819h'});assert.match(r.basis,/separate from reference completion/);for(const name of ['total','done','left','rows','refs'])assert.equal(name in r,false);});
let passed=0;const failures=[];for(const t of tests){try{t.run();passed++;console.log('PASS '+t.name);}catch(error){failures.push({name:t.name,error:error.message});console.error('FAIL '+t.name+': '+error.stack);}}console.log(JSON.stringify({author:'Andrew Fisher',passed,total:tests.length,failures}));process.exitCode=failures.length?1:0;
