/* Author: Andrew Fisher. Native navigation, phone and day-page rendering; no writes. */
const fs=require('fs'),path=require('path'),assert=require('assert');const{open}=require('../toolchain/harness/open_page');const{chromium}=require('playwright');const out=process.env.EVIDENCE||'/workspace/private-v821-browser';fs.mkdirSync(out,{recursive:true});
(async()=>{const h=await open({pageFile:process.env.PAGE||path.resolve(__dirname,'../build/GC500_v8.21/GC500_Delivery_Control_hosted.html'),hash:'#timeline',W:1440,H:1100});const checks=[];try{const p=h.page;await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length);await p.evaluate(()=>{state.day='2026-10-07';state.tlView='day';renderTimeline();});
 await p.locator('.dplate [data-daily821-toggle="2026-10-07"]').click();assert(await p.locator('[data-daily821-panel="2026-10-07"]').isVisible());checks.push('Native Timeline message button opens selected day panel');
 const persons=await p.evaluate(()=>daily821Contacts());await p.selectOption('[data-daily821-recipient="2026-10-07"]',persons[0].id);const popPromise=p.waitForEvent('popup');await p.click('[data-daily821-preview="2026-10-07"]');const pop=await popPromise;await pop.waitForLoadState();await pop.waitForFunction(()=>document.title.includes('Daily deliveries'));assert((await pop.locator('h1').textContent()).includes('07 Oct'));checks.push('Actual Preview button opens its own selected-day HTML page');
 assert(await p.locator('[data-daily821-send="2026-10-07"]').isDisabled());checks.push('Native view link preview cannot send');
 const hrefs=await pop.locator('a[href]').evaluateAll(a=>a.map(x=>x.getAttribute('href')));assert(hrefs.every(x=>x==='#deliveries'||x.startsWith('https://www.google.com/maps/')));checks.push('Installer HTML links only to its own anchor or Google Maps');
 for(const width of[1440,390,320]){await p.setViewportSize({width,height:1000});await p.waitForTimeout(100);await p.locator('.ldlist .ldl').first().click();assert(await p.locator('.daily821-load-message .ld-txt').count());await p.locator('.ldlist .ldl').first().click();await p.evaluate(()=>renderTimeline());assert(await p.locator('[data-daily821-panel="2026-10-07"]').isVisible());assert.equal(await p.locator('[data-daily821-recipient="2026-10-07"]').inputValue(),persons[0].id);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push('Native load open/close and sync redraw preserve panel without overflow '+width);await p.locator('.dplate').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'timeline-actions-'+width+'.png')});await p.locator('.daily821-panel').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'timeline-native-'+width+'.png')});
  await pop.setViewportSize({width:width===1440?1100:width,height:1000});await pop.locator('details').first().evaluate(n=>n.open=true);assert(await pop.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push('Day HTML expanded notes remain in viewport '+width);await pop.screenshot({path:path.join(out,'installer-native-'+width+'.png'),fullPage:false});}
 await p.click('[data-daily821-close="2026-10-07"]');assert(!await p.locator('[data-daily821-panel="2026-10-07"]').isVisible());checks.push('Native Close folds panel');
 assert.equal(h.errors.length,0);assert.equal(h.counts.blocked,0);checks.push('No page errors or attempted live writes');fs.writeFileSync(path.join(out,'visual-report.json'),JSON.stringify({author:'Andrew Fisher',checks,passed:checks.length,errors:h.errors,counts:h.counts},null,2));console.log(JSON.stringify({passed:checks.length,errors:h.errors,counts:h.counts}));}finally{await h.browser.close();}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
