// Author: Andrew Fisher. v9.16 showcase audit, M2: turns the measure_showcase.cjs JSON files into one summary.
//   node tests/summarize_m2.cjs <evidence dir holding the run JSON> <out.md> [<out.json>]
// Wall fps is relative only (software GL, shared CPU); the device-independent columns come first.
const fs = require('fs'), path = require('path');
const dir = process.argv[2], outMd = process.argv[3], outJson = process.argv[4];
const runs = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort().map(f => { try { return Object.assign({file: f}, JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'))); } catch (e) { return null; } }).filter(Boolean);
const pct = (a, q) => { a = a.filter(x => x != null); if (!a.length) return null; const s = a.slice().sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(q * (s.length - 1) + 0.5))]; };
const n0 = x => x == null ? '—' : (Math.abs(x) >= 100 ? Math.round(x).toLocaleString('en-AU') : String(Math.round(x * 10) / 10));
const kb = x => x == null ? '—' : x >= 1048576 ? (x / 1048576).toFixed(1) + ' MB' : x >= 1024 ? (x / 1024).toFixed(0) + ' KB' : x + ' B';
const L = [], J = {runs: []};
L.push('# v9.16 Showcase audit · M2 measurement summary', '', 'Author: Andrew Fisher · generated by tests/summarize_m2.cjs from evidence/m2/*.json', '',
  'Headless Chromium 141 with SwiftShader software GL (no GPU) on a shared 4-core container. **Wall fps and frame intervals are relative only** and are never a real-device figure. ' +
  'Device-independent columns (draw calls, vertices, upload bytes, shader compiles, heap, contexts, timers, audio nodes) are what the page asks of any device. ' +
  'Laptop = 1440x900, CPU throttle 1; phone = 390x844, DPR 3, touch, CPU throttle 4 (applied after load).', '');
for (const r of runs) {
  const ph = r.phases || [];
  J.runs.push({file: r.file, tag: r.tag, profile: r.profile, dpr: r.dpr, script: r.script, blocked: r.counts && r.counts.blocked, error: r.error || null, phases: ph.map(p => p.summary), snapshots: (r.snapshots || []).map(s => ({label: s.label, heapUsedMB: s.heapUsedMB, nodes: s.nodes, listeners: s.listeners, glAlive: s.state && s.state.webgl && s.state.webgl.alive, glMade: s.state && s.state.webgl && s.state.webgl.made, audio: s.state && s.state.audio && s.state.audio.list.map(a => a.state), intervals: s.state && s.state.intervals && s.state.intervals.live, timeouts: s.state && s.state.timeouts && s.state.timeouts.pending})), watch: r.watch});
}
// ---------- per run, per phase
L.push('## 1. Every run, every phase', '');
L.push('| run | phase | s | frames | JS ms/frame med / p95 | script ex-GL med / p95 | GL-call ms p95 | sync-read ms p95 | draws/frame med | vertices/frame med / p95 | buffer upload/frame med | tex upload total | shader compiles | long tasks n / max ms | main-thread busy % | heap end MB | fps (relative) |');
L.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const r of runs) for (const p of (r.phases || [])) { const s = p.summary;
  L.push(`| ${r.tag} | ${s.phase} | ${n0(s.durS)} | ${s.frames} | ${n0(s.jsMsPerFrame.med)} / ${n0(s.jsMsPerFrame.p95)} | ${n0(s.scriptMsExGlPerFrame.med)} / ${n0(s.scriptMsExGlPerFrame.p95)} | ${n0(s.glCallMsPerFrame.p95)} | ${n0(s.syncReadMsPerFrame.p95)} | ${n0(s.drawsPerFrame.med)} | ${n0(s.vertsPerFrame.med)} / ${n0(s.vertsPerFrame.p95)} | ${kb(s.bufBytesPerFrame.med)} | ${kb(s.texBytesTotal)} | ${s.shaderCompiles} | ${s.longTasks.n} / ${n0(s.longTasks.maxMs)} | ${n0(s.cdp && s.cdp.mainThreadBusyPct)} | ${n0(s.cdp && s.cdp.heapEndMB)} | ${n0(s.fpsWallRelative)} |`); }
L.push('');
// ---------- idle repeats
const idle = runs.filter(r => r.script === 'idle');
if (idle.length) {
  L.push('## 2. Idle, Showcase open 90 s: repeats (median and spread)', '');
  L.push('| profile | repeats | frames med (min–max) | JS ms/frame med of medians | JS ms/frame p95 max | draws/frame | vertices/frame med | busy % med (min–max) | long tasks med | longest task ms max | step-downs med | heap open-end MB med | heap after close+GC MB med |');
  L.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|');
  const groups = {}; for (const r of idle) { const k = r.profile + ' DPR ' + r.dpr; (groups[k] = groups[k] || []).push(r); }
  for (const [k, rs] of Object.entries(groups)) {
    const op = rs.map(r => (r.phases || []).find(p => p.summary.phase === 'open')).filter(Boolean).map(p => p.summary);
    const fr = op.map(s => s.frames), busy = op.map(s => s.cdp.mainThreadBusyPct);
    const sd = rs.map(r => (r.watch && r.watch.stepDowns || []).length);
    const heapOpen = rs.map(r => ((r.snapshots || []).find(s => s.label === 'open-end') || {}).heapUsedMB), heapAfter = rs.map(r => ((r.snapshots || []).find(s => s.label === 'after-end') || {}).heapUsedMB);
    L.push(`| ${k} | ${rs.length} | ${n0(pct(fr, .5))} (${Math.min(...fr)}–${Math.max(...fr)}) | ${n0(pct(op.map(s => s.jsMsPerFrame.med), .5))} | ${n0(Math.max(...op.map(s => s.jsMsPerFrame.p95 || 0)))} | ${n0(pct(op.map(s => s.drawsPerFrame.med), .5))} | ${n0(pct(op.map(s => s.vertsPerFrame.med), .5))} | ${n0(pct(busy, .5))} (${n0(Math.min(...busy))}–${n0(Math.max(...busy))}) | ${n0(pct(op.map(s => s.longTasks.n), .5))} | ${n0(Math.max(...op.map(s => s.longTasks.maxMs)))} | ${n0(pct(sd, .5))} | ${n0(pct(heapOpen, .5))} | ${n0(pct(heapAfter, .5))} |`);
  }
  L.push('');
}
// ---------- before / after
L.push('## 3. Does the Showcase leave work running? (before it opens vs after Back)', '');
L.push('| run | phase | rAF frames | rAF callback ms total | timer ms total | timer calls | busy % | live intervals at end | pending timeouts at end | GL contexts alive | AudioContexts (state) | heap MB (after GC) | DOM nodes | listeners |');
L.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const r of runs) for (const ph of ['before', 'after']) { const p = (r.phases || []).find(x => x.summary.phase === ph); if (!p) continue; const s = p.summary;
  const sn = (r.snapshots || []).find(x => x.label === (ph === 'before' ? 'before-end' : 'after-end')) || {}; const st = sn.state || {};
  L.push(`| ${r.tag} | ${ph} | ${s.frames} | ${n0(s.rafMsTotal)} | ${n0(s.timerMsTotal)} | ${s.timerCalls} | ${n0(s.cdp.mainThreadBusyPct)} | ${st.intervals ? st.intervals.live : '—'} | ${st.timeouts ? st.timeouts.pending : '—'} | ${st.webgl ? st.webgl.alive + ' of ' + st.webgl.made : '—'} | ${st.audio ? (st.audio.list.map(a => a.state).join(', ') || 'none') : '—'} | ${n0(sn.heapUsedMB)} | ${sn.nodes || '—'} | ${sn.listeners || '—'} |`); }
L.push('');
// ---------- reopen10
for (const r of runs.filter(r => r.script === 'reopen10')) {
  L.push(`## 4. Open / close 10 times: ${r.tag} (forced GC before each reading)`, '');
  L.push('| reading | heap MB | DOM nodes | JS listeners | GL contexts made / alive | AudioContexts made (states) | live intervals | pending timeouts | window/document listeners |');
  L.push('|---|---|---|---|---|---|---|---|---|');
  for (const sn of (r.snapshots || [])) { const st = sn.state || {};
    const wl = st.listeners ? Object.entries(st.listeners).filter(([, v]) => v > 0).reduce((a, [, v]) => a + v, 0) : '—';
    L.push(`| ${sn.label} | ${n0(sn.heapUsedMB)} | ${sn.nodes} | ${sn.listeners} | ${st.webgl ? st.webgl.made + ' / ' + st.webgl.alive : '—'} | ${st.audio ? st.audio.made + ' (' + st.audio.list.map(a => a.state).join(', ') + ')' : '—'} | ${st.intervals ? st.intervals.live : '—'} | ${st.timeouts ? st.timeouts.pending : '—'} | ${wl} |`); }
  const cyc = (r.snapshots || []).filter(s => /^reopen\.\d+\.closed/.test(s.label)).map(s => s.heapUsedMB);
  if (cyc.length > 2) { const n = cyc.length, xs = cyc.map((_, i) => i + 1), mx = (n + 1) / 2, my = cyc.reduce((a, b) => a + b, 0) / n;
    const slope = xs.reduce((a, x, i) => a + (x - mx) * (cyc[i] - my), 0) / xs.reduce((a, x) => a + (x - mx) ** 2, 0);
    L.push('', `Heap after close + GC, cycles 1–${n}: ${cyc.map(n0).join(', ')} MB; least-squares slope ${slope.toFixed(2)} MB per open/close; first-to-last change ${n0(cyc[n - 1] - cyc[0])} MB.`); }
  const ph = (r.phases || []).filter(p => /^reopen\.\d+$/.test(p.summary.phase)).map(p => p.summary);
  if (ph.length) L.push('', 'Per open (8 s): audio nodes created ' + ph.map(s => s.audio.nodes).join(', ') + '; connects ' + ph.map(s => s.audio.connect).join(', ') + '; disconnects ' + ph.map(s => s.audio.disconnect).join(', ') +
    '; AudioContexts made ' + ph.map(s => s.audio.ctxMade).join(', ') + '; WebGL contexts made ' + ph.map(s => s.gl.ctxMade).join(', ') + '; buffer bytes uploaded ' + ph.map(s => kb(s.bufBytesTotal)).join(', ') + '; shader compiles ' + ph.map(s => s.shaderCompiles).join(', ') + '.');
  const cl = (r.phases || []).filter(p => /^reopen\.\d+\.close$/.test(p.summary.phase)).map(p => p.summary);
  if (cl.length) L.push('', 'Each Back press (close phase): longest task ms ' + cl.map(s => n0(s.longTasks.maxMs)).join(', ') + '; loseContext() calls ' + cl.map(s => s.gl.loseContextCalls).join(', ') + '; AudioContext.close() ' + cl.map(s => s.audio.ctxClosed).join(', ') + '.');
  L.push('');
}
// ---------- watchdog
L.push('## 5. The frame-rate guard: every step down and every hand-back', '');
L.push('| run | step-downs (phase @ s into phase: rung, the stalled frame ms) | GC3D.failed set | #show3dNote shown | watchdog revivals |'); L.push('|---|---|---|---|---|');
for (const r of runs) { const w = r.watch || {}; const sd = (w.stepDowns || []);
  const fail = (w.trips || []).filter(t => t.failed && t.failed !== 'no GC3D'); const note = (w.trips || []).filter(t => t.note);
  const rev = Math.max(0, ...((w.trips || []).map(t => t.revived || 0)));
  L.push(`| ${r.tag} | ${sd.length ? sd.map(x => `${x.phase} @${n0(x.phaseAt / 1000)}: ${x.rung} (${x.stalledAt || '—'} ms)`).join('; ') : 'none'} | ${fail.length ? fail.map(t => `${t.phase} @${n0(t.phaseAt / 1000)} s: ${t.failed}`).slice(0, 3).join('; ') : 'no'} | ${note.length ? `${note[0].phase} @${n0(note[0].phaseAt / 1000)} s: "${note[0].note}"` : 'no'} | ${rev} |`); }
L.push('');
// ---------- demo detail
for (const r of runs.filter(r => r.script === 'demo')) {
  L.push(`## 6. The show-someone path: ${r.tag}`, '');
  L.push('| phase | frames | JS ms/frame med / max | draws med | vertices/frame med | buffer upload total | tex upload total | tex alloc | compiles | long tasks n / max ms | audio nodes / connect / disconnect | AudioContexts made | media play / waiting / stalled / error |');
  L.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|');
  for (const p of (r.phases || [])) { const s = p.summary;
    L.push(`| ${s.phase} | ${s.frames} | ${n0(s.jsMsPerFrame.med)} / ${n0(s.jsMsPerFrame.max)} | ${n0(s.drawsPerFrame.med)} | ${n0(s.vertsPerFrame.med)} | ${kb(s.bufBytesTotal)} | ${kb(s.texBytesTotal)} | ${kb(s.texAllocBytes)} | ${s.shaderCompiles} | ${s.longTasks.n} / ${n0(s.longTasks.maxMs)} | ${s.audio.nodes} / ${s.audio.connect} / ${s.audio.disconnect} | ${s.audio.ctxMade} | ${s.media.play} / ${s.media.waiting} / ${s.media.stalled} / ${s.media.error} |`); }
  L.push('');
  const vb = (r.phases || []).map(p => p.summary).find(s => s.vertsByProgram && s.vertsByProgram.length);
  if (vb) { L.push(`Vertices per frame by shader program (frames captured draw by draw in ${vb.phase}):`, '', '| program | draws/frame | vertices/frame | instances/frame | vertex inputs |', '|---|---|---|---|---|');
    for (const x of vb.vertsByProgram) L.push(`| ${x.program} | ${x.drawsPerFrame} | ${n0(x.vertsPerFrame)} | ${n0(x.instancesPerFrame)} | ${x.vs || ''} |`); L.push(''); }
  for (const p of (r.phases || [])) { const s = p.summary; if (!s.cpuProfile || !s.cpuProfile.top.length) continue;
    if (!/settle|vehicle\.(forklift|car_vms)|close|broadcast|machine/.test(s.phase)) continue;
    L.push(`CPU profile, ${s.phase} (${n0(s.cpuProfile.sampledMs)} ms sampled), top self time: ` + s.cpuProfile.top.slice(0, 8).map(t => `${t.fn} ${n0(t.selfMs)} ms (${t.pct}%)`).join('; ') + '.', ''); }
  if (r.machineState) L.push('Machine frame at its 20 s mark: ' + JSON.stringify({webgl: r.machineState.webgl && {made: r.machineState.webgl.made, alive: r.machineState.webgl.alive}, audio: r.machineState.audio && r.machineState.audio.made, intervals: r.machineState.intervals && r.machineState.intervals.live, dom: r.machineState.dom}), '');
  const acts = (r.actions || []).filter(a => a.machineRadio || a.broadcast || a.sound || a.openShowcase || a.vehicle); L.push('Actions: ' + acts.map(a => JSON.stringify(a)).join(' '), '');
}
// ---------- the page underneath: timer callbacks that block for 100 ms or more, whatever the phase
L.push('## 8. Timer callbacks of 100 ms or more (the page under the Showcase included)', '', '| run | timer (label = function name or its first 60 characters) | phases | calls | total ms | longest ms |', '|---|---|---|---|---|---|');
for (const r of runs) { const agg = {};
  for (const p of (r.phases || [])) for (const [k, v] of Object.entries(p.raw.timerBy || {})) { if (v.max < 100) continue; const a = agg[k] || (agg[k] = {phases: [], n: 0, ms: 0, max: 0}); a.phases.push(p.summary.phase); a.n += v.n; a.ms += v.ms; a.max = Math.max(a.max, v.max); }
  for (const [k, a] of Object.entries(agg).sort((x, y) => y[1].max - x[1].max).slice(0, 6)) L.push(`| ${r.tag} | ${k.replace(/\|/g, '/').slice(0, 80)} | ${[...new Set(a.phases)].slice(0, 4).join(', ')}${a.phases.length > 4 ? ' …' : ''} | ${a.n} | ${n0(a.ms)} | ${n0(a.max)} |`); }
L.push('');
L.push('## 7. Run integrity', '', '| run | load s | WebGL renderer | blocked writes | page errors | console errors/warnings | error |', '|---|---|---|---|---|---|---|');
for (const r of runs) L.push(`| ${r.tag} | ${n0(r.loadS)} | ${(r.env && r.env.renderer || '').slice(0, 40)} | ${r.counts ? r.counts.blocked : '—'} | ${(r.pageErrors || []).length} | ${r.consoleCount || 0} | ${r.error ? String(r.error).slice(0, 80) : ''} |`);
fs.writeFileSync(outMd, L.join('\n') + '\n');
if (outJson) fs.writeFileSync(outJson, JSON.stringify(J, null, 1));
console.log('summary', outMd, runs.length, 'runs');
