// Author: Andrew Fisher. Focused read-only type-instrument integration checks.
// PAGE/OUT/CANDIDATE_SHA required; LIVE=1 forbids local HTML substitution.
// INITIAL_ONLY=1 checks the public model, visible instruments and responsive layout.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {installWriteGuard,ready840,nativeSnapshot}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const oracle=require('./test_type_oracle843.cjs'),ui=require('./test_type_ui843.cjs');
const {exerciseFront842}=require('../v8.42_today_plan_clarity_LIVE/test_front842.cjs');
const {open}=require('../toolchain/harness/open_page.js');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
async function motion843(page){return page.evaluate(()=>{
 const b=document.querySelector('#gc500-work-board840');
 if(!b)return {report:TodayWork840.report(),native:window.TodayMotion820?.report?.(),visible:[],animations:[],activeParents:[],activeTypes:[]};
 const m=document.querySelector('main').getBoundingClientRect(),nav=b.querySelector('.tw840-nav').getBoundingClientRect(),top=Math.max(0,m.top,nav.top<m.bottom&&nav.bottom>m.top?nav.bottom:0),visible=n=>{const r=n.getBoundingClientRect();return r.width>0&&r.height>0&&r.bottom>top&&r.top<Math.min(innerHeight,m.bottom)&&r.right>m.left&&r.left<m.right;};
 return {report:TodayWork840.report(),native:window.TodayMotion820?.report?.(),visible:[...b.querySelectorAll('.tw841-motion-track,[data-tw843-type-id] .tw843-leds')].filter(visible).map(n=>n.closest('[data-tw843-type-id]')?'type:'+n.closest('[data-tw843-type-id]').dataset.tw843TypeId:'parent:'+n.closest('[data-tw840-area]').dataset.tw840Area),animations:document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.target instanceof Element&&a.effect.target.closest('#gc500-work-board840')&&a.animationName!=='gc-lit').map(a=>{const t=a.effect.target,mini=t.closest('[data-tw843-type-id]');return {name:a.animationName,id:mini?'type:'+mini.dataset.tw843TypeId:'parent:'+t.closest('[data-tw840-area]')?.dataset.tw840Area,element:t.className,pseudo:a.effect.pseudoElement};}),activeParents:[...b.querySelectorAll('.tw840-running')].map(n=>n.dataset.tw840Area),activeTypes:[...b.querySelectorAll('.tw843-running')].map(n=>n.dataset.tw843TypeId)};
 });}
const active=s=>{const t=s.report.runningInstrument,id=t?(t.kind==='type'?'type:':'parent:')+t.id:null,ids=[...new Set(s.animations.map(a=>a.id))];return !!id&&s.visible.includes(id)&&ids.length===1&&ids[0]===id&&!s.native?.running;};
const stopped=s=>!s.report.running&&!s.report.runningInstrument&&!s.animations.length&&!s.activeParents.length&&!s.activeTypes.length;
async function revealBar(page,id){await page.evaluate(id=>{const n=[...document.querySelectorAll('[data-tw843-type-id]')].find(n=>n.dataset.tw843TypeId===id),bar=n.querySelector('.tw843-leds'),m=document.querySelector('main'),nav=document.querySelector('.tw840-nav');m.scrollTop+=bar.getBoundingClientRect().top-m.getBoundingClientRect().top-nav.getBoundingClientRect().height-30;},id);await page.waitForTimeout(200);}
async function screenshots(page,model,label,out){
 for(const card of ['buildings','toilets','equipment','fencing']){const types=model.byCard[card],type=types.find(t=>card!=='equipment'||t.groupId==='Forklifts & access')||types[0];if(!type)continue;await page.locator('[data-tw843-type-id='+JSON.stringify(type.id)+']').scrollIntoViewIfNeeded();await page.waitForTimeout(80);await page.screenshot({path:path.join(out,'types843-'+label+'-'+card+'.png')});}
}
async function exerciseMotion(page,check,label,model){
 const first=model.instruments.find(t=>t.cardId==='buildings'&&t.kind==='asset-type');await page.locator('[data-tw840-jump=buildings]').click();await page.waitForTimeout(180);let s=await motion843(page);check(label+' automatic motion starts on one visible main or type instrument',active(s),s);
 await revealBar(page,first.id);s=await motion843(page);check(label+' scrolling past a main display hands motion to one visible subtype',active(s)&&s.report.runningInstrument?.kind==='type'&&!s.activeParents.length&&s.activeTypes.length===1,s);
 const parent=s.report.running;await page.evaluate(id=>document.querySelector('[data-tw840-motion='+id+']').click(),parent);await page.waitForTimeout(100);check(label+' parent Pause also stops the selected subtype sheen',stopped(await motion843(page)),await motion843(page));
 await page.evaluate(()=>renderToday());await page.waitForTimeout(300);check(label+' manual pause survives redraw without resurrecting subtype motion',stopped(await motion843(page)),await motion843(page));
 await page.evaluate(id=>document.querySelector('[data-tw840-motion='+id+']').click(),parent);await page.waitForTimeout(150);check(label+' Play resumes one visible subtype',active(await motion843(page)),await motion843(page));
 await page.evaluate(()=>{localStorage.setItem('gc500.motion','off');motionApply();});await page.waitForTimeout(80);check(label+' global Motion Off stops all parent and subtype effects',stopped(await motion843(page)),await motion843(page));await page.evaluate(()=>{localStorage.setItem('gc500.motion','subtle');motionApply();});await page.waitForTimeout(100);
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(100);check(label+' reduced motion stops all subtype effects',stopped(await motion843(page)),await motion843(page));await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForTimeout(100);check(label+' normal motion resumes exactly one visible effect',active(await motion843(page)),await motion843(page));
 const button=page.locator('[data-tw843-type-detail='+JSON.stringify(first.id)+'][data-tw843-type-mode=total]');await button.click();await page.waitForTimeout(100);check(label+' exact type details suspend parent subtype and Programme motion',stopped(await motion843(page))&&!((await motion843(page)).native?.running),await motion843(page));await page.evaluate(()=>{window.__qaClosed843=false;document.querySelector('#gc500-work-dialog840').addEventListener('close',()=>{window.__qaClosed843=true;},{once:true});});await page.keyboard.press('Escape');await page.waitForFunction(()=>__qaClosed843);await revealBar(page,first.id);check(label+' closing exact type details resumes a visible subtype',active(await motion843(page)),await motion843(page));
 await page.locator('#pane-today .racecard').scrollIntoViewIfNeeded();await page.waitForTimeout(100);await page.locator('#pane-today .racecard .today-motion-button').click();await page.waitForTimeout(100);s=await motion843(page);check(label+' native Programme retains exclusive animation ownership',stopped(s)&&s.native?.running==='programme',s);await page.locator('#pane-today .racecard .today-motion-button').click();
 await page.evaluate(()=>go('timeline'));await page.waitForTimeout(100);check(label+' leaving Today stops subtype effects',stopped(await motion843(page)),await motion843(page));await page.evaluate(()=>go('today'));await page.waitForFunction(()=>TodayWork840.report().typesMerged);await revealBar(page,first.id);check(label+' returning to Today resumes only one visible instrument',active(await motion843(page)),await motion843(page));
}
async function exerciseRefresh(page,check,label,model){
 const t=model.instruments.filter(t=>t.kind==='asset-type').at(-1),button=page.locator('[data-tw843-type-detail='+JSON.stringify(t.id)+'][data-tw843-type-mode=total]');await button.scrollIntoViewIfNeeded();await button.focus();await page.waitForTimeout(100);
 const state=()=>page.evaluate(()=>({focus:document.activeElement?.dataset.tw840Focus,top:document.querySelector('main').scrollTop,x:scrollX,y:scrollY})),before=await state();await page.evaluate(()=>renderToday());await page.waitForTimeout(550);const today=await state();await page.evaluate(()=>render());await page.waitForTimeout(550);const full=await state();await page.waitForTimeout(2200);const poll=await state();
 check(label+' exact type focus and deep scroll survive Today full and health redraws',[today,full,poll].every(x=>x.focus===before.focus&&Math.abs(x.top-before.top)<=1&&x.x===before.x&&x.y===before.y),{before,today,full,poll});
 const fold=page.locator('[data-tw841-group-card=equipment]'),summary=fold.locator('summary');await summary.focus();await page.keyboard.press('Enter');await page.waitForTimeout(100);await page.evaluate(()=>renderToday());await page.waitForTimeout(200);check(label+' source fold remains accessible and persists beside openly visible types',await fold.evaluate(d=>d.open)&&await page.locator('[data-tw843-type-id]').count()===model.instruments.length);await summary.focus();await page.keyboard.press('Enter');await page.waitForTimeout(100);
}
async function exercisePrint(page,check,label,out){
 const snapshot=()=>page.evaluate(()=>({top:document.querySelector('main').scrollTop,folds:[...document.querySelectorAll('[data-tw841-group-card],[data-tw842-plan-fold]')].map(n=>({key:n.dataset.tw841GroupCard||n.dataset.tw842PlanFold,kind:n.dataset.tw841GroupCard?'group':'plan',open:n.open}))})),before=await snapshot();
 await page.evaluate(()=>{window.__qaPrintOriginal843=window.print;window.__qaPrintCalled843=0;window.print=()=>{__qaPrintCalled843++;window.dispatchEvent(new Event('beforeprint'));};document.querySelector('#printProgress').click();});await page.waitForFunction(()=>__qaPrintCalled843===1);await page.emulateMedia({media:'print'});await page.waitForTimeout(150);
 const print=await page.evaluate(()=>{const visible=n=>{for(let e=n;e;e=e.parentElement)if(getComputedStyle(e).display==='none'||getComputedStyle(e).visibility==='hidden')return false;return n.getBoundingClientRect().height>0;};return {called:__qaPrintCalled843,body:document.body.classList.contains('printing-progress'),types:[...document.querySelectorAll('[data-tw843-type-id]')].map(n=>({id:n.dataset.tw843TypeId,visible:visible(n),readings:[...n.querySelectorAll('h5,.tw843-type-percent,.tw843-type-counts strong,.tw843-type-plan,.tw841-fence-value strong,.tw842-fence-plan')].map(x=>({text:x.textContent,color:getComputedStyle(x).color,visible:visible(x)}))})),folds:[...document.querySelectorAll('[data-tw841-group-card],[data-tw842-plan-fold]')].map(n=>n.open)};});
 check(label+' native Today print includes all type readings and expanded source folds',print.called===1&&print.body&&print.types.length>0&&print.types.every(t=>t.visible&&t.readings.every(r=>r.visible&&r.color==='rgb(17, 17, 17)'))&&print.folds.every(Boolean),print);check(label+' print stops subtype and parent motion',stopped(await motion843(page)),await motion843(page));await page.screenshot({path:path.join(out,'types843-'+label+'-print.png')});
 await page.emulateMedia({media:'screen'});await page.evaluate(()=>{window.dispatchEvent(new Event('afterprint'));window.print=__qaPrintOriginal843;});await page.waitForTimeout(550);const after=await snapshot();check(label+' native print restores original fold state and scroll',same(before.folds,after.folds)&&Math.abs(before.top-after.top)<=1,{before,after});
}
async function run(){
 const {PAGE,OUT,CANDIDATE_SHA}=process.env;if(!PAGE||!OUT||!CANDIDATE_SHA)throw Error('Frozen PAGE/SHA and private OUT required');const bytes=fs.readFileSync(PAGE);if(sha(bytes)!==CANDIDATE_SHA)throw Error('Candidate SHA mismatch');fs.mkdirSync(OUT,{recursive:true});
 const live=process.env.LIVE==='1',smoke=process.env.INITIAL_ONLY==='1',skipFirstDetails=process.env.SKIP_FIRST_DETAILS==='1',report={author:'Andrew Fisher',at:new Date().toISOString(),candidate:CANDIDATE_SHA,bytes:bytes.length,live,smoke,skipFirstDetails,checks:[],views:[]},guard=installWriteGuard();let session;
 const check=(name,pass,evidence)=>{report.checks.push({name,pass:!!pass,evidence});if(!pass)console.log('FAIL '+name);if(report.checks.length%25===0||!pass){fs.writeFileSync(path.join(OUT,'checks843.json'),JSON.stringify({candidate:CANDIDATE_SHA,count:report.checks.length,passed:report.checks.filter(c=>c.pass).length,failures:report.checks.filter(c=>!c.pass),last:name},null,2));}};
 const views=[{name:'laptop1366',W:1366,H:768,dpr:1},{name:'laptop1280',W:1280,H:800,dpr:1},{name:'phone',W:390,H:844,dpr:2,mobile:true},{name:'4k',W:3840,H:2160,dpr:1}].filter(v=>!process.env.VIEWS||process.env.VIEWS.split(',').includes(v.name));
 try{for(const view of views){console.log('START '+view.name);session=await open({pageFile:live?undefined:PAGE,hash:'#today',...view});const p=session.page;
  if(live){const upstream=guard.fulfilledDocuments.at(-1),received=guard.documentResponses.at(-1),bom=bytes.subarray(0,3).equals(Buffer.from([239,187,191])),stripped=bom&&received?.sha===sha(bytes.subarray(3))&&received.bytes===bytes.length-3;check(view.name+' exact public upstream and browser bytes without local substitutions',upstream?.sha===CANDIDATE_SHA&&upstream.bytes===bytes.length&&upstream.status===200&&received?.status===200&&(received.sha===CANDIDATE_SHA&&received.bytes===bytes.length||stripped)&&session.counts.page===0,{upstream,received,stripped,counts:session.counts});if(session.counts.page||upstream?.sha!==CANDIDATE_SHA)throw Error('Public source identity failed');}
  await ready840(p);await p.waitForFunction(()=>typeof todayTypeMetrics843==='function'&&TodayWork840.report().typesMerged,null,{timeout:15000});const before=await nativeSnapshot(p),model=await p.evaluate(()=>{const asOf=TodayWork840.report().asOf;return {day:asOf,types:todayTypeMetrics843(asOf),groups:todayGroupDetails841(asOf)};}),inputs=await oracle.typeInputs843(p,model.day),expected=oracle.typeOracle843(inputs),shown=await ui.readTypes843(p);report.views.push({view,model,inputs,expected,shown});
  check(view.name+' public view and type coverage remain read only and fully ready',await p.evaluate(()=>capability()==='view'&&location.pathname.startsWith('/v/Coates-GC500-2026'))&&model.types.health.ready&&model.types.coverage.allRepresented,model.types.coverage);oracle.assertTypeModel843(check,view.name,model.types,expected);ui.assertTypesUI843(check,view.name,model.types,shown);
  await ui.assertRetainedSources843(p,check,view.name,model.groups);await exerciseFront842(p,check,view.name,OUT);await screenshots(p,model.types,view.name,OUT);
  if(!smoke){if(!(skipFirstDetails&&view.name==='laptop1366'))await ui.exerciseTypeDetails843(p,check,view.name,model.types,OUT,view.name==='laptop1366');await exerciseMotion(p,check,view.name,model.types);await exerciseRefresh(p,check,view.name,model.types);await exercisePrint(p,check,view.name,OUT);
   const replay=new Date(model.day+'T00:00:00Z');replay.setUTCDate(replay.getUTCDate()-1);const day=replay.toISOString().slice(0,10);await p.locator('#asOf').fill(day);await p.locator('#asOf').press('Tab');await p.waitForFunction(day=>TodayWork840.report().asOf===day,day);const next=await p.evaluate(day=>todayTypeMetrics843(day),day);check(view.name+' native selected day updates every visible type and preserves membership',next.asOf===day&&same(model.types.instruments.map(t=>t.id),next.instruments.map(t=>t.id)));if(view.name==='laptop1366')oracle.assertTypeModel843(check,view.name+' replay',next,oracle.typeOracle843(await oracle.typeInputs843(p,day)));ui.assertTypesUI843(check,view.name+' replay',next,await ui.readTypes843(p));await p.locator('#asOf').fill(model.day);await p.locator('#asOf').press('Tab');await p.waitForFunction(day=>TodayWork840.report().asOf===day,model.day);
  }
  const after=await nativeSnapshot(p);check(view.name+' native records and media descriptors remain unchanged',same(before.collections,after.collections)&&same(before.media,after.media));check(view.name+' no runtime errors',session.errors.length===0,session.errors);await session.browser.close();session=null;console.log('DONE '+view.name+' '+report.checks.filter(c=>c.pass).length+'/'+report.checks.length);
 }}catch(e){check('Focused browser execution',false,e.stack);}finally{if(session)await session.browser.close();await guard.closeAll();report.guard=guard;check('Frozen candidate bytes unchanged',sha(fs.readFileSync(PAGE))===CANDIDATE_SHA);check('All non-GET requests blocked and no operational write attempted',guard.nonGetSeen.length===guard.blocked.length&&!guard.nonGetSeen.some(r=>r.operational),guard.nonGetSeen);const unexpected=guard.consoleErrors.filter(e=>!(/Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(e.text)&&guard.blocked.some(b=>!b.operational&&b.url===e.url)));check('No unexpected console error',!unexpected.length,unexpected);report.passed=report.checks.filter(c=>c.pass).length;report.total=report.checks.length;fs.writeFileSync(path.join(OUT,'today843.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,total:report.total,candidate:CANDIDATE_SHA}));if(report.passed!==report.total)process.exitCode=1;}
}
module.exports={motion843,active,stopped,readTypes843:ui.readTypes843};if(require.main===module)run().catch(e=>{console.error(e.message);process.exitCode=2;});
