// Author: Andrew Fisher. Visible type instruments and exact-type drilldowns.
'use strict';
const path=require('node:path');
const fmt=n=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('en-AU',{maximumFractionDigits:2}):'—';
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const pct=t=>t.pct==null?'—':(t.pctKind==='lower-bound'?'≥':'')+fmt(t.pct)+'%';
async function readTypes843(page){return page.evaluate(()=>{
 const b=document.querySelector('#gc500-work-board840'),rect=n=>{const r=n.getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:r.width,height:r.height};},font=n=>{const s=getComputedStyle(n);return {font:parseFloat(s.fontSize),filter:s.filter,shadow:s.textShadow,transform:s.transform,color:s.color};};
 return {oldTypes:b.querySelectorAll('[data-tw841-type]').length,oldGroups:document.querySelectorAll('#pane-today .dsn .groups:not(.branches) .grp').length,main:{scroll:document.querySelector('main').scrollWidth,client:document.querySelector('main').clientWidth},documentWidth:document.documentElement.scrollWidth,width:innerWidth,
  items:[...b.querySelectorAll('[data-tw843-type-id]')].map(n=>{const asset=n.dataset.tw843Kind==='asset-type';return {id:n.dataset.tw843TypeId,kind:n.dataset.tw843Kind,cardId:n.closest('[data-tw840-area]')?.dataset.tw840Area,groupId:n.closest('[data-tw843-family]')?.dataset.tw843Family||'Build programme',name:n.querySelector(asset?'h5':'.tw841-fence-label')?.textContent,percent:n.querySelector(asset?'.tw843-type-percent':'.tw841-fence-percent')?.textContent,kindValue:n.querySelector('[data-pct-kind]')?.dataset.pctKind,
   values:Object.fromEntries([...n.querySelectorAll(asset?'[data-tw843-quantity]':'[data-tw842-fence-value]')].map(v=>[v.dataset.tw843Quantity||v.dataset.tw842FenceValue,v.querySelector('strong')?.textContent])),onSite:n.querySelector('[data-tw843-onsite]')?.textContent,plan:n.querySelector(asset?'[data-tw843-plan]':'[data-tw842-fence-plan]')?{text:n.querySelector(asset?'[data-tw843-plan]':'[data-tw842-fence-plan]').textContent,status:n.querySelector(asset?'[data-tw843-plan]':'[data-tw842-fence-plan]').dataset.status}:null,
   text:n.textContent,leds:n.querySelectorAll('.tw843-leds i').length,lit:n.querySelectorAll('.tw843-leds i.is-on').length,closedFold:!!n.closest('details:not([open])'),rect:rect(n),scroll:n.scrollWidth,client:n.clientWidth,buttons:[...(asset?n.querySelectorAll('[data-tw843-type-detail]'):[n])].map(rect),labels:[...n.querySelectorAll(asset?'h5,.tw843-type-caption,.tw843-type-counts button>span,.tw843-type-onsite,.tw843-type-plan>span,.tw843-type-plan>strong':'.tw841-fence-label,.tw841-fence-percent,.tw842-fence-plan')].map(font),readings:[...n.querySelectorAll(asset?'.tw843-type-percent strong,.tw843-type-counts strong':'.tw841-fence-value strong')].map(font),effects:[n,...n.querySelectorAll('h5,.tw843-type-percent,.tw843-type-counts,.tw843-type-gauge')].map(font)};})};
 });}
function assertTypesUI843(check,label,model,ui){
 check(label+' every type is present once outside collapsed source folds',ui.items.length===model.instruments.length&&new Set(ui.items.map(t=>t.id)).size===ui.items.length&&model.instruments.every(t=>ui.items.some(u=>u.id===t.id))&&ui.items.every(t=>!t.closedFold&&t.rect.height>0),ui.items.map(t=>({id:t.id,closed:t.closedFold,rect:t.rect})));
 check(label+' migrated type tables and legacy group plates are absent',ui.oldTypes===0&&ui.oldGroups===0,{oldTypes:ui.oldTypes,oldGroups:ui.oldGroups});
 check(label+' all type instruments fit without horizontal scrolling',ui.documentWidth<=ui.width+1&&ui.main.scroll<=ui.main.client+1&&ui.items.every(t=>t.scroll<=t.client+1&&t.rect.left>=0&&t.rect.right<=ui.width+1),ui.items.filter(t=>t.scroll>t.client+1||t.rect.right>ui.width+1));
 check(label+' type labels remain readable with unfiltered text and usable targets',ui.items.every(t=>t.labels.every(f=>f.font>=14&&f.filter==='none'&&f.shadow==='none')&&t.effects.every(f=>f.filter==='none'&&f.shadow==='none'&&f.transform==='none')&&t.buttons.every(b=>b.height>=44&&b.width>=44)),ui.items.map(t=>({id:t.id,labels:t.labels,buttons:t.buttons})));
 for(const t of model.instruments){const u=ui.items.find(i=>i.id===t.id);if(!u)continue;const asset=t.kind==='asset-type',fencePercent=t.pct==null?(t.loading?'Loading programme':t.sourceRow?.kind==='recorded-only'?'Recorded work only':t.total===0?'No programme quantity':'Programme quantity unconfirmed'):t.done>t.total&&t.total>0?'100% + extra work':fmt(t.pct)+'% recorded';
  check(label+' '+t.groupId+' / '+t.name+' shows its quantities percentage plan and own LED bar',u.kind===t.kind&&u.cardId===t.cardId&&u.groupId===t.groupId&&u.name===t.name&&['total','done','left'].every(k=>u.values[k]===fmt(t[k]))&&u.percent===(asset?pct(t):fencePercent)&&(!asset||u.kindValue===t.pctKind&&u.onSite?.includes(fmt(t.onSite)))&&u.plan?.status===t.plan.status&&u.plan.text.includes(t.plan.label)&&u.leds===12&&u.lit===(t.pct==null?0:Math.floor(Math.max(0,Math.min(100,t.pct))/100*12)),{id:t.id,expected:{total:t.total,done:t.done,left:t.left,pct:t.pct,kind:t.pctKind,plan:t.plan},actual:u});
 }
}
async function exerciseTypeDetails843(page,check,label,model,out,all){
 const assets=model.instruments.filter(t=>t.kind==='asset-type'),selected=all?assets:assets.filter((t,i)=>i===0||t.pctKind==='lower-bound'||t.total==null||/tank/i.test(t.name)||t.name===assets.filter(x=>x.cardId===t.cardId).sort((a,b)=>b.name.length-a.name.length)[0]?.name);
 for(const item of selected){for(const mode of all?['total']:['total','done','left']){
  const selector='[data-tw843-type-detail='+JSON.stringify(item.id)+'][data-tw843-type-mode='+mode+']',button=page.locator(selector);await button.click();await page.waitForTimeout(80);
  const shown=await page.locator('#gc500-work-dialog840').evaluate(d=>({open:d.open,title:d.querySelector('h2')?.textContent,subtitle:d.querySelector('.tw840-dialog-top p')?.textContent,text:d.textContent,rows:[...d.querySelectorAll('.tw840-detail-row')].map(r=>({key:r.querySelector('[data-tw840-reference]')?.dataset.tw840Reference,text:r.textContent,value:[...r.querySelector(':scope>strong').childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent).join('').trim()})),scroll:d.scrollWidth,client:d.clientWidth,left:d.getBoundingClientRect().left,right:d.getBoundingClientRect().right,main:document.querySelector('main').scrollTop}));
  const rows=item.rows.filter(r=>mode==='total'||(mode==='done'?r.complete||typeof r.done==='number'&&r.done>0:!r.complete||typeof r.left!=='number'||r.left>0));
  check(label+' exact '+item.groupId+' / '+item.name+' '+mode+' drilldown owns only its member rows',shown.open&&shown.title.includes(item.name)&&same(shown.rows.map(r=>r.key),rows.map(r=>r.key))&&rows.every(r=>{const s=shown.rows.find(x=>x.key===r.key);return s?.value===fmt(mode==='total'?r.quantity:mode==='done'?r.done:r.left)&&s.text.includes(r.status);})&&shown.subtitle.includes(fmt(item[mode]))&&shown.scroll<=shown.client+1&&shown.left>=0&&shown.right<=page.viewportSize().width,{id:item.id,mode,expected:rows,actual:shown});
  if(mode==='total')check(label+' '+item.name+' source and plan qualifications survive migration',shown.text.includes(item.basis)&&item.issues.every(s=>shown.text.includes(s))&&item.plan.issues.every(s=>shown.text.includes(s))&&(item.total!=null||shown.text.includes(fmt(item.scheduleTotal))&&/Schedule total/i.test(shown.text)),{id:item.id,text:shown.text});
  await page.evaluate(()=>{window.__qaTypeClose843=false;document.querySelector('#gc500-work-dialog840').addEventListener('close',()=>{window.__qaTypeClose843=true;},{once:true});});await page.keyboard.press('Escape');const token='type-'+item.id+'-'+mode;await page.waitForFunction(token=>__qaTypeClose843&&document.activeElement?.dataset.tw840Focus===token,token,{timeout:1500}).catch(()=>{});const after=await page.evaluate(()=>({focus:document.activeElement?.dataset.tw840Focus,main:document.querySelector('main').scrollTop,closed:__qaTypeClose843}));
  check(label+' '+item.name+' '+mode+' close restores exact type button focus and scroll',after.closed&&after.focus===token&&Math.abs(after.main-shown.main)<=1,{after,before:shown.main});
 }}
 const sample=assets.find(t=>t.cardId==='toilets'&&t.pctKind==='lower-bound')||assets.find(t=>t.cardId==='toilets');if(sample){await page.locator('[data-tw843-type-id='+JSON.stringify(sample.id)+']').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'types843-'+label+'-toilet-types.png')});}
}
async function assertRetainedSources843(page,check,label,groups){
 const source=await page.evaluate(()=>[...document.querySelectorAll('[data-tw841-group-card]')].map(f=>({id:f.dataset.tw841GroupCard,text:f.textContent,groups:[...f.querySelectorAll('[data-tw841-group-id]')].map(g=>({id:g.dataset.tw841GroupId,text:g.textContent,keys:[...g.querySelectorAll('.tw841-exclusions [data-tw840-reference]')].map(n=>n.dataset.tw840Reference)})),money:[...f.querySelectorAll('[data-tw841-money]')].map(n=>({id:n.dataset.tw841Money,text:n.textContent})),comparisons:[...f.querySelectorAll('[data-tw841-comparison]')].map(n=>({id:n.dataset.tw841Comparison,text:n.textContent}))})));
 const money=n=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:2}):'Not yet priced';
 for(const fold of source){const card=groups[fold.id];check(label+' '+fold.id+' source facts exclusions and qualifications remain available',same(fold.groups.map(g=>g.id),card.groups.map(g=>g.id))&&card.groups.every(g=>{const shown=fold.groups.find(s=>s.id===g.id);return shown&&same(shown.keys,g.excluded.map(r=>r.key))&&g.notes.every(n=>shown.text.includes(n))&&g.issues.every(n=>shown.text.includes(n))&&g.facts.every(f=>shown.text.includes(f.label)&&shown.text.includes(fmt(f.value)));})&&card.notes.every(n=>fold.text.includes(n)),{id:fold.id,groups:fold.groups});
  check(label+' '+fold.id+' money and comparison buckets remain exactly once',same(fold.money.map(m=>m.id),card.money.map(m=>m.id))&&same(fold.comparisons.map(m=>m.id),card.comparisons.map(m=>m.id))&&card.money.every(m=>fold.money.find(s=>s.id===m.id).text.includes(money(m.amount)))&&card.comparisons.every(m=>{const t=fold.comparisons.find(s=>s.id===m.id).text;return t.includes(money(m.hire))&&t.includes(money(m.transport));}),{money:fold.money,comparisons:fold.comparisons});
 }
}
module.exports={readTypes843,assertTypesUI843,exerciseTypeDetails843,assertRetainedSources843,fmt,pct};
