// Author: Andrew Fisher. Supporting prose folds preserve figures, warnings, controls and source links.
const fs=require('fs'),assert=require('assert/strict'),path=require('path'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}),p=await b.newPage({viewport:{width:390,height:844}});try{
await p.setContent('<body></body>');await p.evaluate(()=>{window.SFOLD_OPEN=new Set();window.foldStories=()=>{};document.addEventListener('toggle',e=>{if(e.target.matches('details[data-sfold]'))e.target.open?SFOLD_OPEN.add(e.target.dataset.sfold):SFOLD_OPEN.delete(e.target.dataset.sfold);},true);});await p.addScriptTag({content:fs.readFileSync(path.resolve(__dirname,'../prose976.js'),'utf8')});
const text='The supporting source details explain the original schedule and how the record was linked to this location. Open the original source for further detail.';
await p.evaluate(text=>{window.fixture=()=>'<section id="pane-plant"><article class="card"><h3>Equipment</h3><div class="kpis"><strong>138</strong></div><p class="sub">'+text+' <a href="#docs">Original source</a></p><p class="hint"><strong>6</strong> installed panels are shown as physical stock with the item ownership saved against each reference and location.</p><p class="warn">Source quantity differs from the delivery record and requires a check of the signed original docket and saved item numbers.</p><label>Count<input value="6"></label><form><p class="hint">'+text+'</p><button>Save</button></form><canvas></canvas><table><tbody><tr><td><p class="sub">'+text+'</p></td></tr></tbody></table><nav><a href="#today">Back</a></nav><p class="hint">Short status</p></article></section>';document.body.innerHTML=fixture();},text);
const first=await p.evaluate(()=>{const pane=document.querySelector('#pane-plant'),before=pane.textContent,count=Prose976.compact(pane),fold=pane.querySelector('[data-prose976]');return{count,unchanged:before===pane.textContent.replace('More info',''),figures:!pane.querySelector('.kpis').closest('details'),warning:!pane.querySelector('.warn').closest('details'),countPrimary:!pane.querySelector('p.hint strong').closest('details'),formPrimary:!pane.querySelector('form').closest('details'),tablePrimary:!pane.querySelector('table p').closest('details'),chartPrimary:!pane.querySelector('canvas').closest('details'),sourceLink:!!fold.querySelector('a[href="#docs"]'),backPrimary:!pane.querySelector('nav').closest('details'),closed:!fold.open,shortPrimary:!Array.from(pane.querySelectorAll('p')).find(n=>n.textContent==='Short status').closest('details')};});
assert.equal(first.count,1);assert(first.figures&&first.warning&&first.countPrimary&&first.formPrimary&&first.tablePrimary&&first.chartPrimary&&first.sourceLink&&first.backPrimary&&first.closed&&first.shortPrimary); // Moving text changes order, never deletes it.
const preserved=await p.evaluate(text=>document.querySelector('[data-prose976] p').textContent.startsWith(text),text);assert(preserved);
assert.equal(await p.evaluate(()=>Prose976.compact(document.querySelector('#pane-plant'))),0);
await p.locator('[data-prose976] summary').click();await p.waitForTimeout(30);
assert(await p.evaluate(()=>{document.body.innerHTML=fixture();Prose976.compact(document.querySelector('#pane-plant'));return document.querySelector('[data-prose976]').open;}));
await p.evaluate(text=>{document.body.innerHTML='<section id="pane-costs"><div class="card"><p class="sub">'+text+'</p></div></section>';},text);assert.equal(await p.evaluate(()=>Prose976.compact(document.querySelector('#pane-costs'))),0);
console.log(JSON.stringify({author:'Andrew Fisher',checks:15,passed:true,networkUsed:false,nativeWrites:0}));
}finally{await b.close();}})().catch(e=>{console.error(e.stack);process.exit(1)});
