// Author: Andrew Fisher. Actual public page; no page or shared-state substitution.
const fs=require('fs'),crypto=require('crypto'),assert=require('assert/strict');const fetcher=require('../../toolchain/harness/curlfetch'),native=fetcher.curlFetch;let served;
fetcher.curlFetch=async(u,h,m,b)=>{const r=await native(u,h,m,b);if(new URL(u).pathname.replace(/\/$/,'')==='/v/Coates-GC500-2026')served=crypto.createHash('sha256').update(r.body).digest('hex');return r;};
const {open}=require('../../toolchain/harness/open_page');
(async()=>{const h=await open({W:390,H:844,mobile:true,hash:'#subhired'}),p=h.page,checks=[];const ck=(n,v)=>{assert(v,n);checks.push(n)};try{await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:150000});await p.evaluate(()=>photoIndex());await p.waitForFunction(()=>photoIndex().state==='ready',null,{timeout:60000});
ck('Exact actual-public bytes',served===process.env.EXPECTED_SHA&&h.counts.page===0);
const r=await p.evaluate(()=>holdAssets(()=>{renderSubhired932();const rows=Subhire975.remainingRows(),v=gcModel925(assetOf('T0103')).rows.filter(r=>r.physical),pane=document.getElementById('pane-subhired');return {remaining:rows.reduce((n,r)=>n+r.remaining,0),friday:rows.filter(r=>r.date==='2026-10-09').length,vms:v.map(r=>r.owner),refs:Reference966.unresolvedLocations().map(r=>r.id),destinations:{T0268:whereText(assetOf('T0268')),WC85:whereText(assetOf('WC85'))},foldClosed:!pane.querySelector('[data-subhire975-units]').open,currentFirst:!!(pane.querySelector('[data-subhire975-plan]').compareDocumentPosition(pane.querySelector('[data-unit925-companies]'))&Node.DOCUMENT_POSITION_FOLLOWING),charges:arrivedChargeRows975(assetOf('WC09')).map(r=>({item:r.item,quantity:r.arrived,keys:r.charges.map(c=>c.key)})),soundOff:!GC3D.sound.ctx&&!GC3D.sound.active};}));
ck('35 actual remaining deliveries',r.remaining===35);ck('Friday only in history',r.friday===0);ck('One Coates and one PremiAir VMS',r.vms.filter(x=>x==='coates').length===1&&r.vms.filter(x=>x==='prem-air-hire').length===1);ck('Current work before folded equipment',r.currentFirst&&r.foldClosed);ck('Only three specific VMS associations remain',JSON.stringify(r.refs.sort())===JSON.stringify(['T0159','T0169','T0170']));ck('Default audio remains off',r.soundOff);
const file=await p.evaluate(()=>subhirePdf975('2026-10-13',()=>true).then(f=>({size:f.size,pages:f.pages})));ck('Fresh remaining-only Tuesday PDF',file.size>1000&&file.pages===1);
await p.evaluate(()=>openAsset('WC09'));ck('Arrived charges on actual view link',await p.locator('[data-charges952="WC09"]').count()===1);ck('Six quantity-only pee panels retained',r.charges.some(c=>c.item==='Pee Panel'&&c.quantity===6));ck('FWF does not gain cleaning fee',r.charges.filter(c=>c.item==='FWF').every(c=>!c.keys.includes('cleaning')));
ck('No operational write attempts or page errors',h.counts.blocked===0&&h.errors.length===0);const report={author:'Andrew Fisher',pass:true,sha256:served,actualPublic:true,pageSubstitutions:h.counts.page,checks,observations:r,errors:h.errors,operationalWrites:h.counts.blocked};fs.writeFileSync(process.env.OUT,JSON.stringify(report,null,2));console.log(JSON.stringify({pass:true,checks:checks.length,sha256:served}));
}finally{await h.browser.close();}})().catch(e=>{console.error(e.stack);process.exit(1)});
