/* Author: Andrew Fisher. Synthetic native lifecycle; no network or operational writes. */
const fs=require('fs'),vm=require('vm'),assert=require('assert');let checks=0;const check=(v,msg)=>{assert(v,msg);checks++;};
const l={discipline:'Toilets & amenities',item:'Toilet Block 6m',quantity:2},other={discipline:l.discipline,item:'FWF',quantity:4},a={key:'WC09',lines:[l,other]},b={key:'P36',lines:[{discipline:'Portable buildings',item:'Building 6m',quantity:1}]};
const saves=[],listeners={},ctx={window:{},S:{loads:{unrelated:{kind:'flow891'}},labour:{keep:true},delivery:{WC09:{steps:true}}},LAB_REST:'rest',qtyOf:x=>x.quantity,labourUnits:(x,item)=>x.key==='WC09'&&item===l.item?['1268858','1311146']:[],labourRestN:()=>0,assetOf:k=>k==='WC09'?a:k==='P36'?b:null,chargeLines:x=>x.lines,mayWrite:()=>true,whoAmI:()=> 'Andrew Fisher',movedAway:()=>false,labourLinesFor:()=>({lines:[{key:'install'},{key:'steps'},{key:'cleaning'},{key:'demob'}]}),stampIt:(...x)=>saves.push(['stamp',...x]),save:()=>saves.push(['save']),bump:()=>saves.push(['bump']),flash:()=>{},esc:x=>String(x).replace(/&/g,'&amp;').replace(/"/g,'&quot;'),money:x=>'$'+x,fmtStamp:x=>x,canEdit:()=>true,labourKey:(r,d,i,k,u)=>(u?r+'/u'+u:r)+'|'+d+'|'+i+'|'+k,labourTicksHtml:x=>x.lines.map(y=>(ctx.labourUnits(x,y.item).length?ctx.labourUnits(x,y.item):[null]).map(u=>'<label class="labtick"><input data-lab="'+ctx.esc(ctx.labourKey(x.key,y.discipline,y.item,'steps',u))+'">Steps</label>').join('')).join(''),document:{addEventListener:(k,v)=>listeners[k]=v},Date,Math,Number,Map,Object,JSON};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/../stairs975.js','utf8'),ctx);const S=ctx.window.Stairs975,original=JSON.stringify({labour:ctx.S.labour,delivery:ctx.S.delivery});
check(S.quantity(a,l)===0,'no inferred stairs exclusion');check(S.save(a.key,l.discipline,l.item,'1268858',1),'remove one numbered block stairs');check(S.excluded(a.key,l.discipline,l.item,'1268858'),'selected block excluded');check(!S.excluded(a.key,l.discipline,l.item,'1311146'),'sibling preserved');check(S.quantity(a,l)===1,'one excluded per location subtotal');check(S.quantity(a,other)===0,'other item untouched');check(S.quantity(b,b.lines[0])===0,'other reference untouched');check(JSON.stringify({labour:ctx.S.labour,delivery:ctx.S.delivery})===original,'native labour and work unchanged');check(ctx.S.loads.unrelated.kind==='flow891','other loads untouched');check(saves.some(x=>x[0]==='stamp'&&x[1]==='loads'),'native stamped loads collection');
const html=ctx.labourTicksHtml(a);check(html.includes('Remove stairs')&&html.includes('Add stairs'),'per-unit add/remove controls');check(html.includes('Stairs excluded × 1'),'exclusion visible');check(html.includes('disabled'),'excluded completion input disabled');check(!S.save(a.key,l.discipline,l.item,null,1),'reject whole location if numbered pieces');check(!S.save(a.key,l.discipline,l.item,'other',1),'reject nonexistent unit');check(!S.save(a.key,l.discipline,l.item,'1311146',2),'reject too many stairs');
const reload=JSON.parse(JSON.stringify(ctx.S.loads));ctx.S.loads=reload;check(S.quantity(a,l)===1,'reload retains scoped exclusion');check(S.save(a.key,l.discipline,l.item,'1268858',0),'restore chosen stairs');check(S.quantity(a,l)===0,'restore returns quantity');check(S.record(a.key,l.discipline,l.item,'1268858').history.length===2,'remove and restore history retained');
check(S.save(a.key,other.discipline,other.item,null,2),'partial unnumbered exclusion');check(S.quantity(a,other)===2,'partial quantity returned');check(!S.excluded(a.key,other.discipline,other.item,null),'partial scope not wholly excluded');check(!S.save(a.key,other.discipline,other.item,null,1.5),'reject fractional quantity');
ctx.mayWrite=()=>false;check(!S.save(b.key,b.lines[0].discipline,b.lines[0].item,null,1),'view mode rejects change');ctx.mayWrite=()=>true;ctx.whoAmI=()=>'';check(!S.save(b.key,b.lines[0].discipline,b.lines[0].item,null,1),'unnamed edit rejected');
check(Object.keys(ctx.S.loads).every(k=>k==='unrelated'||k.startsWith(S.prefix)),'only own namespace written');console.log(JSON.stringify({author:'Andrew Fisher',checks,passed:true,operationalWrites:0}));
