// Author: Andrew Fisher. Isolated native validation and worker UI; no network or record writes.
const fs=require('fs'),assert=require('assert/strict'),vm=require('vm'),{chromium}=require('playwright');
const source=fs.readFileSync(process.env.PAGE,'utf8');
const save=source.match(/^function crew883SavePlan\(.*$/m)[0];
const start=source.indexOf('  function validatePlanValues('),end=source.indexOf('\n  function roster(day)',start);
let captures=[];const ctx={crew883Roles:{spotter:'Spotter',forklift:'Forklift operator',installer:'Installer',escort:'Escort'},crew883Write:(...args)=>{captures.push(args);return true},ROLE_KEYS:['spotter','forklift','installer','escort'],validTime:v=>/^([01]\d|2[0-3]):[0-5]\d$/.test(v),planSignature:JSON.stringify,nameKey:v=>String(v||'').trim().toLowerCase()};vm.createContext(ctx);vm.runInContext(save+'\n'+source.slice(start,end),ctx);
const value={order:null,location:'Coates compound',start:'',finish:'',people:[{slot:1,roles:[]}]},model={count:2,names:['Andrew','Scott'],mappingToken:'mapping'},current={people:[]};
assert.equal(ctx.crew883SavePlan('2026-10-09','P25',value),true);assert.equal(captures[0][2].people[0].roles.length,0);
assert.equal(ctx.validatePlanValues(model,value,current,'mapping',JSON.stringify(current)),'');
assert.match(ctx.validatePlanValues(model,value,current,'stale',JSON.stringify(current)),/changed/);
const duplicate={...value,people:[value.people[0],value.people[0]]};assert.equal(ctx.crew883SavePlan('2026-10-09','P25',duplicate),false);assert.match(ctx.validatePlanValues(model,duplicate,current,'mapping',JSON.stringify(current)),/once/);
assert.equal(ctx.crew883SavePlan('2026-10-09','P25',{...value,people:[{slot:1,roles:['invented']}]}),false);
const historical={...value,people:[{slot:1,roles:['installer','spotter']}]};assert.equal(ctx.crew883SavePlan('2026-10-09','P25',historical),true);assert.deepEqual(Array.from(captures.at(-1)[2].people[0].roles),['installer','spotter']);
assert.match(ctx.validatePlanValues(model,{...value,start:'08:00',finish:'07:00'},current,'mapping',JSON.stringify(current)),/finish after/);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}),p=await b.newPage({viewport:{width:390,height:844}});try{
await p.setContent('<body></body>');await p.evaluate(()=>{window.crew883PersonHtml=(d,p,i,can)=>'<fieldset data-crew883-person><legend>Person '+(i+1)+'</legend><label>Assign person <select data-crew883-slot><option value="1" selected>Andrew</option></select></label>'+['installer','spotter'].map(r=>'<label><input type="checkbox" data-crew883-role="'+r+'"'+(p.roles.includes(r)?' checked':'')+'> '+r+'</label>').join('')+'<button data-crew883-remove>Remove person</button></fieldset>';window.crew883Editor=()=>'<details class="crew883" data-workers911><summary>Workers</summary><div class="crew883-body"><section>WORKERS</section><label>Location<input data-crew883-location value="Coates compound"></label><label>Start<input data-crew883-start value="08:00"></label><label>Finish<input data-crew883-finish value="08:30"></label><p>Stored extra details</p><p class="staff910-message"></p></div></details>';});
await p.addScriptTag({content:fs.readFileSync(require('path').resolve(__dirname,'../workers975_src.js'),'utf8')});
const ui=await p.evaluate(()=>{const blank=crew883PersonHtml('',{roles:[]},0,true),history=crew883PersonHtml('',{roles:['installer']},0,true);document.body.innerHTML=crew883Editor()+blank+history;const root=document.querySelector('.crew883'),more=root.querySelector('[data-workers975-details]');return {blankRoles:(new DOMParser().parseFromString(blank,'text/html')).querySelectorAll('[data-crew883-role]').length,savedRole:document.querySelector('[data-workers975-history] [data-crew883-role="installer"]').checked,historyDisabled:[...document.querySelectorAll('[data-workers975-history] input')].every(i=>i.disabled),historyClosed:!document.querySelector('[data-workers975-history]').open,moreClosed:!more.open,location:more.querySelector('input').value,messagePrimary:root.querySelector('.staff910-message').parentElement===root.querySelector('.crew883-body')};});
assert.deepEqual(ui,{blankRoles:0,savedRole:true,historyDisabled:true,historyClosed:true,moreClosed:true,location:'Coates compound',messagePrimary:true});
console.log(JSON.stringify({author:'Andrew Fisher',checks:15,passed:true,networkUsed:false,nativeWrites:0}));
}finally{await b.close();}})().catch(e=>{console.error(e.stack);process.exit(1)});
