/* Author: Andrew Fisher. Financial presentation only; source models remain authoritative. */
(function(W){
'use strict';
const r2=n=>Math.round(n*100)/100,known=n=>typeof n==='number'&&Number.isFinite(n);
function remaining(recorded,job){return known(recorded)&&known(job)?r2(job-recorded):null;}
function moneyRows(rows){return rows.map(l=>({code:l.code,label:l.line,recorded:l.now,remaining:remaining(l.now,l.job),job:l.job,details:[l.what,l.basis,l.missing&&'Not on the record: '+l.missing].filter(Boolean).join(' · ')}));}
function table(rows,total){const m=n=>known(n)?esc(money(n)):'—';const card=l=>'<article class="card" style="min-width:0;margin:8px 0;padding:12px"><b>'+ (l.code?'<span class="chip ref mono">'+esc(l.code)+'</span> ':'')+esc(l.label)+'</b><div style="display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px 12px;margin:10px 0"><span>Recorded</span><span style="margin:0;text-align:right">'+m(l.recorded)+'</span><span>Forecast remaining</span><span style="margin:0;text-align:right">'+m(l.remaining)+'</span><span>Job forecast</span><span style="margin:0;text-align:right"><b>'+m(l.job)+'</b></span></div>'+(l.details?'<details><summary>More info</summary><p>'+esc(l.details)+'</p></details>':'')+'</article>';return '<div data-financial976>'+(total?card({...total,remaining:remaining(total.recorded,total.job)})+'<details class="units925-edit"><summary>More info · line breakdown</summary>'+rows.map(card).join('')+'</details>':rows.map(card).join(''))+'</div>';}
function fenceSummary(SP,fd,F){const cost=r2(SP.paid+SP.green);return [{label:'Customer revenue',recorded:fd.charged,remaining:F.revenue,job:r2(fd.charged+F.revenue),details:'Recorded work at customer rates; remaining programme at customer rates.'},{label:'Supplier cost',recorded:cost,remaining:F.cost,job:r2(cost+F.cost),details:'Recorded docket and green-book quantities at supplier rates. Forecast remaining is programme work not yet docketed. These figures are not payment confirmations.'}];}
const api={remaining,moneyRows,fenceSummary};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(!W)return;W.FinancialPresentation976=api;
fencePlCard=function(){const SP=fencePaidSplit(),fd=fenceDerived(),F=cj764Fencing(),rows=fenceSummary(SP,fd,F);return '<section class="card" id="fencePl"><h3>Fencing · recorded and forecast</h3><p class="fin745-eyebrow">AUD EX GST</p>'+table(rows)+'<details class="units925-edit"><summary>More info · rates and ledger basis</summary><p>Supplier gear: Rehire 2126. Supplier crew: Installation 2142. Customer fencing hire and installation follow the card metre rate. Purchase orders are source references, not extra costs.</p><p>'+esc(SP.docket_labour_words||'')+'</p></details></section>';};
const originalApply976=fencePrivateApply;
fencePrivateApply=function(){const result=originalApply976.apply(this,arguments),pane=document.getElementById('pane-fencing'),heading=pane&&pane.querySelector('.fp-heading');if(heading){pane.querySelector('#fencePl')?.remove();heading.insertAdjacentHTML('afterend',fencePlCard());}return result;};
const originalPl=pl770Card;
function recoveryDetails976(html){if(typeof document==='undefined')return '';const t=document.createElement('div');t.innerHTML=html;const block=[...t.querySelectorAll('.fin745-block')].find(x=>x.querySelector('h3')?.textContent.trim().startsWith('Recovery'));return block?block.outerHTML:'';}
pl770Card=function(){let P;try{P=pl770Model();}catch(e){return originalPl.apply(this,arguments);}const overhead={label:'Travel, accommodation, meals and printing',recorded:P.over,job:P.overJob,remaining:remaining(P.over,P.overJob),details:'Overheads; Finance confirms any journal allocation.'},wages={label:'Wages',recorded:P.wages.toDate,job:P.wages.job,remaining:remaining(P.wages.toDate,P.wages.job),details:'Recorded and forecast wage cost. Unpriced hours: '+P.wages.unpricedHours};const warning=P.checks&&Object.values(P.checks).some(v=>v===false)?'<div class="notice warn"><b>Financial reconciliation needs review</b><details><summary>More info</summary>'+esc(JSON.stringify(P.checks))+'</details></div>':''; const pct=v=>known(v)?Math.round(v*100)+'%':'—';const results='<details class="units925-edit"><summary>More info · financial results</summary>'+table([{label:'Ledger gross margin before overheads and wages',recorded:P.gm?.now,job:P.gm?.job,remaining:remaining(P.gm?.now,P.gm?.job),details:'Recorded '+pct(P.gm?.pcNow)+' · job forecast '+pct(P.gm?.pcJob)},{label:'Difference so far — not a margin yet',recorded:P.diff?.now,job:P.diff?.job,remaining:remaining(P.diff?.now,P.diff?.job),details:'Recorded '+pct(P.diff?.pcNow)+' · recorded revenue less recorded known costs; job forecast also deducts priced wages.'},{label:'Costs including travel, accommodation, meals and printing',recorded:P.costNow,job:P.costJob,remaining:remaining(P.costNow,P.costJob),details:'Includes overheads; wages shown separately.'}])+'</details>';
 return '<section id="pl770" class="fin745 pl770 nosfold" aria-labelledby="pl770Title"><h2 id="pl770Title">P&amp;L · recorded and forecast</h2><p class="fin745-eyebrow">AUD EX GST · '+esc(fmtDate(P.asAt))+'</p>'+warning+'<h3>Customer revenue</h3>'+table(moneyRows(P.rev),{label:'Total revenue',recorded:P.revNow,job:P.revJob})+'<h3>Direct costs · ledger lines</h3>'+table(moneyRows(P.cost),{label:'Direct costs',recorded:P.direct,job:P.directJob})+'<h3>Overheads and wages</h3>'+table([overhead,wages])+results+'<details class="units925-edit"><summary>More info · full ledger, recovery and reconciliation</summary>'+recoveryDetails976(originalPl.apply(this,arguments))+'</details></section>';};
const originalCosts976=renderCosts;
renderCosts=function(){const result=originalCosts976.apply(this,arguments),pane=document.getElementById('pane-costs'),card=pane?.querySelector('#pl770'),heading=pane?.querySelector('.hubhead');if(card&&heading){const fold=card.closest('details');heading.after(card);if(fold&&!fold.querySelector('.card'))fold.remove();}return result;};
})(typeof window!=='undefined'?window:null);
