/* Author: Andrew Fisher. Every reference must retain its modern drawer; catch handled warnings too. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),Module=require('module');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));hm._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++;(counts.denied||=[]).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const{open}=hm.exports;
const out=process.env.OUT935||'/workspace/private-bughunt935/proof',pageFile=process.env.PAGE||'/workspace/private-bughunt935/candidate935.html';fs.mkdirSync(out,{recursive:true});
(async()=>{const s=await open({pageFile,hash:'#today',W:1440,H:1000,mobile:false,gl:false}),p=s.page,warnings=[];p.on('console',m=>{if(m.type()==='warning')warnings.push(m.text());});try{
 await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live'&&window.Items933,null,{timeout:90000});
 let refs=await p.evaluate(()=>holdAssets(()=>{window.__drawer935Record=JSON.stringify(S);return allAssets().map(a=>a.key);}));if(process.env.REF935)refs=refs.filter(r=>r===process.env.REF935);const result=[];
 for(let i=0;i<refs.length;i+=8){const batch=await p.evaluate(keys=>holdAssets(()=>{const results=[],prior=routing;routing=true;try{for(const ref of keys){const a=assetOf(ref);openAsset(ref);const drawer=document.getElementById('drawer'),m=gcModel925(a);const visible=e=>e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden';results.push({ref,modern:!!drawer.querySelector('.sum816')&&!!drawer.querySelector('.folds816'),modelIds:m.rows.filter(u=>u.physical).map(u=>u.id),cards:[...drawer.querySelectorAll('[data-unit925-id]')].map(n=>n.dataset.unit925Id),sourceIdsMatch:[...drawer.querySelectorAll('[data-unit925-id]')].every(n=>!n.dataset.unit925Id||m.rows.some(u=>u.id===n.dataset.unit925Id)),duplicatePhotoGroups:Drawer935.aliases(m.rows).filter(pair=>[pair.id,pair.legacy].every(id=>[...drawer.querySelectorAll('.dphunit .dphgrid')].some(g=>g.dataset.dphunit===id))).length,selectedItem:drawer.querySelector('[data-unit925-description]')?.value||'',groupExpected:m.groups.length>0,unitPanel:!!drawer.querySelector('[data-units925]'),photoGroups:[...drawer.querySelectorAll('.dphunit>.dphuh,.dphunit>summary .dphuh')].map(e=>e.textContent),visibleEditPhotoControls:[...drawer.querySelectorAll('input[data-item933-add],[data-item933-remove],[data-dphadd],[data-dphdel],[data-dphcap]')].filter(visible).length,readOnly:SYNC.readonly,legacyQuickUploader:!!drawer.querySelector('#ph816in')});}}finally{routing=prior;}return results;}),refs.slice(i,i+8));result.push(...batch);console.log('CHECKED '+result.length+'/'+refs.length);}
 fs.writeFileSync(path.join(out,'all-drawers.json'),JSON.stringify({result,warnings,errors:s.errors},null,2));assert(result.every(r=>r.modern),'modern drawer missing');assert(result.every(r=>r.sourceIdsMatch&&r.duplicatePhotoGroups===0),'source identity or duplicate photo group');assert(result.every(r=>r.unitPanel===r.groupExpected),'unit panels mismatch');assert(result.every(r=>r.readOnly&&r.visibleEditPhotoControls===0),'visible editable photo controls on view link');assert(!warnings.some(w=>/drawer|TypeError|Cannot read/i.test(w)),warnings.join('\n'));
 const visuals=[];for(const W of [1440,390]){await p.setViewportSize({width:W,height:W===390?844:1000});for(const ref of ['WC09','WC20','T0103','P03']){await p.evaluate(ref=>holdAssets(()=>openAsset(ref)),ref);await p.waitForTimeout(100);await p.locator('[data-units925]').screenshot({path:path.join(out,ref+'-'+W+'.png')});visuals.push({W,ref,modern:await p.locator('#drawer .sum816').count()});}}
 const version=await p.evaluate(async()=>await(await fetch('/api/version')).json());version.level='edit';await p.route('**/api/version**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(version)}));await p.waitForTimeout(4500);
 const capture=await p.evaluate(()=>holdAssets(()=>{SYNC.readonly=false;SYNC.level='edit';capability=()=> 'edit';mayWrite=()=>true;whoAmI=()=> 'Captured test';openAsset('WC09');const drawer=document.getElementById('drawer'),id=gcUnits925(assetOf('WC09')).find(u=>u.assetNo==='1268858').id,group=[...drawer.querySelectorAll('.dphunit')].find(g=>g.querySelector('.dphgrid')?.dataset.dphunit===id),caps=[...group.querySelectorAll('[data-dphcap]')],del=group.querySelector('[data-dphdel]'),captures=[];photoLinkPut=p=>captures.push({action:'caption',id:p.id,unit:p.unit,slot:p.slot});photoLinkRemove=(r,p)=>captures.push({action:'remove',id:p.id,unit:p.unit,slot:p.slot});bump=()=>{};if(caps[0]){caps[0].value='Captured caption';caps[0].onblur();}if(del)del.click();return{groups:[...drawer.querySelectorAll('.dphunit .dphgrid')].map(g=>g.dataset.dphunit||''),captionHomes:caps.map(c=>c.dataset.dphunit),captures,recordSame:__drawer935Record===JSON.stringify(S),changed:Object.keys(S).filter(k=>JSON.stringify(S[k])!==JSON.stringify(JSON.parse(__drawer935Record)[k])),stamps:S.stamps};}));fs.writeFileSync(path.join(out,'capture-debug.json'),JSON.stringify(capture,null,2));assert(capture.recordSame);assert.equal(capture.captionHomes.length,2);assert(capture.captionHomes.every(u=>u==='1268858'));assert.equal(capture.captures.length,2);assert(capture.captures.every(p=>p.unit==='1268858'));await p.locator('[data-units925]').screenshot({path:path.join(out,'WC09-edit-390.png')});
 const final=await p.evaluate(()=>({recordSame:__drawer935Record===JSON.stringify(S),readonly:SYNC.readonly}));assert(final.recordSame);assert.equal(s.errors.length,0);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({pageSHA:require('crypto').createHash('sha256').update(fs.readFileSync(pageFile)).digest('hex'),count:refs.length,result,visuals,capture,final,warnings,errors:s.errors,requests:s.counts},null,2));console.log('PASS all references modern; record unchanged; no caught drawer warnings');
 }finally{await s.browser.close();}})().catch(e=>{console.error(e.stack);process.exitCode=1});
