// Author: Andrew Fisher. Independent daily availability regressions; isolated records only.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../availability988.js'),'utf8');
const context={console,module:{exports:{}},exports:{}};vm.createContext(context);
vm.runInContext(source+'\n;this.__staff988=typeof DailyStaff988!=="undefined"?DailyStaff988:module.exports;',context);
const api=context.__staff988,copy=value=>JSON.parse(JSON.stringify(value));
assert.equal(typeof api?.create,'function','DailyStaff988 exports isolated model factory');
let checks=0;const results=[];
function test(name,run){run();checks++;results.push(name);}
const iso='2026-10-13',other='2026-10-14';
const person=(name,id=name)=>({name,key:name.trim().toLowerCase(),sourceIds:[id],windows:[{start:'06:00',finish:'14:00'}],timeUnknown:false});
function fixture(){
 const saved={},legacy={},rosters={},writes=[];let ready=true;
 const env={get:d=>saved[d],legacy:d=>legacy[d],roster:d=>rosters[d]||[],ready:()=>ready,write:(d,value)=>{writes.push({day:d,value:copy(value)});saved[d]=copy(value);return true;}};
 const model=api.create(env);return {model,saved,legacy,rosters,writes,env,setReady:v=>ready=v};
}
test('Exact selected day uses only that day\'s named roster',()=>{const f=fixture();f.rosters[iso]=[person('Andrew Fisher'),person('Scott')];f.rosters[other]=[person('Different person')];const d=f.model.day(iso);assert.equal(d.count,2);assert.deepEqual(copy(d.names),['Andrew Fisher','Scott']);assert.equal(d.day,iso);assert(d.valid&&d.ready);assert.equal(f.writes.length,0);});
test('A rosterless date remains unknown rather than zero',()=>{const d=fixture().model.day(iso);assert.equal(d.count,null);assert.deepEqual(copy(d.names),[]);});
test('An explicitly recorded zero remains zero even when a roster exists',()=>{const f=fixture();f.rosters[iso]=[person('Andrew Fisher')];f.saved[iso]={count:0,names:[]};assert.equal(f.model.day(iso).count,0);assert.deepEqual(copy(f.model.day(iso).names),[]);});
test('An explicit legacy zero remains zero',()=>{const f=fixture();f.rosters[iso]=[person('Andrew Fisher')];f.legacy[iso]={count:0,names:[]};assert.equal(f.model.day(iso).count,0);});
test('Explicit unknown availability does not become inferred attendance',()=>{const f=fixture();f.rosters[iso]=[person('Andrew Fisher')];f.saved[iso]={count:null,names:[]};assert.equal(f.model.day(iso).count,null);});
test('Saved names and total remain explicit when the roster changes',()=>{const f=fixture();f.saved[iso]={count:2,names:['Andrew Fisher']};f.rosters[iso]=[person('Andrew Fisher'),person('Scott')];const d=f.model.day(iso);assert.deepEqual(copy(d.names),['Andrew Fisher']);assert.equal(d.count,2);assert.equal(d.unnamed,1);});
test('Legacy unnamed positions fill only an exact set of remaining roster names',()=>{const f=fixture();f.legacy[iso]={count:3,names:['Andrew Fisher','','']};f.rosters[iso]=[person('Andrew Fisher'),person('Scott'),person('Wayne')];const d=f.model.day(iso);assert.equal(d.count,3);assert.deepEqual(copy(d.names),['Andrew Fisher','Scott','Wayne']);assert.equal(d.unnamed,0);assert.deepEqual(f.legacy[iso].names,['Andrew Fisher','','']);});
test('Ambiguous legacy unnamed positions do not select arbitrary roster people',()=>{const f=fixture();f.legacy[iso]={count:2,names:['Andrew Fisher','']};f.rosters[iso]=[person('Andrew Fisher'),person('Scott'),person('Wayne')];const d=f.model.day(iso);assert.equal(d.count,2);assert.deepEqual(copy(d.names),['Andrew Fisher']);assert.equal(d.unnamed,1);});
test('New explicit daily record takes precedence over the archived legacy day mapping',()=>{const f=fixture();f.legacy[iso]={count:3,names:['Legacy One','Legacy Two','Legacy Three']};f.saved[iso]={count:1,names:['Current One']};assert.deepEqual(copy(f.model.day(iso).names),['Current One']);assert.equal(f.model.day(iso).count,1);});
test('Missing shared collections cannot show a ready availability number',()=>{const f=fixture();f.rosters[iso]=[person('Andrew Fisher')];f.setReady(false);const d=f.model.day(iso);assert.equal(d.ready,false);assert.equal(d.count,null);});
test('Readiness recovery rereads roster and returns available people',()=>{const f=fixture();f.rosters[iso]=[person('Andrew Fisher')];f.setReady(false);f.model.day(iso);f.setReady(true);const d=f.model.day(iso);assert(d.ready);assert.equal(d.count,1);});
test('Invalid real calendar dates are rejected, not normalised into another day',()=>{const f=fixture();for(const bad of ['2026-02-30','2026-13-01','2026-10-00','13/10/2026','2026-10-13junk',''])assert.equal(f.model.day(bad).valid,false,bad);});
test('An explicit save normalises names and writes only its selected daily availability',()=>{const f=fixture();f.legacy[iso]={count:1,names:['Legacy']};f.saved[other]={count:1,names:['Tomorrow']};const beforeLegacy=copy(f.legacy),beforeOther=copy(f.saved[other]);const d=f.model.day(iso),r=f.model.save(iso,{count:2,names:['  Andrew   Fisher  ','Scott']},d.token);assert.equal(r.kept,true);assert.equal(f.writes.length,1);assert.equal(f.writes[0].day,iso);assert.equal(f.writes[0].value.count,2);assert.deepEqual(f.writes[0].value.names,['Andrew Fisher','Scott']);assert.deepEqual(f.legacy,beforeLegacy);assert.deepEqual(f.saved[other],beforeOther);});
test('Same person entered with different case and spaces cannot be saved twice',()=>{const f=fixture(),d=f.model.day(iso);const r=f.model.save(iso,{count:2,names:['Andrew Fisher',' ANDREW   FISHER ']},d.token);assert.equal(r.kept,false);assert(r.reason);assert.equal(f.writes.length,0);});
test('More named workers than availability is rejected',()=>{const f=fixture(),d=f.model.day(iso);assert.equal(f.model.save(iso,{count:1,names:['Andrew','Scott']},d.token).kept,false);assert.equal(f.writes.length,0);});
test('Negative, fractional, infinite and over-limit totals are rejected',()=>{const f=fixture();for(const count of [-1,1.5,51,NaN,Infinity,'2'])assert.equal(f.model.save(iso,{count,names:[]},f.model.day(iso).token).kept,false,String(count));assert.equal(f.writes.length,0);});
test('Names cannot be supplied without a known total',()=>{const f=fixture();assert.equal(f.model.save(iso,{count:null,names:['Andrew']},f.model.day(iso).token).kept,false);assert.equal(f.writes.length,0);});
test('Zero workers can be saved deliberately',()=>{const f=fixture();f.rosters[iso]=[person('Andrew Fisher')];assert.equal(f.model.save(iso,{count:0,names:[]},f.model.day(iso).token).kept,true);assert.equal(f.model.day(iso).count,0);});
test('Unknown workers can remain a known total without invented names',()=>{const f=fixture();assert.equal(f.model.save(iso,{count:3,names:['Andrew']},f.model.day(iso).token).kept,true);assert.equal(f.model.day(iso).count,3);assert.equal(f.model.day(iso).unnamed,2);assert.deepEqual(copy(f.model.day(iso).names),['Andrew']);});
test('Stale saved names reject a concurrent overwrite',()=>{const f=fixture();f.saved[iso]={count:1,names:['Andrew']};const token=f.model.day(iso).token;f.saved[iso]={count:1,names:['Scott']};const r=f.model.save(iso,{count:1,names:['Wayne']},token);assert.equal(r.kept,false);assert(r.reason);assert.equal(f.writes.length,0);assert.deepEqual(f.saved[iso].names,['Scott']);});
test('A change in default roster invalidates a pending save token',()=>{const f=fixture();f.rosters[iso]=[person('Andrew')];const token=f.model.day(iso).token;f.rosters[iso].push(person('Scott'));assert.equal(f.model.save(iso,{count:1,names:['Andrew']},token).kept,false);assert.equal(f.writes.length,0);});
test('A change in legacy availability invalidates a pending save token',()=>{const f=fixture();f.legacy[iso]={count:1,names:['Andrew']};const token=f.model.day(iso).token;f.legacy[iso]={count:2,names:['Andrew','Scott']};assert.equal(f.model.save(iso,{count:1,names:['Andrew']},token).kept,false);assert.equal(f.writes.length,0);});
test('Loss of readiness blocks save even with the old token',()=>{const f=fixture();f.rosters[iso]=[person('Andrew')];const token=f.model.day(iso).token;f.setReady(false);assert.equal(f.model.save(iso,{count:1,names:['Andrew']},token).kept,false);assert.equal(f.writes.length,0);});
test('Invalid calendar date cannot write a daily record',()=>{const f=fixture();assert.equal(f.model.save('2026-02-30',{count:0,names:[]},f.model.day('2026-02-30').token).kept,false);assert.equal(f.writes.length,0);});
test('Malformed names, excessive length and embedded newlines are rejected',()=>{const f=fixture();for(const names of [null,'Andrew',[42],['a'.repeat(101)],['Andrew\nScott']])assert.equal(f.model.save(iso,{count:2,names},f.model.day(iso).token).kept,false);assert.equal(f.writes.length,0);});
test('A rejected write is not reported as saved',()=>{const f=fixture();f.env.write=()=>false;const r=f.model.save(iso,{count:0,names:[]},f.model.day(iso).token);assert.equal(r.kept,false);});
test('Return to roster stores an explicit following-roster mode',()=>{const f=fixture();f.saved[iso]={count:0,names:[]};f.rosters[iso]=[person('Andrew')];const r=f.model.saveRoster(iso,f.model.day(iso).token);assert.equal(r.kept,true);assert.equal(f.writes.length,1);assert.equal(f.writes[0].value.mode,'roster');assert.equal(f.model.day(iso).count,1);f.rosters[iso].push(person('Scott'));assert.equal(f.model.day(iso).count,2);assert.deepEqual(copy(f.model.day(iso).names),['Andrew','Scott']);});
test('Roster mode becomes unknown when no named roster remains',()=>{const f=fixture();f.saved[iso]={mode:'roster',count:1,names:['Old name']};assert.equal(f.model.day(iso).count,null);assert.deepEqual(copy(f.model.day(iso).names),[]);});
test('Return to roster rejects stale token and missing roster',()=>{const f=fixture();assert.equal(f.model.saveRoster(iso,f.model.day(iso).token).kept,false);f.rosters[iso]=[person('Andrew')];const token=f.model.day(iso).token;f.saved[iso]={count:0,names:[]};assert.equal(f.model.saveRoster(iso,token).kept,false);assert.equal(f.writes.length,0);});
test('Reading or editing a returned model cannot mutate source records',()=>{const f=fixture();f.saved[iso]={count:2,names:['Andrew','Scott']};f.rosters[iso]=[person('Andrew')];const before=JSON.stringify([f.saved,f.legacy,f.rosters]);const d=f.model.day(iso);d.names[0]='Changed';if(d.roster[0])d.roster[0].name='Changed';assert.equal(JSON.stringify([f.saved,f.legacy,f.rosters]),before);assert.equal(f.writes.length,0);});
console.log(JSON.stringify({author:'Andrew Fisher',pass:true,checks,results,liveWrites:0}));
