// Author: Andrew Fisher. Network-free native persistence and accounting-boundary tests.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const html=fs.readFileSync(process.argv[2],'utf8');
const fn=name=>{const at=html.indexOf('function '+name+'(');if(at<0)throw Error('Missing '+name);const end=html.indexOf('\n}',at);const s=html.slice(at,end+2);new vm.Script(s);return s;};
let passes=0;const test=(name,f)=>{f();passes++;console.log('PASS '+name);};
for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/type=["'](?:application\/json|importmap)/i.test(m[1])||!m[2].trim())continue;new vm.Script(m[2]);}
const clone=x=>JSON.parse(JSON.stringify(x));
const ctx={console,Date,Math,JSON,Set,Map,Number,String,Object,Array,RegExp,
 DATA:{weeks:[{sheet:'Test week',start:'2026-10-05',end:'2026-10-11',phase:'Build'}],assets:[]},COMMITTED:{deleted:{}},
 FCOM:{collections:[],dockets:[],service_notes:[]},state:{},S:{operator:'Andrew Fisher via Codex',fenceDockets:[],serviceNotes:[],fenceCollections:[],deleted:{},aside:{},by:{},stamps:{}},
 ASIDE_COLLS:{fenceCollections:'id'},FENCE_PRIVATE_VIEW:{book:'red',date:'2026-01-01',evidence:'missing',lastQ:'old'},COLLECT_WORDS:{mesh_panel:['mesh panel','mesh panels'],base:['base','bases'],clamp:['clamp','clamps'],brace:['brace','braces']},FCOL:[],
 mayWrite:()=>true,whoAmI:()=>ctx.S.operator,flash:()=>{},bump:()=>{},todayIso:()=> '2026-10-08',weekOf:()=>({sheet:'Test week'}),
 stampIt:(field,id,who)=>{ctx.S.stamps[field+'/'+id]='2026-10-08T00:00:00.000Z';ctx.S.by[field+'/'+id]=who;},
 fenceRateFor:()=>({value:1}),fenceCostFor:()=>({value:1}),MAX_RATE:1e6,
 money:x=>String(x),fmtStamp:x=>x,fmtNum:x=>String(x),emptyKey:()=>false,
 blank:()=>({operator:'',fenceDockets:[],serviceNotes:[],fenceCollections:[],deleted:{},stamps:{},by:{},added:[],aside:{}}),
 keysOf:(a,b)=>[...new Set([...Object.keys(a||{}),...Object.keys(b||{})])],
 UNDO:'back/',tombed:(s,id)=>!!s.deleted?.[id]&&!(s.deleted?.['back/'+id]>s.deleted[id]),
 safeNum:(x)=>Number(x),IMPORT_MAX_ITEMS:20000,IMPORT_MAX_TEXT:20000,
 SYNC_COLLS:{fenceCollections:{kind:'list',id:c=>c.id,get:()=>ctx.S.fenceCollections}},
 docIdOf:x=>x, COST_FENCE_CAT:'test',PO_SRC:{},normBranch:x=>x,
 allDockets:()=>ctx.S.fenceDockets.map(d=>({...d,usable:!ctx.docketProblems(d).length,...ctx.costDocket(d)})),
 serviceNoteRows:()=>ctx.S.serviceNotes.map(n=>({...n,docket_no:n.note_no}))};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'capture898.js'),'utf8'),ctx);
for(const n of ['afterStamp','tombedHere','nextIdFor','nextDocketId','bookNumbers','paperNoTaken','collectionRows','recordHireAgreement','recordDocket','docketQuantity','docketProblems','costDocket','docketCostLines','recordsFrom','mergeRecords','exportRecord','validateRecords','toDocs','fromDocs','setAside','putBack','tomb','untomb']){
 vm.runInContext(fn(n),ctx);
}
const raw={collection_no:'91001',date:'2026-10-08',location:'Example area',collected:{mesh_panel:3,base:4,clamp:2},note:'Counts transcribed; no commercial adjustment.'};
let c;
test('collection creates counts only with native author, stable FC id and stamp',()=>{c=ctx.recordCollection(raw);assert(c);assert(c.id.startsWith('FC-AFV-'));assert.equal(c.recorded_by,'Andrew Fisher via Codex');for(const k of ['quantities','cost','cost_total','rate','metres'])assert(!(k in c));assert.equal(ctx.S.by['fenceCollections/'+c.id],ctx.S.operator);});
test('duplicate across books does not create another row',()=>{assert.equal(ctx.recordCollection(raw),null);assert.equal(ctx.recordHireAgreement({docket_no:raw.collection_no,components_only:true,date:raw.date,location:raw.location,components:{base:1}}),null);assert.equal(ctx.S.fenceCollections.length,1);});
test('invalid counts and dates are refused, explicit zero retained',()=>{for(const bad of [-1,1.2,Infinity,'bad',true])assert.equal(ctx.recordCollection({...raw,collection_no:'91002',collected:{base:bad}}),null);assert.equal(ctx.recordCollection({...raw,collection_no:'91002',date:'2026-02-30'}),null);assert.equal(ctx.recordCollection({...raw,collection_no:'91002',collected:{base:0}}),null);const x=ctx.recordCollection({...raw,collection_no:'91002',collected:{base:2,clamp:0}});assert.equal(x.collected.clamp,0);});
test('native collection reader and source-number registry see the saved paper',()=>{assert.equal(ctx.collectionRows().length,2);assert(ctx.bookNumbers().includes(raw.collection_no));});
test('component-only agreement has empty charge quantities and adds no P&L line',()=>{const d=ctx.recordHireAgreement({docket_no:'92001',date:raw.date,location:raw.location,components_only:true,quantities:{},components:{base:8,clamp:6,brace:4}});assert(d);assert.equal(Object.keys(d.quantities).length,0);assert.equal(ctx.docketProblems(d).length,0);const priced=ctx.costDocket(d);assert.equal(priced.cost_state,'nothing to price');assert.equal(priced.lines.length,0);assert.equal(priced.margin,null);assert.equal(ctx.docketCostLines().length,0);});
test('components-only flag rejects charge quantities and malformed components',()=>{for(const props of [{quantities:{scrim:10},components:{base:2}},{quantities:{},components:{base:Infinity}},{quantities:{},components:{base:-1}},{quantities:{},components:{base:0}},{quantities:{},components:{unknown:2}}])assert.equal(ctx.recordHireAgreement({docket_no:'92002',date:raw.date,location:raw.location,components_only:true,...props}),null);});
test('ordinary quantified agreement keeps the existing cost path',()=>{const d=ctx.recordHireAgreement({docket_no:'92003',date:raw.date,location:raw.location,quantities:{scrim:10},components:{brace:2}});assert(d);assert.equal(d.quantities.scrim,10);assert(!d.components_only);assert.equal(ctx.costDocket(d).cost_total,10);});
test('native sync serialisation round trips collection rows',()=>{const docs=ctx.toDocs('fenceCollections');const rows=ctx.fromDocs('fenceCollections',docs);assert.equal(JSON.stringify(clone(rows)),JSON.stringify(clone(ctx.S.fenceCollections)));});
test('full and envelope-only exports retain collection rows',()=>{const out=ctx.exportRecord();assert.equal(out.fence_collections.length,2);assert.equal(ctx.recordsFrom(out).fenceCollections.length,2);delete out.records;assert.equal(ctx.recordsFrom(out).fenceCollections.length,2);});
test('import validation accepts collections and rejects malformed counts',()=>{const v=ctx.validateRecords({fenceCollections:[clone(c)]});assert.deepEqual(clone(v),[]);const b=ctx.validateRecords({fenceCollections:[{...clone(c),collected:{base:-2}}]});assert(b.some(x=>/collected counts/.test(x)));});
test('two-way native merge retains collections and does not duplicate identical rows',()=>{const a={fenceCollections:[clone(c)]},b={fenceCollections:[clone(c)]};const merged=ctx.mergeRecords(a,b).merged;assert.equal(merged.fenceCollections.length,1);assert.equal(ctx.mergeRecords({},a).merged.fenceCollections.length,1);assert.equal(ctx.mergeRecords(a,{}).merged.fenceCollections.length,1);});
test('conflicting imports remain distinct rather than silently overwriting',()=>{const x=ctx.mergeRecords({fenceCollections:[clone(c)]},{fenceCollections:[{...clone(c),collected:{base:9}}]});assert.equal(x.merged.fenceCollections.length,2);assert(x.report.clashes.length);});
test('tombstone survives stale merge and local reader; later restore works',()=>{const d={fenceCollections:[clone(c)],deleted:{[c.id]:'2026-10-08T01:00:00.000Z'}};assert.equal(ctx.mergeRecords(d,{fenceCollections:[clone(c)]}).merged.fenceCollections.length,0);ctx.S.deleted[c.id]='2026-10-08T01:00:00.000Z';assert(!ctx.collectionRows().some(r=>r.id===c.id));ctx.S.deleted['back/'+c.id]='2026-10-08T02:00:00.000Z';assert(ctx.collectionRows().some(r=>r.id===c.id));});
test('IDs do not recycle removed or restored collection IDs',()=>{ctx.S.deleted['FC-AFV-0042']='2026-10-08T00:00:00.000Z';assert.equal(ctx.nextCollectionId898(),'FC-AFV-0043');});
test('stored import counts reject strings that component totals cannot consume',()=>{assert(ctx.validateRecords({fenceCollections:[{...clone(c),collected:{base:'2'}}]}).some(x=>/collected counts/.test(x)));assert(!ctx.fenceComponentsOnly898({components_only:true,quantities:{},components:{base:'2'}}));});
test('collection save selects blue book and clears stale filters',()=>{ctx.FENCE_PRIVATE_VIEW.book='red';ctx.FENCE_PRIVATE_VIEW.date='2026-01-01';ctx.FENCE_PRIVATE_VIEW.evidence='missing';ctx.state.q='old';ctx.recordCollection({...raw,collection_no:'91003'});assert.equal(ctx.FENCE_PRIVATE_VIEW.book,'blue');assert.equal(ctx.FENCE_PRIVATE_VIEW.date,'');assert.equal(ctx.FENCE_PRIVATE_VIEW.evidence,'all');assert.equal(ctx.state.q,'');});
test('reader honours base tombstones on conflicting variants',()=>{const variant={...clone(c),id:c.id+'·abcd'};ctx.S.fenceCollections.push(variant);ctx.S.deleted[c.id]='2026-10-08T03:00:00.000Z';assert(!ctx.collectionRows().some(r=>r.id===variant.id));delete ctx.S.deleted[c.id];});
test('set-aside and put-back preserve collection data and paper identity',()=>{const target=ctx.S.fenceCollections.find(x=>x.collection_no==='91003');assert(ctx.setAside('fenceCollections',target.id,ctx.S.operator));assert(!ctx.collectionRows().some(x=>x.id===target.id));assert(ctx.S.aside[target.id].rec.collection_no==='91003');assert(ctx.putBack(target.id,ctx.S.operator));assert(ctx.collectionRows().some(x=>x.id===target.id));});
let scrimInput,work;
test('reviewed service scrim adds scrim only at native rates, one source paper',()=>{const hire=ctx.recordHireAgreement({docket_no:'93001',date:'2026-10-06',location:'Reviewed example area',quantities:{clean:100}});const note={id:'N-EX-0001',note_no:'94001',date:raw.date,week:'Test week',location:hire.location,labour_hours:2,metres:100,recorded_by:ctx.S.operator,recorded_on:raw.date};ctx.S.serviceNotes.push(note);const hn=ctx.allDockets().find(d=>d.id===hire.id),nn=ctx.serviceNoteRows().find(n=>n.id===note.id);scrimInput={service_id:note.id,related_hire_id:hire.id,metres:100,expected_service:ctx.serviceScrimSource898(nn,'service'),expected_hire:ctx.serviceScrimSource898(hn,'hire')};work=ctx.recordServiceScrim898(scrimInput);assert(work);assert.equal(work.docket_no,null);assert.equal(work.quantities.scrim,100);assert(!('clean' in work.quantities));assert.equal(ctx.servicePaperForWork898(work).note_no,'94001');assert.equal(ctx.bookNumbers().filter(n=>n==='94001').length,1);assert.equal(ctx.costDocket(work).cost_total,100);assert.equal(ctx.S.serviceNotes.length,1);assert.equal(ctx.docketProblems(work).length,0);});
test('service work duplicate, stale review and inferred quantity are refused',()=>{assert.equal(ctx.recordServiceScrim898(scrimInput),null);assert.equal(ctx.recordServiceScrim898({...scrimInput,expected_service:{}}),null);assert.equal(ctx.recordServiceScrim898({...scrimInput,metres:99}),null);});
test('service-work metadata survives native sync and records-less export',()=>{const ex=ctx.exportRecord();delete ex.records;const r=ctx.recordsFrom(ex).fenceDockets.find(d=>d.id===work.id);assert.equal(r.source_operation_id,work.source_operation_id);assert.equal(r.related_hire_id,work.related_hire_id);assert.equal(r.docket_no,null);});
test('actual hosted Export button payload contains collections and source metadata',()=>{let downloaded=null;const button={};ctx.$=()=>button;ctx.SYNC={backend:{},first:new Set(['fenceCollections']),dl:{save:p=>{downloaded=p;return Promise.resolve();}}};ctx.save=()=>true;ctx.renderTabs=()=>{};const start=html.indexOf('let EXPORT_SEQ = 0;'),end=html.indexOf('\n};',start);assert(start>=0&&end>start);vm.runInContext(html.slice(start,end+3),ctx);button.onclick();assert(downloaded);const out=JSON.parse(downloaded.data);assert(out.fence_collections.some(r=>r.id===c.id));assert(out.records.fenceCollections.some(r=>r.id===c.id));assert(out.fence_dockets.some(d=>d.source_operation_id===work.source_operation_id));downloaded=null;ctx.SYNC.first.clear();button.onclick();assert.equal(downloaded,null);});
test('key order alone does not create imported collection variants',()=>{const reversed=Object.fromEntries(Object.entries(clone(c)).reverse());reversed.collected=Object.fromEntries(Object.entries(reversed.collected).reverse());const merged=ctx.mergeRecords({fenceCollections:[clone(c)]},{fenceCollections:[reversed]});assert.equal(merged.merged.fenceCollections.length,1);assert.equal(merged.report.clashes.length,0);});
test('conflicting copies of one collection number are unusable',()=>{const keep=ctx.S.fenceCollections;ctx.S.fenceCollections=[clone(c),{...clone(c),id:'FC-OTHER-0001',collected:{base:99}}];const rows=ctx.collectionRows();assert.equal(rows.length,2);assert(rows.every(r=>r.usable===false));ctx.S.fenceCollections=keep;});
test('set-aside collection number cannot become an ordinary chargeable hire',()=>{ctx.S.aside.example={coll:'fenceCollections',rec:{...clone(c),collection_no:'95001'}};assert.equal(ctx.recordHireAgreement({docket_no:'95001',date:raw.date,location:raw.location,quantities:{clean:1}}),null);});
test('changed service-work quantity is quarantined, never partially priced',()=>{const wrong={...work,quantities:{scrim:125}};assert(ctx.serviceWorkProblems898(wrong).length);assert(ctx.docketProblems(wrong).length);assert.equal(ctx.costDocket(wrong).cost_total,null);assert.equal(ctx.costDocket(wrong).cost_state,'source review required');});
test('source deletion or amendment removes the derived charge until reviewed',()=>{const note=ctx.S.serviceNotes.find(n=>n.id===work.source_service_id);ctx.S.deleted[note.id]='2026-10-08T03:00:00.000Z';assert.equal(ctx.costDocket(work).cost_total,null);assert(ctx.docketProblems(work).length);delete ctx.S.deleted[note.id];note.metres=90;assert.equal(ctx.costDocket(work).cost_total,null);note.metres=100;assert.equal(ctx.costDocket(work).cost_total,100);});
test('source review is an immutable snapshot of input object values',()=>{const hire=ctx.S.fenceDockets.find(d=>d.id===work.related_hire_id);const old=work.source_review.hire.quantities.clean;hire.quantities.clean=99;assert.equal(work.source_review.hire.quantities.clean,old);assert.equal(ctx.costDocket(work).cost_total,null);hire.quantities.clean=100;});
test('service source variants respect their base-ID tombstone',()=>{const original=ctx.S.serviceNotes.find(n=>n.id===work.source_service_id);const variant={...clone(original),id:original.id+'·abcd'};ctx.S.serviceNotes.push(variant);const variantWork={...clone(work),source_service_id:variant.id,source_operation_id:variant.id+':scrim',source_review:{service:ctx.serviceScrimSource898(variant,'service'),hire:clone(work.source_review.hire)}};ctx.S.deleted[original.id]='2026-10-08T05:00:00.000Z';assert.equal(ctx.costDocket(variantWork).cost_total,null);assert(ctx.serviceWorkProblems898(variantWork).length);delete ctx.S.deleted[original.id];ctx.S.serviceNotes=ctx.S.serviceNotes.filter(n=>n!==variant);});
test('identical collection contents under different IDs remain visible conflicts',()=>{const keep=ctx.S.fenceCollections;ctx.S.fenceCollections=[clone(c),{...clone(c),id:'FC-OTHER-0010'}];const rows=ctx.collectionRows();assert.equal(rows.length,2);assert(rows.every(r=>!r.usable));ctx.S.fenceCollections=keep;});
console.log(passes+' native checks passed; no browser, network or operational writes.');
