// Author: Andrew Fisher. Read-only actual-page integration and local native-record capture.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {open}=require(path.resolve(__dirname,'../../toolchain/harness/open_page'));
const out=process.env.OUT924||'/workspace/private-restraint924-browser';fs.mkdirSync(out,{recursive:true});
(async()=>{const s=await open({pageFile:process.env.PAGE,hash:'#today',mobile:true,W:390,H:844});try{const p=s.page;await p.waitForFunction(()=>typeof SYNC!=='undefined'&&SYNC.status==='live'&&window.Restraint924,null,{timeout:180000});
const result=await p.evaluate(()=>{const R=Restraint924,assets=allAssets(),refs=assets.map(a=>({a,units:R.unitsFor(a)})),all=refs.flatMap(r=>r.units),target=refs.find(r=>r.units.length&&R.guideCandidates(r.units[0].item).some(g=>g.page===45))||refs.find(r=>r.units.length&&R.guideCandidates(r.units[0].item).length);const d=programmeDays().find(d=>flow891Build(d).share.length),m=d&&flow891Build(d);const before=m?m.share.map(x=>x.fits):[];if(m){m.deliveries.flatMap(x=>x.refs).forEach(r=>FLOW891.specs[r.key]={bogus:true});const after=flow891Build(d).share;FLOW891.specs={};if(after.some(x=>x.fits===true))throw Error('Truthy legacy specs incorrectly approve sharing');}
window.__r924Target=target&&target.a.key;return {catalogueRows:R.guide.length,refs:refs.length,physicalRows:all.length,missingIdentity:all.filter(u=>!u.id).length,knownSpecs:all.filter(u=>R.actualState(u).verified).length,sourceCandidateRefs:refs.filter(r=>R.guideCandidates((r.a.item_types||[]).join(' ')).length).length,target:window.__r924Target,sharePairs:before.length,truthyLegacyBlocked:true,docsHooks:typeof renderDocs==='function'};});
assert.equal(result.catalogueRows,274);assert.equal(result.missingIdentity,0);assert(result.target,'live equipment with guide references exists');
await p.evaluate(()=>openAsset(__r924Target));await p.locator('#drawer details[data-r924-lazy="unit"]').last().evaluate(el=>{for(let q=el.parentElement;q;q=q.parentElement)if(q.tagName==='DETAILS')q.open=true;});await p.locator('#drawer details[data-r924-lazy="unit"]').last().locator('summary').first().click();await p.locator('#drawer .r924-unit').first().locator('summary').first().click();await p.waitForTimeout(400);
result.unitSourceVisible=await p.locator('#drawer .r924-source').first().isVisible();assert(result.unitSourceVisible);result.drawerOverflow=await p.locator('#drawer').evaluate(e=>e.scrollWidth>e.clientWidth+2);assert(!result.drawerOverflow,'phone drawer horizontally fits');
await p.locator('#drawer .r924-unit').first().scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'phone-unit.png')});
const native=await p.evaluate(()=>{const R=Restraint924,a=assetOf(__r924Target),u=R.unitsFor(a)[0],d=programmeDays().find(d=>dpLoads(d).some(g=>g.kind==='deliveries')),g=dpLoads(d).find(g=>g.kind==='deliveries');const h=timeline841Actions(d,g,1),m=driverModel826(d.iso,null);return {unitId:u.id,unitKey:R.unitDocKey(u.id),nativeDocId:docIdOf(R.unitDocKey(u.id)),timeline:h.includes('data-r924-lazy="load"'),driverCheck:m&&m.checks.some(c=>c.id==='transport-recorded924'),driverWarning:m&&m.warnings.some(w=>/transport|specs|individual/i.test(w.text)),printSupplement:dpPage(d,g,'drv',1,1).includes('r924-paper')};});Object.assign(result,native);assert(native.timeline&&native.driverCheck&&native.printSupplement);assert(native.nativeDocId.length<180);
await p.evaluate(()=>{location.hash='#docs';});await p.waitForSelector('#r924-catalogue');await p.locator('#r924-catalogue>summary').click();await p.locator('[data-r924-catalogue]').fill('Cummins');result.catalogueSearch=await p.locator('[data-r924-catalogue-results]').innerText();assert(result.catalogueSearch.includes('2410 kg'));await p.locator('#r924-catalogue').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'phone-catalogue.png')});

// All mutations below are isolated browser memory with the native saver replaced; the harness blocks every HTTP write.
await p.evaluate(()=>{window.__r924Original={loads:JSON.parse(JSON.stringify(S.loads)),bump,mayWrite,whoAmI,capability,on:SYNC.on,readonly:SYNC.readonly};SYNC.on=false;SYNC.readonly=false;capability=()=> 'edit';mayWrite=()=>true;whoAmI=()=> 'Synthetic browser test';bump=()=>{bump.kept=true};openAsset(__r924Target);});
const unitFold=p.locator('#drawer details[data-r924-lazy="unit"]').last();await unitFold.evaluate(el=>{for(let q=el.parentElement;q;q=q.parentElement)if(q.tagName==='DETAILS')q.open=true;});await unitFold.locator('summary').first().click();const editUnit=p.locator('#drawer .r924-unit').first();await editUnit.locator('summary').first().click();const select=editUnit.locator('[data-r924-field="guideId"]');await select.selectOption({index:1});await editUnit.locator('[data-r924-copy]').click();assert(!(await editUnit.locator('[data-r924-field="verified"]').isChecked()),'source copy never verifies actual unit');await editUnit.locator('[data-r924-field="configuration"]').fill('Synthetic browser fixture only');await editUnit.locator('[data-r924-save]').click();
result.nativeCapture=await p.evaluate(()=>{const R=Restraint924,u=R.unitsFor(assetOf(__r924Target))[0],key=R.unitDocKey(u.id),doc=S.loads[key],native=toDocs('loads')[docIdOf(key)];window.__r924Captured={key,doc:JSON.stringify(doc)};return {saved:!!doc,unchecked:doc.actual.verified===false,modelCopied:!!doc.actual.model,massCopied:doc.actual.massKg>0,nativeKey:native._k===key,sameIdentity:native.unitId===u.id};});assert(Object.values(result.nativeCapture).every(Boolean));
await p.evaluate(()=>{bump=()=>{bump.kept=false};});await editUnit.locator('[data-r924-field="massKg"]').fill('1');await editUnit.locator('[data-r924-save]').click();result.failedSaveRestored=await p.evaluate(()=>JSON.stringify(S.loads[__r924Captured.key])===__r924Captured.doc);assert(result.failedSaveRestored);

await p.evaluate(()=>{const doc=S.loads[__r924Captured.key];window.__r924ExternalMass=doc.actual.massKg+7;doc.actual.massKg=__r924ExternalMass;});await editUnit.locator('[data-r924-save]').click();result.midEditUnitHeld=await p.evaluate(()=>S.loads[__r924Captured.key].actual.massKg===__r924ExternalMass&&[...document.querySelectorAll('#drawer .r924-unit input[type="checkbox"]')].every(x=>!x.checked));assert(result.midEditUnitHeld);await p.evaluate(()=>{S.loads[__r924Captured.key]=JSON.parse(__r924Captured.doc);});
await p.evaluate(()=>{bump=()=>{bump.kept=true};const R=Restraint924,d=programmeDays().find(d=>dpLoads(d).some(g=>g.rows.some(r=>r.a.key===__r924Target))),g=dpLoads(d).find(g=>g.rows.some(r=>r.a.key===__r924Target));window.__r924Load={day:d.iso,id:ldId(d,g)};const host=document.createElement('div');host.id='r924-browser-load';host.style='position:fixed;inset:0;background:white;overflow:auto;z-index:999999;padding:12px';host.innerHTML=R.loadEditor(d,g);document.body.append(host);});
const load=p.locator('#r924-browser-load');await load.locator('details[data-r924-lazy="load"]>summary').click();await load.locator('.r924-truck>summary').click();const truck=load.locator('.r924-truck');for(const [key,value]of Object.entries({id:'Synthetic browser vehicle',source:'Synthetic browser fixture only',deckLengthMm:6000,deckWidthMm:2400,payloadKg:6000,extraMassKg:0,deckHeightMm:1000,heightLimitMm:4300,axleEvidence:'Synthetic test',anchorEvidence:'Synthetic test',restraintEvidence:'Synthetic test'}))await truck.locator('[data-r924-field="'+key+'"]').fill(String(value));
for(const key of ['xMm','yMm','supportMm'])for(const input of await truck.locator('[data-r924-field="'+key+'"]').all())await input.fill('0');for(const key of ['axleChecked','anchorChecked','restraintChecked','completeCargo'])await truck.locator('[data-r924-field="'+key+'"]').check();await truck.locator('[data-r924-plan-save]').click();
result.planCapture=await p.evaluate(()=>{const R=Restraint924,l=__r924Load,key=R.planKey(l.day,l.id),doc=S.loads[key];window.__r924PlanCapture={key,doc:JSON.stringify(doc)};return {saved:!!doc,sameNativeKey:toDocs('loads')[docIdOf(key)]._k===key,noApproval:R.loadAssessment(l.day,l.id,R.findLoad(l.day,l.id)).fits===false,complete:doc.completeCargo===true,acknowledgements:doc.vehicle.axleChecked&&doc.vehicle.anchorChecked&&doc.vehicle.restraintChecked};});assert(Object.values(result.planCapture).every(Boolean));
await p.evaluate(()=>{S.loads[__r924Captured.key].actual.massKg+=1;});await truck.locator('[data-r924-plan-save]').click();result.midEditChangeHeld=await p.evaluate(()=>JSON.stringify(S.loads[__r924PlanCapture.key])===__r924PlanCapture.doc&&[...document.querySelectorAll('#r924-browser-load .r924-truck input[type="checkbox"]')].every(x=>!x.checked));assert(result.midEditChangeHeld);await load.evaluate(el=>el.remove());
await p.evaluate(()=>{const o=__r924Original;S.loads=o.loads;bump=o.bump;mayWrite=o.mayWrite;whoAmI=o.whoAmI;capability=o.capability;SYNC.on=o.on;SYNC.readonly=o.readonly;});
const demob=await p.evaluate(()=>{const R=Restraint924,M=demob816(),day=M.days.find(day=>trucks816(day,'all').length),L=day&&trucks816(day,'all')[0];if(!L)return {available:false};const id=R.demobId(L),g=R.findLoad(day,id),m=demobModel826(day,'all','truck',L.n),x=R.loadAssessment(day,id,g);return {available:true,resolved:!!g,sourceIdStable:R.demobId({...L,n:L.n+100})===id,warning:m.warnings.some(w=>/transport arrangement/.test(w.text)),noApproval:!x.fits,html:trucksHtml816(M.day[day],[L]).includes('data-r924-lazy="load"'),print:sheet816(day,L).includes('restraint approval required')||sheet816(day,L).includes('Restraint approval required')};});result.demob=demob;assert(demob.available&&demob.resolved&&demob.sourceIdStable&&demob.warning&&demob.noApproval&&demob.html&&demob.print);

// Measure the actual A4 supplements under the native print CSS, including a load with many known units.
await p.evaluate(()=>{const R=Restraint924,pairs=programmeDays().flatMap(d=>dpLoads(d).filter(g=>g.kind==='deliveries').map(g=>({d,g,n:R.loadStates(g).states.length}))).sort((a,b)=>b.n-a.n),pick=pairs[0],el=document.getElementById('dayprint');window.__r924PrintOld={html:el.innerHTML,className:el.className};el.className='dpwrap';el.innerHTML=dpPage(pick.d,pick.g,'drv',1,1);document.body.classList.add('printing-day');});await p.emulateMedia({media:'print'});
result.printPages=await p.locator('#dayprint .r924-paper').evaluateAll(rows=>rows.map(el=>({height:Math.round(el.clientHeight),content:Math.round(el.scrollHeight),overflow:el.scrollHeight>el.clientHeight+2})));assert(result.printPages.length&&result.printPages.every(x=>!x.overflow),'restraint supplements fit native A4 pages');await p.locator('#dayprint .r924-paper').first().screenshot({path:path.join(out,'print-supplement.png')});await p.emulateMedia({media:'screen'});await p.evaluate(()=>{const el=document.getElementById('dayprint');el.innerHTML=__r924PrintOld.html;el.className=__r924PrintOld.className;document.body.classList.remove('printing-day');});
result.errors=s.errors;result.requests=s.counts;assert.equal(s.errors.length,0);assert.equal(s.counts.blocked,0);fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}finally{await s.browser.close();}})().catch(e=>{console.error(e.stack);process.exitCode=1});
