// Author: Andrew Fisher. Safety of source matching, identity, unknowns and numerical layout assessment.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const dir=path.join(__dirname,'..'),catalog=JSON.parse(fs.readFileSync(path.join(dir,'guide924.json')));
const context={console,module:{exports:{}},S:{loads:{}},CROW:new Map()};context.globalThis=context;
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(dir,'restraint924_src.js'),'utf8').replace('/* GUIDE924_DATA */[]',JSON.stringify(catalog)),context);
const R=context.Restraint924;let checks=0;const ok=(x,m)=>{assert.ok(x,m);checks++};
ok(R.guide.length===274,'all official catalogue rows retained');
const gen=R.guideCandidates('Cummins 50kVA')[0];ok(gen.massKg===2410&&gen.lengthMm===2850&&gen.page===45,'original p45 values');
const toilet=R.guideCandidates('FWF')[0];ok(toilet.massKg===117&&toilet.page===53,'original p53 values');
ok(R.guideCandidates('Building 6m').length===0,'building maximum not an actual specification');
ok(R.guideCandidates('Forklift 2.5T').some(x=>x.massKg===4000),'lifting capacity not mass');
ok(R.guideCandidates('Light Tower').every(x=>x.description!=='SMC SL80'),'generic tower not cube maximum');
const aid=R.unitId('WC09','event-portables','','12'),bid=R.unitId('WC09','coates','','12');ok(aid!==bid,'owner namespace');ok(aid!==R.unitId('WC31','event-portables','','12'),'reference namespace');ok(!R.unitId('WC09','unknown','',''),'no fabricated index identity');ok(R.unitId('WC09','Event Portables','','12')===aid,'owner normalization');
ok(R.unitDocKey(aid).length<100,'bounded native document key');
const u={id:aid,ref:'WC09',owner:'event-portables',assetNo:'12',item:'FWF',label:'Toilet 12'};
const doc={kind:'restraint924-unit',unitId:aid,identity:R.fingerprintUnit(u),at:'2026-10-08T16:00:00Z',actual:{model:'Merlin',source:'Unit plate and manufacturer transport sheet checked',configuration:'Waste empty; fresh water empty; actual transport assembly',lengthMm:1220,widthMm:1200,heightMm:2220,massKg:117,verified:true,by:'Andrew Fisher',at:'2026-10-08T16:00:00Z'},methodId:'toilet-base',methodConfirmed:true,methodEvidence:'Base/friction and actual method applicability checked'};
const state=()=>R.actualState(u,JSON.parse(JSON.stringify(doc)));ok(state().verified,'fully explicit unit spec');ok(!R.actualState(u,{guideId:toilet.id}).verified,'candidate row never actual');
for(const [k,v] of [['massKg',0],['massKg',-1],['massKg','117'],['massKg',Infinity],['lengthMm',null],['source',''],['configuration',''],['verified',{}],['by',''],['at','bad']]){const d=JSON.parse(JSON.stringify(doc));d.actual[k]=v;ok(!R.actualState(u,d).verified,'reject actual '+k+'='+String(v));}
for(const [k,v] of [['methodConfirmed',{}],['methodEvidence',''],['methodId','missing'],['identity','wrong'],['unitId','wrong'],['kind','other']]){const d=JSON.parse(JSON.stringify(doc));d[k]=v;ok(!R.actualState(u,d).verified,'reject unit '+k);}
const states=[state()];const plan=()=>({kind:'restraint924-load',scope:R.scopeFingerprint(states),by:'Andrew Fisher',at:'2026-10-08T16:00:00Z',vehicle:{id:'TEST VEHICLE — synthetic geometry only',source:'test fixture',deckLengthMm:6000,deckWidthMm:2400,payloadKg:6000,extraMassKg:20,deckHeightMm:1000,heightLimitMm:4300,axleChecked:true,axleEvidence:'Test review',anchorChecked:true,anchorEvidence:'Test review',restraintChecked:true,restraintEvidence:'Test review'},placements:[{unitId:aid,xMm:0,yMm:0,supportMm:0,rotation:0}]});
ok(R.assess(states,plan()).geometryFits,'explicit in-bounds arrangement');ok(R.assess(states,plan()).massKg===137,'support/restraint mass included');ok(R.assess(states,plan()).maxHeightMm===3220,'deck and cargo height');
for(const [k,v] of [['payloadKg',100],['deckLengthMm',1000],['deckWidthMm',1000],['heightLimitMm',3000],['extraMassKg',null],['id',''],['source',''],['axleChecked',{}],['anchorChecked','yes'],['restraintChecked',1],['axleEvidence','']]){const p=plan();p.vehicle[k]=v;ok(!R.assess(states,p).geometryFits,'reject truck '+k+'='+String(v));}
for(const [k,v] of [['xMm',-1],['xMm',Infinity],['yMm','0'],['supportMm',null],['rotation',90],['unitId','not-that-unit']]){const p=plan();p.placements[0][k]=v;ok(!R.assess(states,p).geometryFits,'reject placement '+k);}
let p=plan();p.placements[0].rotation=90;p.placements[0].rotationConfirmed=true;ok(R.assess(states,p).geometryFits,'rotation needs explicit permission');
p=plan();p.scope='stale';ok(!R.assess(states,p).geometryFits,'stale unit data invalidates load check');p=plan();p.placements.push({...p.placements[0]});ok(!R.assess(states,p).geometryFits,'duplicate position fails');ok(!R.assess([],plan()).geometryFits,'empty load not approved');
const u2={...u,id:R.unitId('WC09','event-portables','','13'),assetNo:'13',label:'Toilet 13'},d2={...doc,unitId:u2.id,identity:R.fingerprintUnit(u2)},s2=R.actualState(u2,d2),pair=[state(),s2];p=plan();p.scope=R.scopeFingerprint(pair);p.placements.push({unitId:u2.id,xMm:0,yMm:1200,supportMm:0,rotation:0});ok(R.assess(pair,p).geometryFits,'edge-touching envelopes do not overlap');p.placements[1].yMm=1199;ok(!R.assess(pair,p).geometryFits,'one millimetre overlap fails');p.placements[1].yMm=1200;p.vehicle.payloadKg=250;ok(!R.assess(pair,p).geometryFits,'combined mass includes both units and support mass');
context.S.loads[R.unitDocKey(aid)]={...doc,unitId:'another identity'};ok(R.getDoc(aid)===null,'hashed identity collision cannot read another unit');

// Same-stamp imports and edits must invalidate every safety-relevant value, not only a timestamp.
for(const [k,value] of [['model','Different unit'],['lengthMm',1300],['widthMm',1300],['heightMm',2400],['massKg',500],['baseWidthMm',1000],['configuration','Fresh full'],['source','Other evidence'],['verified',false],['by','Another checker'],['at','2026-10-09T00:00:00Z']]){const d=JSON.parse(JSON.stringify(doc));d.actual[k]=value;const changed=[R.actualState(u,d)];ok(!R.assess(changed,plan()).geometryFits,'same-stamp '+k+' invalidates prior load');const editable=R.editablePlan(changed,plan());ok(editable.vehicle.axleChecked===false&&editable.vehicle.anchorChecked===false&&editable.vehicle.restraintChecked===false&&editable.completeCargo===false,'stale '+k+' clears prior acknowledgements');}
for(const [k,value] of [['methodId','toilet-frame'],['methodEvidence','Different configuration'],['methodConfirmed',false],['guideId','different-reference']]){const d=JSON.parse(JSON.stringify(doc));d[k]=value;ok(!R.assess([R.actualState(u,d)],plan()).geometryFits,'same-stamp '+k+' invalidates prior load');}
ok(R.guideCandidates('FWF Trailer').every(x=>/trailer/i.test(x.description)),'FWF trailer does not inherit single toilet size');
const gu={id:R.unitId('GE01','coates','','G1'),ref:'GE01',owner:'coates',assetNo:'G1',item:'50kVA Generator',label:'50kVA Generator'};
const gd={...doc,unitId:gu.id,identity:R.fingerprintUnit(gu),actual:{...doc.actual,model:'Cummins 50kVA',lengthMm:2850,widthMm:1300,heightMm:1600,baseWidthMm:1300,massKg:2410},methodId:'skid-small'};
const gs=()=>R.actualState(gu,JSON.parse(JSON.stringify(gd)));ok(gs().verified,'p45 model within p44 mass and p43 stability');
for(const [k,value] of [['massKg',3301],['baseWidthMm',null],['baseWidthMm',799],['baseWidthMm',1400]]){const d=JSON.parse(JSON.stringify(gd));d.actual[k]=value;ok(!R.actualState(gu,d).verified,'skid source limit '+k);}
let gp=plan();gp.scope=R.scopeFingerprint([gs()]);gp.placements=[{unitId:gu.id,xMm:0,yMm:550,supportMm:0,rotation:0}];ok(R.assess([gs()],gp).geometryFits,'central single-file skid geometry');gp.placements[0].yMm=0;ok(!R.assess([gs()],gp).geometryFits,'skid off-centre fails');gp.placements[0]={unitId:gu.id,xMm:0,yMm:0,supportMm:0,rotation:90,rotationConfirmed:true};gp.vehicle.deckWidthMm=4000;ok(!R.assess([gs()],gp).geometryFits,'checkbox cannot override longitudinal skid requirement');
const cu={...u,item:'Light cube',label:'Light cube'},cd={...doc,identity:R.fingerprintUnit(cu),methodId:'cube',actual:{...doc.actual,model:'SMC SL80',massKg:1100}};ok(R.actualState(cu,cd).verified,'named SL80 at source maximum');cd.actual.massKg=1101;ok(!R.actualState(cu,cd).verified,'SL80 exceeds maximum');cd.actual.massKg=1000;cd.actual.model='Other light cube';ok(!R.actualState(cu,cd).verified,'SL80 method not generic cube approval');
const wrong={...doc,methodId:'skid-small'};ok(!R.actualState(u,wrong).verified,'unrelated method cannot validate toilet');
const small1={...gd,actual:{...gd.actual,model:'Synthetic matching skid',lengthMm:2000,widthMm:1100,heightMm:1000,baseWidthMm:1100,massKg:1650}},gu2={...gu,id:R.unitId('GE01','coates','','G2'),assetNo:'G2'},small2={...small1,unitId:gu2.id,identity:R.fingerprintUnit(gu2)};
let ss=[R.actualState(gu,small1),R.actualState(gu2,small2)];gp=plan();gp.scope=R.scopeFingerprint(ss);gp.placements=[{unitId:gu.id,xMm:0,yMm:100,supportMm:0,rotation:0},{unitId:gu2.id,xMm:0,yMm:1200,supportMm:0,rotation:0}];ok(R.assess(ss,gp).geometryFits,'source two-abreast max each and aligned same unit');small2.actual={...small2.actual,massKg:1651};ss=[R.actualState(gu,small1),R.actualState(gu2,small2)];gp.scope=R.scopeFingerprint(ss);ok(!R.assess(ss,gp).geometryFits,'two-abreast individual max not single-file max');
small1.methodId='skid-medium';small1.actual={...small1.actual,massKg:2700};small2.methodId='skid-medium';small2.actual={...small2.actual,massKg:2700};ss=[R.actualState(gu,small1),R.actualState(gu2,small2)];gp.scope=R.scopeFingerprint(ss);ok(R.assess(ss,gp).geometryFits,'p47 medium paired method permits 2700kg each below single-file threshold');small2.actual={...small2.actual,massKg:2701};ss=[R.actualState(gu,small1),R.actualState(gu2,small2)];gp.scope=R.scopeFingerprint(ss);ok(!R.assess(ss,gp).geometryFits,'p47 pair rejects a unit above2700kg');gp.placements=[{unitId:gu.id,xMm:0,yMm:650,supportMm:0,rotation:0}];gp.scope=R.scopeFingerprint([ss[0]]);ok(!R.assess([ss[0]],gp).geometryFits,'p47 pair cannot reuse medium method for one2700kg skid');
ok(!R.assess(states,plan()).fits&&R.assess(states,plan()).restraintValidated===false,'all recorded numeric checks never imply complete restraint approval');
for(const method of R.methods){const d={...doc,methodId:method.id};const x=R.assess([R.actualState(u,d)],plan());ok(x.fits===false&&x.restraintValidated===false,'method '+method.id+' cannot auto-approve from checkbox evidence');}
const tu={...u,item:'VMS trailer',label:'VMS trailer'},td={...doc,identity:R.fingerprintUnit(tu),actual:{...doc.actual,model:'A1 Senior',massKg:1851},methodId:'trailer'};ok(!R.actualState(tu,td).verified,'p35 small trailer beyond1850kg requires another assessment');td.actual.massKg=1201;const ts=[R.actualState(tu,td)];let tp=plan();tp.scope=R.scopeFingerprint(ts);tp.placements[0].rotation=90;tp.placements[0].rotationConfirmed=true;ok(!R.assess(ts,tp).geometryFits,'p37 across-deck trailer above1200kg not accepted');
ok(R.guideCandidates('100kVA trailer generator').length===0,'skid table does not describe generator trailer assembly');
context.gcUnits925=()=>[];const slot={kind:'restraint924-unit',slot:true,unitId:R.unitId('WC99','unknown','slot:fixture',''),ref:'WC99',owner:'unknown',item:'FWF',label:'Explicit physical test slot'};context.S.loads[R.unitDocKey(slot.unitId)]=slot;ok(R.unitsFor({key:'WC99'}).length===1,'explicit unallocated physical slot remains on reference');ok(R.unitsFor({key:'WC99',_bookingNumbers801:[]}).length===0,'unnumbered slot does not leak into empty split allocation');ok(R.unitsFor({key:'WC99',_bookingNumbers801:['12']}).length===0,'unnumbered slot not assigned to unrelated numbered split load');
for(const [item,method,mass] of [['FWF','toilet-base',701],['FWF','toilet-blocked',701],['FWF internal frame','toilet-frame',701],['Transport cage','cage',5001],['Building wagon','wagon',3501],['Building','building',5001],['Containerised generator','container',22000]]){const nu={...u,item,label:item},nd={...doc,identity:R.fingerprintUnit(nu),methodId:method,actual:{...doc.actual,model:item,massKg:mass}};ok(!R.actualState(nu,nd).verified,'source family scope bound '+method);}
let bd={...doc,methodId:'building',identity:R.fingerprintUnit({...u,item:'Building',label:'Building'}),actual:{...doc.actual,lengthMm:12001,massKg:2000}};ok(!R.actualState({...u,item:'Building',label:'Building'},bd).verified,'p79 building maximum dimensions');
const explicitLarge={...gd,methodId:'skid-large',actual:{...gd.actual,model:'Atlas Copco 230kVA',massKg:5475}};ok(R.actualState(gu,explicitLarge).verified,'p50 explicit5475kg row not rejected solely by rounded section heading');
ok(R.methods.find(m=>m.id==='container').pages.join(',')==='41,42,52','container references actual F4p52, not sideways skidp51');
const output={checks,passed:checks,catalogueRows:catalog.length,actualSourceExamples:{generator:gen.id,toilet:toilet.id},note:'Truck fixture is synthetic; no GC500 truck capacity or load approval asserted.'};console.log(JSON.stringify(output,null,2));
