// Author: Andrew Fisher. Browser-only named worker selector checks; no saves.
const fs=require('fs'),assert=require('assert/strict');
const {open}=require('../../toolchain/harness/open_page');
(async()=>{const h=await open({pageFile:process.env.PAGE,hash:'#timeline',mobile:process.env.MOB==='1',W:process.env.MOB==='1'?390:1440,H:900});try{
await h.page.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:150000});
const result=await h.page.evaluate(()=>{const native=JSON.stringify(S),savedCapability=capability,readonly=SYNC.readonly;capability=()=> 'edit';SYNC.readonly=false;
try{return {unchanged:JSON.stringify(S)===native,days:['2026-10-12','2026-10-13','2026-10-14'].map(day=>{const m=StaffNames910.day(day),t=document.createElement('template');t.innerHTML=crew883Editor(assetOf('WC09'),day);const task=t.content.querySelector('[data-workers983-selection]'),select=task?.querySelector('[data-crew883-slot]');return {day,count:m.roster.length,summary:t.content.querySelector('.crew883>summary')?.textContent,names:m.names,options:select?[...select.options].slice(1).map(o=>o.textContent):[],buried:!!task?.closest('[data-workers979-task]'),prefilled:t.content.querySelector('[data-crew883-names]')?.value.split('\n'),roles:task?[...task.querySelectorAll('[data-crew883-role]')].filter(x=>!x.closest('[hidden]')).length:0};})};}
finally{capability=savedCapability;SYNC.readonly=readonly;}});
let checks=0;for(const d of result.days){assert(d.count>0);checks++;assert(d.summary.includes(d.count+' scheduled'));checks++;assert(d.options.length>=d.count);checks++;assert(d.names.every(n=>d.options.includes(n)));checks++;assert.deepEqual(d.prefilled,d.names);checks++;assert(!d.buried);checks++;assert.equal(d.roles,0);checks++;}assert(result.unchanged);checks++;assert.equal(h.errors.length,0);checks++;assert.equal(h.counts.blocked,0);checks++;
const out={author:'Andrew Fisher',pass:true,checks,mobile:process.env.MOB==='1',days:result.days.map(d=>({day:d.day,count:d.count,prefilled:true,selectionVisibleWithinWorkers:true})),errors:0,writes:0};if(process.env.OUTDIR){fs.mkdirSync(process.env.OUTDIR,{recursive:true});fs.writeFileSync(process.env.OUTDIR+'/workers.json',JSON.stringify(out,null,2));}console.log(JSON.stringify(out));
}finally{await h.browser.close();}})().catch(e=>{console.error(e.stack);process.exit(1)});
