/* Author: Andrew Fisher. Consolidation moves existing nodes and preserves every photo/action. */
const assert=require('assert/strict'),g=require('../drawer935.js');let n=0;
class Node{constructor(kind='',data={}){this.kind=kind;this.dataset=data;this.children=[];this.parent=null;this.textContent='';this.classList={contains:k=>kind.split(' ').includes(k)};}appendChild(x){if(x.parent)x.remove();this.children.push(x);x.parent=this;return x;}remove(){if(this.parent){this.parent.children.splice(this.parent.children.indexOf(this),1);this.parent=null;}}replaceWith(x){const p=this.parent,i=p.children.indexOf(this);if(x.parent)x.remove();p.children[i]=x;x.parent=p;this.parent=null;}querySelector(q){if(q==='.dphgrid')return this.children.find(n=>n.kind==='dphgrid');if(q===':scope > summary .w')return this.label;return null;}querySelectorAll(q){if(q==='.dphunit')return this.children.filter(x=>x.kind==='dphunit');if(q==='.dphstray')return this.children.filter(x=>x.kind==='dphstray');return[];}}
function fixture(){const body=new Node(),make=id=>{const group=body.appendChild(new Node('dphunit'));group.label=new Node();const grid=group.appendChild(new Node('dphgrid',{dphunit:id}));for(let i=0;i<5;i++)grid.appendChild(new Node('dph dphnone'));return{group,grid};},a=make('canonical'),b=make('12');global.holdAssets=f=>f();global.gcModel925=()=>({rows:[{id:'canonical',assetNo:'12',physical:true}]});return{body,a,b};}
function test(name,fn){fn();n++;console.log('PASS '+name);}
test('a legacy photo replaces only the empty canonical display cell with its handlers intact',()=>{const f=fixture(),photo=new Node('dph',{dphunit:'12',dphcap:'0'});let called=0;photo.onclick=()=>called++;f.b.grid.children[0].replaceWith(photo);g.photos({},f.body);assert.equal(f.a.grid.children[0],photo);assert.equal(photo.dataset.dphunit,'12');photo.onclick();assert.equal(called,1);assert.equal(f.body.children.length,1);});
test('canonical and legacy photos in the same slot both remain visible',()=>{const f=fixture(),current=new Node('dph',{id:'current'}),legacy=new Node('dph',{id:'legacy'});f.a.grid.children[0].replaceWith(current);f.b.grid.children[0].replaceWith(legacy);g.photos({},f.body);assert(f.a.grid.children.includes(current));assert(f.a.grid.children.includes(legacy));assert.equal(f.a.group.label.textContent,'2 photographs');});
test('pending legacy uploads remain queued and are not counted as confirmed photos',()=>{const f=fixture(),pending=new Node('dph dphsending',{dphpending:'queued'});f.b.grid.children[1].replaceWith(pending);g.photos({},f.body);assert(f.a.grid.children.includes(pending));assert.equal(f.a.group.label.textContent,'no photograph yet · 1 queued');});
test('stray-file recovery remains available under the consolidated group',()=>{const f=fixture(),stray=f.b.group.appendChild(new Node('dphstray',{legacy:'12'}));g.photos({},f.body);assert.equal(stray.parent,f.a.group);assert.equal(stray.dataset.legacy,'12');});
test('a second enhancement neither duplicates nor removes photo cells',()=>{const f=fixture(),photo=new Node('dph');f.b.grid.children[0].replaceWith(photo);g.photos({},f.body);const count=f.a.grid.children.length;g.photos({},f.body);assert.equal(f.a.grid.children.length,count);assert.equal(f.a.grid.children.filter(x=>x===photo).length,1);});
console.log(n+' DOM association checks passed');
