  // Author: Andrew Fisher. Existing instrument, scoped to recorded programme work.
  function overallRange853(value, suffix) {
    if (number(value)) return format(value) + (suffix || '');
    if (!value || !number(value.min) || !number(value.max)) return '—';
    return format(value.min) + (value.max !== value.min ? '–' + format(value.max) : '') + (suffix || '');
  }
  function overallReading853(model) {
    const known = model?.state === 'ready' && model.pct;
    return '<span class="tw840-sr">' + escape(known ? overallRange853(model.pct,'%') + ' programme work metres recorded' : 'Overall programme percentage unconfirmed') + '</span><span class="tw840-reading' + (known && model.pct.min !== model.pct.max ? ' tw853-range' : '') + '" data-tw842-pct-kind="' + (known ? 'recorded-work' : 'unknown') + '" aria-hidden="true"><span>' + (known ? overallRange853(model.pct) : '—') + '</span>' + (known ? '<small>%</small>' : '') + '</span>';
  }
  function overallCount853(mode, label, value) {
    return '<button type="button" data-tw840-detail="fencing" data-tw840-mode="' + mode + '" data-tw840-focus="fencing-overall-' + mode + '" aria-label="' + escape(label + ': ' + overallRange853(value,' m') + '. Review all programme work metres.') + '"><span>' + escape(label) + '</span><strong data-tw853-quantity="' + mode + '">' + overallRange853(value) + '<small> m</small></strong><span class="tw840-count-link">Review ' + arrow + '</span></button>';
  }
  function overallFencingCard853(area, title) {
    const model = overallFencing, known = model?.state === 'ready', pct = known ? model.lampPct : null;
    const qualifier = model?.state === 'loading' ? 'Loading record' : !known ? 'Overall percentage unconfirmed' : model.provisional ? 'Provisional programme' : 'Current programme';
    const lampLabel = known ? overallRange853(model.pct,'%') + ' programme work metres recorded. Red lights show reached work milestones; this is not a physical completion sign-off.' : 'Overall programme percentage unconfirmed.';
    const lamps = raceLights846(pct, 'recorded-work').replace(/aria-label="[^"]*"/, 'aria-label="' + escape(lampLabel) + '"');
    const gates = (model?.gates || []).map(gate => '<tr><th scope="row"><button type="button" class="tw846-type-name" data-tw840-fence-detail="' + escape(gate.id) + '" data-tw840-focus="overall-' + escape(gate.id) + '">' + escape(gate.label) + '</button></th><td>' + format(gate.done) + '</td><td>' + format(gate.total) + '</td></tr>').join('');
    const gateCaption = 'Programme gates · separate from metres' + (model?.gates?.some(gate => gate.provisional) ? ' · provisional totals' : '');
    return '<div class="tw846-summary tw853-overall" data-tw853-overall><section class="tw846-display" data-complete="false" data-known="' + String(!!known) + '">' + lamps + title + '<button type="button" class="tw840-display tw846-indicator" data-tw840-detail="fencing" data-tw840-mode="total" data-tw840-focus="fencing-indicator" aria-label="Fencing: open programme work metres and their basis"><span class="tw840-percent">' + overallReading853(model) + '</span><span class="tw840-caption">Programme work metres recorded</span><span class="tw853-qualifier">' + escape(qualifier) + '</span></button></section><div class="tw853-readings"><p class="tw853-scope"><strong data-tw853-total>' + format(model?.total) + ' m</strong> in the current programme</p><div class="tw846-counts tw840-counts" style="grid-template-columns:repeat(2,minmax(0,1fr))">' + overallCount853('done','Recorded',model?.credited) + overallCount853('left','Left',model?.left) + '</div><table class="tw846-table tw853-gates"><caption>' + escape(gateCaption) + '</caption><thead><tr><th scope="col">Type</th><th scope="col">Recorded</th><th scope="col">Total</th></tr></thead><tbody>' + gates + '</tbody></table></div></div>';
  }
  function overallFencingDetail853(mode) {
    const model = overallFencing || {}, label = mode === 'done' ? 'recorded work metres' : mode === 'left' ? 'work metres left' : 'programme work metres';
    const qualification = model.state === 'ready' ? model.provisional ? 'Provisional programme' : 'Current programme' : 'Overall percentage unconfirmed';
    const rows = (model.rows || []).map(row => '<tr><th scope="row">' + escape(row.label) + '</th><td>' + overallRange853(row.totalRange || row.total) + '</td><td>' + overallRange853(row.recordedRange || row.recorded) + '</td><td>' + format(row.credited) + '</td><td>' + format(row.left) + '</td></tr>').join('');
    const value = mode === 'done' ? model.credited : mode === 'left' ? model.left : model.total;
    return '<div class="tw840-dialog-top" data-tw853-detail><div><span class="tw840-kicker">FENCING · ALL PROGRAMME WORK METRES</span><h2 id="tw840-dialog-title">Fencing · ' + label + '</h2><p>' + overallRange853(value,' m') + ' · Build + Event · excluding Demob</p></div><button type="button" class="tw840-close" data-tw840-close data-tw840-focus="dialog-close" aria-label="Close work breakdown">×</button></div><p class="tw842-review-label"><strong>' + escape(qualification) + '</strong></p><div class="tw840-detail-summary"><strong>' + overallRange853(model.pct,'%') + '</strong><span>Programme work metres recorded</span></div><div class="tw853-table-scroll" tabindex="0" role="region" aria-label="Work metres by activity"><table class="tw853-detail-table"><thead><tr><th scope="col">Work type</th><th scope="col">Total m</th><th scope="col">Recorded m</th><th scope="col">Within plan m</th><th scope="col">Left m</th></tr></thead><tbody>' + rows + '</tbody></table></div>' + (model.classificationPending ? '<p>Pending CCB allocations share one quantity; individual Within plan and Left cells await classification. The headline range counts that shared quantity once.</p>' : '') + '<details class="tw853-basis"><summary>How this percentage is calculated</summary><div><p>' + escape(model.basis) + '</p><p>Recorded in the headline means work within each activity’s plan. Where an activity exceeds its total, the original recorded amount stays in the table and the excess cannot reduce another activity’s Left.</p><p>Each included work type contributes its own metres; the same physical fence may have both installation and movement work. Gate openings, supplier gate components and physical completion sign-offs keep their own records.</p>' + groupNotes(model.issues) + '</div></details><button type="button" class="tw840-destination" data-tw840-destination="fencing" data-tw840-focus="dialog-destination">Open Fencing source records →</button>';
  }
