// running sheet as an editor: prefill, edit times, money, rate, add person; hours/split/pay and Costs follow
const {chromium} = require('playwright');
(async () => { const b = await chromium.launch({executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox']});
  const p = await (await b.newContext({viewport: {width: 1440, height: 900}})).newPage(); const errs = [];
  p.on('pageerror', e => errs.push(String(e).slice(0, 200))); p.on('dialog', d => d.dismiss());
  await p.goto('http://127.0.0.1:8814/e/edittokenedittoken1/#runsheet', {waitUntil: 'load'}); await p.waitForTimeout(3000);
  await p.evaluate(() => { S.operator = 'Test Runner'; const w = document.querySelector('#who'); if (w) w.value = 'Test Runner'; state.runDay = '2026-09-24'; renderRunsheet(); });
  await p.waitForTimeout(600);
  const row = n => p.evaluate(n => { const tr = [...document.querySelectorAll('#pane-runsheet .rstbl tbody tr')].find(t => t.cells[0] && t.cells[0].textContent.includes(n)); return tr ? [...tr.cells].map(c => { const i = c.querySelector('input,select'); return i ? i.value : c.textContent.trim(); }) : null; }, n);
  console.log('Daniel before', JSON.stringify(await row('Daniel')));
  console.log('Aaron before', JSON.stringify(await row('Aaron')));
  const set = async (sel, v) => { await p.evaluate(([sel, v]) => { const i = document.querySelector(sel); i.value = v; i.dispatchEvent(new Event('change', {bubbles: true})); }, [sel, v]); await p.waitForTimeout(700); };
  await set('[data-rsf="finish"][data-rsp="Daniel Gough"]', '18:00');
  await set('[data-rsm="meals"][data-rsp="Daniel Gough"]', '25.50');
  await set('[data-rsx="R&M"][data-rsp="Daniel Gough"]', '40');
  await set('[data-rsrate="Daniel Gough"]', '45');
  console.log('Daniel after', JSON.stringify(await row('Daniel')));
  await p.evaluate(() => { document.querySelector('#rsNewName').value = 'Test Worker'; document.querySelector('#rsNewType').value = 'hire'; document.querySelector('#rsAdd').click(); }); await p.waitForTimeout(800);
  await set('[data-rsf="start"][data-rsp="Test Worker"]', '06:00'); await set('[data-rsf="finish"][data-rsp="Test Worker"]', '17:00');
  console.log('Test Worker', JSON.stringify(await row('Test Worker')));
  const sat = await p.evaluate(() => { state.runDay = '2026-09-26'; renderRunsheet(); return null; }); await p.waitForTimeout(500);
  await set('[data-rsf="start"][data-rsp="Test Worker"]', '06:00'); await set('[data-rsf="finish"][data-rsp="Test Worker"]', '17:00');
  console.log('Saturday Test Worker', JSON.stringify(await row('Test Worker')));
  await p.evaluate(() => { state.runDay = '2026-09-27'; renderRunsheet(); }); await p.waitForTimeout(500);
  await set('[data-rsf="start"][data-rsp="Aaron Zelvis"]', '06:00'); await set('[data-rsf="finish"][data-rsp="Aaron Zelvis"]', '17:00');
  console.log('Sunday Aaron', JSON.stringify(await row('Aaron')));
  const costs = await p.evaluate(() => { const T = trackerFigures(); return {hours: T.labour.hours, ord: T.labour.ordinary, x15: T.labour.at_1_5, x2: T.labour.at_2, meals: T.meals.amount, misc: T.misc.amount}; });
  console.log('Costs tracker figures', JSON.stringify(costs));
  const q = await p.evaluate(() => { const Q = questionsList(); const g = {}; Q.forEach(x => g[x.group] = (g[x.group] || 0) + 1); return {n: Q.length, g, sample: Q.slice(0, 3).map(x => x.q)}; });
  console.log('Questions', JSON.stringify(q));
  console.log('errors', JSON.stringify(errs)); await b.close(); })();
