// Author: Andrew Fisher. Native record, finance and toilet print checks; GET-only.
const fs=require('fs'),assert=require('assert'),R=process.env.REPO,O=process.env.OUT;
const {installWriteGuard,ready840,nativeSnapshot}=require(R+'/v8.40_today_work_progress_LIVE/test_today840.cjs');const {open}=require(R+'/toolchain/harness/open_page.js');const guard=installWriteGuard();
(async()=>{let s;try{fs.mkdirSync(O,{recursive:true});for(const W of [1366,390]){s=await open({pageFile:process.env.PAGE,hash:'#today',W,H:900,mobile:W===390});const p=s.page;await ready840(p);await p.waitForFunction(()=>labourAllowance858()>0);const before=await nativeSnapshot(p);await p.evaluate(()=>go('runsheet'));await p.waitForTimeout(1300);
assert.equal(await p.evaluate(()=>state.tab),'costs');assert.equal(await p.locator('#pane-costs #pane-runsheet').count(),1);assert.equal(await p.evaluate(()=>TABS.some(x=>x[0]==='runsheet')),false);
const check=await p.evaluate(()=>{const tables=[...document.querySelectorAll('#pane-runsheet .rstbl')];const T=holdAssets(runTotals);return {headers:tables.map(t=>[...t.querySelectorAll('thead th')].map(c=>c.textContent.trim())),jobRows:[...tables[1].querySelectorAll('tbody tr')].map(r=>[...r.children].map(c=>c.textContent.trim())),allowance:labourAllowance858(),total:T.all.total,P:pl770Model(),C:cj764Model()};});
fs.writeFileSync(O+'/debug-'+W+'.json',JSON.stringify(check,null,2));for(const h of check.headers)assert.equal(h[h.indexOf('×2')+1],'Salary allowance (forecast)');const h=check.headers[1],rows=check.jobRows,ai=h.indexOf('Salary allowance (forecast)'),ti=h.indexOf('Total'),num=s=>Number(s.replace(/[^\d.-]/g,''));assert.equal(num(rows.find(r=>r[0]==='Andrew Fisher')[ai]),check.allowance);assert.equal(num(rows.at(-1)[ai]),check.allowance);assert.equal(num(rows.at(-1)[ti]),Math.round((check.total+check.allowance)*100)/100);assert.equal(rows.filter(r=>num(r[ai])>0).length,2);assert(Object.values(check.P.checks).every(Boolean));assert.equal(check.C.wages.allowanceForecast,check.allowance);assert.equal(check.C.wages.job,Math.round((check.C.wages.known+check.C.wages.toCome2)*100)/100);
await p.locator('[data-rsday]').first().click();console.log('day-after',await p.evaluate(()=>({tab:state.tab,view:state.financeView857,headers:[...document.querySelectorAll('#pane-runsheet th')].map(x=>x.textContent)})));assert((await p.locator('#pane-runsheet .rstbl thead').first().innerText()).toLowerCase().includes('salary allowance (forecast)'));await p.screenshot({path:O+'/roster-'+W+'.png'});await p.locator('[data-finance857="summary"]').click();assert.equal(await p.locator('#pane-costs details>summary').filter({hasText:'Forecast salary uplift and living-away allowance'}).count(),0);
await p.evaluate(()=>{go('timeline');window.__printCalls859=0;window.print=()=>window.__printCalls859++;});await p.waitForTimeout(1300);
for(let n=1;n<=5;n++){await p.locator('[data-ep819-print="'+n+'"]').click();await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>window.__printCalls859),2*(n-1));assert(await p.evaluate(()=>epOpen819()));assert.equal(await p.locator('.rs819').count(),1);assert((await p.locator('.rs819').innerText()).includes('Load '+n+' of 5'));if(W===1366){await p.emulateMedia({media:'print'});assert(await p.locator('.rs819').isVisible());await p.pdf({path:O+'/toilet-load-'+n+'.pdf',preferCSSPageSize:true});await p.emulateMedia({media:'screen'});}if(n===1)await p.screenshot({path:O+'/toilet-preview-'+W+'.png'});await p.locator('[data-ep819-go]').click();assert.equal(await p.evaluate(()=>window.__printCalls859),2*n-1);await p.evaluate(()=>window.dispatchEvent(new Event('afterprint')));assert(await p.evaluate(()=>epOpen819()));await p.locator('[data-ep819-go]').click();assert.equal(await p.evaluate(()=>window.__printCalls859),2*n);await p.locator('[data-ep819-x]').click();assert(!await p.evaluate(()=>epOpen819()));}
const after=await nativeSnapshot(p);assert.deepStrictEqual(after.collections,before.collections);assert.equal(s.errors.length,0,s.errors.join('\n'));fs.writeFileSync(O+'/finance-'+W+'.json',JSON.stringify(check,null,2));console.log('PASS '+W+' allowance column, aggregate once, finance reconciliation, five toilet previews/print/retry, record preservation');await s.browser.close();s=null;}assert(!guard.nonGetSeen.some(x=>x.operational));}finally{if(s)await s.browser.close();await guard.closeAll();}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
