/* Author: Andrew Fisher. Extend the existing permanent reference method; door orientation remains separate. */
function handling875Merge(a,b){const valid=x=>x&&['forklift','tilt-tray','crane-truck','franna','onsite-crane','not-required','none','to-confirm',''].includes(x.method)&&typeof x.by==='string'&&x.by.trim()&&Number.isFinite(Date.parse(x.at));return !valid(a)?valid(b)?b:null:!valid(b)?a:a.at!==b.at?(a.at>b.at?a:b):JSON.stringify(a)>JSON.stringify(b)?a:b;}
function handling875Record(a){const x=handling875Merge(((CROW.get(a.key)||{}).delivery||{}).handling875,((S.delivery||{})[a.key]||{}).handling875);if(x)return x;const full=assetOf(a.key)||a,e=(full.events||[]).find(e=>e.handling_source875);return e?Object.assign({source:true},e.handling_source875):null;}
function handling875Words(m){return {forklift:'Forklift unloading','tilt-tray':'Tilt tray unloading','crane-truck':'Crane truck unloading',franna:'Franna crane unloading','onsite-crane':'On-site crane unloading · type to confirm','not-required':'Crane / Franna not required · unloading method to confirm',none:'No unloading required','to-confirm':'Unloading method to be confirmed'}[m]||'Unloading method not set';}
function handling875Set(ref,method){const a=assetOf(ref);if(!a||a._cancelled||!['forklift','tilt-tray','crane-truck','franna','onsite-crane','not-required','none','to-confirm',''].includes(method)||!mayWrite('the unloading method'))return false;const who=whoAmI();if(!who)return false;const old=handling875Record(a),d=(S.delivery||(S.delivery={}))[ref]||((S.delivery)[ref]={});d.handling875={method,by:who,at:new Date(Math.max(Date.now(),old&&old.at?Date.parse(old.at)+1:0)).toISOString()};bump();flash(ref+' · '+handling875Words(method)+' saved.');return true;}

function handling875Editor(a){if(!a||a._cancelled)return '';const r=handling875Record(a),can=capability()==='edit'&&!SYNC.readonly;if(!r&&!can)return '';const name='handling875-'+a.key+'-'+(++handling875Seq);return '<details class="loading872 handling875"><summary>Unloading · '+esc(handling875Words(r&&r.method))+'</summary><fieldset><legend>Unloading method</legend>'+['forklift','tilt-tray','crane-truck','franna','onsite-crane','none','to-confirm'].map(m=>'<label><input type="radio" name="'+esc(name)+'" data-handling875-ref="'+esc(a.key)+'" value="'+m+'"'+(r&&r.method===m?' checked':'')+(can?'':' disabled')+'> '+esc(handling875Words(m))+'</label>').join('')+(r&&r.source?'<p>'+esc(r.source===true?'Schedule source':r.source)+' · '+esc(r.sheet)+' row '+esc(r.row)+'. Confirm the equipment, access and site arrangement for the next movement.</p>':'')+(can?'<button type="button" class="btn" data-handling875-clear="'+esc(a.key)+'">Clear</button>':'')+'</fieldset></details>';}
function handling875Sheet(a){const r=a&&handling875Record(a);return r?'<div class="loading872-sheet handling875-sheet"><b>Unloading · '+esc(a.key)+'</b><div>'+esc(handling875Words(r.method))+'</div><div>Confirm equipment capacity, operator, load restraints, access and site setup before unloading.</div></div>':'';}

handling875Checks=function(m,assets){const unique=[...new Map(assets.map(a=>[a.key,a])).values()],rows=unique.map(a=>({a,r:handling875Record(a)})).filter(x=>x.r);if(!rows.length)return m;m.checks.push({id:'lifting-requirement',text:'The reference unloading methods, equipment capacity and site arrangements are confirmed with the driver and site team.'});rows.forEach(({a,r})=>{const text=a.key+': '+handling875Words(r.method);if(!r.method||r.method==='onsite-crane'||r.method==='to-confirm'||r.method==='not-required')m.warnings.push({key:a.key,text:text+' — confirm equipment for this movement.'});else m.report.push(text);});return m;};
