/* Author: Andrew Fisher. Focused native navigation probes. Every service mutation is blocked. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const assert=require('node:assert/strict'),Module=require('module');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));
const original=fs.readFileSync(hp,'utf8');assert.match(original,/const okPost = [^;]+;/);assert(original.includes('counts.blocked++;'));
hm._compile(original.replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++; (counts.blockedPaths ||= []).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const {open}=hm.exports;
async function guard(p){await p.evaluate(()=>{if(Array.isArray(SYNC.unsub)){SYNC.unsub.forEach(fn=>fn());SYNC.unsub=[];}window.__independent931Writes=[];window.bump=()=>{__independent931Writes.push('bump');throw Error('Navigation must not save');};if(SYNC.db&&typeof SYNC.db.doc==='function'){const native=SYNC.db.doc.bind(SYNC.db);SYNC.db.doc=(...args)=>{const doc=native(...args);for(const m of ['set','update','delete'])if(typeof doc[m]==='function')doc[m]=()=>{__independent931Writes.push(m);throw Error('Navigation must not write');};return doc;};}});}
async function assertNoWrites(p,s){assert.deepEqual(await p.evaluate(()=>__independent931Writes),[]);assert((s.counts.blockedPaths||[]).every(x=>x.method==='POST'&&x.origin==='https://tile.googleapis.com'&&x.path==='/v1/createSession'));}

const file=process.env.PAGE||'/workspace/private-navigation934/candidate.html',out=process.env.NAV_OUT||'/workspace/private-navigation934/evidence';fs.mkdirSync(out,{recursive:true});
(async()=>{const s=await open({pageFile:file,hash:'#today',W:390,H:844,mobile:true}),p=s.page,result={sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),checks:[]};
async function note(name,pass,data){result.checks.push({name,pass,data});console.log((pass?'PASS ':'FAIL ')+name);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));}
async function controlsFit(box){return box.locator('[data-nav934-back],button.close,[data-x83],[data-pdf7-x]').evaluateAll(bs=>bs.filter(b=>b.getClientRects().length).every(b=>{const r=b.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth+1&&r.y>=0&&r.bottom<=innerHeight+1&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===b;}));}
async function clear(){await p.evaluate(()=>{document.querySelectorAll('#inv83 [data-x83],#pdf7 [data-pdf7-x],.drawer.on:not(#drawer) button.close,dialog[open] [data-tw840-close]').forEach(b=>b.click());});}
try{await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live',null,{timeout:120000});await guard(p);const before=await p.evaluate(()=>JSON.stringify(S));await p.evaluate(()=>{window.inv83Make=()=>new Promise(()=>{});window.pdf7Make=()=>new Promise(()=>{});});
 for(const kind of ['inventory','print']){await clear();await p.evaluate(()=>go('today'));await p.waitForTimeout(100);await p.evaluate(()=>go('plant'));await p.waitForTimeout(150);const box=kind==='inventory'?'#inv83':'#pdf7',close=kind==='inventory'?'[data-x83]':'[data-pdf7-x]';const launch=()=>p.evaluate(k=>k==='inventory'?inv83Open():pdf7Open('prestart','2026-10-08',null),kind);
 await launch();await p.waitForTimeout(100);await note(kind+' visible Close',await p.locator(box+' '+close).first().isVisible());await note(kind+' visible Back',await p.locator(box+' [data-nav934-back]').isVisible());await note(kind+' controls fit and are unobscured',await controlsFit(p.locator(box)));await p.screenshot({path:path.join(out,kind+'-390.png')});await p.locator(box+' [data-nav934-back]').focus();await p.keyboard.press('Shift+Tab');await note(kind+' focus remains inside overlay',await p.evaluate(sel=>document.querySelector(sel).contains(document.activeElement),box));await p.locator(box+' [data-nav934-back]').click();await note(kind+' Back dismisses',await p.locator(box).count()===0);await launch();await p.locator(box+' '+close).first().click();await note(kind+' Close dismisses',await p.locator(box).count()===0);await launch();await p.keyboard.press('Escape');await p.waitForTimeout(100);await note(kind+' Escape dismisses',await p.locator(box).count()===0);await clear();await launch();await p.waitForTimeout(100);await p.goBack().catch(()=>{});await p.waitForTimeout(250);await note(kind+' browser Back dismisses',await p.locator(box).count()===0,{tab:await p.evaluate(()=>state.tab)});if(await p.locator(box).count())await p.screenshot({path:path.join(out,kind+'-back.png')});}
 await clear();await p.evaluate(()=>{go('subhired');document.querySelector('[data-supplier932-company="prem-air-hire"]')?.click();go('today');});await p.waitForTimeout(350);const detail=p.locator('[data-tw840-detail="toilets"]').first();await detail.evaluate(b=>{let e=b.parentElement;while(e){if(e.tagName==='DETAILS')e.open=true;e=e.parentElement;}b.click();});await p.waitForTimeout(250);const supplier=p.getByRole('button',{name:'Supplier plan and quantities without a WC allocation',exact:true});await note('Today supplier link available',await supplier.count()===1);await note('Today breakdown visible Back',await p.locator('#gc500-work-dialog840 [data-nav934-back]').isVisible());await supplier.click();await p.waitForTimeout(500);await note('Today supplier opens Sub-hired Event Portables',await p.evaluate(()=>state.tab==='subhired'&&!!document.querySelector('#pane-subhired #ep819')),{tab:await p.evaluate(()=>state.tab)});const back=p.locator('[data-tw844-return]');await note('Supplier retains Back to breakdown',await back.count()===1);if(await back.count()){await back.click();await p.waitForTimeout(250);await note('Supplier Back restores Today breakdown',await p.evaluate(()=>state.tab==='today'&&document.querySelector('#gc500-work-dialog840')?.open));}await clear();
 await p.evaluate(()=>go('plant'));await p.waitForTimeout(150);await p.evaluate(()=>holdAssets(()=>openAsset('WC20')));await p.waitForTimeout(200);await p.evaluate(()=>smsDropBox(assetOf('WC20')));await p.waitForTimeout(250);await note('Nested Text dialog has Close',await p.locator('.drawer.on:not(#drawer) button.close').isVisible());await p.keyboard.press('Escape');await p.waitForTimeout(200);await note('Nested Text Escape closes only upper dialog',await p.evaluate(()=>!document.querySelector('.drawer.on:not(#drawer)')&&document.querySelector('#drawer').classList.contains('on')));await clear();await note('Asset drawer visible Back',await p.locator('#drawer [data-nav934-back]').isVisible());await p.screenshot({path:path.join(out,'asset-390.png')});
 await p.evaluate(()=>document.querySelector('#dclose').click());await p.waitForTimeout(100);
 for(const spec of [{name:'contract',fn:'contractDialog',args:[],id:'cClose'},{name:'breakdown',fn:'breakdownDialog',args:[],id:'bClose'},{name:'variation',fn:'varDialog',args:[{scope:'plant'}],id:'vClose'},{name:'pairing',fn:'loadPairDialog',load:true,id:'lpClose'},{name:'drop card',fn:'cardMadeDialog',card:true,id:'cmClose'}]){
 await p.evaluate(x=>{if(x.load){const l=carrierLoads801()[0];window[x.fn](loadId(l));}else if(x.card){const l=carrierLoads801()[0];window[x.fn](l,{url:location.origin+'/v/navigation-test'},'2026-10-31');}else window[x.fn](...x.args);},spec);await p.waitForTimeout(120);
 const cls=p.locator('#'+spec.id),box=cls.locator('xpath=ancestor::*[@role="dialog"][1]');await note(spec.name+' native Close visible',await cls.isVisible());await note(spec.name+' visible Back',await box.locator('[data-nav934-back]').isVisible());await note(spec.name+' header controls fit',await controlsFit(box));if(spec.name==='contract')await p.screenshot({path:path.join(out,'contract-390.png')});await box.locator('[data-nav934-back]').click();await p.waitForTimeout(80);await note(spec.name+' Back dismisses without saving',await cls.count()===0&&await p.evaluate(()=>__independent931Writes.length===0));
 }
 await p.evaluate(()=>{go('timeline');timeline841Dialog('WC20');});await p.waitForTimeout(180);await note('Timeline progress visible Back and Close',await p.locator('#timeline841-dialog [data-nav934-back]').isVisible()&&await p.locator('#timeline841-dialog [data-tl841-close]').isVisible());await p.locator('#timeline841-dialog [data-nav934-back]').click();await note('Timeline progress Back dismisses',await p.locator('#timeline841-dialog').count()===0);
 await p.evaluate(()=>{go('plant');const b=document.querySelector('[data-inv83]');b.click();});await p.waitForTimeout(100);await p.evaluate(()=>document.querySelector('[data-inv83]').remove());await p.locator('#inv83 [data-nav934-back]').click();await p.waitForTimeout(100);await note('Removed opener returns focus to current pane',await p.evaluate(()=>document.activeElement===document.querySelector('.pane.on')));
 await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>inv83Open());await p.waitForTimeout(100);await note('Desktop preview controls fit',await controlsFit(p.locator('#inv83')));await p.screenshot({path:path.join(out,'inventory-1440.png')});await p.locator('#inv83 [data-x83]').click();
 await note('Native record unchanged',await p.evaluate(v=>JSON.stringify(S)===v,before));await assertNoWrites(p,s);await note('No runtime errors',s.errors.length===0);result.requests=s.counts;result.errors=s.errors;
}catch(e){result.error=e.stack;console.error(e.stack);}finally{result.errors=s.errors;result.requests=s.counts;fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));await s.browser.close();if(result.error||result.checks.some(c=>!c.pass))process.exitCode=1;}})();
