// Author: Andrew Fisher. Native page behaviour with in-memory save stubs; all network writes blocked by harness.
const {open}=require('../../toolchain/harness/open_page');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const E=__dirname,root=path.resolve(E,'../..'),out='/workspace/private-release-v814';fs.mkdirSync(out,{recursive:true});
const result={author:'Andrew Fisher',pageSha256:require('crypto').createHash('sha256').update(fs.readFileSync(process.env.PAGE)).digest('hex'),devices:[]};
(async()=>{for(const mobile of [false,true]){const name=mobile?'phone':'desktop';const s=await open({pageFile:process.env.PAGE,hash:'#today',W:mobile?390:1440,H:mobile?844:1000,dpr:mobile?2:1,mobile});try{const p=s.page;await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length);await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(1200);await p.screenshot({path:path.join(out,name+'.png'),fullPage:false});
const proof=await p.evaluate(async()=>{const old={attention,localCounts,save,dl:SYNC.dl,changes:S.changes,last:S.lastExport};const checks=[];const check=(name,pass)=>checks.push({name,pass:!!pass});try{window.localCounts=()=>({supplied:1});for(const n of [0,1,7]){S.changes=n;renderTabs();const b=document.querySelector('#exportBtn');check(`render shows ${n} unexported changes`,b.textContent===(n?`Export · ${n} new`:'Export'));check(`reminder styling ${n}`,b.classList.contains('due814')===!!n);check(`reminder title ${n}`,n?b.title.startsWith(`${n} change`):!/^\d/.test(b.title));}S.changes=5;let finish,reject;SYNC.dl={save:()=>new Promise((res,rej)=>{finish=res;reject=rej})};window.save=()=>{S.changes++};document.querySelector('#exportBtn').onclick();S.changes=7;finish();await new Promise(r=>setTimeout(r,30));check('changes during export remain unexported',S.changes===2&&document.querySelector('#exportBtn').textContent==='Export · 2 new');document.querySelector('#exportBtn').onclick();reject({code:'declined'});await new Promise(r=>setTimeout(r,30));check('cancelled export preserves reminder',S.changes===2&&document.querySelector('#exportBtn').textContent==='Export · 2 new');document.querySelector('#exportBtn').onclick();finish();await new Promise(r=>setTimeout(r,30));check('successful export clears only exported changes',S.changes===0&&document.querySelector('#exportBtn').textContent==='Export');}finally{window.localCounts=old.localCounts;window.save=old.save;SYNC.dl=old.dl;S.changes=old.changes;S.lastExport=old.last;renderTabs()}return checks});assert(proof.every(x=>x.pass),JSON.stringify(proof.filter(x=>!x.pass)));
const dateProof=await p.evaluate(()=>{const original=Date.now;const result=[];try{for(const date of ['2026-10-03','2026-10-07']){Date.now=()=>Date.parse(date+'T02:00:00Z');TODAY_ISO.v='';renderToday();const d=programmeDays().find(d=>d.iso===date);const due=[...document.querySelectorAll('#pane-today .hubcard h3')].some(h=>h.textContent==='Due today');result.push({date,programmeDay:!!d,due,pass:due===!!d,titles:[...document.querySelectorAll('#pane-today .hubcard h3')].map(h=>h.textContent)})}}finally{Date.now=original;TODAY_ISO.v='';renderToday()}return result});assert(dateProof.every(x=>x.pass),JSON.stringify(dateProof));
await p.evaluate(()=>{S.changes=7;window.localCounts=()=>({supplied:1});renderTabs();document.querySelector('#moreBtn').click()});await p.waitForTimeout(200);await p.screenshot({path:path.join(out,name+'-tools.png')});
assert.equal(s.errors.length,0);assert.equal(s.counts.blocked,0);result.devices.push({name,checks:proof,dates:dateProof,pageErrors:s.errors,blockedWrites:s.counts.blocked});}finally{await s.browser.close()}}
fs.writeFileSync(path.join(E,'codex_browser_audit.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({devices:result.devices.map(d=>({name:d.name,checks:d.checks.length,dates:d.dates.length,errors:d.pageErrors.length,blockedWrites:d.blockedWrites}))}));})().catch(e=>{console.error(e);process.exitCode=1});
