// Author: Andrew Fisher. Actual live Showcase visual inspection. No source or operational writes.
const fs=require('fs'),path=require('path'),Module=require('module'),crypto=require('crypto'),assert=require('assert/strict');
const out=process.env.OUTDIR||__dirname,tool=path.resolve(__dirname,'../../toolchain/harness'),hp=tool+'/open_page.js';
const fetcher=require(tool+'/curlfetch'),native=fetcher.curlFetch;let served={};fetcher.curlFetch=async(u,h,method,b)=>{assert.equal(method,'GET');const r=await native(u,h,method,b),url=new URL(u);if(url.origin==='https://gc500-production.up.railway.app'&&/^\/v\/Coates-GC500-2026\/?$/.test(url.pathname))served={sha256:crypto.createHash('sha256').update(r.body).digest('hex'),bytes:r.body.length};return r};
const m=new Module(hp,module);m.filename=hp;m.paths=Module._nodeModulePaths(path.dirname(hp));m._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++; return route.abort();','counts.blocked++;(counts.blockedRequests||(counts.blockedRequests=[])).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});return route.abort();'),hp);
async function run(phone){const name=phone?'phone':'desktop',publicMode=process.env.PUBLIC==='1',candidate=publicMode?null:process.env.PAGE,expected=process.env.EXPECTED_SHA;assert(expected);if(!publicMode)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(candidate)).digest('hex'),expected);const h=await m.exports.open({pageFile:candidate,hash:'#today',W:phone?390:1440,H:phone?844:900,dpr:1,mobile:phone,gl:true}),p=h.page; p.setDefaultTimeout(180000);const R={author:'Andrew Fisher',device:name,actualPublic:publicMode,served,expectedSha256:expected,shots:[],checks:[]},check=(name,ok)=>{R.checks.push({name,pass:!!ok});assert(ok,name)};
try{
 if(publicMode)check('Actual served bytes',served.sha256===expected&&h.counts.page===0);
 await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:150000});const original=await p.evaluate(()=>JSON.stringify(S));
 R.defaults=await p.evaluate(()=>({back:showBackPref(),view:showViewGet(),quality:showQualityGet(),focus:showCarFocusGet()}));check('Original viewing defaults preserved',R.defaults.back==='circuit3d'&&R.defaults.view==='hero'&&R.defaults.quality==='auto'&&R.defaults.focus===true);
 await p.evaluate(()=>{showOpen();if(SHOW.playing)showPause()});await p.waitForFunction(()=>GC3D.S?.dressStats?.photoLandmarks970?.landmarks?.length===5,null,{timeout:150000});
 R.landmarks=await p.evaluate(()=>GC3D.S.dressStats.photoLandmarks970);check('Five source landmarks built without fallback',R.landmarks.landmarks.length===5&&R.landmarks.skipped.length===0);check('No new landmark draw calls or textures declared',R.landmarks.newDrawCalls===0&&R.landmarks.newTextures===0);
 for(const [look,backdrop]of[['day','circuit3d_day'],['night','circuit3d']]){
  if(phone)await p.locator('#showOptions794').click();await p.selectOption('#showBackdrop',backdrop);await p.selectOption('#showView','onboard');if(phone)await p.locator('#showOptions794').click();
  await p.waitForFunction(()=>!!GC3D.S?.trackDetail781&&!!GC3D.S?.architecture781&&!!GC3D.S?.vegetation781&&(!GC3D.startupReport971||GC3D.startupReport971()?.shown),null,{timeout:150000});
  R.atlas=await p.evaluate(()=>GC3D.S.trackDetail781.stats.signage792);
  for(const id of (process.env.FOCUS==='1'?(look==='day'?['PB3']:['OT5']):['PB1','PB2','OT4','PB3','OT5']))for(const approachM of (phone?[40]:[60,28])){
   const observation=await p.evaluate(({id,approachM,poseFixture})=>{const G=GC3D,S=G.S,a=G.photoLandmarks970.resolve(S,id);if(!a)throw new Error('No landmark '+id);G.simReset();S.paused=true;const rel=((a.s-S.gridS-approachM/G.M_PER_PT)%S.CL.L+S.CL.L)%S.CL.L,target=S.gridS+rel;let n=0;if(poseFixture){S.clock=12;S.sim.s=target;S.sim.v=S.vAt(target);S.sim.go=true;S.sim.burn=0;G.pose();}else while(S.sim.s<target&&n++<90000)G.step(1/120);if(n>=90000)throw new Error('Approach exceeded simulation bound');S.camBase=null;for(let j=0;j<60;j++)G.camStep(1/60);G.render();return {id,approachM,poseFixture,steps:n,positionM:(S.sim.s-S.gridS)*G.M_PER_PT,landmark:a,clock:S.clock,quality:G.graphicsReport(),detail:G.fullLapReport788(),glError:S.gl.getError()}},{id,approachM,poseFixture:process.env.FOCUS==='1'});R.shots.push(observation);check(look+' '+id+' '+approachM+' m GL ready',observation.glError===0&&!observation.detail.detailError);await p.screenshot({path:out+'/'+name+'-'+look+'-'+id+'-'+approachM+'m.png',timeout:120000});
  }
 }
 await p.locator('#showBack').click();check('Back disposes scene',await p.evaluate(()=>!SHOW.open&&!GC3D.S));R.recordUnchanged=await p.evaluate(value=>JSON.stringify(S)===value,original);check('Native record preserved',R.recordUnchanged);check('No page errors',h.errors.length===0);check('No operational writes',(h.counts.blockedRequests||[]).every(x=>x.origin!=='https://gc500-production.up.railway.app'));R.errors=h.errors;R.counts=h.counts;if(!publicMode)check('Frozen bytes unchanged',crypto.createHash('sha256').update(fs.readFileSync(candidate)).digest('hex')===expected);fs.writeFileSync(out+'/'+name+'.json',JSON.stringify(R,null,2));console.log(JSON.stringify({device:name,sha256:expected,checks:R.checks.length,errors:h.errors,recordUnchanged:R.recordUnchanged,shots:R.shots.length}));
}catch(e){R.error=e.stack;R.errors=h.errors;R.counts=h.counts;fs.writeFileSync(out+'/'+name+'-failure.json',JSON.stringify(R,null,2));await p.screenshot({path:out+'/'+name+'-failure.png',timeout:120000}).catch(()=>{});throw e}finally{await h.browser.close()}}
(async()=>{for(const phone of (process.env.MOB==='1'?[true]:process.env.DESKTOP==='1'?[false]:[false,true]))await run(phone)})().catch(e=>{console.error(e.stack);process.exit(1)});
