// Author: Andrew Fisher. Read-only historical card and Today distinction checks.
const fs=require('fs'),crypto=require('crypto'),assert=require('assert/strict');let servedHash;
if(process.env.PUBLIC==='1'){const f=require('../../toolchain/harness/curlfetch'),old=f.curlFetch;f.curlFetch=async function(url,...args){const r=await old(url,...args);if(/^https:\/\/gc500-production\.up\.railway\.app\/v\/Coates-GC500-2026\/?(?:[?#].*)?$/.test(url))servedHash=crypto.createHash('sha256').update(r.body).digest('hex');return r;};}
const {open}=require('../../toolchain/harness/open_page');
(async()=>{const mobile=process.env.MOB==='1',pub=process.env.PUBLIC==='1';if(!pub)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(process.env.PAGE)).digest('hex'),process.env.EXPECTED_SHA);const h=await open({pageFile:pub?undefined:process.env.PAGE,hash:'#day/2026-10-09',mobile,W:mobile?390:1440,H:900}),p=h.page;let checks=0;const check=(x,t)=>{assert(x,t);checks++;};try{
await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:150000});await p.evaluate(()=>{state.day='2026-10-09';go('timeline');renderTimeline();});
const before=await p.evaluate(()=>({native:JSON.stringify(S),money:JSON.stringify(pl770Model()),dates:calendarDays().map(d=>[d.iso,d.deliveries.map(r=>r.a.key),d.removals.map(r=>r.a.key)])}));
if(pub){check(h.counts.page===0,'No HTML substitution');check(servedHash===process.env.EXPECTED_SHA,'Exact public source');}
const reading=await p.evaluate(()=>{const today=todayIso(),past=[...document.querySelectorAll('#pane-timeline .day[data-day]')].filter(e=>e.dataset.day<today),current=document.querySelector('#pane-timeline .day[data-day="'+today+'"]'),future=[...document.querySelectorAll('#pane-timeline .day[data-day]')].filter(e=>e.dataset.day>today),selected=document.querySelector('#pane-timeline .day.on'),s=selected.getBoundingClientRect();return {past:past.length,allPast:past.every(e=>e.classList.contains('past984')&&e.querySelectorAll('[data-past984-summary]').length===1&&e.textContent.includes('PAST DAY')),today:!!current,todayHasPercent:!!current?.querySelector('[data-past984-summary]'),todayActive:current?.classList.contains('today'),futureClean:future.every(e=>!e.classList.contains('past984')&&!e.querySelector('[data-past984-summary]')),selected:!!selected?.classList.contains('past984'),width:s.width,height:s.height,pageWidth:document.documentElement.scrollWidth,viewport:innerWidth,percentage:selected.querySelector('.past984-band>b')?.textContent,percentFont:selected.querySelector('.past984-band>b')?parseFloat(getComputedStyle(selected.querySelector('.past984-band>b')).fontSize):null,allFits:past.every(e=>{const r=e.querySelector('.past984-band').getBoundingClientRect(),f=e.querySelector('.dface').getBoundingClientRect();return r.left>=f.left-1&&r.right<=f.right+1;}),todayText:current?.querySelector('.dtoday')?.textContent};});
check(reading.past>0&&reading.allPast,'Every past card clearly reference');check(reading.today&&!reading.todayHasPercent&&reading.todayActive,'Today no percentage');check(reading.futureClean,'Future unaffected');check(reading.selected,'Historical selected day distinct');check(reading.allFits,'All historical badges fit');check(reading.percentFont===null||reading.percentFont>=24,'Clear percentage size');check(reading.pageWidth<=reading.viewport+1,'No page overflow');
const card=p.locator('#pane-timeline .day[data-day="2026-10-08"]');await card.click();check(await p.evaluate(()=>state.day==='2026-10-08'),'Past day remains clickable');check(await p.locator('#pane-timeline .day.on').getAttribute('data-day')==='2026-10-08','Selected reference date correct');
await p.evaluate(()=>{state.day='2026-10-09';renderTimeline();renderTimeline();});check(await p.locator('#pane-timeline .day.on [data-past984-summary]').count()===1,'No duplicate badge after refresh');
const after=await p.evaluate(()=>({native:JSON.stringify(S),money:JSON.stringify(pl770Model()),dates:calendarDays().map(d=>[d.iso,d.deliveries.map(r=>r.a.key),d.removals.map(r=>r.a.key)])}));check(before.native===after.native,'Native record unchanged');check(before.money===after.money,'Financial figures unchanged');check(JSON.stringify(before.dates)===JSON.stringify(after.dates),'Movement schedule unchanged');check(h.errors.length===0,'No page errors');check(h.counts.blocked===0,'No writes');
if(process.env.OUTDIR){fs.mkdirSync(process.env.OUTDIR,{recursive:true});await p.locator('#pane-timeline .day.on').scrollIntoViewIfNeeded();await p.screenshot({path:process.env.OUTDIR+'/past-day.png'});fs.writeFileSync(process.env.OUTDIR+'/past.json',JSON.stringify({author:'Andrew Fisher',pass:true,checks,mobile,actualPublic:pub,sha256:process.env.EXPECTED_SHA,reading,errors:0,writes:0},null,2));}console.log(JSON.stringify({pass:true,checks,mobile,actualPublic:pub,reading}));
}finally{await h.browser.close();}})().catch(e=>{console.error(e.stack);process.exit(1)});
