#!/usr/bin/env python3
"""Author: Andrew Fisher. Rebuild the v7.90 explorer files from their exact live v7.82 inputs.
Usage: python3 patch_explorer790.py <live explorer.js> <live index.html> <output folder>
This writes local files only. It never uploads or modifies the shared record.
"""
import hashlib, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / 'toolchain'))
from rep import rep
base_js, base_index, out = map(pathlib.Path, sys.argv[1:4])
def read_guard(p, expected):
    b = p.read_bytes()
    if hashlib.sha256(b).hexdigest() != expected:
        sys.exit('Wrong base for ' + p.name + '; fetch current live files and review before rebuilding')
    return b.decode('utf-8')
src = read_guard(base_js, 'dd6256bcd3e20cd89a70ba1c1d32e5f3b7b1acf09a2d19f1ac824f05fea93d3e')
idx = read_guard(base_index, '634881d7832bfd4f892ec50ae1e7eacbce2ea8d37dc0479d22804f190e94095e')
rep(src, "function setMode(m) {\n  if (m === mode) return; mode = m; document.querySelectorAll('.modes button').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.mode === m)));\n  dropVTQueue(); setSatState('');\n", "function setMode(m) {\n  if (m === mode) return; const wasGeo790 = geoOn(); mode = m; /* v7.90 - see below */ document.querySelectorAll('.modes button').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.mode === m)));\n  dropVTQueue(); setSatState('');\n", 'v7.90 explorer change 1', str(base_js))
src = src.replace("function setMode(m) {\n  if (m === mode) return; mode = m; document.querySelectorAll('.modes button').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.mode === m)));\n  dropVTQueue(); setSatState('');\n", "function setMode(m) {\n  if (m === mode) return; const wasGeo790 = geoOn(); mode = m; /* v7.90 - see below */ document.querySelectorAll('.modes button').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.mode === m)));\n  dropVTQueue(); setSatState('');\n")
rep(src, '  setAttrib();\n  changeView(false);\n}\n', '  setAttrib();\n  /* v7.90 - the plan and the satellite views measure in different coordinates (sheet units against metres on the ground), so\n     a camera carried from one into the other lands off the drawing - the project manager, 2 Oct 2026, saw the plan pushed into\n     the bottom-right on black. Changing between the two now fits the whole view; within one family the view is kept. */\n  if (geoOn() !== wasGeo790) {\n    /* The old coordinate-space anchor must not move the newly fitted view on a later animation frame. */\n    stopZoomAnim(); stopFling(); cancelAnimationFrame(rotAnim); rotAnim = 0;\n    fit();\n  } else changeView(false);\n}\n', 'v7.90 explorer change 2', str(base_js))
src = src.replace('  setAttrib();\n  changeView(false);\n}\n', '  setAttrib();\n  /* v7.90 - the plan and the satellite views measure in different coordinates (sheet units against metres on the ground), so\n     a camera carried from one into the other lands off the drawing - the project manager, 2 Oct 2026, saw the plan pushed into\n     the bottom-right on black. Changing between the two now fits the whole view; within one family the view is kept. */\n  if (geoOn() !== wasGeo790) {\n    /* The old coordinate-space anchor must not move the newly fitted view on a later animation frame. */\n    stopZoomAnim(); stopFling(); cancelAnimationFrame(rotAnim); rotAnim = 0;\n    fit();\n  } else changeView(false);\n}\n')
rep(src, "   rests. One chip shows or hides the layer; the list is read from the dashboard every 4 s. */\nlet DONE782 = new Set(), done782Sig = '', DONE782_ON = (() => { try { return localStorage.getItem('gc500.done782') !== 'off'; } catch (e) { return true; } })();\n(() => { const st = document.createElement('style'); st.textContent = '.d782{position:absolute;left:0;top:0;width:0;height:0;pointer-events:none;z-index:1}'\n", '   rests. One chip shows or hides the layer; the list is read from the dashboard every 4 s. */\nlet DONE782 = new Set(), done782Sig = \'\', DONE782_ON = (() => { try { return localStorage.getItem(\'gc500.done790\') === \'on\'; } catch (e) { return false; } })(); /* v7.90 - off until asked for: the project manager, 2 Oct 2026, "you are putting green ticks everywhere" */\n(() => { const st = document.createElement(\'style\'); st.textContent = \'.d782{position:absolute;left:0;top:0;width:0;height:0;pointer-events:none;z-index:1}\'\n', 'v7.90 explorer change 3', str(base_js))
src = src.replace("   rests. One chip shows or hides the layer; the list is read from the dashboard every 4 s. */\nlet DONE782 = new Set(), done782Sig = '', DONE782_ON = (() => { try { return localStorage.getItem('gc500.done782') !== 'off'; } catch (e) { return true; } })();\n(() => { const st = document.createElement('style'); st.textContent = '.d782{position:absolute;left:0;top:0;width:0;height:0;pointer-events:none;z-index:1}'\n", '   rests. One chip shows or hides the layer; the list is read from the dashboard every 4 s. */\nlet DONE782 = new Set(), done782Sig = \'\', DONE782_ON = (() => { try { return localStorage.getItem(\'gc500.done790\') === \'on\'; } catch (e) { return false; } })(); /* v7.90 - off until asked for: the project manager, 2 Oct 2026, "you are putting green ticks everywhere" */\n(() => { const st = document.createElement(\'style\'); st.textContent = \'.d782{position:absolute;left:0;top:0;width:0;height:0;pointer-events:none;z-index:1}\'\n')
rep(src, "  if (!row) { row = document.createElement('div'); row.id = 'done782row'; row.className = 'd782row'; chips.insertAdjacentElement('afterend', row);\n    row.onclick = e => { const b = e.target.closest('#done782'); if (!b) return; DONE782_ON = !DONE782_ON; try { localStorage.setItem('gc500.done782', DONE782_ON ? 'on' : 'off'); } catch (_) {} done782Chip(); requestPaint(); }; }\n  const n = (typeof ITEMS !== 'undefined' && ITEMS ? ITEMS.filter(it => it.places.length && it.cat && it.cat.host === 'trade' && DONE782.has(it.code)).length : 0);\n", "  if (!row) { row = document.createElement('div'); row.id = 'done782row'; row.className = 'd782row'; chips.insertAdjacentElement('afterend', row);\n    row.onclick = e => { const b = e.target.closest('#done782'); if (!b) return; DONE782_ON = !DONE782_ON; try { localStorage.setItem('gc500.done790', DONE782_ON ? 'on' : 'off'); } catch (_) {} done782Chip(); requestPaint(); }; }\n  const n = (typeof ITEMS !== 'undefined' && ITEMS ? ITEMS.filter(it => it.places.length && it.cat && it.cat.host === 'trade' && DONE782.has(it.code)).length : 0);\n", 'v7.90 explorer change 4', str(base_js))
src = src.replace("  if (!row) { row = document.createElement('div'); row.id = 'done782row'; row.className = 'd782row'; chips.insertAdjacentElement('afterend', row);\n    row.onclick = e => { const b = e.target.closest('#done782'); if (!b) return; DONE782_ON = !DONE782_ON; try { localStorage.setItem('gc500.done782', DONE782_ON ? 'on' : 'off'); } catch (_) {} done782Chip(); requestPaint(); }; }\n  const n = (typeof ITEMS !== 'undefined' && ITEMS ? ITEMS.filter(it => it.places.length && it.cat && it.cat.host === 'trade' && DONE782.has(it.code)).length : 0);\n", "  if (!row) { row = document.createElement('div'); row.id = 'done782row'; row.className = 'd782row'; chips.insertAdjacentElement('afterend', row);\n    row.onclick = e => { const b = e.target.closest('#done782'); if (!b) return; DONE782_ON = !DONE782_ON; try { localStorage.setItem('gc500.done790', DONE782_ON ? 'on' : 'off'); } catch (_) {} done782Chip(); requestPaint(); }; }\n  const n = (typeof ITEMS !== 'undefined' && ITEMS ? ITEMS.filter(it => it.places.length && it.cat && it.cat.host === 'trade' && DONE782.has(it.code)).length : 0);\n")
rep(src, '  const n = (typeof ITEMS !== \'undefined\' && ITEMS ? ITEMS.filter(it => it.places.length && it.cat && it.cat.host === \'trade\' && DONE782.has(it.code)).length : 0);\n  row.innerHTML = `<button class="chip" id="done782" aria-pressed="${DONE782_ON}" style="--c:#2bd46b" title="Finished units: a green tick, and a ring that beats twice. Tap to ${DONE782_ON ? \'hide\' : \'show\'} them."><b>✓</b>Done <small>${n}</small></button><small class="k">${DONE782_ON ? \'green tick, double beat = finished\' : \'finished units hidden\'}</small>`; }\nfunction done782Draw(ctx, M, dn) { const out = [];\n', '  const n = (typeof ITEMS !== \'undefined\' && ITEMS ? ITEMS.filter(it => it.places.length && it.cat && it.cat.host === \'trade\' && DONE782.has(it.code)).length : 0);\n  row.innerHTML = `<button class="chip" id="done782" aria-pressed="${DONE782_ON}" style="--c:#2bd46b" title="Finished units: a green tick, and a ring that beats twice. Tap to ${DONE782_ON ? \'hide\' : \'show\'} them."><b>✓</b>Done <small>${n}</small></button><small class="k">${DONE782_ON ? \'green tick, double beat = finished\' : \'finished units hidden - tap Done to show them\'}</small>`; }\nfunction done782Draw(ctx, M, dn) { const out = [];\n', 'v7.90 explorer change 5', str(base_js))
src = src.replace('  const n = (typeof ITEMS !== \'undefined\' && ITEMS ? ITEMS.filter(it => it.places.length && it.cat && it.cat.host === \'trade\' && DONE782.has(it.code)).length : 0);\n  row.innerHTML = `<button class="chip" id="done782" aria-pressed="${DONE782_ON}" style="--c:#2bd46b" title="Finished units: a green tick, and a ring that beats twice. Tap to ${DONE782_ON ? \'hide\' : \'show\'} them."><b>✓</b>Done <small>${n}</small></button><small class="k">${DONE782_ON ? \'green tick, double beat = finished\' : \'finished units hidden\'}</small>`; }\nfunction done782Draw(ctx, M, dn) { const out = [];\n', '  const n = (typeof ITEMS !== \'undefined\' && ITEMS ? ITEMS.filter(it => it.places.length && it.cat && it.cat.host === \'trade\' && DONE782.has(it.code)).length : 0);\n  row.innerHTML = `<button class="chip" id="done782" aria-pressed="${DONE782_ON}" style="--c:#2bd46b" title="Finished units: a green tick, and a ring that beats twice. Tap to ${DONE782_ON ? \'hide\' : \'show\'} them."><b>✓</b>Done <small>${n}</small></button><small class="k">${DONE782_ON ? \'green tick, double beat = finished\' : \'finished units hidden - tap Done to show them\'}</small>`; }\nfunction done782Draw(ctx, M, dn) { const out = [];\n')
digest = hashlib.sha256(src.encode('utf-8')).hexdigest()
idx = rep(idx, 'explorer.js?v=dd6256bcd3e20', 'explorer.js?v=' + digest[:12], 'version the explorer script', str(base_index))
out.mkdir(parents=True, exist_ok=True)
for name, text in [('explorer.js', src), ('index.html', idx)]:
    data = text.encode('utf-8'); (out / name).write_bytes(data)
    print(name, len(data), hashlib.sha256(data).hexdigest())
