// Author: Andrew Fisher. Public synthetic evidence: no customer records or prices.
const assert=require('assert/strict'),Q=require('./questions967.js');let checks=0;const ok=(name,fn)=>{fn();checks++;};
const unit=(item,assetNo,owner='coates',physical=true)=>({item,assetNo,owner,physical});
const inventory={list:[{item:'Pee Panel',unnum:true,refs:{A:{key:'WC09',on:6}}},{item:'Toilet Block',refs:{A:{key:'WC09',on:2}}},{item:'VMS',refs:{A:{key:'T0103',on:2}}}]};
const models={WC09:{rows:[unit('Toilet Block','ONE'),unit('Toilet Block','TWO'),unit('FWF','OTHER')]},T0103:{rows:[unit('VMS','THREE'),unit('VMS','FOUR','supplier')]}};
const original=JSON.stringify({inventory,models}),ids=Q.identities(inventory,k=>models[k]);
ok('typed and quantity-only scopes',()=>assert.equal(ids.pending.length,0));
ok('no invented quantity-only identities',()=>assert.equal(ids.covered.length,2));
ok('no source mutation',()=>assert.equal(JSON.stringify({inventory,models}),original));
ok('missing identity reopens',()=>{const m=structuredClone(models);m.T0103.rows.pop();assert.equal(Q.identities(inventory,k=>m[k]).pending[0].missing,1);});
ok('other item cannot cover missing number',()=>{const m=structuredClone(models);m.T0103.rows[0].item='FWF';assert.equal(Q.identities(inventory,k=>m[k]).pending[0].missing,1);});
ok('duplicate identity cannot cover another unit',()=>{const m=structuredClone(models);m.T0103.rows[1]=structuredClone(m.T0103.rows[0]);assert.equal(Q.identities(inventory,k=>m[k]).pending[0].missing,1);});
ok('supplier namespaces remain separate',()=>{const m=structuredClone(models);m.T0103.rows[1].assetNo='THREE';assert.equal(Q.identities(inventory,k=>m[k]).pending.length,0);});
ok('nonphysical rows never fill identity',()=>{const m=structuredClone(models);m.T0103.rows[0].physical=false;assert.equal(Q.identities(inventory,k=>m[k]).pending[0].missing,1);});
ok('zero receipts never imply missing numbers',()=>{const i=structuredClone(inventory);i.list[2].refs.A.on=0;assert.equal(Q.identities(i,k=>models[k]).covered.length,1);});
const h=[['R27','open','old','old','ask','plant'],['R28','later','old','old','ask','fencing'],['R23','open','old','old','ask','about'],['R30','open','VMS conflict','known','decision','docs']];
const c={ready:true,day:'2026-10-09',lighting:{confirmed:true,scope:6,groups:[{name:'Yard',scope:4},{name:'Seaway',scope:2}],on:'2026-10-08'},demob:{confirmed:true,reviewed:'09 Oct 2026',weeks:[{sheet:'DECON WK1',first_day:'2026-10-25',last_day:'2026-10-30'}],held:['old rows']},drawings:{confirmed:true,sheets:['D001-26003-03']},identities:ids,labour:{mapped:true,unpriced:[]}};
ok('three source-backed historical closures',()=>assert.deepEqual(Q.history(h,c).map(x=>x[1]),['done','done','done','open']));
ok('original history intact',()=>assert.equal(h[0][1],'open'));
ok('no early closure while hydration pending',()=>assert.deepEqual(Q.history(h,{...c,ready:false}),h));
for(const k of ['lighting','demob','drawings'])ok(k+' stale evidence reopens',()=>{const x=structuredClone(c);x[k].confirmed=false;const n={lighting:0,demob:1,drawings:2}[k];assert.equal(Q.history(h,x)[n][1],h[n][1]);});
const qs=[{id:'sp-nums',st:'open',q:'Missing numbers',why:'Old count',need:'Record fleet',rows:['old']},{id:'lb-install-confirm747',st:'later',q:'Install rate',why:'Awaiting',need:'Rate'},{id:'br-norate-NVAC',st:'later',q:'Three rates missing'},{id:'ccb-classification753',st:'open',q:'CCB',rows:['zero']}];qs.fails=[];
ok('fleet and customer installation answered',()=>assert.deepEqual(Q.project(qs,c).slice(0,2).map(x=>x.st),['done','done']));
ok('unknown rates preserved',()=>assert.deepEqual(Q.project(qs,c)[2],qs[2]));
ok('old wording retained',()=>assert.match(Q.project(qs,c)[0].original,/Missing numbers.*Old count/));
ok('input question rows remain untouched',()=>assert.deepEqual(qs[0].rows,['old']));
ok('identity reader unavailable never closes',()=>assert.equal(Q.project(qs,{...c,identities:null})[0].st,'open'));
ok('failed original identity check never closes',()=>{const x=qs.slice();x.fails=['asset numbers'];assert.equal(Q.project(x,c)[0].st,'open');});
ok('new labour gap reopens precise scope',()=>{const x=structuredClone(c);x.labour.unpriced=[{ref:'X',item:'Unit',line:'Install'}];assert.equal(Q.project(qs,x)[1].st,'later');});
ok('removed source mapping never closes',()=>{const x=structuredClone(c);x.labour.mapped=false;assert.equal(Q.project(qs,x)[1].st,'later');});
ok('measured unclassified record keeps measured metres',()=>{const x={...c,ccb:[{number:'ABC',location:'Site',metres:10}]};assert.match(Q.project(qs,x)[3].rows[0],/10 m measured/);});
ok('unknown measure never shown as zero',()=>{const x={...c,ccb:[{number:'ABC',location:'Site',metres:null}]};assert.match(Q.project(qs,x)[3].rows[0],/needs review/);});

const programme={source_sha256:'836a3e1036c660caa89b1b36d4b821e2f84df7a8d8b977068b13a4f07602d9db',received:'09 Oct 2026',week_sheets:[['DECON WK1','2026-10-25','2026-10-30'],['DECON WK2','2026-11-02','2026-11-06'],['DECON WK3','2026-11-09','2026-11-13']].map(([sheet,first_day,last_day])=>({sheet,first_day,last_day,year:2026,phase:'Deconstruction'})),not_rolled_forward:['old row']};
ok('exact supplied demob source closes original date question',()=>assert(Q.demobEvidence(programme).confirmed));
ok('changed programme hash reopens',()=>assert(!Q.demobEvidence({...programme,source_sha256:'changed'}).confirmed));
ok('changed demob date reopens',()=>{const p=structuredClone(programme);p.week_sheets[0].first_day='2026-10-26';assert(!Q.demobEvidence(p).confirmed);});
ok('duplicate week cannot hide missing week',()=>{const p=structuredClone(programme);p.week_sheets[1]=p.week_sheets[0];assert(!Q.demobEvidence(p).confirmed);});
ok('missing demob week reopens',()=>{const p=structuredClone(programme);p.week_sheets.pop();assert(!Q.demobEvidence(p).confirmed);});
ok('old year never accepted',()=>{const p=structuredClone(programme);p.week_sheets[0].year=2025;assert(!Q.demobEvidence(p).confirmed);});
ok('traced move retains known identity without receipt mutation',()=>{const m=structuredClone(models);m.T0103.rows.pop();m.T0103.tracedMoves=[{item:'VMS',assetNo:'FOUR',owner:'supplier'}];assert.equal(Q.identities(inventory,k=>m[k]).pending.length,0);assert.equal(inventory.list[2].refs.A.on,2);});
ok('new missing identity produces a precise question',()=>{const x={...c,identities:{covered:[],pending:[{ref:'NEW',item:'Machine',numbered:0,quantity:1,missing:1}]}};assert.equal(Q.project([],x)[0].st,'open');});
const basisRows=[['R06','open','BOQ','old','ask','pricing'],['R09','later','Returns','old','Nothing yet','plant'],['R10','later','Pickup mismatch','old','choose date','plant']];
ok('current policy and return monitoring closed without settling date conflict',()=>assert.deepEqual(Q.history(basisRows,{...c,basis:{confirmed:true}}).map(r=>r[1]),['done','done','later']));
ok('missing source policy retains original questions',()=>assert.deepEqual(Q.history(basisRows,{...c,basis:{confirmed:false}}),basisRows));
ok('approved policy never declares single BOQ approved',()=>assert.match(Q.history(basisRows,{...c,basis:{confirmed:true}})[0][3],/No single BOQ is declared approved/));
ok('return monitoring never implies collection',()=>assert.match(Q.history(basisRows,{...c,basis:{confirmed:true}})[1][3],/no pick-up is inferred/));
console.log(JSON.stringify({author:'Andrew Fisher',pass:true,checks}));
