// Author: Andrew Fisher. Local-only presentation checks; no service requests.
const assert=require('assert/strict'),path=require('path'),{chromium}=require(require.resolve('playwright',{paths:[path.join(__dirname,'../toolchain/harness')]})),Q=require('./questions967.js');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{const p=await browser.newPage();await p.setContent(`<div id="pane-questions"><div class="card"><div class="hubtitle">Questions <b>1 need an answer</b></div><p class="sub">Guidance and source explanation.</p></div><div class="card"><ol><li data-question-id="one"><b>Missing unit number</b><span class="qwhy">A source explanation.</span><ul class="qrows"><li>REF · 2 of 3 recorded</li></ul><span class="qneed">Add the missing number.</span><button data-qgo="plant">Open where it lives</button><input data-qa="one"></li></ol></div><details data-qfold="history"><summary>Answered</summary><p class="sub">History guidance.</p><ol><li data-question-id="done"><b>Applied source</b><span class="qwhy">Original source evidence.</span></li></ol></details></div>`);await p.evaluate(fn=>{window.compact=new Function('return ('+fn+')')();window.pane=document.getElementById('pane-questions');window.actions=[];pane.querySelector('button').onclick=()=>actions.push('navigate');pane.querySelector('input').onchange=e=>actions.push(e.target.value);window.beforeText=pane.textContent;compact(pane);},Q.compact.toString());
const a=await p.evaluate(()=>({folds:[...pane.querySelectorAll('details[data-qfold]')].map(d=>({key:d.dataset.qfold,open:d.open})),why:!!pane.querySelector('[data-qfold="evidence967:one"] > .qwhy'),rowsVisible:!pane.querySelector('.qrows').closest('details'),needVisible:!pane.querySelector('.qneed').closest('details'),title:!pane.querySelector('[data-question-id="one"] > b').closest('details'),inputVisible:!pane.querySelector('input').closest('details'),numbers:pane.querySelector('.qrows').innerText}));let n=0;const check=(name,fn)=>{fn();n++};
check('new source and intro folds closed',()=>assert(a.folds.every(x=>!x.open)));
check('stable per-question and intro keys',()=>assert.deepEqual(a.folds.map(x=>x.key),['intro967','evidence967:one','history','history-intro967','evidence967:done']));
check('source inside More info',()=>assert(a.why));check('numeric rows remain visible',()=>assert(a.rowsVisible));check('needed action remains visible',()=>assert(a.needVisible));check('title remains visible',()=>assert(a.title));check('note input remains visible',()=>assert(a.inputVisible));check('numeric text unchanged',()=>assert.equal(a.numbers,'REF · 2 of 3 recorded'));
await p.click('button');await p.fill('input','A saved note');await p.locator('input').dispatchEvent('change');check('native note and navigation handlers retained',()=>{});assert.deepEqual(await p.evaluate(()=>actions),['navigate','A saved note']);
await p.evaluate(()=>{pane.querySelector('[data-qfold="evidence967:one"]').open=true;compact(pane)});check('compaction is idempotent and preserves open state',()=>{});assert.deepEqual(await p.evaluate(()=>({count:pane.querySelectorAll('[data-qfold="evidence967:one"]').length,open:pane.querySelector('[data-qfold="evidence967:one"]').open})),{count:1,open:true});
check('all original information retained',()=>{});assert.equal(await p.evaluate(()=>pane.textContent.replaceAll('More info','')),await p.evaluate(()=>beforeText));
console.log(JSON.stringify({author:'Andrew Fisher',passed:n,failed:0}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
