// Author: Andrew Fisher. Actual native performance, DOM equivalence, freshness and routing.
const fs=require('fs'),path=require('path'),Module=require('module'),assert=require('node:assert/strict'),crypto=require('crypto');
const h=path.resolve(__dirname,'../toolchain/harness/open_page.js'),source=fs.readFileSync(h,'utf8').replace("const okPost = r.method() === 'POST' && u.startsWith('https://tile.googleapis.com/v1/createSession');","const okPost = false;");assert(source.includes('const okPost = false;'));const m=new Module(h,module);m.filename=h;m.paths=Module._nodeModulePaths(path.dirname(h));m._compile(source,h);
async function check(file,isBase,mobile){const s=await m.exports.open({pageFile:file,hash:'#subhired',mobile,W:mobile?390:1440,H:mobile?844:900});const p=s.page;try{await p.waitForFunction(()=>SYNC.status==='live'&&Object.keys(SYNC_COLLS).every(k=>SYNC.first.has(k)),{timeout:120000});
 const results=await p.evaluate(()=>{window.__b936=buildAllAssets;window.__n936=0;buildAllAssets=function(){__n936++;return __b936.apply(this,arguments)};window.__state936=JSON.stringify(S);const start=performance.now();renderSubhired932();return {ms:performance.now()-start,builds:__n936,html:document.getElementById('pane-subhired').innerHTML,holdReleased:ASSETS_HELD===null};});
 assert(results.holdReleased);if(isBase){assert(results.builds>100);return results;}assert.equal(results.builds,1,'direct render');
 await p.evaluate(()=>__n936=0);await p.locator('[data-supplier932-company="prem-air-hire"]').click();assert(await p.evaluate(()=>__n936<=3),'company pointer bounded builds');assert.equal(await p.locator('#ep819').count(),0);
 await p.evaluate(()=>__n936=0);await p.locator('[data-supplier932-company="event-portables"]').focus();await p.keyboard.press('Enter');assert(await p.evaluate(()=>__n936<=3),'company keyboard bounded builds');assert.equal(await p.locator('#ep819').count(),1);
 // The retained generic company-select handler must share the same native scope.
 await p.evaluate(()=>{__n936=0;const e=document.createElement('select');e.dataset.unit925Company='';e.innerHTML='<option value="prem-air-hire">PremAir</option>';document.getElementById('pane-subhired').append(e);e.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await p.evaluate(()=>__n936),1,'action3');assert.equal(await p.locator('#ep819').count(),0);
 // Exact Today supplier route is go(subhired), then company click. Each fresh draw builds once.
 await p.evaluate(()=>{go('today');__n936=0;go('subhired');document.querySelector('[data-supplier932-company="event-portables"]').click();});assert.equal(await p.evaluate(()=>__n936),2);
 const fresh=await p.evaluate(()=>{const old=S.added;try{S.added=[...old,{key:'TEST936',discipline:'Other',item_types:['FWF'],asset_numbers:['TEST936'],locations:[]}];__n936=0;let seen=false;buildAllAssets=function(){__n936++;const a=__b936.apply(this,arguments);seen=a.some(x=>x.key==='TEST936');return a;};renderSubhired932();return {builds:__n936,seen,released:ASSETS_HELD===null};}finally{S.added=old;buildAllAssets=function(){__n936++;return __b936.apply(this,arguments)};renderSubhired932();}});assert.deepEqual(fresh,{builds:1,seen:true,released:true});
 const fail=await p.evaluate(()=>{try{holdAssets(()=>{throw Error('expected936')});}catch(_){}return ASSETS_HELD===null&&HELD_MEMO.size===0});assert(fail);
 assert(await p.evaluate(()=>JSON.stringify(S)===__state936));assert.deepEqual(s.errors,[]);const out='/workspace/private-supplier936';fs.mkdirSync(out,{recursive:true});await p.evaluate(()=>document.querySelector('main').scrollTop=0);await p.screenshot({path:out+(mobile?'/phone.png':'/desktop.png')});return {...results,stateUnchanged:true,routeBuilds:2,fresh};
 }finally{await s.browser.close();}}
(async()=>{const mobile=process.env.MOB==='1',base=await check(process.env.BASE,true,mobile),final=await check(process.env.PAGE,false,mobile);assert.equal(final.html,base.html,'Supplier DOM/data must be identical');const hash=x=>crypto.createHash('sha256').update(x).digest('hex');delete base.html;delete final.html;const r={mobile,base,final,domIdentical:true};fs.mkdirSync('/workspace/private-supplier936',{recursive:true});fs.writeFileSync('/workspace/private-supplier936/'+(mobile?'phone':'desktop')+'.json',JSON.stringify(r,null,2));console.log(JSON.stringify(r));})().catch(e=>{console.error(e.message);process.exitCode=1});
