export const ringNames=['The centre','Performance pillars','Scorecard & cadence','The seven traits'];
export const captions=['Everything connects to service and value.','People. Operations. Assets. Financials.','Measure performance. Own the action.','The behaviours that make the cog turn.'];
export const KPIs=[['0','Recordable safety injuries'],['<15%','Redline · unavailable fleet'],['20%','Return on capital employed'],['30%','EBIT margin'],['35%','Sales win rate'],['60','Customer NPS'],['65%','Fleet time utilisation'],['65+','Employee engagement']];
export const pillars=[
 {name:'People',color:'#c44c28',text:'Our people are the foundation of everything we deliver. Safe, engaged, capable teams create value every day.',items:['Put safety, values and culture first.','Build leadership capability and accountability.','Hire, onboard, develop and retain our people.','Recognise performance and support an inclusive team.'],kpi:'Employee engagement 65+ · Retention · Regular performance conversations'},
 {name:'Operations',color:'#999999',text:'How we execute the hire cycle — safely, reliably and consistently. Every customer interaction reflects the Coates brand.',items:['Keep customers at the centre and deliver on promises.','Run daily yard walks and weekly PULSE meetings.','Execute sales, transport and service reliably.','Track actions and close them out.'],kpi:'Safety 0 · NPS 60 · Sales win rate 35% · Delivery reliability'},
 {name:'Assets',color:'#587735',text:'Our fleet and technology is our business. Every asset must earn its return through quality, availability and lifecycle discipline.',items:['Match fleet to customer demand.','Keep equipment maintained, ready and available.','Use data to guide fleet mix and capital investment.','Use telemetry and address unavailable fleet.'],kpi:'Time utilisation 65% · Redline <15% · Telemetry coverage'},
 {name:'Financials',color:'#25376a',text:'Disciplined financial performance funds the flywheel. Every dollar must earn its return.',items:['Sell total value and defend pricing.','Make evidence-based investment decisions.','Forecast honestly and understand cost drivers.','Balance short-term and long-term commercial decisions.'],kpi:'EBIT margin 30% · ROCE 20% · Capital discipline'}
];
export const traits=[
 {name:'Customer Solutions',text:'Understand the customer’s needs and combine equipment, expertise and specialist services into one safe, efficient solution.',items:['Ask what the customer is trying to achieve.','Bring specialists in early.','Document requirements clearly in CRM.'],kpi:'NPS 60 · Sales win rate 35%'},
 {name:'Targeted Growth',text:'Grow deliberately in sectors and regions where Coates can lead. Invest where the returns justify it.',items:['Know priority customers and growth sectors.','Use evidence to decide where to invest.','Reinvest wins to compound returns.'],kpi:'ROCE 20% · EBIT margin 30%'},
 {name:'Performance-led Results',text:'Every metric has an owner. When performance is off track, understand why and act to fix it.',items:['Diagnose the root cause.','Assign a person and date to each action.','Track actions until performance is back on target.'],kpi:'Variance close-out · Forecast accuracy · Review cadence'},
 {name:'Operational Excellence',text:'Execute every stage of the hire cycle safely, reliably and consistently, from enquiry to return.',items:['Complete pre-start checks without shortcuts.','Fix issues before dispatch.','Deliver the correct kit and process returns promptly.'],kpi:'Safety 0 · Redline <15% · NPS 60'},
 {name:'Resilient Processes',text:'Standardise, document and follow processes. When a process fails, fix it at the source.',items:['Follow the agreed standard.','Flag workarounds and recurring problems.','Train teams and fix root causes.'],kpi:'Compliance · Defect close-out · Repeat defects'},
 {name:'Customer-led Innovation',text:'Use data, technology and frontline feedback to solve real customer problems.',items:['Start with the customer’s problem.','Run small experiments and use evidence.','Share learning and scale what works.'],kpi:'Digital adoption · Telemetry coverage · Pilot success'},
 {name:'Ease of Doing Business',text:'Make every interaction straightforward. Keep handovers clean, systems working and approvals moving.',items:['Own issues from start to finish.','Provide same-day quotes and clear answers.','Remove friction and make work easier for others.'],kpi:'First-call resolution · Quote turnaround · Customer effort'}
];
