// Author: Andrew Fisher. v8.91 Truck flow — the day's numbers from who is on, the day's load order (drag, ▲▼, keyboard) renumbering
// every label, the area limits (Main Beach 1, Pit lane by programme week, Helen Park 4, oversized guide 7), curfew-first, could-share-
// a-truck (never without weights and dimensions), the printed checklist and Printed by on every sheet, the sender's full name on the
// messages, the one remembered name prompt (Close, Not now, Escape), no scroll jump on reorder, no money change, render timing.
// Read-only against the live record: every write the page tries is aborted by open_page (counts.blocked must stay 0); the record
// writes practised here go through stubs and the local record is put back byte for byte.
//   PAGE=build/GC500_v8.91/GC500_Delivery_Control_hosted.html [MOB=1] [W=2560 H=1370] [OUT=dir] [TIMING_ONLY=1] node v8.91_truck_flow_DRAFT/tests/test_flow891.cjs
const fs = require('fs'), path = require('path'), {open} = require('../../toolchain/harness/open_page');
(async () => { let s; try {
  const MOB = !!process.env.MOB, W = MOB ? 390 : Number(process.env.W || 1440), H = MOB ? 844 : Number(process.env.H || 900), OUT = process.env.OUT || '', tag = MOB ? 'phone' : W >= 1900 ? 'wide' : 'laptop';
  if (OUT) fs.mkdirSync(OUT, {recursive: true});
  const R = []; const ok = (name, pass, detail) => { R.push({name, pass: !!pass, detail}); console.log((pass ? 'PASS ' : 'FAIL ') + name + (pass ? '' : ' ' + JSON.stringify(detail || null).slice(0, 400))); };
  s = await open({pageFile: process.env.PAGE, hash: '#timeline', W, H, mobile: MOB, dpr: MOB ? 2 : 1}); const p = s.page;
  await p.waitForFunction(() => typeof go === 'function' && typeof SYNC !== 'undefined' && SYNC.status === 'live' && typeof dpLoads === 'function', null, {timeout: 150000}); await p.waitForTimeout(2500);
  /* ---- render timing: the Timeline day view on the busiest coming day (the same measure runs on the base page with TIMING_ONLY=1) */
  const T = await p.evaluate(() => { const t0 = todayIso(); const days = programmeDays().filter(d => d.iso >= t0).map(d => ({iso: d.iso, n: dpLoads(d).length})).sort((a, b) => b.n - a.n); const iso = (days[0] || {}).iso || t0;
    state.day = iso; state.tlView = 'day'; go('timeline'); render(); const t = []; for (let k = 0; k < 9; k++) { const a = performance.now(); render(); t.push(Math.round(performance.now() - a)); }
    const sorted = t.slice().sort((a, b) => a - b); const t1 = performance.now(); const d = programmeDays().find(x => x.iso === iso); for (let k = 0; k < 30; k++) dpLoads(d);
    return {iso, loads: (days[0] || {}).n, runs: t, median: sorted[Math.floor(sorted.length / 2)], dpLoads30ms: Math.round(performance.now() - t1), flow: typeof flow891Build === 'function'}; });
  console.log('TIMING ' + tag + ' ' + JSON.stringify(T)); if (OUT) fs.writeFileSync(path.join(OUT, 'timing_' + tag + (T.flow ? '' : '_base') + '.json'), JSON.stringify(T));
  if (process.env.TIMING_ONLY) { console.log('timing only · errors ' + s.errors.length + ' blocked ' + s.counts.blocked); await s.browser.close(); return; }
  await p.waitForFunction(() => typeof flow891Build === 'function', null, {timeout: 30000});
  ok('render time of the day view is reasonable (' + T.median + ' ms median, ' + T.loads + ' loads)', T.median < 1500, T);
  const near = (a, b, eps) => typeof a === 'number' && typeof b === 'number' && Math.abs(a - b) <= eps;
  /* ---- 0. the rules in one place; the pit lane allowance by programme week; the Helen Park holding strip */
  const A = await p.evaluate(() => { const H = FLOW891.holding, d = (p, q) => Math.hypot((p[1] - q[1]) * 111320 * Math.cos(-27.98 * Math.PI / 180), (p[0] - q[0]) * 110540);
    const wb04 = (MASTER_LOC.WB04 || {}).ll, mp = MP819.points.find(x => x.id === 'HELEN_PARK');
    return {source: FLOW891.source, maxHelen: FLOW891.areas.helenPark.max, maxMain: FLOW891.areas.mainBeach.max, ov: FLOW891.oversized.total, holdMax: H.max, len: d(H.line[0], H.line[1]), toLabel: wb04 ? d(H.ll, wb04) : null, toMp: mp ? d(H.ll, mp.ll) : null,
      pinsSame: !!wb04 && wb04[0] === -27.981235 && wb04[1] === 153.423761 && !!mp && mp.ll[0] === -27.981233,
      pit: ['2026-09-10', '2026-09-15', '2026-09-22', '2026-10-03', '2026-10-08', '2026-10-19', '2026-10-27', '2026-09-01'].map(iso => [iso, flow891PitLaneMax(iso).max, flow891PitLaneMax(iso).words]), checklist: FLOW891.checklist}; });
  ok('the rules carry their source (the project manager, 8 Oct 2026 — the page’s own words for Andrew): Main Beach 1, Helen Park 4, oversized guide 7, holding 4', /project manager, 8 Oct 2026/.test(A.source) && A.maxMain === 1 && A.maxHelen === 4 && A.ov === 7 && A.holdMax === 4, A);
  ok('Helen Park holding strip: about 50 m, within 60 m of the master’s Helen Park label and 100 m of the Helen Park meet point; no pin moved', near(A.len, 50, 8) && A.toLabel != null && A.toLabel < 60 && A.toMp != null && A.toMp < 100 && A.pinsSame, A);
  ok('pit lane allowance follows the programme weeks: Weeks 6–5 up to 6, Week 4 onwards 2 (gaps take the week before), before the programme not set', JSON.stringify(A.pit.map(x => x[1])) === JSON.stringify([6, 6, 2, 2, 2, 2, 2, null]) && /not set/.test(A.pit[7][2]), A.pit);
  ok('the printed checklist is Andrew’s four lines', JSON.stringify(A.checklist) === JSON.stringify(['Site aware of truck status', 'Loads all ready', 'Truck doors loaded on the correct side', 'Trucks staggered']), A.checklist);
  /* ---- 1. nothing moves until an order is saved; oversized reads the item words; curfew and window rules */
  const B = await p.evaluate(() => { const out = {same: true, days: 0}; programmeDays().forEach(d => { const a = dpLoads(d), b = dpLoadsBefore891(d); out.days++; if (a.length !== b.length || a.some((g, i) => g !== b[i])) out.same = false; });
    const row = key => { const d = programmeDays().find(x => x.deliveries.some(r => r.a.key === key)); return d ? d.deliveries.find(r => r.a.key === key) : null; };
    const wc60 = row('WC60'), gn18 = row('GN18'), fwf = row('WC61'), t = (time, ov) => flow891Curfew({time}, {oversize: ov});
    return Object.assign(out, {wc60: wc60 ? flow891Oversize(wc60) : null, gn18: gn18 ? flow891Oversize(gn18) : null, fwf: fwf ? flow891Oversize(fwf) : null,
      late: t('08:30', true), ok: t('04:30', true), early: t('05:30', true), unknown: t(null, true), none: t('08:30', false),
      win: flow891WindowOf('2026-10-07', '05:00', ['P55'], true), winAfter: flow891WindowOf('2026-10-09', '05:00', ['WC57'], false), winNone: flow891WindowOf('2026-10-09', null, ['WC57'], false)}); });
  ok('with no saved order every day reads exactly as before (' + B.days + ' days)', B.same, B);
  ok('oversized reads the item words: WC60’s Toilet Block 6m yes, GN18 generator no, FWF toilets no', B.wc60 === true && B.gn18 === false && B.fwf === false, B);
  ok('curfew first: an oversized load loaded 08:30 is on the road in the 07:00–09:00 restriction; 04:30 is the earliest run; no time says so; not oversized is not flagged', B.late.state === 'late' && /07:00–09:00/.test(B.late.words) && /Make it Load 1/.test(B.late.fix) && B.ok.state === 'ok' && B.early.state === 'ok' && B.unknown.state === 'unknown' && /not known/.test(B.unknown.words) && B.none === null, B);
  ok('arrival windows: a 05:00 booking lands 06:10–06:40 (70 min run, 30 min unload); a 05:00 schedule load waits for the 07:00 access; no time means not known', B.win.known && B.win.start === 370 && B.win.finish === 400 && B.winAfter.known && B.winAfter.start === 420 && !B.winNone.known && /not known/.test(B.winNone.basis), B);
  /* ---- 2. the day's card and the order controls on a coming day with several loads */
  const day = await p.evaluate(() => { const t0 = todayIso(); const d = programmeDays().find(x => x.iso >= t0 && dpLoads(x).filter(g => g.kind === 'deliveries').length >= 4 && dpLoads(x).every(g => g.kind === 'deliveries')) || programmeDays().find(x => x.iso >= t0 && dpLoads(x).filter(g => g.kind === 'deliveries').length >= 2); return d ? d.iso : null; });
  ok('a coming day with several delivery loads exists for the practice (' + day + ')', !!day, day);
  await p.evaluate(iso => { state.day = iso; state.tlView = 'day'; go('timeline'); render(); }, day); await p.waitForTimeout(600);
  const money0 = await p.evaluate(() => JSON.stringify([moneySummary(), fh866Model()]));
  const C = await p.evaluate(iso => { const d = programmeDays().find(x => x.iso === iso), M = flow891Day(d), card = document.querySelector('.flow891[data-flow891="' + iso + '"]'), L = dpLoads(d);
    const lines = [...document.querySelectorAll('#pane-timeline .ldlist .ld[data-tl846-load]')], ords = lines.map(l => (l.querySelector('.flow891-ordw') || {}).textContent || '');
    return {card: !!card, h3: card ? card.querySelector('h3').textContent : '', sub: card ? card.querySelector('.sub').textContent : '', rows: card ? [...card.querySelectorAll('.flow891-row > b')].map(b => b.textContent) : [], loads: L.length, D: M.deliveries.length, lines: lines.length, ords,
      firstUpDisabled: !!(lines[0] && lines[0].querySelector('[data-flow891-move="up"]') || {}).disabled, lastDownDisabled: !!(lines[lines.length - 1] && lines[lines.length - 1].querySelector('[data-flow891-move="down"]') || {}).disabled,
      grips: document.querySelectorAll('#pane-timeline [data-flow891-grip]').length, people: M.people, rulesOpen: card ? card.querySelector('.flow891-rules').open : null, nav: card ? !!card.querySelector('.flow891-rules a[href*="google.com/maps/dir"]') : false, cardTxt: card ? card.innerText : '',
      plateSub: (document.querySelector('.dplate .dpt-s') || {}).textContent || '', unknown: M.unknownWindows, share: M.share.map(x => ({fits: x.fits, area: x.area, why: x.why})), guide: card ? !!card.querySelector('a[href*="Load_Restraint"]') : false}; }, day);
  ok('the Truck flow card sits on the day under its figures, headed by who is on and the loads (' + C.h3 + ')', C.card && new RegExp('(people on|People on: not set) · ' + C.loads + ' loads?').test(C.h3) && /Order|Curfew first|Could share a truck/.test(C.rows.join('|')), {h3: C.h3, rows: C.rows});
  ok('people on is not set until somebody sets it, and the card says what the number gives', C.people.count === null ? /People on: not set/.test(C.h3) && /gives the day its numbers/.test(C.sub) : /people on/.test(C.h3) && /allows/.test(C.sub), {h3: C.h3, sub: C.sub});
  ok('every delivery load line carries the order controls (grip, ▲, ▼) and reads Load k of N; the ends are disabled', C.lines === C.D && C.grips === C.D && C.ords.every((t, i) => new RegExp('Load\\s*' + (i + 1) + '\\s*of ' + C.D).test(t)) && C.firstUpDisabled && C.lastDownDisabled, {lines: C.lines, D: C.D, ords: C.ords});
  ok('the rules fold is closed, names its source and carries a Navigate link to the Helen Park holding strip', C.rulesOpen === false && C.nav && /Rules · the project manager, 8 Oct 2026/.test(C.cardTxt), {rulesOpen: C.rulesOpen, nav: C.nav});
  ok('could share a truck: same-area pairs are listed but none is suggested — weights and dimensions are not on the page; the guide is linked', C.share.every(x => x.fits === null && /weights and dimensions are not on the page/.test(x.why)) && /None suggested/.test(C.cardTxt) && (!C.share.length || C.guide), {n: C.share.length, sample: C.share[0]});
  ok('loads with no arrival window are counted and the card says how to give them one', C.unknown === 0 || /no arrival window yet/.test(C.cardTxt), {unknown: C.unknown});
  if (OUT) { await p.locator('.flow891').first().scrollIntoViewIfNeeded(); await p.screenshot({path: path.join(OUT, 'card_' + tag + '.png')}); }
  /* ---- 3. view only: the order controls behave like every other edit */
  const V = await p.evaluate(iso => { const d = programmeDays().find(x => x.iso === iso), before = dpLoads(d).map(g => ldId(d, g)); const b = document.querySelector('#pane-timeline [data-flow891-move="down"]:not(:disabled)'); if (!b) return {no: true};
    const f0 = (document.getElementById('flash') || {}).textContent || ''; b.click(); const after = dpLoads(d).map(g => ldId(d, g)); return {flash: (document.getElementById('flash') || {}).textContent || '', same: JSON.stringify(before) === JSON.stringify(after), cap: capability()}; }, day);
  ok('on the view link a reorder is refused the page’s way (View only …) and nothing moves', V.no !== true && V.same && /View only/.test(V.flash) && V.cap === 'view', V);
  /* ---- 4. edit practice: stubs instead of the record; the local record is restored afterwards */
  await p.evaluate(() => { window.__saved891 = JSON.stringify(S); window.__old891 = {bump, whoAmI, mayWrite, capability, readonly: SYNC.readonly, operator: S.operator}; window.bump = () => { render(); }; window.whoAmI = () => 'Isolated check'; window.mayWrite = () => true; window.capability = () => 'edit'; SYNC.readonly = false; render(); });
  await p.waitForTimeout(300);
  const scrollSel = '#pane-timeline .ldlist .ld[data-tl846-load]';
  const E = await p.evaluate(iso => { const d = programmeDays().find(x => x.iso === iso), ids0 = dpLoads(d).map(g => ldId(d, g)), refs0 = dpLoads(d).map(g => g.rows.map(r => r.a.key).join('+'));
    const scroller = ldScroller(document.querySelector('#pane-timeline .ldlist')) || document.querySelector('main'); const first = document.querySelector('#pane-timeline .ldlist .ld[data-tl846-load]'); first.scrollIntoView({block: 'center'}); const top0 = scroller.scrollTop;
    const b = first.querySelector('[data-flow891-move="down"]'); b.focus(); b.click();
    const d2 = programmeDays().find(x => x.iso === iso), ids1 = dpLoads(d2).map(g => ldId(d2, g)), refs1 = dpLoads(d2).map(g => g.rows.map(r => r.a.key).join('+'));
    const lines = [...document.querySelectorAll('#pane-timeline .ldlist .ld[data-tl846-load]')];
    const plate = [...document.querySelectorAll('.dplate [data-pdf7="drivers"][data-only]')].map(x => x.querySelector('b').textContent + ' ' + x.querySelector('span').textContent);
    const hdr = dpHeader(d2, dpLoads(d2)[0], 'drv', 1, dpLoads(d2).length), model = daily821Model(iso), scope = (driverModel826(iso, null) || {scope: []}).scope;
    const rec = Object.keys(S.loads || {}).filter(k => k.startsWith('crew883/' + iso + '/') && S.loads[k].ref).map(k => S.loads[k]);
    return {ids0, ids1, refs0, refs1, swapped: ids1[0] === ids0[1] && ids1[1] === ids0[0] && ids1.slice(2).join() === ids0.slice(2).join(), lineIds: lines.map(l => l.dataset.tl846Load), ords: lines.map(l => (l.querySelector('.flow891-ordw') || {}).textContent || ''),
      plate, hdrHasNewFirst: hdr.includes('Load 1 of ' + ids0.length) && hdr.includes(refs1[0].split('+')[0]), modelFirst: model.loads[0] && model.loads[0].rows[0].key, scope0: scope[0] || '', scrollJump: Math.abs(scroller.scrollTop - top0), focused: document.activeElement && document.activeElement.dataset ? document.activeElement.dataset.flow891Move : null,
      rec: rec.map(r => ({ref: r.ref, order: r.order, kind: r.kind, by: r.by, stamped: !!r.at})), flash: (document.getElementById('flash') || {}).textContent || ''}; }, day);
  ok('▼ on Load 1 swaps it with Load 2 and every label renumbers at once: the list, the Drivers plate menu, the sheet header, the message model and the pre-dispatch scope', E.swapped && E.lineIds.join() === E.ids1.join() && E.ords.every((t, i) => new RegExp('Load\\s*' + (i + 1) + ' of').test(t)) && E.plate[0] && E.plate[0].startsWith('Load 1 ' + E.refs1[0].split('+')[0]) && E.hdrHasNewFirst && E.modelFirst === E.refs1[0].split('+')[0] && E.scope0.startsWith('Load 1 · Delivery · ' + E.refs1[0].split('+')[0]), {ids0: E.ids0, ids1: E.ids1, plate: E.plate.slice(0, 3), modelFirst: E.modelFirst, scope0: E.scope0, ords: E.ords});
  ok('the order is saved as the planned arrival order on the crew record (kind crew883, one document per reference, stamped and named)', E.rec.length >= E.ids1.length && E.rec.every(r => r.kind === 'crew883' && Number.isInteger(r.order) && r.by === 'Isolated check' && r.stamped) && /Load order saved/.test(E.flash), {rec: E.rec.slice(0, 4), flash: E.flash});
  ok('no scroll jump on reorder (' + E.scrollJump + ' px) and the focus stays on the control that was pressed', E.scrollJump <= 2 && (E.focused === 'down' || E.focused === 'up'), {jump: E.scrollJump, focused: E.focused});
  if (OUT) await p.screenshot({path: path.join(OUT, 'reorder_' + tag + '.png')});
  const K = await p.evaluate(iso => { const d = programmeDays().find(x => x.iso === iso), ids0 = dpLoads(d).map(g => ldId(d, g)); const lines = [...document.querySelectorAll('#pane-timeline .ldlist .ld[data-tl846-load]')]; const grip = lines[1].querySelector('[data-flow891-grip]'); grip.focus();
    grip.dispatchEvent(new KeyboardEvent('keydown', {key: 'ArrowUp', altKey: true, bubbles: true, cancelable: true})); const d2 = programmeDays().find(x => x.iso === iso), ids1 = dpLoads(d2).map(g => ldId(d2, g));
    return {moved: ids1[0] === ids0[1] && ids1[1] === ids0[0], focusGrip: !!(document.activeElement && document.activeElement.dataset && document.activeElement.dataset.flow891Grip)}; }, day);
  ok('Alt + ↑ on the grip moves the load up (keyboard), and the grip keeps focus', K.moved && K.focusGrip, K);
  let dragged = null; try { const lines = p.locator(scrollSel); const n = await lines.count(); if (n >= 3) { const before = await p.evaluate(iso => { const d = programmeDays().find(x => x.iso === iso); return dpLoads(d).map(g => ldId(d, g)); }, day);
      await lines.nth(0).locator('[data-flow891-grip]').dragTo(lines.nth(2), {targetPosition: {x: 40, y: 10}}); await p.waitForTimeout(500);
      const after = await p.evaluate(iso => { const d = programmeDays().find(x => x.iso === iso); return dpLoads(d).map(g => ldId(d, g)); }, day); dragged = {before, after, changed: before.join() !== after.join() && after.includes(before[0])}; } } catch (e) { dragged = {error: String(e.message).slice(0, 120)}; }
  const Dfn = await p.evaluate(iso => { const d = programmeDays().find(x => x.iso === iso), ids0 = dpLoads(d).map(g => ldId(d, g)); if (ids0.length < 3) return {skip: true}; const r = flow891Drop(iso, ids0[0], ids0[2], false); const d2 = programmeDays().find(x => x.iso === iso), ids1 = dpLoads(d2).map(g => ldId(d2, g)); return {r, ok: ids1[2] === ids0[0] && ids1[0] === ids0[1] && ids1[1] === ids0[2]}; }, day);
  ok('drag and drop reorders (desktop pointer drag' + (dragged && dragged.changed ? ' moved it' : dragged && dragged.error ? ' not driven here: ' + dragged.error : ' left it') + '; the drop rule itself puts a load after another)', Dfn.skip || (Dfn.r && Dfn.ok), {dragged, Dfn});
  /* ---- 5. people on for the day, through the crew record */
  const Pp = await p.evaluate(iso => { const card = document.querySelector('.flow891[data-flow891="' + iso + '"]'); const inp = card.querySelector('[data-flow891-people]'); inp.value = '3'; card.querySelector('[data-flow891-people-save]').click();
    const c2 = document.querySelector('.flow891[data-flow891="' + iso + '"]'); const h = c2.querySelector('h3').textContent, sub = c2.querySelector('.sub').textContent, count = crew883Day(iso).count;
    c2.querySelector('[data-flow891-people]').value = ''; c2.querySelector('[data-flow891-people-save]').click(); const c3 = document.querySelector('.flow891[data-flow891="' + iso + '"]');
    return {h, sub, count, unset: c3.querySelector('h3').textContent, countAfter: crew883Day(iso).count}; }, day);
  ok('people on sets the day’s numbers: 3 people on → 1 unload at a time (2 people each); blank → not set', /3 people on/.test(Pp.h) && /allows 1 unload at a time/.test(Pp.sub) && Pp.count === 3 && /People on: not set/.test(Pp.unset) && Pp.countAfter === null, Pp);
  /* ---- 6. area limits: two Main Beach loads planned at the same time are flagged with the simplest fix; the stagger writes the window */
  const Ar = await p.evaluate(() => { const t0 = todayIso(); const pick = programmeDays().filter(d => d.iso >= t0).map(d => { const X = flow891Day(d).deliveries.filter(x => x.area.key === 'mainBeach'); return {d, X}; }).find(x => x.X.length >= 2); if (!pick) return {skip: true};
    const {d, X} = pick, iso = d.iso; state.day = iso; state.tlView = 'day'; render(); const put = (x, st, fi) => x.refs.forEach(r => { const k = crew883Key(iso, r.key), old = S.loads[k] || {people: [], order: null, location: ''}; S.loads[k] = Object.assign({}, old, {start: st, finish: fi, kind: 'crew883', day: iso, ref: r.key, by: 'Isolated check', at: new Date().toISOString()}); });
    put(X[0], '09:00', '09:30'); put(X[1], '09:00', '09:30'); render(); const M = flow891Day(programmeDays().find(x => x.iso === iso)), a = M.areas.find(z => z.key === 'mainBeach'), card = document.querySelector('.flow891[data-flow891="' + iso + '"]'), txt = card.innerText;
    const chip = [...document.querySelectorAll('#pane-timeline .flow891-chip')].map(c => c.textContent); const btn = card.querySelector('[data-flow891-stagger]'); const to = btn ? Number(btn.dataset.flow891To) : null; if (btn) btn.click();
    const M2 = flow891Day(programmeDays().find(x => x.iso === iso)), a2 = M2.areas.find(z => z.key === 'mainBeach'), moved = S.loads[crew883Key(iso, X[1].refs[0].key)] || {}, txt2 = document.querySelector('.flow891[data-flow891="' + iso + '"]').innerText;
    return {iso, loads: [X[0].n, X[1].n], peak: a.peak, conflicts: a.conflicts.map(c => ({at: c.at, loads: c.loads, to: c.to})), flagged: /over the limit of 1/.test(txt) && /Fix: stagger Load/.test(txt) && /hold it at Helen Park/.test(txt), chip, to, after: a2.conflicts.length, movedStart: moved.start, movedFinish: moved.finish, cleared: !/over the limit/.test(txt2)}; });
  ok('Main Beach: two trucks planned 09:00–09:30 are flagged (limit 1) with the fix — stagger the later one to 09:30, or hold it at Helen Park; an Area full chip sits on the line', Ar.skip || (Ar.peak === 2 && Ar.conflicts.length === 1 && Ar.conflicts[0].to === 570 && Ar.flagged && Ar.chip.includes('Area full')), Ar);
  ok('one tap staggers the later load to 09:30 through the crew record (planned unloading window 09:30–10:00) and the flag clears', Ar.skip || (Ar.to === 570 && Ar.movedStart === '09:30' && Ar.movedFinish === '10:00' && Ar.after === 0 && Ar.cleared), Ar);
  if (OUT && !Ar.skip) { await p.locator('.flow891').first().scrollIntoViewIfNeeded(); await p.screenshot({path: path.join(OUT, 'areas_' + tag + '.png')}); }
  /* ---- 7. curfew first on the record's own days: 7 Oct (P57, P52 loaded 08:30) and 1 Oct (WC60, the example) */
  const Cf = await p.evaluate(() => { const day7 = programmeDays().find(x => x.iso === '2026-10-07'), day1 = programmeDays().find(x => x.iso === '2026-10-01'); if (!day7 || !day1) return {skip: true};
    const M7 = flow891Day(day7), late = M7.curfew.filter(x => x.curfew.state === 'late').map(x => flow891Refs(x.g)), okk = M7.curfew.filter(x => x.curfew.state === 'ok').map(x => flow891Refs(x.g)); const M1 = flow891Day(day1), wc60 = M1.curfew.find(x => /WC60/.test(flow891Refs(x.g)));
    state.day = '2026-10-07'; state.tlView = 'day'; render(); const card = document.querySelector('.flow891[data-flow891="2026-10-07"]'), txt = card ? card.innerText : ''; const btn = card ? card.querySelector('[data-flow891-first]') : null; const target = btn ? btn.dataset.flow891First : null; if (btn) btn.click();
    const d2 = programmeDays().find(x => x.iso === '2026-10-07'), first = dpLoads(d2)[0]; return {late, ok: okk, wc60: wc60 ? wc60.curfew.state : null, wc60words: wc60 ? wc60.curfew.words : '', flagged: /Curfew first/.test(txt) && /on the road in the 07:00–09:00 restriction/.test(txt), hadBtn: !!btn, movedFirst: !!first && ldId(d2, first) === target, chips: [...document.querySelectorAll('#pane-timeline .flow891-chip')].map(c => c.textContent)}; });
  ok('7 Oct: the oversized buildings loaded 08:30 (P57, P52) are flagged curfew-first; the 05:00 loads are on the earliest run; WC60 (1 Oct, loaded 08:30) reads the same', Cf.skip || (Cf.late.includes('P57') && Cf.late.includes('P52') && Cf.ok.includes('P55') && Cf.wc60 === 'late' && /07:00–09:00/.test(Cf.wc60words) && Cf.flagged), Cf);
  ok('one tap makes a flagged load Load 1 (the day’s order), and the lines carry a Curfew first chip', Cf.skip || (Cf.hadBtn && Cf.movedFirst && Cf.chips.includes('Curfew first')), Cf);
  if (OUT && !Cf.skip) { await p.locator('.flow891').first().scrollIntoViewIfNeeded(); await p.screenshot({path: path.join(OUT, 'curfew_' + tag + '.png')}); }
  /* ---- 8. the prints: checklist, order, window, holding and Printed by on every sheet; the check's snapshot stays clean */
  const Pr = await p.evaluate(iso => { try { localStorage.removeItem('gc500.printedBy'); } catch (e) {} S.operator = 'Andrew'; const noName = flow891PrintedBy(); S.operator = 'Andrew Fisher'; const opName = flow891PrintedBy(); S.operator = ''; flow891Remember('Andrew Fisher'); const stored = flow891PrintedBy();
    const d = programmeDays().find(x => x.iso === iso), L = dpLoads(d), g = L[0], n = L.length; const drv = dpPage(d, g, 'drv', 1, n), ins = dpPage(d, g, 'ins', 1, n), signs = pl782Pages(d, g, 1, n), snap = pl782Pages(d, g, 0, 0), a = g.rows[0].a, drop = dropPage(a, g.rows[0].events || [], 1, 1, {iso}, 'deliveries');
    const has = (h, w) => h.includes(w); const lines = FLOW891.checklist; return {noName, opName, stored, drvCk: lines.every(w => has(drv, w)), insCk: lines.every(w => has(ins, w)), drvBy: /Printed by Andrew Fisher · \d\d [A-Z][a-z]{2} 2026, \d\d:\d\d AEST/.test(drv), insBy: /Printed by Andrew Fisher/.test(ins), order: has(drv, 'this is load 1 of ' + n) && has(drv, 'A truck out of order delays everyone'), hold: has(drv, 'Hold at Helen Park — red line, Rankin Pde'), window: /Arrival window<\/label><b>[^<]+<\/b>/.test(drv), signsBy: signs === '' || /Printed by Andrew Fisher/.test(signs), snapClean: !/Printed by/.test(snap), dropBy: /Printed by Andrew Fisher/.test(drop), once: (drv.match(/Printed by/g) || []).length === 1, stripBeforeFoot: drv.indexOf('dp-flow891') < drv.indexOf('dp-ft') && drv.indexOf('dp-flow891') > 0}; }, day);
  ok('Printed by needs a first and last name: one word is “name not recorded”; the operator’s full name counts; the remembered name counts, with the 24-hour stamp', /name not recorded/.test(Pr.noName) && /Printed by Andrew Fisher/.test(Pr.opName) && /Printed by Andrew Fisher · \d\d [A-Z][a-z]{2} 2026, \d\d:\d\d AEST/.test(Pr.stored), Pr);
  ok('the Drivers and Install sheets carry the four checklist lines, the allocated order, the arrival window, the holding instruction and Printed by, once, above the footer', Pr.drvCk && Pr.insCk && Pr.drvBy && Pr.insBy && Pr.order && Pr.hold && Pr.window && Pr.once && Pr.stripBeforeFoot, Pr);
  ok('the location signs and the drop sheet carry Printed by; the pre-dispatch check’s snapshot of the signs stays clean (no stamp, so a minute ticking over cannot fail a print)', Pr.signsBy && Pr.snapClean && Pr.dropBy, Pr);
  /* ---- 9. the pre-dispatch check asks for first and last name and carries the first two checklist lines; Escape closes it */
  const Ck = await p.evaluate(iso => new Promise(res => { let went = false; drvCheck782(iso, 0, () => { went = true; }); setTimeout(() => { const box = document.getElementById('drv782'); if (!box) return res({noBox: true});
    const texts = [...box.querySelectorAll('label.ck span')].map(x => x.textContent), nm = box.querySelector('#drv782n'), go = box.querySelector('.b-go'), cks = [...box.querySelectorAll('input[type=checkbox]')]; cks.forEach(c => { c.checked = true; c.dispatchEvent(new Event('change', {bubbles: true})); });
    nm.value = 'Andrew'; nm.dispatchEvent(new Event('input', {bubbles: true})); const one = go.disabled; nm.value = 'Andrew Fisher'; nm.dispatchEvent(new Event('input', {bubbles: true})); const two = go.disabled; const ph = nm.placeholder, small = (box.querySelector('.dw782 small') || {}).textContent || '';
    box.dispatchEvent(new KeyboardEvent('keydown', {key: 'Escape', bubbles: true})); res({texts, one, two, ph, small, closed: !document.getElementById('drv782'), went}); }, 400); }), day);
  ok('the pre-dispatch check lists “Site is aware of the status of the trucks” and “The loads are all ready”, wants a first AND last name, and Escape closes it', !Ck.noBox && Ck.texts.includes('Site is aware of the status of the trucks.') && Ck.texts.includes('The loads are all ready.') && Ck.texts.some(t => /staggered/.test(t)) && Ck.one === true && Ck.two === false && Ck.ph === 'First and last name' && /Printed by/.test(Ck.small) && Ck.closed && !Ck.went, Ck);
  if (OUT) { await p.evaluate(iso => { drvCheck782(iso, 0, () => {}); }, day); await p.waitForTimeout(400); await p.screenshot({path: path.join(OUT, 'check_dialog_' + tag + '.png')}); await p.evaluate(() => document.querySelectorAll('#drv782').forEach(e => e.remove())); }
  /* ---- 10. who is printing: asked once (Close ×, Not now, Escape), remembered; then no prompt */
  const Nm = await p.evaluate(iso => new Promise(res => { try { localStorage.removeItem('gc500.printedBy'); } catch (e) {} S.operator = ''; pdf7Open('install', iso, 0, false); setTimeout(() => { const box = document.getElementById('flow891name'); if (!box) return res({noBox: true});
    const hasX = !!box.querySelector('.x[data-flow891-close]'), hasNo = /Not now/.test(box.querySelector('.b-no').textContent), inp = box.querySelector('#flow891n'), go = box.querySelector('.b-go'); const disabled0 = go.disabled; inp.value = 'Andrew'; inp.dispatchEvent(new Event('input', {bubbles: true})); const disabled1 = go.disabled;
    box.dispatchEvent(new KeyboardEvent('keydown', {key: 'Escape', bubbles: true})); const closedByEsc = !document.getElementById('flow891name'), noPdf = !document.getElementById('pdf7');
    pdf7Open('install', iso, 0, false); const box2 = document.getElementById('flow891name'); const inp2 = box2.querySelector('#flow891n'); inp2.value = 'Andrew Fisher'; inp2.dispatchEvent(new Event('input', {bubbles: true})); inp2.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', bubbles: true}));
    setTimeout(() => { const gone = !document.getElementById('flow891name'), pdf = !!document.getElementById('pdf7'), remembered = localStorage.getItem('gc500.printedBy'), pdfClose = !!document.querySelector('#pdf7 [data-pdf7-x]'); pdf7Close();
      pdf7Open('install', iso, 0, false); const again = !!document.getElementById('flow891name'), pdf2 = !!document.getElementById('pdf7'); pdf7Close(); res({hasX, hasNo, disabled0, disabled1, closedByEsc, noPdf, gone, pdf, pdfClose, remembered, again, pdf2}); }, 300); }, 300); }), day);
  ok('the name prompt has Close (×), Not now and Escape; one word is not enough; nothing prints until a name is given', !Nm.noBox && Nm.hasX && Nm.hasNo && Nm.disabled0 && Nm.disabled1 && Nm.closedByEsc && Nm.noPdf, Nm);
  ok('a first and last name continues to the PDFs (the panel has Close), is remembered on the device and is not asked again', Nm.gone && Nm.pdf && Nm.pdfClose && Nm.remembered === 'Andrew Fisher' && Nm.again === false && Nm.pdf2, Nm);
  if (OUT) { await p.evaluate(iso => { try { localStorage.removeItem('gc500.printedBy'); } catch (e) {} S.operator = ''; pdf7Open('install', iso, 0, false); }, day); await p.waitForTimeout(300); await p.screenshot({path: path.join(OUT, 'name_prompt_' + tag + '.png')}); await p.evaluate(() => { document.querySelectorAll('#flow891name').forEach(e => e.remove()); flow891Remember('Andrew Fisher'); }); }
  /* ---- 11. the messages to install teams: the sender's full name; each load's order, window and holding words; the daily page */
  const Ms = await p.evaluate(iso => { const team = {name: 'Install team'}; let oneWord = ''; S.operator = 'Andrew'; try { daily861Body(iso, team, 'https://example.invalid/d/x', {text: 'Fine'}); } catch (e) { oneWord = e.message; }
    S.operator = 'Andrew Fisher'; const body = daily861Body(iso, team, 'https://example.invalid/d/x', {text: 'Fine'}); const m = daily821Model(iso), n = m.loads.length, notes = m.loads.map(l => l.rows.map(r => r.notes.join(' | ')).join(' || ')); const html = daily821Html(m, team, 'local'); S.operator = '';
    return {oneWord, sent: /Sent by Andrew Fisher\./.test(body) && body.indexOf('Sent by') < body.indexOf('Your daily runs'), len: body.length, notes1: notes[0] || '', every: m.loads.every(l => l.rows.every(r => r.notes.some(t => t.startsWith('Load ' + l.n + ' of ' + n + ' — the trucks arrive in this order') && /Hold at Helen Park/i.test(t)))), prepared: /Prepared by Andrew Fisher · Issued/.test(html), orderLine: /In load order — the trucks arrive in this order/.test(html), sender: m.sender}; }, day);
  ok('a message needs the sender’s first and last name in Recording as; with it the text says “Sent by Andrew Fisher.” and stays under the texting limit', /first and last name/.test(Ms.oneWord) && Ms.sent && Ms.len <= 480, Ms);
  ok('every reference in the message model carries its load’s order, arrival window and the Helen Park holding words; the daily page says Prepared by and the arrival order', Ms.every && Ms.prepared && Ms.orderLine && Ms.sender === 'Andrew Fisher', {notes1: Ms.notes1.slice(0, 200), prepared: Ms.prepared, orderLine: Ms.orderLine});
  /* ---- 12. put the record back; nothing about money changed; the layout holds */
  const Z = await p.evaluate(() => { const o = window.__old891; S = JSON.parse(window.__saved891); Object.assign(window, {bump: o.bump, whoAmI: o.whoAmI, mayWrite: o.mayWrite, capability: o.capability}); SYNC.readonly = o.readonly; S.operator = o.operator; RENDER_MEMO.clear(); render();
    return {restored: JSON.stringify(S) === window.__saved891, money: JSON.stringify([moneySummary(), fh866Model()]), cap: capability()}; });
  ok('the local record is put back byte for byte and the link is view-only again', Z.restored && Z.cap === 'view', {restored: Z.restored, cap: Z.cap});
  ok('no money figure changed through any of it (moneySummary and the Finance handover model identical)', Z.money === money0, {same: Z.money === money0});
  await p.evaluate(iso => { state.day = iso; state.tlView = 'day'; render(); }, day); await p.waitForTimeout(400);
  const Ly = await p.evaluate(() => { const card = document.querySelector('.flow891'), pane = document.getElementById('pane-timeline'), main = document.querySelector('main'); const btns = [...document.querySelectorAll('#pane-timeline .flow891-ord button, .flow891 .btn, .flow891-rules summary')].map(b => b.getBoundingClientRect().height);
    const row = card ? getComputedStyle(card.querySelector('.flow891-row')).gridTemplateColumns.split(' ').length : 0; return {overflow: document.documentElement.scrollWidth <= innerWidth + 2, paneOverflow: pane.scrollWidth <= (main ? main.clientWidth : innerWidth) + 2, cardW: card ? card.getBoundingClientRect().width : 0, paneW: pane.clientWidth, minBtn: Math.min(...btns.filter(h => h > 0)), cols: row, motion: getComputedStyle(document.querySelector('.ld') || document.body).transitionProperty}; });
  ok('layout: no horizontal overflow, the card fits its pane, every control is at least 40 px tall, rows ' + (MOB ? 'stack on the phone' : 'keep two columns'), Ly.overflow && Ly.paneOverflow && Ly.cardW <= Ly.paneW + 2 && Ly.minBtn >= 39 && (MOB ? Ly.cols === 1 : Ly.cols === 2), Ly);
  /* ---- 13. the Drivers and Install sheets rendered to PDF (looked at in the evidence) */
  if (OUT && !MOB) { for (const doc of ['drv', 'ins']) { await p.evaluate(([iso, d]) => { flow891Remember('Andrew Fisher'); dpPrint(iso, d, {only: 0}); }, [day, doc]); await p.waitForFunction(() => !!document.querySelector('#dayprint .dp-page') && document.getElementById('dayprint').dataset.dpReady !== undefined, null, {timeout: 60000}).catch(() => {}); await p.waitForTimeout(2500);
      try { await p.pdf({path: path.join(OUT, (doc === 'drv' ? 'drivers' : 'install') + '_sheet_' + tag + '.pdf'), format: 'A4', printBackground: true, preferCSSPageSize: true}); } catch (e) { console.log('pdf skipped: ' + e.message.slice(0, 80)); }
      const pg = p.locator('#dayprint .dp-page').first(); try { await pg.screenshot({path: path.join(OUT, (doc === 'drv' ? 'drivers' : 'install') + '_sheet_' + tag + '.png')}); } catch (e) { console.log('shot skipped: ' + e.message.slice(0, 80)); }
      const fit = await p.evaluate(() => { const pg = document.querySelector('#dayprint .dp-page'), strip = pg && pg.querySelector('.dp-flow891'), ft = pg && pg.querySelector('.dp-ft'); if (!pg || !strip || !ft) return {missing: true}; const P = pg.getBoundingClientRect(), S0 = strip.getBoundingClientRect(), F = ft.getBoundingClientRect(); return {inside: S0.bottom <= F.top + 1 && F.bottom <= P.bottom + 1, stripH: Math.round(S0.height), footTop: Math.round(F.top - P.top), pageH: Math.round(P.height)}; });
      ok('the ' + (doc === 'drv' ? 'Drivers' : 'Install') + ' sheet keeps the truck flow strip above the footer on the one A4 page', !fit.missing && fit.inside, fit);
      await p.evaluate(() => { const x = document.querySelector('#dpbar [data-dpbar-x]'); if (x) x.click(); }); await p.waitForTimeout(500); } }
  /* ---- the wrap */
  ok('no page errors', s.errors.length === 0, s.errors); ok('no attempted live writes', s.counts.blocked === 0, s.counts);
  const passN = R.filter(r => r.pass).length; console.log('flow891 ' + tag + ': ' + passN + '/' + R.length); if (OUT) fs.writeFileSync(path.join(OUT, 'flow891_' + tag + '.json'), JSON.stringify({tag, timing: T, results: R}, null, 1));
  await s.browser.close(); process.exit(passN === R.length ? 0 : 1);
} catch (e) { console.error('FAIL harness', e && e.stack || e); if (s && s.browser) await s.browser.close().catch(() => {}); process.exit(2); } })();
