import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {Drive} from './drive.js';
import {GEAR,stageFraction} from './gear-math.js';
import {PARTS,buildModel,environment} from './model.js';
import {ringNames,KPIs,pillars,traits} from './content.js';
import {partPose} from './poses.js';
import {initPartsRegister} from './parts-register.js';
const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const drive=new Drive(PARTS.length,PARTS.map(p=>p.rotates),PARTS);let model,renderer,scene,camera,controls,ready=false,selected=0,mode='orbit',isolated=false,cutaway=false,quality='laptop',camTween=null,currentView='3d',drag=null,clickStart=null,pinch=null,tour=-1,audioContext=null,audioGain=null,audioOsc=null,sound=false,capturing=false;
const pointer=new T.Vector2(),raycaster=new T.Raycaster(),touches=new Map();let lastFrame=performance.now(),uiAt=0,toastTimer,labelUntil=0,boxHelper;let flow=false,slow=false,keyLight=null,lastRender=0,renderFPS=0,frameCount=0,fpsAt=performance.now();
let graphicsUnavailable=false,mechanismView=false,followAnchor=null;
function toast(s){$('toast').textContent=s;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3400);$('announcement').textContent=s;}
$('panel-description').textContent=PARTS.length+' removable parts. Find every reference. Explore every connection.';
const connectionRoot=document.querySelector('.connections');connectionRoot.innerHTML=PARTS.slice(0,4).map((p,i)=>`<button class="connection ${i===0?'active':''}" data-ring="${i}" aria-pressed="${i===0}"><span class="ring-num">0${i+1}</span><span class="name">${i===0?'Centre':p.name}</span><span class="connection-state"><i class="dot"></i><span>Connected</span></span></button>`).join('');
$('part-select').innerHTML=PARTS.map((p,i)=>`<option value="${i}">${p.ref} · ${p.name}</option>`).join('');
function selectPart(i,{focus=false}={}){selected=Math.max(0,Math.min(PARTS.length-1,i));const p=PARTS[selected];$('part-ref').textContent=p.ref;$('part-category').textContent=p.category;$('part-parent').hidden=p.mount===undefined;if(p.mount!==undefined)$('part-parent').textContent='↳ Fits '+PARTS[p.mount].ref+' · '+PARTS[p.mount].name;if(mechanismView&&!['Planetary gearbox','Clutch'].includes(p.category)){mechanismView=false;$('gearbox').setAttribute('aria-pressed',false);}if(focus&&p.kind&&ready){isolated=true;$('isolate').textContent='Show all';$('isolate').setAttribute('aria-pressed',true);}$('part-select').value=selected;$('part-number').textContent=`${String(selected+1).padStart(3,'0')} / ${PARTS.length}`;$('part-description').textContent=p.description;$('learn').hidden=selected>3;connectionRoot.querySelectorAll('button').forEach(b=>{const on=+b.dataset.ring===selected;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});$('part-pull').value=drive.pullTargets[selected];$('part-turn').value=drive.turns[selected]*180/Math.PI;$('turn-value').textContent=Math.round(drive.turns[selected]*180/Math.PI)+'°';if(ready){updateVisibility();labelUntil=performance.now()+4500;if(focus||isolated)fitCamera(currentView,selected);}updateUI(true);}
connectionRoot.querySelectorAll('[data-ring]').forEach(b=>b.addEventListener('click',()=>selectPart(+b.dataset.ring)));$('part-select').addEventListener('change',e=>selectPart(+e.target.value,{focus:isolated}));
function toggleMotor(){if(!ready)return;if(drive.running||!drive.stationary){drive.stop();toast('Motor stopping.');}else if(drive.start()){if(sound)audioContext?.resume();toast('Motor starting. 4 input turns drive 1 cog turn.');}else toast('Reconnect every part before starting the motor.');updateUI(true);}
function changeSpread(value){mechanismView=false;$('gearbox').setAttribute('aria-pressed',false);drive.requestSpread(value);isolated=false;updateVisibility();$('isolate').setAttribute('aria-pressed','false');$('isolate').textContent='Isolate';setMode('orbit');fitCamera('3d',-1,{spread:value});if(value>0)toast('Stopping the drive, then separating the assembly.');else toast('Reconnecting the assembly.');}
function reconnect(){drive.reassemble();isolated=false;updateVisibility();$('isolate').textContent='Isolate';$('isolate').setAttribute('aria-pressed','false');$('part-turn').value=0;setMode('orbit');fitCamera('3d',-1,{spread:0,pulls:[]});updateUI(true);}
function reset(){mechanismView=false;$('gearbox').setAttribute('aria-pressed',false);drive.reset();tour=-1;$('tour-bar').hidden=true;$('tour').innerHTML='▷ <span>Guided tour</span>';isolated=false;cutaway=false;flow=false;slow=false;$('flow').setAttribute('aria-pressed',false);$('slow').setAttribute('aria-pressed',false);$('slow').textContent='Slow motion';$('cutaway').setAttribute('aria-pressed',false);$('cutaway').textContent='See inside';$('isolate').textContent='Isolate';$('isolate').setAttribute('aria-pressed',false);$('speed').value=1;$('speed-value').textContent='1×';$('spread').value=0;selectPart(0);setMode('orbit');updateVisibility();if(ready){applyTransforms();fitCamera('3d');}updateUI(true);}
function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});if(mode!=='orbit'&&drive.running){drive.stop();toast('Motor stopping so you can handle the parts.');}$('hint').textContent=mode==='orbit'?'Drag to orbit · Scroll or pinch to zoom · Click any part to inspect':mode==='pull'?'Drag a part along the shaft · Use the pull slider for precise control':'Drag around a part to turn it · Connected rings move together';}
$('motor').addEventListener('click',toggleMotor);$('speed').addEventListener('input',e=>{drive.speed=+e.target.value;$('speed-value').textContent=drive.speed.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+'×';});$('explode').addEventListener('click',()=>changeSpread(drive.spreadTarget>.02?0:1));$('spread').addEventListener('input',e=>{drive.requestSpread(+e.target.value/100);if(isolated){isolated=false;updateVisibility();$('isolate').setAttribute('aria-pressed',false);$('isolate').textContent='Isolate';}});$('spread').addEventListener('change',()=>fitCamera('3d'));
$('part-pull').addEventListener('input',e=>{drive.requestPull(selected,+e.target.value);labelUntil=performance.now()+4000;});$('part-pull').addEventListener('change',()=>{if(drive.pullTargets[selected]>2.8)fitCamera(currentView,isolated?selected:-1);});
$('part-turn').addEventListener('input',e=>{const value=+e.target.value*Math.PI/180,prev=drive.turns[selected];if(!drive.stationary||drive.running){drive.stop();toast('Wait for the drive to stop before turning a part.');e.target.value=prev*180/Math.PI;return;}const coupled=drive.engaged(selected);if(!drive.turn(selected,value-prev)){toast('Pull this stationary component out before turning it.');e.target.value=0;return;}e.target.value=coupled?0:drive.turns[selected]*180/Math.PI;$('turn-value').textContent=coupled?'Linked drive':Math.round(+e.target.value)+'°';});
$('detach').addEventListener('click',()=>{if(!drive.connected(selected)){if(drive.spreadTarget>0){reconnect();toast('Reassembling all parts.');}else{drive.requestPull(selected,0);toast(PARTS[selected].name+' reconnecting.');}}else{drive.requestPull(selected,2.6);toast('Drive stopping. '+PARTS[selected].name+' will withdraw.');labelUntil=performance.now()+7000;}});
$('reconnect-all').addEventListener('click',reconnect);$('reset').addEventListener('click',reset);$('focus-part').addEventListener('click',()=>fitCamera(currentView,selected));$('isolate').addEventListener('click',()=>{isolated=!isolated;$('isolate').textContent=isolated?'Show all':'Isolate';$('isolate').setAttribute('aria-pressed',isolated);updateVisibility();fitCamera(currentView,isolated?selected:-1);});$('cutaway').addEventListener('click',()=>{cutaway=!cutaway;$('cutaway').setAttribute('aria-pressed',cutaway);$('cutaway').textContent=cutaway?'Show casing':'See inside';updateVisibility();if(cutaway){selectPart(9);fitCamera(mechanismView?'gearbox':'motor');toast('Casing hidden for inspection. Connections are unchanged.');}});
for(const [id,view] of [['view-3d','3d'],['view-front','front'],['view-back','motor']])$(id).addEventListener('click',()=>{mechanismView=false;$('gearbox').setAttribute('aria-pressed',false);updateVisibility();fitCamera(view);});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('fit').addEventListener('click',()=>fitCamera('3d',isolated?selected:-1));
function zoom(factor){if(!ready)return;camTween=null;camera.position.copy(controls.target.clone().add(camera.position.clone().sub(controls.target).multiplyScalar(factor).clampLength(.22,85)));controls.update();}$('zoom-in').addEventListener('click',()=>zoom(.82));$('zoom-out').addEventListener('click',()=>zoom(1.22));
function applyQuality(){if(!renderer)return;const ratio=quality==='laptop'?1:quality==='balanced'?1.4:2;renderer.setPixelRatio(Math.min(devicePixelRatio,ratio));if(keyLight){const n=quality==='high'?2048:1024;keyLight.shadow.mapSize.set(n,n);keyLight.shadow.map?.dispose();keyLight.shadow.map=null;}resize();$('quality').textContent='Quality: '+({laptop:'Laptop',balanced:'Balanced',high:'High'}[quality]);}
$('quality').addEventListener('click',()=>{const modes=['laptop','balanced','high'];quality=modes[(modes.indexOf(quality)+1)%3];applyQuality();toast(quality==='laptop'?'Laptop: lower drawing resolution and a 30 fps limit.':quality==='balanced'?'Balanced: sharper view with a 60 fps limit.':'High: maximum drawing resolution and sharper shadows.');});
$('flow').addEventListener('click',()=>{flow=!flow;$('flow').setAttribute('aria-pressed',flow);toast(flow?'Moving connections are highlighted.':'Power highlight off.');});
$('slow').addEventListener('click',()=>{slow=!slow;$('slow').setAttribute('aria-pressed',slow);$('slow').textContent=slow?'Slow motion on':'Slow motion';});
$('fullscreen').addEventListener('click',async()=>{const a=document.querySelector('.app');if(a.classList.contains('immersive')){a.classList.remove('immersive');if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});}else{a.classList.add('immersive');if(a.requestFullscreen)await a.requestFullscreen().catch(()=>{});}$('fullscreen').setAttribute('aria-label',a.classList.contains('immersive')?'Exit full screen':'Enter full screen');resize();});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.querySelector('.app').classList.remove('immersive');resize();});
function info(html,eyebrow='THE COATES WAY'){$('info-content').innerHTML=html;$('info-eyebrow').textContent=eyebrow;$('info').showModal();}$('info-close').addEventListener('click',()=>$('info').close());$('info').addEventListener('click',e=>{const r=$('info').getBoundingClientRect();if(e.target===$('info')&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))$('info').close();});
$('reference').addEventListener('click',()=>info('<h2>The original cog</h2><img src="./assets/cog-reference.png" alt="Original Coates Way cog"><p>From the June 2026 CMG presentation.</p>','FROM YOUR PRESENTATION'));
$('learn').addEventListener('click',()=>{let html='<h2>'+PARTS[selected].name+'</h2>';if(selected===0){html+='<p>Every decision supports Best Service and Value. These are the benchmarks from the supplied presentation.</p><div class="kpi-grid">'+KPIs.map(k=>`<div class="kpi"><strong>${k[0]}</strong><span>${k[1]}</span></div>`).join('')+'</div>';}if(selected===1||selected===3){const arr=selected===1?pillars:traits;html+=arr.map(a=>`<div class="content-item"><h3>${a.name}</h3><p>${a.text}</p><ul>${a.items.map(t=>`<li>${t}</li>`).join('')}</ul><p>${a.kpi}</p></div>`).join('');}if(selected===2){html+='<p>The Balanced Scorecard links strategy to measurable goals across People, Operations, Assets, Financials and Sales Effectiveness.</p><div class="content-item"><h3>The operating rhythm</h3><p>Daily checks · Weekly PULSE meetings · Monthly performance reviews · Quarterly strategy reviews.</p></div><div class="content-item"><h3>When a metric is red</h3><p>Document the root cause, agree a corrective action, name an owner and a deadline, and escalate persistent red metrics.</p></div>';}info(html,'RING '+(selected+1)+' OF 4');});
$('help').addEventListener('click',()=>info('<h2>Explore the machine</h2><ul class="help-list"><li><strong>Gearbox:</strong> inspect the 4:1 planetary stage with the cover and clutch hidden from view, and see live input and output speeds.</li><li><strong>Staged teardown:</strong> covers and couplings withdraw first, followed by carriers, gears and the four information rings. Reassembly reverses that sequence.</li><li><strong>Start motor:</strong> every connection must be assembled.</li><li><strong>Orbit:</strong> drag the background or model to look around; scroll or pinch to zoom.</li><li><strong>Pull:</strong> stop the drive, then drag a part along the shaft. The side slider gives precise movement.</li><li><strong>Turn:</strong> rotate a detached part. When fully assembled, manually turning a ring moves the common drive.</li><li><strong>Separate all:</strong> stops the drive and opens all 138 physical components. Reassemble restores their connections.</li><li><strong>Focus / Isolate:</strong> inspect one part closely.</li><li><strong>See inside:</strong> hides the casing without changing its connection.</li><li><strong>4K capture:</strong> saves a 3840 × 2160 image of the current scene.</li></ul><p>Keyboard on the 3D view: Space starts/stops; E separates; R reassembles; arrow keys turn or pull the selected part; +/− zoom; 0 resets.</p><p>This is an interactive illustration of the operating model. Motor speeds and mechanical details are demonstrative, not specifications for real equipment.</p>','CONTROLS'));
function inGearbox(p){return p.category==='Planetary gearbox'||p.category==='Clutch';}
function updateVisibility(){if(!model)return;for(const p of model.parts){const host=p.mount??p.index;const hiddenHousing=cutaway&&[8,11,12,14,15,16,30].includes(host);const gearboxVisible=inGearbox(p)&&(![30,32].includes(host)||p.index===selected);p.group.visible=(!isolated||p.index===selected)&&(!mechanismView||gearboxVisible||isolated)&&(!hiddenHousing||isolated);}}
$('gearbox').addEventListener('click',()=>{if(!ready)return;mechanismView=!mechanismView;isolated=false;$('isolate').setAttribute('aria-pressed',false);$('isolate').textContent='Isolate';$('gearbox').setAttribute('aria-pressed',mechanismView);updateVisibility();selectPart(mechanismView?24:0);fitCamera(mechanismView?'gearbox':'3d');toast(mechanismView?'24-tooth sun · four 24-tooth planets · fixed 72-tooth ring.':'Complete machine view.');});

function partPosition(p,spread=drive.spread,pulls=drive.pulls){return new T.Vector3().fromArray(partPose(p.index,drive,spread,pulls).position);}
function applyTransforms(){for(const p of model.parts){const pose=partPose(p.index,drive);p.group.position.fromArray(pose.position);p.group.rotation.z=pose.angle;for(const c of p.rotorChildren)if(drive.engaged(p.index))c.rotation.z=drive.angle*(p.cageRatio??.4);p.group.traverse(o=>{if(!o.isMesh)return;if(p.kind==='spring')o.scale.z=1+stageFraction(p,drive.spread)*.9;for(const m of (Array.isArray(o.material)?o.material:[o.material])){if(!m.emissive)continue;m.emissive.setHex(0xf26222);m.emissiveIntensity=flow&&p.rotates&&drive.engaged(p.index)&&drive.omega>.001?.12+.1*Math.sin(drive.angle*4-p.index*.55):0;}});}model.root.updateMatrixWorld(true);}
function fitCamera(view='3d',part=-1,override={}){if(!ready)return;currentView=view;followAnchor=isolated&&part>=0?partPosition(model.parts[part]):null;const bounds=new T.Box3();for(const p of model.parts){if(part>=0&&p.index!==part)continue;if(part<0&&mechanismView&&!inGearbox(p))continue;const b=p.localBounds.clone();b.applyMatrix4(new T.Matrix4().makeRotationZ(partPose(p.index,drive,override.spread??drive.spreadTarget,override.pulls??drive.pullTargets).angle));b.translate(partPosition(p,override.spread??drive.spreadTarget,override.pulls??drive.pullTargets));bounds.union(b);}if(bounds.isEmpty())return;const centre=bounds.getCenter(new T.Vector3());const dir=(view==='gearbox'?new T.Vector3(.12,.12,1):view==='front'?new T.Vector3(0,.015,1):view==='motor'?new T.Vector3(-.9,.32,-.8):new T.Vector3(.72,.29,1)).normalize();const right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),dir).normalize(),up=new T.Vector3().crossVectors(dir,right);const tan=Math.tan(camera.fov*Math.PI/360);let dist=0;for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const d=new T.Vector3(x,y,z).sub(centre),depth=d.dot(dir);dist=Math.max(dist,Math.abs(d.dot(right))/(tan*camera.aspect)+depth,Math.abs(d.dot(up))/tan+depth);}dist=Math.max(part>=0?.24:3.5,dist*1.13);const to=centre.clone().addScaledVector(dir,dist);camTween={from:camera.position.clone(),to,targetFrom:controls.target.clone(),targetTo:centre,start:performance.now(),duration:reduced?0:950};for(const [id,key] of [['view-3d','3d'],['view-front','front'],['view-back','motor']]){$(id).classList.toggle('active',key===view);$(id).setAttribute('aria-pressed',key===view);}}
function updateUI(force=false){const n=PARTS.filter(p=>drive.connected(p.index)).length;$('assembly-count').textContent=n+' / '+PARTS.length;$('assembly-progress').value=n;$('next-loose').hidden=n===PARTS.length||!ready;$('teardown-stage').hidden=drive.spread<.001||tour>=0;const phase=drive.spread<.25?0:drive.spread<.6?1:2;$('teardown-name').textContent=['01 / Release fasteners','02 / Open the assemblies','03 / Separate the mechanism'][phase];$('teardown-stage').querySelectorAll('i').forEach((el,i)=>el.classList.toggle('active',i<=phase));if(graphicsUnavailable){$('state-text').textContent='3D unavailable';$('rpm').textContent='—';$('status').classList.remove('running');$('status').classList.add('warning');$('system-note-title').textContent='3D graphics unavailable';$('system-note-copy').textContent='Open this page on a device with WebGL to explore the assembly. The presentation content is still available.';return;}const s=drive.status;const all=drive.assembled;const moving=drive.running||!drive.stationary;$('state-text').textContent=s==='Ready'?'Drive ready':s==='Disconnected'?'Drive interrupted':s;$('rpm').textContent=(drive.omega*60/(Math.PI*2)).toFixed(1)+' rpm out';$('input-rpm').textContent=(drive.omega*GEAR.ratio*60/(Math.PI*2)).toFixed(1);$('output-rpm').textContent=(drive.omega*60/(Math.PI*2)).toFixed(1);$('mechanism-data').hidden=!mechanismView;$('render-stats').textContent=renderFPS?renderFPS+' fps · '+renderer.domElement.width+' × '+renderer.domElement.height:PARTS.length+' components';$('status').classList.toggle('warning',!all&&!moving);$('status').classList.toggle('running',drive.running);$('motor').classList.toggle('running',moving);$('motor-icon').textContent=moving?'Ⅱ':'▶';$('motor-text').textContent=moving?'Stop motor':'Start motor';$('motor').setAttribute('aria-label',moving?'Stop motor':'Start motor');$('explode').textContent=drive.spreadTarget>.01?'▱ Reassemble all':'▱ Staged teardown';$('explode').setAttribute('aria-pressed',drive.spreadTarget>.01);if(document.activeElement!==$('spread'))$('spread').value=Math.round(drive.spreadTarget*100);
 for(let i=0;i<4;i++){const b=connectionRoot.querySelector(`[data-ring="${i}"]`),connected=drive.connected(i);b.classList.toggle('disconnected',!connected);b.querySelector('.connection-state span').textContent=connected?'Connected':'Disconnected';}
 const attached=drive.connected(selected);$('pull-value').textContent=attached?'Connected':(drive.pullTargets[selected]>0?drive.pullTargets[selected].toFixed(2)+' units':'Separated');if(document.activeElement!==$('part-pull'))$('part-pull').value=drive.pullTargets[selected];$('detach').innerHTML=attached?'Disconnect selected part <span>↗</span>':'Reconnect selected part <span>↙</span>';$('system-note-title').textContent=all?(drive.running?'One connected drive':'All connections ready'):moving?'Motor stopping':s==='Reassembling'?'Reconnecting the assembly':'Drive interrupted';$('system-note-copy').textContent=all?(drive.running?'The motor drives the cog through the 4:1 planetary gearbox.':'All '+PARTS.length+' components are assembled. The motor is ready.'):'Reconnect every required component before restarting the drive.';$('reconnect-all').hidden=all;
 if(tour>=0){$('tour-next').disabled=(tour===0||tour===5)?!drive.assembled:tour===2?drive.pulls[32]<2.09:tour===3?drive.spread<.999:false;}
}
function initAudio(){if(audioContext)return;audioContext=new (window.AudioContext||window.webkitAudioContext)();audioGain=audioContext.createGain();audioGain.gain.value=0;const filter=audioContext.createBiquadFilter();filter.type='lowpass';filter.frequency.value=470;audioOsc=audioContext.createOscillator();audioOsc.type='sawtooth';audioOsc.frequency.value=75;audioOsc.connect(filter);filter.connect(audioGain);audioGain.connect(audioContext.destination);audioOsc.start();}
$('sound').addEventListener('click',async()=>{try{initAudio();await audioContext.resume();sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',sound);}catch{toast('Sound is unavailable in this browser.');}});
const tourSteps=[['One connected machine','The original Coates Way artwork sits on a motor-driven mechanism. All 138 physical components must be connected.'],['Watch the gearbox','The motor drives the central sun. Four planets spin and orbit inside a fixed ring. The carrier output turns four times slower.'],['Inspect the clutch','The clutch hub and seven individual plates transmit rotation to the output. Withdrawing the hub opens the drive interlock. Every plate, bolt and spring has its own reference.'],['The teardown sequence','Covers withdraw, couplings release, and the gearset and information rings open in stages.'],['Inspect a planet','This planet gear is isolated. Its tooth profile and bearing detail are modelled in 3D. Find individual pins, input bearing balls and clutch plates in the parts register. Turn it with the side control.'],['Reconnect the system','The teardown reverses. Detached gears align to their drive phase before the system becomes ready.'],['Ready to explore','The complete machine is running again. Try Gearbox and Slow motion together to watch the reduction.']];
function showTour(){const t=tourSteps[tour];$('tour-bar').hidden=false;$('tour-step').textContent=`0${tour+1} / 07 · ${t[0]}`;$('tour-copy').textContent=t[1];$('tour-next').textContent=tour===6?'Finish tour ✓':'Next →';if(tour===0){mechanismView=false;reconnect();selectPart(0);}if(tour===1){mechanismView=true;$('gearbox').setAttribute('aria-pressed',true);updateVisibility();selectPart(24);fitCamera('gearbox');drive.start();}if(tour===2){selectPart(32);drive.requestPull(32,2.1);fitCamera('gearbox',32);}if(tour===3){mechanismView=false;$('gearbox').setAttribute('aria-pressed',false);updateVisibility();drive.requestSpread(1);fitCamera('3d',-1,{spread:1});}if(tour===4){selectPart(25);isolated=true;updateVisibility();$('isolate').textContent='Show all';$('isolate').setAttribute('aria-pressed',true);fitCamera('3d',25);setMode('turn');}if(tour===5)reconnect();if(tour===6)drive.start();}
function endTour(){tour=-1;$('tour-bar').hidden=true;$('tour').innerHTML='▷ <span>Guided tour</span>';}$('tour').addEventListener('click',()=>{if(tour>=0){endTour();return;}tour=0;$('tour').textContent='End tour';showTour();});$('tour-next').addEventListener('click',()=>{if(tour===6)endTour();else{tour++;showTour();}});$('tour-end').addEventListener('click',endTour);
async function capture(){
 if(!ready||capturing)return;
 capturing=true;$('capture').textContent='Rendering…';
 const oldAspect=camera.aspect,oldFov=camera.fov,oldRatio=renderer.getPixelRatio();
 const oldSize=renderer.getSize(new T.Vector2());
 try{
  const w=3840,h=2160;
  if(renderer.capabilities.maxTextureSize<w)throw Error('4K exceeds the device limit');
  // Render through the same tone-mapped canvas path as the live view.
  renderer.setPixelRatio(1);renderer.setSize(w,h,false);
  camera.aspect=w/h;
  if(camera.aspect<oldAspect)camera.fov=2*Math.atan(Math.tan(oldFov*Math.PI/360)*oldAspect/camera.aspect)*180/Math.PI;
  camera.updateProjectionMatrix();renderer.render(scene,camera);
  const cv=document.createElement('canvas');cv.width=w;cv.height=h;
  const ctx=cv.getContext('2d');ctx.drawImage(renderer.domElement,0,0);
  // Restore interactive rendering before asynchronous PNG encoding.
  camera.aspect=oldAspect;camera.fov=oldFov;camera.updateProjectionMatrix();
  renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);renderer.render(scene,camera);
  const blob=await new Promise(resolve=>cv.toBlob(resolve,'image/png'));
  if(!blob)throw Error('No image data');
  const url=URL.createObjectURL(blob),a=document.createElement('a');
  a.href=url;a.download='Coates_Way_3D_4K.png';a.click();
  setTimeout(()=>URL.revokeObjectURL(url),15000);toast('4K image captured: 3840 × 2160.');
 }catch(e){console.error(e);toast('The 4K capture could not complete on this device.');}
 finally{
  camera.aspect=oldAspect;camera.fov=oldFov;camera.updateProjectionMatrix();
  renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);
  capturing=false;lastFrame=performance.now();$('capture').textContent='↓ 4K capture';
 }
}
$('capture').addEventListener('click',capture);
function resize(){if(!renderer)return;const r=$('scene').getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}
function intersect(e){const r=$('canvas').getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(model.pickables,false).find(h=>{let a=h.object;while(a){if(!a.visible)return false;a=a.parent;}return true;});return hit||null;}
function project(world){const p=world.clone().project(camera),r=$('canvas').getBoundingClientRect();return{x:(p.x+1)*r.width/2+r.left,y:(1-p.y)*r.height/2+r.top,z:p.z};}
function input(){const canvas=$('canvas');canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2){const t=[...touches.values()];pinch={distance:Math.hypot(t[0].x-t[1].x,t[0].y-t[1].y),position:camera.position.clone()};drag=null;clickStart=null;controls.enabled=false;camTween=null;canvas.setPointerCapture(e.pointerId);return;}}if(e.button!==0)return;const hit=intersect(e);clickStart={x:e.clientX,y:e.clientY,id:e.pointerId,part:hit?.object.userData.part};if(mode==='orbit'||!hit)return;selectPart(hit.object.userData.part);controls.enabled=false;camTween=null;canvas.setPointerCapture(e.pointerId);if(!drive.stationary){drive.stop();toast('Let the motor stop before handling the parts.');return;}const centre=project(model.parts[selected].group.position),end=project(model.parts[selected].group.position.clone().add(new T.Vector3(0,0,1)));let dx=end.x-centre.x,dy=end.y-centre.y,den=dx*dx+dy*dy;if(den<70){dx=55;dy=0;den=3025;}drag={id:e.pointerId,part:selected,x:e.clientX,y:e.clientY,dx,dy,den,pull:drive.pullTargets[selected],cx:centre.x,cy:centre.y,lastAngle:Math.atan2(e.clientY-centre.y,e.clientX-centre.x)};},true);
 canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&touches.has(e.pointerId)){touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&touches.size===2){const t=[...touches.values()],d=Math.hypot(t[0].x-t[1].x,t[0].y-t[1].y);camera.position.copy(controls.target.clone().add(pinch.position.clone().sub(controls.target).multiplyScalar(pinch.distance/Math.max(1,d)).clampLength(.22,85)));return;}}if(drag&&e.pointerId===drag.id){if(mode==='pull'){const delta=((e.clientX-drag.x)*drag.dx+(e.clientY-drag.y)*drag.dy)/drag.den;drive.requestPull(drag.part,drag.pull+delta);$('part-pull').value=drive.pullTargets[drag.part];}else{const angle=Math.atan2(e.clientY-drag.cy,e.clientX-drag.cx);let diff=drag.lastAngle-angle;while(diff>Math.PI)diff-=2*Math.PI;while(diff<-Math.PI)diff+=2*Math.PI;drive.turn(drag.part,diff);drag.lastAngle=angle;$('part-turn').value=drive.turns[drag.part]*180/Math.PI;$('turn-value').textContent=Math.round(drive.turns[drag.part]*180/Math.PI)+'°';}labelUntil=performance.now()+4000;return;}if(e.pointerType==='touch')return;const hit=intersect(e);if(hit){const r=$('scene').getBoundingClientRect();$('tooltip').textContent=PARTS[hit.object.userData.part].ref+' · '+PARTS[hit.object.userData.part].name;$('tooltip').style.left=Math.max(8,Math.min(e.clientX-r.left+14,r.width-200))+'px';$('tooltip').style.top=Math.min(e.clientY-r.top+15,r.height-50)+'px';$('tooltip').style.opacity=1;canvas.style.cursor=mode==='orbit'?'grab':'ew-resize';}else{$('tooltip').style.opacity=0;canvas.style.cursor='grab';}});
 function finish(e,cancel=false){touches.delete(e.pointerId);if(pinch){pinch=null;controls.enabled=true;clickStart=null;drag=null;}if(clickStart&&clickStart.id===e.pointerId&&!cancel&&Math.hypot(e.clientX-clickStart.x,e.clientY-clickStart.y)<5&&clickStart.part!==undefined)selectPart(clickStart.part);clickStart=null;drag=null;controls.enabled=true;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}
 canvas.addEventListener('pointerup',e=>finish(e));canvas.addEventListener('pointercancel',e=>finish(e,true));canvas.addEventListener('lostpointercapture',e=>{if(drag||pinch)finish(e,true)});canvas.addEventListener('pointerleave',()=>{$('tooltip').style.opacity=0;});canvas.addEventListener('keydown',e=>{if(![' ','e','E','r','R','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0'].includes(e.key))return;e.preventDefault();if(e.key===' ')toggleMotor();else if(e.key.toLowerCase()==='e')changeSpread(drive.spreadTarget>0?0:1);else if(e.key.toLowerCase()==='r')reconnect();else if(e.key==='0')reset();else if(e.key==='+'||e.key==='=')zoom(.85);else if(e.key==='-')zoom(1.18);else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){drive.stop();drive.turn(selected,e.key==='ArrowLeft'?.12:-.12);}else drive.requestPull(selected,drive.pullTargets[selected]+(e.key==='ArrowUp'?.2:-.2));});}
async function initialise(){try{
 renderer=new T.WebGLRenderer({canvas:$('canvas'),antialias:true,alpha:false,powerPreference:'default'});renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.setClearColor(0x16191b,1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 scene=new T.Scene();scene.background=new T.Color(0x16191b);scene.fog=new T.Fog(0x16191b,48,120);camera=new T.PerspectiveCamera(34,1,.025,180);camera.position.set(13,7,20);controls=new OrbitControls(camera,$('canvas'));controls.enableDamping=true;controls.dampingFactor=.08;controls.enablePan=true;controls.minDistance=.2;controls.maxDistance=85;controls.maxPolarAngle=Math.PI*.82;controls.rotateSpeed=.65;controls.zoomSpeed=.7;controls.addEventListener('start',()=>{camTween=null;});
 $('loading').querySelector('span').textContent='Loading the model and studio lighting…';
 const [loaded,env]=await Promise.all([buildModel(),environment(renderer)]);model=loaded;scene.environment=env;scene.environmentIntensity=.85;
 for(const texture of model.textures)if(texture)texture.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);
 scene.add(new T.HemisphereLight(0xdce8ef,0x403126,.6));keyLight=new T.DirectionalLight(0xfff4e8,3.1);keyLight.position.set(5,10,13);keyLight.castShadow=true;keyLight.shadow.mapSize.set(1024,1024);keyLight.shadow.camera.left=-13;keyLight.shadow.camera.right=13;keyLight.shadow.camera.top=13;keyLight.shadow.camera.bottom=-13;keyLight.shadow.camera.far=55;keyLight.shadow.normalBias=.025;keyLight.shadow.bias=-.0002;scene.add(keyLight);const fill=new T.DirectionalLight(0xbcd4ef,1.2);fill.position.set(-9,5,4);scene.add(fill);const rim=new T.DirectionalLight(0xffa46c,1.7);rim.position.set(4,6,-10);scene.add(rim);
 const floor=new T.Mesh(new T.PlaneGeometry(220,220),new T.MeshStandardMaterial({color:0x20262b,metalness:.32,roughness:.48}));floor.rotation.x=-Math.PI/2;floor.position.y=-4.63;floor.receiveShadow=true;scene.add(floor);
 scene.add(model.root);ready=true;applyTransforms();resize();/* hero mode (?hero=1): the exhibit alone on its studio floor for a captured loop — the interface hidden, the frame loop
   paused, and a small hook for the capture script to step the drive, orbit the camera and render one frame at a time */
if(new URLSearchParams(location.search).get('hero')==='1'){document.body.classList.add('hero');capturing=true;const heroResize=()=>{renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();};heroResize();const spreadEl=$('spread');window.__mech={drive,T,resize:heroResize,get camera(){return camera},get controls(){return controls},get renderer(){return renderer},setSpread:v=>{spreadEl.value=String(v);spreadEl.dispatchEvent(new Event('input'));},step:(dt)=>{drive.advance(dt);applyTransforms();if(controls.autoRotate){controls.update(dt);}renderer.render(scene,camera);},fit:(v,o)=>fitCamera(v,-1,o||{}),fitNow:(v,o)=>{fitCamera(v,-1,o||{});if(camTween){camera.position.copy(camTween.to);controls.target.copy(camTween.targetTo);camTween=null;}controls.update&&controls.update();},get tween(){return camTween},frameNow:()=>renderer.domElement.toDataURL('image/jpeg',.92)};}new ResizeObserver(()=>{const old=camera.aspect;resize();if(Math.abs(old-camera.aspect)>.2)fitCamera(currentView,isolated?selected:-1);}).observe($('scene'));fitCamera('3d');input();selectPart(0);$('loading').hidden=true;lastFrame=performance.now();renderer.setAnimationLoop(frame);$('canvas').addEventListener('webglcontextlost',e=>{e.preventDefault();drive.stop();showFallback('The graphics connection was lost. Reload to restore the 3D view.');});
 }catch(e){console.error('3D initialisation failed',e);showFallback();}}
function showFallback(message){document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=true);graphicsUnavailable=true;ready=false;drive.stop();renderer?.setAnimationLoop(null);if(audioGain)audioGain.gain.setTargetAtTime(0,audioContext.currentTime,.05);$('loading').hidden=true;$('canvas').hidden=true;$('fallback').hidden=false;if(message)$('fallback').querySelector('p').textContent=message;for(const id of ['motor','explode','spread','part-pull','part-turn','detach','focus-part','isolate','cutaway','capture','view-3d','view-front','view-back','fit','zoom-in','zoom-out','tour','sound','speed','quality','reconnect-all','flow','slow','gearbox'])$(id).disabled=true;updateUI(true);}
function frame(now){if(!ready||capturing)return;if(now-lastRender<(quality==='laptop'?1000/30:1000/60)-.6)return;lastRender=now;frameCount++;if(now-fpsAt>1000){renderFPS=Math.round(frameCount*1000/(now-fpsAt));frameCount=0;fpsAt=now;}const dt=Math.min((now-lastFrame)/1000,.1);lastFrame=now;if(document.hidden)return;drive.advance(dt*(slow?.15:1));applyTransforms();if(isolated&&followAnchor){const next=partPosition(model.parts[selected]),delta=next.clone().sub(followAnchor);camera.position.add(delta);controls.target.add(delta);if(camTween)for(const k of ['from','to','targetFrom','targetTo'])camTween[k].add(delta);followAnchor.copy(next);}if(camTween){const t=Math.min(1,(now-camTween.start)/Math.max(1,camTween.duration)),e=1-Math.pow(1-t,3);camera.position.lerpVectors(camTween.from,camTween.to,e);controls.target.lerpVectors(camTween.targetFrom,camTween.targetTo,e);if(t===1)camTween=null;}controls.update();if(now< labelUntil){const p=model.parts[selected],pos=p.group.position.clone().add(new T.Vector3(0,p.radius*.8,.2));const v=project(pos),r=$('scene').getBoundingClientRect();$('selected-label').hidden=v.z>1||v.x<r.left+50||v.x>r.right-50||v.y<r.top+90||v.y>r.bottom-50;if(!$('selected-label').hidden){$('selected-label').style.left=(v.x-r.left)+'px';$('selected-label').style.top=(v.y-r.top)+'px';$('selected-label').querySelector('b').textContent=p.ref+' · '+p.name;}}else $('selected-label').hidden=true;
 if(audioContext&&audioGain){audioGain.gain.setTargetAtTime(sound?Math.min(.024,drive.omega*.025):0,audioContext.currentTime,.08);audioOsc.frequency.setTargetAtTime(65+drive.omega*GEAR.ratio*35,audioContext.currentTime,.08);}if(now-uiAt>90){updateUI();uiAt=now;}renderer.render(scene,camera);}
document.addEventListener('visibilitychange',()=>{lastFrame=performance.now();drive.accumulator=0;if(document.hidden&&audioGain)audioGain.gain.setTargetAtTime(0,audioContext.currentTime,.05);});
initPartsRegister({drive,selectPart,graphicsReady:()=>ready});
$('part-parent').addEventListener('click',()=>{const parent=PARTS[selected].mount;if(parent!==undefined)selectPart(parent,{focus:true});});
$('next-loose').addEventListener('click',()=>{const candidates=PARTS.filter(p=>!drive.connected(p.index));const next=candidates.find(p=>p.index>selected)||candidates[0];if(next)selectPart(next.index,{focus:true});});
$('assembly-progress').max=PARTS.length;
selectPart(0);initialise();
