// Author: Andrew Fisher. Real phone controls -> production PDF producers. GET-only; mocked platform share only.
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const R=process.env.REPO||path.resolve(__dirname,'..'),O=process.env.OUT;if(!O)throw Error('Set private OUT');
const {installWriteGuard,ready840,nativeSnapshot}=require(R+'/v8.40_today_work_progress_LIVE/test_today840.cjs'),{open}=require(R+'/toolchain/harness/open_page.js');const guard=installWriteGuard();
(async()=>{let s;try{
 fs.mkdirSync(O,{recursive:true});s=await open({pageFile:process.env.PAGE,hash:'#today',W:390,H:900,mobile:true,dpr:2});const p=s.page;await ready840(p);const before=await nativeSnapshot(p);
 await p.evaluate(()=>{go('timeline');window.__ep860UiShares=[];Object.defineProperty(navigator,'canShare',{configurable:true,value:o=>!!o.files?.length});Object.defineProperty(navigator,'share',{configurable:true,value:async o=>window.__ep860UiShares.push({title:o.title,names:o.files.map(f=>f.name),types:o.files.map(f=>f.type),sizes:o.files.map(f=>f.size)})});});await p.waitForTimeout(1000);
 await p.locator('[data-ep860-email="1"]').click();await p.waitForFunction(()=>EP860.file&&document.querySelector('[data-ep860-share]'),null,{timeout:120000});const load=await p.evaluate(()=>({name:EP860.file.name,pages:EP860.file.pages,size:EP860.file.size,title:document.querySelector('#ep860-title').textContent,base64:null}));assert.equal(load.pages,1);assert(load.name.includes('Load-1_'));assert.equal(load.title,'Run sheet - Load 1');await p.screenshot({path:O+'/real-load-email-phone.png'});
 await p.locator('[data-ep860-share]').click();await p.waitForFunction(()=>window.__ep860UiShares.length===1);const share=await p.evaluate(()=>window.__ep860UiShares[0]);assert.deepEqual(share.names,[load.name]);assert.deepEqual(share.types,['application/pdf']);assert.deepEqual(share.sizes,[load.size]);await p.keyboard.press('Escape');assert.equal(await p.locator('#ep860-dialog').count(),0);
 await p.locator('[data-ep860-inventory]').first().click();await p.waitForFunction(()=>EP860.file&&document.querySelector('[data-ep860-share]'),null,{timeout:120000});const inv=await p.evaluate(()=>({name:EP860.file.name,pages:EP860.file.pages,size:EP860.file.size,title:document.querySelector('#ep860-title').textContent,model:holdAssets(epInventory860).summary}));assert(inv.name.includes('Event_Portables_Inventory_'));assert.equal(inv.title,'Inventory print');assert(inv.pages>=1);await p.screenshot({path:O+'/real-inventory-phone.png'});await p.keyboard.press('Escape');
 const after=await nativeSnapshot(p);assert.deepEqual(after.collections,before.collections);assert.equal(s.errors.length,0);assert(!guard.nonGetSeen.some(x=>x.operational));const intentional=e=>e.url==='https://tile.googleapis.com/v1/createSession'&&/ERR_BLOCKED_BY_CLIENT/.test(e.text)&&guard.blocked.some(b=>b.method==='POST'&&b.url===e.url);assert.equal(guard.consoleErrors.filter(e=>!intentional(e)).length,0);
 fs.writeFileSync(O+'/real-controls.json',JSON.stringify({author:'Andrew Fisher',at:new Date().toISOString(),load,inventory:inv,share,recordsPreserved:true,operationalWrites:0,unexpectedConsoleErrors:0,intentionalMapBlocks:guard.consoleErrors.filter(intentional),blockedRequests:guard.blocked},null,2));console.log('PASS real phone Email load1 and Inventory buttons -> native PDF production; actual File share payload; no record writes');
}finally{if(s)await s.browser.close();await guard.closeAll();}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
