// Author: Andrew Fisher. Native presentation, fold memory, scroll and record preservation; no live writes.
const fs=require('fs'),{open}=require('../../toolchain/harness/open_page');
(async()=>{let s;try{const mob=!!process.env.MOB;s=await open({pageFile:process.env.PAGE,W:mob?390:1600,H:mob?844:1000,mobile:mob,dpr:mob?2:1});const p=s.page,R=[];const ok=(n,v)=>R.push({name:n,pass:!!v});await p.waitForFunction(()=>typeof today876Tidy==='function'&&SYNC.status==='live'&&todayWorkHealth840().ready);await p.evaluate(()=>go('today'));await p.waitForTimeout(400);
const initial=await p.evaluate(()=>{window.__before876=JSON.stringify([S,moneySummary(),fh866Model()]);const pane=document.getElementById('pane-today'),groups=[...pane.querySelectorAll('[data-tw848-group-fold]')],rect=pane.getBoundingClientRect();return {groups:groups.length,allOpen:groups.every(d=>d.open),detailsClosed:[...pane.querySelectorAll('[data-tw841-group-card]')].every(d=>!d.open),rail:rect.width<=1760&&rect.width<=innerWidth,columns:getComputedStyle(pane.querySelector('.tw840-grid')).gridTemplateColumns.split(' ').length,contacts:getComputedStyle(pane.querySelector('.tm-list')).gridTemplateColumns.split(' ').length,toolbar:!!pane.querySelector('.acts793 .hacts'),unique:new Set([...pane.querySelectorAll('[id]')].map(x=>x.id)).size===pane.querySelectorAll('[id]').length};});ok('all seven groups present',initial.groups===7);ok('all groups initially open',initial.allOpen);ok('supporting details initially folded',initial.detailsClosed);ok('bounded Today rail',initial.rail);ok('balanced responsive progress grid',initial.columns===(mob?1:2));ok('contacts use available space',initial.contacts===(mob?1:3));ok('native Today controls retained',initial.toolbar);ok('no duplicate identifiers',initial.unique);
const fold=p.locator('[data-tw848-group-fold]').first();await fold.locator(':scope > summary').click();await p.waitForTimeout(200);ok('manual collapse works',!await fold.evaluate(d=>d.open));await p.evaluate(()=>renderToday());await p.waitForTimeout(300);ok('manual collapse survives redraw',!await p.locator('[data-tw848-group-fold]').first().evaluate(d=>d.open));ok('other groups remain open',await p.locator('[data-tw848-group-fold][open]').count()===6);await p.locator('[data-tw848-group-fold]').first().locator(':scope > summary').click();await p.waitForTimeout(200);
const first=p.locator('[data-tw840-area]').first();await first.scrollIntoViewIfNeeded();await p.waitForTimeout(350);await p.waitForFunction(()=>TodayWork840.report().running&&!!TodayWork840.report().runningInstrument,null,{timeout:5000}).catch(()=>{});ok('native automatic instrument animation',await p.evaluate(()=>TodayWork840.report().mode==='auto'&&!!TodayWork840.report().runningInstrument));
const before=await p.evaluate(()=>document.querySelector('main').scrollTop);await p.evaluate(()=>renderToday());await p.waitForTimeout(350);ok('redraw retains scroll position',Math.abs(await p.evaluate(()=>document.querySelector('main').scrollTop)-before)<4);ok('redraw does not change data or money',await p.evaluate(()=>window.__before876===JSON.stringify([S,moneySummary(),fh866Model()])));ok('no page-wide horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
if(process.env.OUT){fs.mkdirSync(process.env.OUT,{recursive:true});await p.locator('[data-tw840-area]').first().scrollIntoViewIfNeeded();await p.screenshot({path:process.env.OUT+'/card-'+(mob?'phone':'desktop')+'.png'});await p.evaluate(()=>document.querySelector('main').scrollTop=0);await p.screenshot({path:process.env.OUT+'/today-'+(mob?'phone':'desktop')+'.png'});}
ok('no runtime errors',s.errors.length===0);ok('no attempted live writes',s.counts.blocked===0);R.forEach(r=>console.log((r.pass?'PASS ':'FAIL ')+r.name));console.log((mob?'phone':'desktop')+': '+R.filter(r=>r.pass).length+'/'+R.length);if(R.some(r=>!r.pass))process.exitCode=1;
}finally{if(s)await s.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
