# Author: Andrew Fisher
from pathlib import Path
import sys
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / 'toolchain'))
from rep import rep
p = Path(sys.argv[1]); raw = p.read_bytes(); s = raw.decode('utf-8-sig')
assert 'function physicalCountAssets963(' not in s, 'v9.63 already applied'
assert " · v9.62'; /* v8.19" in s and 'function toiletItem962(' in s, 'Requires v9.62 base'
def change(old, new, why):
 global s
 s = rep(s, old, new, why, str(p))
change('function inventory(){', (HERE/'counts963.js').read_text()+'\nfunction inventory(){', 'shared source-linked physical count projection')
change('return rows.get(t); };\n allAssets().filter(a => !a._cancelled && !a.relocation && !movedAway(a.key)).forEach(a => {', 'return rows.get(t); };\n physicalCountAssets963(allAssets()).assets.filter(a => !a._cancelled && !a.relocation && !movedAway(a.key)).forEach(a => {', 'Inventory counts each proven source machine once')
change('function plantGroups(){\n const by = new Map();\n allAssets().forEach(a => {', 'function plantGroups(){\n const by = new Map();\n physicalCountAssets963(allAssets()).assets.forEach(a => {', 'Equipment lists use the same physical references')
change('title="every thing on the job${esc(offWords(allAssets()))}">All ${esc(fmtNum(tot(allAssets())))}', 'title="physical equipment references${esc(offWords(physicalCountAssets963(allAssets()).assets))}">All ${esc(fmtNum(tot(physicalCountAssets963(allAssets()).assets)))}', 'Equipment all filter matches its listed references')
change(' link. Open any reference here or on the Map to fill it in.</p>', ' link. Open any reference here or on the Map to fill it in.</p>\n ${physicalAliasHtml963()}', 'alias histories remain accessible in the reference disclosure')
change('  const X = dsnState(day), areas = workAreas || todayWorkMetrics840(day);', '  const X = dsnState(day), areas = workAreas || todayWorkMetrics840(day);\n  const physical963 = physicalCountAssets963(X.rows.map(r => r.a));\n  const alias963 = new Set(physical963.aliases.map(a => a.ref));\n  result.equipment.sourceAliases963 = physical963.aliases;\n  result.equipment.sourceAliasReviews963 = physical963.pending;', 'Today shares canonical physical source matching')
change('  for (const row of X.rows) {\n    if (row.a._cancelled) continue;', '  for (const row of X.rows) {\n    if (row.a._cancelled || alias963.has(row.a.key)) continue;', 'Today types do not repeat source-linked machines')
change("  result.equipment.notes.push('VMS has its own card.", "  physical963.aliases.forEach(a => result.equipment.notes.push(a.ref + ' is the source-linked reference for ' + a.source + ' (' + a.item + '). Counted once under ' + a.source + '; both histories are linked in Equipment.'));\n  physical963.pending.forEach(a => result.equipment.issues.push(a.ref + ' → ' + a.source + ': ' + a.reason + ' Both references remain in the counts pending reconciliation.'));\n  result.equipment.notes.push('VMS has its own card.", 'show physical alias treatment and unresolved matches')
change('  const represented = ids.flatMap(id => result[id].groups.flatMap(g => g.keys.concat(g.excluded.map(r => r.key))));', '  const represented = ids.flatMap(id => result[id].groups.flatMap(g => g.keys.concat(g.excluded.map(r => r.key)))).concat(physical963.aliases.map(a => a.ref));', 'source coverage retains aliases without counting additional machines')
change('    sourceMoneyIds, mappedMoneyIds};', '    sourceMoneyIds, mappedMoneyIds, sourceAliases963: physical963.aliases};', 'coverage records exact canonical source relationships')
change("    const caption = area.loading ? 'Loading record' : complete ? 'Finished · confirmed complete' : number(pct) ? summary.pctLabel || 'Confirmed complete' : 'Percentage unconfirmed';", "    const caption = area.loading ? 'Loading record' : area.id === 'equipment' ? 'Forklifts & access · ' + (number(pct) ? 'confirmed complete' : 'percentage unconfirmed') : complete ? 'Finished · confirmed complete' : number(pct) ? summary.pctLabel || 'Confirmed complete' : 'Percentage unconfirmed';", 'Equipment instrument names its counted scope')
change("digits(pct, area.id, summary.scopeProvisional960 ? 'complete against provisional schedule scope' : 'confirmed complete', summary.pctKind)", "digits(pct, area.id, area.id === 'equipment' ? 'forklifts and access confirmed complete' : summary.scopeProvisional960 ? 'complete against provisional schedule scope' : 'confirmed complete', summary.pctKind)", 'accessible equipment scope')
change("vms:'VMS boards',equipment:'Equipment'};", "vms:'VMS boards',equipment:'Forklifts & access'};", 'category index names actual equipment scope')
change(" const BASIS='Whole job is the average of the seven group readings below, each counting equally (one seventh each): Buildings, Toilets, Fencing, Generators, Lighting, VMS boards and Equipment. The equipment groups use confirmed completion; Fencing uses recorded Build + Event programme metres. Metres and unit counts are never added together. When any group shows a minimum (≥), the whole job is a minimum too. One red light for each 20% reached; all five turn green only at a confirmed 100%. This is a progress reading, not a handover or financial sign-off.';", " const BASIS='Tracked category progress is an index of seven readings, each counting equally (one seventh each): Buildings, Toilets, Fencing, Generators, Lighting, VMS boards and Forklifts & access. Furniture, water-filled barriers, track mat and other equipment retain their separate type details; they are outside this index. The equipment readings use confirmed completion; Fencing uses recorded Build + Event programme metres. Metres and unit counts are never added together. When any reading shows a minimum (≥), the index is a minimum too. One red light for each 20% reached; all five turn green only at a confirmed 100%. This index does not establish whole-job completion, physical handover or financial sign-off.';", 'explain bounded category index')
change("whole.text+'% whole-job progress. '", "whole.text+'% tracked category progress. '", 'index accessible name')
change("'Whole-job progress unavailable.'", "'Tracked category progress unavailable.'", 'missing index accessible name')
change("+'seven groups counted equally';", "+'seven category index · equal weighting';", 'visible index basis')
change('<h3 class="w885-title">Whole job</h3>', '<h3 class="w885-title">Tracked category progress</h3>', 'avoid whole-job completion claim')
change('How the whole-job figure is worked out', 'How the category index is worked out', 'index disclosure label')
change('const k=Math.min(1,(now-start)/(COUNT*1000)),stop=k>=1||still()||paused;', 'const k=Math.max(0,Math.min(1,(now-start)/(COUNT*1000))),stop=k>=1||still()||paused;', 'first animation frame cannot display a negative percentage')
change("Equipment groups use confirmed completion; Fencing uses recorded Build + Event programme work metres,", "Equipment here means Forklifts & access; furniture, water-filled barriers, track mat and other equipment remain outside this index. Equipment groups use confirmed completion; Fencing uses recorded Build + Event programme work metres,", 'model carries bounded scope')
change(" · v9.62'; /* v8.19", " · v9.63'; /* v8.19", 'footer')
p.write_bytes((b'\xef\xbb\xbf' if raw.startswith(b'\xef\xbb\xbf') else b'') + s.encode())
