// Author: Andrew Fisher. Source-linked physical counts; no record or network writes.
'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const copy=x=>JSON.parse(JSON.stringify(x)),checks=[];
const check=(name,fn)=>{fn();checks.push(name);};
const snap=JSON.parse(fs.readFileSync(process.argv[2]||'/workspace/private-fencing958/cross-tab/snapshot.json','utf8'));
const ref=new Map(snap.refs.map(r=>[r.key,r]));
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'counts963.js'),'utf8'),ctx);
const options={linesOf:a=>a.testLines||ref.get(a.key)?.chargeLines||[],movedAway:()=>false,identitiesOf:a=>(a.asset_numbers||[]).map(x=>'asset:'+x)};
const project=assets=>copy(ctx.physicalCountAssets963(assets,options));
const original=JSON.stringify(snap),before=copy(snap.assets),m=project(before);
check('exactly two explicit source aliases',()=>assert.deepEqual(m.aliases.map(a=>[a.ref,a.source]),[['FL01','T0003'],['FL02','T0004']]));
check('source records and snapshots stay unchanged',()=>{assert.equal(JSON.stringify(snap),original);assert.deepEqual(before,snap.assets);});
check('canonical physical list removes exactly two alias references',()=>assert.deepEqual(m.assets.map(a=>a.key),before.filter(a=>!['FL01','FL02'].includes(a.key)).map(a=>a.key)));
check('full schedule source evidence retained',()=>{for(const a of m.aliases){assert.equal(a.evidence.task_id,a.source);assert.equal(a.evidence.sheet,'Week 6');assert.equal(a.evidence.date,'2026-09-11');assert.equal(a.evidence.quantity,1);assert.equal(a.evidence.location,'Phillip Park');}});
check('no pending source aliases in native record',()=>assert.equal(m.pending.length,0));
check('subhired canonical forklift keeps rental identity and ownership',()=>assert.deepEqual(m.assets.find(a=>a.key==='T0003'),before.find(a=>a.key==='T0003')));
check('asked 2.5t is preserved when actual supplied is 3t',()=>assert.equal(m.assets.find(a=>a.key==='T0004').charge_lines[0].item,'Forklift 2.5T'));
const pair=()=>copy(before.filter(a=>['FL02','T0004'].includes(a.key)));
const guard=(name,mutate)=>check(name,()=>{const xs=pair();mutate(xs);const result=project(xs);assert.equal(result.aliases.length,0);assert.equal(result.assets.length,xs.length);});
guard('missing source is retained',xs=>xs.splice(xs.findIndex(a=>a.key==='T0004'),1));
guard('duplicate source key is retained',xs=>xs.push(copy(xs.find(a=>a.key==='T0004'))));
guard('duplicate alias key is retained',xs=>xs.push(copy(xs.find(a=>a.key==='FL02'))));
guard('two competing aliases are retained',xs=>xs.push({...copy(xs.find(a=>a.key==='FL02')),key:'FL03'}));
guard('cancelled parent is not canonicalised',xs=>xs.find(a=>a.key==='T0004')._cancelled=true);
guard('cancelled alias is not hidden as an active alias',xs=>xs.find(a=>a.key==='FL02')._cancelled=true);
guard('source chains are not canonicalised',xs=>xs.find(a=>a.key==='T0004').source_row='T9999');
guard('self-reference is not canonicalised',xs=>xs.find(a=>a.key==='FL02').source_row='FL02');
guard('changed source ownership type is retained',xs=>xs.find(a=>a.key==='T0004').origin='drawing');
guard('independently scheduled alias is retained',xs=>xs.find(a=>a.key==='FL02').events=[{date:'2026-09-11'}]);
guard('changed item is retained',xs=>xs.find(a=>a.key==='FL02').testLines=[{item:'Forklift 3T',quantity:1}]);
guard('changed quantity is retained',xs=>xs.find(a=>a.key==='FL02').testLines=[{item:'Forklift 2.5T',quantity:2}]);
guard('unknown quantity is retained',xs=>xs.find(a=>a.key==='FL02').testLines=[{item:'Forklift 2.5T',quantity:null}]);
guard('mixed equipment is retained',xs=>xs.find(a=>a.key==='FL02').testLines=[{item:'Forklift 2.5T',quantity:1},{item:'Tyne extensions',quantity:1}]);
guard('changed location is retained',xs=>xs.find(a=>a.key==='FL02').locations=['Pit Lane']);
guard('changed schedule date is retained',xs=>xs.find(a=>a.key==='FL02').first_date='2026-09-12');
guard('source event missing is retained',xs=>xs.find(a=>a.key==='T0004').events=[]);
guard('duplicate source placement is retained',xs=>{const p=xs.find(a=>a.key==='T0004');p.events.push(copy(p.events[0]));});
guard('source event quantity conflicts are retained',xs=>xs.find(a=>a.key==='T0004').events[0].quantity_raw=2);
guard('new alias asset identity is retained',xs=>xs.find(a=>a.key==='FL02').asset_numbers=['DIFFERENT']);
guard('moved alias is retained',xs=>xs.find(a=>a.key==='FL02')._movedTo='FL05');
guard('moved parent is retained',xs=>xs.find(a=>a.key==='T0004')._locationMoved='Pit Lane');
guard('follow-up alias is retained',xs=>xs.find(a=>a.key==='FL02').rest_of='T0004');
check('identical unlinked machine remains separately counted',()=>{const xs=pair(),other={...copy(xs.find(a=>a.key==='FL02')),key:'FL03'};delete other.source_row;xs.push(other);assert.equal(project(xs).assets.length,2);assert.ok(project(xs).assets.some(a=>a.key==='FL03'));});
check('source changes are re-evaluated without stale caching',()=>{const xs=pair();assert.equal(project(xs).aliases.length,1);xs.find(a=>a.key==='FL02').asset_numbers=['NEW'];assert.equal(project(xs).aliases.length,0);});
check('source reconciliation does not replace objects',()=>{const xs=pair(),r=ctx.physicalCountAssets963(xs,options);assert.strictEqual(r.assets[0],xs.find(a=>a.key==='T0004'));});
check('unknown supplier identity on alias blocks reconciliation',()=>{const xs=pair(),r=ctx.physicalCountAssets963(xs,{...options,identitiesOf:a=>a.key==='FL02'?['supplier:new:1']:['asset:1197839']});assert.equal(r.aliases.length,0);});
ctx.esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
check('both histories remain actionable',()=>{const html=ctx.physicalAliasHtml963(m);for(const key of ['FL01','FL02','T0003','T0004'])assert.match(html,new RegExp('data-open="'+key+'"'));assert.match(html,/Counted once under T0003/);});
check('pending source evidence is explicitly qualified',()=>{const html=ctx.physicalAliasHtml963({aliases:[],pending:[{ref:'FL01',source:'T0003',reason:'Source changed.'}]});assert.match(html,/Both references remain in the counts pending reconciliation/);});
console.log(JSON.stringify({author:'Andrew Fisher',pass:true,checks:checks.length,names:checks,aliases:m.aliases},null,2));
