// Author: Andrew Fisher. Frozen native-state replay; all non-GET requests blocked.
'use strict';
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),tool=path.join(base,'toolchain/harness'),hp=path.join(tool,'open_page.js');
const snapshot=JSON.parse(fs.readFileSync(process.env.SNAPSHOT||'/workspace/private-fencing958/cross-tab/snapshot.json'));
const prior=JSON.parse(fs.readFileSync(process.env.PRIOR||'/workspace/private-fencing958/results962.json'));
const frozen=JSON.parse(fs.readFileSync(process.env.NATIVE_STATE||'/workspace/private-fencing958/cross-tab/native-api-state.json'));
const fetcher=require(path.join(tool,'curlfetch')),get=fetcher.curlFetch;
fetcher.curlFetch=async(url,headers,method,body)=>{assert.equal(method,'GET');const u=new URL(url);if(['/api/state','/api/version'].includes(u.pathname))return{status:200,headers:{'content-type':'application/json'},body:Buffer.from(JSON.stringify(u.pathname==='/api/state'?frozen:{version:frozen.version,updated:frozen.updated,level:'view'}))};return get(url,headers,method,body);};
const m=new Module(hp,module);m.filename=hp;m.paths=Module._nodeModulePaths(path.dirname(hp));m._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;'),hp);
(async()=>{const h=await m.exports.open({pageFile:process.env.PAGE||'/workspace/private-fencing958/candidate963.html',W:390,H:844,hash:'#today'});try{
 await h.page.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:150000});
 const out=await h.page.evaluate(()=>holdAssets(()=>{const before=JSON.stringify(S),day=todayIso(),areas=todayWorkMetrics840(day),groups=todayGroupDetails841(day,areas),summary=todayWorkSummary848(day,areas,groups,todayFencingSummary848(day)),types=todayTypeMetrics843(day,groups,summary),physical=physicalCountAssets963(allAssets());return JSON.parse(JSON.stringify({day,record:S,recordUnchanged:before===JSON.stringify(S),physical:{aliases:physical.aliases,pending:physical.pending,keys:physical.assets.map(a=>a.key)},groups,summary,types,inventory:inventory(),plantGroups:plantGroups().map(([g,as])=>[g,as.map(a=>a.key)]),index:progress881Model(day),main:areas.find(a=>a.id==='equipment'),identities:physical.aliases.map(a=>({alias:a.ref,source:a.source,aliasUnits:unitsOf(a.ref),sourceUnits:unitsOf(a.source),aliasSub:subOf(a.ref),sourceSub:subOf(a.source)}))},(k,v)=>v instanceof Map?Object.fromEntries(v):v));}));
 assert(out.recordUnchanged);assert.deepEqual(out.record,snapshot.record);assert.deepEqual(out.physical.aliases.map(a=>[a.ref,a.source]),[['FL01','T0003'],['FL02','T0004']]);assert.equal(out.physical.pending.length,0);
 assert(out.groups.__coverage.allRepresented);assert.equal(out.groups.__coverage.sourceAliases963.length,2);
 assert.deepEqual(out.groups.equipment.money,snapshot.models.groups.equipment.money);assert.deepEqual(out.groups.equipment.comparisons,snapshot.models.groups.equipment.comparisons);
 assert(!out.groups.equipment.groups.some(g=>g.keys.some(k=>['FL01','FL02'].includes(k))));assert(!out.plantGroups.flatMap(([,ks])=>ks).some(k=>['FL01','FL02'].includes(k)));
 assert.deepEqual([out.summary.byId.equipment.done,out.summary.byId.equipment.total,out.summary.byId.equipment.pct],[6,6,100]);
 const sum=(i,k)=>i.list.reduce((n,r)=>n+(r[k]||0),0),delta={asked:sum(out.inventory,'asked')-sum(prior.inventory,'asked'),on:sum(out.inventory,'on')-sum(prior.inventory,'on')};assert.deepEqual(delta,{asked:-2,on:-2});
 assert.deepEqual(out.inventory.cos,prior.inventory.cos);assert(!out.inventory.list.some(r=>r.refs.FL01||r.refs.FL02));
 const paired=out.inventory.list.filter(r=>r.refs.T0003||r.refs.T0004).map(r=>({item:r.item,asked:r.asked,on:r.on,coates:r.coates,sub:r.sub,nonum:r.nonum,refs:r.refs}));
 await h.page.waitForTimeout(2200);
 const todayText=await h.page.locator('#pane-today').innerText();assert.match(todayText,/Tracked category progress/i);assert.match(todayText,/Forklifts & access/);assert.equal(out.index.rows.find(r=>r.id==='equipment').name,'Forklifts & access');
 await h.page.locator('#where885').scrollIntoViewIfNeeded();
 const displayed=await h.page.locator('[data-w885-pct]').first().innerText();assert(Number(displayed.replaceAll(',',''))>=0,'visible index cannot be negative');
 await h.page.screenshot({path:path.join(__dirname,'evidence/today-phone.png')});
 await h.page.evaluate(()=>{state.plantGroup=null;eq796s().seen=true;go('plant');});
 await h.page.waitForTimeout(250);
 const node=h.page.locator('[data-physical-alias963]');assert.equal(await node.count(),1);
 for(const k of ['FL01','FL02','T0003','T0004'])assert.equal(await node.locator('[data-open="'+k+'"]').count(),1);
 const ui=await h.page.evaluate(()=>({width:document.documentElement.scrollWidth,inner:innerWidth,aliases:document.querySelector('[data-physical-alias963]')?.textContent,indexTitle:document.querySelector('.w885-title')?.textContent}));assert(ui.width<=ui.inner+1);
 await node.evaluate(n=>{const d=n.closest('details');if(d)d.open=true;});await node.scrollIntoViewIfNeeded();
 await h.page.screenshot({path:path.join(__dirname,'evidence/equipment-phone.png')});
 assert.deepEqual(h.errors,[]);
 const evidence={author:'Andrew Fisher',pass:true,recordVersion:frozen.version,recordUnchanged:true,aliases:out.physical.aliases,inventoryDelta:delta,equipment:out.summary.byId.equipment,groups:out.groups.equipment.groups.map(g=>({name:g.name,total:g.summary.total,keys:g.keys})),paired,coverage:out.groups.__coverage,financialEquipmentComparisonsUnchanged:true,ui,errors:h.errors};
 fs.writeFileSync(path.join(__dirname,'evidence/native.json'),JSON.stringify(evidence,null,2));
 fs.writeFileSync(process.env.MODELS||'/workspace/private-fencing958/results963.json',JSON.stringify(out,null,2));
 console.log(JSON.stringify({pass:true,aliases:out.physical.aliases.map(a=>[a.ref,a.source]),inventoryDelta:delta,equipment:[out.summary.byId.equipment.done,out.summary.byId.equipment.total,out.summary.byId.equipment.pct],recordUnchanged:true,errors:h.errors}));
 }finally{await h.browser.close();}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
