/* Author: Andrew Fisher. Generic synthetic acceptance checks. No project evidence or ledger mutations. */
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const crypto=require('node:crypto');
const corePath=require('node:path').resolve(process.argv[2]||require('node:path').join(__dirname,'../source/fencing-trace-core837.js'));
if(!corePath)throw Error('Provide the pure core module path');
const api=require(corePath),checks=[];
const H='a'.repeat(64),P='b'.repeat(64),O='c'.repeat(64);
const copy=x=>JSON.parse(JSON.stringify(x));
function fixture(){
 const geometry={id:'g1',source_sha256:P,source_page:1,points:[[1,2],[3,4]]};
 const record={book:'red',id:'R1',docket_no:'N1',date:'2026-01-01',location:'Area A',quantities:{clean:10},paid_total:80,cost_total:120,paid_state:'priced',cost_state:'priced',paid_unpriced:[],unpriced:[],lines:[{paid:80,cost:120}]};
 const input={schema:1,master_sha256:H,sources:[{id:'plan.pdf',sha256:P,pages:2},{id:'original.pdf',sha256:O,pages:1}],areas:[{id:'a1',geometry_id:'g1',source_id:'plan',source_sha256:P,source_page:1,source_revision:'revision-A',master_sha256:H,scope:'area',label:'Area A',expected_geometry:copy(geometry),basis:'Explicit synthetic area evidence'}],rows:[{book:'red',record_id:'R1',docket_no:'N1',area_ids:['a1'],activity:'install',expected:{location:'Area A',quantities:{clean:10}},evidence:[{source_id:'original.pdf',sha256:O,page:1}],basis:'Synthetic original'}],relations:[],unmapped:[]};
 const context={master_sha256:H,geometry:[geometry],sources:[{id:'plan',sha256:P,revision:'revision-A',document_file:'plan.pdf'}],files:{'plan.pdf':{sha256:P},'original.pdf':{sha256:O}},records:[record],reviews:{[api.key(record)]:{state:'current',po:{number:'PO-X'},query:'Source reviewed'}},links:{},purchaseOrders:[{number:'PO-X',supplier_code:'S',supplier_name:'Supplier',amount:300,invoice_no:'INV-X',confirmed:true}]};
 return {input,context};
}
function check(id,fn){if(process.env.TRACE_CHECK_FILTER&&!id.includes(process.env.TRACE_CHECK_FILTER))return;try{fn();checks.push({id,result:'pass'});}catch(e){checks.push({id,result:'fail',message:e.message});}}
function current(f){const m=api.model(f.input,f.context);assert.equal(m.rows[0].state,'current');return m;}
check('valid-source-and-current-row',()=>{const m=current(fixture());assert.equal(m.rows.length,1);assert.equal(m.rows[0].money.supplier,80);assert.equal(m.rows[0].money.revenue,120);assert.equal(m.allocation,'not allocated');});
check('native-invoice-amount-basis-is-distinct-from-source-association',()=>{const m=current(fixture());assert.equal(m.orders[0].amount,300);assert.notEqual(m.orders[0].basis,'source_summary','Order amount is sourced from native P/O, not the supplier summary');});
check('invoice-is-not-payment',()=>{const m=current(fixture());assert.equal(m.orders[0].payment,'unknown');assert.equal(m.orders[0].invoice_no,'INV-X');assert.equal(m.rows[0].money.supplier,80);assert.equal(m.rows[0].money.revenue,120);});
check('source-page-upper-bound-known',()=>{const f=fixture();assert.ok(api.documentState({source_id:'original.pdf',sha256:O,page:2},f.input.sources,f.context.files));});
check('source-page-count-must-be-known',()=>{const f=fixture();delete f.input.sources[1].pages;assert.ok(api.documentState({source_id:'original.pdf',sha256:O,page:999},f.input.sources,f.context.files),'Missing source page count must not accept page999');});
check('one-record-many-geometries-deduplicates',()=>{const f=fixture(),g2={...copy(f.context.geometry[0]),id:'g2'};f.context.geometry.push(g2);f.input.areas.push({...copy(f.input.areas[0]),id:'a2',geometry_id:'g2',expected_geometry:g2});f.input.rows[0].area_ids.push('a2');const m=current(f),s=api.selection(m,['g1','g2','g1']);assert.equal(s.rows.length,1);assert.equal(s.rows[0].money.supplier,80);assert.equal(s.rows[0].money.revenue,120);assert.equal(s.orders.length,1);assert.equal(s.allocation,'not allocated');});
check('one-po-many-records-shared-once',()=>{const f=fixture();const r={...copy(f.context.records[0]),id:'R2',docket_no:'N2',paid_total:160,cost_total:240};f.context.records.push(r);f.context.reviews[api.key(r)]={state:'current',po:{number:'PO-X'}};f.input.rows.push({...copy(f.input.rows[0]),record_id:'R2',docket_no:'N2'});const m=current(f),s=api.selection(m,['g1']);assert.equal(s.rows.length,2);assert.equal(s.orders.length,1);assert.equal(s.orders[0].amount,300);assert.equal(s.orders[0].record_keys.length,2);assert.equal(s.allocation,'not allocated');assert.ok(!('total' in s));});
check('green-cost-only-whole-record',()=>{const m=api.money({book:'green',cost:150});assert.equal(m.supplier,150);assert.equal(m.revenue,null);assert.match(m.revenue_state,/cost only/i);});
check('blue-collections-stay-unpriced',()=>{const m=api.money({book:'blue',cost:0,paid_total:123,cost_total:456});assert.equal(m.supplier,null);assert.equal(m.revenue,null);assert.match(m.supplier_state,/counts only/i);});
check('partial-money-keeps-missing-rate-state',()=>{const m=api.money({book:'red',paid_total:80,cost_total:120,paid_state:'partly priced',cost_state:'partly priced',paid_unpriced:['unknown'],unpriced:['other'],lines:[{paid:80,cost:120},{paid:null,cost:null}]});assert.equal(m.supplier,80);assert.equal(m.revenue,120);assert.equal(m.supplier_state,'partly priced');assert.deepEqual(m.supplier_unpriced,['unknown']);assert.deepEqual(m.revenue_unpriced,['other']);});
check('explicit-zero-distinct-from-null',()=>{assert.equal(api.money({book:'green',cost:0}).supplier,0);assert.equal(api.money({book:'green',cost:null}).supplier,null);assert.equal(api.money({book:'red',paid_total:null,cost_total:null}).supplier,null);});
check('current-money-hydration-does-not-reprice-from-edge',()=>{const f=fixture();f.context.records[0].paid_total=95;f.context.records[0].cost_total=155;const m=current(f);assert.equal(m.rows[0].money.supplier,95);assert.equal(m.rows[0].money.revenue,155);assert.equal(m.orders[0].amount,300);});
check('stale-record-suspends-link-not-record',()=>{const f=fixture();f.context.records[0].quantities.clean=12;const m=api.model(f.input,f.context);assert.equal(m.rows[0].state,'unavailable');assert.equal(m.rows[0].money,null);assert.equal(m.orders.length,0);assert.equal(f.context.records[0].quantities.clean,12);});
check('stale-document-fingerprint-suspends-link',()=>{const f=fixture();f.context.files['original.pdf'].sha256='d'.repeat(64);const m=api.model(f.input,f.context);assert.equal(m.rows[0].state,'unavailable');assert.equal(m.rows[0].money,null);assert.equal(m.orders.length,0);});
check('stale-plan-revision-suspends-area',()=>{const f=fixture();f.context.sources[0].revision='revision-B';const m=api.model(f.input,f.context);assert.equal(m.areas[0].state,'unavailable');assert.equal(m.rows[0].state,'unavailable');});
check('book-id-number-must-all-match',()=>{const f=fixture();f.context.records[0].book='green';const m=api.model(f.input,f.context);assert.equal(m.rows[0].state,'unavailable');assert.equal(m.rows[0].money,null);});
check('duplicate-docket-number-fails-closed',()=>{const f=fixture();f.context.records.push({...copy(f.context.records[0]),id:'R2'});const m=api.model(f.input,f.context);assert.equal(m.rows[0].state,'unavailable');assert.equal(m.orders.length,0);});
check('no-fuzzy-location-reassignment',()=>{const f=fixture();f.context.records[0].location='Area A nearby compound';const m=api.model(f.input,f.context);assert.equal(m.rows[0].state,'unavailable');});
check('cent-precision-native-amount',()=>{const f=fixture();f.context.purchaseOrders[0].amount=300.50;const m=current(f);assert.equal(m.orders[0].amount,300.50);});
check('unmapped-valid-identity-retained',()=>{const f=fixture();f.input.unmapped=[{book:'red',record_id:'R1',docket_no:'N1',reason:'No reviewed geometry'}];const m=current(f);assert.equal(m.unmapped.length,1);assert.equal(m.unmapped[0].location,'Area A');});
check('inputs-unmodified-no-native-write-callback',()=>{const f=fixture();let writes=0;f.context.nativeSetter=()=>writes++;const before=JSON.stringify(f);const m=current(f);api.selection(m,['g1']);assert.equal(JSON.stringify(f),before);assert.equal(writes,0);});
check('all-missing-rates-are-not-zero-priced',()=>{const m=api.money({book:'red',paid_total:0,cost_total:0,paid_state:'partly priced',cost_state:'partly priced',paid_unpriced:['unknown'],unpriced:['unknown'],lines:[{paid:null,cost:null}]});assert.equal(m.supplier,null);assert.equal(m.revenue,null);assert.deepEqual(m.supplier_unpriced,['unknown']);});
check('explicit-priced-zero-is-preserved',()=>{const m=api.money({book:'red',paid_total:0,cost_total:0,paid_state:'priced',cost_state:'priced',paid_unpriced:[],unpriced:[],lines:[{paid:0,cost:0}]});assert.equal(m.supplier,0);assert.equal(m.revenue,0);});
function relationFixture(){const f=fixture();const r={...copy(f.context.records[0]),id:'R2',docket_no:'N2'};f.context.records.push(r);f.input.rows.push({...copy(f.input.rows[0]),record_id:'R2',docket_no:'N2'});f.input.relations=[{child_record_id:'R2',parent_record_id:'R1',kind:'additional_bracing',evidence:copy(f.input.rows[0].evidence),expected_child:copy(f.input.rows[1].expected),expected_parent:copy(f.input.rows[0].expected)}];return f;}
check('relation-current-endpoint-signatures',()=>{const f=relationFixture();assert.equal(api.model(f.input,f.context).relations.length,1);});
check('relation-stale-note-does-not-survive-refreshed-row',()=>{const f=relationFixture();f.input.relations[0].expected_parent.location='Older unrelated area';const m=api.model(f.input,f.context);assert.equal(m.rows.filter(x=>x.state==='current').length,2);assert.equal(m.relations.length,0);});
check('relation-missing-endpoint-signature-fails-closed',()=>{const f=relationFixture();delete f.input.relations[0].expected_parent;assert.equal(api.model(f.input,f.context).relations.length,0);});
function commercialFixture(){const f=fixture(),S='d'.repeat(64),T='e'.repeat(64);f.input.sources.push({id:'summary.pdf',sha256:S,pages:1},{id:'other-summary.pdf',sha256:T,pages:1});f.context.files['summary.pdf']={sha256:S};f.context.files['other-summary.pdf']={sha256:T};const r={...copy(f.context.records[0]),id:'R2',docket_no:'N2',paid_total:160,cost_total:240};f.context.records.push(r);f.input.rows.push({...copy(f.input.rows[0]),record_id:'R2',docket_no:'N2'});f.context.reviews[api.key(r)]={state:'current',po:{number:'PO-X'}};const source={source_id:'summary.pdf',sha256:S,page:1};const make=(id,cents,record)=>({id,label:id,number:'PO-X',supplier:'S',source:copy(source),records:record?[{book:'red',record_id:record.id,docket_no:record.docket_no}]:[],parents:[],amount_cents:cents,lines:[{line_id:id+':line',category:'synthetic',quantity:1,unit:'each',rate_cents:cents,amount_cents:cents}],unallocated:!record});f.input.commercial={schema:1,groups:[{number:'PO-X',supplier:'S',source,total_cents:30000,allocations:[make('A',11000,f.context.records[0]),make('B',14000,r),make('residual',5000,null)]}],additional:[]};return f;}
check('commercial-source-allocations-plus-residual',()=>{const f=commercialFixture(),m=current(f),g=m.commercial.groups[0];assert.equal(g.state,'current');assert.equal(g.total_cents,30000);assert.equal(g.native_amount,300);assert.equal(g.native_match,true);assert.equal(g.allocations[2].unallocated,true);assert.equal(g.allocations[2].records.length,0);assert.equal(m.rows[0].money.supplier,80);assert.equal(m.rows[0].money.revenue,120);});
check('commercial-source-and-native-difference-preserved',()=>{const f=commercialFixture();f.context.purchaseOrders[0].amount=300.50;const g=current(f).commercial.groups[0];assert.equal(g.total_cents,30000);assert.equal(g.native_amount,300.50);assert.equal(g.native_match,false);});
check('commercial-group-once-for-many-members',()=>{const f=commercialFixture(),m=current(f),s=api.selection(m,['g1']);assert.equal(s.rows.length,2);assert.equal(s.commercial.groups.length,1);assert.equal(s.commercial.groups[0].total_cents,30000);});
check('commercial-unmapped-group-remains-available',()=>{const f=commercialFixture();f.input.rows.forEach(r=>r.area_ids=[]);const m=current(f);assert.equal(m.commercial.groups[0].state,'current');assert.equal(m.commercial.groups[0].total_cents,30000);assert.equal(m.commercial.groups[0].allocations[0].amount_cents,11000);});
check('commercial-duplicate-source-line-rejected',()=>{const f=commercialFixture();f.input.commercial.groups[0].allocations[1].lines[0].line_id=f.input.commercial.groups[0].allocations[0].lines[0].line_id;const g=current(f).commercial.groups[0];assert.equal(g.state,'unavailable');assert.equal(g.total_cents,null);});
check('commercial-residual-cannot-hide-overallocation',()=>{const f=commercialFixture();f.input.commercial.groups[0].allocations[2].amount_cents=6000;f.input.commercial.groups[0].allocations[2].lines[0].amount_cents=6000;const g=current(f).commercial.groups[0];assert.equal(g.state,'unavailable');assert.equal(g.total_cents,null);});
check('commercial-stale-source-fails-closed',()=>{const f=commercialFixture();f.context.files['summary.pdf'].sha256='f'.repeat(64);const g=current(f).commercial.groups[0];assert.equal(g.state,'unavailable');assert.equal(g.total_cents,null);});
check('commercial-exact-po-association-required',()=>{const f=commercialFixture();f.context.reviews[api.key(f.context.records[0])].po.number='PO-Y';const g=current(f).commercial.groups[0];assert.equal(g.state,'unavailable');});
check('commercial-unnumbered-residual-stays-unnumbered',()=>{const f=commercialFixture();f.input.commercial.groups[0].allocations[2].records=[{book:'red',record_id:'R1',docket_no:'N1'}];assert.equal(current(f).commercial.groups[0].state,'unavailable');});
check('commercial-negative-credit-preserved',()=>{const f=commercialFixture(),a=copy(f.input.commercial.groups[0].allocations[0]);a.id='upgrade';a.amount_cents=1200;a.lines=[{line_id:'upgrade:credit',category:'clean_credit',amount_cents:-2000},{line_id:'upgrade:braced',category:'braced',amount_cents:3200}];f.input.commercial.additional=[a];const m=current(f),x=m.commercial.additional[0];assert.equal(x.state,'current');assert.equal(x.amount_cents,1200);assert.deepEqual(x.lines.map(l=>l.amount_cents),[-2000,3200]);assert.equal(m.rows[0].money.supplier,80);assert.equal(m.rows[0].money.revenue,120);});
check('commercial-stale-parent-rejects-upgrade-allocation',()=>{const f=commercialFixture(),a=copy(f.input.commercial.groups[0].allocations[0]);a.id='upgrade';a.lines[0].line_id='upgrade:unique';a.parents=[{book:'red',record_id:'R2',docket_no:'N2'}];a.parent_source=copy(a.source);f.input.commercial.additional=[a];f.context.records[1].location='Changed parent location';const m=api.model(f.input,f.context);assert.equal(m.commercial.additional[0].state,'unavailable');});
check('commercial-group-rejects-another-summary-allocation',()=>{const f=commercialFixture();f.input.commercial.groups[0].allocations[1].source={source_id:'other-summary.pdf',sha256:'e'.repeat(64),page:1};assert.equal(current(f).commercial.groups[0].state,'unavailable','A whole-summary group must not silently mix another summary source');});
check('commercial-different-native-supplier-not-a-match',()=>{const f=commercialFixture();f.context.purchaseOrders[0].supplier_code='OTHER';const g=current(f).commercial.groups[0];assert.equal(g.state,'current');assert.equal(g.native_match,null);assert.match(g.native_comparison,/supplier/i);});
check('commercial-duplicate-native-po-does-not-pick-first',()=>{const f=commercialFixture();f.context.purchaseOrders.push({...copy(f.context.purchaseOrders[0]),amount:999});const g=current(f).commercial.groups[0];assert.equal(g.state,'current');assert.equal(g.native_match,null);assert.equal(g.native_amount,null);assert.match(g.native_comparison,/ambiguous/i);});
const result={type:'Generic synthetic pure-core checks; no real financial evidence',core_sha256:crypto.createHash('sha256').update(fs.readFileSync(corePath)).digest('hex'),checks,passed:checks.filter(x=>x.result==='pass').length,failed:checks.filter(x=>x.result==='fail').length,pending:['Owner browser navigation, source links and zero-write lifecycle check']};
if(process.argv[3])fs.writeFileSync(process.argv[3],JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({core_sha256:result.core_sha256,passed:result.passed,failed:result.failed,failures:checks.filter(x=>x.result==='fail')},null,2));process.exitCode=result.failed?1:0;
