#!/usr/bin/env node
/* The page-side fixes from REVIEW.md, applied to the page's own source.

     node gc500/page-fixes/apply.js <print/build_asset_app.py | GC500_Delivery_Control_hosted-NN.html> [out]

   The page is generated by print/build_asset_app.py in the GC500 package (the app script sits in it verbatim),
   so the same edits apply to the builder and to a built page. Each edit is an exact-text replacement that must
   be found exactly once, or nothing is written. Written against hosted-37 / the v5.25 package of 17 Sep 2026.

   What it changes (numbers are REVIEW.md's):
     R1  renderDocs: a drawing thumbnail keeps its own file link; only the card's buttons open the asset drawer
     R2  finderPick: closes the search through closeSearch(), so the magnifier's state and SEARCH_FROM follow
     R4  recordBytes: the record's size is measured when it is written, not read back out of localStorage
         on every poll (persist() sets the cache; recordBytes() reuses it for 20 s)
     B1  timeOfStamp: hourCycle 'h23', so a light set just after midnight never prints as 24:05
     B3  showcase countdown: the event name is escaped once, so an & in it reads as &
     B4  photoRedraw: redraws through syncRedraw(), which waits while somebody is typing
     B5  boardWxNote: builds plain text; the first draw escapes it exactly as the refresh path does
     B6  adviceSheet: prints on the font-settled path paperOpen() uses, instead of a flat 60 ms timer
   R3 (showReduced honouring Motion: Off) is already in hosted-37. B2 (the scanner burst detector in the search
   box) is left as it is: a fast Enter on a four-character search opens the one match, which is the intended
   scanner behaviour, and the miss case only moves to the Register with the text as the query. */
'use strict';
const fs = require('fs');
const src = process.argv[2], out = process.argv[3] || src;
if (!src || !fs.existsSync(src)) { console.error('usage: apply.js <build_asset_app.py | page.html> [out]'); process.exit(2); }
let text = fs.readFileSync(src, 'utf8');
const EDITS = [
  ['R1', "pane.querySelectorAll('.doccard [data-open]').forEach(b => b.onclick = () => openAsset(b.dataset.open));",
         "pane.querySelectorAll('.doccard [data-open]:not(img.thumb)').forEach(b => b.onclick = () => openAsset(b.dataset.open)); /* a drawing's cover keeps its own file link, bound above */"],
  ['R2', "$('#qx').hidden = true; document.body.classList.remove('search-open');",
         "$('#qx').hidden = true; closeSearch({keepQuery: true, noFocus: true}); /* through closeSearch, so the magnifier and SEARCH_FROM follow */"],
  ['R4a', "try { localStorage.setItem(STORE, JSON.stringify(S)); return true; }",
          "try { const s = JSON.stringify(S); localStorage.setItem(STORE, s); RB_CACHE = {at: Date.now(), bytes: s.length * 2}; return true; }"],
  ['R4b', "function recordBytes(){ try { const s = localStorage.getItem(STORE); return s ? s.length * 2 : 0; } catch (e) { return 0; } }",
          "var RB_CACHE = null; /* set by persist() when the record is written; read back at most every 20 s, not on every poll */\n"
        + "function recordBytes(){ const now = Date.now(); if (RB_CACHE && now - RB_CACHE.at < 20000) return RB_CACHE.bytes;\n"
        + "  try { const s = localStorage.getItem(STORE); RB_CACHE = {at: now, bytes: s ? s.length * 2 : 0}; } catch (e) { RB_CACHE = {at: now, bytes: 0}; } return RB_CACHE.bytes; }"],
  ['B1', "minute: '2-digit', hour12: false}).format(d);",
         "minute: '2-digit', hourCycle: 'h23'}).format(d);"],
  ['B3', "return kick(esc(DATA.event.name))",
         "return kick(DATA.event.name)"],
  ['B4', "if (state.tab && state.tab !== 'docs') render();",
         "if (state.tab && state.tab !== 'docs') { syncRedraw(); return; } /* waits while somebody is typing, and reopens the drawer itself */"],
  ['B5a', ", their reading of ${esc(d.reading_at)}` : ''}${",
          ", their reading of ${d.reading_at}` : ''}${"],
  ['B5b', '<span class="${note.cls}">${note.t}</span>',
          '<span class="${note.cls}">${esc(note.t)}</span>'],
  ['B6', "setTimeout(() => { try { markCards(); window.print(); } catch (e) { done(); } }, 60);",
         "{ const fonts = (document.fonts && document.fonts.ready) ? document.fonts.ready : Promise.resolve(); const settle = ms => new Promise(r => setTimeout(r, ms));\n"
       + "    Promise.race([fonts.catch(() => {}), settle(1500)]).then(() => settle(60)).then(() => { try { markCards(); window.print(); } catch (e) { done(); } }); }"],
];
const missing = [];
for (const [id, from, to] of EDITS) {
  const n = text.split(from).length - 1;
  if (n !== 1) { missing.push(id + ' found ' + n + ' times'); continue; }
  text = text.replace(from, () => to);
  console.log('ok   ' + id);
}
if (missing.length) { console.error('not applied — ' + missing.join('; ')); process.exit(1); }
fs.writeFileSync(out, text);
console.log('written ' + out + ' (' + text.length + ' chars)');
