// Author: Andrew Fisher. GET-only frozen native comparison; financial artifacts stay outside Git.
const fs=require('fs'),path=require('path'),Module=require('module'),assert=require('assert/strict');
const D=__dirname,OUT=process.env.OUT,BASE=process.env.BASE,PAGE=process.env.PAGE;
assert(OUT&&BASE&&PAGE,'OUT, BASE and PAGE required');fs.mkdirSync(OUT,{recursive:true});
const H=path.resolve(D,'../toolchain/harness'),hp=H+'/open_page.js',fetcher=require(H+'/curlfetch'),native=fetcher.curlFetch;
let frozen=fs.existsSync(OUT+'/state.json')?JSON.parse(fs.readFileSync(OUT+'/state.json')):null;
fetcher.curlFetch=async(url,headers,method,body)=>{assert.equal(method,'GET');const u=new URL(url);if(frozen&&u.origin==='https://gc500-production.up.railway.app'&&['/api/state','/api/version'].includes(u.pathname)){const j=u.pathname==='/api/state'?frozen:{version:frozen.version,updated:frozen.updated,level:'view'};return{status:200,headers:{'content-type':'application/json'},body:Buffer.from(JSON.stringify(j))};}const r=await native(url,headers,method,body);if(u.pathname==='/api/state'&&r.status===200){frozen=JSON.parse(r.body);fs.writeFileSync(OUT+'/state.json',JSON.stringify(frozen));}return r;};
const h=new Module(hp,module);h.filename=hp;h.paths=Module._nodeModulePaths(path.dirname(hp));h._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;'),hp);
async function run(name,file,phone=false){const b=await h.exports.open({pageFile:file,hash:'#costs',W:phone?390:1440,H:phone?844:1000,mobile:phone}),p=b.page;try{
 await p.waitForFunction(()=>SYNC.status==='live'&&Object.keys(SYNC_COLLS).every(k=>SYNC.first.has(k)),null,{timeout:120000});
 await p.evaluate(()=>{window.__before956=JSON.stringify(S);window.print=()=>{};bump=()=>{throw Error('No operational writes');};});
 const result=await p.evaluate(()=>{RENDER_MEMO.clear();return holdAssets(()=>({version:SYNC.backend.readVersion821(),money:moneySummary(todayIso()),transport:transport888Core(),building:buildingTransportModel831(),supplier:Source949.model(),costs:cj764Model(),profit:pl770Model(),finance:fh866Model(),recon:recon888Model(),rehire:rh766Model()}));});
 fs.writeFileSync(OUT+'/'+name+'.json',JSON.stringify(result,null,2));
 if(phone){await p.evaluate(()=>{document.body.innerHTML=tr888Html();const d=document.querySelector('.transport953');if(d)d.open=true;});await p.locator('.transport953').evaluate(e=>e.scrollIntoView({block:'start'}));await p.screenshot({path:OUT+'/phone.png'});const sample=p.locator('.transport953 tbody tr').filter({hasText:'WC60'}).first();await sample.evaluate(e=>e.scrollIntoView({block:'start'}));await p.screenshot({path:OUT+'/phone-allowance.png'});const w=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,screen:innerWidth}));assert(w.scroll<=w.screen+1,'phone overflow');}
 assert(await p.evaluate(()=>JSON.stringify(S)===__before956));assert.deepEqual(b.errors,[]);return result;
 }finally{await b.browser.close();}}
(async()=>{const before=process.env.PHONE_ONLY?JSON.parse(fs.readFileSync(OUT+'/before.json')):await run('before',BASE),after=process.env.PHONE_ONLY?JSON.parse(fs.readFileSync(OUT+'/after.json')):await run('after',PAGE),T=after.transport;
 assert.equal(before.version,after.version);assert.equal(T.audit953.added.length,34,'reviewed source movements');assert.equal(T.audit953.excluded.length,5,'exact quote overlaps only');assert.equal(T.forecast.plannedInbound953,8);assert.equal(T.forecast.plannedDemob953,26);assert.deepEqual(after.money,before.money,'all actual/customer money');assert.deepEqual(after.building,before.building,'all customer transport');assert.deepEqual(after.supplier,before.supplier,'all other supplier forecasts');assert.deepEqual(T.schedT,before.transport.schedT,'actual schedule totals');assert.deepEqual(T.OCL,before.transport.OCL,'typed cost records');assert.equal(T.rows.length,before.transport.rows.length,'no planned load promoted to booking');
 const cash=r=>['card','average'].includes(r.forecast.kind),round=n=>Math.round(n*100)/100;
 assert.equal(round(T.rows.concat(T.planned).filter(cash).reduce((s,r)=>s+r.forecast.amount,0)),T.forecast.total,'every displayed allowance ties');assert.equal(round(Object.values(T.weights.toCome).reduce((s,n)=>s+n,0)+T.weights.toComeNone),T.forecast.total,'Finance weights tie');
 const prior=before.transport.rows.filter(r=>r.leg==='demob'&&r.forecast.kind==='average');assert.equal(prior.length,6);for(const r of prior)assert.deepEqual(T.rows.find(x=>x.id===r.id).forecast,r.forecast,'existing average demob unchanged');
 assert(after.recon.ties.every(t=>t.ok),'native reconciliation');assert.equal(after.costs.known,before.costs.known);assert.deepEqual(after.costs.revenue,before.costs.revenue);assert.equal(round(T.forecast.total-before.transport.forecast.total),986.92,'two original source matches only');assert.equal(round(T.demob.total-before.transport.demob.total),986.92,'demob cut only changes by source amounts');assert.deepEqual(T.rows,before.transport.rows,'every existing transport row and cent preserved');const aliasKeys=new Set(['WC05','WC60']);for(const r of before.transport.planned.filter(r=>!aliasKeys.has(r.key)))assert.deepEqual(T.planned.find(x=>x.id===r.id),r,'other planned rows and cents preserved');assert.equal(round(after.costs.toCome-before.costs.toCome),986.92,'cost forecast delta');assert.deepEqual(after.rehire,before.rehire,'supplier forecast unaffected');for(const key of ['WC05','WC60']){const r=T.planned.find(x=>x.key===key&&x.leg==='demob');assert.equal(r.forecast.kind,'card');assert(r.forecast.reason928.includes('tank-mounted block'));}const unknown=T.rows.find(r=>r.key==='WC09'&&r.item==='Toilet Block 6m');assert.equal(unknown.forecast.kind,'held');assert.equal(after.rehire.totals.costMissing,before.rehire.totals.costMissing);
 await run('phone',PAGE,true);fs.writeFileSync(OUT+'/proof.json',JSON.stringify({record:after.version,actualsUnchanged:true,customerRevenueUnchanged:true,recordsUnchanged:true,nativeTies:after.recon.ties.length,added:T.audit953.added.length,excluded:T.audit953.excluded.length,delta:round(T.forecast.total-before.transport.forecast.total),forecast:T.forecast.total,plannedInbound:T.forecast.plannedInbound953,plannedDemob:T.forecast.plannedDemob953,actualSupplierMissing:after.rehire.totals.costMissing,forecastSupplierMissing:after.rehire.totals.forecastMissing},null,2));console.log('PASS',JSON.stringify({record:after.version,ties:after.recon.ties.length,added:T.audit953.added.length,excluded:T.audit953.excluded.length,forecast:T.forecast.total,delta:round(T.forecast.total-before.transport.forecast.total)}));
})().catch(e=>{console.error(e.stack);process.exitCode=1});
