/* Author: Andrew Fisher. Real native-frame card sizing and close regressions. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {open}=require('./strict948.cjs');
const inv=require('./preservation.cjs');
const out=process.env.OUT948;fs.mkdirSync(out,{recursive:true});
(async()=>{for(const mobile of [false,true]){const device=mobile?'phone':'desktop';let s;const report={device,fixture:!!process.env.STATE948,checks:[]};
try{s=await open({pageFile:process.env.PAGE,mobile,W:mobile?390:1440,H:mobile?844:900,dpr:1});const p=s.page;p.setDefaultTimeout(10000);
await p.waitForFunction(()=>typeof SYNC!=='undefined'&&SYNC.status==='live'&&Object.keys(SYNC_COLLS).every(k=>SYNC.first.has(k)),null,{timeout:120000});await inv.guard(p);await inv.capture(p);await p.evaluate(()=>go('today'));await p.waitForTimeout(1500);const before=await inv.capture(p);
await p.evaluate(()=>expOpen2d());await p.waitForFunction(()=>expApi()?.GC500Explorer?.state?.ready&&typeof expApi()?.GC500Explorer?.is3d==='function'&&gc500ExplorerCard948.active(EXP.frame),null,{timeout:120000});await p.waitForTimeout(1200);
const f=p.locator('#expFrame').contentFrame();
async function select(key){await p.evaluate(key=>expApi().GC500Explorer.find(key),key);await f.locator('#xcard:not([hidden])').waitFor();await p.waitForTimeout(500);}
async function geometry(name){const v=await p.evaluate(()=>{const d=expApi().document,c=d.getElementById('xcard'),b=c.querySelector('[data-xclose]'),s=d.getElementById('stage'),r=x=>{const q=x.getBoundingClientRect();return{top:q.top,bottom:q.bottom,left:q.left,right:q.right,height:q.height,width:q.width}};const cr=r(c),br=r(b),sr=r(s);return{card:cr,button:br,stage:sr,closeHit:d.elementFromPoint(br.left+br.width/2,br.top+br.height/2)===b,scrollHeight:c.scrollHeight,clientHeight:c.clientHeight,bottom:c.style.bottom,room:c.style.getPropertyValue('--card-room948'),styles:d.querySelectorAll('#explorer-card948').length};});report.checks.push({name,geometry:v});assert(v.card.top>=v.stage.top-1,name+' top');assert(v.card.bottom<=v.stage.bottom+1,name+' bottom');assert(v.closeHit,name+' reachable Close');assert.equal(v.styles,1);return v;}
for(const key of ['WC20','GN19']){await select(key);await geometry(key);await f.locator('[data-xclose]').click();assert(await f.locator('#xcard').isHidden());report.checks.push({name:key+' normal Close',ok:true});}
await select('WC20');await geometry('WC20 selected');await p.screenshot({path:path.join(out,device+'-card.png')});
await f.locator('#xcard').evaluate(c=>c.scrollTop=c.scrollHeight);if(mobile)await f.locator('#xcard').evaluate(c=>c.scrollTop=0);await geometry(mobile?'phone scroll return':'scrolled Close');await f.locator('[data-xclose]').click();assert(await f.locator('#xcard').isHidden());
await select('WC20');await p.evaluate(()=>{const w=expApi(),m=w.document.getElementById('mini');m.style.display='none';w.dispatchEvent(new w.Event('resize'));});await p.waitForTimeout(250);await geometry('minimap hidden');
await p.evaluate(()=>{const w=expApi(),m=w.document.getElementById('mini');m.style.display='';w.dispatchEvent(new w.Event('resize'));});await p.waitForTimeout(250);await geometry('minimap restored');
await p.setViewportSize({width:mobile?844:1024,height:mobile?390:650});await p.waitForTimeout(700);await geometry('resized selected card');await f.locator('[data-xclose]').click();assert(await f.locator('#xcard').isHidden());await select('WC20');
await p.setViewportSize({width:mobile?390:1440,height:mobile?844:900});await p.waitForTimeout(500);await geometry('restored viewport');
await f.locator('[data-xclose]').focus();await p.keyboard.press('Escape');assert(await f.locator('#xcard').isHidden());
await select('WC20');const text=await f.locator('#xcard').innerText();
for(let i=0;i<3;i++){const hidden=await p.evaluate(()=>{const old=EXP.frame;go('today');return{active:gc500ExplorerCard948.active(old),key:S&&JSON.stringify(S).length};});assert(!hidden.active,'observer disposed on tab departure');await p.evaluate(()=>expOpen2d());await p.waitForFunction(()=>expApi()?.GC500Explorer?.state?.ready&&gc500ExplorerCard948.active(EXP.frame),null,{timeout:30000});await select('WC20');assert.equal(await f.locator('#xcard').innerText(),text);await geometry('reopen '+i);}
const cycles=await p.evaluate(async()=>{const c=expApi().document.getElementById('xcard');let n=0;const o=new MutationObserver(()=>n++);o.observe(c,{attributes:true,attributeFilter:['style']});await new Promise(r=>setTimeout(r,400));o.disconnect();return n;});assert.equal(cycles,0,'no idle observer style loop');report.checks.push({name:'idle observer loop',mutations:cycles});
inv.unchanged(before,await inv.capture(p));await inv.assertNoWrites(p,s);report.preserved=true;report.errors=s.errors;assert.equal(s.errors.length,0);report.counts=s.counts;report.ok=true;console.log(device+' PASS '+report.checks.length);
}catch(e){report.error=String(e.stack);console.error(device+' '+report.error);if(s)try{await s.page.screenshot({path:path.join(out,device+'-failure.png'),timeout:10000});}catch(_){}process.exitCode=1;}finally{fs.writeFileSync(path.join(out,device+'.json'),JSON.stringify(report,null,2));if(s)await s.browser.close();}}})().catch(e=>{console.error(e);process.exitCode=1});
