// Author: Andrew Fisher. Current-record and stale-artifact regressions.
const fs=require('fs'),vm=require('vm'),assert=require('assert');let rows=['P25','P66','P65','P67'].map((key,i)=>({a:{key},units:[{id:'u'+i,no:i?'':1189408,item:i?'Building 6m':'Building 4.8m'}],side:i%2?'driver':'passenger'}));
const ctx={holdAssets:f=>f(),programmeDays:()=>[{iso:'2026-10-14'}],dpLoads:()=>rows.map(r=>({kind:'deliveries',rows:[r]})),loading872Rows:a=>rows.find(r=>r.a.key===a.key).units,loading872Side:(a,id)=>rows.find(r=>r.a.key===a.key).side,handling875Record:a=>({method:"tilt-tray"}),handling875Words:s=>s,loading872Words:s=>'Door to '+s+' side',order782:()=>null,entry782:()=>null,flow891HeadLines:()=>'',daily821Model:()=>({loads:[]}),daily861Body:()=>'',daily861Gsm:s=>s,esc:s=>s,dpSec:(h,b)=>'<section>'+h+b+'</section>',flow891Card:()=>'',dpHero:()=>"",dpPage:()=>'<section class="dp-sec">original</section>',dropSmsLong:()=> 'native',pdf7MailText:()=>({text:'native'}),inPlace782:()=>false,document:{addEventListener(){}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(process.argv[2]||__dirname+'/../arrival943.js','utf8'),ctx);const run=s=>vm.runInContext(s,ctx);
assert.equal(run('arrival943Model().artifactCurrent'),true);
assert(run("dpPage({iso:'2026-10-14'},dpLoads()[0],'drv',1,4)").includes('arrival943-map'));
rows[1].units[0].item='Building 16m';assert.equal(run('arrival943Model().artifactCurrent'),false);rows[1].units[0].item='Building 60m';assert.equal(run('arrival943Model().artifactCurrent'),false);rows[1].units[0].item='Building 6m';const originalLoads=ctx.dpLoads;ctx.dpLoads=()=>[{kind:'deliveries',rows:rows}];assert.equal(run('arrival943Model().artifactCurrent'),false);ctx.dpLoads=originalLoads;
rows[0].units[0].no=999;assert.equal(run('arrival943Model().artifactCurrent'),false);assert(!run("dpPage({iso:'2026-10-14'},dpLoads()[0],'drv',1,4)").includes('arrival943-map'));assert(run('arrival943Words(arrival943Model())').includes('Asset 999'));
rows[0].units[0].no=1189408;rows[1].side='passenger';assert.equal(run('arrival943Model().artifactCurrent'),false);assert(run('arrival943Words(arrival943Model())').includes('stale'));
rows[1].side='driver';rows.reverse();assert.equal(run('arrival943Model().artifactCurrent'),false);assert(run('arrival943Words(arrival943Model())').includes('P67 → P65 → P66 → P25'));
assert.equal(run("dpPage({iso:'2026-10-13'},dpLoads()[0],'drv',1,4)"),'<section class="dp-sec">original</section>');
assert.equal(run("pdf7MailText('drivers','2026-10-13').text"),'native');rows=[];assert.equal(run('arrival943Model()'),null);assert.equal(run("dropSmsLong({key:'P25'})"),'native');console.log('arrival943 model regressions pass');
