/* Author: Andrew Fisher. Read-only delivered-product loading information; existing evidence and identity semantics retained. */
(function(root){
'use strict';
const GUIDE=/* GUIDE924_DATA */[];
const GUIDE_URL='/f/Coates-GC500-2026/Coates_Load_Restraint_Guide_2023.pdf';
const METHODS=[
 {id:'mobile',name:'Mobile plant and access equipment',pages:[9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,40],words:'Match the actual machine, transport configuration and matrix row. Check rated manufacturer restraint points, lashing geometry, attachments and loose equipment. Lifting capacity is not transport mass.'},
 {id:'trailer',name:'Trailer-mounted equipment',pages:[9,35,36,37,38,39,40],words:'Match along-deck (up to 1850 kg) or across-deck (up to 1200 kg) method, actual trailer mass and anchor geometry. Secure drawbar and onboard equipment; do not mix chain and webbing on the same restrained item under these methods.'},
 {id:'skid-small',name:'Skid equipment up to 3.3 t',pages:[41,42,43,44,45,46],words:'Match the complete skid method and source row. Central longitudinal placement, looped corner-chain arrangement, stated anchor offsets and stability ratio apply. Two abreast is limited to the same unit, up to 1.65 t each, with aligned pockets.'},
 {id:'skid-medium',name:'Skid equipment 3.3–5.4 t',pages:[41,42,43,47,48],words:'Match the complete skid method: corner restraint plus the specified additional through-pocket chain, exact anchor geometry and stability. Two-abreast limits differ from a single unit.'},
 {id:'skid-large',name:'Large skid equipment',pages:[41,42,43,49,50],words:'The general and model-table requirements differ in places, including the 5475 kg row under the 5.5 t heading and through-pocket chain counts. Resolve the applicable model requirement with Coates/carrier before recording a restraint assessment; do not select chain count from mass alone.'},
 {id:'container',name:'Containerised generator',pages:[41,42,52],words:'For containerised sets below 22 t, match the configuration and all four engaged twistlocks. Fuel tanks must be completely empty or full. Check loading exclusion and actual complete transport mass; skid-only dimensions do not describe a trailer.'},
 {id:'toilet-base',name:'Portable toilet — base restraint',pages:[41,42,53],words:'For small portable toilets up to 700 kg, straps pass over the base inside lifting-point positions, with the specified anti-slip interface and no timber dunnage. Check actual tank state. The Merlin table row is a reference for that unit, not every FWF toilet.'},
 {id:'toilet-blocked',name:'Portable toilets — blocked two abreast',pages:[41,42,54],words:'For small toilets up to 700 kg: requires depicted base restraint and an engineered headboard at least 1 m high providing 30% payload blocking, with at most 200 mm cumulative gap. Merely touching toilets together does not establish the method.'},
 {id:'toilet-frame',name:'Portable toilets — internal-frame top restraint',pages:[41,42,55],words:'For small toilets up to 700 kg: top restraint applies only to toilets with the specified internal frames. Confirm frame, strap path, friction and tank state; do not apply to a frameless unit or an ablution building.'},
 {id:'cage',name:'Transport cages and stillages',pages:[41,42,56,57],words:'Up to 5 t; cages carrying more than 500 kg require a rated WLL/SWL. Check condition, contents containment, wheel/castor condition, blocking, interface and the angle-specific table. These pages do not establish stacking permission.'},
 {id:'barrier',name:'Water-filled barriers',pages:[58,59,67,68],words:'Barriers must be empty for transport. Match model, vehicle, unitised layers, blocking and anti-spearing restraint. The guide limits layers to three on semitrailers and two on tilt trays; new/filmed barriers need extra lashings. This is not a fence-panel or fencing-foot method.'},
 {id:'building',name:'Portable building',pages:[79,80,81,82,83,84,85],words:'Complete pre-transit checks; secure windows, doors, air conditioners and contents. Scope is at most 12 m × 3 m and 5000 kg; select the correct 2000 kg or 5000 kg diagram and check frame and engineered anchors. The p83 dimension conflict requires clarification. Roof straps are not load restraint; overhead lifting points are not tie-down points.'},
 {id:'wagon',name:'Building wagon',pages:[86,87,88],words:'Only dual-axle wagons up to 3500 kg, with axles 300–500 mm above the deck. Match the axle-loop method and geometry; protect brake lines. Body lifting points are not the specified axle-loop restraint anchors.'},
 {id:'ablution',name:'Named Melbourne ablution blocks',pages:[118,119,120,121,122],words:'Only the named BAU sewer, 16 User Number 14 and Event Tank Mount Number 13 configurations. Maximum 5000 kg. Check actual identity, shackle/anchor geometry and the correct four- or six-chain drawing. Resolve the p121 diagram/body dimension conflict with the source owner.'},
 {id:'cube',name:'SMC SL80 pallet light cube',pages:[123,124],words:'Only the named SMC SL80 configuration. Use specified anti-slip mat at every contact, minimum 8 mm and friction 0.6; secure mast/stabilisers and match the single-file or touching-pair arrangement. The 1100 kg scope maximum is not an actual weight.'},
 {id:'other',name:'Other equipment / engineering assessment',pages:[4,40],words:'Use the equipment-specific guide section or a documented alternative supported by testing/engineering advice. Record the actual source and arrangement; do not borrow an unrelated equipment method.'}
];
const txt=v=>String(v==null?'':v).trim();
const positive=v=>typeof v==='number'&&Number.isFinite(v)&&v>0;
const nonnegative=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
const has=v=>typeof v==='string'&&v.trim().length>0;
const fmtSpec=g=>[g.lengthMm,g.widthMm,g.heightMm].map(v=>positive(v)?v:'?').join(' × ')+' mm · '+(positive(g.massKg)?g.massKg+' kg':'mass not stated');
const esc924=v=>txt(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ownerKey(v){const n=txt(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(!n||n==='unknown'||n==='to-confirm')return 'unknown';if(n==='coates'||n==='coates-hire')return 'coates';if(n==='event-portables'||n==='event-portable')return 'event-portables';if(n==='premair'||n==='prem-air'||n==='prem-air-hire'||n==='premair-hire')return 'prem-air-hire';return n.startsWith('other-')?'other:'+n.slice(6):'other:'+n;}
function unitId(ref,owner,nativeId,assetNo){const n=txt(nativeId),a=txt(assetNo);return n||a?JSON.stringify([txt(ref),ownerKey(owner),n?'native':'asset',n||a]):'';}
// Bounded per-document key; the full identity is retained and checked on every read/write.
function keyHash(s){let a=1779033703,b=3144134277,c=1013904242,d=2773480762;for(let i=0;i<s.length;i++){const k=s.charCodeAt(i);a=b^Math.imul(a^k,597399067);b=c^Math.imul(b^k,2869860233);c=d^Math.imul(c^k,951274213);d=a^Math.imul(d^k,2716044179);}a=Math.imul(c^(a>>>18),597399067);b=Math.imul(d^(b>>>22),2869860233);c=Math.imul(a^(c>>>17),951274213);d=Math.imul(b^(d>>>19),2716044179);return [a^b^c^d,b^a,c^a,d^a].map(n=>(n>>>0).toString(16).padStart(8,'0')).join('');}
function unitDocKey(id){return 'restraint924-unit-'+keyHash(id);}
function stateLoads(){return typeof S==='undefined'?{}:S.loads||{};}
function getDoc(id){const d=stateLoads()[unitDocKey(id)];return d&&d.kind==='restraint924-unit'&&d.unitId===id?d:null;}
function guideCandidates(words){
 const w=txt(words).toLowerCase(),kva=w.match(/\b(\d+(?:\.\d+)?)\s*kva\b/),fork=w.match(/(\d+(?:\.\d+)?)\s*t\b/);
 let out=[];
 if(kva)out=GUIDE.filter(g=>/generator/i.test(g.description)&&new RegExp('\\b'+kva[1]+'\\s*kva\\b','i').test(g.description)&&(!/trailer/.test(w)||g.page>=35&&g.page<=38));
 else if(/trailer.*toilet|toilet.*trailer|fwf.*trailer/.test(w))out=GUIDE.filter(g=>/toilet.*trailer/i.test(g.description));
 else if(/\bfwf\b|fresh.?water.*flush/.test(w))out=GUIDE.filter(g=>/fresh water flush/i.test(g.description));
 else if(/\bvms\b|variable message/.test(w))out=GUIDE.filter(g=>/variable message/i.test(g.description));
 else if(/forklift|forktruck|fortruck/.test(w)&&fork)out=GUIDE.filter(g=>/forklift|forktruck|fortruck/i.test(g.description)&&new RegExp('\\b'+fork[1]+'\\s*t\\b','i').test(g.description));
 else if(/light.*tower/.test(w))out=GUIDE.filter(g=>/lighting tower/i.test(g.description));
 else if(/trailer.*toilet|toilet.*trailer/.test(w))out=GUIDE.filter(g=>/toilet.*trailer/i.test(g.description));
 else if(/scissor|boom|excavator|roller|pump|compressor|welder/.test(w)){const term=(w.match(/scissor|boom|excavator|roller|pump|compressor|welder/)||[])[0];out=GUIDE.filter(g=>g.description.toLowerCase().includes(term));}
 const knownMake=[...new Set(GUIDE.map(g=>txt(g.make).toLowerCase()).filter(Boolean))].find(m=>w.includes(m));if(knownMake)out=out.filter(g=>txt(g.make).toLowerCase()===knownMake);
 return out;
}
function methodCandidates(words){const w=txt(words).toLowerCase();let ids=/trailer[ -]?mounted|mounted.*trailer|with trailer/.test(w)?['trailer']:/trailer.*toilet|toilet.*trailer|fwf.*trailer/.test(w)?['trailer']:/building|ticket.?box|\b(?:office|crib|lunch|change).?room/.test(w)?['building','wagon']:/toilet.?block|pan.?block|ablution/.test(w)?['building','ablution']:/\bfwf\b|portable.?toilet|fresh.?water.*flush/.test(w)?['toilet-base','toilet-blocked','toilet-frame']:/water.*barrier|triton|armorzone/.test(w)?['barrier']:/generator|\bkva\b|\bskid\b|pump|compressor|welder/.test(w)?['skid-small','skid-medium','skid-large','container']:/light.*tower|light.*cube/.test(w)?['trailer','cube']:/\bvms\b|variable.?message|trailer/.test(w)?['trailer']:/forklift|forktruck|fortruck|excavator|roller|scissor|boom/.test(w)?['mobile']:/cage|stillage/.test(w)?['cage']:['other'];return METHODS.filter(m=>ids.includes(m.id));}
function nativeUnits(a){
 if(!a||!a.key)return [];
 if(typeof root.gcUnits925==='function'){const r=root.gcUnits925(a);if(Array.isArray(r))return r.filter(u=>u&&u.physical===true&&has(u.id)).map(u=>Object.assign({},u,{ref:a.key,owner:ownerKey(u.owner)}));}
 const out=[],seen=new Set(),lines=typeof chargeLines==='function'?chargeLines(a):[],subs=typeof subOf==='function'?subOf(a.key):[],native=typeof unitsOf==='function'?unitsOf(a.key):[];
 const add=(owner,assetNo,item,label,nativeId)=>{const id=unitId(a.key,owner,nativeId,assetNo);if(!id||seen.has(id))return;seen.add(id);out.push({id,ref:a.key,owner:ownerKey(owner),assetNo:txt(assetNo),item:txt(item),label:txt(label)||txt(item),physical:true});};
 if(typeof vms913BoardsOn==='function'&&typeof vms913Of==='function')for(const b of vms913BoardsOn(a)||[]){const v=vms913Of(b);add(v.co||'unknown',v.fleet||'','VMS',b.vms||b.name,'vms:'+b.key);}
 const allowed=Array.isArray(a._bookingNumbers801)&&typeof asset873Numbers==='function'?new Set(asset873Numbers(a).map(String)):null;
 for(const l of lines){if(!l.item)continue;const nums=typeof asset873Allocated==='function'?asset873Allocated(a,l.item):[];const fallback=nums.length?nums:typeof invItemNums==='function'?invItemNums(a,l.item):[];
  for(const no0 of fallback){const no=txt(no0);if(!no||/^MISCITEM$/i.test(no)||allowed&&!allowed.has(no)||out.some(u=>u.item==='VMS'&&u.assetNo===no))continue;const matches=subs.filter(s=>txt(s.no)===no);const n=native.find(u=>txt(u.asset_no)===no);add(matches.length===1?matches[0].co:matches.length>1?'unknown':'coates',no,l.item,n&&n.label,null);}
 }
 for(const s of subs){if(!s.no||allowed&&!allowed.has(txt(s.no))||out.some(u=>u.item==='VMS'&&u.assetNo===txt(s.no)))continue;const item=s.item||(lines.length===1?lines[0].item:'');const n=native.find(u=>txt(u.asset_no)===txt(s.no));add(s.co||'unknown',s.no,item,n&&n.label,null);}
 for(const n of native){if(!n.asset_no&&!n.id&&!n._id)continue;if(allowed&&!allowed.has(txt(n.asset_no)))continue;if(out.some(u=>u.assetNo&&u.assetNo===txt(n.asset_no)))continue;add(n.owner||'unknown',n.asset_no,n.item||n.label,n.label,n.id||n._id);}
 return out;
}
function unitsFor(a){const out=nativeUnits(a);if(Array.isArray(a._bookingNumbers801))return out;const ids=new Set(out.map(u=>u.id));for(const d of Object.values(stateLoads()))if(d&&d.kind==='restraint924-unit'&&d.slot===true&&d.ref===a.key&&has(d.unitId)&&!ids.has(d.unitId)){out.push({id:d.unitId,ref:a.key,owner:d.owner,assetNo:d.assetNo||'',item:d.item,label:d.label,physical:true,slot:true});ids.add(d.unitId);}return out;}
function methodIssues(u,v,m){const out=[];if(!m)return out;const max={trailer:1850,'toilet-base':700,'toilet-blocked':700,'toilet-frame':700,cage:5000,wagon:3500,'skid-small':3300,'skid-medium':5400,'skid-large':15300,building:5000,ablution:5000,cube:1100}[m.id];if(max&&positive(v.massKg)&&v.massKg>max)out.push('actual mass exceeds the selected method’s '+max+' kg scope');if(m.id==='container'&&positive(v.massKg)&&v.massKg>=22000)out.push('containerised generator method is for sets below 22000 kg');if(m.id==='building'&&(v.lengthMm>12000||v.widthMm>3000))out.push('building exceeds the method’s 12 m × 3 m scope');if(m.id!=='other'&&!methodCandidates(u.item+' '+u.label+' '+v.model+(/trailer[ -]?mounted|mounted.*trailer/i.test(txt(v.configuration))?' trailer-mounted':'')).some(x=>x.id===m.id))out.push('selected method does not match the equipment family');if(m.id.startsWith('skid-')&&(!positive(v.baseWidthMm)||v.baseWidthMm>v.widthMm||v.heightMm>2*v.baseWidthMm))out.push('record the skid support-base width and meet the guide’s 2:1 stability limit, or document an alternative engineering assessment');if(m.id==='cube'&&!/\bsmc\b.*\bsl[ -]?80\b|\bsl[ -]?80\b.*\bsmc\b/i.test(txt(v.model)))out.push('confirm the named SMC SL80 model');if(m.id==='ablution'&&!/BAU.*sewer|16.*user.*(?:number|no\.?|#)?\s*14|event.*tank.*mount.*(?:number|no\.?|#)?\s*13/i.test(txt(v.model)))out.push('confirm a named Melbourne appendix model');return out;}
function fingerprintUnit(u){return JSON.stringify([u.id,u.ref,ownerKey(u.owner),txt(u.assetNo),txt(u.item)]);}
function editableUnit(u,doc){const d=JSON.parse(JSON.stringify(doc||{}));if(d.kind!=='restraint924-unit'||d.unitId!==u.id||d.identity!==fingerprintUnit(u)){d.actual=Object.assign({},d.actual,{verified:false});d.methodConfirmed=false;}return d;}
function actualState(u,doc){const d=doc||getDoc(u.id),v=d&&d.actual||{},issues=[];
 if(!d||d.kind!=='restraint924-unit'||d.unitId!==u.id||d.identity!==fingerprintUnit(u))issues.push('unit identity or equipment type needs confirmation');
 if(!positive(v.lengthMm)||!positive(v.widthMm)||!positive(v.heightMm))issues.push('actual transport dimensions');
 if(!positive(v.massKg))issues.push('actual transport mass including contents');
 if(!has(v.model)||!has(v.configuration)||!has(v.source))issues.push('model, transport condition and evidence');
 if(v.verified!==true||!has(v.by)||!Number.isFinite(Date.parse(v.at)))issues.push('named specification verification');
 const m=d&&METHODS.find(x=>x.id===d.methodId);if(!m)issues.push('applicable restraint method');
 if(!d||d.methodConfirmed!==true||!has(d.methodEvidence))issues.push('method applicability and evidence');
 issues.push(...methodIssues(u,v,m));return {unit:u,doc:d,actual:v,method:m||null,verified:issues.length===0,issues};}
function planKey(day,id){return 'restraint924-load-'+keyHash(JSON.stringify([day,id]));}
function planFor(day,id){const x=stateLoads()[planKey(day,id)];return x&&x.kind==='restraint924-load'&&x.day===day&&x.loadId===id?x:null;}
function scopeFingerprint(states){return JSON.stringify(states.map(s=>{const d=s.doc||{},v=s.actual||{};return [fingerprintUnit(s.unit),d.kind||'',d.unitId||'',d.identity||'',d.at||'',d.by||'',...['model','lengthMm','widthMm','heightMm','massKg','baseWidthMm','configuration','source','verified','by','at'].map(k=>v[k]??null),d.guideId||'',d.methodId||'',d.methodConfirmed===true,d.methodEvidence||'',s.verified===true];}).sort((a,b)=>a[0].localeCompare(b[0])));}
function editablePlan(states,plan){const p=JSON.parse(JSON.stringify(plan||{}));if(p.scope!==scopeFingerprint(states)){p.vehicle=Object.assign({},p.vehicle,{axleChecked:false,anchorChecked:false,restraintChecked:false});p.completeCargo=false;p.placements=(p.placements||[]).map(x=>Object.assign({},x,{rotationConfirmed:false}));}return p;}
function assess(states,plan){
 const reasons=[],v=plan&&plan.vehicle||{},rows=plan&&Array.isArray(plan.placements)?plan.placements:[],known=states.filter(s=>s.verified);let mass=known.reduce((n,s)=>n+s.actual.massKg,0),maxHeight=0;
 if(!states.length)reasons.push('No individual units identified');if(new Set(states.map(s=>s.unit.id)).size!==states.length)reasons.push('A physical unit is listed more than once');if(known.length!==states.length)reasons.push('Verify every unit’s actual transport dimensions, mass and method');
 if(!plan||plan.scope!==scopeFingerprint(states))reasons.push('Load contents or specifications changed — review this arrangement');
 if(!has(v.id)||!has(v.source)||!positive(v.deckLengthMm)||!positive(v.deckWidthMm)||!positive(v.payloadKg)||!positive(v.deckHeightMm)||!positive(v.heightLimitMm)||!nonnegative(v.extraMassKg))reasons.push('Record the actual truck, usable deck, available payload, heights and support/restraint mass');
 for(const k of ['axle','anchor','restraint'])if(v[k+'Checked']!==true||!has(v[k+'Evidence']))reasons.push('Record the '+k+' assessment for this arrangement');
 if(!has(plan&&plan.by)||!Number.isFinite(Date.parse(plan&&plan.at)))reasons.push('Name and date the load assessment');
 const boxes=[];for(const s of states){if(!s.verified)continue;const matches=rows.filter(p=>p.unitId===s.unit.id);if(matches.length!==1){reasons.push('One position required for '+s.unit.label);continue;}const p=matches[0];if(!nonnegative(p.xMm)||!nonnegative(p.yMm)||!nonnegative(p.supportMm)||![0,90].includes(p.rotation)){reasons.push('Complete position and support height for '+s.unit.label);continue;}if(p.rotation===90&&p.rotationConfirmed!==true)reasons.push('Confirm rotated transport configuration for '+s.unit.label);const l=p.rotation===90?s.actual.widthMm:s.actual.lengthMm,w=p.rotation===90?s.actual.lengthMm:s.actual.widthMm;if(p.xMm+l>v.deckLengthMm||p.yMm+w>v.deckWidthMm)reasons.push(s.unit.label+' extends outside the usable deck');if(s.method.id==='trailer'&&p.rotation===90&&(s.actual.massKg>1200||l>v.deckLengthMm||w>2500))reasons.push('Across-deck small trailers require at most 1200 kg and a retracted transport width within 2500 mm');if(s.method.id.startsWith('skid-')&&p.rotation!==0)reasons.push('Skid guide methods require longitudinal placement; use a documented alternative for other orientations');const box={id:s.unit.id,x:p.xMm,y:p.yMm,l,w,state:s};if(boxes.some(b=>box.x<b.x+b.l&&box.x+box.l>b.x&&box.y<b.y+b.w&&box.y+box.w>b.y))reasons.push('Unit envelopes overlap');boxes.push(box);maxHeight=Math.max(maxHeight,v.deckHeightMm+p.supportMm+s.actual.heightMm);}
 for(const b of boxes.filter(b=>b.state.method.id.startsWith('skid-'))){const peers=boxes.filter(o=>o!==b&&b.x<o.x+o.l&&b.x+b.l>o.x);if(!peers.length){if(b.state.method.id==='skid-medium'&&b.state.actual.massKg<3300)reasons.push('Select the single-file method for the actual skid mass range');if(Math.abs(b.y+b.w/2-v.deckWidthMm/2)>1)reasons.push('Single skid units must be central on the deck');}else{const o=peers[0],limit={'skid-small':1650,'skid-medium':2700}[b.state.method.id],v1=b.state.actual,v2=o.state.actual;if(peers.length!==1||!limit||o.state.method.id!==b.state.method.id||v1.model!==v2.model||v1.configuration!==v2.configuration||b.l!==o.l||b.w!==o.w||b.x!==o.x||v1.massKg>limit||v2.massKg>limit||Math.abs((Math.min(b.y,o.y)+Math.max(b.y+b.w,o.y+o.w))/2-v.deckWidthMm/2)>1)reasons.push('Two-abreast skids require the same unit, aligned arrangement, central loading and the guide’s per-unit mass limits');}}
 if(rows.length!==states.length||new Set(rows.map(p=>p.unitId)).size!==rows.length)reasons.push('Load position list does not match the identified units');
 if(nonnegative(v.extraMassKg))mass+=v.extraMassKg;if(positive(v.payloadKg)&&mass>v.payloadKg)reasons.push('Recorded load mass exceeds the entered available payload');if(positive(v.heightLimitMm)&&maxHeight>v.heightLimitMm)reasons.push('Recorded loaded height exceeds the entered limit');
 const geometryFits=reasons.length===0;const review='Restraint approval required: the complete guide method, rated connections, lashing geometry, friction and blocking are not automatically validated. Recorded checks and envelope/payload calculations are planning evidence, not load approval.';return {fits:false,geometryFits,restraintValidated:false,why:[...new Set(reasons),review].join(' · '),massKg:known.length===states.length&&nonnegative(v.extraMassKg)?mass:null,knownMassKg:mass,maxHeightMm:known.length===states.length&&positive(v.deckHeightMm)&&boxes.length===states.length?maxHeight:null,reasons:[...new Set(reasons)]};
}
