/* Author: Andrew Fisher. Actual numbered destination shapes; public GETs only. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),Module=require('module');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));hm._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++;(counts.denied||=[]).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const{open}=hm.exports;
const out=process.env.OUT930||'/workspace/private-markers930',pageFile=process.env.PAGE||path.join(out,'candidate.html');fs.mkdirSync(out,{recursive:true});
(async()=>{const all=[];for(const W of [1440,390]){console.log('START '+W);const s=await open({pageFile,hash:'#timeline',W,H:W===390?844:1000,mobile:W===390,gl:true}),p=s.page;try{
 await p.waitForFunction(()=>GC500Refresh904.report().settled&&SYNC.status==='live'&&window.DestinationMarkers930,null,{timeout:90000});
 const setup=await p.evaluate(()=>holdAssets(()=>{const days=programmeDays(),rank=days.map(d=>({day:d,groups:dpLoads(d).filter(g=>g.kind==='deliveries'&&g.rows.some(r=>r.a.key==='WC09'))})).filter(x=>x.groups.length).sort((a,b)=>b.groups.length-a.groups.length);const {day,groups}=rank[0];window.__marker930Record=JSON.stringify(S);window.__marker930Shapes=JSON.stringify(MasterShapes926.shape('WC09'));window.__marker930Bumps=0;window.bump=()=>{__marker930Bumps++;throw Error('Viewing marker must not save');};state.day=day.iso;state.q='';state.disc='';state.light='';state.tlView='day';go('timeline');render();return{day:day.iso,ids:groups.map(g=>ldId(day,g))};}));
 await p.locator('[data-drop911-open]').first().click();await p.waitForFunction(()=>Drops911.report().status==='ready'&&document.querySelector('.destination930-label'),null,{timeout:90000});
 await p.evaluate(id=>[...document.querySelectorAll('[data-drop911-select]')].find(b=>b.dataset.drop911Select===id).click(),setup.ids[0]);await p.locator('[data-drop911-focus]').click();await p.waitForTimeout(700);
 const first=await p.evaluate(()=>{const r=Drops911.report(),buttons=[...document.querySelectorAll('.destination930-label')];return{selected:r.selected,pins:buttons.map(b=>{const z=b.getBoundingClientRect(),c=getComputedStyle(b);return{id:b.dataset.drop911Marker,n:b.querySelector('span').textContent,refs:b.querySelector('strong').textContent,w:z.width,h:z.height,background:c.backgroundColor,selected:b.getAttribute('aria-pressed')};}),outlines:document.querySelectorAll('[data-shape926-map-ref="WC09"] .ms926-comp').length,shape:document.querySelector('[data-shape926-map-ref="WC09"] .ms926-marker')?.dataset.ms926At,overflow:document.documentElement.scrollWidth>innerWidth+1};});
 assert(first.outlines>=2);assert(!first.overflow);assert(first.pins.every(b=>b.w>=44&&b.h>=44&&b.background==='rgba(0, 0, 0, 0)'));assert.equal(first.selected,setup.ids[0]);
 const other=setup.ids[1]||setup.ids[0];await p.locator('[data-drop911-marker]').filter({hasText:'WC09'}).filter({visible:true}).evaluateAll((bs,id)=>bs.find(b=>b.dataset.drop911Marker===id)?.click(),other);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>Drops911.report().selected),other);
 assert(await p.locator('.destination930-ref').filter({hasText:'WC09'}).first().evaluate(e=>getComputedStyle(e).whiteSpace==='nowrap'));
 const wcButtons=await p.locator('.destination930-label').filter({hasText:'WC09'}).count();assert(wcButtons>=setup.ids.length);
 await p.locator('.drops911-view').screenshot({path:path.join(out,'wc09-map-'+W+'.png')});await p.locator('.drops911').screenshot({path:path.join(out,'wc09-workspace-'+W+'.png')});
 await p.locator('[data-drop911-zoom="16000"]').click();await p.waitForTimeout(400);const zoom=await p.evaluate(()=>({text:document.querySelector('[data-drop911-percent]').textContent,shapeSame:__marker930Shapes===JSON.stringify(MasterShapes926.shape('WC09')),buttons:document.querySelectorAll('.destination930-label').length}));assert(zoom.text.includes('16,000'));assert(zoom.shapeSame);await p.locator('.drops911-view').screenshot({path:path.join(out,'wc09-detail-'+W+'.png')});
 await p.locator('[data-drop911-fit]').click();await p.waitForTimeout(250);const labels=p.locator('.destination930-label');await labels.first().focus();await p.keyboard.press('Enter');const keyboard=await p.evaluate(()=>({focus:document.activeElement.classList.contains('destination930-label'),selected:document.activeElement.getAttribute('aria-pressed')}));assert(keyboard.focus&&keyboard.selected==='true');
 await p.locator('[data-drop911-close]').click();
 const dense=await p.evaluate(()=>holdAssets(()=>{const ranked=programmeDays().map(d=>({d,n:dpLoads(d).filter(g=>g.kind==='deliveries').length})).sort((a,b)=>b.n-a.n),d=ranked[0].d;state.day=d.iso;render();return{day:d.iso,count:ranked[0].n};}));await p.locator('[data-drop911-open]').first().click();await p.waitForFunction(()=>Drops911.report().status==='ready'&&document.querySelector('.destination930-label'),null,{timeout:90000});await p.locator('[data-drop911-fit]').click();await p.waitForTimeout(500);
 const denseRead=await p.evaluate(()=>{const bs=[...document.querySelectorAll('.destination930-label')],rs=bs.map(b=>b.getBoundingClientRect()),overlaps=[];for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++){const a=rs[i],b=rs[j];if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top)overlaps.push([i,j]);}return{labels:bs.length,rows:document.querySelectorAll('[data-drop911-select]').length,overlaps,recordSame:JSON.stringify(S)===__marker930Record,bumps:__marker930Bumps,overflow:document.documentElement.scrollWidth>innerWidth+1};});assert(denseRead.labels>2);assert(!denseRead.overlaps.length);assert(denseRead.recordSame&&denseRead.bumps===0&&!denseRead.overflow);await p.locator('.drops911').screenshot({path:path.join(out,'dense-workspace-'+W+'.png')});assert.equal(s.errors.length,0);assert((s.counts.denied||[]).every(r=>r.method==='POST'&&r.origin==='https://tile.googleapis.com'&&r.path==='/v1/createSession'));let wide=null;if(W===1440){await p.setViewportSize({width:3840,height:1200});await p.waitForTimeout(700);wide=await p.evaluate(()=>{const view=document.querySelector('.drops911-view'),buttons=[...view.querySelectorAll('.destination930-label')],leaders=[...view.querySelectorAll('.destination930-leader line')],items=buttons.map((b,i)=>({id:b.dataset.drop911Marker,n:+b.querySelector('.destination930-number').textContent,refs:[...b.querySelectorAll('.destination930-ref')].map(x=>x.textContent),x:+leaders[i].getAttribute('x1'),y:+leaders[i].getAttribute('y1')})),obs=view.__destination930Obstacles,t=performance.now();for(let i=0;i<50;i++)DestinationMarkers930.labels(items,view.clientWidth,view.clientHeight,obs);return{width:view.clientWidth,loads:items.length,obstacles:obs.length,meanPlanningMs:(performance.now()-t)/50,forcedGeometryReads:false};});await p.locator('.drops911').screenshot({path:path.join(out,'dense-workspace-3840.png')});}
 all.push({W,setup,first,zoom,keyboard,dense,denseRead,wide,errors:s.errors,requests:s.counts});console.log('PASS '+W);
 }finally{await s.browser.close();}}fs.writeFileSync(path.join(out,'browser930.json'),JSON.stringify(all,null,2));console.log('PASS actual desktop and phone markers');})().catch(e=>{console.error(e.stack);process.exitCode=1});
