/* Author: Andrew Fisher. Destination labels keep source positions and separate loads. */
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),A=require('../markers930.js');
let n=0;const check=(name,fn)=>{fn();console.log('PASS '+name);n++;};
const pin=(id,n,x=200,y=180,refs=['WC09'])=>({key:id+'|'+x+'|'+y,id,n,x,y,point:[.2,.3],refs,complete:true});
check('shared destination keeps every truck separately numbered',()=>{const r=A.labels([pin('a',1),pin('b',2)],700,420);assert.equal(r.length,2);assert.deepEqual(r.map(x=>[x.id,x.n]),[['a',1],['b',2]]);assert(!A.overlaps(r[0],r[1]));});
check('label offset never changes source point or anchor',()=>{const p=pin('a',1),b=JSON.stringify(p),r=A.labels([p],700,420)[0];assert.equal(JSON.stringify(p),b);assert.deepEqual(r.point,p.point);assert.equal(r.anchorX,p.x);assert.equal(r.anchorY,p.y);assert(r.x!==p.x||r.y!==p.y);});
check('real footprint stays clear when adjacent space is available',()=>{const block={x:200,y:180,w:160,h:60};const r=A.labels([pin('a',1)],700,420,[block])[0];assert(!A.overlaps(r,block,7));});
check('44 pixel hit height remains independent of visible badge',()=>{for(const refs of [['P1'],['WC09'],['P03','WC09']]){const d=A.dimensions(refs);assert(d.w>=44&&d.h>=44);}});
for(const width of [320,390,768,1440,3840])check('eleven nearby loads remain distinct at '+width,()=>{const cols=Math.max(1,Math.floor((width-106)/108)+1),height=Math.max(420,30+Math.max(0,Math.ceil(15/cols)-1)*61+55),items=Array.from({length:11},(_,i)=>pin('load'+i,i+1,width/2,190));const r=A.labels(items,width,height);for(let i=0;i<r.length;i++){assert(r[i].x-r[i].w/2>=0&&r[i].x+r[i].w/2<=width);assert(r[i].y-r[i].h/2>=0&&r[i].y+r[i].h/2<=height);for(let j=i+1;j<r.length;j++)assert(!A.overlaps(r[i],r[j]),'overlap '+i+','+j);}});
check('fourteen adjacent phone labels repack without covering another load',()=>{const items=Array.from({length:14},(_,i)=>pin('load'+i,i+1,195+(i%3)*3,190+Math.floor(i/3)*3,['P01'])),r=A.labels(items,390,420);assert(r.some(p=>p.repacked));assert(r.every(p=>!p.crowded));for(let i=0;i<r.length;i++)for(let j=i+1;j<r.length;j++)assert(!A.overlaps(r[i],r[j]));assert.deepEqual(r.map(p=>[p.anchorX,p.anchorY]),items.map(p=>[p.x,p.y]));});
check('multi-reference label retains every reference',()=>{const r=A.labels([pin('a',1,200,180,['WC09','P03'])],700,420);assert.deepEqual(r[0].refs,['WC09','P03']);});
check('many references keep a small honest caption without removing source refs',()=>{const refs=Array.from({length:24},(_,i)=>'WC'+i),p=pin('multi',1,200,180,refs),r=A.labels([p],390,420)[0];assert.deepEqual(A.caption(refs),['WC0','WC1','+22']);assert.deepEqual(r.refs,refs);assert.equal(A.dimensions(refs).h,44);});
check('full-view destination never loses load badge',()=>{const r=A.labels([pin('a',1),pin('b',2)],390,420,[{x:195,y:210,w:390,h:420}]);assert.equal(r.length,2);assert(!A.overlaps(r[0],r[1]));});
check('nonfinite obstacle cannot corrupt label coordinates',()=>{const r=A.labels([pin('a',1)],390,420,[{x:NaN,y:10,w:20,h:20}])[0];assert(Number.isFinite(r.x)&&Number.isFinite(r.y));});
check('edge anchors are preserved while controls stay inside',()=>{const r=A.labels([pin('a',1,0,0),pin('b',2,389,419)],390,420);assert.deepEqual(r.map(p=>[p.anchorX,p.anchorY]),[[0,0],[389,419]]);});
check('collision bounds keep projected rotation and door extents',()=>{const layout={components:[{poly:[[0,0],[10,10],[5,15],[-5,5]],doors:[{arcs:[[[0,0],[4,4]]],leaves:[[[0,0],[4,0]]],mid:[0,0],out:[0,-1]}]}]},before=JSON.stringify(layout),r=A.bounds(layout,{x:100,y:200});assert.deepEqual(r[0],{x:102.5,y:207.5,w:15,h:15});assert(r[1].y-r[1].h/2===180);assert.equal(JSON.stringify(layout),before);});
check('marker pan path performs no forced DOM geometry reads',()=>{const s=fs.readFileSync(path.join(__dirname,'../markers930.js'),'utf8');assert(!s.includes('getBoundingClientRect'));});
check('presentation module cannot read or mutate operational state',()=>{const s=fs.readFileSync(path.join(__dirname,'../markers930.js'),'utf8');assert(!/\b(?:S|SYNC|bump|localStorage|fetch|XMLHttpRequest|gcUnits925)\b/.test(s));});
console.log(n+' checks passed');
