// Author: Andrew Fisher. GET-only financial, partial-unit and visible charge proofs.
const fs=require('fs'),path=require('path'),Module=require('module'),assert=require('assert/strict');
const H=path.resolve(__dirname,'../../toolchain/harness'),hp=H+'/open_page.js',OUT=process.env.OUT952, snap=JSON.parse(fs.readFileSync(process.env.STATE952));assert(OUT);fs.mkdirSync(OUT,{recursive:true});
const f=require(H+'/curlfetch'),native=f.curlFetch;f.curlFetch=async(u,headers,method,body)=>{assert.equal(method,'GET');const url=new URL(u);if(['/api/state','/api/version'].includes(url.pathname))return {status:200,headers:{'content-type':'application/json'},body:Buffer.from(JSON.stringify(url.pathname==='/api/state'?snap:{version:snap.version,updated:snap.updated,level:'view'}))};return native(u,headers,method,body);};
const h=new Module(hp,module);h.filename=hp;h.paths=Module._nodeModulePaths(path.dirname(hp));h._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;'),hp);
async function run(file,label,mobile=false){const s=await h.exports.open({pageFile:file,hash:'#about',W:mobile?390:1440,H:mobile?844:900,mobile});const p=s.page;try{await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:120000});const state=await p.evaluate(()=>JSON.stringify(S));const model=await p.evaluate(()=>holdAssets(()=>({charged:allAssets().filter(a=>!a._cancelled&&!movedAway(a.key)).map(a=>({ref:a.key,lines:chargeLines(a).map(l=>({item:l.item,amount:labourMoney(a.key,l,a.key,a).total}))})),labour:labourRevenue858(),slots:labourPlan().slots})));
if(label!=='base'){
const proof=await p.evaluate(()=>{const back={labour:JSON.parse(JSON.stringify(S.labour)),by:JSON.parse(JSON.stringify(S.by)),stamps:JSON.parse(JSON.stringify(S.stamps))},oldBump=bump,oldSave=save,oldWho=whoAmI,oldMay=mayWrite;mayWrite=()=>true;bump=()=>{};save=()=>{};whoAmI=()=> 'Andrew Fisher test';try{return holdAssets(()=>{const a=assetOf('WC69'),l=chargeLines(a).find(l=>l.item==='FWF'),us=labourUnits(a,'FWF');if(us.length!==7||!us.includes(LAB_REST))throw Error('Supplier units/remainder not exposed');setLabour(a.key,l.discipline,l.item,'install',true,us[0]);const first=labourMoney(a.key,l,a.key,a).total;setLabour(a.key,l.discipline,l.item,'install',true,LAB_REST);const combined=labourMoney(a.key,l,a.key,a).total;const ticked=us.filter(u=>labourTicked(a.key,l.discipline,l.item,'install',u,a));return {first,combined,ticked: ticked.length,untickedSiblings:us.length-ticked.length};});}finally{Object.assign(S,back);bump=oldBump;save=oldSave;whoAmI=oldWho;mayWrite=oldMay;RENDER_MEMO.clear();}});
assert.deepEqual(proof,{first:36.44,combined:255.05,ticked:2,untickedSiblings:5});
await p.evaluate(()=>{window.capability=()=> 'edit';window.mayWrite=()=>false;openAsset('WC31');});await p.waitForTimeout(600);assert(await p.locator('[data-charges952="WC31"]').count());assert(await p.locator('#drawer').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.locator('[data-charges952="WC31"]').scrollIntoViewIfNeeded();await p.screenshot({path:OUT+'/'+label+'.png'});model.partialProof=proof;
}
assert.equal(await p.evaluate(()=>JSON.stringify(S)),state);assert.deepEqual(s.errors,[]);model.errors=s.errors;model.recordUnchanged=true;fs.writeFileSync(OUT+'/'+label+'.json',JSON.stringify(model,null,2));return model;
}finally{await s.browser.close();}}
(async()=>{const b=await run(process.env.BASE952,'base'),a=await run(process.env.PAGE,'candidate'),phone=await run(process.env.PAGE,'phone',true);assert.deepEqual(a.charged,b.charged);assert.equal(a.labour.recorded,b.labour.recorded);assert.equal(phone.labour.recorded,a.labour.recorded);const panels=a.slots.filter(s=>s.ref==='WC09'&&s.item==='Pee Panel');assert.equal(panels.find(s=>s.key==='install').value,874.44);assert.equal(panels.find(s=>s.key==='demob').value,874.44);assert(panels.every(s=>s.state!=='charged'));assert(!a.slots.some(s=>s.ref==='WC31'&&s.item==='Accessible Toilet'&&s.state==='charged'));const evidence={author:'Andrew Fisher',passed:true,allExistingChargedAmountsPreserved:true,locations:a.charged.length,partialUnitProof:a.partialProof,phoneNoOverflow:true,recordUnchanged:true,errors:[]};fs.writeFileSync(OUT+'/verified.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence));})().catch(e=>{console.error(e.stack);process.exit(1);});
