/* Author: Andrew Fisher. Print explicit recorded sets; never infer a pairing from number order. */
function paired879Sets(a){
 const typed=chargeLines(assetOf(a.key)||a).filter(x=>x.item),toilets=new Set(typed.filter(x=>/toilet.*block/i.test(x.item)).flatMap(x=>asset873Allocated(a,x.item))),tanks=new Set(typed.filter(x=>/waste.*tank/i.test(x.item)).flatMap(x=>asset873Allocated(a,x.item)));
 const groups=new Map();for(const u of unitsOf(a.key)||[]){const m=String(u.label||'').match(/\bSet\s+(\d+)\b/i),n=String(u.asset_no||'');if(!m||(!toilets.has(n)&&!tanks.has(n)))continue;const g=groups.get(m[1])||{set:m[1],toilets:[],tanks:[]};(toilets.has(n)?g.toilets:g.tanks).push(n);groups.set(m[1],g);}
 const sets=[...groups.values()].sort((a,b)=>Number(a.set)-Number(b.set));if(!sets.length||sets.some(g=>g.toilets.length!==1||g.tanks.length!==1)||sets.length!==toilets.size||sets.length!==tanks.size)return [];
 const booked=(a._bookingNumbers801||[]).map(String);if(!Array.isArray(a._bookingNumbers801)||!(a._bookingSource801?.loads||[]).length||a._bookingSource801.loads.length===1)return sets;return booked.length?sets.filter(g=>[...g.toilets,...g.tanks].some(n=>booked.includes(n))):sets;
}
function paired879Table(a,sets){return '<div class="paired879"><h3>'+esc(a.key)+' · '+sets.length+' toilet '+(sets.length===1?'set':'sets')+'</h3><p>'+sets.length+' toilet '+(sets.length===1?'block':'blocks')+' + '+sets.length+' waste '+(sets.length===1?'tank':'tanks')+'</p><table><thead><tr><th>Set</th><th>Equipment</th><th>Asset number</th><th>Truck loading</th></tr></thead><tbody>'+sets.map(g=>{const n=g.toilets[0],side=loading872Side(a,'u'+n);return '<tr><th rowspan="2">'+esc(g.set)+'</th><td>Toilet block</td><td><b>'+esc(n)+'</b></td><td>'+esc(side?loading872Words(side):'Door side to confirm')+'</td></tr><tr><td>Waste tank</td><td><b>'+esc(g.tanks[0])+'</b></td><td>Door side not applicable</td></tr>';}).join('')+'</tbody></table></div>';}
function paired879Cargo(r){if(!Array.isArray(r.a._bookingNumbers801))return '';const words=dpItemsWords(r);return '<p class="paired879-cargo"><b>This load: '+esc(words)+'</b><br>Paired equipment below is the reference setup; it does not add cargo to this truck.</p>'; }
const paired879Truck=dpTruck;dpTruck=function(g,doc){if(!(g.rows||[]).some(r=>paired879Sets(r.a).length))return paired879Truck(g,doc);return g.rows.map(r=>{const sets=paired879Sets(r.a);return sets.length?paired879Cargo(r)+paired879Table(r.a,sets)+(typeof handling875Sheet==='function'?handling875Sheet(r.a):''):paired879Truck(Object.assign({},g,{rows:[r]}),doc);}).join('');};
const paired879Drop=dropPage;dropPage=function(a,...args){const html=paired879Drop(a,...args),sets=paired879Sets(a);if(!sets.length)return html;const root=document.createElement('div');root.innerHTML=html;const id=root.querySelector('.rs-id');if(id){const asset=id.children[1];if(asset)asset.innerHTML='<span class="rs-l">Equipment · paired sets</span>'+paired879Table(a,sets);}root.querySelectorAll('.loading872-sheet:not(.handling875-sheet)').forEach(e=>e.remove());const fields=root.querySelectorAll('.rs-grid.four .rs-f');if(!Array.isArray(a._bookingNumbers801)&&fields[0])fields[0].innerHTML='<span class="rs-l">What</span><div class="rs-v"><b>Toilet blocks with waste tanks</b></div>';if(!Array.isArray(a._bookingNumbers801)&&fields[1])fields[1].innerHTML='<span class="rs-l">Quantity</span><div class="rs-v"><b>'+sets.length+' toilet blocks + '+sets.length+' waste tanks</b></div>';return root.innerHTML;};
