// Author: Andrew Fisher. v8.92 A+ pass: the release's markers; the once-per-draw memos give the same answers as the original
// functions; the Timeline lamps are set right after a scroll; a redraw keeps the reading position; the Transport explanation is
// folded under the figures; the words are Andrew's (Equipment, Costs & P&L, Customer rates & charges, sub-hired, oversized, Rate 1);
// contrast, tap targets and overflow at this size; every dialog and menu closes with Escape and with its × or Close; Back and deep
// links work; the slow tabs open inside their budgets; no money figure moves on a redraw; no errors, no live writes.
//   PAGE=build/GC500_v8.92/GC500_Delivery_Control_hosted.html [MOB=1] [W=2560 H=1370] [OUT=dir] node v8.92_a_plus_pass_DRAFT/tests/test_aplus892.cjs
const fs = require('fs'), {open} = require('../../toolchain/harness/open_page');
(async () => { let s; try { const MOB = !!process.env.MOB, W = MOB ? 390 : Number(process.env.W || 1440), H = MOB ? 844 : Number(process.env.H || 900), R = []; const ok = (name, pass, detail) => R.push({name, pass: !!pass, detail});
  s = await open({pageFile: process.env.PAGE, W, H, mobile: MOB, dpr: MOB ? 2 : 1}); const p = s.page; const cons = []; p.on('console', m => { if (m.type() === 'error') cons.push(m.text().slice(0, 160)); });
  await p.waitForFunction(() => typeof go === 'function' && typeof TABS !== 'undefined' && typeof SYNC !== 'undefined' && SYNC.status === 'live' && typeof transport888Core === 'function', null, {timeout: 180000}); await p.waitForTimeout(2500);
  const paint = () => p.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(() => r()))));
  const openTab = async k => { const t = await p.evaluate(k => new Promise(res => { const t0 = performance.now(); go(k); requestAnimationFrame(() => requestAnimationFrame(() => res(Math.round(performance.now() - t0)))); }), k); await p.waitForTimeout(k === 'map' ? 2000 : 500); return t; };
  /* 1. the release is in */
  const A = await p.evaluate(() => ({style: !!document.getElementById('aplus892-style'), script: !!document.getElementById('aplus892-script'), api: window.aplus892 && window.aplus892.version, footer: (document.getElementById('footL') || {}).textContent || '', coarse: matchMedia('(pointer:coarse)').matches}));
  ok('v8.92 style and script are in and the footer says v8.92', A.style && A.script && A.api === 'v8.92' && / · v8\.92\b/.test(A.footer) && !/ · v8\.(89|91|93|94)\b/.test(A.footer), A);
  /* 1b. the four decorative sweeps run on transform, not left (the last keyframes of each name is the one the page uses) */
  const KF = await p.evaluate(() => { const out = {}; for (const name of ['tw841-travel', 'tw843-sheen', 'plateGloss', 'wipSheen']) { let last = null; for (const sh of document.styleSheets) { let rules; try { rules = sh.cssRules; } catch (e) { continue; } for (const r of rules) if (r.type === CSSRule.KEYFRAMES_RULE && r.name === name) last = r; } out[name] = last ? {transform: /transform/.test(last.cssText), left: /\bleft\s*:/.test(last.cssText), frames: last.cssRules.length} : null; } return out; });
  ok('the Today travelling light, the LED sheen, the plate gloss and the toggle sheen animate transform, not left', Object.values(KF).every(k => k && k.transform && !k.left), KF);
  /* 2. the memos: one answer per draw, the same answer as the original reading */
  const M = await p.evaluate(() => { const out = {};
    out.inHold = holdAssets(() => ({ev: fin745Events() === fin745Events(), book: bookNumbers() === bookNumbers(), plan: labourPlan() === labourPlan(), idx: dropFileIndex() === dropFileIndex(), idxNull: dropFileIndex() === null}));
    out.outside = {ev: fin745Events() !== fin745Events()};
    /* docketNoInName: the original reading, written out again here, must agree on every file name the service holds and on a few shapes */
    const raw = nm => { const s = String(nm || ''); if (!s) return null; const got = bookNumbers().find(n => { const no = String(n || '').trim(); if (!/^\d{4,7}$/.test(no)) return false; if (allAssets().some(a => (a.asset_numbers || []).some(x => String(x).trim() === no))) return false; return new RegExp('(^|\\D)' + no + '(\\D|$)').test(s); }); return got ? String(got).trim() : null; };
    const names = Object.values((typeof DOCS !== 'undefined' && DOCS.files) || {}).map(f => f.name || f.id).concat(['36503.jpg', 'IMG_36503.pdf', '136503.jpg', 'photo of 1327224.jpg', 'docket 36564 signed.pdf', '', null]);
    out.names = names.length; out.agree = holdAssets(() => names.every(n => docketNoInName(n) === raw(n))); out.matched = holdAssets(() => names.filter(n => docketNoInName(n)).length);
    out.heldKeys = holdAssets(() => { docketNoInName('36503.jpg'); dropFileIndex(); fin745History('rate', 'x'); return [...HELD_MEMO.keys()].filter(k => k.startsWith('aplus892:')).length; });
    out.cleared = HELD_MEMO.size; return out; });
  ok('inside a draw each model is worked out once (file index, book numbers, labour plan, Finance events); outside a draw nothing is kept', M.inHold.ev && M.inHold.book && M.inHold.plan && M.inHold.idx && M.outside.ev && M.heldKeys >= 4 && M.cleared === 0, M);
  ok('a paper’s docket number is read exactly as before for every file name on the service (' + M.names + ' names, ' + M.matched + ' carry a number)', M.agree && M.names > 20, {agree: M.agree, names: M.names, matched: M.matched});
  /* 3. the Timeline lamps after a scroll */
  await openTab('timeline'); await p.evaluate(() => { document.querySelector('main').scrollTop = 600; }); await p.waitForTimeout(400); await paint();
  const L = await p.evaluate(() => { timeline841Motion(); const m = document.querySelector('main').getBoundingClientRect(), bottom = Math.min(innerHeight, m.bottom); const g = [...document.querySelectorAll('#pane-timeline .tl841-gantry')]; const off = motionOff();
    const want = g.map(e => { const r = e.getBoundingClientRect(); return !off && r.width > 0 && r.bottom > m.top && r.top < bottom; }), have = g.map(e => e.classList.contains('tl841-live'));
    return {gantries: g.length, agree: want.every((v, i) => v === have[i]), live: have.filter(Boolean).length, off}; });
  ok('the Timeline lamps are lit exactly for the gantries in view (' + L.live + ' of ' + L.gantries + ')', L.gantries >= 1 && L.agree, L);
  /* 4. a redraw keeps the reading position */
  const hold = async k => { await openTab(k); return p.evaluate(() => new Promise(res => { const m = document.querySelector('main'); m.scrollTop = Math.min(900, m.scrollHeight - m.clientHeight); const y0 = m.scrollTop; requestAnimationFrame(() => { render(); const y1 = m.scrollTop; requestAnimationFrame(() => requestAnimationFrame(() => setTimeout(() => res({y0, y1, y2: m.scrollTop, held: y0 > 100 && Math.abs(y1 - y0) <= 2 && Math.abs(m.scrollTop - y0) <= 2}), 350))); }); })); };
  const HD = {}; for (const k of ['timeline', 'plant', 'costs', 'fencing', 'today']) HD[k] = await hold(k);
  ok('a redraw while scrolled keeps the reading position on Timeline, Equipment, Costs, Fencing and Today', Object.values(HD).every(h => h.held), HD);
  /* 5. the Transport view: the figures lead, the explanation is folded and closed, the tie line stays */
  await openTab('costs'); await p.evaluate(() => { document.querySelector('#pane-costs [data-finance888="transport"]').click(); }); await p.waitForFunction(() => !!document.getElementById('transport888'), null, {timeout: 30000}); await p.waitForTimeout(600);
  const T = await p.evaluate(() => { const sec = document.getElementById('transport888'), how = sec.querySelector('details.tr888-how'), metrics = sec.querySelector('.tr888-metrics'), tie = sec.querySelector('.tr888-tie'), headP = sec.querySelectorAll('.fin745-heading > div > p:not(.fin745-eyebrow)').length;
    const order = how && metrics && tie ? (metrics.compareDocumentPosition(tie) & 4) && (tie.compareDocumentPosition(how) & 4) : false; const txt = sec.innerText;
    const r = {present: !!how, closed: how && !how.open, order: !!order, summary: how ? how.querySelector('summary').textContent.trim().slice(0, 40) : '', headP, tieVisible: !!tie && tie.getBoundingClientRect().height > 0 && /tie-outs/.test(tie.textContent), hiddenWords: !/To date: every schedule row/.test(txt), tied: /all tied|do not tie/.test(txt), words: {unconfirmed: /unconfirmed/.test(txt), notInPl: /Not in the P&L/.test(txt), rules: /load times at/.test(txt), author: /Author: Andrew Fisher/.test(txt), plan: /carrier plan of/.test(txt)}};
    if (how) { how.open = true; how.dispatchEvent(new Event('toggle', {bubbles: true})); r.openWords = /To date: every schedule row/.test(sec.innerText) && /Every truck movement the schedule carries/.test(sec.innerText); r.remembered = SFOLD_OPEN.has('costs765|tr888how'); how.open = false; how.dispatchEvent(new Event('toggle', {bubbles: true})); r.forgotten = !SFOLD_OPEN.has('costs765|tr888how'); }
    r.metricsTop = metrics ? Math.round(metrics.getBoundingClientRect().top) : null; r.howTop = how ? Math.round(how.getBoundingClientRect().top) : null; return r; });
  ok('Transport: the four figures come first, the tie-out line stays, and “How these figures are worked out” is a closed fold that opens, is remembered and keeps every word', T.present && T.closed && T.order && /^How these figures are worked out/.test(T.summary) && T.headP === 0 && T.tieVisible && T.hiddenWords && T.tied && T.openWords && T.remembered && T.forgotten && Object.values(T.words).every(Boolean), T);
  /* 6. the words */
  const key = await p.evaluate(() => { const a = allAssets().filter(x => !x._cancelled && (x.events || []).length); return (a.find(x => /^WC/.test(x.key)) || a[0]).key; });
  await openTab('plant'); await p.evaluate(k => openAsset(k), key); await p.waitForTimeout(700);
  const Wd = await p.evaluate(() => { const d = document.getElementById('drawer'); const r = {toPlant: (d.querySelector('#toPlant') || {}).textContent || '', drawerAmp: /&amp;/.test(d.innerText)}; if (state.drawerClose) state.drawerClose(); return r; });
  await openTab('costs'); const Wc = await p.evaluate(() => { const pane = document.getElementById('pane-costs'), t = pane.innerText; return {h2: (pane.querySelector('.hubhead h2') || {}).textContent || '', charges: /Costs & charges/.test(t), pricingTab: /Pricing tab/.test(t), subhired: /\bsubhired\b/i.test(t), oversize: /\boversize\b/i.test(t), rate1: /\brate 1\b/.test(t), amp: /&amp;/.test(t), streams: FH866_STREAMS.map(x => x[1]).slice(0, 2), registerTab: /Register tab/.test(t)}; });
  await openTab('today'); const Wt = await p.evaluate(() => { const pane = document.getElementById('pane-today'), t = pane.innerText; return {hub: (pane.querySelector('[data-go="costs"]') || {}).getAttribute ? ((pane.querySelector('[data-go="costs"]') || {}).getAttribute('title') || '') : '', charges: /Costs & charges/.test(t), amp: /&amp;/.test(t)}; });
  await openTab('plant'); const Wp = await p.evaluate(() => { const t = document.getElementById('pane-plant').innerText; return {subhired: /\bsubhired\b/i.test(t), register: /Sub-hire register/.test(t), amp: /&amp;/.test(t), rate1: /\brate 1\b/.test(t)}; });
  await openTab('demob'); const Wdm = await p.evaluate(() => { const t = document.getElementById('pane-demob').innerText; return {oversize: /\boversize\b/i.test(t), amp: /&amp;/.test(t)}; });
  ok('the words: Equipment page; Costs & P&L (not Costs & charges); Customer rates & charges (no “Pricing tab”); sub-hired (one spelling); oversized; Rate 1; Fencing/Toilets — Rehire; no stray &amp;',
     Wd.toPlant === 'Equipment page' && !Wd.drawerAmp && /^Costs & P&L — /.test(Wc.h2) && !Wc.charges && !Wc.pricingTab && !Wc.subhired && !Wc.oversize && !Wc.rate1 && !Wc.amp && !Wc.registerTab && Wc.streams.join('|') === 'Fencing — Rehire|Toilets — Rehire' && !/Costs & charges/.test(Wt.hub) && !Wt.charges && !Wt.amp && !Wp.subhired && !Wp.register && !Wp.amp && !Wp.rate1 && !Wdm.oversize && !Wdm.amp, {Wd, Wc, Wt, Wp, Wdm});
  /* 7. the look: contrast, overflow, tap targets */
  const lum = c => { const m = String(c).match(/rgba?\(([^)]+)\)/); if (!m) return null; const v = m[1].split(',').map(Number); const f = x => { x /= 255; return x <= 0.03928 ? x / 12.92 : Math.pow((x + 0.055) / 1.055, 2.4); }; return 0.2126 * f(v[0]) + 0.7152 * f(v[1]) + 0.0722 * f(v[2]); };
  const C = await p.evaluate(() => { const bg = el => { let e = el; while (e) { const c = getComputedStyle(e).backgroundColor; if (c && !/rgba\(0, 0, 0, 0\)|transparent/.test(c)) return c; e = e.parentElement; } return 'rgb(255, 255, 255)'; };
    const pick = sel => { const el = document.querySelector(sel); return el ? {fg: getComputedStyle(el).color, bg: bg(el), size: parseFloat(getComputedStyle(el).fontSize)} : null; };
    go('demob'); const demob = {ctk: pick('#pane-demob .cside .ctile .ctk'), span: pick('#pane-demob .cside .ctile span:not(.dled)'), summary: pick('#pane-demob details.dsect>summary')};
    go('today'); const today = {jump: pick('#pane-today .jb95:first-child'), hint: pick('#pane-today .maphint')}; return {demob, today}; });
  const ratio = x => x ? Math.round(((Math.max(lum(x.fg), lum(x.bg)) + 0.05) / (Math.min(lum(x.fg), lum(x.bg)) + 0.05)) * 100) / 100 : null;
  const ratios = {demobCtk: ratio(C.demob.ctk), demobSpan: ratio(C.demob.span), demobSummary: ratio(C.demob.summary), todayJump: ratio(C.today.jump), todayHint: ratio(C.today.hint)};
  ok('contrast clears WCAG AA where the audit found it short: Demob day tiles, the Demob oversized fold, Today’s jump pill and small print', Object.values(ratios).every(r => r === null || r >= 4.5) && ratios.demobCtk != null && ratios.todayJump != null, ratios);
  const OV = {}; for (const k of ['today', 'timeline', 'plant', 'demob', 'fencing', 'prestarts', 'coatesway', 'docs', 'costs', 'change', 'questions', 'about']) { await openTab(k); OV[k] = await p.evaluate(() => { const m = document.querySelector('main'); return {page: document.documentElement.scrollWidth - innerWidth, main: m.scrollWidth - m.clientWidth}; }); }
  ok('no page-wide or main-area horizontal overflow on any tab at ' + (MOB ? 'phone' : W + ' px'), Object.values(OV).every(o => o.page <= 2 && o.main <= 2), OV);
  if (MOB) { await openTab('plant'); const TT = await p.evaluate(() => { const hit = el => { const r = el.getBoundingClientRect(); const a = getComputedStyle(el, '::after'); const h = a.content !== 'none' && a.position === 'absolute' ? Math.max(r.height, parseFloat(a.height) || 0) : r.height; return {h: Math.round(h), w: Math.round(r.width)}; };
      const sample = sel => [...document.querySelectorAll(sel)].filter(e => e.getBoundingClientRect().width > 0).slice(0, 12).map(hit); const sm = sample('#pane-plant .btn.sm'), lk = sample('#pane-plant .linkish'), sums = [...document.querySelectorAll('#pane-plant summary')].filter(e => e.getBoundingClientRect().width > 0).slice(0, 12).map(e => Math.round(e.getBoundingClientRect().height));
      openAsset(allAssets().find(x => !x._cancelled && (x.events || []).length).key); const x = document.querySelector('#drawer .close'); const xr = x ? x.getBoundingClientRect() : null; if (state.drawerClose) state.drawerClose();
      return {coarse: matchMedia('(pointer:coarse)').matches, sm, lk, sums, close: xr ? {w: Math.round(xr.width), h: Math.round(xr.height)} : null}; });
    ok('phone: small buttons and links carry a 44 px tall hit area, fold headings are 44 px, the drawer × is 44 × 44', !TT.coarse || (TT.sm.every(x => x.h >= 44) && TT.lk.every(x => x.h >= 44) && TT.sums.every(h => h >= 42) && TT.close && TT.close.w >= 44 && TT.close.h >= 44), {coarse: TT.coarse, sm: TT.sm.slice(0, 3), lk: TT.lk.slice(0, 3), sums: TT.sums.slice(0, 5), close: TT.close}); }
  /* 8. every dialog and menu: Escape, then its × or Close */
  const dlg = async (name, openFn, isOpen, closeSel) => { const r = {name}; await p.evaluate(openFn); await p.waitForFunction(isOpen, null, {timeout: 6000}).catch(() => {}); await p.waitForTimeout(300); r.opened = await p.evaluate(isOpen); await p.keyboard.press('Escape'); await p.waitForTimeout(400); r.escape = !(await p.evaluate(isOpen));
    if (!r.escape) await p.evaluate(sel => { const el = document.querySelector(sel); if (el) el.click(); }, closeSel);
    await p.evaluate(openFn); await p.waitForFunction(isOpen, null, {timeout: 6000}).catch(() => {}); await p.waitForTimeout(300); r.reopened = await p.evaluate(isOpen); await p.evaluate(sel => { const el = document.querySelector(sel); if (el) el.click(); }, closeSel); await p.waitForTimeout(450); r.x = !(await p.evaluate(isOpen)); if (!r.x) await p.keyboard.press('Escape'); return r; };
  const D = [];
  await openTab('today'); D.push(await dlg('Tools menu', `document.getElementById('moreBtn').click()`, `!document.getElementById('moreMenu').hidden`, '#moreBtn'));
  D.push(await dlg('Clock pod', `document.getElementById('tpodOpen').click()`, `!document.getElementById('tpodPanel').hidden`, '#tpodOpen'));
  D.push(await dlg('Search finder', `openSearch(true); document.getElementById('q').value = 'WC1'; state.q = 'WC1'; finderOpen('WC1')`, `!document.getElementById('finder').hidden`, '#qx'));
  await p.evaluate(() => { state.q = ''; document.getElementById('q').value = ''; closeSearch({always: true}); render(); });
  D.push(await dlg('Today work dialog', `(() => { const b = document.querySelector('#pane-today [data-tw840-detail]'); if (b) b.click(); })()`, `!!document.querySelector('dialog[open]')`, 'dialog[open] [data-tw840-close]'));
  await openTab('plant'); D.push(await dlg('Reference drawer', `openAsset(${JSON.stringify(key)})`, `document.getElementById('drawer').classList.contains('on')`, '#drawer .close'));
  await openTab('timeline'); D.push(await dlg('Timeline stage dialog', `(() => { const b = document.querySelector('[data-tl841-open]'); if (b) b.click(); })()`, `!!document.querySelector('dialog[open]')`, 'dialog[open] [data-tl841-close]'));
  await openTab('coatesway'); await p.waitForFunction(() => typeof MACHINE !== 'undefined' && MACHINE.status && MACHINE.status.ready === true, null, {timeout: 20000}).catch(() => {}); D.push(await dlg('Coates Way machine', `(() => { const b = document.querySelector('#pane-coatesway .btn.primary, #pane-coatesway button[id*="achine"]'); if (b) b.click(); })()`, `!document.getElementById('machine').hidden`, '#machineClose'));
  ok('every dialog and menu opens, closes with Escape and closes with its × or Close (' + D.length + ' tried)', D.every(d => d.opened && d.escape && d.reopened && d.x), D.filter(d => !(d.opened && d.escape && d.reopened && d.x)));
  /* 9. Back and deep links */
  await openTab('plant'); await openTab('timeline'); await p.goBack().catch(() => {}); await p.waitForTimeout(1200);
  const back = await p.evaluate(() => ({pane: (document.querySelector('main .pane.on') || {}).id, hash: location.hash, backBtn: !document.getElementById('navBack').hidden}));
  await p.evaluate(() => { location.hash = '#day/2026-09-28'; }); await p.waitForTimeout(1500); const deep1 = await p.evaluate(() => ({tab: state.tab, day: state.day}));
  await p.evaluate(() => { location.hash = '#costs'; }); await p.waitForTimeout(1200); const deep2 = await p.evaluate(() => ({tab: state.tab, pane: (document.querySelector('main .pane.on') || {}).id}));
  ok('Back returns to the tab before; #day/… opens that day on the Timeline; #costs opens Costs & P&L', back.pane === 'pane-plant' && deep1.tab === 'timeline' && deep1.day === '2026-09-28' && deep2.tab === 'costs' && deep2.pane === 'pane-costs', {back, deep1, deep2});
  /* 10. speed: the slow tabs on a revisit, inside a generous budget for a shared machine */
  await openTab('today'); const tCosts = await openTab('costs'); await openTab('today'); const tFence = await openTab('fencing'); await openTab('today'); const tDocs = await openTab('docs'); await openTab('today'); const tTl = await openTab('timeline');
  ok(`speed: Costs & P&L ${tCosts} ms, Fencing ${tFence} ms, Documents ${tDocs} ms, Timeline ${tTl} ms to the painted frame (budgets 1500 / 1200 / 900 / 1200)`, tCosts <= 1500 && tFence <= 1200 && tDocs <= 900 && tTl <= 1200, {tCosts, tFence, tDocs, tTl});
  await openTab('today'); await p.evaluate(() => openSearch(true)); await p.focus('#q'); const typed = await p.evaluate(() => new Promise(res => { const P = {lt: []}; let obs; try { obs = new PerformanceObserver(l => { for (const e of l.getEntries()) P.lt.push(Math.round(e.duration)); }); obs.observe({type: 'longtask'}); } catch (e) {} window.__lt892 = {P, obs}; res(true); }));
  await p.keyboard.type('WC12', {delay: 90}); await p.waitForTimeout(900); const typing = await p.evaluate(() => { const o = window.__lt892; if (o.obs) o.obs.disconnect(); return {longTasks: o.P.lt, max: Math.max(0, ...o.P.lt), finder: !document.getElementById('finder').hidden}; }); await p.keyboard.press('Escape'); await p.waitForTimeout(300);
  ok(`search typing: the finder answers and no task over 600 ms (longest ${typing.max} ms, ${typing.longTasks.length} over 50 ms)`, typing.finder && typing.max <= 600, typing);
  /* 11. figures and the record */
  await openTab('costs'); const same = await p.evaluate(() => holdAssets(() => { const b = JSON.stringify([moneySummary(), cj764Model().job, fh866Model().costTotal, transport888View().tot, recon888Model().ties.map(t => t.ok)]); render(); return b === JSON.stringify([moneySummary(), cj764Model().job, fh866Model().costTotal, transport888View().tot, recon888Model().ties.map(t => t.ok)]); }));
  ok('a redraw changes no figure, and every reconciliation tie-out still ties', same && (await p.evaluate(() => recon888Model().ok)), {});
  if (process.env.OUT) { fs.mkdirSync(process.env.OUT, {recursive: true}); const tag = MOB ? 'phone' : String(W); await p.evaluate(() => { document.querySelector('#pane-costs [data-finance888="transport"]').click(); }); await p.waitForTimeout(900); await p.evaluate(() => { document.querySelector('main').scrollTop = 0; }); await p.screenshot({path: process.env.OUT + '/transport-fold-' + tag + '.png'});
    await openTab('demob'); await p.screenshot({path: process.env.OUT + '/demob-' + tag + '.png'}); await openTab('plant'); await p.evaluate(k => openAsset(k), key); await p.waitForTimeout(700); await p.screenshot({path: process.env.OUT + '/drawer-' + tag + '.png'}); await p.evaluate(() => state.drawerClose && state.drawerClose()); }
  ok('no page errors and no console errors', s.errors.length === 0 && cons.length === 0, {errors: s.errors.slice(0, 3), console: cons.slice(0, 3)});
  ok('no writes attempted', s.counts.blocked === 0, s.counts);
  R.forEach(r => console.log(`${r.pass ? 'PASS' : 'FAIL'}  ${r.name}${r.pass ? '' : '  ' + JSON.stringify(r.detail).replace(/\$\s?[0-9][0-9,]*(\.[0-9]+)?/g, '$—').slice(0, 900)}`));
  const fails = R.filter(r => !r.pass).length; console.log(`${MOB ? 'phone' : W + ' px'}: ${R.length - fails}/${R.length}`); process.exitCode = fails ? 1 : 0;
} finally { if (s) await s.browser.close(); } })().catch(e => { console.error('TEST FAIL', e); process.exit(2); });
