// Author: Andrew Fisher. Read-only checks for decluttered Today and equipment backgrounds.
const fs=require('fs'),path=require('path'),{open}=require('../../toolchain/harness/open_page');
const here=path.resolve(__dirname,'..'),descriptor=path.join(here,'plates907.json'),art=fs.existsSync(descriptor)?JSON.parse(fs.readFileSync(descriptor)).cells:[];
(async()=>{let s;const checks=[],ok=(name,pass,detail)=>{checks.push({name,pass:!!pass,detail});if(!pass)throw Error(name+' '+JSON.stringify(detail));};try{
 const W=Number(process.env.W||1440),phone=W===390,H=phone?844:1440,out=process.env.OUT||'/tmp/gc500-907';fs.mkdirSync(out,{recursive:true});
 s=await open({pageFile:process.env.PAGE,hash:'#today',W,H,mobile:phone,dpr:1});const p=s.page,blocked=[],consoleErrors=[];p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource|ERR_FAILED|net::/.test(m.text()))consoleErrors.push(m.text());});
 await p.route('**/*',r=>{if(r.request().method()==='GET')return r.fallback();const u=new URL(r.request().url());blocked.push({host:u.hostname,path:u.pathname});return r.abort();});
 for(const c of art)await p.route(new RegExp('/m/Coates-GC500-2026/'+c.file+'(?:\\?.*)?$'),r=>r.fulfill({status:200,contentType:c.type,body:fs.readFileSync(path.join(here,'assets',c.file))}));
 await p.waitForFunction(()=>typeof TodayPlates907==='object'&&SYNC.status==='live'&&todayWorkHealth840().ready,null,{timeout:150000});
 await p.evaluate(shas=>{go('today');for(const sha of shas)DATA.media[sha]+='?v907='+Date.now();document.getElementById('scene896-atlas')?.remove();Scene896.mount();TodayPlates907.mount();},art.map(c=>c.sha256));await p.waitForTimeout(2400);
 const scroll=async sel=>{await p.evaluate(sel=>{const e=document.querySelector(sel),m=document.querySelector('main');const inset=sel.startsWith('#tw840-card-')?(document.querySelector('.tw840-nav')?.getBoundingClientRect().height||0)+20:12;m.scrollTop+=e.getBoundingClientRect().top-m.getBoundingClientRect().top-inset;},sel);await p.waitForTimeout(200);};
 await scroll('#where885');await p.screenshot({path:path.join(out,'hero-'+W+'.png')});
 const initial=await p.evaluate(()=>{
  const visible=e=>{const r=e.getBoundingClientRect();return r.width>1&&r.height>1&&getComputedStyle(e).display!=='none';};
  const cards=[...document.querySelectorAll('#gc500-work-board840 .tw848-card')];
  return{hiddenHeroChips:getComputedStyle(document.querySelector('.w885-groups')).display==='none',navs:[...document.querySelectorAll('nav[aria-label="Work categories"]')].filter(visible).length,navItems:document.querySelectorAll('.tw840-nav [data-tw840-jump]').length,
   open:cards.every(c=>c.querySelector('[data-tw848-group-fold]').open),folds:TodayPlates907.report(),stats:document.querySelector('.p907-programme > summary .pstats')?.innerText,statsVisible:visible(document.querySelector('.p907-programme > summary .pstats')),
   model:progress881Model(todayWorkDay841()),cards:cards.map(c=>({id:c.dataset.tw840Area,title:c.querySelector('.tw846-title')?.textContent,notes:[...c.querySelectorAll('[data-tw847-headline-qualifier]')].map(e=>e.textContent),buttons:c.querySelectorAll('[data-tw840-detail]').length,background:getComputedStyle(c.querySelector('.tw846-summary'),'::before').backgroundImage,opacity:parseFloat(getComputedStyle(c.querySelector('.tw846-summary'),'::before').opacity)})),overflow:document.documentElement.scrollWidth>innerWidth+1};
 });
 ok('one category jump bar and no duplicated mini percentage strip',initial.hiddenHeroChips&&initial.navs===1&&initial.navItems===7,initial);
 ok('seven existing group plates stay open with their controls and headings',initial.open&&initial.cards.length===7&&initial.cards.every(c=>c.title&&c.buttons>=3),initial.cards);
 ok('programme countdown remains visible once with a single details disclosure',initial.folds.folds===1&&initial.folds.stats===1&&initial.statsVisible&&!initial.folds.programmeOpen&&!!initial.stats,initial.folds);
 ok('all category backgrounds are present behind the readings',initial.cards.every(c=>/url\(/.test(c.background)&&c.opacity>=.8),initial.cards);
 ok('no viewport overflow',!initial.overflow);
 if(phone){const headers=await p.evaluate(()=>[...document.querySelectorAll('#gc500-work-board840 .tw848-card')].map(c=>{const scope=c.querySelector('.tw840-scope'),r=scope.getBoundingClientRect(),style=getComputedStyle(scope),close=c.querySelector('.tw848-group-toggle').getBoundingClientRect();return{id:c.dataset.tw840Area,hidden:style.display==='none',width:scope.parentElement.getBoundingClientRect().width,cardWidth:c.getBoundingClientRect().width,lines:r.height/parseFloat(style.lineHeight),separate:r.bottom<=close.top+1};}));ok('phone scopes use the full card width above the compact controls',headers.every(h=>h.hidden||(h.width>h.cardWidth*.6&&h.lines<=3&&h.separate)),headers);}
 await p.locator('.p907-programme > summary').click();await p.waitForTimeout(100);
 ok('programme disclosure reveals timeline, dates and milestone without copying stats',await p.evaluate(()=>document.querySelector('.p907-programme').open&&document.querySelector('.p907-body .pkeys').getBoundingClientRect().height>0&&document.querySelectorAll('#where885 .pstats').length===1));
 await p.evaluate(()=>renderToday());await scroll('#where885');ok('redraw preserves the opened programme once',await p.evaluate(()=>document.querySelector('.p907-programme').open&&TodayPlates907.report().folds===1&&TodayPlates907.report().stats===1));
 await p.locator('.p907-programme > summary').click();await p.waitForTimeout(100);await p.evaluate(()=>renderToday());
 ok('redraw preserves the closed programme with visible stats',await p.evaluate(()=>!document.querySelector('.p907-programme').open&&document.querySelector('.p907-programme > summary .pstats').getBoundingClientRect().height>0));
 await scroll('#gc500-work-board840');await p.screenshot({path:path.join(out,'cards-'+W+'.png')});
 const geometry=[];for(const id of ['buildings','toilets','fencing','generators','lighting','vms','equipment']){
  await p.locator('[data-tw840-jump="'+id+'"]').click();await p.waitForTimeout(650);
  const g=await p.evaluate(id=>{const card=document.getElementById('tw840-card-'+id),r=card.getBoundingClientRect(),main=document.querySelector('main').getBoundingClientRect(),fold=card.querySelector('[data-tw848-group-fold]');const excess=[...card.querySelectorAll('*')].filter(e=>{const q=e.getBoundingClientRect();return q.width>1&&!e.classList.contains('tw840-sr')&&!e.closest('.tw848-group[open] > .tw848-group-toggle .tw848-toggle-title')&&(q.left<r.left-2||q.right>r.right+2);}).map(e=>({tag:e.tagName,cls:e.getAttribute('class'),html:e.outerHTML.slice(0,220)}));return{id,open:fold.open,inView:r.top<main.bottom&&r.bottom>main.top,excess,width:r.width,height:r.height};},id);geometry.push(g);
  if(['generators','fencing','toilets'].includes(id))await p.screenshot({path:path.join(out,id+'-'+W+'.png')});
 }
 ok('every category remains reachable and fits its card',geometry.every(g=>g.open&&g.inView&&!g.excess.length),geometry);
 await scroll('#tw840-card-generators');await p.locator('#tw840-card-generators .tw848-group-toggle').click();await p.waitForTimeout(100);const closed=await p.evaluate(()=>{const c=document.getElementById('tw840-card-generators'),f=c.querySelector('[data-tw848-group-fold]'),n=c.querySelector('.tw848-toggle-title'),r=n.getBoundingClientRect();return !f.open&&r.width>10&&r.height>10&&getComputedStyle(n).clipPath==='none'&&n.textContent.includes('Generators');});ok('closing a group reveals its category name and compact summary',closed);await p.locator('#tw840-card-generators .tw848-group-toggle').click();await p.waitForTimeout(100);await p.locator('#tw840-card-generators [data-tw840-detail="generators"][data-tw840-mode="done"]').click();await p.waitForTimeout(150);
 ok('Review still opens its native detail dialog',await p.locator('#gc500-work-dialog840').evaluate(e=>e.open));await p.locator('#gc500-work-dialog840 [data-tw840-close]').click();
 await p.locator('#tw840-card-generators [data-tw841-group-card] > summary').click();ok('source detail and methodology remain available',await p.locator('#tw840-card-generators [data-tw841-group-card]').evaluate(e=>e.open));
 const stale=await p.evaluate(()=>{const f=document.querySelector('#tw840-card-generators .tw840-footer'),keep=f.lastElementChild.textContent;f.lastElementChild.textContent='Last received';TodayPlates907.mount();const visible=getComputedStyle(f).display!=='none';f.lastElementChild.textContent=keep;TodayPlates907.mount();return visible;});ok('stale record status is never hidden as a redundant footer',stale);
 if(art.length){const decoded=await p.evaluate(shas=>Promise.all(shas.map(sha=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve({sha,width:i.naturalWidth,height:i.naturalHeight});i.onerror=()=>resolve({sha,error:true});i.src=DATA.media[sha];}))),art.map(c=>c.sha256));ok('all eight final images decode',decoded.length===8&&decoded.every(d=>d.width>0&&!d.error),decoded);}
 const print=await p.evaluate(async()=>{const before=document.querySelector('.p907-programme').open;dispatchEvent(new Event('beforeprint'));const during=document.querySelector('.p907-programme').open;dispatchEvent(new Event('afterprint'));await new Promise(r=>requestAnimationFrame(r));return{before,during,after:document.querySelector('.p907-programme').open};});ok('printing includes programme details and restores the screen fold',print.during&&print.after===print.before,print);
 await scroll('#where885');await p.locator('#w885-motion').click();ok('native overall Pause still stops animated weather',await p.evaluate(()=>Scene896.report().paused&&!Scene896.report().running));await p.locator('#w885-motion').click();
 ok('no page errors, console errors or record-write attempts',!s.errors.length&&!consoleErrors.length&&!blocked.some(b=>b.host!=='tile.googleapis.com')&&!s.counts.blocked,{page:s.errors,console:consoleErrors,blocked,counts:s.counts});
 fs.writeFileSync(path.join(out,'result-'+W+'.json'),JSON.stringify({checks,geometry,initial},null,2));console.log('PASS '+checks.length+'/'+checks.length+' Today plate checks at '+W);
 }catch(e){console.error(e.stack);process.exitCode=1;}finally{if(s)await s.browser.close();}})();
