/* Author: Andrew Fisher. Physical-unit identity and supplier views; native money, work and photo records stay authoritative. */
(function(){
'use strict';
const kind='unit925-record',prefix='unit925/',selected=new Map();
const esc925=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const trim=v=>String(v==null?'':v).trim();
function owner925(value){const s=trim(value).toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(!s||s==='unknown')return 'unknown';if(s==='coates'||s==='coates-hire')return 'coates';if(/^event-portables?$/.test(s)||s==='ep')return 'event-portables';if(/^(prem-air|premair)(-hire)?$/.test(s))return 'prem-air-hire';return s.startsWith('other-')?'other:'+s.slice(6):'other:'+s;}
function company925(owner){return {'coates':'Coates','event-portables':'Event Portables','prem-air-hire':'PremAir Hire','unknown':'Owner to confirm'}[owner]||owner.replace(/^other:/,'').split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');}
function identity925(ref,owner,nativeId,assetNo,helper){const make=helper||(typeof transportUnitId924==='function'&&transportUnitId924);return make?make(ref,owner,nativeId,assetNo):'';}
function sourceKey925(ref,owner,assetNo,label){return JSON.stringify([ref,owner,assetNo?'asset':'label',assetNo||label]);}
function metadata925(loads){return Object.entries(loads||{}).filter(([k,v])=>k.startsWith(prefix)&&v&&v.kind===kind).map(([key,v])=>Object.assign({docKey:key},v));}
function sourceUnits925(a,env){
 const found=[],seen=new Set(),numbers=env.numbers(a).map(String),knownNumbers=(env.coatesNumbers?env.coatesNumbers(a):numbers).map(String),items=env.items(a),raw=env.units(a.key);
 const add=(u,coates)=>{
  const assetNo=trim(u.asset_no||u.assetNo),supplier=/^sub[- ]?hire\s*:\s*(.+?)(?:\s*·\s*unit\s+\d+)?$/i.exec(trim(u.label));
  const owner=owner925(u.owner||u.company||u.supplier||(supplier&&supplier[1])||(coates?'Coates':''));
  const nativeId=trim(u.nativeId||u.unit_id||u.id),key=nativeId?JSON.stringify([a.key,owner,'native',nativeId]):sourceKey925(a.key,owner,assetNo,trim(u.label));if(seen.has(key))return;seen.add(key);
  let item=trim(u.item||u.description);
  if(!item&&assetNo)item=env.itemOf(a,assetNo)||'';
  if(!item&&supplier&&items.length===1)item=items[0];
  if(!item&&!supplier&&trim(u.label))item=trim(u.label);
  if(!item&&a.key==='WC31'&&owner==='event-portables'&&assetNo==='12')item='16Pan Block';
  const id=identity925(a.key,owner,nativeId,assetNo,env.identity);
  const loading=assetNo&&env.loading(a).find(r=>String(r.no)===assetNo&&(!item||r.item===item));
  const removed=!!assetNo&&!!(env.removed&&env.removed(a,assetNo)),conflict=a.key==='WC20'&&((assetNo==='1327228'&&!/toilet.*block/i.test(item))||(assetNo==='1311341'&&!/waste.*tank/i.test(item)));
  found.push({id,ref:a.key,owner,assetNo,nativeId,label:trim(u.label)||item||a.name||'Recorded unit',item,sourceKey:key,source:'native',physical:!!id&&!conflict&&!removed,identityReview:removed?'Asset number was taken off this reference':conflict?'Asset type conflicts with Andrew’s correction':!id?'Identify this physical unit':'' ,sourceToken:JSON.stringify({assetNo,owner,item,label:trim(u.label)}),loadingId:loading?loading.id:'',branch:u.branch||'',contractBranch:u.branch||'',registration:u.registration||'',raw:u});
 };
 const boards=env.vms?env.vms(a):[],vmsNumbers=new Set(boards.flatMap(u=>[u.asset_no,u.sourceAssetNo]).filter(Boolean).map(String));
 boards.forEach(u=>add(u,u.owner==='coates'));
 raw.filter(u=>!vmsNumbers.has(String(u.asset_no||''))).forEach(u=>add(u,knownNumbers.includes(String(u.asset_no||''))&&!/^sub[- ]?hire\s*:/i.test(trim(u.label))));
 numbers.forEach(no=>{if(!vmsNumbers.has(no)&&!found.some(u=>u.assetNo===no))add({asset_no:no,item:env.itemOf(a,no)||(items.length===1?items[0]:''),label:env.itemOf(a,no)||a.name||'Coates unit'},true);});
 return found;
}
function restraintSlots925(a,loads,identity){const out=[];for(const [key,d] of Object.entries(loads||{})){if(!d||d.kind!=='restraint924-unit'||d.slot!==true||d.ref!==a.key)continue;let parts;try{parts=JSON.parse(d.unitId);}catch(e){continue;}if(!Array.isArray(parts)||parts.length!==4||parts[0]!==a.key||parts[2]!=='native'||!String(parts[3]).startsWith('slot:'))continue;const owner=owner925(d.owner),nativeId=parts[3],assetNo=trim(d.assetNo),id=identity925(a.key,owner,nativeId,assetNo,identity);if(id!==d.unitId)continue;out.push({id,ref:a.key,owner,nativeId,assetNo,label:trim(d.label)||trim(d.item),item:trim(d.item),physical:true,slot:true,source:'restraint',restraintDocKey:key,loadingId:''});}return out;}
function model925(a,env){
 const native=sourceUnits925(a,env),docs=metadata925(env.loads).filter(d=>d.ref===a.key),claimed=new Set(),rows=[];
 native.forEach(base=>{
  const matches=docs.filter(d=>d.sourceKey===base.sourceKey&&d.active!==false);
  if(matches.length!==1){rows.push(Object.assign({},base,matches.length>1?{physical:false,identityReview:'More than one unit identity matches this record'}:{}));return;}
  const d=matches[0];claimed.add(d.docKey);
  const unchanged=(!base.assetNo||base.assetNo===d.assetNo)&&(base.owner==='unknown'||base.owner===d.owner)&&(!d.sourceSnapshot||d.sourceSnapshot===base.sourceToken);
  const id=identity925(a.key,base.owner==='unknown'?d.owner:base.owner,base.id?(base.nativeId||''):d.nativeId,d.assetNo,env.identity),review=base.identityReview==='Identify this physical unit'?'':base.identityReview;
  rows.push(Object.assign({},base,d,{id:unchanged?id:'',physical:unchanged&&!!id&&!review,identityReview:unchanged?review:'Original unit details changed; review this identification',metadata:d,raw:base.raw,sourceToken:base.sourceToken,source:'native'}));
 });
 docs.filter(d=>!claimed.has(d.docKey)).forEach(d=>{
  if(d.sourceKey){rows.push(Object.assign({},d,{id:d.transportId||'',physical:false,identityReview:'Original unit is no longer on the current record',metadata:d,source:'history'}));return;}
  const id=identity925(a.key,owner925(d.owner),d.nativeId,d.assetNo,env.identity);
  rows.push(Object.assign({},d,{id,physical:d.active!==false&&!!id,metadata:d,source:d.active===false?'history':'identified',identityReview:d.active===false?'Unit identification archived':''}));
 });
 restraintSlots925(a,env.loads,env.identity).forEach(u=>{if(!rows.some(r=>r.id===u.id))rows.push(u);});
 const duplicates=new Map(),fleets=new Map();rows.filter(r=>r.physical).forEach(r=>{duplicates.set(r.id,(duplicates.get(r.id)||0)+1);if(r.assetNo){const k=JSON.stringify([r.owner,r.assetNo]);fleets.set(k,(fleets.get(k)||0)+1);}});
 rows.forEach(r=>{if(r.physical&&(duplicates.get(r.id)>1||(r.assetNo&&fleets.get(JSON.stringify([r.owner,r.assetNo]))>1))){r.physical=false;r.identityReview='Duplicate physical identity; check the unit records';}});
 const groups=env.lines(a).map(l=>{const quantity=env.qty(l),units=rows.filter(u=>u.item===l.item&&u.source!=='history');return {item:l.item,quantity,units,pending:quantity==null?null:Math.max(0,quantity-units.filter(u=>u.physical).length)};});
 const other=rows.filter(r=>!groups.some(g=>g.item===r.item));if(other.length)groups.push({item:'Description to confirm',quantity:null,units:other,pending:null});
 return {ref:a.key,rows,groups};
}
function nativeEnv925(){return {units:r=>{const rows=unitsOf(r),extras=subOf(r).filter(s=>s.source754).map(s=>s.u);return rows.concat(extras);},numbers:a=>buildingNumbersOf(a),coatesNumbers:a=>assetNumbersOf(a),removed:(a,n)=>typeof tombedHere==='function'&&tombedHere('num/'+a.key+'/'+n),items:a=>chargeLines(a).map(l=>l.item).filter(Boolean),itemOf:(a,n)=>{const typed=typeof itemNumbersOf==='function'?itemNumbersOf(a):null;return typed&&Object.keys(typed).find(item=>(typed[item]||[]).map(String).includes(String(n)))||numberItemOf(a,n);},loading:a=>loading872Rows(a),lines:a=>chargeLines(a).filter(l=>l.item),qty:l=>qtyOf(l),loads:S.loads||{},identity:typeof transportUnitId924==='function'?transportUnitId924:null,vms:a=>{if(typeof vms913BoardsOn!=='function'||typeof vms913Of!=='function')return [];return (vms913BoardsOn(a)||[]).map(b=>{const v=vms913Of(b);return {label:b.vms||b.name,item:'VMS',nativeId:'vms:'+b.key,asset_no:v.fleet||'',sourceAssetNo:b.asset||'',owner:owner925(v.co),branch:b.branch||'',registration:v.rego||''};});}};}
function gcModel925(a){return model925(a,nativeEnv925());}
function physical925(a,rows){const booked=Array.isArray(a._bookingNumbers801)?new Set(a._bookingNumbers801.map(String)):null;return a._cancelled?[]:rows.filter(r=>r.physical&&(!booked||booked.has(r.assetNo)));}
function gcUnits925(a){if(movedAway(a.key))return [];return physical925(a,gcModel925(a).rows).map(r=>({id:r.id,ref:r.ref,owner:r.owner,assetNo:r.assetNo,label:r.label,item:r.item,nativeId:r.nativeId||'',loadingId:r.loadingId||'',physical:true,slot:!!r.slot,source:r.source,branch:r.branch||r.contractBranch||'',registration:r.registration||'',docKey:r.docKey||''}));}
function photos925(unit,rows,photos){const duplicates=rows.filter(r=>r.assetNo&&r.assetNo===unit.assetNo).length;return photos.filter(p=>p.unit&&(p.unit===unit.id||(unit.assetNo&&duplicates===1&&String(p.unit)===unit.assetNo)));}
function workEvidence925(u,rows,lines,ticks,key,eligible){
 const unique=!!u.assetNo&&rows.filter(r=>r.assetNo===u.assetNo).length===1,per=eligible&&unique;
 const evidence=lines.map(l=>{const explicit=per&&!!ticks[key(l.key,true)]&&!!l.ticked;return Object.assign({},l,{ticked:!!explicit,descriptionTicked:!!l.ticked&&!explicit,evidence:explicit?'unit':l.ticked?'description':'not recorded'});});
 return {scope:evidence.some(l=>l.descriptionTicked)?'description':per?'unit':'unknown',lines:evidence};
}
function work925(a,u,model){
 if(!u.item||!u.physical)return {scope:'unknown',lines:[]};
 const us=labourUnits(a,u.item),per=!!u.assetNo&&us.includes(u.assetNo),l=chargeLines(a).find(x=>x.item===u.item);if(!l)return {scope:'unknown',lines:[]};
 const info=labourLinesFor(a.key,l.discipline,u.item,a.key,per?u.assetNo:undefined,a);
 return workEvidence925(u,model.rows,info.lines||[],S.labour||{},(line,unit)=>labourKey(a.key,l.discipline,u.item,line,unit?u.assetNo:undefined),per);
}
function branch925(a,u){if(u.contractBranch)return {code:u.contractBranch,basis:'VMS contract branch'};if(u.branch)return {code:u.branch,basis:'Unit record'};const b=branchOf(a.key);return b?{code:b.code,basis:b.via==='asset number'?'Contract asset match':'Reference branch'}:{code:'Not recorded',basis:''};}
function token925(value){return JSON.stringify(value||null);}
function validate925(ref,input,existing,env){
 if(!env.isRef(ref))return {ok:false,reason:'Reference not found.'};
 const owner=owner925(input.owner),assetNo=trim(input.assetNo).replace(/\s+/g,''),item=trim(input.item),label=trim(input.label),branch=trim(input.branch).toUpperCase();
 if(!item||(!env.items.includes(item)&&!(existing&&existing.item===item)))return {ok:false,reason:'Choose a description from this reference.'};
 if(!label&&!assetNo)return {ok:false,reason:'Give this physical unit a name or number.'};
 if(assetNo&&!/^[A-Za-z0-9-]{1,24}$/.test(assetNo))return {ok:false,reason:'Use the unit’s own asset or fleet number.'};
 if(owner==='unknown')return {ok:false,reason:'Confirm who owns this unit before recording its identity.'};
 if(branch&&!/^[A-Z0-9-]{2,16}$/.test(branch))return {ok:false,reason:'Check the costing branch.'};
 if(existing&&existing.sourceKey&&((existing.assetNo&&existing.assetNo!==assetNo)||(existing.owner!=='unknown'&&existing.owner!==owner)))return {ok:false,reason:'Correct this number or owner in the original unit record first. Its work and photos will remain linked.'};
 const duplicate=env.rows.find(r=>r.physical&&assetNo&&r.assetNo===assetNo&&r.owner===owner&&!(existing&&existing.docKey&&r.docKey===existing.docKey)&&!(input.sourceKey&&r.sourceKey===input.sourceKey));
 if(duplicate)return {ok:false,reason:'That company and fleet number already identify a unit here.'};
 return {ok:true,values:{ref,owner,assetNo,item,label:label||item,branch,note:trim(input.note)}};
}
function save925(ref,input,docKey,expected,sourceToken){
 if(!mayWrite('unit identification'))return {ok:false,reason:'This link can view units but cannot edit them.'};
 const who=whoAmI();if(!who)return {ok:false,reason:'Choose the name recording this change.'};
 const a=assetOf(ref);if(!a||a._cancelled||movedAway(ref))return {ok:false,reason:'This reference is not active.'};
 const doc=docKey&&(S.loads||{})[docKey],model=gcModel925(a),existing=doc?Object.assign({docKey},doc):null;
 if(token925(doc)!==expected)return {ok:false,reason:'This unit changed on another device. Reopen it before saving.'};
 const source=input.sourceKey&&model.rows.find(u=>u.sourceKey===input.sourceKey);
 if(input.sourceKey&&(!source||source.sourceToken!==sourceToken))return {ok:false,reason:'The original unit changed. Reopen it before saving.'};
 const checked=validate925(ref,input,existing||source,{isRef,items:chargeLines(a).map(l=>l.item),rows:model.rows});if(!checked.ok)return checked;
 const uuid=existing&&existing.uuid||crypto.randomUUID(),key=docKey||prefix+uuid;
 const nativeId=source&&source.id?(source.nativeId||''):existing&&existing.nativeId||'slot:'+uuid;
 const transportId=identity925(ref,checked.values.owner,nativeId,checked.values.assetNo);
 if(!transportId)return {ok:false,reason:'This unit identity could not be confirmed.'};
 const next=Object.assign({},existing||{},checked.values,{kind,uuid,nativeId,transportId,sourceKey:input.sourceKey||'',sourceSnapshot:source&&source.sourceToken||'',active:true,by:who,at:new Date().toISOString()});delete next.docKey;
 S.loads=S.loads||{};S.loads[key]=next;stampIt('loads',key,who);bump();
 const kept=bump.kept!==false;return {ok:true,kept,id:transportId,key,reason:kept?'Unit identification recorded.':'The change is still on this device; the page’s save warning shows what needs attention.'};
}
function descriptionItems925(items,u){return [...new Set(items.filter(Boolean).concat(u&&u.item?[u.item]:[]))];}
function form925(a,u){
 const existing=u&&u.metadata,source=u&&u.source==='native'?u:null,owner=u?u.owner:'unknown';
 const companies=[...new Set(['unknown','coates','event-portables','prem-air-hire',owner].concat(subCompanies().map(owner925)))];
 return '<form class="units925-form" data-unit925-form data-ref="'+esc925(a.key)+'" data-doc="'+esc925(existing&&existing.docKey||'')+'" data-expected="'+esc925(token925(existing?Object.fromEntries(Object.entries(existing).filter(([k])=>k!=='docKey')):null))+'" data-source="'+esc925(source&&source.sourceKey||'')+'" data-source-token="'+esc925(source?source.sourceToken:'')+'"><div class="units925-fields"><label>Description<select name="item">'+descriptionItems925(chargeLines(a).map(l=>l.item),u).map(item=>'<option'+((u?u.item:selected.get(a.key))===item?' selected':'')+'>'+esc925(item)+'</option>').join('')+'</select></label><label>Owning company<select name="owner">'+companies.map(c=>'<option value="'+esc925(c)+'"'+(owner===c?' selected':'')+'>'+esc925(company925(c))+'</option>').join('')+'</select></label><label>Asset / fleet number<input name="assetNo" value="'+esc925(u&&u.assetNo||'')+'" maxlength="24"></label><label>Name on site<input name="label" value="'+esc925(u&&u.label||'')+'" maxlength="120" placeholder="Name marked on this unit"></label><label>Costing branch<input name="branch" value="'+esc925(u&&u.branch||'')+'" maxlength="16" placeholder="Not yet assigned"></label><label>Evidence / note<input name="note" value="'+esc925(u&&u.note||'')+'" maxlength="300"></label></div><p class="units925-note">Identifies this unit. Delivery counts, labour and charges are kept in their existing records.</p><button type="submit" class="btn primary">Save unit details</button><p class="units925-result" data-unit925-result role="status"></p></form>';
}
function rowHtml925(a,u,model){
 const photos=photos925(u,model.rows,dropPhotosOf(a.key)),work=work925(a,u,model),branch=branch925(a,u);
 const lines=work.lines.map(l=>'<span class="units925-work'+(l.ticked?' done':'')+'">'+esc925(l.name)+(l.ticked?' ✓':l.descriptionTicked?' · description record':'')+'</span>').join('');
 const owned=u.owner==='coates';
 return '<details class="units925-unit" data-unit925-id="'+esc925(u.id||'')+'"><summary><span><b>'+esc925(u.assetNo||u.label)+'</b><small>'+esc925(company925(u.owner))+'</small></span><span>'+esc925(u.item||'Description to confirm')+'</span></summary><div class="units925-body">'+(u.identityReview?'<p class="units925-warning">'+esc925(u.identityReview)+'</p>':'')+'<dl><div><dt>'+(owned?'Coates asset':'Supplier fleet')+'</dt><dd>'+esc925(u.assetNo||'Not recorded')+'</dd></div><div><dt>Costing branch</dt><dd>'+esc925(branch.code)+'<small>'+esc925(branch.basis)+'</small></dd></div><div><dt>Ownership</dt><dd>'+esc925(company925(u.owner))+'</dd></div><div><dt>Cost allocation</dt><dd>'+(owned?'Coates fleet':'Quote / unit match to confirm')+'</dd></div></dl><p class="units925-note">'+esc925(u.label)+'</p><h4>Photos for this unit</h4>'+(photos.length?'<div class="units925-photos">'+photos.map(ph=>{const r=photoFor(ph);return r.state==='ready'?'<img src="'+esc925(r.thumb||r.url)+'" alt="Photo assigned to '+esc925(u.assetNo||u.label)+'" loading="lazy">':'<span class="units925-note">Photo unavailable · '+esc925(ph.id)+'</span>';}).join('')+'</div>':'<p class="units925-note">No photos assigned to this unit.</p>')+(u.registration?'<p class="units925-note">Registration: '+esc925(u.registration)+'</p>':'')+'<h4>Work record</h4>'+(lines?'<div class="units925-worklist">'+lines+'</div><p class="units925-note">'+(work.scope==='unit'?'Recorded against this asset.':'Description records do not confirm completion of this individual unit.')+'</p>':'<p class="units925-note">No priced individual work record for this unit.</p>')+(u.loadingId?'<p class="units925-note">Loading door side: '+esc925(loading872Side(a,u.loadingId)||'To confirm')+'</p>':'')+(!SYNC.readonly&&u.source!=='restraint'?'<details class="units925-edit"><summary>Edit unit details</summary>'+form925(a,u)+'</details>':'')+'</div></details>';
}
function panel925(a){
 const model=gcModel925(a);if(!model.groups.length)return '';
 const choice=model.groups.some(g=>g.item===selected.get(a.key))?selected.get(a.key):model.groups[0].item;selected.set(a.key,choice);
 const g=model.groups.find(g=>g.item===choice),photos=dropPhotosOf(a.key),assigned=new Set(model.rows.flatMap(u=>photos925(u,model.rows,photos)).map(p=>p.id)),unassigned=photos.filter(p=>!assigned.has(p.id));
 return '<section class="card units925" data-units925="'+esc925(a.key)+'"><p class="units925-save-status" role="status"></p><div class="units925-title"><h3>Units at this location</h3><span>'+model.rows.filter(r=>r.physical).length+' identified</span></div><label class="units925-description">Description<select data-ro data-unit925-description>'+model.groups.map(x=>'<option'+(x.item===choice?' selected':'')+'>'+esc925(x.item)+'</option>').join('')+'</select></label><p class="units925-note">'+g.units.filter(u=>u.physical).length+' identified'+(g.quantity==null?'':' · '+g.quantity+' planned')+'</p>'+g.units.map(u=>rowHtml925(a,u,model)).join('')+(g.pending?'<p class="units925-warning">'+g.pending+' planned unit'+(g.pending===1?'':'s')+' still need'+(g.pending===1?'s':'')+' an individual identity.</p>':'')+(a.key==='WC31'&&g.item==='Accessible Toilet'&&!model.rows.some(u=>u.assetNo==='1317645')?'<p class="units925-note">Andrew reported Coates asset 1317645. It is not yet on the shared unit record.</p>':'')+(a.key==='WC31'&&g.item==='16Pan Block'?'<p class="units925-note">The current Q6845 quote covers one 16-pan block. Coverage for the second block remains to confirm.</p>':'')+(unassigned.length?'<details class="units925-edit"><summary>Location / unassigned photos · '+unassigned.length+'</summary><p class="units925-note">These remain at their original location until assigned to the correct unit.</p><div class="units925-photos">'+unassigned.map(ph=>{const r=photoFor(ph);return r.state==='ready'?'<img src="'+esc925(r.thumb||r.url)+'" alt="Location photo, not assigned to this unit" loading="lazy">':'<span>Photo unavailable</span>';}).join('')+'</div></details>':'')+(!SYNC.readonly?'<details class="units925-edit"><summary>Identify another physical unit</summary>'+form925(a,null)+'</details>':'')+'</section>';
}
function mount925(a){const drawer=document.getElementById('drawer'),body=drawer&&drawer.querySelector('.db');if(!body)return;body.querySelectorAll('.units925').forEach(e=>e.remove());const html=panel925(a);if(!html)return;const summary=body.querySelector(':scope > .sum816');if(summary)summary.insertAdjacentHTML('afterend',html);else body.insertAdjacentHTML('afterbegin',html);}
function companyModel925(){
 const assets=allAssets().filter(a=>!a._cancelled&&!movedAway(a.key)),companies=new Map();
 assets.forEach(a=>gcModel925(a).rows.forEach(u=>{if(u.owner==='coates'||/advanced.*fenc/i.test(company925(u.owner)))return;let c=companies.get(u.owner);if(!c){c={owner:u.owner,name:company925(u.owner),units:[]};companies.set(u.owner,c);}c.units.push(Object.assign({name:a.name},u));}));
 subCompanies().concat(typeof allCosts==='function'?allCosts().filter(c=>c.kind==='subhire').map(c=>c.supplier).filter(Boolean):[]).forEach(name=>{const owner=owner925(name);if(owner!=='coates'&&!/advanced.*fenc/i.test(name)&&!companies.has(owner))companies.set(owner,{owner,name,units:[]});});
 return [...companies.values()].sort((a,b)=>a.name.localeCompare(b.name));
}
let companyChoice925='event-portables';
function quoteFile925(q,index,url){const id=q.quote+'_2.pdf',f=index&&index.state==='ready'&&index.files&&index.files[id];if(!index||index.state==='loading'||index.state==='unrequested')return {state:'checking',id};if(index.state==='failed')return {state:'unchecked',id};if(!f)return {state:'missing',id};if(!q.sha256||f.sha256!==q.sha256)return {state:'mismatch',id};return {state:'ready',id,url:url(id)};}
function original925(q){const f=quoteFile925(q,photoIndex(),id=>SYNC.backend&&SYNC.backend.fileUrl?SYNC.backend.fileUrl(id):null);return f.state==='ready'&&f.url?'<a class="btn" href="'+esc925(f.url)+'" target="_blank" rel="noopener">Open original '+esc925(q.quote)+'</a>':'<span class="units925-note">'+esc925(f.state==='checking'?'Checking original PDF availability…':f.state==='unchecked'?'Original PDF availability could not be checked.':f.state==='mismatch'?'Original PDF needs source verification.':'Original PDF is not currently in Documents.')+'</span>';}
function quote925(q){const scope={Q6844:'Servicing: cleaning, pump-outs and water truck',Q6845:'Equipment hire: quoted quantities; one 16-pan block',Q6846:'Water deliveries and drinking-water tank · 6 weeks',Q6847:'Pitlane party: trailer hire, separate staff labour'}[q.quote]||q.delivery_to||'Supplier quote';return '<details class="units925-edit"><summary>'+esc925(q.quote)+' · '+esc925(scope)+'</summary><p class="units925-note">Original PDF reviewed · 28 Jul 2026 · approved by Andrew, final total may change.</p>'+((q.groups||[]).flatMap(g=>g.lines||[])).map(l=>'<div class="units925-quote"><b>'+esc925(l.qty)+' ×</b><span>'+esc925(l.description)+(l.period?' · '+esc925(l.period):'')+'<small>'+esc925(l.unit_price_is||l.note||'Quoted unit rate: '+money(l.unit_price)+' ex GST')+'</small></span><span>'+esc925(money(l.total_price))+' ex GST</span></div>').join('')+['delivery_charge','pickup'].filter(k=>q[k]!=null).map(k=>'<div class="units925-quote"><b>'+esc925(k==='pickup'?'Pickup':'Delivery')+'</b><span>Already included in this quote total</span><span>'+esc925(money(q[k]))+' ex GST</span></div>').join('')+'<p class="units925-note"><b>'+esc925(money((q.sub_total||0)+(q.delivery_charge||0)+(q.pickup||0)))+' ex GST</b> · unit allocation remains to confirm.</p><p class="units925-note">'+original925(q)+'</p></details>'; }
function companyHtml925(){const all=companyModel925();if(!all.some(c=>c.owner===companyChoice925))companyChoice925=all[0]&&all[0].owner||'';const company=all.find(c=>c.owner===companyChoice925),quotes=companyChoice925==='event-portables'&&DATA.rehire_quotes&&DATA.rehire_quotes.quotes||[],plans=companyChoice925==='event-portables'?[['WC09',['FWF','Pee Panel']],['WC31',['16Pan Block']]].flatMap(([ref,items])=>{const a=assetOf(ref);return a&&!a._cancelled&&!movedAway(ref)?gcModel925(a).groups.filter(g=>items.includes(g.item)&&g.pending>0).map(g=>({ref,item:g.item,pending:g.pending})):[];}):[];
 return '<section class="card units925 units925-companies" data-unit925-companies><div class="units925-title"><h3>Sub-hire companies</h3><button type="button" class="btn" data-unit925-fencing>Fencing</button></div><label class="units925-description">Company<select data-ro data-unit925-company>'+all.map(c=>'<option value="'+esc925(c.owner)+'"'+(c.owner===companyChoice925?' selected':'')+'>'+esc925(c.name)+'</option>').join('')+'</select></label>'+(company?'<p class="units925-note">'+company.units.filter(u=>u.physical).length+' individually identified units · owner and costing branch are recorded separately.</p><div class="units925-company-list">'+company.units.map(u=>'<button type="button" class="units925-company-unit" data-unit925-open="'+esc925(u.ref)+'" data-unit925-item="'+esc925(u.item||'')+'" data-unit925-target="'+esc925(u.id||'')+'"><span><b>'+esc925(u.ref)+' · '+esc925(u.assetNo||u.label)+'</b><small>'+esc925(u.item||'Description to confirm')+'</small></span><span>'+esc925(u.identityReview||u.name||'Open unit')+' →</span></button>').join('')+'</div>':'')+(plans.length?'<details class="units925-edit"><summary>Planned units awaiting identity · '+plans.reduce((n,x)=>n+x.pending,0)+'</summary>'+plans.map(x=>'<button type="button" class="units925-company-unit" data-unit925-open="'+esc925(x.ref)+'" data-unit925-item="'+esc925(x.item)+'"><span><b>'+esc925(x.ref)+' · '+esc925(x.item)+'</b></span><span>'+x.pending+' to identify →</span></button>').join('')+'</details>':'')+(quotes.length?'<details class="units925-edit"><summary>Approved quotes & costs</summary><p class="units925-note">Original quotes dated 28 Jul 2026. Quote totals are unchanged. Supplier delivery and pickup stay with each quote; unit coverage must be confirmed.</p>'+quotes.map(quote925).join('')+'</details>':'<p class="units925-note">Supplier costs remain in the existing Costs records until their unit allocation is confirmed.</p>')+'<p class="units925-note"><button type="button" class="btn" data-unit925-costs>Open Costs</button> <button type="button" class="btn" data-unit925-documents>Original documents</button></p></section>';
}
const api={owner:owner925,company:company925,identity:identity925,sourceKey:sourceKey925,metadata:metadata925,sourceUnits:sourceUnits925,model:model925,physical:physical925,restraintSlots:restraintSlots925,workEvidence:workEvidence925,quoteFile:quoteFile925,photos:photos925,validate:validate925,descriptionItems:descriptionItems925,token:token925};
if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof window!=='undefined'){window.Units925=api;window.gcUnits925=gcUnits925;window.gcModel925=gcModel925;window.unit925Save=save925;}
if(typeof openAssetDraw!=='function'||typeof renderAbout!=='function')return;
const beforeDraw925=openAssetDraw;openAssetDraw=function(a,key,keep){const result=beforeDraw925(a,key,keep);mount925(a);return result;};
const beforeAbout925=renderAbout;renderAbout=function(){const result=beforeAbout925();const pane=document.getElementById('pane-about');if(pane){pane.querySelectorAll('[data-unit925-companies]').forEach(e=>e.remove());const head=pane.firstElementChild;head?head.insertAdjacentHTML('afterend',companyHtml925()):pane.insertAdjacentHTML('afterbegin',companyHtml925());}return result;};
document.addEventListener('change',e=>{if(e.target.matches('[data-unit925-description]')){const panel=e.target.closest('[data-units925]');selected.set(panel.dataset.units925,e.target.value);const a=assetOf(panel.dataset.units925);panel.outerHTML=panel925(a);document.querySelector('[data-units925="'+CSS.escape(a.key)+'"] [data-unit925-description]')?.focus();}else if(e.target.matches('[data-unit925-company]')){companyChoice925=e.target.value;e.target.closest('[data-unit925-companies]').outerHTML=companyHtml925();document.querySelector('[data-unit925-company]')?.focus();}});
document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('[data-unit925-open],[data-unit925-fencing],[data-unit925-costs],[data-unit925-documents]');if(!b)return;e.preventDefault();if(b.hasAttribute('data-unit925-open')){const ref=b.dataset.unit925Open;if(b.dataset.unit925Item)selected.set(ref,b.dataset.unit925Item);openAsset(ref);if(b.dataset.unit925Target){const target=[...document.querySelectorAll('[data-unit925-id]')].find(el=>el.dataset.unit925Id===b.dataset.unit925Target);if(target){target.open=true;target.scrollIntoView({block:'center'});}}}else if(b.hasAttribute('data-unit925-costs'))go('costs');else if(b.hasAttribute('data-unit925-documents'))go('docs');else go('fencing');});
document.addEventListener('submit',e=>{const form=e.target.closest&&e.target.closest('[data-unit925-form]');if(!form)return;e.preventDefault();const input=Object.fromEntries(new FormData(form));input.sourceKey=form.dataset.source;const ref=form.dataset.ref,result=save925(ref,input,form.dataset.doc,form.dataset.expected,form.dataset.sourceToken);const target=[...document.querySelectorAll('[data-unit925-form]')].find(f=>f.dataset.ref===ref&&(result.key?f.dataset.doc===result.key:f.dataset.doc===form.dataset.doc&&f.dataset.source===form.dataset.source));const current=(target||form).querySelector('[data-unit925-result]');if(current)current.textContent=result.reason;if(result.ok){const msg=document.querySelector('[data-units925="'+CSS.escape(ref)+'"] .units925-save-status');if(msg)msg.textContent=result.reason;}});
})();
