// Author: Andrew Fisher. Deterministic scheduler/visibility/clock and fallback tests without WebGL writes.
const assert=require('assert/strict'),{create}=require('./startup971');let passed=0;
function test(name,fn){try{fn();passed++;}catch(e){e.message=name+': '+e.message;throw e;}}
function fixture(){
 const log=[],queue=new Map();let next=1,hidden=false,open=true,time=0;
 const flat={style:{visibility:'hidden'},isConnected:true},cv={style:{visibility:''},isConnected:true,parentNode:{querySelectorAll:()=>[flat]}},cap={textContent:'Circuit credit'};
 const S={gl:{isContextLost:()=>false},cv,capEl:cap,clock:47,last:12,accum:.06,bloom:true,architecture781Source:[1],vegetation781Source:[1],dayTrees:{},quality:{name:'high'},creditNow:()=> 'Circuit credit'};
 const G={S,fullLap788:{enabled:true},camStep:n=>log.push(['camera',n])};
 S.unmount=function(quiet){log.push(['unmount',quiet,this===S]);G.S=null;return 'released';};
 const c=create(G,{raf:f=>{const id=next++;queue.set(id,f);return id;},cancel:id=>queue.delete(id),now:()=>++time,hidden:()=>hidden,open:()=>open});
 function fail(s,e){log.push(['failure',e.message]);s.fullLapFailed788=e.message;s.detail781Enabled=false;}
 function ensure(s){if(!G.fullLap788.enabled||s.fullLapFailed788||s.bloom===false){s.detail781Enabled=false;return;}s.detail781Enabled=true;for(const name of c.required(s)){log.push(['upload',name]);s[name==='track'?'trackDetail781':name==='architecture'?'architecture781':'vegetation781']={};if(name==='vegetation')s.dayTrees={};return;}}
 G.render=()=>{if(!S.dayTrees.visibility918){log.push(['visibility-upload']);S.dayTrees.visibility918=true;}if(!c.prepare(S,ensure,fail))return;return c.draw(S,()=>{log.push(['draw']);return 'drawn';});};
 function step(){const [id,f]=queue.entries().next().value||[];assert(f,'callback exists');queue.delete(id);f();}
 return {S,G,c,log,queue,flat,cv,cap,step,ensure,fail,hidden:v=>hidden=v,open:v=>open=v};
}
test('one stage per queued pass and no partial heavy draw',()=>{const f=fixture();f.G.render();assert.deepEqual(f.log.filter(x=>x[0]==='upload'),[['upload','track']]);assert(!f.log.some(x=>x[0]==='draw'));assert.equal(f.queue.size,1);f.step();f.step();assert.equal(f.log.filter(x=>x[0]==='upload').length,3);assert(!f.log.some(x=>x[0]==='draw'));f.step();assert.equal(f.log.filter(x=>x[0]==='draw').length,1);assert.equal(f.queue.size,0);});
test('replacement tree visibility upload precedes first draw',()=>{const f=fixture();f.G.render();f.step();f.step();f.step();const firstDraw=f.log.findIndex(x=>x[0]==='draw'),uploads=f.log.map((x,i)=>[x,i]).filter(([x])=>/upload/.test(x[0]));assert(uploads.every(([,i])=>i<firstDraw));assert.equal(uploads.filter(([x])=>x[0]==='visibility-upload').length,2);});
test('calls while queued cannot duplicate installers or callbacks',()=>{const f=fixture();f.G.render();for(let i=0;i<20;i++)f.G.render();assert.equal(f.queue.size,1);assert.equal(f.log.filter(x=>x[0]==='upload').length,1);});
test('flat fallback stays visible until first prepared render',()=>{const f=fixture();f.G.render();assert.equal(f.cv.style.visibility,'hidden');assert.equal(f.flat.style.visibility,'');assert.match(f.cap.textContent,/Preparing circuit/);f.step();f.step();assert.equal(f.cv.style.visibility,'hidden');f.step();assert.equal(f.cv.style.visibility,'');assert.equal(f.flat.style.visibility,'hidden');assert.equal(f.cap.textContent,'Circuit credit');assert(f.c.report().shown);});
test('preparation holds elapsed baseline without changing clock or seek',()=>{const f=fixture();let native=0;f.c.frame(()=>native++);assert.equal(native,0);assert.equal(f.S.clock,47);assert.equal(f.S.last,null);assert.equal(f.S.accum,0);f.S.clock=125;f.step();f.step();f.step();assert.equal(f.S.clock,125);f.c.frame(()=>native++);assert.equal(native,1);assert.deepEqual(f.S.quality,{name:'high'});});
test('paused initial scene completes through queued stages',()=>{const f=fixture();f.S.paused=true;f.c.frame(()=>{throw Error('simulation must remain paused');});f.step();f.step();f.step();assert(f.c.report().shown);assert.equal(f.S.paused,true);assert.equal(f.S.clock,47);});
test('hidden preparation stops without allocating or drawing',()=>{const f=fixture();f.G.render();f.hidden(true);const n=f.log.length;f.step();assert.equal(f.log.length,n);assert.equal(f.queue.size,0);assert.equal(f.S.needsRender,true);f.hidden(false);f.G.render();f.step();f.step();assert(f.c.report().shown);});
test('closed and disconnected scenes defer without new uploads',()=>{for(const mode of ['closed','disconnected']){const f=fixture();if(mode==='closed')f.open(false);else f.cv.isConnected=false;assert.equal(f.c.prepare(f.S,f.ensure,f.fail),false);assert.equal(f.log.length,0);assert.equal(f.queue.size,0);}});
test('unmount before the next hidden frame cancels pending callback immediately',()=>{const f=fixture();f.G.render();const wrapper=f.S.unmount;assert.equal(f.queue.size,1);f.G.render();assert.equal(f.S.unmount,wrapper);f.hidden(true);f.open(false);assert.equal(f.S.unmount(true),'released');assert.equal(f.queue.size,0);assert.deepEqual(f.log.at(-1),['unmount',true,true]);assert.equal(f.G.S,null);f.G.S=f.S;assert.equal(f.c.report(),null);assert.equal(f.log.filter(x=>x[0]==='draw').length,0);});
test('replaced and lost scenes cannot use stale callbacks',()=>{for(const mode of ['replaced','lost']){const f=fixture();f.G.render();const n=f.log.length;if(mode==='replaced')f.G.S={};else f.S.lost=true;f.step();assert.equal(f.log.length,n);assert.equal(f.queue.size,0);assert.equal(f.cv.style.visibility,'hidden');}});
test('empty optional sources do not prevent readiness',()=>{const f=fixture();f.S.architecture781Source=[];f.S.vegetation781Source=[];f.G.render();f.step();assert.deepEqual(f.log.filter(x=>x[0]==='upload'),[['upload','track']]);assert(f.c.report().shown);});
test('manual disabled detail and composite fallback remain selected',()=>{for(const mode of ['disabled','composite']){const f=fixture();if(mode==='disabled')f.G.fullLap788.enabled=false;else f.S.bloom=false;f.G.render();assert.equal(f.log.filter(x=>x[0]==='draw').length,1);assert.equal(f.queue.size,0);assert.equal(f.c.report(),null);}});
test('no progress uses existing failure fallback instead of looping',()=>{const f=fixture();assert.equal(f.c.prepare(f.S,()=>{},f.fail),false);assert.match(f.S.fullLapFailed788,/preparation did not complete/);f.step();assert(f.c.report().shown);assert.equal(f.queue.size,0);});
test('failed draw does not expose an unpainted canvas',()=>{const f=fixture();f.G.render();f.step();f.step();assert.throws(()=>f.c.draw(f.S,()=>{throw Error('draw failed');}));assert.equal(f.cv.style.visibility,'hidden');assert.equal(f.flat.style.visibility,'');});
test('manual detail disabled mid-preparation clears queued work safely',()=>{const f=fixture();f.G.render();f.G.fullLap788.enabled=false;f.step();assert.equal(f.log.filter(x=>x[0]==='upload').length,1);assert(f.c.report().shown);assert.equal(f.S.bloom,true);});
console.log(JSON.stringify({author:'Andrew Fisher',passed,writes:0}));
