// Author: Andrew Fisher. Compact-row UI checks use semantic hooks, not the former mini-card layout.
'use strict';
const path=require('node:path');
const {close844,readDialog844}=require('../v8.44_linked_completion_LIVE/test_linked_ui844.cjs');
const {same,finite}=require('./test_compact_model846.cjs');
const fmt=n=>finite(n)?n.toLocaleString('en-AU',{maximumFractionDigits:2}):'—';
const percent=(n,kind)=>finite(n)?(kind==='lower-bound'?'≥':'')+fmt(kind==='lower-bound'?Math.floor((Math.min(100,n)+1e-9)*100)/100:Math.min(100,n))+'%':'—';
async function settle(p){await p.evaluate(()=>document.fonts.ready);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function reveal(p,selector){await p.locator(selector).evaluate(node=>{const main=document.querySelector('main'),nav=document.querySelector('.tw840-nav');main.scrollTop+=node.getBoundingClientRect().top-main.getBoundingClientRect().top-(nav?.getBoundingClientRect().height||0)-18;});await settle(p);}
async function platformFont(p,selector){const s=await p.context().newCDPSession(p);try{await s.send('DOM.enable');await s.send('CSS.enable');const {root}=await s.send('DOM.getDocument');const {nodeId}=await s.send('DOM.querySelector',{nodeId:root.nodeId,selector});return (await s.send('CSS.getPlatformFontsForNode',{nodeId})).fonts;}finally{await s.detach();}}
async function board846(p){return p.evaluate(()=>{
 const b=document.querySelector('#gc500-work-board840'),m=document.querySelector('main'),rect=e=>e?.getBoundingClientRect().toJSON(),style=e=>{const s=getComputedStyle(e);return {font:s.fontFamily,size:parseFloat(s.fontSize),weight:s.fontWeight,fontStyle:s.fontStyle,filter:s.filter,shadow:s.textShadow,transform:s.transform,color:s.color,display:s.display};};
 return {report:TodayWork840.report(),horizontal:document.documentElement.scrollWidth>innerWidth+1||m.scrollWidth>m.clientWidth+1,oldMini:b.querySelectorAll('.tw843-type-instrument,.tw843-type-gauge,[data-tw841-type]').length,ids:[...b.querySelectorAll('[id]')].map(n=>n.id),cards:[...b.querySelectorAll('[data-tw840-area]')].map(c=>({id:c.dataset.tw840Area,title:c.querySelector('.tw846-title')?.textContent,scope:c.querySelector('.tw840-scope')?.textContent,titleCount:c.querySelectorAll('.tw846-title').length,displayCount:c.querySelectorAll('.tw846-display').length,percent:c.querySelector('.tw840-reading')?.textContent.replace(/\s/g,''),counts:Object.fromEntries([...c.querySelectorAll('[data-tw842-quantity]')].map(n=>[n.dataset.tw842Quantity,n.textContent])),lamps:c.querySelectorAll('.tw846-lights .tl841-lamp').length,lit:c.querySelectorAll('.tw846-lights .tl841-lamp.is-on').length,green:c.querySelectorAll('.tw846-lights .tl841-lamp.is-on.is-finished').length,sweeps:c.querySelectorAll('.race-sweep-window').length,complete:c.querySelector('.tw846-display')?.dataset.complete,overflow:c.scrollWidth>c.clientWidth+1,heading:{rect:rect(c.querySelector('.tw846-title')),style:style(c.querySelector('.tw846-title'))},rows:[...c.querySelectorAll('.tw846-type-row')].map(r=>({id:r.dataset.tw843TypeId,kind:r.dataset.tw843Kind,fenceId:r.dataset.tw840FenceRow,family:r.closest('[data-tw843-family]')?.dataset.tw843Family,name:r.querySelector('.tw846-type-name')?.textContent,note:[...r.querySelectorAll('.tw846-row-note')].map(n=>n.textContent).join(' '),pctKind:r.querySelector('[data-pct-kind]')?.dataset.pctKind,counts:Object.fromEntries([...r.querySelectorAll('.tw846-qty')].map(n=>[n.dataset.tw843TypeMode||n.dataset.tw842FenceValue,n.querySelector('strong')?.textContent])),overflow:r.scrollWidth>r.clientWidth+1,nameStyle:style(r.querySelector('.tw846-type-name')),controls:[...r.querySelectorAll('.tw846-qty')].map(n=>({rect:rect(n),style:style(n),scroll:n.scrollWidth,client:n.clientWidth})),plan:r.querySelector('[data-tw842-fence-plan]')?.textContent,provisional:r.querySelector('[data-tw842-fence-plan]')?.dataset.provisional}))}))};});}
function assertBoard846(check,label,shown,e){
 check(label+' six group housings replace all duplicate mini-instruments and type tables',same(shown.cards.map(c=>c.id),e.areas.map(a=>a.id))&&shown.cards.every(c=>c.titleCount===1&&c.displayCount===(c.id==='fencing'?0:1))&&shown.oldMini===0&&new Set(shown.ids).size===shown.ids.length,shown.cards.map(c=>({id:c.id,displayCount:c.displayCount,rows:c.rows.length})));
 for(const card of shown.cards){const area=e.areas.find(a=>a.id===card.id),s=e.summary.byId[card.id],types=e.types.byCard[card.id],complete=s.pctKind==='confirmed'&&finite(s.total)&&s.total>0&&s.pct===100&&!s.reviewRefs.length&&!s.unquantifiedRefs,lit=complete?5:finite(s.pct)?Math.min(4,Math.floor(Math.max(0,s.pct)/20)):0;
  check(label+' '+card.id+' headline and race lamps preserve their explicit source scope',card.title===area.name&&card.scope===(card.id==='fencing'?'Recorded Build work':area.scope)&&(card.id==='fencing'?card.lamps===0:card.percent===percent(s.pct,s.pctKind)&&['total','done','left'].every(k=>card.counts[k]===fmt(s[k]))&&card.lamps===5&&card.lit===lit&&card.green===(complete?5:0)&&card.sweeps===lit&&card.complete===String(complete)),{summary:s,shown:card});
  check(label+' '+card.id+' every type has one compact row with exact counts and qualification',same(card.rows.map(r=>r.id),types.map(t=>t.id))&&types.every(t=>{const r=card.rows.find(r=>r.id===t.id);return ['total','done','left'].every(k=>r.counts[k]===fmt(t[k]))&&(t.kind==='asset-type'?r.name===t.name&&r.family===t.groupId&&r.pctKind===t.pctKind&&r.note.includes(finite(t.pct)?percent(t.pct,t.pctKind).replace('≥','≥ '):'unconfirmed')&&(!t.scopeNote||r.note.includes(t.scopeNote))&&(!t.reviewQuantity||r.note.includes('need review')):r.fenceId===t.fenceId&&r.note.includes(t.unit)&&r.plan.includes(t.plan.label)&&r.provisional===String(!!t.plan.provisional));}),{expected:types,shown:card.rows});
 }
 check(label+' compact names and controls fit without clipping or blurred text',!shown.horizontal&&shown.cards.every(c=>!c.overflow&&c.heading.style.font.includes('Inter')&&c.heading.style.fontStyle==='normal'&&c.heading.style.filter==='none'&&c.heading.style.shadow==='none'&&c.rows.every(r=>!r.overflow&&r.nameStyle.font.includes('Inter')&&r.nameStyle.size>=14&&r.nameStyle.filter==='none'&&r.nameStyle.shadow==='none'&&r.controls.every(n=>n.rect.width>=43&&n.rect.height>=43&&n.scroll<=n.client+1&&n.style.size>=18))),shown.cards.map(c=>({id:c.id,overflow:c.overflow,heading:c.heading,rows:c.rows.map(r=>({id:r.id,overflow:r.overflow,nameStyle:r.nameStyle,controls:r.controls}))})));
}
async function capture846(p,view,out){for(const id of ['toilets','fencing','equipment']){await p.locator('[data-tw840-jump='+id+']').click();await settle(p);await p.screenshot({path:path.join(out,'compact846-'+view+'-'+id+'-main.png')});if(id!=='fencing'){await reveal(p,'[data-tw840-area='+id+'] .tw846-types');await p.screenshot({path:path.join(out,'compact846-'+view+'-'+id+'-types.png')});}}}
async function openType846(p,id,mode){await p.locator('.tw846-qty[data-tw843-type-detail='+JSON.stringify(id)+'][data-tw843-type-mode='+mode+']').click();await p.waitForFunction(({id,mode})=>{const d=document.querySelector('#gc500-work-dialog840');return d?.open&&d.querySelector('[data-tw843-detail-id]')?.dataset.tw843DetailId===id&&d.querySelector('[data-tw843-detail-mode]')?.dataset.tw843DetailMode===mode;},{id,mode});}
async function details846(p,check,label,e,all,out){const assets=e.types.instruments.filter(t=>t.kind==='asset-type'),samples=all?assets:assets.filter((t,i)=>i===0||t.pctKind==='lower-bound'||t.total==null||/tank/i.test(t.name)||t===assets.find(x=>x.cardId===t.cardId));
 for(const t of samples){const modes=all||t===samples[0]||t.pctKind==='lower-bound'||t.total==null?['left','total','done']:['left'];const results=[];for(const mode of modes){await openType846(p,t.id,mode);const before=await p.evaluate(()=>({token:document.querySelector('#gc500-work-dialog840')?.open,main:document.querySelector('main').scrollTop})),d=await readDialog844(p),rows=t.rows.filter(r=>mode==='total'||(mode==='done'?r.complete||finite(r.done)&&r.done>0:!r.complete||!finite(r.left)||r.left>0)),links=e.byType.find(x=>x.id===t.id).linked.rowsByKey;
  const ok=same(d.rows.map(r=>r.key),rows.map(r=>r.key))&&d.subtitle.startsWith(fmt(t[mode])+' ')&&d.subtitle.includes('across '+rows.length+' references')&&d.rows.every((r,i)=>r.value===fmt(rows[i][mode==='total'?'quantity':mode])&&r.current?.includes(links[r.key].current.label)&&r.destination?.includes(links[r.key].destination.text)&&r.actions.every(a=>a.key===r.key))&&d.text.includes(t.plan.basis)&&d.text.includes('Native schedule total')&&d.text.includes('On site / on hire')&&d.scroll<=d.client+1&&d.rows.every(r=>!r.overflow);
  if(mode==='left'&&t.pctKind==='lower-bound')await p.screenshot({path:path.join(out,'compact846-'+label+'-review-detail.png')});await close844(p);await p.waitForFunction(token=>document.activeElement?.dataset.tw840Focus===token,'type-'+t.id+'-'+mode);const after=await p.locator('main').evaluate(n=>n.scrollTop);results.push({mode,ok,focusRestored:true,scrollBefore:before.main,scrollAfter:after,referenceCount:rows.length,shown:d.rows.map(r=>({key:r.key,value:r.value,current:r.current})),total:d.subtitle});}
  check(label+' '+t.groupId+' / '+t.name+' compact count links preserve exact reference scope and return focus',results.every(r=>r.ok&&Math.abs(r.scrollAfter-r.scrollBefore)<=2),results);
 }
 const f=e.summary.fencingRows.find(x=>finite(x.done)&&x.done>0)||e.summary.fencingRows[0];await p.locator('[data-tw840-fence-row='+JSON.stringify(f.id)+'] .tw846-qty').first().click();await p.waitForFunction(()=>document.querySelector('#gc500-work-dialog840')?.open);const fence=await p.locator('#gc500-work-dialog840').evaluate(d=>({text:d.textContent,values:[...d.querySelectorAll('.tw841-fence-totals dd')].map(n=>n.childNodes[0]?.textContent),scroll:d.scrollWidth,client:d.clientWidth}));check(label+' compact Fencing opens separate Build quantities and provenance',same(fence.values,[fmt(f.total),fmt(f.done),fmt(f.left)])&&fence.text.includes('not a list of the areas left')&&fence.scroll<=fence.client+1,fence);await close844(p);
}
module.exports={fmt,percent,settle,reveal,platformFont,board846,assertBoard846,capture846,openType846,details846};
