// Author: Andrew Fisher. Bounded motion, replay, refresh, source-return and native-print checks.
'use strict';
const path=require('node:path'),{same,finite,evidence846}=require('./test_compact_model846.cjs');
const ui=require('./test_compact_ui846.cjs'),{close844}=require('../v8.44_linked_completion_LIVE/test_linked_ui844.cjs');
async function motion(p){return p.evaluate(()=>{const b=document.querySelector('#gc500-work-board840'),main=document.querySelector('main').getBoundingClientRect(),nav=b.querySelector('.tw840-nav').getBoundingClientRect();return {report:TodayWork840.report(),running:b.querySelectorAll('.tw840-running').length,visible:[...b.querySelectorAll('[data-tw840-area]')].filter(c=>{const r=c.querySelector('.tw846-lights')?.getBoundingClientRect();return r&&r.bottom>Math.max(main.top,nav.bottom)&&r.top<Math.min(main.bottom,innerHeight);}).map(c=>c.dataset.tw840Area),sweeps:[...b.querySelectorAll('.race-sweep-window')].map(n=>{const s=getComputedStyle(n);return {card:n.closest('[data-tw840-area]').dataset.tw840Area,play:s.animationPlayState,name:s.animationName,transform:s.transform};}),numbers:[...b.querySelectorAll('.tw840-reading,.tw846-title')].map(n=>{const s=getComputedStyle(n);return {text:n.textContent,animation:s.animationName,transform:s.transform,filter:s.filter};})};});}
const stopped=x=>!x.report.running&&x.sweeps.every(s=>s.play==='paused'||s.name==='none');
async function lifecycle846(p,check,label,e,out){
 const activeArea=e.areas.find(a=>a.id!=='fencing'&&e.summary.byId[a.id].pct>=20),id=activeArea.id;
 await p.locator('[data-tw840-jump='+id+']').click();await ui.settle(p);await p.waitForFunction(id=>TodayWork840.report().selected===id&&TodayWork840.report().running===id,id);check(label+' category navigation selects and animates its own visible group',await p.evaluate(id=>TodayWork840.report().selected===id&&TodayWork840.report().running===id,id));const initial=await motion(p),samples=[];
 for(let i=0;i<14;i++){samples.push(await p.locator('.tw840-running .race-sweep-window').first().evaluate(n=>getComputedStyle(n).transform));if(new Set(samples).size>1)break;await p.waitForTimeout(220);}
 check(label+' exactly one visible group has a moving reached-lamp reflection and fixed readings',initial.running===1&&initial.visible.includes(initial.report.running)&&new Set(samples).size>1&&initial.sweeps.every(s=>s.card===initial.report.running||s.play==='paused')&&initial.numbers.every(n=>n.animation==='none'&&n.transform==='none'&&n.filter==='none'),{initial,samples});
 await p.locator('[data-tw840-motion='+id+']').click();await p.waitForFunction(()=>TodayWork840.report().mode==='paused');const paused=await motion(p);await p.evaluate(()=>renderToday());await ui.settle(p);const refreshedPause=await motion(p);check(label+' manual Pause survives a native refresh without changing values',stopped(paused)&&stopped(refreshedPause)&&same(paused.numbers,refreshedPause.numbers),{paused,refreshedPause});
 await p.locator('[data-tw840-motion='+id+']').click();await p.waitForFunction(()=>TodayWork840.report().mode==='selected');const resumed=await motion(p);if(!resumed.visible.includes(id)){check(label+' manual Play keeps entirely offscreen lamps paused',stopped(resumed),resumed);await p.locator('[data-tw840-jump='+id+']').click();}await p.waitForFunction(id=>TodayWork840.report().running===id,id);
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>document.querySelector('[data-tw840-motion]').disabled);const reduced=await motion(p);check(label+' reduced motion stops reflections and disables controls',stopped(reduced)&&reduced.sweeps.every(s=>s.name==='none'),reduced);
 await p.emulateMedia({reducedMotion:'no-preference'});await p.waitForFunction(()=>!document.querySelector('[data-tw840-motion]').disabled);await p.waitForFunction(id=>TodayWork840.report().running===id,id);
 const pref=await p.evaluate(()=>document.documentElement.getAttribute('data-motion'));
 try{await p.evaluate(()=>{document.documentElement.dataset.motion='off';document.dispatchEvent(new Event('gc500motionchange'));});await p.waitForFunction(()=>!TodayWork840.report().running);check(label+' global Motion Off stops every work reflection',stopped(await motion(p)));}finally{await p.evaluate(value=>{if(value==null)document.documentElement.removeAttribute('data-motion');else document.documentElement.setAttribute('data-motion',value);document.dispatchEvent(new Event('gc500motionchange'));},pref);}
 await p.locator('[data-tw844-indicator][data-tw840-detail='+id+']').click();await p.waitForFunction(()=>document.querySelector('#gc500-work-dialog840').open);check(label+' opening a work breakdown stops its decorative motion',stopped(await motion(p)));await close844(p);await p.waitForFunction(token=>document.activeElement?.dataset.tw840Focus===token,id+'-indicator');
 await p.evaluate(()=>{const m=document.querySelector('main');m.scrollTop=m.scrollHeight;});await p.waitForFunction(()=>{const b=document.querySelector('#gc500-work-board840'),r=document.querySelector('main').getBoundingClientRect(),nav=b.querySelector('.tw840-nav').getBoundingClientRect();return ![...b.querySelectorAll('.tw846-lights')].some(n=>{const q=n.getBoundingClientRect();return q.bottom>Math.max(r.top,nav.bottom)&&q.top<Math.min(r.bottom,innerHeight);})&&!TodayWork840.report().running;});check(label+' lamps entirely offscreen have no running reflection',stopped(await motion(p)));await p.locator('[data-tw840-jump='+id+']').click();await p.waitForFunction(()=>!!TodayWork840.report().running);
 const type=e.types.instruments.find(t=>t.kind==='asset-type'&&t.rows.some(r=>!r.complete&&finite(r.left)&&r.left>0));await ui.openType846(p,type.id,'left');const key=type.rows.find(r=>!r.complete&&finite(r.left)&&r.left>0).key,button=p.locator('[data-tw844-reference='+JSON.stringify(key)+'] [data-tw844-action=record]');await button.click();await p.waitForFunction(()=>document.querySelector('#drawer').classList.contains('on')&&document.querySelector('[data-tw844-return]'));check(label+' compact row opens the exact native record drawer with work motion suspended',await p.evaluate(key=>state.sel===key&&!TodayWork840.report().running,key));await p.locator('[data-tw844-return]').click();await p.waitForFunction(()=>document.querySelector('#gc500-work-dialog840')?.open);check(label+' Back restores the exact type and Left breakdown',await p.locator('[data-tw843-detail-id]').getAttribute('data-tw843-detail-id')===type.id&&await p.locator('[data-tw843-detail-mode]').getAttribute('data-tw843-detail-mode')==='left');await close844(p);await p.waitForFunction(token=>document.activeElement?.dataset.tw840Focus===token,'type-'+type.id+'-left');
 const fold=p.locator('[data-tw841-group-card=equipment]');await fold.locator('summary').click();await p.waitForFunction(()=>document.querySelector('[data-tw841-group-card=equipment]').open);const beforeRefresh=await p.evaluate(()=>({top:document.querySelector('main').scrollTop,focus:document.activeElement.dataset.tw840Focus}));await p.evaluate(()=>renderToday());await p.waitForFunction(s=>document.querySelector('[data-tw841-group-card=equipment]').open&&document.activeElement.dataset.tw840Focus===s.focus&&Math.abs(document.querySelector('main').scrollTop-s.top)<=2,beforeRefresh);check(label+' open cost/source fold preserves keyboard focus and scroll through refresh',true,beforeRefresh);
 await p.locator('#printProgress').focus();let beforePrint=await p.evaluate(()=>({top:document.querySelector('main').scrollTop,folds:[...document.querySelectorAll('[data-tw841-group-card],[data-tw842-plan-fold]')].map(n=>({id:n.dataset.tw841GroupCard||'plan:'+n.dataset.tw842PlanFold,open:n.open}))}));
 await p.evaluate(()=>{window.__originalPrint846=window.print;window.__print846=0;window.print=()=>{__print846++;window.__nativePrint846={top:document.querySelector('main').scrollTop,folds:[...document.querySelectorAll('[data-tw841-group-card],[data-tw842-plan-fold]')].map(n=>({id:n.dataset.tw841GroupCard||'plan:'+n.dataset.tw842PlanFold,open:n.open}))};dispatchEvent(new Event('beforeprint'));};});
 try{await p.locator('#printProgress').click();await p.waitForFunction(()=>__print846===1);const beforeActionPrint=beforePrint;beforePrint=await p.evaluate(()=>__nativePrint846);await p.emulateMedia({media:'print'});await ui.settle(p);const print=await p.evaluate(()=>{const b=document.querySelector('#gc500-work-board840'),visible=n=>{for(let q=n;q;q=q.parentElement){const s=getComputedStyle(q);if(s.display==='none'||s.visibility==='hidden')return false;}return n.getBoundingClientRect().height>0;};return {printing:document.body.classList.contains('printing-progress'),cards:[...b.querySelectorAll('[data-tw840-area]')].map(n=>({id:n.dataset.tw840Area,visible:visible(n),container:getComputedStyle(n).containerType})),rows:[...b.querySelectorAll('.tw846-type-row')].map(n=>({id:n.dataset.tw843TypeId,visible:visible(n),counts:[...n.querySelectorAll('.tw846-qty strong')].map(v=>({value:v.textContent,color:getComputedStyle(v).color,visible:visible(v)}))})),folds:[...b.querySelectorAll('[data-tw841-group-card],[data-tw842-plan-fold]')].map(n=>n.open),running:TodayWork840.report().running};});check(label+' native Today Print keeps every compact type/count visible in dark ink and opens source folds',print.printing&&print.cards.length===6&&print.cards.every(c=>c.visible)&&print.rows.length===e.types.instruments.length&&print.rows.every(r=>r.visible&&r.counts.length===3&&r.counts.every(c=>c.visible&&c.color==='rgb(17, 17, 17)'))&&print.folds.every(Boolean)&&!print.running,{...print,beforeActionPrint,beforePrint});await p.screenshot({path:path.join(out,'compact846-'+label+'-print.png')});}
 finally{await p.emulateMedia({media:'screen'});await p.evaluate(()=>{dispatchEvent(new Event('afterprint'));window.print=__originalPrint846;delete window.__originalPrint846;});await ui.settle(p);}
 await p.waitForFunction(top=>Math.abs(document.querySelector('main').scrollTop-top)<=2,beforePrint.top,{timeout:3000});const afterPrint=await p.evaluate(()=>({top:document.querySelector('main').scrollTop,printing:document.body.classList.contains('printing-progress'),folds:[...document.querySelectorAll('[data-tw841-group-card],[data-tw842-plan-fold]')].map(n=>({id:n.dataset.tw841GroupCard||'plan:'+n.dataset.tw842PlanFold,open:n.open}))}));check(label+' after print restores folds and scroll',!afterPrint.printing&&same(afterPrint.folds,beforePrint.folds)&&Math.abs(afterPrint.top-beforePrint.top)<=2,{beforePrint,afterPrint});
 if(label==='laptop1366'){const day=new Date(e.day+'T00:00:00Z');day.setUTCDate(day.getUTCDate()-1);const selected=day.toISOString().slice(0,10);await p.locator('#asOf').fill(selected);await p.locator('#asOf').press('Tab');await p.waitForFunction(day=>TodayWork840.report().asOf===day,selected);const replay=await evidence846(p,selected,false);ui.assertBoard846(check,label+' replay',await ui.board846(p),replay.actual);await p.locator('#asOf').fill(e.day);await p.locator('#asOf').press('Tab');await p.waitForFunction(day=>TodayWork840.report().asOf===day,e.day);}
}
module.exports={lifecycle846};
