// Author: Andrew Fisher. Bounded read-only event and Inspector-resource diagnostic.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {installWriteGuard,ready840}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const {open}=require('../toolchain/harness/open_page.js'),ui=require('./test_compact_ui846.cjs');
const {PAGE,OUT,CANDIDATE_SHA}=process.env,sha=b=>crypto.createHash('sha256').update(b).digest('hex');
if(sha(fs.readFileSync(PAGE))!==CANDIDATE_SHA)throw Error('Candidate mismatch');fs.mkdirSync(OUT,{recursive:true});const guard=installWriteGuard(),r={author:'Andrew Fisher',candidate:CANDIDATE_SHA,cycles:[]};let s;
async function snap(p){return p.evaluate(()=>({report:TodayWork840.report(),main:document.querySelector('main').scrollTop,clip:document.querySelector('main').getBoundingClientRect().toJSON(),nav:document.querySelector('.tw840-nav').getBoundingClientRect().toJSON(),lamp:document.querySelector('[data-tw840-area=buildings] .tw846-lights').getBoundingClientRect().toJSON(),button:document.querySelector('[data-tw840-motion=buildings]').getBoundingClientRect().toJSON(),events:window.__events846}));}
(async()=>{try{s=await open({pageFile:PAGE,hash:'#today',W:390,H:844,dpr:2,mobile:true});const p=s.page;await ready840(p);await ui.settle(p);await p.evaluate(()=>{window.__events846=[];for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,e=>{if(e.target.closest('[data-tw840-motion]'))__events846.push({type,at:performance.now(),trusted:e.isTrusted,target:e.target.closest('[data-tw840-motion]').dataset.tw840Motion});},true);});
for(let i=0;i<3;i++){await p.locator('[data-tw840-jump=buildings]').click();await ui.settle(p);if(await p.evaluate(()=>TodayWork840.report().mode==='paused'))await p.locator('[data-tw840-motion=buildings]').click();await p.waitForFunction(()=>TodayWork840.report().running==='buildings');const c={initial:await snap(p)};await p.locator('[data-tw840-motion=buildings]').click();await p.waitForFunction(()=>TodayWork840.report().mode==='paused');await p.evaluate(()=>renderToday());await ui.settle(p);c.refreshed=await snap(p);await p.locator('[data-tw840-motion=buildings]').click();c.immediate=await snap(p);await p.waitForTimeout(400);c.settled=await snap(p);r.cycles.push(c);console.log('CYCLE '+i+' '+JSON.stringify({mode:c.settled.report.mode,running:c.settled.report.running,main:c.settled.main}));if(!c.settled.report.running){await p.screenshot({path:path.join(OUT,'phone-resume.png')});break;}}
await p.waitForTimeout(500);r.beforeInspector=guard.consoleErrors.slice();r.styles=await Promise.all(p.frames().map(async f=>({url:f.url().replace(/\/e\/[^/?]+/g,'/e/[redacted]'),styles:await f.evaluate(()=>[...document.styleSheets].map(s=>{try{return {href:s.href,rules:s.cssRules.length};}catch(e){return {href:s.href,error:e.name};}})).catch(e=>[{error:e.message}])})));r.fonts=await ui.platformFont(p,'[data-tw840-area=toilets] .tw846-title');await p.waitForTimeout(800);r.afterInspector=guard.consoleErrors.slice();r.errors=s.errors;console.log('INSPECTOR '+JSON.stringify({before:r.beforeInspector,after:r.afterInspector,fonts:r.fonts}));}
catch(e){r.error=e.stack;console.log(e.stack);}finally{if(s)await s.browser.close();await guard.closeAll();r.guard=guard;fs.writeFileSync(path.join(OUT,'diagnostic846.json'),JSON.stringify(r,null,2));}})();
