// Author: Andrew Fisher. Read-only compact Today checks; private native evidence only.
// PAGE/OUT/CANDIDATE_SHA required. LIVE=1 prohibits local HTML substitutions.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const fetchModule=require('../toolchain/harness/curlfetch.js'), originalFetch=fetchModule.curlFetch, mapStyleFetches=[];
fetchModule.curlFetch=async(...args)=>{const r=await originalFetch(...args);if(/fencing-map\.css/.test(args[0]))mapStyleFetches.push({url:args[0],status:r.status,headers:r.headers,bytes:r.body.length,sha:crypto.createHash('sha256').update(r.body).digest('hex')});return r;};
const {open}=require('../toolchain/harness/open_page.js');
const {installWriteGuard,ready840,nativeSnapshot}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const model=require('./test_compact_model846.cjs'),ui=require('./test_compact_ui846.cjs');
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
async function run(){const {PAGE,OUT,CANDIDATE_SHA}=process.env;if(!PAGE||!OUT||!CANDIDATE_SHA)throw Error('Frozen PAGE/SHA and private OUT required');const bytes=fs.readFileSync(PAGE);if(sha(bytes)!==CANDIDATE_SHA)throw Error('Candidate changed');fs.mkdirSync(OUT,{recursive:true});const live=process.env.LIVE==='1',smoke=process.env.INITIAL_ONLY==='1',first=process.env.FIRST_LOOK==='1',report={author:'Andrew Fisher',candidate:CANDIDATE_SHA,bytes:bytes.length,live,smoke,firstLook:first,fontInspector:process.env.SKIP_FONT!=='1',checks:[],views:[]},guard=installWriteGuard();let session;
const check=(name,pass,evidence)=>{report.checks.push({name,pass:!!pass,evidence});fs.writeFileSync(path.join(OUT,'checks846.json'),JSON.stringify({count:report.checks.length,passed:report.checks.filter(c=>c.pass).length,failures:report.checks.filter(c=>!c.pass),last:name},null,2));if(!pass)console.log('FAIL '+name);};
const views=[{name:'laptop1366',W:1366,H:768,dpr:1},{name:'laptop1280',W:1280,H:800,dpr:1},{name:'zoom125',W:1093,H:614,dpr:1.25},{name:'phone',W:390,H:844,dpr:2,mobile:true},{name:'4k',W:3840,H:2160,dpr:1}].filter(v=>!process.env.VIEWS||process.env.VIEWS.split(',').includes(v.name));
try{for(const view of views){console.log('START '+view.name);session=await open({pageFile:live?undefined:PAGE,hash:'#today',...view});const p=session.page;
 if(live){const up=guard.fulfilledDocuments.at(-1),got=guard.documentResponses.at(-1),bom=bytes.subarray(0,3).equals(Buffer.from([239,187,191])),stripped=bom&&got?.sha===sha(bytes.subarray(3))&&got.bytes===bytes.length-3;const exact=up?.status===200&&up.sha===CANDIDATE_SHA&&up.bytes===bytes.length&&got?.status===200&&(got.sha===CANDIDATE_SHA&&got.bytes===bytes.length||stripped)&&session.counts.page===0;check(view.name+' exact public upstream/browser bytes with zero HTML substitutions',exact,{up,got,stripped,counts:session.counts});if(!exact)throw Error('Public source identity differs');}
 await ready840(p);await p.waitForFunction(()=>TodayWork840.report().version==='v8.46'&&TodayWork840.report().typesMerged);await p.evaluate(()=>photoIndex());await p.waitForFunction(()=>['ready','failed'].includes(DOCS.state));await ui.settle(p);
 const before=await nativeSnapshot(p),day=await p.evaluate(()=>TodayWork840.report().asOf);
 await ui.capture846(p,view.name,OUT);console.log('IMAGES '+view.name+' '+OUT);
 const evidence=await model.evidence846(p,day,view.name===views[0].name),shown=await ui.board846(p);report.views.push({view,evidence,shown});if(evidence.expected)model.assertModel846(check,view.name,evidence);ui.assertBoard846(check,view.name,shown,evidence.actual);
 if(process.env.SKIP_FONT!=='1'){const fonts=await ui.platformFont(p,'[data-tw840-area=toilets] .tw846-title');check(view.name+' group title uses the loaded embedded Inter face',fonts.length>0&&fonts.every(f=>f.glyphCount===0||f.isCustomFont&&f.familyName==='Inter'),fonts);}
 await ui.details846(p,check,view.name,evidence.actual,!first&&!smoke&&view.name==='laptop1366',OUT);
 if(!first&&!smoke)await require('./test_compact_lifecycle846.cjs').lifecycle846(p,check,view.name,evidence.actual,OUT);
 const after=await nativeSnapshot(p);check(view.name+' native records media and helpers unchanged with no runtime errors',model.same(before.collections,after.collections)&&model.same(before.media,after.media)&&model.same(before.functions,after.functions)&&!session.errors.length,session.errors);
 await session.browser.close();session=null;console.log('DONE '+view.name+' '+report.checks.filter(c=>c.pass).length+'/'+report.checks.length);
}}catch(error){if(session)report.failureState=await session.page.evaluate(()=>({tab:state.tab,report:TodayWork840.report(),scroll:document.querySelector('main').scrollTop,main:document.querySelector('main').getBoundingClientRect().toJSON(),nav:document.querySelector('.tw840-nav')?.getBoundingClientRect().toJSON(),cards:[...document.querySelectorAll('[data-tw840-area]')].map(c=>({id:c.dataset.tw840Area,lamp:c.querySelector('.tw846-lights')?.getBoundingClientRect().toJSON(),button:c.querySelector('[data-tw840-motion]')?.getBoundingClientRect().toJSON()}))})).catch(e=>({error:e.message}));check('Compact browser execution',false,error.stack);}finally{if(session)await session.browser.close();await guard.closeAll();report.guard=guard;report.mapStyleFetches=mapStyleFetches;check('Frozen candidate remains unchanged',sha(fs.readFileSync(PAGE))===CANDIDATE_SHA);check('All non-GET requests blocked and no operational write attempted',guard.nonGetSeen.length===guard.blocked.length&&!guard.nonGetSeen.some(r=>r.operational),guard.nonGetSeen);const unexpected=guard.consoleErrors.filter(e=>!(/Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(e.text)&&guard.blocked.some(b=>!b.operational&&b.url===e.url)));check('No unexpected console errors',!unexpected.length,unexpected);report.passed=report.checks.filter(c=>c.pass).length;report.total=report.checks.length;fs.writeFileSync(path.join(OUT,'compact846.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,total:report.total}));if(report.passed!==report.total)process.exitCode=1;}}
if(require.main===module)run().catch(e=>{console.error(e.message);process.exitCode=2;});
