// Author: Andrew Fisher. Local-only examples; never reads or writes shared records.
const pin='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" aria-hidden="true"><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>';
const icons={run:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M6 9V3h12v6M6 17H3V9h18v8h-3M6 14h12v7H6Z"/></svg>',progress:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m5 12 4 4L19 6"/><circle cx="12" cy="12" r="10"/></svg>'};
const examples=window.GC500TimelinePreviewExamples; // Supplied by the isolated private preview shell.
const labels=['','Off site','In transit','At location','Installed','Finished'];
const cards=[...document.querySelectorAll('.load-card')],dlg=document.querySelector('dialog'),reduced=matchMedia('(prefers-reduced-motion:reduce)');
let stage=1,paused=false,selected='a';
const example=()=>examples[document.querySelector('#example').value];
function draw(){const r=example();cards.forEach(c=>{c.innerHTML='<header class="load-top"><div class="load-order"><span>LOAD</span><b>'+r.load+'</b></div><div class="identity"><h3><span class="ref">'+r.key+'</span><span>'+esc(r.name)+'</span></h3><div class="subtitle"><span>'+esc(r.item)+'</span><span class="source">'+esc(r.source)+'</span></div></div><span class="status'+(stage===5?' finished':'')+'"><i></i>'+labels[stage]+'</span></header><div class="card-body"><div class="lights-wrap">'+timeline841Lights({stage,arrived:stage>=3,label:labels[stage],why:'Demonstration only; no record changes.'})+'</div><div class="actions"><button class="action navigate" data-action="navigate">'+pin+'<span>Navigate<small>MAP & QR</small></span></button><button class="action run" data-action="run">'+icons.run+'Run sheet</button><button class="action" data-action="progress">'+icons.progress+'Progress</button></div></div>';});refresh();}
function visible(c){const b=c.querySelector('.tl841-gantry').getBoundingClientRect();return b.top<innerHeight&&b.bottom>0;}
function refresh(){const allowed=!paused&&!reduced.matches&&!document.hidden&&!dlg.open;const active=allowed?(cards.find(c=>c.dataset.option===selected&&visible(c))||cards.find(visible)):null;cards.forEach(c=>{c.classList.toggle('tl841-live',c===active);c.classList.toggle('selected',c.dataset.option===selected)});const b=document.querySelector('#motion');b.disabled=reduced.matches;b.textContent=reduced.matches?'Reduced motion':paused?'Resume glow':'Pause glow';b.setAttribute('aria-pressed',String(paused));}
function openPreview(type){const r=example();const titles={progress:r.key+' · Progress',run:'Run sheet · Load '+r.load,navigate:r.key+' · Destination'};document.querySelector('#dialog-title').textContent=titles[type];let text='';if(type==='progress'){text='<p>Try the five stages. These controls affect both layout examples only.</p><div class="choices">'+labels.slice(1).map((s,i)=>'<button data-stage="'+(i+1)+'" class="'+(stage===i+1?'selected':'')+'">'+s+'</button>').join('')+'</div><p class="note">Finished stays clearly marked, with all five lights green. Existing live completion checks will remain authoritative.</p>';}else{text='<dl><dt>Reference</dt><dd>'+esc(r.key)+'</dd><dt>Destination</dt><dd>'+esc(r.name)+'</dd><dt>Equipment</dt><dd>'+esc(r.item)+'</dd><dt>Source</dt><dd>'+esc(r.source)+'</dd></dl><p class="note">'+(type==='run'?'Layout preview only. No print request is sent and no load moves to Transit. The final page will retain the existing run-sheet checklist and print behaviour.':'Layout preview only. The final page will retain the existing destination, QR code and map action. No location is created or changed.')+'</p>';}document.querySelector('#dialog-content').innerHTML=text;dlg.showModal();refresh();}
document.querySelector('#stage').addEventListener('change',e=>{stage=+e.target.value;draw()});document.querySelector('#example').addEventListener('change',draw);document.querySelector('#motion').addEventListener('click',()=>{paused=!paused;refresh()});
document.addEventListener('click',e=>{const c=e.target.closest('.load-card');if(c){selected=c.dataset.option;refresh()}const a=e.target.closest('[data-action]');if(a)openPreview(a.dataset.action);const s=e.target.closest('[data-stage]');if(s){stage=+s.dataset.stage;document.querySelector('#stage').value=stage;draw();document.querySelectorAll('[data-stage]').forEach(b=>b.classList.toggle('selected',+b.dataset.stage===stage))}});dlg.querySelector('.close').addEventListener('click',()=>dlg.close());dlg.addEventListener('close',refresh);addEventListener('scroll',refresh,{passive:true});addEventListener('resize',refresh);document.addEventListener('visibilitychange',refresh);reduced.addEventListener('change',refresh);draw();
