/* Author: Andrew Fisher. People, not roles, determine crew numbers. No roster or wage assumptions. */
const crew883Roles={spotter:'Spotter',forklift:'Forklift operator',installer:'Installer',escort:'Escort'};
function crew883Key(day,ref){return 'crew883/'+day+'/'+(ref||'availability');}
function crew883Day(day){return (S.loads||{})[crew883Key(day)]||{count:null,names:[]};}
function crew883Arrival(day,ref){const d=programmeDays().find(d=>d.iso===day);if(!d)return '';const loads=dpLoads(d).filter(g=>(g.rows||[]).some(r=>r.a.key===ref)),times=[...new Set(loads.map(g=>String(g.time||'').trim()).filter(Boolean))];if(times.length!==1)return '';const m=/^(\d{1,2}):([0-5]\d)$/.exec(times[0]);return m&&Number(m[1])<24?m[1].padStart(2,'0')+':'+m[2]:'';}
function crew883Finish(start){if(!start)return '';const n=Number(start.slice(0,2))*60+Number(start.slice(3))+30;return n<1440?String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0'):'';}
function crew883Plan(day,ref){const saved=(S.loads||{})[crew883Key(day,ref)];if(saved)return saved;const a=assetOf(ref),scheduled=crew883Arrival(day,ref),clock=new Date(Date.now()+10*3600000).toISOString().slice(11,16),arrival=day>todayIso()||day===todayIso()&&scheduled>=clock?scheduled:'',finish=crew883Finish(arrival);return {people:[],start:finish?arrival:'',finish,location:a?whereText(a).main||'':'',order:null,defaultWindow:true};}
function crew883Transport(a){const product=String(a.product||'');if(/waste|sewage/i.test(product)&&/tank/i.test(product))return 'Standard-size item · sewage tank';if(/building/i.test(a.discipline||'')||/building|ticket box|toilet.*block|\d+\s*pan.*block|ablution/i.test(product))return 'Oversize transport planning required';return 'Transport requirements to confirm';}
function crew883ValidDay(day){return /^\d{4}-\d{2}-\d{2}$/.test(day)&&!isNaN(Date.parse(day));}
function crew883Write(day,ref,value){if(!crew883ValidDay(day)||ref&&(!assetOf(ref)||assetOf(ref)._cancelled)||!mayWrite('crew planning'))return false;const by=whoAmI();if(!by)return false;const key=crew883Key(day,ref),old=(S.loads||{})[key];S.loads=S.loads||{};S.loads[key]=Object.assign({},value,{kind:'crew883',day,ref:ref||'',by,at:new Date(Math.max(Date.now(),old?Date.parse(old.at)+1:0)).toISOString()});bump();flash('Crew planning saved.');return true;}
function crew883SaveDay(day,count,names){if(count!==null&&(!Number.isInteger(count)||count<0||count>50)||!Array.isArray(names))return false;return crew883Write(day,'',{count,names:count===null?[]:names.slice(0,count).map(x=>String(x||'').trim().slice(0,100))});}
function crew883SavePlan(day,ref,v){if(!v||v.order!=null&&(!Number.isInteger(v.order)||v.order<1||v.order>200)||!Array.isArray(v.people)||v.people.length>20||v.people.some(p=>!Array.isArray(p.roles)||!p.roles.length||p.roles.some(r=>!crew883Roles[r])||p.slot!==null&&(!Number.isInteger(p.slot)||p.slot<1||p.slot>50)))return false;const time=x=>x===''||/^([01]\d|2[0-3]):[0-5]\d$/.test(x);if(!time(v.start)||!time(v.finish)||!!v.start!==!!v.finish||v.start&&v.finish<=v.start)return false;const slots=v.people.map(p=>p.slot).filter(x=>x!==null);if(new Set(slots).size!==slots.length)return false;return crew883Write(day,ref,{order:v.order||null,people:v.people.map(p=>({slot:p.slot,roles:[...new Set(p.roles)]})),start:v.start,finish:v.finish,location:String(v.location||'').trim().slice(0,200)});}
function crew883Assess(day,ref){const p=crew883Plan(day,ref),d=crew883Day(day),issues=[],needed=p.people.length,plans=Object.values(S.loads||{}).filter(x=>x.kind==='crew883'&&x.day===day&&x.ref&&x.people&&x.people.length&&assetOf(x.ref)&&!assetOf(x.ref)._cancelled);if(d.count!==null&&needed>d.count)issues.push('People shortage');if(p.people.some(x=>x.slot&&d.count!==null&&x.slot>d.count))issues.push('Assigned person outside available crew');if(p.people.some(x=>x.roles.includes('forklift')&&x.roles.includes('spotter')))issues.push('Confirm a separate external spotter during forklift operation');const timed=p.start&&p.finish,overlap=(a,b)=>a.start<b.finish&&b.start<a.finish;if(needed&&(!timed||!p.location||plans.some(x=>x.ref!==ref&&(!x.start||!x.finish||!x.location))))issues.push('Clash check incomplete');if(timed){const others=plans.filter(x=>x.ref!==ref&&x.start&&x.finish&&overlap(p,x));for(const x of others){if(p.people.some(a=>a.slot&&x.people.some(b=>a.slot===b.slot)))issues.push(x.location===p.location&&p.location?'Shared person with '+x.ref+' · confirm unloading sequence':'Person also assigned to '+x.ref);}
// Peak simultaneous people: explicit shared slots count once; unnamed requirements remain separate.
if(d.count!==null){for(const t of [p.start,...others.map(x=>x.start)].filter(t=>t>=p.start&&t<p.finish)){const active=[p,...others].filter(x=>x.start<=t&&t<x.finish),slots=new Set(),anonymous=active.reduce((n,x)=>n+x.people.filter(a=>!a.slot).length,0);active.forEach(x=>x.people.forEach(a=>{if(a.slot)slots.add(a.slot);}));if(slots.size+anonymous>d.count){issues.push('Overlapping loads exceed available people');break;}}}}
return {needed,available:d.count,issues:[...new Set(issues)],unassigned:p.people.filter(x=>!x.slot||!d.names[x.slot-1]).length};}
function crew883Summary(day,ref){const x=crew883Assess(day,ref);return ((S.loads||{})[crew883Key(day,ref)]?x.needed+' people needed':'People required to confirm')+' · '+(x.available===null?'availability to confirm':x.available+' available')+(x.unassigned?' · names to be assigned':'')+(crew883Plan(day,ref).order?' · planned order '+crew883Plan(day,ref).order:'');}
function crew883PersonHtml(day,p,i,can){const d=crew883Day(day);return '<fieldset data-crew883-person><legend>Person '+(i+1)+'</legend><label>Assign person <select data-crew883-slot'+(can?'':' disabled')+'><option value="">To be assigned</option>'+Array.from({length:Math.max(d.count||0,p.slot||0)},(_,n)=>'<option value="'+(n+1)+'"'+(p.slot===n+1?' selected':'')+'>'+esc(d.names[n]||'Person '+(n+1))+'</option>').join('')+'</select></label>'+Object.entries(crew883Roles).map(([r,w])=>'<label><input type="checkbox" data-crew883-role="'+r+'"'+(p.roles.includes(r)?' checked':'')+(can?'':' disabled')+'> '+w+'</label>').join('')+(can?'<button type="button" class="btn" data-crew883-remove>Remove person</button>':'')+'</fieldset>';}
function crew883Editor(a,day){day=day||state.day||todayIso();if(!a||!crew883ValidDay(day))return '';const p=crew883Plan(day,a.key),d=crew883Day(day),can=capability()==='edit'&&!SYNC.readonly;if(!can&&!p.people.length&&d.count===null)return '';const x=crew883Assess(day,a.key);return '<details class="loading872 crew883" data-crew883-ref="'+esc(a.key)+'" data-crew883-day="'+esc(day)+'"><summary>Crew · '+esc(crew883Summary(day,a.key))+'</summary><div class="crew883-body"><b>'+esc(fmtDate(day))+'</b><p>'+esc(crew883Transport(a))+'</p><details><summary>Transport checks</summary><p>Planning category only. Confirm the loaded vehicle dimensions, total and axle masses, restraints, route access and applicable permit conditions before dispatch.</p></details><details><summary>People available for the day · '+(d.count===null?'not set':d.count)+'</summary><label>Number available <input type="number" min="0" max="50" data-crew883-count value="'+(d.count===null?'':d.count)+'"'+(can?'':' disabled')+'></label><label>Names (optional; one per line) <textarea data-crew883-names'+(can?'':' disabled')+'>'+esc(d.names.join('\n'))+'</textarea></label>'+(can?'<button type="button" class="btn" data-crew883-day-save>Save day availability</button>':'')+'</details><label>Planned arrival order <input type="number" min="1" max="200" data-crew883-order value="'+(p.order||'')+'"'+(can?'':' disabled')+'></label><label>Location <input data-crew883-location value="'+esc(p.location)+'"'+(can?'':' disabled')+'></label><label>Planned unloading starts <input type="time" data-crew883-start value="'+esc(p.start)+'"'+(can?'':' disabled')+'></label><label>Planned unloading finishes <input type="time" data-crew883-finish value="'+esc(p.finish)+'"'+(can?'':' disabled')+'></label><div data-crew883-people>'+p.people.map((x,i)=>crew883PersonHtml(day,x,i,can)).join('')+'</div>'+(can?'<button type="button" class="btn" data-crew883-add>Add person</button> <button type="button" class="btn" data-crew883-save>Save crew plan</button>':'')+'<p>Past arrival times are not inferred. Planned order and people can be recorded without times. Future unloading allows 30 minutes from the scheduled arrival where one time is known. Adjust the finish time for delays. Staggered loads can reuse the same crew.</p><p>Each row is one person. Select all roles they will cover. Shared people need a confirmed sequence.</p><div data-crew883-result>'+x.issues.map(t=>'<p>'+esc(t)+'</p>').join('')+'</div></div></details>';}
function crew883Sheet(a,day){day=day||crew883PrintDay||state.day||todayIso();const p=crew883Plan(day,a.key);if(!p.people.length){const text=crew883Transport(a);return text==='Transport requirements to confirm'?'':'<div class="loading872-sheet"><b>'+esc(text)+'</b><div>Confirm loaded vehicle dimensions, mass, restraints and route conditions.</div></div>';}const d=crew883Day(day),x=crew883Assess(day,a.key);return '<div class="loading872-sheet"><b>Crew · '+esc(a.key)+' · '+esc(fmtDate(day))+'</b><p>'+esc(crew883Summary(day,a.key))+'</p>'+p.people.map((p,i)=>'<div>'+esc(p.slot?(d.names[p.slot-1]||'Person '+p.slot):'Person '+(i+1)+' · to be assigned')+' · '+esc(p.roles.map(r=>crew883Roles[r]).join(' / '))+'</div>').join('')+'<div>'+esc(crew883Transport(a))+'</div><div>'+esc([p.location,p.start&&p.start+'–'+p.finish].filter(Boolean).join(' · '))+'</div>'+x.issues.map(t=>'<div>'+esc(t)+'</div>').join('')+'</div>';}
const crew883HandlingEditor=handling875Editor;handling875Editor=function(a){return crew883HandlingEditor(a)+crew883Editor(a);};
const crew883HandlingSheet=handling875Sheet;handling875Sheet=function(a){return crew883HandlingSheet(a)+(a?crew883Sheet(a):'');};
document.addEventListener('click',e=>{const button=e.target.closest('[data-crew883-add],[data-crew883-remove],[data-crew883-save],[data-crew883-day-save]');if(!button)return;e.preventDefault();const box=button.closest('.crew883'),day=box.dataset.crew883Day,ref=box.dataset.crew883Ref;if(!mayWrite('crew planning'))return;if(button.hasAttribute('data-crew883-add')){const list=box.querySelector('[data-crew883-people]');if(list.children.length>=20)return;list.insertAdjacentHTML('beforeend',crew883PersonHtml(day,{slot:null,roles:[]},list.children.length,true));return;}if(button.hasAttribute('data-crew883-remove')){button.closest('[data-crew883-person]').remove();return;}let ok;if(button.hasAttribute('data-crew883-day-save')){const v=box.querySelector('[data-crew883-count]').value;ok=crew883SaveDay(day,v===''?null:Number(v),box.querySelector('[data-crew883-names]').value.split('\n'));}else{ok=crew883SavePlan(day,ref,{order:box.querySelector('[data-crew883-order]').value?Number(box.querySelector('[data-crew883-order]').value):null,people:[...box.querySelectorAll('[data-crew883-person]')].map(n=>({slot:n.querySelector('[data-crew883-slot]').value?Number(n.querySelector('[data-crew883-slot]').value):null,roles:[...n.querySelectorAll('[data-crew883-role]:checked')].map(x=>x.dataset.crew883Role)})),location:box.querySelector('[data-crew883-location]').value,start:box.querySelector('[data-crew883-start]').value,finish:box.querySelector('[data-crew883-finish]').value});}if(ok){box.outerHTML=crew883Editor(assetOf(ref),day);const reopened=document.querySelector('.crew883[data-crew883-ref="'+CSS.escape(ref)+'"][data-crew883-day="'+day+'"]');if(reopened)reopened.open=true;}else flash('Choose a role for each person and check the crew numbers and time window.');});
let crew883PrintDay='';
const crew883Page=dpPage;dpPage=function(d,...args){const before=crew883PrintDay;crew883PrintDay=d.iso;try{return crew883Page(d,...args);}finally{crew883PrintDay=before;}};
const crew883DemobSheet=sheet816;sheet816=function(day,...args){const before=crew883PrintDay;crew883PrintDay=day;try{return crew883DemobSheet(day,...args);}finally{crew883PrintDay=before;}};
const crew883EP=epRunSheet819;epRunSheet819=function(L){const before=crew883PrintDay;crew883PrintDay=L.iso||L.date||'';try{return crew883EP(L);}finally{crew883PrintDay=before;}};
function crew883Checks(m,day,assets){if(!m)return m;for(const a of [...new Map(assets.filter(Boolean).map(a=>[a.key,a])).values()]){const p=crew883Plan(day,a.key);if(!p.people.length)continue;const x=crew883Assess(day,a.key);m.report.push(a.key+': '+crew883Summary(day,a.key));x.issues.forEach(text=>m.warnings.push({key:a.key,text}));}return m;}
const crew883Driver=driverModel826;driverModel826=function(day,only){const m=crew883Driver(day,only),sel=selectedDriver826(day,only);return sel?crew883Checks(m,day,sel.loads.flatMap(x=>x.g.rows.map(r=>r.a))):m;};
const crew883Demob=demobModel826;demobModel826=function(day,...args){const m=crew883Demob(day,...args);return crew883Checks(m,day,selectedDemob826(day,...args).flatMap(L=>L.stops.map(s=>assetOf(s.r.key))));};

document.addEventListener('change',e=>{if(!e.target.matches('[data-crew883-start]'))return;const box=e.target.closest('.crew883');box.querySelector('[data-crew883-finish]').value=crew883Finish(e.target.value);});
const crew883Drop=dropPage;dropPage=function(a,events,n,total,d,kind){const before=crew883PrintDay;crew883PrintDay=d&&d.iso||before;try{return crew883Drop(a,events,n,total,d,kind);}finally{crew883PrintDay=before;}};
