/* Author: Andrew Fisher. Compatibility with the unchanged hosted explorer core. */
'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const parent=path.resolve(__dirname,'../..'),folder=fs.readdirSync(parent).find(n=>n.startsWith('v8.28_fencing_map_'));
const core=require(path.join(parent,folder,'source/fencing-map-core.js'));
const H='a'.repeat(64),O='b'.repeat(64),N='c'.repeat(64),old={id:'old-plan',sha256:O,pages:1,revision:'2026-09-01'},plan={id:'new-plan',sha256:N,pages:2,revision:'2026-09-02'};
const geom=(id,sha)=>({id,kind:'anchor',role:'area-signoff',master_sha256:H,source_sha256:sha,source_page:1,task_ids:[],area_evidence_names:[],points:[[100,100]],region:'main',confidence:'Reviewed area only',alignment:{method:'Reviewed native master match',setout:false},category:'unclassified',line_completion_permitted:false,task_completion_permitted:false});
const snapshot={master_sha256:H,current_source_id:'old-plan',sources:[old],reference_sources:[],geometry:[geom('old-area',O)],weeks:[{plan_update:{sha256:O,sha256_16:O.slice(0,16),rows_by_day:[{date:'2026-09-01',rows:[{id:'old-task',page:1,location:'Original location',description:'Original work',fields:{},requirements:[],conflicts:[]}]}]}}],coverage:[],areaEvidence:[],sectionEvidence:[]};
let passed=0;function test(name,fn){fn();passed++;process.stdout.write('PASS '+name+'\n');}
const base=core.model(snapshot,H),wrong=core.model({...snapshot,reference_sources:[plan],geometry:[...snapshot.geometry,geom('new-area',N)]},H),right=core.model({...snapshot,sources:[old,plan],geometry:[...snapshot.geometry,geom('new-area',N)]},H);
test('original source and native task remain accepted',()=>{assert.equal(base.geometry.length,1);assert.equal(base.rows.length,1);assert.equal(base.rejected.length,0);});
test('regression: plan in master-reference catalogue is rejected',()=>{assert.equal(wrong.geometry.length,1);assert.deepEqual(wrong.rejected,[{id:'new-area',reason:'Plan source mismatch'}]);});
test('additive plan in sources accepts both areas and no rejected geometry',()=>{assert.equal(right.geometry.length,2);assert.equal(right.rejected.length,0);assert.deepEqual(right.rows,base.rows);});
test('original source descriptor, source order and default are preserved',()=>{assert.deepEqual(right.sources[0],old);assert.equal(right.currentSource,'old-plan');assert.equal(right.referenceSources.length,0);});
test('new area carries no section completion or measured work',()=>{const g=right.geometry.find(g=>g.id==='new-area');assert.deepEqual(g.area_evidence_names,[]);assert.deepEqual(g.task_ids,[]);assert.equal(g.line_completion_permitted,false);assert.equal(g.task_completion_permitted,false);assert.equal(right.rows[0].status.state,'planned');});
test('reviewed date qualification survives the unchanged child model',()=>{const note='PDF creation metadata; no printed revision and no work-date assertion.',qualified=core.model({...snapshot,sources:[old,{...plan,label:'Plan (rev = PDF creation date, not issue/work date)'}],geometry:[...snapshot.geometry,{...geom('new-area',N),source_date_conflict:note}]},H);assert.equal(qualified.geometry.find(g=>g.id==='new-area').source_date_conflict,note);assert.match(qualified.sources[1].label,/PDF creation date/);assert.deepEqual(qualified.rows,base.rows);});
test('newly recognised source exposes only its existing native planned rows',()=>{const week={plan_update:{sha256:N,sha256_16:N.slice(0,16),rows_by_day:[{date:'2026-09-02',rows:[{id:'existing-source-task',page:2,location:'Existing area',description:'Work already recorded',fields:{},requirements:[],conflicts:[]}]}]}},s={...snapshot,weeks:[...snapshot.weeks,week]},before=core.model(s,H),after=core.model({...s,sources:[old,plan]},H),added=after.rows.filter(r=>!before.rows.some(b=>b.id===r.id));assert.deepEqual(after.rows.filter(r=>before.rows.some(b=>b.id===r.id)),before.rows);assert.equal(added.length,1);assert.equal(added[0].native_id,'existing-source-task');assert.equal(added[0].source_sha256,N);assert.equal(added[0].page,2);assert.equal(added[0].status.state,'planned');assert.equal(after.currentSource,before.currentSource);assert.deepEqual(after.geometry,before.geometry);assert.equal(s.weeks[1],week);});
process.stdout.write(JSON.stringify({passed,failed:0})+'\n');
