/* Author: Andrew Fisher. Each photograph belongs to one explicit physical item. */
(function(){
'use strict';
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function sourceAsset(board,lines){const matches=(lines||[]).filter(r=>String(r.rental_contract)===String(board.contract)&&String(r.line)===String(board.line));return board.asset||(matches.length===1?String(matches[0].asset_no||''):'');}
function assetSummary(a,nos,branch){const boards=typeof vms913BoardsOn==='function'?vms913BoardsOn(a):[];if(!boards.length)return [a.discipline,branch,nos.length?'asset '+nos.slice(0,2).join(', ')+(nos.length>2?' +'+(nos.length-2):''):null].filter(Boolean).join(' · ');return boards.map(b=>{const v=vms913Of(b),owner=Units925.owner(v.co);return (owner==='coates'?'Coates ':'SUB-HIRED — '+Units925.company(owner)+' ')+(v.fleet||b.vms);}).join(' · ');}
function signature(u){return JSON.stringify([u.id,u.ref,u.owner,u.assetNo,u.item]);}
function photoUnits(rows,photos){const ids=rows.filter(r=>r.physical&&r.id).map(r=>r.id);return [...new Set(ids.concat(photos.map(p=>String(p.unit||'')).filter(Boolean)))];}
function firstFree(unit,rows,photos,pending,max){const aliases=new Set([unit.id]);if(unit.assetNo&&rows.filter(r=>r.assetNo===unit.assetNo).length===1)aliases.add(unit.assetNo);const used=new Set();for(const p of photos.concat(pending||[])){if(aliases.has(String(p.unit||''))&&Number.isInteger(p.slot)&&p.slot>=0&&p.slot<max)used.add(p.slot);}for(let i=0;i<max;i++)if(!used.has(i))return i;return -1;}
function friendlyRow(u){return [u.label&&u.label!==u.item?u.label:'',u.item,u.assetNo,typeof Units925!=='undefined'?Units925.company(u.owner):u.owner].filter(Boolean).join(' · ');}
function read(ref){return holdAssets(()=>{const a=assetOf(ref);return a?{a,model:gcModel925(a)}:null;});}
function friendly(ref,id){if(!id)return 'Location';const data=read(ref),u=data&&data.model.rows.find(x=>x.id===id);if(u)return friendlyRow(u);try{const p=JSON.parse(id);if(Array.isArray(p)&&p.length===4)return (p[2]==='asset'?'Asset '+p[3]:'Previously identified unit')+' · '+Units925.company(p[1]);}catch(e){}return 'Asset '+id;}
function pending(ref){return typeof PHOTO_OUTBOX!=='undefined'?[...PHOTO_OUTBOX.values()].filter(p=>p.key===ref):[];}
function guard(ref,id,slot,expected,replace){const data=read(ref),u=data&&data.model.rows.find(x=>x.id===id&&x.physical);if(!u||signature(u)!==expected||data.a._cancelled||movedAway(ref))return 'This item changed. Reopen its card before adding a photo.';if(replace){const all=dropPhotosOf(ref),ph=all.find(p=>p.id===replace.id&&String(p.unit||'')===replace.unit&&p.slot===replace.slot);return ph&&Units925.photos(u,data.model.rows,all).some(p=>p.id===ph.id)?'':'That photo changed. Reopen the photos before replacing it.';}return firstFree(u,data.model.rows,dropPhotosOf(ref),pending(ref),DROP_MAX)===slot?'':'That photo place is now in use. Choose Add photo again.';}
function uploadControl(a,u,full){return !SYNC.readonly&&u.physical?'<label class="btn primary item933-add">'+(full?'Manage photos':'Add photo')+(full?'':'<input type="file" accept="image/jpeg,image/png,image/webp" data-item933-add="'+esc(u.id)+'" data-item933-ref="'+esc(a.key)+'" data-item933-sig="'+esc(signature(u))+'">')+'</label>':'';}
function photoHtml(ph,ref,u){const r=photoFor(ph);return '<figure>'+(r.state==='ready'?'<a href="'+esc(r.url)+'" target="_blank" rel="noopener"><img src="'+esc(r.thumb||r.url)+'" alt="'+esc(u?friendlyRow(u):'Location photo at '+ref)+'" loading="lazy"></a>':'<p class="units925-note">Photo unavailable · '+esc(ph.id)+'</p>')+'<figcaption>'+esc(ph.caption||(DROP_SLOTS[ph.slot]||{}).lab||'Photo')+'</figcaption>'+(!SYNC.readonly?'<div class="item933-photo-tools">'+(u&&u.physical&&ph.slot<DROP_MAX?'<label class="btn item933-add">Replace<input type="file" accept="image/jpeg,image/png,image/webp" data-item933-replace="'+esc(ph.id)+'" data-item933-home="'+esc(String(ph.unit||''))+'" data-item933-slot="'+esc(ph.slot)+'" data-item933-add="'+esc(u.id)+'" data-item933-ref="'+esc(ref)+'" data-item933-sig="'+esc(signature(u))+'"></label>':'')+'<button type="button" class="btn" data-item933-remove="'+esc(ph.id)+'" data-item933-remove-home="'+esc(String(ph.unit||''))+'" data-item933-remove-slot="'+esc(ph.slot)+'" data-item933-ref="'+esc(ref)+'">Remove link</button></div>':'')+'</figure>';}
function cardPhotos(a,u,model){const photos=Units925.photos(u,model.rows,dropPhotosOf(a.key)),full=firstFree(u,model.rows,dropPhotosOf(a.key),pending(a.key),DROP_MAX)<0;return '<div class="item933-actions">'+(full?(!SYNC.readonly&&u.physical?'<button type="button" class="btn" data-item933-view>Manage photos</button>':''):uploadControl(a,u,false))+'<button type="button" class="btn" data-ro data-item933-view aria-expanded="false">View photos · '+photos.length+'</button></div><div class="item933-gallery" hidden>'+ (full?'<p class="units925-note">All '+DROP_MAX+' photo places are filled. View a photo or choose its Replace button.</p>':'')+(photos.length?'<div class="units925-photos">'+photos.map(ph=>photoHtml(ph,a.key,u)).join('')+'</div>':'<p class="units925-note">No photos assigned to this item.</p>')+'</div><p class="item933-status units925-note" role="status"></p>';}
function locationPhotos(a,photos){return '<details class="units925-edit item933-location"><summary>Location / unassigned photos · '+photos.length+'</summary><p class="units925-note">These photographs retain their original association.</p><div class="units925-photos">'+photos.map(p=>photoHtml(p,a.key,null)).join('')+'</div></details>';}
function tidy(a,body){const ph=body.querySelector('.ph816');if(!ph)return;ph.querySelector(':scope > .hubtitle')?.remove();ph.querySelector(':scope > .strip816p')?.remove();ph.querySelector(':scope > .add816')?.remove();ph.querySelectorAll(':scope > .note816').forEach(e=>e.remove());const tools=ph.querySelector('[data-f816="photos"]');if(tools){tools.querySelector('summary')?.setAttribute('aria-label','Photo record tools');}else ph.hidden=true;}
const api={sourceAsset,assetSummary,signature,photoUnits,firstFree,friendly,friendlyRow,guard,cardPhotos,locationPhotos,tidy};
if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof window==='undefined')return;window.Items933=api;
if(typeof dropPhotoUnits!=='function')return;
const previous=dropPhotoUnits;dropPhotoUnits=function(a){const ref=typeof a==='string'?a:a.key,data=read(ref);return data?photoUnits(data.model.rows,dropPhotosOf(ref)):previous(a);};
// Geographic pins retain their native asset-number identity; photo UUIDs are not new pins.
pinUnits=function(a){const nums=buildingNumbersOf(a),extra=dropPhotosOf(a.key||a).map(p=>String(p.unit||'')).filter(u=>u&&!nums.includes(u)&&!/^\s*\[/.test(u));return [...new Set(nums.concat(extra))];};
document.addEventListener('click',e=>{const view=e.target.closest&&e.target.closest('[data-item933-view]');if(view){const card=view.closest('[data-unit925-id]'),gallery=card.querySelector('.item933-gallery');gallery.hidden=!gallery.hidden;card.querySelectorAll('[data-item933-view]').forEach(b=>b.setAttribute('aria-expanded',String(!gallery.hidden)));return;}const remove=e.target.closest&&e.target.closest('[data-item933-remove]');if(!remove)return;if(!mayWrite('photo association'))return;const who=whoAmI();if(!who)return;const ref=remove.dataset.item933Ref,same=p=>p.id===remove.dataset.item933Remove&&String(p.unit||'')===remove.dataset.item933RemoveHome&&p.slot===Number(remove.dataset.item933RemoveSlot);if(!dropPhotosOf(ref).some(same))return flash('That photo changed. Reopen its card before removing the link.');if(!window.confirm('Remove this photo link? The original file stays on the service.'))return;const ph=dropPhotosOf(ref).find(same);if(!ph||!mayWrite('photo association')||whoAmI()!==who)return flash('The photo or editing session changed. Reopen its card.');photoLinkRemove(ref,ph,who,'taken off');bump();photoDrawerRedraw();});
document.addEventListener('change',async e=>{const input=e.target.closest&&e.target.closest('input[data-item933-add]');if(!input)return;const file=input.files&&input.files[0];if(!file)return;const ref=input.dataset.item933Ref,id=input.dataset.item933Add,expected=input.dataset.item933Sig;const tell=msg=>{const panel=[...document.querySelectorAll('[data-unit925-id]')].find(n=>n.dataset.unit925Id===id),out=panel&&panel.querySelector('.item933-status');if(out)out.textContent=msg;else flash(msg);};if(!mayWrite('photograph'))return;const who=whoAmI();if(!who)return;const data=read(ref),u=data&&data.model.rows.find(r=>r.id===id&&r.physical);if(!u)return tell('Reopen this item before adding a photo.');const old=input.dataset.item933Replace&&dropPhotosOf(ref).find(p=>p.id===input.dataset.item933Replace);if(input.dataset.item933Replace&&!old)return tell('That photo changed. Reopen the photos.');const replace=old?{id:old.id,unit:input.dataset.item933Home,slot:Number(input.dataset.item933Slot)}:null;const slot=replace?replace.slot:firstFree(u,data.model.rows,dropPhotosOf(ref),pending(ref),DROP_MAX);if(slot<0)return tell('All photo places are filled. Open View photos and choose a photo to replace.');const error=guard(ref,id,slot,expected,replace);if(error)return tell(error);try{await dropPhotoAdd(ref,slot,file,tell,replace?replace.unit:id,{unitId:id,expected,replace,actor:who});}catch(err){tell('The photo could not be added. Please try again.');}finally{input.value='';}});
})();
