function rowHtml925(a,u,model){
 const work=work925(a,u,model),branch=branch925(a,u),owned=u.owner==='coates',supplier=!owned&&u.owner!=='unknown';
 const lines=work.lines.map(l=>'<span class="units925-work'+(l.ticked?' done':'')+'">'+esc925(l.name)+(l.ticked?' ✓':l.descriptionTicked?' · description record':'')+'</span>').join('');
 return '<article class="units925-unit item933-card" data-unit925-id="'+esc925(u.id||'')+'"><div class="item933-head"><div><h4>'+esc925(u.item||'Description to confirm')+'</h4><b class="item933-number">'+esc925(u.assetNo||u.label)+'</b>'+(u.label&&u.label!==u.item&&u.label!==u.assetNo?'<small>'+esc925(u.label)+'</small>':'')+'</div><span class="item933-owner'+(supplier?' sub':'')+'">'+esc925((supplier?'SUB-HIRED — ':'')+company925(u.owner))+'</span></div>'+(u.identityReview?'<p class="units925-warning">'+esc925(u.identityReview)+'</p>':'')+(u.registration?'<p class="units925-note">Registration '+esc925(u.registration)+'</p>':'')+Items933.cardPhotos(a,u,model)+'<details class="units925-edit"><summary>Item details & work</summary><div class="units925-body"><dl><div><dt>Costing branch</dt><dd>'+esc925(branch.code)+'<small>'+esc925(branch.basis)+'</small></dd></div><div><dt>Cost allocation</dt><dd>'+(owned?'Coates fleet':'Quote / unit match to confirm')+'</dd></div></dl>'+(lines?'<div class="units925-worklist">'+lines+'</div><p class="units925-note">'+(work.scope==='unit'?'Recorded against this asset.':'Description records do not confirm completion of this individual unit.')+'</p>':'')+(u.loadingId?'<p class="units925-note">Loading door side: '+esc925(loading872Side(a,u.loadingId)||'To confirm')+'</p>':'')+(!SYNC.readonly&&u.source!=='restraint'?'<details class="units925-edit"><summary>Edit unit details</summary>'+form925(a,u)+'</details>':'')+'</div></details></article>';
}
function panel925(a){
 const model=gcModel925(a);if(!model.groups.length)return '';
 const choice=model.groups.some(g=>g.item===selected.get(a.key))?selected.get(a.key):(model.groups.find(g=>g.units.some(u=>u.physical))||model.groups[0]).item;selected.set(a.key,choice);
 const g=model.groups.find(g=>g.item===choice),photos=dropPhotosOf(a.key),assigned=new Set(model.rows.flatMap(u=>photos925(u,model.rows,photos)).map(p=>p.id)),unassigned=photos.filter(p=>!assigned.has(p.id));
 const history=model.rows.filter(u=>u.source==='history'&&!model.groups.some(x=>x.units.includes(u)));
 const plannedEP=(a.key==='WC09'&&['FWF','Pee Panel'].includes(g.item))||(a.key==='WC31'&&g.item==='16Pan Block');
 return '<section class="card units925" data-units925="'+esc925(a.key)+'"><p class="units925-save-status" role="status"></p><div class="units925-title"><h3>Equipment at this location</h3><span>'+model.rows.filter(r=>r.physical).length+' identified</span></div><label class="units925-description">Description<select data-ro data-unit925-description>'+model.groups.map(x=>'<option'+(x.item===choice?' selected':'')+'>'+esc925(x.item)+'</option>').join('')+'</select></label><p class="units925-note">'+g.units.filter(u=>u.physical).length+' identified'+(g.quantity==null?'':' · '+g.quantity+' planned')+'</p>'+g.units.map(u=>rowHtml925(a,u,model)).join('')+(g.pending?'<p class="units925-warning">'+(plannedEP?'<b>SUB-HIRED — Event Portables</b><br>':'')+g.pending+' planned '+esc925(g.item)+(g.pending===1?' unit needs':' units need')+' an individual identity.</p>':'')+(a.key==='WC31'&&g.item==='Accessible Toilet'&&!model.rows.some(u=>u.assetNo==='1317645')?'<p class="units925-note">Andrew reported Coates asset 1317645. It is not yet on the shared unit record.</p>':'')+(a.key==='WC31'&&g.item==='16Pan Block'?'<p class="units925-note">The current Q6845 quote covers one 16-pan block. Coverage for the second block remains to confirm.</p>':'')+(unassigned.length?Items933.locationPhotos(a,unassigned):'')+(history.length?'<details class="units925-edit"><summary>Previously recorded items · '+history.length+'</summary>'+history.map(u=>rowHtml925(a,u,model)).join('')+'</details>':'')+(!SYNC.readonly?'<details class="units925-edit"><summary>Identify another physical unit</summary>'+form925(a,null)+'</details>':'')+'</section>';
}
function mount925(a){const drawer=document.getElementById('drawer'),body=drawer&&drawer.querySelector('.db');if(!body)return;body.querySelectorAll('.units925').forEach(e=>e.remove());const html=panel925(a);if(!html)return;const summary=body.querySelector(':scope > .sum816');if(summary)summary.insertAdjacentHTML('afterend',html);else body.insertAdjacentHTML('afterbegin',html);Items933.tidy(a,body);}
