// Author: Andrew Fisher. Synthetic source/classification regressions; no live writes.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const hash='a'.repeat(64),source={id:'original.pdf',sha256:hash},files={'original.pdf':{sha256:hash}};
const cols=[['clean','m'],['scrim','m'],['v_gates','each'],['ped_gates','each'],['ccb_event','m'],['ccb_demarc','m'],['relocation','m'],['removal','m']].map(([key,unit])=>({key,unit,programme_type:key}));
const totals=n=>Object.fromEntries(cols.map(c=>[c.key,n]));
const weeks=[{sheet:'Build',phase:'Build',start:'2026-10-01',end:'2026-10-10'},{sheet:'Event',phase:'Event',start:'2026-10-19',end:'2026-10-25'},{sheet:'Demob',phase:'Demob',start:'2026-10-26',end:'2026-10-30'}];
const plans=Object.fromEntries(weeks.map(w=>[w.sheet,{sheet:w.sheet,year:2026,rolled_forward:true,totals:totals(w.phase==='Build'?100:w.phase==='Event'?50:900),days:[{date:w.start,totals:totals(w.phase==='Build'?100:w.phase==='Event'?50:900),basis:w.phase==='Event'?'source conflicts awaiting confirmation':''}]}]));
const docket=(id,date,week,quantities,extra={})=>({id,docket_no:id,date,week,quantities,components:{},location:'Work area '+id,note:'Original record',usable:true,scope:'programme',...extra});
let records=[docket('A','2026-10-01','Build',{ccb_event:40,clean:40}),docket('B','2026-10-02','Build',{ccb_event:60}),docket('C','2026-10-19','Event',{ccb_demarc:30,clean:20}),docket('D','2026-10-26','Demob',{ccb_event:900,clean:900}),docket('Y','2026-10-03','Build',{ccb_event:800,clean:800},{scope:'compound'})];
const row=(r,type)=>({record_id:r.id,docket_no:r.docket_no,source_ids:[source.id],expected:Object.fromEntries(['date','location','quantities','components','note'].map(k=>[k,r[k]])),decision:{state:'confirmed',type,basis:'Explicit source category'}});
const catalogue={schema:1,sources:[source],rows:[row(records[0],'ccb_event'),row(records[2],'ccb_demarc')]};
const DATA={weeks,fence_ccb_review847:catalogue},health={ready:true,loading:false,stale:false,basis:'Ready'};
const context=vm.createContext({DATA,FCOL:cols,todayIso:()=> '2026-10-05',allDockets:()=>records,photoIndex:()=>({state:'ready',files}),todayWorkHealth840:()=>health,progSheetOf:week=>plans[week],plannedToDay:(sheet,day,key)=>sheet.days.filter(d=>d.date<=day).reduce((n,d)=>n+(d.totals[key]||0),0),dsnState:()=>({rows:[]})});
for(const filename of ['../v8.42_today_plan_clarity_LIVE/work_summary842_src.js','fencing_classification847_src.js','fencing_metrics847_src.js','work_summary847_src.js','fencing_other_views847_src.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,filename),'utf8'),context);
const exec=(code,args={})=>{Object.assign(context,args);return vm.runInContext(code,context);};
const summary=day=>exec('todayWorkSummary847(day,Object.assign([{id:"fencing",rows:[]}],{health:todayWorkHealth840()}),{},todayFencingSummary847(day))',{day});
const byId=(s,id)=>s.fencingRows.find(r=>r.id===id);
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
const original=JSON.stringify({DATA,plans,records,files});
check('A booked type alone is unconfirmed',()=>assert.equal(exec('fenceCcbReview847(record)',{record:records[1]}).state,'pending'));
check('Exact source identity confirms classification',()=>assert.equal(exec('fenceCcbReview847(record)',{record:records[0]}).confirmedType,'ccb_event'));
check('Unavailable source remains pending',()=>{const r=exec('fenceCcbReview847(record,{files:null})',{record:records[0]});assert.equal(r.state,'pending');assert.equal(r.reviewState,'unavailable');});
check('Changed source remains pending',()=>{const r=exec('fenceCcbReview847(record,{files:{"original.pdf":{sha256:"b".repeat(64)}}})',{record:records[0]});assert.equal(r.state,'pending');assert.equal(r.reviewState,'stale');});
check('Changed quantities, note or identity do not inherit approval',()=>{for(const changed of [{...records[0],quantities:{ccb_event:41,clean:40}},{...records[0],note:'Updated'},{...records[0],docket_no:'changed'}])assert.equal(exec('fenceCcbReview847(record)',{record:changed}).state,'pending');});
check('Duplicate current docket identity remains pending',()=>{const r=exec('fenceCcbReview847(record,{records:[record,record]})',{record:records[0]});assert.equal(r.state,'pending');assert.equal(r.reviewState,'ambiguous');});
check('Conflicting source category never silently rebooks quantity',()=>{const changed=JSON.parse(JSON.stringify(catalogue));changed.rows[0].decision.type='ccb_demarc';const r=exec('fenceCcbReview847(record,{catalogue:changed})',{record:records[0],changed});assert.equal(r.state,'pending');assert.equal(r.currentType,'ccb_event');});
let now=summary('2026-10-05');
check('Full installation denominator includes Event and excludes Demob',()=>{assert.equal(byId(now,'clean').total,150);assert.equal(byId(now,'ccb_event').total,150);});
check('Date replay excludes future work and off-programme work',()=>{assert.equal(byId(now,'clean').done,40);assert.equal(byId(now,'ccb_event').done,100);assert.equal(byId(now,'ccb_event').offProgramme,800);});
check('Unknown class holds BOTH subtype pct, left and pace',()=>{for(const id of ['ccb_event','ccb_demarc']){const r=byId(now,id);assert.equal(r.pct,null);assert.equal(r.left,null);assert.equal(r.plan.status,'unknown');assert.equal(r.plan.delta,null);assert.equal(r.plan.provisionalReason,'classification');assert.equal(r.classificationPendingMetres,60);}});
check('Raw allocation and confirmed/pending source quantities remain separate',()=>{const r=byId(now,'ccb_event');assert.equal(r.done,100);assert.equal(r.confirmedRecorded,40);assert.equal(r.pendingRecorded,60);assert.equal(byId(now,'ccb_demarc').pendingRecorded,0);});
check('Future source conflicts qualify full total before dated pace',()=>{const r=byId(now,'clean');assert.equal(r.sourceProvisional,true);assert.equal(r.pctKind,'provisional-work');assert.equal(r.pct,26.67);assert.equal(r.plan.provisional,false);});
const event=summary('2026-10-25'),demob=summary('2026-10-30');
check('Event date work contributes to numerator and dated plan',()=>{const r=byId(event,'clean');assert.equal(r.done,60);assert.equal(r.plan.planned,150);assert.equal(r.plan.provisional,true);assert.equal(r.plan.provisionalReason,'source-dates');assert.equal(byId(event,'ccb_demarc').confirmedRecorded,30);});
check('Demob quantities never enter installation work',()=>{assert.equal(byId(demob,'clean').done,60);assert.equal(byId(demob,'ccb_event').done,100);});
check('No model or classification call mutates sources',()=>assert.equal(JSON.stringify({DATA,plans,records,files}),original));
check('Removing pending record restores only recorded-work ratio, never completion',()=>{const prior=records;records=records.filter(r=>r.id!=='B');const r=byId(summary('2026-10-05'),'ccb_event');assert.equal(r.classificationPending,false);assert.equal(r.pct,26.67);assert.equal(r.pctKind,'provisional-work');assert.equal(r.left,110);assert.notEqual(r.pctKind,'confirmed');records=prior;});
check('Missing Event total makes full quantity unknown',()=>{const prior=plans.Event.totals.clean;delete plans.Event.totals.clean;const r=byId(summary('2026-10-05'),'clean');assert.equal(r.total,null);assert.equal(r.left,null);assert.equal(r.pct,null);plans.Event.totals.clean=prior;});
check('Source-provisional ratio is not arbitrarily clamped at 100',()=>{const prior=records[0].quantities.clean;records[0].quantities.clean=200;const r=byId(summary('2026-10-05'),'clean');assert.equal(r.pct,133.33);assert.equal(r.pctKind,'provisional-work');records[0].quantities.clean=prior;});
const native={asOf:'2026-10-05',testTypes:[{key:'clean',name:'Clean',planned:50,done:40,total:150},{key:'ccb_event',name:'CCB event',planned:50,done:100,total:150},{key:'ccb_demarc',name:'CCB demarcation',planned:50,done:0,total:150}],fenceLines:[{column:'ccb_event',planned:50,done:100,behind:0},{column:'ccb_demarc',planned:50,done:0,behind:50}]};
context.fenceTypes=p=>p.testTypes;context.fmtNum=String;
check('Legacy views keep raw quantities but do not report pending subtypes as definite gaps',()=>{const output=exec('fenceCcbDisplayTypes847(native)',{native});assert.equal(output[0],native.testTypes[0]);assert.equal(output[1].done,100);assert.equal(output[1].plannedRecorded,50);assert.equal(output[1].planned,null);assert.equal(output[2].planned,null);assert.equal(output.filter(r=>r.planned!=null&&r.done<r.planned).length,1);assert.equal(native.testTypes[1].planned,50);});
check('Fallback progress explicitly marks unknown rows and never mutates native behind values',()=>{const output=exec('fenceCcbDisplayLines847(native)',{native});assert.ok(output.every(r=>r.ccbPending&&r.behind===null));assert.equal(native.fenceLines[1].behind,50);});
check('Printed and draft context includes pending CCB warning',()=>assert.match(exec('fenceCcbDisplayWords847(native)',{native}),/CCB categories need review/));
console.log(checks+' synthetic checks passed');
