// v7.82 - maps accuracy and driver rules. Author: Andrew Fisher. Read-only: GETs only, every write aborted by the harness.
//   PAGE=<built page> [BASE=<live page>] [MOB=1] [OUT=<json>] node rules_tests.js
const {open} = require('../../toolchain/harness/open_page');
const fs = require('fs');
async function texts(page, mob) {
  const s = await open(mob ? {pageFile: page, W: 390, H: 844, dpr: 2, mobile: true} : {pageFile: page, W: 1440, H: 900});
  const p = s.page;
  await p.waitForFunction(() => typeof dropSmsText === 'function' && typeof SYNC !== 'undefined' && SYNC.status === 'live' && SYNC.first && SYNC.first.size === Object.keys(SYNC_COLLS).length, null, {timeout: 240000});
  const R = await p.evaluate(() => {
    const out = {};
    allAssets().forEach(a => { const t = dropSmsText(a); out[a.key] = {t, u: smsShape(t).units, parts: smsShape(t).parts,
      future: typeof inPlace782 === 'function' ? !inPlace782(a.key) : null, link: /\n(Delivery details|Pictures): /.test(t), due: /\nDue /.test(t), long: typeof rules782Long === 'function' ? text747Plain(dropSmsLong(a)) : null,
      side: typeof entry782 === 'function' ? (entry782(a) || {}).side || null : null, html: typeof rules782Html === 'function' ? rules782Html(a) : null}; });
    const nt = navTargetFor(allAssets().find(a => a.key === 'GN21'));
    const gens = {}; allAssets().filter(a => /^GN\d/.test(a.key)).forEach(a => { const n = navTargetFor(a); if (n) gens[a.key] = [n.ll.lat, n.ll.lon]; });
    return {texts: out, gens, gn21: nt ? [nt.ll.lat, nt.ll.lon, nt.fix && nt.fix.how] : null, check: typeof orderCheck782 === 'function' ? orderCheck782() : null,
      load: typeof loadCheck782 === 'function' ? (() => { const keep = window.inPlace782, keepD0 = window.deliveryOf; window.inPlace782 = () => false; window.deliveryOf = k => Object.assign({}, keepD0(k), {eta: undefined, state: 'not on site'}); /* as if still to come, with no time asked for */
        try { const wc = JSON.parse(JSON.stringify(assetOf('WC05'))); const swap = wc.events.map(e => /waste tank/i.test(e.item || '') ? Object.assign(e, {load_time: '1000'}) : /toilet block/i.test(e.item || '') ? Object.assign(e, {load_time: '0430'}) : e);
          wc.events = swap; return {wc05: loadCheck782(assetOf('WC05')), p01: loadCheck782(assetOf('P01')), p04: loadCheck782(assetOf('P04')), p05: loadCheck782(assetOf('P05')), swapped: loadCheck782(wc)}; } finally { window.inPlace782 = keep; window.deliveryOf = keepD0; } })() : null,
      time: typeof timeCheck782 === 'function' ? (() => { const keepD = window.deliveryOf, keepP = window.inPlace782;
        try { window.deliveryOf = k => k === 'WB04' ? Object.assign({}, keepD(k), {eta: '09:00', state: 'not on site'}) : keepD(k);
          const wb = assetOf('WB04'), r = {wb04Sms: (dropSmsText(wb).match(/Due[^\n]*/) || [''])[0], wb04Check: timeCheck782(wb), wb04Html: rules782Html(wb).replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ')};
          const tight = JSON.parse(JSON.stringify(wb)); tight.events = [{item: 'test load', load_time: '0730', date: '2026-10-16'}]; r.tight = timeCheck782(tight); const late = JSON.parse(JSON.stringify(wb)); late.events = [{item: 'test load', load_time: '0530', date: '2026-10-16'}]; r.late = timeCheck782(late);
          r.plans = ['07:00', '09:00', '10:00', '10:30', '10:40', '12:00', '18:30'].map(x => { const P = plan782(hhmm782(x)); return x + '>' + clock782(P.onBy) + '/' + clock782(P.leaveBy); });
          const due = due782(wb); r.clock = [clock782(-40), clock782(1440 + 65), when782(due - 10, due), when782(due + 1450, due)];
          const prev = new Date((due - 1440) * 60000).toISOString().slice(0, 10), early = JSON.parse(JSON.stringify(wb)); early.events = [{item: 'night load', load_time: '2300', date: prev}]; r.early = timeCheck782(early);
          window.deliveryOf = k => k === 'WB04' ? Object.assign({}, keepD(k), {eta: '00:20', state: 'not on site'}) : keepD(k);
          r.midSms = (dropSmsText(wb).match(/Due[^\n]*/) || [''])[0]; r.mid = timeCheck782(wb);
          window.deliveryOf = k => /^(WC05|P05)$/.test(k) ? Object.assign({}, keepD(k), {state: 'not on site'}) : keepD(k); window.inPlace782 = () => false; r.wc05 = timeCheck782(assetOf('WC05')); r.p05 = timeCheck782(assetOf('P05')); return r; }
        finally { window.deliveryOf = keepD; window.inPlace782 = keepP; } })() : null,
      ready: typeof window.gc500NotReady === 'function' ? (() => { const nr = window.gc500NotReady(); const fut = allAssets().filter(a => !a._cancelled && !inPlace782(a.key));
        const one = k => { const a = assetOf(k); return {sms: dropSmsText(a), html: rules782Html(a).replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' '), long: text747Plain(dropSmsLong(a))}; };
        return {nFuture: fut.length, notReady: nr.length, noDrop: nr.filter(x => /no drop-off/.test(x.missing.join())).length, noDir: nr.filter(x => /no direction point/.test(x.missing.join())).length,
          gn04: one('GN04'), pg01: one('PG01'), ready: fut.filter(a => ready782(a).ok).map(a => a.key), delivered: ready782(assetOf('P03'))}; })() : null,
      drops: (() => { const all = allAssets().filter(a => !a._cancelled), tally = {}; all.forEach(a => { const k = dpPos(a).kind; tally[k] = (tally[k] || 0) + 1; });
        const keep = S.places, k = 'T0085', a = assetOf(k), before = dpPos(a).kind; S.places = Object.assign({}, keep || {}, {[k]: {lat: -27.98, lon: 153.43, at: new Date().toISOString(), by: 'test', how: 'test'}});
        const after = dpPos(a), txt = text747Where(a)[0]; S.places = keep; return {n: all.length, tally, before, after: after.kind, sheetLat: after.lat, txt}; })(),
      src: typeof locSrc782 === 'function' ? (() => { const P47 = assetOf('P47'), LT = assetOf('LTC01'), PG = assetOf('PG01');
        return {p47: {by: masterFixFor('P47').by, nav: navSays(P47), sheet: dpPosWords(dpPos(P47)).label, sms: text747Where(P47)[0]},
          ltc: {by: masterFixFor('LTC01').by, nav: navSays(LT), dirs: dirs782(LT), sheet: dpPos(LT).kind, sms: text747Where(LT).slice(0, 2)},
          pg01: {sms: text747Where(PG).slice(0, 2), sheet: dpPos(PG).kind, words: dpPosWords(dpPos(PG)).label, p33: MASTER_LOC.P33.ll}}; })() : null,
      wb: typeof descLoc782 === 'function' ? allAssets().filter(a => /^WB\d/.test(a.key) && !a._cancelled).map(a => ({k: a.key, sheet: dpPos(a).kind, sms: text747Where(a)[0], drop: dirs782(a).drop})) : null,
      p33seen: typeof report782 === 'function' ? (() => { const out = []; allAssets().filter(a => !a._cancelled && report782(a)).forEach(a => { const s = dropSmsText(a), w = dpPosWords(dpPos(a)), h = rules782Html(a), l = text747Plain(dropSmsLong(a)), sg = pl782Pages({iso: '2026-10-06'}, {kind: 'deliveries', rows: [{a, events: a.events || []}]}, 1, 1);
        [s, w.label + ' ' + w.line, h, l, sg].forEach((x, i) => { if (/\bP33\b/.test(String(x).replace(new RegExp('\\b' + a.key + '\\b', 'g'), ''))) out.push(a.key + ':' + ['text', 'sheet', 'drawer', 'full', 'sign'][i]); }); }); return out; })() : null,
      zones: typeof zoneEntry782 === 'function' ? Object.fromEntries(['P26', 'WC86', 'WB06', 'WC54', 'WC49', 'WC13', 'WB15', 'WC30', 'P52', 'WC68', 'P46', 'WC38', 'GN04', 'WB07'].map(k => { const z = zoneEntry782(assetOf(k)); return [k, z ? z.zone + '/' + z.side : null]; })) : null,
      noWay: typeof dirs782 === 'function' ? allAssets().filter(a => !a._cancelled && !inPlace782(a.key) && !dirs782(a).dir).map(a => a.key) : null,
      hist: typeof rules782Html !== 'function' ? null : (() => { const a = assetOf('P03'); return {html: rules782Html(a).replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' '), long: text747Plain(dropSmsLong(a)), time: timeCheck782(a), load: loadCheck782(a)}; })(),
      loadNow: typeof loadCheck782 === 'function' ? loadCheck782(assetOf('WC05')).length : null,
      doneKeys: typeof window.gc500DoneKeys === 'function' ? window.gc500DoneKeys().length : null,
      css: (() => { try { state.mapMasterSeen = true; state.sheet = 'MASTER'; go('map'); } catch (e) { return 'go: ' + e.message; }
        const ok = [...document.querySelectorAll('.mk[data-complete="1"] .okx')]; return {pills: ok.length, anim: ok[0] ? getComputedStyle(ok[0]).animationName : null}; })(), max: TEXT747_MAX};
  });
  R.errors = s.errors; await s.browser.close(); return R;
}
(async () => {
  const MOB = !!process.env.MOB, N = await texts(process.env.PAGE, MOB), B = process.env.BASE ? await texts(process.env.BASE, MOB) : null;
  const T = [], ok = (name, pass, detail) => T.push({name, pass: !!pass, detail: String(detail)});
  const keys = Object.keys(N.texts);
  const hav = (a, b) => { const r = x => x * Math.PI / 180, R = 6371000, h = Math.sin(r(b[0] - a[0]) / 2) ** 2 + Math.cos(r(a[0])) * Math.cos(r(b[0])) * Math.sin(r(b[1] - a[1]) / 2) ** 2; return 2 * R * Math.asin(Math.sqrt(h)); };
  ok('G1 GN21 is beside GN20 at the pit lane west end (D024 arrow 021, its orange symbol on the master), not by Gate 2', N.gn21 && hav(N.gn21, [-27.985391, 153.427185]) < 10 && hav(N.gn21, [-27.982825, 153.424072]) > 400, JSON.stringify(N.gn21));
  const GEN = JSON.parse(fs.readFileSync(__dirname + '/generators_on_their_master_symbol.json', 'utf8'));
  ok('G2 every generator the master places sends the driver to its orange symbol (within 1 m)', Object.keys(GEN).every(k => N.gens[k] && hav(N.gens[k], GEN[k].ll) < 1), Object.keys(GEN).map(k => k + ':' + (N.gens[k] ? Math.round(hav(N.gens[k], GEN[k].ll) * 10) / 10 : 'none')).join(' '));
  ok('R1 every text stays inside three texts (<= 459 GSM units), all plain', keys.every(k => N.texts[k].u <= N.max), 'max ' + Math.max(...keys.map(k => N.texts[k].u)));
  const has = (k, re) => N.texts[k] && re.test(N.texts[k].t);
  ok('R2 the order line is on every named unit', has('P03', /ORDER: truck 1 of 6 \(P03, P01, P05, WC05 tank, WC05 toilet, P04\)\. Out of order = no entry/) && has('P01', /ORDER: truck 2 of 6 - only after P03 is in/) && has('P05', /ORDER: truck 3 of 6 - only after P01 is in/) && has('WC05', /ORDER: trucks 4-5 of 6: tank, toilet, after P05/) && has('P04', /ORDER: truck 6 of 6 - only after the WC05 toilet block is in/) && /1 P03 > 2 P01 > 3 P05 > 4 WC05 waste tank > 5 WC05 toilet block > 6 P04/.test(N.texts.P05.long) && /refused entry and waits - waiting delays apply/.test(N.texts.P04.long) && has('GN21', /ORDER: GN21 60kVA first - tight spot/) && has('GN20', /ORDER: only after GN21 60kVA is placed/), ['P03','P01','P05','P04','WC05','GN21','GN20'].map(k => k + ':' + (N.texts[k].t.match(/ORDER:[^\n]*/) || ['-'])[0]).join(' | '));
  const tanks = keys.filter(k => /waste tank/i.test(N.texts[k].t) || ['WC20','WC27','WC60'].includes(k));
  ok('R3 every reference with a waste tank says the tank goes first', ['WC20','WC27','WC60'].every(k => has(k, /ORDER: waste tank first/)) && has('WC05', /tank, toilet/), ['WC20','WC27','WC60'].map(k => k + ':' + has(k, /ORDER: waste tank first/)).join(' '));
  ok('R4 S08 drops (WB02, WB19, WC27) are land side: enter from the Surfers (south) end, race direction', ['WB02','WB19','WC27'].every(k => N.texts[k].side === 'land side' || N.texts[k].side === null) && has('WC27', /ENTRY: land side - in from the Surfers end of Main Beach Pde, drive north \(race direction\)/), ['WB02','WB19','WC27'].map(k => k + ':' + N.texts[k].side).join(' '));
  ok('R5 seaside drops (WC50, WC60, WC62) come in at the Seaworld Dr roundabout end and drive south', ['WC50','WC60','WC62'].every(k => N.texts[k].side === 'seaside' && has(k, /ENTRY: seaside - in at the Seaworld Dr roundabout end of Main Beach Pde, drive south/)), ['WC50','WC60','WC62'].map(k => k + ':' + N.texts[k].side).join(' '));
  ok('R6 a drop nowhere near Main Beach Pde carries no Main Beach entry line (AA, P01)', !has('AA', /ENTRY:/) && !has('P01', /ENTRY:/), (N.texts.AA.t.match(/ENTRY:[^\n]*/) || ['none'])[0]);
  ok('R7 Full details carries the whole rule set (order, entry, park, stagger, D007 event-week facts)', /DRIVER RULES/.test(N.texts.P05.long) && /  P01: /.test(N.texts.P05.long) && /Stagger arrivals/.test(N.texts.P05.long) && /one-way anti-clockwise \(race direction\) from 05:00 Mon 19 Oct; roads reopen 17:00 Mon 26 Oct\. D007 General Note 1 gives different dates - the drawing conflicts, confirm with site/.test(N.texts.P05.long) && !/Mon 20 Oct|Mon 27 Oct/.test(N.texts.P05.long), N.texts.P05.long.split('DRIVER RULES')[1].slice(0, 300));
  ok('R8 the drawer shows a Driver rules box for a named unit, none for a unit no rule touches', /Driver rules/.test(N.texts.GN20.html) && /GN21/.test(N.texts.GN20.html), (N.texts.GN20.html || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').slice(0, 240));
  ok('R9 park drops carry the wildlife and branches caution, in the text when it fits and always in Full details', keys.filter(k => /Park access: watch for wildlife/.test(N.texts[k].long)).length > 20, keys.filter(k => /Park access/.test(N.texts[k].long)).length + ' in Full details · ' + keys.filter(k => /PARK: watch/.test(N.texts[k].t)).length + ' in the short text');
  ok('R10 the order check reads the record (GN21 before GN20 recorded out of order; P01 vs P03; WC05 vs P05, P04)', Array.isArray(N.check) && N.check.length === 5, JSON.stringify(N.check.map(c => c.first + '>' + c.then + ':' + c.state)));
  ok('L1 the load rule (morning: away from Kingston by 05:00, in order, no travel 07:00-09:00 or 16:00-18:00; a timed delivery follows its own leave-by) is in Full details and the drawer of a delivery still to come', /LOAD: for a morning delivery \(on site before 07:00\), loaded and away from Kingston by 05:00\. Load in the delivery order/.test(N.texts.WB04.long) && /NO travel to the Gold Coast 07:00-09:00 or 16:00-18:00\. A delivery with a time asked for gets one leave-by time that meets all of these/.test(N.texts.WB04.long) && /For a morning delivery \(on site before 07:00\), loaded and away from Kingston by 05:00/.test(N.texts.WB04.html || ''), (N.texts.WB04.long.match(/LOAD:[^\n]*/) || ['-'])[0]);
  ok('L2 the general load check flags the 14 Sep plan as if still to come and untimed (WC05 tank 08:30 after 05:00 and in the 07:00-09:00 no-travel window; toilet 09:30 after 05:00; P01 same slot as P03; P04 same slot as the WC05 toilet; P05 clean)', N.load && N.load.wc05.some(x => /Waste tank: load 08:30 - away from Kingston after 05:00 and puts the truck on the road 08:30-09:40, inside the 07:00-09:00 no-travel window/.test(x)) && N.load.wc05.some(x => /Toilet Block 6m: load 09:30 - away from Kingston after 05:00$/.test(x)) && N.load.p01.some(x => /not after P03 \(04:30\)/.test(x)) && N.load.p04.some(x => /not after WC05 \(09:30\)/.test(x)) && !N.load.p05.length, JSON.stringify(N.load && {wc05: N.load.wc05, p01: N.load.p01, p04: N.load.p04, p05: N.load.p05}));
  ok('L3 a waste tank loading after its toilet block is called out', N.load && N.load.swapped.some(x => /the waste tank loads at 10:00, not before the toilet block \(04:30\) - load the tank first/.test(x)), JSON.stringify(N.load && N.load.swapped));
  ok('L4 nothing to check on a unit already on site (no noise on finished work)', N.loadNow === 0, N.loadNow);
  ok('T1 the time given is an UNLOADED-BY time: every Full details of a delivery still to come says so; a delivered one does not (its record, not a plan)', keys.filter(k => N.texts[k].future).every(k => /TIME: the time given is when you must be UNLOADED by - not when you arrive\. Unloading takes at least 30 min, so be on site 30 min before it - and no travel to the Gold Coast 07:00-09:00 or 16:00-18:00/.test(N.texts[k].long || '')) && keys.filter(k => !N.texts[k].future).every(k => !/^(TIME|LOAD|DISPATCH):/m.test(N.texts[k].long || '')), keys.filter(k => N.texts[k].future).length + ' to come with the rule · ' + keys.filter(k => !N.texts[k].future && /^(TIME|LOAD|DISPATCH):/m.test(N.texts[k].long || '')).join(',') + ' delivered with it');
  ok('T2 a delivery still to come with a time reads "on site by .., unloaded by .." (30 min to unload), and the check gives the latest Kingston departure (WB04 at 09:00, no load time: in before the 07:00-09:00 window and a morning run away by 05:00, so on site by 06:10)', N.time && /Due [^\n]*, on site by 06:10, unloaded by 09:00/.test(N.time.wb04Sms) && N.time.wb04Check.some(x => /to be unloaded by 09:00: on site by 06:10 \(no travel 07:00-09:00, so in before 07:00; a morning run leaves Kingston by 05:00\), so leave Kingston by 05:00, loaded before then \(70 min run, at least 30 min to unload\)/.test(x)) && /Unloaded by 09:00 - so on site by 06:10 \(no travel 07:00-09:00, so in before 07:00; a morning run leaves Kingston by 05:00\), leave Kingston by 05:00 ?, loaded before then/.test(N.time.wb04Html), JSON.stringify(N.time && {sms: N.time.wb04Sms, check: N.time.wb04Check}));
  ok('T5 a load that would be on the road in a no-travel window is called out with the load-by time (load 07:30 for 09:00: leave Kingston by 05:00)', N.time && N.time.tight.some(x => /load 07:30, on site about 08:40 - on the road in the 07:00-09:00 no-travel window\. Leave Kingston by 05:00, loaded before then\./.test(x)), JSON.stringify(N.time && N.time.tight));
  ok('T7 one plan, one answer: a timed morning load that leaves after 05:00 is called out, even with time to unload (load 05:30 for 09:00)', N.time && N.time.late.some(x => /load 05:30, on site about 06:40 - leaves Kingston after its leave-by time \(no travel 07:00-09:00, so in before 07:00; a morning run leaves Kingston by 05:00\)\. Leave Kingston by 05:00/.test(x)), JSON.stringify(N.time && N.time.late));
  ok('T6 one plan meets every constraint: 30 min to unload, 70 min run, never on the road 07:00-09:00 or 16:00-18:00, and a morning run away from Kingston by 05:00', N.time && N.time.plans.join(' ') === '07:00>06:10/05:00 09:00>06:10/05:00 10:00>06:10/05:00 10:30>06:10/05:00 10:40>10:10/09:00 12:00>11:30/10:20 18:30>16:00/14:50', N.time && N.time.plans.join(' '));
  ok('T3 a load that reaches site after its unloaded-by time is called out (WC05 07:00: tank 08:30 runs into the no-travel window, toilet 09:30 lands after 07:00, as if to come); one that makes it shows its unloading time (P05: 50 min)', N.time && N.time.wc05.length === 2 && N.time.wc05.some(x => /Waste tank: load 08:30, on site about 09:40 - on the road in the 07:00-09:00 no-travel window\. Leave Kingston by 05:00, loaded before then\./.test(x)) && N.time.wc05.some(x => /Toilet Block 6m: load 09:30, on site about 10:40 - AFTER 07:00, when it must already be unloaded\. Leave Kingston by 05:00, loaded before then\./.test(x)) && N.time.p05.some(x => /load 05:00, on site about 06:10 - 50 min to unload before 07:00/.test(x)), JSON.stringify(N.time && {wc05: N.time.wc05, p05: N.time.p05}));
  ok('T4 a delivered record keeps its own words (P03: "on site 07:00")', /Due Mon 14 Sep 2026, on site 07:00/.test(N.texts.P03.t), (N.texts.P03.t.match(/Due[^\n]*/) || ['-'])[0]);
  ok('D1 every Full details of a delivery still to come carries the dispatch rule (no driver leaves without firm directions)', keys.filter(k => N.texts[k].future).every(k => /DISPATCH: no driver leaves the pick-up point without firm instructions - the drop-off location on the map AND the direction point to head for \(the way in\)/.test(N.texts[k].long || '')), keys.filter(k => N.texts[k].future && !/DISPATCH:/.test(N.texts[k].long || '')).join(',') || 'all');
  ok('D2 a delivery with a verified location but no way in is held - in the text, the drawer and Full details (GN04); the label says DIRECTIONS, not ready to send', N.ready && /\nHOLD: way in not set - do not leave until site gives it\./.test(N.ready.gn04.sms) && /Directions MISSING - no direction point \(way in\) set\. No driver leaves until both are set \(Pin the way in, below\)/.test(N.ready.gn04.html) && /DIRECTIONS MISSING: no direction point \(way in\) set\. Hold the truck\./.test(N.ready.gn04.long), JSON.stringify(N.ready && {sms: N.ready.gn04.sms.split('\n').slice(0, 5)}));
  ok('D3 no drop-off yet: the driver is sent to the pit lane (the spot by P33; never named) - text (with P33 GPS and Navigate), driver sheet and Full details (PG01)', N.src && /^No drop-off yet: report to the pit lane\.$/.test(N.src.pg01.sms[0]) && N.src.pg01.sms[1] === 'GPS: ' + N.src.pg01.p33[0].toFixed(6) + ', ' + N.src.pg01.p33[1].toFixed(6) + ' (pit lane)' && N.src.pg01.sheet === 'report' && N.src.pg01.words === 'Report to the pit lane' && /DIRECTIONS SET: no drop-off yet - report to the pit lane/.test(N.ready.pg01.long), JSON.stringify(N.src && N.src.pg01));
  ok('D4 (measure) still to come: ready to send vs not, and why; delivered units are not counted', N.ready && N.ready.delivered === null && N.ready.notReady + N.ready.ready.length === N.ready.nFuture, N.ready && (N.ready.nFuture + ' to come · ' + N.ready.ready.length + ' ready · ' + N.ready.notReady + ' not ready (' + N.ready.noDrop + ' no location, ' + N.ready.noDir + ' no way in) · ready: ' + N.ready.ready.join(',')));
  ok('D5 a drop-off placed at the branch (Edit) reaches the driver sheet as well as the text - it replaces the pit-lane fallback (T0085, in memory only)', N.drops && N.drops.before === 'report' && N.drops.after === 'placed' && N.drops.sheetLat === -27.98 && /^GPS: -27\.980000, 153\.430000 \(placed on the map/.test(N.drops.txt), JSON.stringify(N.drops && {before: N.drops.before, after: N.drops.after, txt: N.drops.txt}));
  ok('D6 (measure) every reference on the driver sheet: exact drop-off (pin, master, placed) vs description (water barriers) vs report to the pit lane', N.drops && N.drops.n > 0, N.drops && (N.drops.n + ' references · ' + Object.entries(N.drops.tally).map(([k, v]) => k + ' ' + v).join(' · ')));
  ok('C1 clocks are always valid, and a time on another day says which (Codex review)', N.time && N.time.clock.join('|') === '23:20|01:05|23:50 the day before|00:10 the next day', N.time && N.time.clock.join('|'));
  ok('C2 a delivery just after midnight plans back into the day before (WB04 unloaded by 00:20: on site by 23:50 the day before, leave Kingston by 22:40 the day before)', N.time && /on site by 23:50 the day before, unloaded by 00:20/.test(N.time.midSms) && N.time.mid.some(x => /on site by 23:50 the day before, so leave Kingston by 22:40 the day before/.test(x)), JSON.stringify(N.time && {sms: N.time.midSms, check: N.time.mid}));
  ok('C3 a load the day before is compared on the calendar, not the clock (23:00 the day before for 09:00: on site 00:10, 530 min to unload)', N.time && N.time.early.some(x => /night load: load 23:00 the day before, on site about 00:10 - 530 min to unload before 09:00\./.test(x)), JSON.stringify(N.time && N.time.early));
  ok('H1 a delivered unit shows its record, not a plan: no Time or Loading row, no time/load checks, no TIME/LOAD/DISPATCH lines (P03)', N.hist && !/\bTime\b Unloaded by|Loading For a morning/.test(N.hist.html) && !N.hist.time.length && !N.hist.load.length && !/^(TIME|LOAD|DISPATCH):/m.test(N.hist.long), JSON.stringify(N.hist && {html: N.hist.html.slice(0, 200)}));
  ok('V1 a position the map review left unverified does not count as a drop-off: LTC01 goes to the pit lane - its source still says not verified, and Navigate names the pit lane it goes to (Codex recheck: the tooltip matches the destination)', N.src && !!N.src.ltc.dirs.report && N.src.ltc.sheet === 'report' && /^No drop-off yet: report to the pit lane/.test(N.src.ltc.sms[0]) && /not verified/.test(N.src.ltc.by) && /pit lane/.test(N.src.ltc.nav) && !/not verified/.test(N.src.ltc.nav), JSON.stringify(N.src && N.src.ltc));
  ok('V2 one source label on every surface: P47 is "confirmed by the project manager" in the text, Navigate, the pin record and the driver sheet', N.src && /confirmed by the project manager/.test(N.src.p47.sms) && /project manager confirmed/.test(N.src.p47.nav) && /the project manager/.test(N.src.p47.by) && N.src.p47.sheet === 'Confirmed position', JSON.stringify(N.src && N.src.p47));
  ok('W1 every water barrier has a drop-off from its description - the spot the master marks, or (WB01, WB05, WB06) looked up from the description; none goes to the pit lane', N.wb && N.wb.length >= 15 && N.wb.every(x => x.drop && (x.sheet === 'desc' || x.sheet === 'pin' || x.sheet === 'placed') && /water barriers: the spot the description names|placed|pinned/.test(x.sms)), JSON.stringify(N.wb && N.wb.map(x => x.k + ':' + x.sheet)));
  ok('W2 "P33" is never shown to a driver for a pit-lane fallback (text, driver sheet, drawer, Full details, sign)', Array.isArray(N.p33seen) && !N.p33seen.length, JSON.stringify(N.p33seen));
  ok('Z1 every location has its way in by area (the project manager, 2 Oct 2026; zones read off the master D001): the island by the pit lane; seaside from the north end; land side and over the bridge from the south end; Gate 1 by the Tedder Ave access point and Gate 2 by the GC Hwy underpass (D007)', N.zones && N.zones.P26 === 'island/pit lane' && N.zones.WC86 === 'island/pit lane' && N.zones.WB06 === 'island/pit lane' && N.zones.WC54 === 'main beach/seaside' && N.zones.WC49 === 'main beach/seaside' && N.zones.WC13 === 'main beach/land side' && N.zones.WB15 === 'main beach/land side' && N.zones.WC30 === 'main beach/land side' && N.zones.P52 === 'gate 1/Tedder Ave' && N.zones.WC68 === 'gate 1/Tedder Ave' && N.zones.P46 === 'gate 2/Gate 2' && N.zones.WC38 === 'gate 2/Gate 2', JSON.stringify(N.zones));
  ok('Z2 only Turn 2 / Ferny Ave and Admiralty Dr still need a way in (not in the rules or D007 - for the project manager)', N.noWay && N.noWay.slice().sort().join(',') === 'GN04,WB07,WB13,WB18,WB20,WC25,WC45,WC47', JSON.stringify(N.noWay));
  ok('M1 the done tick has its own double beat on the master plan', N.css && N.css.pills > 0 && N.css.anim === 'done782', JSON.stringify(N.css));
  ok('M2 the explorer gets the finished list', N.doneKeys > 0, N.doneKeys);
  if (B) {
    const lost = keys.filter(k => B.texts[k] && B.texts[k].link && !N.texts[k].link), lostDue = keys.filter(k => B.texts[k] && B.texts[k].due && !N.texts[k].due);
    ok('R11 (measure) a delivery-details link gives way only where a v7.82 line needs the room (ORDER, ENTRY, HOLD, the pit-lane directions, the spot for a water barrier) (the link stays in Full details)', lost.every(k => /\n(ORDER|ENTRY|HOLD): |\nNo drop-off yet: report to the pit lane|water barriers: the spot the description names/.test(N.texts[k].t) && /Delivery details|card/i.test(N.texts[k].long || '')), lost.join(',') + ' · live ' + keys.filter(k => B.texts[k] && B.texts[k].link).length + ' → ' + keys.filter(k => N.texts[k].link).length);
    ok('R12 no Due line lost against the live page', !lostDue.length, lostDue.join(','));
    const p3 = k => (k.parts === 3 ? 1 : 0); ok('R13 (measure) three-text messages', true, 'live ' + keys.filter(k => B.texts[k] && B.texts[k].parts === 3).length + ' → ' + keys.filter(k => N.texts[k].parts === 3).length);
  }
  ok('E1 no page errors', !N.errors.length && (!B || !B.errors.length), JSON.stringify(N.errors).slice(0, 200));
  T.forEach(t => console.log(`${t.pass ? 'PASS' : 'FAIL'} ${t.name} — ${t.detail.slice(0, 300)}`));
  const passed = T.filter(t => t.pass).length; console.log(`${passed}/${T.length} ${MOB ? 'phone' : 'desktop'}`);
  if (process.env.OUT) fs.writeFileSync(process.env.OUT, JSON.stringify({page: process.env.PAGE, passed, of: T.length, tests: T, samples: Object.fromEntries(['P05','GN20','GN21','WC27','WC50','WC05','P03'].map(k => [k, N.texts[k].t.replace(/https?:\/\/\S+/g, '<url>')]))}, null, 1));
  process.exit(passed === T.length ? 0 : 1);
})().catch(e => { console.error('FAIL', e.message); process.exit(1); });
