# Author: Andrew Fisher
from pathlib import Path
import sys
HERE=Path(__file__).resolve().parent
sys.path.insert(0,str(HERE.parent/'toolchain'))
from rep import rep
p=Path(sys.argv[1]);raw=p.read_bytes();s=raw.decode('utf-8-sig')
assert 'function toiletItem962(' not in s, 'v9.62 already applied'
assert " · v9.61'; /* v8.19" in s and 'function supplierScope961(' in s, 'Requires v9.61 base'
def change(old,new,why):
 global s
 s=rep(s,old,new,why,str(p))
change('function todayWorkMetrics840(asOf) {',(HERE/'toilets962.js').read_text()+'\nfunction todayWorkMetrics840(asOf) {','shared item-level receipt and installation reading')
change("      const conflict = !!d.done && shorts.some(s => selected.some(l => l.item === s.item));", "      const toilet962 = def.id==='toilets' ? toiletRows962(a,d,selected,day) : null;\n      const conflict = toilet962 ? toilet962.conflict : !!d.done && shorts.some(s => selected.some(l => l.item === s.item));",'item conflict scope')
change('      const complete = !!d.done && !conflict && !split900r;\n      const contribution = complete ? known : split900r ? Math.max(0, known - split900r.withheld) : 0;', '      const complete = toilet962 ? toilet962.complete : !!d.done && !conflict && !split900r;\n      const contribution = toilet962 ? toilet962.done : complete ? known : split900r ? Math.max(0, known - split900r.withheld) : 0;', 'preserve installed item quantities inside mixed reference')
change("      const status = conflict ? 'Completion tick", "      const status = toilet962 ? toilet962.status : conflict ? 'Completion tick", 'toilet status follows item evidence')
change('      const detail = [split900r ?', '      const detail = toilet962 ? toilet962.detail : [split900r ?', 'replace stale scheduled due wording for received items')
change('quantity: rowUnknown ? null : known, knownQuantity: known, complete, recordedComplete: !!d.done && !split900r,', 'quantity: rowUnknown ? null : known, knownQuantity: known, complete, recordedComplete: !!d.done && !split900r,\n        ...(toilet962 ? {arrived962:toilet962.arrived, reviewQuantity962:toilet962.reviewQuantity, items962:toilet962.rows} : {}),', 'surface item receipt and narrowly scoped review quantity')
change('const reviewQuantity = health.ready && reviewKnown ? round(conflicts.reduce((n, r) => n + r.quantity, 0)) : null;', 'const reviewQuantity = health.ready && reviewKnown ? round(conflicts.reduce((n, r) => n + (r.reviewQuantity962 == null ? r.quantity : r.reviewQuantity962), 0)) : null;', 'review only unsupported item quantities')
change("      basis: 'Confirmed complete uses the existing conflict-free Complete ticks. Not confirmed includes outstanding work and any quantity requiring review; it does not infer partial installation.',", "      ...(area.id==='toilets' ? {arrived962:rows.reduce((n,r)=>n+(r.arrived962||0),0), arrivalNote962:'Received quantities and installed quantities are separate; assigned fleet numbers are not receipts.'} : {}),\n      basis: area.id==='toilets' ? 'Installed quantities use recorded completion for the item scope, or dated item installation supported by the supplied quantity. Received and assigned are separate.' : 'Confirmed complete uses the existing conflict-free Complete ticks. Not confirmed includes outstanding work and any quantity requiring review; it does not infer partial installation.',", 'summary receipt and completion basis')
change('      const onSite = !!d.done || !!(d.recorded && d.state === \'on site\' && d.where !== \'rental\');', "      const onSite = row.arrived962!=null && row.quantity!=null ? row.arrived962>=row.quantity : !!d.done || !!(d.recorded && d.state === 'on site' && d.where !== 'rental');", 'complete arrival plan requires every counted item')
# Shared native quantity readings (money, records and reference lights are retained).
change(' const unitsOn = [...onBy.values()].reduce((n, v) => n + v, 0);', " if (a.product==='Toilet'||a.discipline==='Toilets & amenities') for(const item of askedBy.keys()) onBy.set(item,toiletArrival962(a,item,asOf,onBy.get(item)||0));\n const unitsOn = [...onBy.values()].reduce((n, v) => n + v, 0);", 'native item arrivals')
change('onq: on ? (sup != null ? sup + restArrived(a, l.item) : asked) : 0', 'onq: toiletArrival962(a,l.item,td,on ? (sup != null ? sup + restArrived(a, l.item) : asked) : 0)', 'Equipment Inventory receipts')
change('_on:!!(a&&!a._cancelled&&invOnSite(a,asAt)),_spare:false', '_on:!!(a&&!a._cancelled&&toiletSupplierArrived962(a,description(a,u,all),asAt)),_spare:false', 'supplier receipts never follow assignment alone')
change('...pos,status,qty:1,warning:[pos.warning,a&&a._cancelled?', "...pos,status:toiletSupplierStatus962(a,description(a,u,all),asAt,status),qty:1,warning:[pos.warning,a&&a._cancelled?", 'supplier assigned arrival status')
# Group/type instruments use the same reading as the main card.
change('        const conflict = matchedShort || !!r.d.done && main && main.recordedComplete && !main.complete;', "        const toilet962 = name==='Toilets & amenities' ? toiletItem962(r.a,item,r.d,day,r.onBy.get(item)||0) : null;\n        const conflict = toilet962 ? toilet962.conflict : matchedShort || !!r.d.done && main && main.recordedComplete && !main.complete;", 'group item conflicts')
change('if (r.d.done && !conflict) type.knownComplete += Math.max(0, quantity - (split900g && split900g.items.get(item) || 0));', 'if (toilet962) type.knownComplete += toilet962.done;\n        else if (r.d.done && !conflict) type.knownComplete += Math.max(0, quantity - (split900g && split900g.items.get(item) || 0));', 'group installed quantity')
change('          const conflict = itemShort || referenceReview;', "          const toilet962 = cardId==='toilets' ? toiletItem962(native.a,type.name,d,day,native.onBy.get(type.name)||0) : null;\n          const conflict = toilet962 ? toilet962.conflict : itemShort || referenceReview;", 'type item conflicts')
change('          const complete = recordedComplete && !conflict && !held900;\n          const done = unitKnown ? (complete ? knownQuantity : held900 ? Math.max(0, knownQuantity - held900) : 0) : null;', '          const complete = toilet962 ? toilet962.complete : recordedComplete && !conflict && !held900;\n          const done = toilet962 ? toilet962.done : unitKnown ? (complete ? knownQuantity : held900 ? Math.max(0, knownQuantity - held900) : 0) : null;', 'type installed quantity')
change("if (itemShort) rowIssues.push('This item has a recorded shortage; its Complete tick requires review.');", "if (itemShort && conflict) rowIssues.push('This item has a recorded shortage; its Complete tick requires review.');", 'shortage review follows the item completion scope')
change("          else if (referenceReview) rowIssues.push('Completion on this shared reference requires review; this item is not separately claimed to be short.');", "          else if (referenceReview && !toilet962) rowIssues.push('Completion on this shared reference requires review; this item is not separately claimed to be short.');", 'do not propagate unrelated item shortage')
change('          const status = conflict ? itemShort ?', '          const status = toilet962 ? toilet962.status : conflict ? itemShort ?', 'type receipt/install status')
change('onSite, complete, recordedComplete: recordedComplete && !held900, conflict, conflictReason:', 'onSite, complete, recordedComplete: recordedComplete && !held900, ...(toilet962 ? {reviewQuantity962:toilet962.reviewQuantity, arrived962:toilet962.arrived} : {}), conflict, conflictReason:', 'type review quantity')
change("conflictReason: itemShort ? 'item-short' : referenceReview ? 'reference-review' : null,", "conflictReason: !conflict ? null : itemShort ? 'item-short' : referenceReview ? 'reference-review' : null,", 'type reason agrees with item conflict')
change("const basis = 'Each source type retains its own quantity. Confirmed completion follows the reference Complete tick, excluding item shortages and shared-reference completion reviews. On site / on hire retains the native rental-or-person item reading; it is not installation evidence.';", "const basis = cardId==='toilets' ? 'Received quantities follow item receipts and the dated reference scope. Installed quantities follow recorded completion for that item or dated item installation supported by the supplied quantity. Assigned numbers do not establish arrival.' : 'Each source type retains its own quantity. Confirmed completion follows the reference Complete tick, excluding item shortages and shared-reference completion reviews. On site / on hire retains the native rental-or-person item reading; it is not installation evidence.';", 'type basis')
# Read-only reference status preserves the old stored tick without claiming the mixed location finished.
change("p=timeline841Proof(a.key),v=timeline841Project({asset:a,delivery:d,proof:p,conflict:d.done?timeline841CompletionConflict(a):[]});if(p", "p=timeline841Proof(a.key),v=toiletProgressView962(a,d,timeline841Project({asset:a,delivery:d,proof:p,conflict:d.done?timeline841CompletionConflict(a):[]}));if(p", 'Timeline item-scope status')
change("if (d.done) t.push('<i class=\"ld-tk\" title=\"Complete\">✓</i>');", "if (d.done) { const x=toiletRows962(a,d,chargeLines(a),todayIso()); t.push(x&&!x.complete?'<i class=\"ld-tk sh\" title=\"'+esc(x.status)+'\">'+x.done+'/'+x.quantity+' installed</i>':'<i class=\"ld-tk\" title=\"Complete\">✓</i>'); }", 'Timeline does not show an unqualified Complete tick')
change("const labels=[v.arrived?'On Site':'Off Site','Transit','Location','Installed','Finished'];", "const labels=[v.partial962&&!v.arrived?'Part received':v.arrived?'On Site':'Off Site','Transit','Location','Installed','Finished'];", 'partial receipt light caption')
change("+' planned')+'</p>'+Source949.note(a.key)", "+' planned')+'</p>'+toiletScopeHtml962(a)+Source949.note(a.key)", 'drawer item receipt and installation explanation')
# Other shared read-only badges and counts use the same partial-scope reading.
change(" const P = DSTATE[semantic];", " const partial962=toiletPresentation962(a&&a.key?a:assetOf(key),d,todayIso());\n const P = partial962 ? {...DSTATE[semantic],c:'amber',word:'Part received / installed',label:partial962.status,pill:'plan',negative:false} : DSTATE[semantic];", 'delivery badge item scope')
change(" const title = `Complete — ticked ${fmtStamp(d.done_at)}", " const partial962=toiletPresentation962(a&&a.key?a:assetOf(a),d,todayIso());\n if(partial962)return '<span class=\"chip act\" title=\"'+esc(partial962.detail)+'\">'+partial962.done+'/'+partial962.quantity+' installed</span>'+shortChip(a);\n const title = `Complete — ticked ${fmtStamp(d.done_at)}", 'shared Complete chip truth')
change("live.forEach(a => { const d = asOf ? deliveryAsOf(a.key, asOf) : deliveryOf(a.key);\n if (!d.recorded) t.none++; else t[d.c]++;\n if (d.done) t.done++;", "live.forEach(a => { const d = asOf ? deliveryAsOf(a.key, asOf) : deliveryOf(a.key), partial962=toiletPresentation962(a,d,asOf||todayIso());\n if (!d.recorded) t.none++; else t[partial962?'amber':d.c]++;\n if (d.done&&!partial962) t.done++;", 'verified complete and partial receipt tally')
change("const d = deliveryOf(a.key);\n /* the filter matches the counts above it:", "const d = deliveryOf(a.key), partial962=toiletPresentation962(a,d,todayIso());\n /* the filter matches the counts above it:", 'filter uses same partial scope')
change("state.light === 'done' ? d.done\n : state.light", "state.light === 'done' ? d.done&&!partial962\n : state.light", 'Complete filter agrees with tally')
change(": (d.recorded && d.c === state.light);", ": (d.recorded && (partial962?'amber':d.c) === state.light);", 'partial amber filter')
change("${btn('amber', 'amber', 'In transit', t.amber, 'on the truck, between the yard and the gate')}", "${btn('amber', 'amber', 'Transit / incomplete', t.amber, 'in transit or a mixed reference not wholly received and installed')}", 'amber count scope')
change("const ticks = [d.done ? '<span class=\"tick\">✓ Complete</span>' : '', levelChip(a)", "const partial962=toiletPresentation962(a,d,todayIso());\n\tconst ticks = [doneChip(a), levelChip(a)", 'drawer shares truthful completion chip')
change("+ (d.state === 'on site' ? ' · arrived' : '') + (d.eta", "+ (partial962 ? ' · '+partial962.arrived+'/'+partial962.quantity+' received' : d.state === 'on site' ? ' · arrived' : '') + (d.eta", 'drawer receipt date qualifier')
change("const word = a._cancelled ? 'Cancelled' : d.recorded ?", "const word = a._cancelled ? 'Cancelled' : partial962 ? partial962.status : d.recorded ?", 'drawer summary truth')
change("trow('done', 'done', d.done, 'complete', d.done_at, '✓')", "trow('done', 'done', d.done, partial962?'stored Complete tick · item scope shown above':'complete', d.done_at, '✓')", 'retain editable stored tick with explicit scope')
change("<h3>Complete it</h3><span class=\"chip ${got === of ? 'ok' : 'ref'}\">${got} of ${of}</span>", "<h3>${partial962?'Recorded checks':'Complete it'}</h3><span class=\"chip ${!partial962&&got === of ? 'ok' : 'ref'}\">${partial962?'Item scope incomplete':got+' of '+of}</span>", 'drawer checks do not claim full completion')
change("signalHead({green: d.recorded && d.state === 'on site' ? 1 : 0, amber: d.recorded && d.state === 'in transit' ? 1 : 0, red: d.recorded && d.state === 'not on site' ? 1 : 0})", "signalHead({green: !partial962&&d.recorded && d.state === 'on site' ? 1 : 0, amber: partial962||d.recorded && d.state === 'in transit' ? 1 : 0, red: d.recorded && d.state === 'not on site' ? 1 : 0})", 'drawer partial scope amber light')
change("lines.push({k: 'Finished', text: d.done ? (who(d.done_by, d.done_at) || 'Complete recorded') : 'Complete check still open', done: !!d.done});", "lines.push({k: v.partial962 ? 'Item progress' : 'Finished', text: v.partial962 ? v.label+' · '+v.why : d.done ? (who(d.done_by, d.done_at) || 'Complete recorded') : 'Complete check still open', done: !!d.done&&!v.partial962});", 'map progress matches Timeline item scope')
change("lamps: [v.arrived ? 'On site' : 'Off site', 'Transit', 'Location', 'Installed', 'Finished']", "lamps: [v.partial962&&!v.arrived ? 'Part received' : v.arrived ? 'On site' : 'Off site', 'Transit', 'Location', 'Installed', 'Finished']", 'map lamp matches item receipts')
change("lines.push({k: L, text: who(d.by, d.set_at) || 'recorded', done: d.state === 'on site'});", "lines.push({k: v.partial962?'Item receipts':L, text: v.partial962?v.why:who(d.by, d.set_at) || 'recorded', done: d.state === 'on site'&&!v.partial962});", 'map arrival row scope')
change("lines.push({k: proof.stage === 4 ? 'Installed' : 'At location', text: who(proof.by, proof.recorded_at || proof.at) || 'confirmed', done: true});", "lines.push({k: v.partial962?'Earlier scope record':proof.stage === 4 ? 'Installed' : 'At location', text: who(proof.by, proof.recorded_at || proof.at) || 'confirmed', done: !v.partial962});", 'map previous installation remains historical')
change("outcomeParts.push(fmtNum(t.amber) + ' in transit');", "outcomeParts.push(fmtNum(t.amber) + ' in transit / incomplete');", 'daily brief amber scope')
change("['plan', t.amber + ' in transit']", "['plan', t.amber + ' in transit / incomplete']", 'attention amber scope')
change("kpi(all.amber, 'amber · in transit')", "kpi(all.amber, 'amber · transit / incomplete')", 'calendar amber scope')
change("one('amber', t.amber, 'In transit', 'somebody recorded it as on its way')", "one('amber', t.amber, 'Transit / incomplete', 'in transit or item receipt and installation are not complete')", 'signals amber scope')
# Current day pod counts schedule entries; partial toilet entries are not wholly arrived.
change(" const due = show ? show.deliveries : [];\n const onsite = due.filter(r => { const d = deliveryOf(r.a.key); return d.recorded && d.state === 'on site'; }).length;", " const due = show ? show.deliveries : [];\n const onsite = due.filter(r => { const item=toiletDeliveryEntry962(r,today); if(item!=null)return item; const d = deliveryOf(r.a.key); return d.recorded && d.state === 'on site'; }).length;", 'day pod complete item receipts')
change(" const rows = (d.deliveries || []).map(r => ({a: r.a, d: deliveryOf(r.a.key), v: deliveryView(r.a)}))", " const rows = (d.deliveries || []).map(r => ({a: r.a, d: deliveryOf(r.a.key), v: deliveryView(r.a), receipt962:toiletDeliveryEntry962(r,todayIso())}))", 'day attention shared receipts')
change('.filter(r => r.v.negative || !r.v.recorded);', '.filter(r => r.receipt962===false || r.v.negative || !r.v.recorded);', 'partial toilet arrival remains visible')
change(" const split = [waiting ? fmtNum(waiting) + ' with no record' : null, redDue ? fmtNum(redDue) + ' recorded not on site' : null].filter(Boolean).join(' · ');", " const partial962 = due.filter(r=>toiletDeliveryEntry962(r,today)===false&&deliveryOf(r.a.key).recorded).length;\n const split = [waiting ? fmtNum(waiting) + ' with no record' : null, redDue ? fmtNum(redDue) + ' recorded not on site' : null, partial962 ? fmtNum(partial962)+' toilet entries not fully received' : null].filter(Boolean).join(' · ');", 'explain partial day receipts')
# Quantity-only pee panels: this is a receipt, not an identity task.
change(" const g=model.groups.find(g=>g.item===choice),photos=dropPhotosOf(a.key)", " const g=model.groups.find(g=>g.item===choice), quantityOnly962=a.key==='WC09'&&g.item==='Pee Panel', receipt962=quantityOnly962?toiletItem962(a,g.item,deliveryAsOf(a.key,todayIso()),todayIso()):null,photos=dropPhotosOf(a.key)", 'quantity-only drawer reading')
change("g.units.filter(u=>u.physical).length+' identified'+(g.quantity==null?'':' · '+g.quantity+' planned')", "(quantityOnly962?(receipt962?.arrived||0)+' received · quantity only; no fleet numbers':g.units.filter(u=>u.physical).length+' identified')+(g.quantity==null?'':' · '+g.quantity+' planned')", 'pee panel received quantity')
change("+(g.pending?'<p class=\"units925-warning\">'", "+(!quantityOnly962&&g.pending?'<p class=\"units925-warning\">'", 'no identity prompt for quantity-only panels')
change("+(!SYNC.readonly?'<details class=\"units925-edit\"><summary>Identify another physical unit</summary>'", "+(!SYNC.readonly&&!quantityOnly962?'<details class=\"units925-edit\"><summary>Identify another physical unit</summary>'", 'no serial form for quantity-only panels')
change("filter(g=>items.includes(g.item)&&g.pending>0)", "filter(g=>items.includes(g.item)&&g.pending>0&&!(ref==='WC09'&&g.item==='Pee Panel'))", 'supplier pending identity excludes quantity-only panels')
# Existing card layout; show actual receipt and installation bases, not another layout.
change("+ compactPlan847(summary.plan);", "+ (area.id==='toilets'&&number(summary.arrived962)?'<p class=\"tw846-row-note\" data-toilet962-receipts><b>'+format(summary.arrived962)+' received</b> · '+format(summary.done)+' installed. Assigned numbers do not establish arrival. Left includes installation not yet recorded. Separate waste tanks are excluded from this toilet total.</p>':'') + compactPlan847(summary.plan);", 'clear arrival versus installation on Today')
change("+ '</strong> Done</span><span><strong data-tw848-quantity=\"left\">'", "+ '</strong> '+(area.id==='toilets'?'Installed':'Done')+'</span><span><strong data-tw848-quantity=\"left\">'", 'closed toilet card completion label')
change(" · v9.61'; /* v8.19", " · v9.62'; /* v8.19", 'footer')
p.write_bytes((b'\xef\xbb\xbf' if raw.startswith(b'\xef\xbb\xbf') else b'')+s.encode())
