// Author: Andrew Fisher. Read-only concise figures, source disclosures and controls.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {installWriteGuard,ready840,nativeSnapshot}=require('../v8.40_today_work_progress_LIVE/test_today840.cjs');
const {immutable,localState,guideRows}=require('../v8.49_fencing_components_LIVE/test_components849_browser.cjs');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),canon=x=>Array.isArray(x)?'['+x.map(canon)+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canon(x[k])).join(',')+'}':JSON.stringify(x),same=(a,b)=>canon(a)===canon(b);
const {PAGE,BASE,OUT,CANDIDATE_SHA}=process.env,day=process.env.AS_OF||'2026-10-05',live=process.env.LIVE==='1';
const baseHash='1c2a663221e3f9d9f0e375905037a427c3b7a2ccb11de3e1077928342aaa92bc',section=s=>'[data-fc849-scope="'+s+'"]';
async function route(p,scope){await p.evaluate(s=>go(s),scope);if(scope==='today'){const d=p.locator('[data-tw848-group-fold="fencing"]');if(!await d.evaluate(e=>e.open))await d.locator(':scope > summary').click();}await p.locator(section(scope)).waitFor({state:'visible'});}
async function openFold(p,scope,key){const d=p.locator(section(scope)+' [data-fc849-fold="'+key+'"]');if(!await d.evaluate(e=>e.open))await d.locator(':scope > summary').click();await p.waitForFunction(({scope,key})=>FENCE_COMPONENTS_VIEW849.folds.get(scope+':'+key)===true,{scope,key});return d;}
async function snapshot(p){return {base:await immutable(p,day),native:await nativeSnapshot(p),models:await p.evaluate(day=>({components:fenceComponents849(day),issues:fenceComponentEvidence849(day),po:fencePoGateEvidence850(day),guide:fenceGuide849({length:100,gatePanels:2,gateOpenings:2,layout:'straight',braced:true})}),day)};}
function intact(a,b){return same(a.base,b.base)&&same(a.native.collections,b.native.collections)&&same(a.native.functions,b.native.functions)&&same(a.native.media,b.native.media)&&same(a.models,b.models);}
async function readings(p,scope){return p.locator(section(scope)).evaluate(e=>({counts:[...e.querySelectorAll('[data-fc849-count]')].map(n=>[n.dataset.fc849Count,n.textContent]),rows:[...e.querySelectorAll('[data-fc850-matched],[data-fc850-conflict]')].map(r=>({id:r.dataset.fc850Matched||r.dataset.fc850Conflict,links:[...r.querySelectorAll('a[href]')].map(a=>a.href),details:[...r.querySelectorAll('p')].map(n=>n.textContent)})),accepted:e.querySelector('[data-fc850-accepted-total]')?.textContent,conflicts:e.querySelector('[data-fc850-conflict-total]')?.textContent,narrative:e.innerText,allText:e.textContent,paragraphs:[...e.querySelectorAll(':scope > p')].map(n=>n.textContent)}));}
function linkCovered(old,links){const o=new URL(old);return links.some(href=>{const n=new URL(href);return o.hash?n.href===o.href:n.origin+n.pathname+n.search===o.origin+o.pathname+o.search;});}
(async()=>{
 if(!PAGE||!BASE||!OUT||!CANDIDATE_SHA||hash(fs.readFileSync(PAGE))!==CANDIDATE_SHA||hash(fs.readFileSync(BASE))!==baseHash)throw Error('Frozen candidate/base/OUT required');
 fs.mkdirSync(OUT,{recursive:true});const report={author:'Andrew Fisher',candidate:CANDIDATE_SHA,base:baseHash,live,checks:[],views:[]},save=()=>fs.writeFileSync(path.join(OUT,'notes851.json'),JSON.stringify(report,null,2));
 const check=(name,pass,evidence)=>{report.checks.push({name,pass:!!pass,evidence});save();console.log((pass?'PASS ':'FAIL ')+name);};
 const guard=installWriteGuard(),{open}=require('../toolchain/harness/open_page.js');let s;
 try{
  s=await open({pageFile:BASE,hash:'#today',W:1366,H:900});await ready840(s.page);await s.page.waitForFunction(()=>DOCS.state==='ready');await s.page.evaluate(day=>{state.asOf=day;renderToday();},day);const baseline=await snapshot(s.page),baseReadings={};
  for(const scope of ['today','fencing']){await route(s.page,scope);baseReadings[scope]=await readings(s.page,scope);}await s.browser.close();s=null;
  for(const view of [{name:'laptop',W:1366,H:900},{name:'phone',W:390,H:844,dpr:2,mobile:true}]){
   s=await open({pageFile:live?undefined:PAGE,hash:'#today',...view});const p=s.page;await ready840(p);await p.waitForFunction(()=>DOCS.state==='ready');await p.evaluate(day=>{state.asOf=day;renderToday();},day);
   const upstream=guard.fulfilledDocuments.at(-1);check(view.name+' frozen document identity and intended source mode',upstream.sha===CANDIDATE_SHA&&(live?s.counts.page===0:s.counts.page>0),upstream);
   const before=await snapshot(p);check(view.name+' all recorded quantities, eight readings, money and model outputs unchanged',intact(baseline,before));
   const routes=[];
   for(const scope of ['today','fencing']){
    await route(p,scope);const host=p.locator(section(scope)),current=await readings(p,scope),prior=baseReadings[scope];
    check(view.name+' '+scope+' every recorded and collected count remains exact',same(current.counts,prior.counts)&&current.accepted===prior.accepted&&current.conflicts===prior.conflicts,current.counts);
    check(view.name+' '+scope+' main figures are concise and explanatory notes start closed',await host.locator('[data-fc849-fold="count-notes"]').evaluate(e=>!e.open)&&current.paragraphs.length===0&&current.narrative.length<prior.narrative.length,{before:prior.narrative.length,after:current.narrative.length});
    const countNotes=await openFold(p,scope,'count-notes');
    const noteText=await countNotes.textContent();check(view.name+' '+scope+' original count caveats remain available in notes',prior.paragraphs.every(t=>noteText.includes(t)),prior.paragraphs);
    const summary=countNotes.locator(':scope > summary');await summary.focus();await p.keyboard.press('Space');await p.waitForFunction(s=>FENCE_COMPONENTS_VIEW849.folds.get(s+':count-notes')===false,scope);const closed=await countNotes.evaluate(e=>!e.open);await p.keyboard.press('Enter');await p.waitForFunction(s=>FENCE_COMPONENTS_VIEW849.folds.get(s+':count-notes')===true,scope);
    check(view.name+' '+scope+' note disclosure supports Space and Enter keyboard controls',closed&&await countNotes.evaluate(e=>e.open));
    const focusBefore=await p.evaluate(()=>({token:document.activeElement?.dataset.tw840Focus,top:document.querySelector('main').scrollTop}));await p.evaluate(s=>s==='today'?renderToday():renderFencing(),scope);await p.waitForTimeout(120);
    const focusAfter=await p.evaluate(()=>({token:document.activeElement?.dataset.tw840Focus,top:document.querySelector('main').scrollTop}));
    check(view.name+' '+scope+' native redraw retains open note, keyboard focus and scroll',await host.locator('[data-fc849-fold="count-notes"]').evaluate(e=>e.open)&&focusAfter.token===focusBefore.token&&Math.abs(focusAfter.top-focusBefore.top)<=1,{before:focusBefore,after:focusAfter});
    await host.locator('[data-fc849-fold="count-notes"] > summary').click();await openFold(p,scope,'po-quantities');
    const unitNotes=host.locator('[data-fc849-fold="po-unit-notes"]');check(view.name+' '+scope+' P/O rows show numbers with unit explanations and More notes folded',await unitNotes.evaluate(e=>!e.open)&&await host.locator('[data-fc850-matched] [data-fc851-notes][open]').count()===0);
    const links=await readings(p,scope);check(view.name+' '+scope+' source-link dedup preserves each original document and reviewed page',prior.rows.every(r=>{const n=links.rows.find(n=>n.id===r.id);return n&&r.links.every(url=>linkCovered(url,n.links));})&&links.rows.some(n=>n.links.length<prior.rows.find(r=>r.id===n.id).links.length),{before:prior.rows.map(r=>({id:r.id,links:r.links.length})),after:links.rows.map(r=>({id:r.id,links:r.links.length}))});
    check(view.name+' '+scope+' source explanations remain inside More for every matched and conflict row',before.models.po.accepted.every(r=>host&&links.allText.includes(r.detail))&&before.models.po.conflicts.every(r=>links.allText.includes(r.reason)));
    await openFold(p,scope,'po-unit-notes');const unitBody=await unitNotes.textContent();check(view.name+' '+scope+' unchanged source quote, unit explanation and original programme link available',unitBody.includes(before.models.po.unitEvidence.noteAsWritten)&&unitBody.includes(before.models.po.unitEvidence.conclusion)&&await unitNotes.locator('[data-fc850-unit-evidence] a[href]').count()>0);
    const first=host.locator('[data-fc850-matched] [data-fc851-notes]').first(),key=await first.getAttribute('data-fc849-fold');await openFold(p,scope,key);const more=first.locator(':scope > summary');await more.focus();await p.keyboard.press('Space');await p.waitForFunction(({s,k})=>FENCE_COMPONENTS_VIEW849.folds.get(s+':'+k)===false,{s:scope,k:key});await p.keyboard.press('Enter');await p.waitForFunction(({s,k})=>FENCE_COMPONENTS_VIEW849.folds.get(s+':'+k)===true,{s:scope,k:key});
    check(view.name+' '+scope+' nested More disclosure works independently by keyboard',await first.evaluate(e=>e.open)&&await unitNotes.evaluate(e=>e.open));
    const g=await localState(p,scope);check(view.name+' '+scope+' expanded notes and source rows fit viewport',g.documentWidth<=g.width+1&&g.scroll<=g.client+1,g);
    await host.locator('h4').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(OUT,view.name+'-'+scope+'-figures.png')});await host.locator('[data-fc850-evidence] > summary').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(OUT,view.name+'-'+scope+'-notes.png')});
    await openFold(p,scope,'guide');const form=host.locator('[data-fc849-guide]');for(const [k,v]of Object.entries({length:'100',gatePanels:'2',gateOpenings:'2'}))await form.locator('[name="'+k+'"]').fill(v);await form.locator('[name="braced"]').setChecked(true);const guide=guideRows(await localState(p,scope));check(view.name+' '+scope+' existing unsaved planner and corrected allowances remain usable',guide['Total panels']==='42'&&guide['Line feet / blocks']==='43'&&guide['Braces / stays']==='27–28',guide);
    routes.push({scope,current,focusBefore,focusAfter,guide});
   }
   await route(p,'fencing');const overview=p.locator('[data-tw847-category-overview]');check(view.name+' CCB explanation appears once inside closed Count notes',await overview.count()===1&&await overview.evaluate(e=>e.closest('[data-fc849-fold]').dataset.fc849Fold==='count-notes'));const c=p.locator('[data-fc849-scope="fencing"] [data-fc849-fold="count-notes"]');if(await c.evaluate(e=>e.open))await c.locator(':scope > summary').click();check(view.name+' CCB explanation hidden until notes opened',!await overview.isVisible());await c.locator(':scope > summary').click();check(view.name+' original CCB explanation available when opened',await overview.isVisible());await p.screenshot({path:path.join(OUT,view.name+'-ccb-notes.png')});
   await route(p,'today');const state=await localState(p,'today');check(view.name+' route return retains supplementary note state and unsaved guide',state.open.includes('po-unit-notes')&&state.open.includes('guide')&&state.values.length==='100');
   await p.evaluate(()=>go('prestarts'));const filing=await openFold(p,'prestarts','filing-notes');
   check(view.name+' Pre-starts shows one common view-only instruction',await p.locator('[data-clean851-read-notice]').count()===1&&await p.locator('#pane-prestarts [data-preup]').count()===0);
   await filing.locator(':scope > summary').focus();await p.keyboard.press('Space');await p.waitForFunction(()=>FENCE_COMPONENTS_VIEW849.folds.get('prestarts:filing-notes')===false);await p.keyboard.press('Enter');await p.waitForFunction(()=>FENCE_COMPONENTS_VIEW849.folds.get('prestarts:filing-notes')===true);
   const filingBefore=await p.evaluate(()=>({token:document.activeElement?.dataset.tw840Focus,top:document.querySelector('main').scrollTop}));await p.evaluate(()=>renderPrestarts());
   const filingAfter=await p.evaluate(()=>({token:document.activeElement?.dataset.tw840Focus,top:document.querySelector('main').scrollTop}));
   check(view.name+' Pre-starts filing instructions retain keyboard focus, open state and scroll on redraw',filingBefore.token===filingAfter.token&&Math.abs(filingBefore.top-filingAfter.top)<=1&&await p.locator('[data-fc849-fold="filing-notes"]').evaluate(e=>e.open),{before:filingBefore,after:filingAfter});
   await route(p,'today');const after=await snapshot(p);check(view.name+' every disclosure and guide interaction leaves records and financial outputs unchanged',intact(before,after));check(view.name+' zero JavaScript errors',s.errors.length===0,s.errors);report.views.push({view,routes});await s.browser.close();s=null;
  }
 }catch(e){check('Focused disclosure audit completed',false,e.stack);}finally{if(s)await s.browser.close();await guard.closeAll();report.guard=guard;check('All non-GET requests blocked and no operational write attempts',guard.nonGetSeen.length===guard.blocked.length&&!guard.nonGetSeen.some(r=>r.operational),guard.nonGetSeen);const unexpected=guard.consoleErrors.filter(e=>!(/Failed to load resource: net::ERR_BLOCKED_BY_CLIENT/.test(e.text)&&guard.blocked.some(b=>!b.operational&&b.url===e.url)));check('No unexpected console errors',!unexpected.length,unexpected);report.passed=report.checks.filter(c=>c.pass).length;report.total=report.checks.length;save();console.log(JSON.stringify({passed:report.passed,total:report.total,out:OUT}));if(report.passed!==report.total)process.exitCode=1;}
})().catch(e=>{console.error(e.message);process.exitCode=2;});
