// Author: Andrew Fisher. Exact combined Map candidate. No operational writes; no credential URLs recorded.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{chromium}=require('playwright');
const OUT='/workspace/private-maps813/3d/settled-remaining',SRC='/workspace/private-maps813/audit/frozen813b',HOST='https://gc500-production.up.railway.app';
fs.mkdirSync(OUT,{recursive:true});process.env.GC500_CACHE=OUT+'/curl-cache';
const {curlFetch}=require('/workspace/gc500-showcase-full-lap/03_GC500_Delivery_Control/toolchain/harness/curlfetch');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const report={author:'Andrew Fisher',sources:Object.fromEntries(['index.html','explorer.js','explorer-merge.js','poc3d__index.html'].map(f=>[f,sha(SRC+'/'+f)])),checks:[],errors:[],blockedWrites:0,childDocs:0,childKeyRequests:0,rootTileRequests:0,limits:['Headless Chromium software renderer; no physical-device performance claim.','Google tile session POST allowed; operational writes blocked.']};
const check=(n,v,detail)=>{report.checks.push({name:n,pass:!!v,detail});if(!v)throw Error(n)},safe=s=>String(s).replace(/https?:\/\/\S+/g,'[URL]').replace(/AIza[\w-]+/g,'[redacted]');
let browser,failChildKey=false;
(async()=>{
browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:2,isMobile:true,hasTouch:true,locale:'en-AU',timezoneId:'Australia/Brisbane'});
await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url()),method=req.method();if(['data:','blob:'].includes(u.protocol))return route.continue();if(method!=='GET'&&!(method==='POST'&&u.origin==='https://tile.googleapis.com'&&u.pathname==='/v1/createSession')){report.blockedWrites++;return route.abort()}
try{let f=null;if(u.origin===HOST){if(u.pathname.endsWith('/explorer/index.html'))f='index.html';else if(u.pathname.endsWith('/explorer/explorer.js'))f='explorer.js';else if(u.pathname.endsWith('/explorer/explorer-merge.js'))f='explorer-merge.js';else if(u.pathname.endsWith('/poc3d/index.html')){f='poc3d__index.html';report.childDocs++}
if(u.pathname==='/api/map-key'&&req.frame().url().includes('/poc3d/')){report.childKeyRequests++;if(failChildKey){failChildKey=false;return route.fulfill({status:503,contentType:'application/json',body:'{"error":"fixture temporary unavailable"}'})}}}
if(u.hostname==='tile.googleapis.com'&&u.pathname==='/v1/3dtiles/root.json')report.rootTileRequests++;
if(f)return route.fulfill({status:200,contentType:f.endsWith('.js')?'application/javascript':'text/html',body:fs.readFileSync(f==='poc3d__index.html'?'/workspace/private-maps813/3d/candidate/poc3d/index.html':SRC+'/'+f)});
return route.fulfill(await curlFetch(req.url(),req.headers(),method,req.postData()));
}catch(e){try{await route.abort()}catch{}}});
report.sources['poc3d__index.html']=sha('/workspace/private-maps813/3d/candidate/poc3d/index.html');
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(safe(e.message)));
await page.goto(HOST+'/w/Coates-GC500-2026/explorer/index.html?embed=1&back=v#hybrid',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__ready&&document.querySelector('[data-mode="3d"]'),null,{timeout:120000});
await page.locator('[data-mode="3d"]').click();await page.waitForFunction(()=>document.querySelector('#model3d')?.contentWindow?.__ready===true,null,{timeout:120000});let child=page.frames().find(f=>f.url().includes('/poc3d/'));
const metrics=()=>child.evaluate(()=>({loaded:!!window.__allLoaded,tilesLoaded:!!tileset.tilesLoaded,tilesReceived:perf.tilesLoaded,adapt:GC500_3D.state.adapt,quality:GC500_3D.state.quality,dpr:devicePixelRatio,canvas:{w:viewer.canvas.width,h:viewer.canvas.height,cssW:viewer.canvas.clientWidth,cssH:viewer.canvas.clientHeight},cameraHeight:viewer.camera.positionCartographic.height,requests:tileset._statistics?{pending:tileset._statistics.numberOfPendingRequests,processing:tileset._statistics.numberOfTilesProcessing,selected:tileset._statistics.numberOfTilesSelected,ready:tileset._statistics.numberOfTilesWithContentReady}:null}));
async function settle(label){await child.evaluate(()=>window.__settle813={earliest:Date.now()+1500,at:null});let settled=false;for(let i=0;i<2;i++){try{await child.waitForFunction(()=>{const s=window.__settle813;if(Date.now()<s.earliest||!window.__allLoaded||!tileset.tilesLoaded||!perf.tilesLoaded||ADAPT.moving){s.at=null;return false}if(!s.at)s.at=Date.now();return Date.now()-s.at>=1500},null,{timeout:60000});settled=true;break}catch{console.log(JSON.stringify({phase:label,waitSeconds:(i+1)*60,metrics:await metrics()}))}}const m=await metrics();settled=settled&&m.loaded&&m.tilesLoaded&&!m.adapt.moving;report[label]={settled,metrics:m};await page.screenshot({path:OUT+'/'+label+'.png'});console.log(JSON.stringify({phase:label,settled,metrics:m}));return settled}
check('wide touch context uses DPR2',await child.evaluate(()=>devicePixelRatio===2));check('wide Auto view reaches settled current-camera imagery',await settle('wide-auto-settled'));
await page.setViewportSize({width:390,height:844});await child.evaluate(()=>applyQuality());const loss=await child.evaluate(()=>{const ext=viewer.scene.context._gl.getExtension('WEBGL_lose_context');if(!ext)return false;ext.loseContext();return true});check('controlled actual contextloss available',loss);await child.waitForFunction(()=>window.__bootError==='context',null,{timeout:10000});
const hit=await child.evaluate(()=>{const b=document.getElementById('retry3d813'),r=b.getBoundingClientRect(),p=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {hit:p===b||b.contains(p),overlays:document.querySelectorAll('.cesium-widget-errorPanel').length,ready:window.__ready,error:window.__bootError,rendering:viewer.useDefaultRenderLoop}});check('Retry is actual hit target without a second error overlay',hit.hit&&hit.overlays===0,hit);check('lost graphics remains unready and stopped',!hit.ready&&!hit.rendering&&hit.error==='context');await page.screenshot({path:OUT+'/phone-recovery-hit.png'});
const roots=report.rootTileRequests,docs=report.childDocs;await child.locator('#retry3d813').click();await page.waitForFunction(()=>document.querySelector('#model3d')?.contentWindow?.__ready===true,null,{timeout:120000});child=page.frames().find(f=>f.url().includes('/poc3d/'));check('actual Retry click opens exactly one replacement session',report.rootTileRequests===roots+1&&report.childDocs===docs+1);check('replacement context resumes ready rendering',await child.evaluate(()=>GC500_3D.state.ready&&viewer.useDefaultRenderLoop));check('no operational writes',report.blockedWrites===0);check('no page exceptions',report.errors.length===0,report.errors);
report.finished=new Date().toISOString();report.passed=true;
})().catch(e=>{report.failure=safe(e.message);report.passed=false;console.error(report.failure);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();fs.writeFileSync(OUT+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.checks.length,passed:report.passed,blockedWrites:report.blockedWrites,errors:report.errors,rootTileRequests:report.rootTileRequests,childDocs:report.childDocs}));});
