// Author: Andrew Fisher. Production-function CPU fixtures; no network or credentials.
const fs=require('fs'),vm=require('vm'),crypto=require('crypto');const ROOT='/workspace/private-maps813/3d';
const html=fs.readFileSync(ROOT+'/candidate/poc3d/index.html','utf8'),merge=fs.readFileSync(ROOT+'/candidate/explorer-merge.js','utf8'),helper=fs.readFileSync('/workspace/gc500-showcase-full-lap/03_GC500_Delivery_Control/v8.13_maps_satellite_DRAFT/satellite3d813_src.js','utf8');
const fn=(s,n)=>{const at=s.indexOf('function '+n+'(');if(at<0)throw Error(n);const lead=s===merge?'\n  function ':'\nfunction ';let end=s.indexOf(lead,at+1);return s.slice(at,end<0?s.length:end).replace(/^function/,'function');};
const checks=[];function check(n,v){checks.push({name:n,pass:!!v});if(!v)throw Error(n)}
const timers=new Map();let ti=0;const elems={};const el=id=>elems[id]||(elems[id]={hidden:true,textContent:'',disabled:false,classList:{add(){},remove(){}},addEventListener(){}});
const make=()=>{const e={},ts=new Map();let tid=0;const c={viewer:null,tileset:null,window:null,addEventListener(){},PHONE:true,LOWPOWER:true,EMBED3D:true,quality:'auto',qualityChosen:false,ADAPT:{},perf:{},PINS:[],orbit:0,graphicsLost813:false,Date,Promise,URLSearchParams,AbortController,location:{search:'',pathname:'/fixture',reload(){c.reloads++}},reloads:0,performance:{now:()=>1},setTimeout:(f,ms)=>{const id=++tid;ts.set(id,{f,ms});return id},clearTimeout:id=>ts.delete(id),setInterval(){},$:id=>e[id]||(e[id]={hidden:true,disabled:false,textContent:'',classList:{add(){},remove(){}},addEventListener(){}}),document:{querySelectorAll:()=>[],addEventListener(){}},stopOrbit(){c.orbitStops++},stopFace(){c.faceStops++},orbitStops:0,faceStops:0,applyQuality(){},fly(){},updateCompass(){},adaptFrame(){},scheduleHeights(){},setStatus(){},loadPins:async()=>{},search(){},perfText(){},key:async()=>{c.keys++;return 'fixture-key'},keys:0};c.window=c;c.parent={gc500Explorer3DReady813(){c.readyCalls++}};c.readyCalls=0;c.cancelFlights=0;c.events={};c.tilesCalls=0;c.destroyed=0;
const event={addEventListener(){}};c.tile={tileFailed:event,tileLoad:event,allTilesLoaded:event,loadProgress:event,destroy(){c.destroyed++}};
c.Cesium={Viewer:function(){return{useDefaultRenderLoop:true,canvas:{addEventListener:(k,f)=>c.events[k]=f},scene:{globe:{},skyAtmosphere:{},fog:{},postProcessStages:{fxaa:{}},screenSpaceCameraController:{},primitives:{add(){}},postRender:event,renderError:event,requestRender(){}},camera:{changed:event,cancelFlight(){c.cancelFlights++}}}},Cesium3DTileset:{fromUrl:async()=>{c.tilesCalls++;return c.tile}},Color:{fromCssColorString:()=>({})},ScreenSpaceEventHandler:function(){this.setInputAction=()=>{}},ScreenSpaceEventType:{LEFT_CLICK:1}};
vm.createContext(c);vm.runInContext(helper,c);vm.runInContext('async '+fn(html,'boot'),c);return{c,e,ts};};
(async()=>{
let q=make();q.c.Cesium=undefined;await q.c.boot();check('missing library classified without map request',q.c.__bootError==='library'&&q.c.keys===0);check('missing library exposes manual Retry',q.e.retry3d813.hidden===false&&q.c.reloads===0);
q=make();q.c.key=async()=>{throw Error('fixture')};await q.c.boot();check('access failure classified and no automatic retry',q.c.__bootError==='access'&&q.c.reloads===0);q.e.retry3d813.onclick();check('one explicit Retry reloads once',q.c.reloads===1&&q.e.retry3d813.disabled);
q=make();q.c.Cesium.Viewer=function(){throw Error('fixture unsupported graphics')};await q.c.boot();check('graphics unavailable differs from network',q.c.__bootError==='graphics'&&q.e.loadText.textContent.includes('3D graphics'));
q=make();q.c.Cesium.Cesium3DTileset.fromUrl=async()=>{throw Error('fixture imagery error')};await q.c.boot();check('imagery failure retains useful network recovery',q.c.__bootError==='imagery'&&q.e.loadText.textContent.includes('imagery'));
q=make();let resolve; q.c.Cesium.Cesium3DTileset.fromUrl=()=>{q.c.tilesCalls++;return new Promise(r=>resolve=r)};const pending=q.c.boot();await new Promise(setImmediate);q.ts.forEach(x=>{if(x.ms===30000)x.f()});check('slow startup exposes recovery without reload',q.c.__bootError==='slow'&&q.c.reloads===0);resolve(q.c.tile);await pending;check('late success clears slow state and notifies parent',q.c.__ready===true&&q.c.__bootError===null&&q.c.readyCalls===1&&q.e.retry3d813.hidden);check('slow startup opened imagery only once',q.c.tilesCalls===1);
q=make();let resolveLost;q.c.Cesium.Cesium3DTileset.fromUrl=()=>new Promise(r=>resolveLost=r);const lost=q.c.boot();await new Promise(setImmediate);let prevented=false;q.c.events.webglcontextlost({preventDefault(){prevented=true}});resolveLost(q.c.tile);await lost;check('context loss during startup cannot be cleared by late imagery',q.c.__bootError==='context'&&!q.c.__ready&&q.c.destroyed===1&&prevented);check('context loss stops render loop pending explicit retry',q.c.viewer.useDefaultRenderLoop===false&&q.c.reloads===0);
q=make();await q.c.boot();q.c.events.webglcontextlost({preventDefault(){}});check('running context loss exposes Retry and stops flight',q.c.__bootError==='context'&&!q.e.retry3d813.hidden&&q.c.cancelFlights>0);check('terminal failure clears child readiness',q.c.__ready===false);
// Exact camera commands, not a rewritten model.
const site=Number(html.match(/const SITE_H = ([\d.]+)/)[1]),views=html.match(/const VIEWS = (\{[\s\S]*?\});/)[1];const c={SITE_H:site,VIEWS:vm.runInNewContext('('+views+')',{SITE_H:site}),stopMotion813(){c.stops++},stops:0,viewer:{camera:{flyTo:x=>c.last=x}},Cesium:{Cartesian3:{fromDegrees:(lon,lat,height)=>({lon,lat,height})},Math:{toRadians:x=>x*Math.PI/180},EasingFunction:{QUADRATIC_IN_OUT:0}},setStatus:s=>c.status=s,Math};vm.createContext(c);vm.runInContext(fn(html,'fly'),c);for(const [name,height]of[['ground',12],['street',45]]){c.fly(name,0);check(name+' camera is above measured local datum',Math.abs(c.last.destination.height-site-height)<1e-9);check(name+' label describes relative local height',c.status.includes('about '+height+' m above local ground'));}check('new preset takes over old motion',c.stops===2);
const unchanged=['overhead','angled','close','island','narrowneck','pits'];const original=fs.readFileSync('/workspace/private-maps813/live-source/poc3d/index.html','utf8');const oldViews=vm.runInNewContext('('+original.match(/const VIEWS = (\{[\s\S]*?\});/)[1]+')');check('all other camera presets unchanged',unchanged.every(n=>JSON.stringify(oldViews[n])===JSON.stringify(c.VIEWS[n])));check('ground and street coordinates/angles unchanged',['ground','street'].every(n=>['lon','lat','heading','pitch'].every(k=>oldViews[n][k]===c.VIEWS[n][k])));
for(const name of ['stillScale','applyRender','adaptFrame','tune','settle','applyQuality','pinPos','heightBatch']){if(name==='pinPos'){check('pin coordinate projection unchanged',html.includes('const pinPos = p => Cesium.Cartesian3.fromDegrees(p.ll[1], p.ll[0], pinH(p));'));continue}check(name+' policy unchanged',fn(original,name)===fn(html,name));}
// Native merge lifecycle with controllable timeout callbacks.
let created=0,next=0,loads,sets=0,syncs=0,stops=0;const active=new Map(),child={__ready:false,GC500_3D:{setPins(){sets++},stopMotion813(){stops++}}};const m={in3d:false,frame:null,ready3d:false,lastCode:null,window:null,document:{createElement(){created++;return{contentWindow:child,addEventListener:(event,cb)=>{if(event==='load')loads=cb}}},body:{classList:{add(){},remove(){}}}},$$:()=>({appendChild(){}}),URLSearchParams,location:{search:'',pathname:'/fixture'},localStorage:{setItem(){}},history:{replaceState(){}},Date,modeButtons:()=>[],pins3d:()=>[],sync3d(){syncs++},api3d:()=>child.GC500_3D,setTimeout:(f,ms)=>{const id=++next;active.set(id,{f,ms});return id},clearTimeout:id=>active.delete(id)};m.window=m;vm.createContext(m);vm.runInContext(merge.slice(merge.indexOf('let wait3dTimer813'),merge.indexOf('  function modeButtons')),m);for(const n of['enter3d','exit3d'])vm.runInContext(fn(merge,n),m);
check('no 3D iframe before activation',created===0);m.enter3d();loads();const stale=[...active.values()][0].f;loads();check('reload owns exactly one readiness poll',active.size===1);stale();check('superseded poll cannot set pins',sets===0&&active.size===1);child.__ready=true;m.gc500Explorer3DReady813(child);check('ready child receives pins once and clears poll',sets===1&&active.size===0&&m.ready3d);m.exit3d();check('leaving3D stops all camera motion',stops===1);m.enter3d();check('returning3D reuses successful session',created===1);child.__bootError='context';check('failed child cannot publish readiness',m.gc500Explorer3DReady813(child)===false);m.gc500Explorer3DFailed813(child);check('failure notification clears parent readiness',m.ready3d===false);check('unrelated frame cannot publish readiness',m.gc500Explorer3DReady813({__ready:true,GC500_3D:child.GC500_3D})===false);
const out={author:'Andrew Fisher',poc_sha256:crypto.createHash('sha256').update(html).digest('hex'),merge_sha256:crypto.createHash('sha256').update(merge).digest('hex'),checks};fs.writeFileSync(ROOT+'/cpu_checks.json',JSON.stringify(out,null,2));console.log(JSON.stringify({checks:checks.length,passed:checks.filter(c=>c.pass).length,poc:out.poc_sha256,merge:out.merge_sha256}));
})().catch(e=>{console.error(e.message);process.exitCode=1});
