// Author: Andrew Fisher. Exact 3D quality/access functions under bounded CPU fixtures.
const fs=require('fs'),vm=require('vm'),crypto=require('crypto');const file='/workspace/private-maps813/3d/candidate/poc3d/index.html',s=fs.readFileSync(file,'utf8'),checks=[];
const fn=n=>{const a=s.indexOf('function '+n+'('),b=s.indexOf('\nfunction ',a+1);return s.slice(a,b)};const check=(name,pass)=>{checks.push({name,pass});if(!pass)throw Error(name)};
const tiers=s.match(/const TIERS = (\{[\s\S]*?\});/)[1];
for(const dpr of [1,2,3])for(const quality of ['auto','crisp','light'])for(const moving of [false,true]){
 const c={quality,ADAPT:{moving,k:.6},orbit:0,window:{devicePixelRatio:dpr},TIERS:vm.runInNewContext('('+tiers+')',{LOWPOWER:true}),viewer:{canvas:{clientWidth:390,clientHeight:844},resolutionScale:1,scene:{requestRender(){}}},tileset:{},perfText(){},Math};vm.createContext(c);for(const n of ['cssPixels','stillScale','applyRender'])vm.runInContext(fn(n),c);c.applyRender();const res=c.viewer.resolutionScale*dpr;check('phone DPR'+dpr+' '+quality+' '+(moving?'moving':'still')+' density/detail bounded',res>0&&res<=Math.min(dpr,quality==='light'?1:quality==='auto'?2:3)+.025&&c.tileset.maximumScreenSpaceError===c.TIERS[quality][moving?'sseMove':'sse']);}
(async()=>{
let timer,cleared=0,calls=0;const c={location:{pathname:'/fixture'},AbortController,encodeURIComponent,setTimeout:(f,ms)=>{timer={f,ms};return 1},clearTimeout:()=>cleared++,fetch:async()=>{calls++;return {ok:false,json(){throw Error('must not read error response body')}}}};vm.createContext(c);vm.runInContext('async '+fn('key'),c);let rejected=false;try{await c.key()}catch{rejected=true}check('non-success map access is rejected and deadline cleaned',rejected&&cleared===1&&calls===1);
c.fetch=(url,opts)=>{calls++;return new Promise((resolve,reject)=>opts.signal.addEventListener('abort',()=>reject(Error('fixture timeout'))))};const p=c.key();check('map access has20second deadline',timer.ms===20000);timer.f();rejected=false;try{await p}catch{rejected=true}check('hung map access aborts without automatic retry',rejected&&cleared===2&&calls===2);
const out={author:'Andrew Fisher',poc_sha256:crypto.createHash('sha256').update(s).digest('hex'),checks};fs.writeFileSync('/workspace/private-maps813/3d/quality_access_checks.json',JSON.stringify(out,null,2));console.log(JSON.stringify({checks:checks.length,passed:checks.filter(x=>x.pass).length}));})().catch(e=>{console.error(e.message);process.exitCode=1});
