// Author: Andrew Fisher. Evaluated inside ui813_runner.cjs after immutable-source boot.
async function prove(id, run) {try {return await run();} catch(e) {return await check(id,false,{error:e.message});}}
async function fold(id) {if(!await frame.locator('#'+id).evaluate(e=>e.open))await frame.locator('#'+id+' > summary').click();}
async function controlProof() {
  await shot('initial'); await bounds('initial');
  await prove('search-local-card',async()=>{await search('WC31');const s=await selection();const drawer=await page.locator('#drawer').evaluate(e=>e.classList.contains('on'));await shot('wc31-selected');await check('search-local-card',s.selected==='WC31'&&s.cardVisible&&!drawer,{selection:s,drawer});});
  await prove('explicit-open-record',async()=>{await frame.locator('[data-xopen="WC31"]').click();const on=await page.locator('#drawer').evaluate(e=>e.classList.contains('on'));await check('explicit-open-record',on);await page.keyboard.press('Escape');});
  await prove('included-category-coherent',async()=>{await search('WC31');await menu();await fold('findCard');const cat=await frame.evaluate(()=>ITEMS.find(x=>x.code==='WC31').cat.id);await frame.locator('[data-cat="'+cat+'"]').click();const s=await selection();await check('included-category-coherent',s.selected==='WC31'&&s.cardVisible&&s.marks.includes('WC31'),s);});
  await prove('excluded-category-clears',async()=>{const cat=await frame.evaluate(()=>ITEMS.find(x=>x.code==='WC31').cat.id);await frame.locator('[data-cat]:not([data-cat="'+cat+'"])').first().click();const s=await selection();await check('excluded-category-clears',s.selected===null&&!s.cardVisible,s);await menu(false);});
  await prove('fit-clears-pick',async()=>{await search('WC31');await frame.locator('#fitBtn').click();const s=await selection();await check('fit-clears-pick',s.selected===null&&!s.cardVisible,s);});
  await prove('area-clears-pick',async()=>{await search('WC31');await menu();await fold('areas813');await frame.locator('[data-region="0"]').click();const s=await selection();await check('area-clears-pick',s.selected===null&&!s.cardVisible&&!s.menu,s);await shot('area');});
  await prove('unplaced-preserves-map',async()=>{const code=await frame.evaluate(()=>ITEMS.find(x=>!x.places.length)?.code||null);if(!code)return await check('unplaced-preserves-map',true,{notApplicable:'No unplaced reference in current source.'});const before=await frame.evaluate(()=>GC500Explorer.state.view);await search(code);const s=await selection(),after=await frame.evaluate(()=>GC500Explorer.state.view);await check('unplaced-preserves-map',s.selected===code&&s.cardVisible&&JSON.stringify(before)===JSON.stringify(after)&&/no place on the master plan/i.test(s.cardText),{code,selection:s,before,after});});
  await prove('drawing-result-zero',async()=>{await menu();await frame.locator('#q').fill('WC');const mixed=await frame.locator('#results [data-code]').count(),n=await frame.locator('#results [data-result="0"]').count();if(!n)return await check('drawing-result-zero',false,{reason:'No raw WC result available to exercise mixed search.'});const expected=await frame.evaluate(()=>lastSearch[0].r.slice(1));await frame.locator('#results [data-result="0"]').click();const s=await selection(),actual=await frame.evaluate(()=>highlight);await check('drawing-result-zero',mixed>0&&s.selected===null&&JSON.stringify(actual)===JSON.stringify(expected),{mixed,expected,actual,selection:s});});
  await prove('sources-open-close-focus',async()=>{await menu();await fold('about813');await frame.locator('#legendBtn').click();await shot('sources');const open=await frame.locator('#legend').evaluate(e=>e.classList.contains('show')),closedMenu=await frame.evaluate(()=>!matchMedia('(max-width:900px)').matches||!document.body.classList.contains('nav'));await frame.locator('[data-closelegend813]').first().click();const state=await frame.evaluate(()=>({closed:!document.querySelector('#legend').classList.contains('show'),focused:document.activeElement?.id}));await check('sources-open-close-focus',open&&closedMenu&&state.closed&&['navBtn','legendBtn'].includes(state.focused),state);});
  await prove('sources-escape',async()=>{await menu();await fold('about813');await frame.locator('#legendBtn').click();await page.keyboard.press('Escape');await check('sources-escape',await frame.locator('#legend').evaluate(e=>!e.classList.contains('show')));});
  await prove('input-escape-closes-menu',async()=>{await menu();await frame.locator('#q').fill('WC31');await frame.locator('#q').press('Escape');const s=await selection();await check('input-escape-closes-menu',!s.menu,s);});
  await prove('keyboard-zoom-pan',async()=>{await frame.locator('#stage').focus();const before=await frame.evaluate(()=>GC500Explorer.state);await page.keyboard.press('+');await page.waitForTimeout(450);const zoomed=await frame.evaluate(()=>GC500Explorer.state);await page.keyboard.press('ArrowRight');await page.waitForTimeout(300);const panned=await frame.evaluate(()=>GC500Explorer.state);await check('keyboard-zoom-pan',zoomed.zoom>before.zoom&&panned.view.x!==zoomed.view.x,{before:before.zoom,after:zoomed.zoom,panX:[zoomed.view.x,panned.view.x]});});
  await prove('native-fullscreen-toggle',async()=>{await frame.locator('#fullBtn').click();await page.waitForTimeout(300);const entered=await frame.evaluate(()=>!!document.fullscreenElement);await bounds('fullscreen');await frame.locator('#fullBtn').click();await page.waitForTimeout(300);await check('native-fullscreen-toggle',entered&&!await frame.evaluate(()=>!!document.fullscreenElement));});
  await prove('tab-reopen',async()=>{await page.locator('#tabs [data-tab="timeline"]').click();await page.locator('#tabs [data-tab="map"]').click();await page.waitForTimeout(500);frame=await(await page.$('#expFrame')).contentFrame();await frame.waitForFunction(()=>window.__ready,null,{timeout:30000});await bounds('reopen');await check('tab-reopen',await frame.evaluate(()=>GC500Explorer.state.ready));});
  await check('no-page-errors',session.errors.length===0,{errors:session.errors});
  await check('no-record-write-attempts',session.counts.blocked===0,{blocked:session.counts.blocked});
  save();return checks.filter(c=>c.device===device);
}
