// Author: Andrew Fisher. Final release financial capture; strict GET-only and exact supplied source hash.
const fs=require('fs'),path=require('path'),Module=require('module'),assert=require('assert/strict'),crypto=require('crypto');
const capture=process.env.CAPTURE;assert(/^[a-z0-9-]+$/.test(capture||''),'Safe CAPTURE filename required');
const root=process.env.OUTDIR;assert(root&&fs.statSync(root).isDirectory(),'Private OUTDIR required');const tool=path.resolve(__dirname,'../../toolchain/harness'),hp=tool+'/open_page.js';
const file=process.env.PAGE,expected=process.env.EXPECTED_SHA;assert(file&&/^[a-f0-9]{64}$/.test(expected||''),'PAGE and EXPECTED_SHA are required before browser capture');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),expected,'source changed before capture');
const fetcher=require(tool+'/curlfetch'),native=fetcher.curlFetch;let frozen=process.env.STATE?JSON.parse(fs.readFileSync(process.env.STATE,'utf8')):null;assert(frozen,'Frozen native STATE required for paired preservation capture');
fetcher.curlFetch=async(url,headers,method,body)=>{assert.equal(method,'GET');const u=new URL(url);if(frozen&&['/api/state','/api/version'].includes(u.pathname))return{status:200,headers:{'content-type':'application/json'},body:Buffer.from(JSON.stringify(u.pathname==='/api/state'?frozen:{version:frozen.version,updated:frozen.updated,level:'view'}))};const r=await native(url,headers,method,body);if(u.pathname==='/api/state'&&r.status===200){frozen=JSON.parse(r.body);fs.writeFileSync(root+'/'+capture+'-state.json',JSON.stringify(frozen,null,2))}return r};
const m=new Module(hp,module);m.filename=hp;m.paths=Module._nodeModulePaths(path.dirname(hp));let hs=fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;');hs=hs.replace('counts.blocked++; return route.abort();','counts.blocked++; (counts.blockedRequests || (counts.blockedRequests=[])).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname}); return route.abort();');hs=hs.replace('const okPost = false;', `if(r.method()==='POST'&&new URL(u).origin==='https://tile.googleapis.com'&&new URL(u).pathname==='/v1/createSession'){counts.localMapSessions=(counts.localMapSessions||0)+1;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({session:'local-readonly-fixture',expiry:String(Math.floor(Date.now()/1000)+600),tileWidth:256,tileHeight:256,imageFormat:'png'})});}
    if(r.method()==='GET'&&new URL(u).origin==='https://tile.googleapis.com'&&new URL(u).pathname.startsWith('/v1/2dtiles/'))return route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aPt8AAAAASUVORK5CYII=','base64')});
    const okPost = false;`);m._compile(hs,hp);
(async()=>{const h=await m.exports.open({pageFile:file,W:1440,H:1000,hash:'#costs'}),p=h.page,consoleErrors=[];p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});try{
 await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:150000});
 await p.evaluate(()=>photoIndex());await p.waitForFunction(()=>photoIndex().state==='ready',null,{timeout:60000});
 const r=await p.evaluate(()=>{RENDER_MEMO.clear();return holdAssets(()=>{const before=JSON.stringify(S),errors={},call=(name,fn)=>{try{return fn()}catch(e){errors[name]=String(e);return null}};const models={pl752:call('pl752Rows',()=>pl752Rows()),ticks:call('pl760Ticks',()=>pl760Ticks()),pl770:call('pl770Model',()=>pl770Model()),rehire:call('rh766Model',()=>rh766Model()),cj:call('cj764Model',()=>cj764Model()),finance:call('fh866Model',()=>fh866Model()),money:call('moneySummary',()=>moneySummary()),fenceSplit:call('fencePaidSplit',()=>fencePaidSplit()),fence:call('fenceDerived',()=>fenceDerived()),green:call('greenBookTotals',()=>greenBookTotals()),source949:call('Source949.model',()=>Source949.model()),supplierCosts:call('ourCosts',()=>ourCosts()),contracts:ONHIRE_ROWS,ties:typeof recon888Model==='function'?call('recon888Model',()=>recon888Model()):null,scope961:typeof supplierScope961==='function'?call('supplierScope961',()=>supplierScope961()):null};const assets=allAssets();
const preservation={
 embeddedData:DATA,
 assets:assets.map(a=>({asset:a,units:call('gcModel925 '+a.key,()=>gcModel925(a)),nativeUnits:call('unitsOf '+a.key,()=>unitsOf(a.key)),ownership:call('ItemOwnership969 '+a.key,()=>ItemOwnership969.read(a))})),
 today:call('todayWorkSummary848',()=>todayWorkSummary848(todayIso())),
 inventory:call('inventory',()=>inventory()),
 ep:call('epInventory860',()=>epInventory860()),
 epSupply:call('epSupply870',()=>epSupply870()),
 sourceAliases:call('physicalCountAssets963',()=>physicalCountAssets963(assets)),
 destinations:assets.map(a=>({ref:a.key,where:whereText(a),destination:dest782(a),map:mapRefOf(a.key)})),
 dates:call('programmeDays',()=>programmeDays().map(d=>({iso:d.iso,deliveries:d.deliveries.map(r=>r.a.key),removals:d.removals.map(r=>r.a.key),unref:d.unref.map(r=>r.task_id)}))),
 referenceRows:call('Reference966.rows',()=>Reference966.rows()),
 sourceLinks12Nov:call('Reference966.sourceLinksForDay',()=>Reference966.sourceLinksForDay('2026-11-12')),
 unresolvedLocations:call('Reference966.unresolvedLocations',()=>Reference966.unresolvedLocations())
};
return {author:'Andrew Fisher',record:S,recordUnchanged:before===JSON.stringify(S),cacheCleared:true,photoIndexReady:photoIndex().state==='ready',sync:{status:SYNC.status,first:SYNC.first.size,expected:Object.keys(SYNC_COLLS).length},models,preservation,errors}})});
 r.nativeVersion=frozen.version;r.sha256=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');r.pageErrors=h.errors;r.consoleErrors=consoleErrors;r.blockedRequests=h.counts.blockedRequests||[];r.localMapSessionFixtures=h.counts.localMapSessions||0;
 fs.writeFileSync(root+'/'+capture+'.json',JSON.stringify(r,null,2));
 const cents=n=>Math.round(n*100),x=r.models,checks={allModelCallsPass:Object.keys(r.errors).length===0,recordUnchanged:r.recordUnchanged,sourceHash:r.sha256===expected,fenceSupplierSplit:x.fenceSplit&&cents(x.fenceSplit.gear+x.fenceSplit.docket_labour)===cents(x.fence.cost),installationSplit:x.fenceSplit&&cents(x.fenceSplit.installation)===cents(x.fenceSplit.docket_labour+x.green.amount),financeCostCheck:x.finance?.costCheck,financeInvoiceCheck:x.finance?.invCheck,pageErrors:h.errors.length===0,blockedWrites:h.counts.blocked===0};
 const summary={author:'Andrew Fisher',nativeVersion:r.nativeVersion,sha256:r.sha256,checks,modelErrors:r.errors,pageErrors:r.pageErrors,consoleErrors,blockedRequests:r.blockedRequests};fs.writeFileSync(root+'/'+capture+'-summary.json',JSON.stringify(summary,null,2));console.log(JSON.stringify({author:'Andrew Fisher',nativeVersion:r.nativeVersion,sha256:r.sha256,pass:checks.allModelCallsPass&&checks.recordUnchanged&&checks.sourceHash&&checks.fenceSupplierSplit&&checks.installationSplit&&checks.pageErrors&&checks.blockedWrites,modelErrorCount:Object.keys(r.errors).length,pageErrorCount:r.pageErrors.length,consoleErrorCount:consoleErrors.length,blockedRequestCount:r.blockedRequests.length,privateSnapshot:root+'/'+capture+'.json'}));
 assert(checks.allModelCallsPass&&checks.recordUnchanged&&checks.sourceHash&&checks.fenceSupplierSplit&&checks.installationSplit&&checks.pageErrors&&checks.blockedWrites&&consoleErrors.length===0);if(process.env.EXPECTED_RECORD)assert.equal(String(r.nativeVersion),process.env.EXPECTED_RECORD);
}finally{await h.browser.close()}})().catch(e=>{console.error(e.stack);process.exit(1)});
