// Author: Andrew Fisher. Phone source reconciliation checks, local candidate or unchanged actual public page.
// PUBLIC=1 EXPECTED_SHA=... OUT_DIR=/private/output CAPTURE=public973 node tests/questions_ui973.cjs
// Local: PAGE=... STATE=... EXPECTED_RECORD=5168 with the same EXPECTED_SHA and output variables.
const fs=require('fs'),path=require('path'),Module=require('module'),assert=require('assert/strict'),crypto=require('crypto');
const capture=process.env.CAPTURE;assert(/^[a-z0-9-]+$/.test(capture||''),'Safe CAPTURE filename required');
const root=process.env.OUT_DIR||'/tmp/gc500-questions973',publicPage=process.env.PUBLIC==='1',tool=path.resolve(__dirname,'../../toolchain/harness'),hp=tool+'/open_page.js';fs.mkdirSync(root,{recursive:true});
const file=publicPage?undefined:process.env.PAGE,expected=process.env.EXPECTED_SHA;assert(/^[a-f0-9]{64}$/.test(expected||''),'EXPECTED_SHA is required');if(!publicPage){assert(file,'PAGE is required for a local candidate');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),expected,'source changed before capture');}else assert(!process.env.STATE,'PUBLIC mode forbids a supplied state fixture');
const fetcher=require(tool+'/curlfetch'),native=fetcher.curlFetch;let frozen=!publicPage&&process.env.STATE?JSON.parse(fs.readFileSync(process.env.STATE,'utf8')):null;
fetcher.curlFetch=async(url,headers,method,body)=>{assert.equal(method,'GET');const u=new URL(url);if(!publicPage&&frozen&&['/api/state','/api/version'].includes(u.pathname))return{status:200,headers:{'content-type':'application/json'},body:Buffer.from(JSON.stringify(u.pathname==='/api/state'?frozen:{version:frozen.version,updated:frozen.updated,level:'view'}))};const r=await native(url,headers,method,body);if(publicPage&&/^\/v\/Coates-GC500-2026\/?$/.test(u.pathname))assert.equal(crypto.createHash('sha256').update(r.body).digest('hex'),expected,'Actual public page differs from released candidate');if(u.pathname==='/api/state'&&r.status===200){frozen=JSON.parse(r.body);fs.writeFileSync(root+'/'+capture+'-state.json',JSON.stringify(frozen,null,2))}return r};
const m=new Module(hp,module);m.filename=hp;m.paths=Module._nodeModulePaths(path.dirname(hp));let hs=fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;');hs=hs.replace('counts.blocked++; return route.abort();','counts.blocked++; (counts.blockedRequests || (counts.blockedRequests=[])).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname}); return route.abort();');hs=hs.replace('const okPost = false;', `if(r.method()==='POST'&&new URL(u).origin==='https://tile.googleapis.com'&&new URL(u).pathname==='/v1/createSession'){counts.localMapSessions=(counts.localMapSessions||0)+1;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({session:'local-readonly-fixture',expiry:String(Math.floor(Date.now()/1000)+600),tileWidth:256,tileHeight:256,imageFormat:'png'})});}
    if(r.method()==='GET'&&new URL(u).origin==='https://tile.googleapis.com'&&new URL(u).pathname.startsWith('/v1/2dtiles/'))return route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aPt8AAAAASUVORK5CYII=','base64')});
    const okPost = false;`);m._compile(hs,hp);
(async()=>{const h=await m.exports.open({pageFile:file,W:390,H:844,hash:'#questions'}),p=h.page,checks=[];try{
 await p.waitForFunction(()=>SYNC.status==='live'&&SYNC.first.size===Object.keys(SYNC_COLLS).length,null,{timeout:150000});await p.evaluate(()=>photoIndex());await p.waitForFunction(()=>photoIndex().state==='ready',null,{timeout:60000});
 const initial=await p.evaluate(()=>JSON.stringify(S));
 const q=await p.evaluate(()=>{RENDER_MEMO.clear();return holdAssets(()=>{const rows=questionsList(),history=questionHistory753(),a=assetOf('P36'),model=gcModel925(a);return {rows,context:Questions973.context(),identitiesContext:Identities973.context(a),model,open:rows.filter(x=>x.st==='open').length,pending:rows.filter(x=>x.st==='later').length,answered:history.filter(x=>x[1]==='done').length+rows.filter(x=>x.st==='done').length,fails:rows.fails||[]};});});
 fs.writeFileSync(root+'/'+capture+'-context.json',JSON.stringify(q,null,2));
 assert.equal(q.open,12);assert.equal(q.pending,5);assert.equal(q.answered,41);assert.equal(q.rows.find(x=>x.id==='sp-extra').st,'done');assert.equal(q.fails.length,0);checks.push('12 open, 5 pending and 41 answered/history');assert(q.context.p36);assert(q.context.offices);assert(q.context.loads);assert(q.context.staffing);const staff=q.rows.find(x=>x.id==='lb-miss-the-cost-of-the-people-on-the-event-labour-scope-who-are-not');assert.equal(staff.q,'Event staffing — remaining shifts and cost coverage');assert.equal(staff.rows.length,3);assert(staff.rows.some(r=>r.startsWith('Advanced fencing crew')));checks.push('All four intended source-evidence predicates and specific staffing remainder are active');
 assert.equal(q.model.rows.find(x=>x.assetNo==='1327222').physical,false);assert.equal(q.model.rows.find(x=>x.assetNo==='1327222').source,'history');assert.equal(q.model.rows.find(x=>x.assetNo==='1282487').physical,true);assert.equal(q.model.groups.find(x=>x.item==='Building 6m').units.length,1);checks.push('Current P36 building and retained planned history are distinct');
 await p.evaluate(()=>go('questions'));await p.waitForSelector('[data-question-id="sp-extra"][data-question-state="done"]',{state:'attached'});
 const folds=await p.evaluate(()=>{const pane=document.querySelector('#pane-questions'),history=pane.querySelector('details[data-qfold="history"]');return {historyClosed:!history.open,whyFolded:[...pane.querySelectorAll('.qwhy')].every(n=>n.parentElement.matches('details[data-qfold^="evidence967:"]')),historyContainsP36:!!history.querySelector('[data-question-id="sp-extra"]'),wide:document.documentElement.scrollWidth>window.innerWidth+1};});assert(folds.historyClosed&&folds.whyFolded&&folds.historyContainsP36&&!folds.wide);checks.push('Phone Questions keeps settled P36 in closed history with evidence folded');
 await p.screenshot({path:root+'/'+capture+'-questions-phone.png',fullPage:false});
 const persist=await p.evaluate(()=>{const key=document.querySelector('#pane-questions [data-qfold^="evidence967:"]').dataset.qfold;const find=()=>document.querySelector('[data-qfold="'+key+'"]');find().open=true;renderQuestions();const redraw=find().open;go('plant');go('questions');return {redraw,navigation:find().open};});assert(persist.redraw&&persist.navigation);checks.push('Question evidence disclosure survives redraw and navigation');
 await p.evaluate(()=>{go('plant');openAsset('P36');});await p.waitForSelector('#drawer [data-units925="P36"]',{state:'attached'});
 await p.evaluate(()=>{const select=document.querySelector('#drawer [data-unit925-description]');let fold=select.closest('details');while(fold){fold.open=true;fold=fold.parentElement.closest('details');}select.value='Building 6m';select.dispatchEvent(new Event('change',{bubbles:true}));});
 const ui=await p.evaluate(()=>{const box=document.querySelector('#drawer [data-units925="P36"]'),history=[...box.querySelectorAll('details')].find(d=>d.querySelector(':scope>summary')?.textContent.startsWith('Previously recorded items'));box.scrollIntoView({block:'start'});return {current:[...box.querySelectorAll(':scope>article .item933-number')].map(x=>x.textContent),history:history?.innerText||'',historyText:history?.textContent||'',historyClosed:history&&!history.open,all:box.textContent};});
 assert.deepEqual(ui.current,['1282487']);assert(ui.historyClosed&&ui.historyText.includes('1327222'));assert(ui.all.includes('1 identified')&&ui.all.includes('1 planned'));checks.push('Phone drawer shows one current building and the old allocation in closed history');
 await p.screenshot({path:root+'/'+capture+'-p36-phone.png',fullPage:false});
 const refs=await p.evaluate(()=>holdAssets(()=>['GN25','LT05','LT06'].map(ref=>{const a=assetOf(ref);return {ref,place:Reference973.sourcePlace(a),destination:dest782(a),point:aerialPointFor(a),noDrop:noDrop782(a),text:text747Where(a),way:text747WayIn(a)};})));
 for(const r of refs){assert(r.place&&r.place.exactPosition===false);assert.equal(r.destination,null);assert.equal(r.point,null);assert.equal(r.way,'');assert.equal(r.noDrop,false);assert(r.text.join(' ').includes(r.place.label));}checks.push('GN25/LT05/LT06 retain named sourced destinations without invented coordinates or pit-lane navigation');
 const referenceCounts=await p.evaluate(()=>holdAssets(()=>{const rows=Reference966.rows();return {rows:rows.length,linked:rows.filter(r=>r.linked).length,tasks:rows.filter(r=>!r.linked).length,remaining:Reference966.unresolvedLocations().length};}));assert.equal(referenceCounts.linked,31);assert.equal(referenceCounts.tasks,3);assert.equal(referenceCounts.remaining,8);checks.push('31 linked source rows, 3 source tasks, 8 specific remaining allocation facts');
 const document=await p.evaluate(()=>holdAssets(()=>{const d=docCollection().items.find(d=>d.id===Documents973.id);return {href:Documents973.href(),source:d};}));assert(document.href&&document.href.startsWith('/f/Coates-GC500-2026/'));assert.equal(document.source.sha256,'9ef1527d1fd9c6c7ea70dd3db3ced96784b0c1b32eba0df2aa3fb5ecd61be382');assert.equal(document.source.pages,17);const docResponse=await native('https://gc500-production.up.railway.app'+document.href,{},'GET');assert.equal(docResponse.status,200);assert.equal(crypto.createHash('sha256').update(docResponse.body).digest('hex'),'9ef1527d1fd9c6c7ea70dd3db3ced96784b0c1b32eba0df2aa3fb5ecd61be382');checks.push('Original 17-page VMS document publicly answers with the verified original bytes');
 assert.equal(await p.evaluate(()=>JSON.stringify(S)),initial);assert.equal(h.errors.length,0);assert.equal(h.counts.blocked,0);if(process.env.EXPECTED_RECORD)assert.equal(String(frozen.version),process.env.EXPECTED_RECORD);assert.equal(h.counts.page,publicPage?0:1);checks.push('Native record preserved and zero errors or operational writes');
 fs.writeFileSync(root+'/'+capture+'.json',JSON.stringify({author:'Andrew Fisher',sha256:expected,nativeVersion:frozen.version,checks,questions:q,folds,persist,ui,refs,referenceCounts,document,publicPage,errors:h.errors,blocked:h.counts.blocked},null,2));console.log(JSON.stringify({author:'Andrew Fisher',sha256:expected,nativeVersion:frozen.version,checks:checks.length,pass:true,output:root+'/'+capture+'.json'}));
}finally{await h.browser.close()}})().catch(e=>{console.error(e.stack);process.exit(1)});
