// Author: Andrew Fisher. Only evidenced allocation closes; source disagreements and missing rates stay visible.
'use strict';
const assert=require('assert/strict'),Q=require('../questions973.js');let checks=0;const check=(name,fn)=>{fn();checks++;};
const source=[{id:'sp-extra',q:'Allocation review',st:'open',why:'Original facts',need:'Original action',rows:['P36 Harry the Hirer: 2 numbers for 1 ordered']},{id:'oi-R10',st:'later',q:'Old date question'},{id:'oi-TX03',st:'open',q:'Old duplicate question'},...['br-norate-KINP','br-norate-NVAC','fe-quote','fe-closure','lb-rates','lb-nights-alfie-harris','oi-R30','ccb-classification753'].map(id=>({id,st:'open',q:id,need:'Still needed'}))];source.fails=['preserved failure'];
check('loading leaves all questions as they were',()=>assert.deepEqual(Q.project(source,{ready:false,p36:true,offices:true,loads:true}),source));
check('supported P36 closes with original question retained',()=>{const r=Q.project(source,{ready:true,p36:true}),p=r[0];assert.equal(p.st,'done');assert.equal(p.need,'');assert(p.original.includes('Original facts'));assert(p.why.includes('photographs'));assert(p.rows[0].includes('1327222'));assert.equal(source[0].st,'open');assert.equal(r.fails[0],source.fails[0]);});
check('lost evidence reopens from original live question',()=>assert.equal(Q.project(source,{ready:true,p36:false})[0].st,'open'));
check('unscoped question cannot be closed by unrelated P36 evidence',()=>{for(const rows of [undefined,[],['P37: two numbers']]){const q={id:'sp-extra',st:'open',q:'Future scope',rows};assert.deepEqual(Q.project([q],{ready:true,p36:true})[0],q);}});
check('other allocations are never closed along with P36',()=>{const s=source.map(q=>({...q}));s[0].rows=[...source[0].rows,'P37: two numbers'];const p=Q.project(s,{ready:true,p36:true})[0];assert.equal(p.st,'open');assert.deepEqual(p.rows,['P37: two numbers']);});
check('missing rates and other source conflicts retain exact fields',()=>{const out=Q.project(source,{ready:true,p36:true,offices:true,loads:true});for(let i=3;i<source.length;i++)assert.deepEqual(out[i],source[i]);});
check('office identity is settled but pickup remains pending',()=>{const q=Q.project(source,{ready:true,offices:true})[1];assert.equal(q.st,'later');assert(q.why.includes('Booked Pickup Date'));assert(q.why.includes('12 Nov'));assert(q.why.includes('13 Nov'));assert.equal(q.rows.length,2);assert.equal(q.need,'Confirm the transport pick-up date only.');});
check('changed office evidence retains previous question',()=>assert.deepEqual(Q.project(source,{ready:true,offices:false})[1],source[1]));
check('duplicate load links stay open and do not demand known unit sizes',()=>{const q=Q.project(source,{ready:true,loads:true})[2];assert.equal(q.st,'open');assert(q.why.includes('1097339'));assert(q.why.includes('1327220'));assert(q.why.includes('no trip or cost is removed'));assert(!q.need.includes('size'));});
check('changed load evidence retains original question',()=>assert.deepEqual(Q.project(source,{ready:true,loads:false})[2],source[2]));
const fs=require('fs'),vm=require('vm');
function runtime(){const assets={T0021:{key:'T0021',numbers:['960639']},T0022:{key:'T0022',numbers:['960634']}};const c={module:{exports:{}},DATA:{edition:'hosted',schedule_review950:{sha256:'485f5d885b88d836b63e85ad4062474a95a484022386efec7be62429f958edac'}},ONHIRE_ROWS:[{rental_contract:'9968929',line:1,asset_no:'960639',booked_pickup_date:'2026-11-13'},{rental_contract:'9968929',line:3,asset_no:'960634',booked_pickup_date:'2026-11-13'}],assetOf:ref=>assets[ref]||null,buildingNumbersOf:a=>a.numbers,Reference973:{officeLink:id=>({T0222:'T0021',T0223:'T0022'})[id]},S:{loads:{}},chargeLines:()=>[]};vm.runInNewContext(fs.readFileSync(require.resolve('../questions973.js'),'utf8'),c);return {c,assets,read:()=>c.module.exports.context()};}
check('current office source and identity both required',()=>assert.equal(runtime().read().offices,true));
check('later replacement wins even when demob reference remains linked',()=>{const x=runtime();x.assets.T0021.numbers=['999999'];assert.equal(x.read().offices,false);});
check('ambiguous office current identities reopen',()=>{const x=runtime();x.assets.T0022.numbers.push('999999');assert.equal(x.read().offices,false);});
check('new contract pickup date is not overwritten by source text',()=>{const x=runtime();x.c.ONHIRE_ROWS[0].booked_pickup_date='2026-11-12';assert.equal(x.read().offices,false);});
check('changed office demob association reopens',()=>{const x=runtime();x.c.Reference973.officeLink=()=>null;assert.equal(x.read().offices,false);});
function staffing(){const days=['2026-10-23','2026-10-24','2026-10-25'];return {spec:{placeholders:[{role:'Advanced fencing crew',people:6,hours:null},{role:'Night Manager / supervisor',people:1,hours:null}],unconfirmed:[{id:'W-P-kyle-gover',shiftIds:days.map(d=>'W-L-kyle-gover-'+d.replace(/-/g,''))}]},rows:['andrew-fisher','aaron-zelvis','jayden-paul','daniel-gough','frank-devilles','ludwig-chee'].flatMap(id=>days.map(date=>({id:'W-L-'+id+'-'+date.replace(/-/g,''),person:id,date,status:'forecast',paid:12,source:{start:'06:00',finish:'18:00',break_min:0}})))};}
check('verified active staffing narrows the question without claiming actual work',()=>{const x=staffing();assert(Q.staffingEvidence(x.spec,x.rows));const s=[{id:'lb-miss-the-cost-of-the-people-on-the-event-labour-scope-who-are-not',st:'open',q:'Old blanket question'}],q=Q.project(s,{ready:true,staffing:true})[0];assert.equal(q.st,'open');assert(q.why.includes('18 planned shifts'));assert(q.why.includes('Advanced'));assert.equal(q.rows.length,3);});
for(const [name,mutate]of [['hours changed',x=>x.rows[0].paid=11],['shift missing',x=>x.rows.pop()],['shift now actual',x=>x.rows[0].status='confirmed'],['duplicate shift',x=>x.rows[0]=x.rows[1]],['crew hours supplied',x=>x.spec.placeholders[0].hours=36],['night supervisor supplied',x=>x.spec.placeholders.splice(1,1)],['Kyle settled',x=>x.spec.unconfirmed=[]],['old Alfie roster replaced active Jayden',x=>x.rows.forEach(r=>{r.id=r.id.replace('jayden-paul','alfie-harris');r.person=r.person.replace('jayden-paul','alfie-harris');})]])check(name+' disables reviewed staffing wording',()=>{const x=staffing();mutate(x);assert.equal(Q.staffingEvidence(x.spec,x.rows),false);});
check('Kyle remains separately unconfirmed',()=>{const x=staffing();x.rows.push({id:'W-L-kyle-gover-20261023',date:'2026-10-23',person:'Kyle Gover',paid:10.5});assert(Q.staffingEvidence(x.spec,x.rows));});
console.log(JSON.stringify({author:'Andrew Fisher',checks,passed:checks}));
