// Author: Andrew Fisher. Native accessory description preservation; no service writes.
const fs=require('fs'),path=require('path'),Module=require('module'),assert=require('assert/strict');
const hp=path.resolve(__dirname,'../../toolchain/harness/open_page.js'),hm=new Module(hp,module);hm.filename=hp;hm.paths=Module._nodeModulePaths(path.dirname(hp));hm._compile(fs.readFileSync(hp,'utf8').replace(/const okPost = [^;]+;/,'const okPost = false;').replace('counts.blocked++;',"counts.blocked++; (counts.blockedPaths ||= []).push({method:r.method(),origin:new URL(u).origin,path:new URL(u).pathname});"),hp);const{open}=hm.exports;
const out=process.env.OUT925||'/workspace/private-units925-final927';fs.mkdirSync(out,{recursive:true});
(async()=>{const s=await open({pageFile:process.env.PAGE,hash:'#toilets',W:390,H:844,mobile:true});try{const p=s.page;await p.waitForFunction(()=>typeof SYNC!=='undefined'&&SYNC.status==='live'&&window.gcModel925,null,{timeout:180000});await p.evaluate(()=>docsRefresh(true));await p.waitForFunction(()=>DOCS.state==='ready',null,{timeout:60000});
const setup=await p.evaluate(()=>holdAssets(()=>{const a=assetOf('P03'),rows=gcModel925(a).rows,unit=rows.find(u=>u.item==='Fridge');if(!unit)throw Error('Recorded P03 fridge missing');window.__a925={record:JSON.stringify(S),unit,readonly:SYNC.readonly,capability,mayWrite,whoAmI,bump};SYNC.readonly=false;capability=()=> 'edit';openAsset('P03');const group=gcModel925(a).groups.find(g=>g.units.some(r=>r.id===unit.id));const select=document.querySelector('[data-unit925-description]');select.value=group.item;select.dispatchEvent(new Event('change',{bubbles:true}));SYNC.readonly=__a925.readonly;capability=__a925.capability;return{unitId:unit.id,item:unit.item,assetNo:unit.assetNo};}));
assert.equal(await p.locator('[data-unit925-description]').inputValue(),'Description to confirm');const unit=p.locator('[data-unit925-id]').filter({has:p.locator('b',{hasText:setup.assetNo})}).first();await unit.locator('summary').first().click();const edit=unit.locator('.units925-edit').first();await edit.locator('summary').first().click();const selected=await edit.locator('select[name="item"]').inputValue();assert.equal(selected,'Fridge');await edit.locator('select[name="item"]').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'phone-accessory-edit.png')});
const capture=await p.evaluate(()=>{const x=__a925,u=x.unit,a=holdAssets(()=>assetOf('P03')),before=JSON.stringify(S),moneyRead=()=>holdAssets(()=>JSON.stringify({M:moneySummary(),P:pl770Model(),R:recon888Model(),V:transport888View(),LP:labourPlan()})),money=moneyRead();try{mayWrite=()=>true;whoAmI=()=> 'Captured test fixture';bump=function(){};bump.kept=false;const r=unit925Save(a.key,{sourceKey:u.sourceKey,owner:u.owner==='unknown'?'coates':u.owner,assetNo:u.assetNo,label:u.label,item:u.item,branch:u.branch||''},'',Units925.token(null),u.sourceToken);if(!r.ok)throw Error(r.reason);const doc=S.loads[r.key],old=JSON.parse(before);return{saved:r.ok,localOnly:!r.kept,description:doc.item,nativeUnitsUnchanged:JSON.stringify(S.units)===JSON.stringify(old.units),countsUnchanged:JSON.stringify(S.supplied)===JSON.stringify(old.supplied),moneyUnchanged:money===moneyRead(),changed:Object.keys(S).filter(k=>JSON.stringify(S[k])!==JSON.stringify(old[k]))};}finally{S=JSON.parse(x.record);mayWrite=x.mayWrite;whoAmI=x.whoAmI;bump=x.bump;SYNC.readonly=x.readonly;capability=x.capability;applyCapability();}});
assert(capture.saved&&capture.localOnly&&capture.nativeUnitsUnchanged&&capture.countsUnchanged&&capture.moneyUnchanged);assert.equal(capture.description,'Fridge');assert(capture.changed.every(k=>['loads','stamps','by'].includes(k)));const restored=await p.evaluate(()=>JSON.stringify(S)===__a925.record);assert(restored);assert.equal(s.errors.length,0);assert((s.counts.blockedPaths||[]).every(x=>x.method==='POST'&&x.origin==='https://tile.googleapis.com'&&x.path==='/v1/createSession'));const result={pageSHA:require('crypto').createHash('sha256').update(fs.readFileSync(process.env.PAGE)).digest('hex'),selected,capture,recordRestored:restored,errors:s.errors,requests:s.counts};fs.writeFileSync(path.join(out,'accessory925.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await s.browser.close();}})().catch(e=>{console.error(e.stack);process.exitCode=1});
