// Author: Andrew Fisher. Native setter, guarded quantity ownership and preservation.
'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'quantity964.js'),'utf8');
const a={key:'WC09',product:'Toilet'},lines=[{item:'FWF',quantity:4},{item:'Pee Panel',quantity:6},{item:'Toilet Block 6m',quantity:2}],units=[{item:'FWF',physical:true,id:'fwf:0085',assetNo:'0085',owner:'event-portables'},{item:'Toilet Block 6m',physical:true,id:'block:1268858',assetNo:'1268858',owner:'coates'}];
const S={loads:{other:{kind:'unrelated',quantity:7}},supplied:{WC09:{items:[{asked:'Pee Panel',qty_supplied:6}]}},labour:{'WC09|Toilets & amenities|Pee Panel|install':true},stamps:{'supplied/WC09/Pee Panel':'2026-10-09T01:40:11.800Z','labour/WC09|Toilets & amenities|Pee Panel|install':'2026-10-09T07:10:00Z'},units:{WC09:{units:units}}};
let write=true,who='Andrew Fisher via Codex',saved=0,bumped=0,progress={quantity:6,arrived:6,done:6};const now='2026-10-09T07:20:00Z';
class FakeDate extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return Date.parse(now);}}
const box={S,Date:FakeDate,assetOf:k=>k==='WC09'?a:null,chargeLines:()=>lines,qtyOf:l=>l.quantity,movedAway:()=>false,gcModel925:()=>({rows:units}),deliveryAsOf:()=>({}),toiletItem962:()=>progress,todayIso:()=> '2026-10-09',isoIn:t=>new Date(Date.parse(t)+3600e4).toISOString().slice(0,10),mayWrite:()=>write,whoAmI:()=>who,stampIt:(c,k)=>{S.stamps[c+'/'+k]=now;},save:()=>saved++,bump:()=>{bumped++;saved++;},esc:v=>String(v).replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]))};
vm.createContext(box);vm.runInContext(source,box);let count=0;const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);count++;};const clone=x=>JSON.parse(JSON.stringify(x));const read=options=>box.quantitySubhire964Read('WC09','Pee Panel',options),key=box.quantitySubhire964Key('WC09','Pee Panel'),token=()=>box.quantitySubhire964Token('WC09','Pee Panel');
eq(read().valid,false,'missing ownership is not inferred from quote or receipt');
write=false;eq(box.quantitySubhire964Set('WC09','Pee Panel',6,'event-portables',token()).ok,false,'view capability cannot write');write=true;who='';eq(box.quantitySubhire964Set('WC09','Pee Panel',6,'event-portables',token()).ok,false,'named operator required');who='Andrew Fisher via Codex';
const before=clone(S);eq(box.quantitySubhire964Set('WC09','Pee Panel',6,'event-portables','stale').ok,false,'stale token fails');eq(JSON.stringify(S),JSON.stringify(before),'failed setters retain all records');
const result=box.quantitySubhire964Set('WC09','Pee Panel',6,'event-portables',token());eq(result.ok,true,'current named native setter succeeds');eq([saved,bumped],[1,1],'one save and bump');eq(key,'quantity-subhire964/WC09/Pee%20Panel','canonical item scoped key');eq(S.loads[key].by,who,'native recorder stored');eq(S.loads[key].source.quote,'Q6845','existing quote provenance stored');eq([read().row.quantity,read().row.received,read().row.installed],[6,6,6],'confirmed owner reads native quantities');
for(const field of ['supplied','labour','units'])eq(JSON.stringify(S[field]),JSON.stringify(before[field]),field+' unchanged');for(const [k,v] of Object.entries(before.stamps))eq(S.stamps[k],v,'existing stamp retained '+k);eq(S.loads.other.quantity,7,'other namespaced records untouched');
eq(box.quantitySubhire964Set('WC09','Pee Panel',6,'event-portables',token()).unchanged,true,'repeat confirmation idempotent');eq([saved,bumped],[1,1],'repeat does not duplicate writes');
progress={quantity:6,arrived:2,done:0};eq([read().row.received,read().row.installed],[2,0],'partial receipt never becomes six arrivals');progress={quantity:6,arrived:0,done:0};eq(read().row.received,0,'ownership does not prove arrival');progress={quantity:6,arrived:6,done:6};
const original=clone(S.loads[key]);
for(const patch of [{quantity:5},{quantity:6.5},{quantity:'6'},{owner:'coates'},{owner:'unknown'},{owner:'prem-air-hire'},{schema:2},{quantityOnly:false},{by:''},{at:'invalid'},{at:'2026-10-10T00:00:00Z'},{item:'FWF'},{active:false}]){S.loads[key]={...original,...patch};eq(read().valid,false,'malformed/drifted record withheld '+JSON.stringify(patch));}S.loads[key]=original;
S.loads.duplicate=clone(original);eq(read().valid,false,'duplicate quantity record fails closed');eq(box.quantitySubhire964Set('WC09','Pee Panel',6,'event-portables',token()).ok,false,'setter refuses duplicate peer');delete S.loads.duplicate;
const drift=clone(lines);drift.find(l=>l.item==='Pee Panel').quantity=7;eq(read({lines:drift}).valid,false,'schedule quantity drift withheld');eq(read({units:units.concat([{item:'Pee Panel',id:'new-physical',physical:true,source:'identified'}])}).valid,false,'new physical identities cannot double count');eq(read({units:units.concat([{item:'Pee Panel',id:'old-physical',physical:false,source:'history'}])}).valid,true,'archived history is not current stock');
for(const flag of ['_cancelled','relocation','rest_of','_movedTo','_locationMoved'])eq(read({asset:{...a,[flag]:true}}).valid,false,'inactive or moved item withheld '+flag);
eq(read({progress:{quantity:6,arrived:7,done:6}}).valid,false,'over-received quantity fails');eq(read({progress:{quantity:6,arrived:2,done:6}}).valid,false,'installation cannot exceed receipts');eq(read({day:'2026-10-08'}).valid,false,'ownership not projected before confirmation');
eq(box.quantitySubhire964List().rows.length,1,'one aggregate row, no invented identities');assert.match(box.quantitySubhire964Drawer('WC09','Pee Panel',progress),/SUB-HIRED · Event Portables/);count++;assert.match(box.quantitySubhire964CompanyHtml({owner:'event-portables',quantityOnly:[read().row]}),/Pee Panel ×6/);count++;
eq(box.quantitySubhire964Set('WC09','FWF',4,'event-portables',box.quantitySubhire964Token('WC09','FWF')).ok,false,'cannot mark adjacent FWF scope');eq(box.quantitySubhire964Set('WC09','Toilet Block 6m',2,'event-portables',box.quantitySubhire964Token('WC09','Toilet Block 6m')).ok,false,'cannot mark Coates blocks');
delete S.loads[key];box.bump=()=>{bumped++;saved++;box.bump.kept=false;};const local=box.quantitySubhire964Set('WC09','Pee Panel',6,'event-portables',token());eq(local.kept,false,'save warning propagates');assert.match(local.reason,/still on this device/);count++;
if(process.argv[2]){const html=fs.readFileSync(process.argv[2],'utf8'),start=html.indexOf('function companyModel925(){'),end=html.indexOf('let companyChoice925=',start);Object.assign(box,{allAssets:()=>[],subCompanies:()=>[]});vm.runInContext(html.slice(start,end),box);const cs=box.companyModel925();eq([cs.length,cs[0].units.length,cs[0].quantityOnly[0].quantity],[1,0,6],'company scope renders with quantity stock and no individual identities');}
console.log(JSON.stringify({author:'Andrew Fisher',checks:count,passed:true}));
