/* Author: Andrew Fisher. Generic money-label and source-allocation display checks; no private evidence. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const viewPath=require('node:path').resolve(process.argv[2]||require('node:path').join(__dirname,'../source/fencing-trace-view837.js')),view=require(viewPath),checks=[];
function check(id,fn){try{fn();checks.push({id,result:'pass'});}catch(e){checks.push({id,result:'fail',message:e.message});}}
const row=(money,book='red')=>({state:'current',book,key:'synthetic',docket_no:'N1',date:'2026-01-01',location:'Area A',activity:'additional_bracing',money,links:[],po:'S:PO-X'});
check('nothing-to-price-has-distinct-label',()=>{const html=view.rowHtml(row({supplier:null,revenue:null,supplier_state:'nothing to price',revenue_state:'nothing to price'}));assert.match(html,/No current priced lines/);assert.doesNotMatch(html,/Not priced|query open/);});
check('wholly-missing-rates-not-zero',()=>{const html=view.rowHtml(row({supplier:null,revenue:null,supplier_state:'partly priced',revenue_state:'partly priced'}));assert.match(html,/Not priced/);assert.doesNotMatch(html,/\$0\.00/);});
check('partial-subtotals-qualified',()=>{const html=view.rowHtml(row({supplier:80,revenue:120,supplier_state:'partly priced',revenue_state:'partly priced'}));assert.match(html,/\$80\.00/);assert.match(html,/\$120\.00/);assert.equal((html.match(/known subtotal; some rates missing/g)||[]).length,2);});
check('explicit-zero-displays-zero',()=>{const html=view.rowHtml(row({supplier:0,revenue:0,supplier_state:'priced',revenue_state:'priced'}));assert.equal((html.match(/\$0\.00/g)||[]).length,2);});
check('green-cost-not-revenue',()=>{const html=view.rowHtml(row({supplier:150,revenue:null,supplier_state:'Supplier labour estimate'},'green'));assert.match(html,/Cost only; no separate customer labour charge/);assert.doesNotMatch(html,/<dt>Customer Revenue/);});
check('collection-has-no-monetary-reversal',()=>{const html=view.rowHtml(row({supplier:null,revenue:null},'blue'));assert.match(html,/Collection counts only/);assert.match(html,/No automatic charge or credit/);assert.doesNotMatch(html,/\$0\.00/);});
const a=(label,cents,unallocated=false)=>({state:'current',label,amount_cents:cents,records:unallocated?[]:[{book:'red',record_id:'R1',docket_no:'N1'}],unallocated,note:'Supplier source basis',lines:[{category:'source line',quantity:1,unit:'each',amount_cents:cents}]});
check('matched-source-does-not-repeat-whole-po-value',()=>{const order={number:'PO-X',record_keys:['R1'],area_ids:['A'],amount:300,invoice_no:'INV-X'},group={state:'current',number:'PO-X',total_cents:30000,native_amount:300,native_match:true,allocations:[a('Area A',11000),a('Area B',14000),a('Unnumbered labour',5000,true)]};const html=view.orderHtml(order,group);assert.equal((html.match(/\$300\.00/g)||[]).length,1);assert.match(html,/matches recorded P\/O total/);assert.match(html,/not an addition to the P\/O or docket estimates/);assert.match(html,/Unnumbered source activity/);});
check('signed-credit-line-preserved',()=>{const x=a('Upgrade',1200);x.lines=[{category:'credit',quantity:-2,unit:'m',amount_cents:-2000},{category:'bracing',quantity:2,unit:'m',amount_cents:3200}];const html=view.allocationHtml(x);assert.match(html,/-\$20\.00/);assert.match(html,/\$32\.00/);assert.match(html,/\$12\.00/);});
check('unavailable-source-does-not-show-stale-amount',()=>{const html=view.allocationHtml({...a('Hidden old allocation',99900),state:'unavailable',reason:'Source changed'});assert.match(html,/needs review/);assert.doesNotMatch(html,/\$999\.00/);});
check('area-list-exposes-only-current-reviewed-work-and-escapes-labels',()=>{const trace={areas:[{id:'A',geometry_id:'pin-A',label:'Area <A>',state:'current'},{id:'B',geometry_id:'pin-B',label:'Stale area',state:'current'}],rows:[{state:'current',area_ids:['A']},{state:'unavailable',area_ids:['B']}]};const html=view.areas(trace);assert.match(html,/Recorded work by area \(1\)/);assert.match(html,/data-fmtrace-area="pin-A"/);assert.match(html,/Area &lt;A&gt;/);assert.doesNotMatch(html,/pin-B/);assert.equal(view.areas(trace,'nonmatching'),'');assert.match(view.areas(trace,'area'),/pin-A/);});
check('stale-work-retains-only-safe-independent-original-link',()=>{const html=view.rowHtml({state:'unavailable',key:'R',docket_no:'N',reason:'Quantity changed',links:[{kind:'original',label:'Original',url:'https://example.test/original.pdf'},{kind:'summary',label:'Stale summary',url:'https://example.test/summary.pdf'},{kind:'original',label:'Unsafe',url:'javascript:bad()'}]});assert.match(html,/original.pdf/);assert.doesNotMatch(html,/summary.pdf|javascript:/);});
check('unmapped-register-exposes-source-allocation-without-assigning-geometry',()=>{const key=JSON.stringify(['red','R1','N1']),allocation=a('Shared unmapped source work',11000),group={state:'current',number:'PO-X',total_cents:11000,native_match:true,allocations:[allocation]},trace={rows:[{key,state:'current',area_ids:[]}],orders:[{number:'PO-X',record_keys:[key],area_ids:[],amount:110}],commercial:{groups:[group],additional:[]}};const html=view.recordCommercial(trace,key);assert.match(html,/Supplier summary and shared P\/O/);assert.match(html,/Shared unmapped source work/);assert.match(html,/\$110\.00/);assert.match(html,/Payment not confirmed/);assert.doesNotMatch(html,/data-fmtrace-area|data-fence-trace-map/);assert.equal(view.recordCommercial(trace,'unrelated'),'');trace.rows[0].state='unavailable';assert.equal(view.recordCommercial(trace,key),'');});
check('unnumbered-residual-never-becomes-unmapped-docket-allocation',()=>{const key=JSON.stringify(['red','R2','N2']),group={state:'current',number:'PO-X',allocations:[a('Unnumbered source activity',5000,true)]},trace={rows:[{key,state:'current',area_ids:[]}],orders:[],commercial:{groups:[group],additional:[]}};assert.equal(view.recordCommercial(trace,key),'');});
const result={view_sha256:crypto.createHash('sha256').update(fs.readFileSync(viewPath)).digest('hex'),checks,passed:checks.filter(x=>x.result==='pass').length,failed:checks.filter(x=>x.result==='fail').length};if(process.argv[3])fs.writeFileSync(process.argv[3],JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({view_sha256:result.view_sha256,passed:result.passed,failed:result.failed,failures:checks.filter(x=>x.result==='fail')},null,2));process.exitCode=result.failed?1:0;
